=== ACME Intro


We’re using a company called ACME as an example. ACME is supposed to represent a typical customer environment.

Note: All scenarios and people are fictional, and any resemblance to any person living or dead is purely coincidental.

ACME has just been founded, and the business model is not finally defined yet. The current focus is to establish an e-commerce platform for various consumer goods. The web shop system is currently in the design phase and is not covered in this solution guide. Instead, we focus on setting up the required infrastructures and the systems and application management capabilities.

==== ACME IT Organization Overview


Because ACME is brand new, the IT Organization is still quite small. Nevertheless, ACME has decided to use a traditional approach to segregating tasks while structuring its IT departments.

Although ACME has additional departments, such as Human Resources, Legal, and Finance, we are focusing primarily on the following three main departments and their teams:

* IT Operations
* Software Development
* IT Services Management

The *IT Operations* department is taking care of all data-center management tasks and owns the entire *production environment*. They build and oversee all* infrastructure layers,* including computing (both physical and virtual), storage and network resources. These responsibilities include monitoring, incident management and backup / restore as well. In addition, they are responsible for all *operating-system*-related items, including OS upgrades and security patching.

The *Software Development Department* *creates custom software* and integrates it with 3rd-party software components. Their responsibilities include all application-specific *building and testing activities* and *configuration management*.

*IT Services Management *is responsible for all *architecture and process areas* in IT. These include Service Validation and Testing (QA), Release Management, and Security Management as the key processes. This department also acts as a *bridge* between Business and IT and between IT Operations and Software Development. To be better prepared for the future, it recently founded an *Emerging Technologies (ET) Department *to investigate upcoming trends and technologies early.

The following organization chart illustrates current ACME IT Organization structure:




In Step 8 “Map your IT Organization and Roles,” we will pick some typical roles and explain how they could be mapped and configured in Red Hat Satellite 6. Only a few departments and corresponding roles are covered inside this solution guide, but we will extend this coverage step by step in upcoming documents.

==== ACME Datacenter Topology Overview


ACME is based in Munich, Germany. The primary datacenter is in Munich as well. This datacenter has a segregated network that is used for frontend servers, which are available to the World Wide Web. Most of the infrastructure services are running in Munich, where the entire IT operations organization is based as well.

Only the web application development and testing are based in Boston, MA, in the United States. Both locations run small datacenters. Munich uses Red Hat Enterprise Virtualization as the underlying virtualization platform; in contrast, Boston uses the Red Hat Enterprise Linux OpenStack Platform.

The following diagram illustrates the datacenter topology, which is described in further detail in Step 2:


==== ACME Application Architecture Overview


Since our ACME company has just been founded and the business model is still evolving, we currently have only one business application: *ACME Website,* which is the public web presence of ACME.

A second business application is currently in the design phase: the ACME Webshop. The ACME website is based on the famous WordPress application, but the ACME webshop will become a JEE app running on top of JBoss Enterprise Application Server. Both are using MariaDB as database backend. To achieve a higher degree of standardization, ACME has decided to use a standardized MariaDB configuration as shared component.

Besides these business applications, there are a lot of infrastructure services required and documented in this solution guide. Primarily, the following infrastructure services are in-scope for this document and are (at least partially) documented as well:

* the server type, *git server,* which hosts a shared revision control system (e.g., for centrally managed Puppet configurations)
* the dedicated “*Docker*” *computing resources,* which act as container hosts
* the server type, *log host, * which acts as a central remote log server
* the server type, *Satellite 6 Capsule,* as used in our different locations
* (a *standard server* (plain OS) that is just providing a core build)

The following diagram illustrates the sample application architecture used in this solution guide:




We are also using some pre-existing systems:

* Red Hat Enterprise Virtualization as the underlying virtualization platform
* Red Hat Enterprise Linux OpenStack Platform as the virtualization platform used in the second location (Boston, US)
* a Zabbix monitoring server
