[id='configuring-capsule-server-with-default-ssl-certificates-for-load-balancing-with-puppet']
= Configuring {SmartProxyServer} with Default SSL Certificates for Load Balancing with Puppet

The following section describes how to configure {SmartProxyServer}s that use default SSL certificates for load balancing with Puppet.

If you use Puppet in your {Project} configuration, you must complete the following procedures:

. xref:configuring-capsule-server-to-generate-and-sign-puppet-certificates-default-certs[]

. xref:configuring-remaining-capsule-servers-for-load-balancing-default-certs[]

[id='configuring-capsule-server-to-generate-and-sign-puppet-certificates-default-certs']
.Configuring {SmartProxyServer} to Generate and Sign Puppet Certificates

Complete this procedure only for the system where you want to configure {SmartProxyServer} to generate and sign Puppet certificates for all other {SmartProxyServer}s that you configure for load balancing.
In the examples in this procedure, the FQDN of this {SmartProxyServer} is `{smart-proxy-context}-ca.example.com`.

. On {ProjectServer}, generate Katello certificates for the system where you configure {SmartProxyServer} to generate and sign Puppet certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {certs-generate} \
--foreman-proxy-fqdn _{smart-proxy-context}-ca.example.com_ \
--certs-tar "/root/_{smart-proxy-context}-ca.example.com_-certs.tar" \
--foreman-proxy-cname _loadbalancer.example.com_
----
+
Retain a copy of the example `{foreman-installer}` command that is output by the `{certs-generate}` command for installing {SmartProxyServer} certificate.

. Copy the certificate archive file from {ProjectServer} to {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp /root/_{smart-proxy-context}-ca.example.com_-certs.tar \
root@_{smart-proxy-context}-ca.example.com_:__{smart-proxy-context}-ca.example.com__-certs.tar
----

. Append the following options to the `{foreman-installer}` command that you obtain from the output of the `{certs-generate}` command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
--certs-cname "_loadbalancer.example.com_" \
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "true" \
--puppet-server-ca "true" \
--enable-foreman-proxy-plugin-remote-execution-ssh
----

. On {SmartProxyServer}, enter the `{foreman-installer}` command, for example:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {installer-scenario-smartproxy} \
--foreman-proxy-register-in-foreman "true" \
--foreman-proxy-foreman-base-url "_https://{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-oauth-consumer-key "_oauth key_" \
--foreman-proxy-oauth-consumer-secret "_oauth secret_" \
--certs-tar-file "_{smart-proxy-context}-ca.example.com-certs.tar_" \
--puppet-server-foreman-url "_https://{foreman-example-com}_" \
--certs-cname "_loadbalancer.example.com_" \
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "true" \
--puppet-server-ca "true" \
--enable-foreman-proxy-plugin-remote-execution-ssh
----

. On {SmartProxyServer}, stop the Puppet server:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet resource service puppetserver ensure=stopped
----
+
. Generate Puppet certificates for all other {SmartProxyServer}s that you configure for load balancing, except the first system where you configure Puppet certificates signing:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppetserver ca generate --certname _{smartproxy-example-com}_ \
--subject-alt-names _loadbalancer.example.com_ --ca-client
----
+
This command creates the following files on the system where you configure {SmartProxyServer} to sign Puppet certificates:
+
* `/etc/puppetlabs/puppet/ssl/certs/ca.pem`
* `/etc/puppetlabs/puppet/ssl/certs/_{smartproxy-example-com}_.pem`
* `/etc/puppetlabs/puppet/ssl/private_keys/_{smartproxy-example-com}_.pem`
* `/etc/puppetlabs/puppet/ssl/public_keys/_{smartproxy-example-com}_.pem`

. Resume the Puppet server:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet resource service puppetserver ensure=running
----


[id='configuring-remaining-capsule-servers-for-load-balancing-default-certs']
.Configuring Remaining {SmartProxyServer}s for Load Balancing

Complete this procedure on each {SmartProxyServer} excluding the system where you configure {SmartProxyServer} to sign Puppet certificates.

. On {ProjectServer}, generate Katello certificates for {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {certs-generate} \
--foreman-proxy-fqdn _{smartproxy-example-com}_ \
--certs-tar "/root/_{smartproxy-example-com}_-certs.tar" \
--foreman-proxy-cname _loadbalancer.example.com_
----
+
Retain a copy of the example `{foreman-installer}` command that is output by the `{certs-generate}` command for installing {SmartProxyServer} certificate.

. Copy the certificate archive file from {ProjectServer} to {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp /root/_{smartproxy-example-com}_-certs.tar \
root@_{smartproxy-example-com}_:__{smartproxy-example-com}__-certs.tar
----

. On {SmartProxyServer}, install the `puppetserver` package:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {package-install-project} puppetserver
----

. On {SmartProxyServer}, create directories for puppet certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /etc/puppetlabs/puppet/ssl/certs/ \
/etc/puppetlabs/puppet/ssl/private_keys/ \
/etc/puppetlabs/puppet/ssl/public_keys/
----

. On {SmartProxyServer}, copy the Puppet certificates for this {SmartProxyServer} from the system where you configure {SmartProxyServer} to sign Puppet certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/certs/ca.pem \
/etc/puppetlabs/puppet/ssl/certs/ca.pem
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/certs/_{smartproxy-example-com}_.pem \
/etc/puppetlabs/puppet/ssl/certs/_{smartproxy-example-com}_.pem
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/private_keys/_{smartproxy-example-com}_.pem \
/etc/puppetlabs/puppet/ssl/private_keys/_{smartproxy-example-com}_.pem
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/public_keys/_{smartproxy-example-com}_.pem \
/etc/puppetlabs/puppet/ssl/public_keys/_{smartproxy-example-com}_.pem
----

. On {SmartProxyServer}, change the directory ownership to user `puppet`, group `puppet` and set the SELinux contexts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# chown -R puppet:puppet /etc/puppetlabs/puppet/ssl/
# restorecon -Rv /etc/puppetlabs/puppet/ssl/
----

. Append the following options to the `{foreman-installer}` command that you obtain from the output of the `{certs-generate}` command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
--certs-cname "_loadbalancer.example.com_" \
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "false" \
--puppet-server-ca "false" \
--enable-foreman-proxy-plugin-remote-execution-ssh
----
. On {SmartProxyServer}, enter the `{foreman-installer}` command, for example:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {installer-scenario-smartproxy} \
--foreman-proxy-register-in-foreman "true" \
--foreman-proxy-foreman-base-url "_https://{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{smartproxy-example-com}_" \
--foreman-proxy-oauth-consumer-key "_oauth key_" \
--foreman-proxy-oauth-consumer-secret "_oauth secret_" \
--certs-tar-file "_{smartproxy-example-com}-certs.tar_" \
--puppet-server-foreman-url "_https://{foreman-example-com}_" \
--certs-cname "_loadbalancer.example.com_" \
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "false" \
--puppet-server-ca :false" \
--enable-foreman-proxy-plugin-remote-execution-ssh
----
