[id='configuring-capsule-server-with-custom-ssl-certificates-for-load-balancing-with-puppet']
= Configuring {SmartProxyServer} with Custom SSL Certificates for Load Balancing with Puppet

The following section describes how to configure {SmartProxyServer}s that use custom SSL certificates for load balancing with Puppet.

== Creating Custom SSL Certificates for {SmartProxyServer}

This procedure outlines how to create a configuration file for the Certificate Signing Request and include the load balancer and {SmartProxyServer} as Subject Alternative Names (SAN).
Complete this procedure on each {SmartProxyServer} that you want to configure for load balancing.

.Procedure

. On {SmartProxyServer}, create a directory to contain all the source certificate files, accessible to only the `root` user:
+
[options="nowrap", subs="+quotes,attributes"]
----
# mkdir /root/{smart-proxy-context}_cert
# cd /root/{smart-proxy-context}_cert
----

. Create a private key with which to sign the Certificate Signing Request (CSR).
+
Note that the private key must be unencrypted.
If you use a password-protected private key, remove the private key password.
+
If you already have a private key for this {SmartProxyServer}, skip this step.
+
[options="nowrap", subs="+quotes,attributes"]
----
# openssl genrsa -out /root/{smart-proxy-context}_cert/{smart-proxy-context}.pem 4096
----

. Create the certificate request configuration file with the following content:
+
[options="nowrap", subs="+quotes,attributes"]
----
[ req ]
default_bits       = 4096
distinguished_name = req_distinguished_name
req_extensions     = req_ext
prompt = no

[ req_distinguished_name ]
countryName=_2 Letter Country Code_
stateOrProvinceName=_State or Province Full Name_
localityName=_Locality Name_
0.organizationName=_Organization Name_
organizationalUnitName=_{SmartProxy} Organization Unit Name_
commonName=_{smartproxy-example-com}_  <1>
emailAddress=_Email Address_

[ req_ext ]
#authorityKeyIdentifier=keyid,issuer
#basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]                  <2>
DNS.1 = _loadbalancer.example.com_
DNS.2 = _{smartproxy-example-com}_
----
<1> The certificate's common name must match the FQDN of {SmartProxyServer}.
Ensure to change this when running the command on each {SmartProxyServer}.
You can also set a wildcard value `*`.
If you set a wildcard value, you must add the `-t {certs-proxy-context}` option when you use the `katello-certs-check` command.
<2> Under `[alt_names]`, include the FQDN of the load balancer as `DNS.1` and the FQDN of {SmartProxyServer} as `DNS.2`.

. Create a Certificate Signing Request (CSR) for the SAN certificate:
+
[options="nowrap", subs="+quotes,attributes"]
----
# openssl req -new \
-key /root/{smart-proxy-context}_cert/{smart-proxy-context}.pem \ <1>
-config SAN_config.cfg \          <2>
-out /root/{smart-proxy-context}_cert/{smart-proxy-context}.pem   <3>
----
<1> {SmartProxyServer}’s private key, used to sign the certificate
<2> The certificate request configuration file
<3> Certificate Signing Request file

. Send the certificate request to the Certificate Authority:
+
When you submit the request, specify the lifespan of the certificate.
The method for sending the certificate request varies, so consult the Certificate Authority for the preferred method.
In response to the request, you can expect to receive a Certificate Authority bundle and a signed certificate, in separate files.

. Copy the Certificate Authority bundle and {SmartProxyServer} certificate file that you receive from the Certificate Authority, and {SmartProxyServer} private key to your {ProjectServer} to validate them.

. On {ProjectServer}, validate {SmartProxyServer} certificate input files:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# katello-certs-check \
-c /root/{smart-proxy-context}_cert/{smart-proxy-context}.pem \      <1>
-k /root/{smart-proxy-context}_cert/{smart-proxy-context}.pem \      <2>
-b /root/{smart-proxy-context}_cert/ca_cert_bundle.pem <3>
----
<1> {SmartProxyServer} certificate file, provided by your Certificate Authority
<2> {SmartProxyServer}’s private key that you used to sign the certificate
<3> Certificate Authority bundle, provided by your Certificate Authority
+
+
If you set the `commonName=` to a wildcard value `*`, you must add the `-t {certs-proxy-context}` option to the `katello-certs-check` command.
+
Retain a copy of the example `{certs-generate}` command that is output by the `katello-certs-check` command for creating the Certificate Archive File for this {SmartProxyServer}.

== Configuring {SmartProxyServer} with Custom SSL Certificates for Load Balancing with Puppet

If you use Puppet in your {Project} configuration, then you must complete the following procedures:

. xref:configuring-capsule-server-to-generate-and-sign-puppet-certificates-custom-certs[]

. xref:configuring-remaining-capsule-servers-for-load-balancing-custom-certs[]

[id='configuring-capsule-server-to-generate-and-sign-puppet-certificates-custom-certs']
.Configuring {SmartProxyServer} to Generate and Sign Puppet Certificates


Complete this procedure only for the system where you want to configure {SmartProxyServer} to generate Puppet certificates for all other {SmartProxyServer}s that you configure for load balancing.
In the examples in this procedure, the FQDN of this {SmartProxyServer} is `{smart-proxy-context}-ca.example.com`.

. Append the following option to the `{certs-generate}` command that you obtain from the output of the `katello-certs-check` command:
+
[options="nowrap", subs="+quotes,attributes"]
----
--foreman-proxy-cname _loadbalancer.example.com_
----

. On {ProjectServer}, enter the `{certs-generate}` command to generate {SmartProxy} certificates.
For example:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {certs-generate} \
--foreman-proxy-fqdn _{smart-proxy-context}-ca.example.com_ \
--certs-tar /root/{smart-proxy-context}_cert/{smart-proxy-context}-ca.tar \
--server-cert /root/{smart-proxy-context}_cert/{smart-proxy-context}-ca.pem \
--server-key /root/{smart-proxy-context}_cert/{smart-proxy-context}-ca.pem \
--server-ca-cert /root/{smart-proxy-context}_cert/ca_cert_bundle.pem \
--foreman-proxy-cname _loadbalancer.example.com_
----
+
Retain a copy of the example `{foreman-installer}` command from the output for installing {SmartProxyServer} certificates.

. Copy the certificate archive file from {ProjectServer} to {SmartProxyServer}.

. Append the following options to the `{foreman-installer}` command that you obtain from the output of the `{certs-generate}` command:
+
[options="nowrap", subs="+quotes,attributes"]
----
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "true" \
--puppet-server-ca "true" \
--enable-foreman-proxy-plugin-remote-execution-script
----

. On {SmartProxyServer}, enter the `{foreman-installer}` command, for example:
+
[options="nowrap", subs="+quotes,attributes"]
----
{installer-scenario-smartproxy} \
--foreman-proxy-register-in-foreman "true" \
--foreman-proxy-foreman-base-url "_https://{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-oauth-consumer-key "oauth key" \
--foreman-proxy-oauth-consumer-secret "oauth secret" \
--certs-tar-file "_certs.tgz_" \
--puppet-server-foreman-url "_https://{foreman-example-com}_" \
--certs-cname "_loadbalancer.example.com_" \
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "true" \
--puppet-server-ca "true" \
--enable-foreman-proxy-plugin-remote-execution-script
----

. On {SmartProxyServer}, generate Puppet certificates for all other {SmartProxies} that you configure for load balancing, except this first system where you configure Puppet certificates signing:
+
[options="nowrap", subs="+quotes,attributes"]
----
# puppet cert generate _{smartproxy-example-com}_ \
--dns_alt_names=_loadbalancer.example.com_
----
+
This command creates the following files on the Puppet certificate signing {SmartProxyServer} instance:
+
* `/etc/puppetlabs/puppet/ssl/certs/ca.pem`
* `/etc/puppetlabs/puppet/ssl/certs/{smartproxy-example-com}.pem`
* `/etc/puppetlabs/puppet/ssl/private_keys/{smartproxy-example-com}.pem`
* `/etc/puppetlabs/puppet/ssl/public_keys/{smartproxy-example-com}.pem`

[id='configuring-remaining-capsule-servers-for-load-balancing-custom-certs']
.Configuring Remaining {SmartProxyServer}s for Load Balancing

Complete this procedure for each {SmartProxyServer} excluding the system where you configure {SmartProxyServer} to sign Puppet certificates.

. Append the following option to the `{certs-generate}` command that you obtain from the output of the `katello-certs-check` command:
+
[options="nowrap", subs="+quotes,attributes"]
----
--foreman-proxy-cname _loadbalancer.example.com_
----

. On {ProjectServer}, enter the `{certs-generate}` command to generate {SmartProxy} certificates.
For example:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {certs-generate} \
--foreman-proxy-fqdn _{smartproxy-example-com}_ \
--certs-tar /root/{smart-proxy-context}_cert/{smart-proxy-context}.tar \
--server-cert /root/{smart-proxy-context}_cert/{smart-proxy-context}.pem \
--server-key /root/{smart-proxy-context}_cert/{smart-proxy-context}.pem \
--server-ca-cert /root/{smart-proxy-context}_cert/ca_cert_bundle.pem \
--foreman-proxy-cname _loadbalancer.example.com_
----
+
Retain a copy of the example `{foreman-installer}` command from the output for installing {SmartProxyServer} certificates.

. Copy the certificate archive file from {ProjectServer} to {SmartProxyServer}.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp /root/_{smartproxy-example-com}_-certs.tar \
root@_{smartproxy-example-com}_:__{smartproxy-example-com}__-certs.tar
----

. On {SmartProxyServer}, install the `puppetserver` package:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {package-install-project} puppetserver
----

. On {SmartProxyServer}, create directories for puppet certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /etc/puppetlabs/puppet/ssl/certs/ \
/etc/puppetlabs/puppet/ssl/private_keys/ \
/etc/puppetlabs/puppet/ssl/public_keys/
----

. On {SmartProxyServer}, copy the Puppet certificates for this {SmartProxyServer} from the system where you configure {SmartProxyServer} to sign Puppet certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/certs/ca.pem \
/etc/puppetlabs/puppet/ssl/certs/ca.pem
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/certs/_{smartproxy-example-com}_.pem \
/etc/puppetlabs/puppet/ssl/certs/_{smartproxy-example-com}_.pem
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/private_keys/_{smartproxy-example-com}_.pem \
/etc/puppetlabs/puppet/ssl/private_keys/_{smartproxy-example-com}_.pem
# scp root@_{smart-proxy-context}-ca.example.com_:/etc/puppetlabs/puppet/ssl/public_keys/_{smartproxy-example-com}_.pem \
/etc/puppetlabs/puppet/ssl/public_keys/_{smartproxy-example-com}_.pem
----

. On {SmartProxyServer}, change the directory ownership to user `puppet`, group `puppet` and set the SELinux contexts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# chown -R puppet:puppet /etc/puppetlabs/puppet/ssl/
# restorecon -Rv /etc/puppetlabs/puppet/ssl/
----

. Append the following options to the `{foreman-installer}` command that you obtain from the output of the `{certs-generate}` command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
--certs-cname "_loadbalancer.example.com_" \
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "false" \
--puppet-server-ca "false" \
--enable-foreman-proxy-plugin-remote-execution-script
----

. On {SmartProxyServer}, enter the `{foreman-installer}` command, for example:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {installer-scenario-smartproxy} \
--foreman-proxy-register-in-foreman "true" \
--foreman-proxy-foreman-base-url "_https://{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{smartproxy-example-com}_" \
--foreman-proxy-oauth-consumer-key "_oauth key_" \
--foreman-proxy-oauth-consumer-secret "_oauth secret_" \
--certs-tar-file "_{smartproxy-example-com}-certs.tar_" \
--puppet-server-foreman-url "_https://{foreman-example-com}_" \
--certs-cname "_loadbalancer.example.com_" \
--puppet-dns-alt-names "_loadbalancer.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--foreman-proxy-puppetca "false" \
--puppet-server-ca "false" \
--enable-foreman-proxy-plugin-remote-execution-script
----
