[id='registering-clients']
= Registering Clients

You can register a client running a {RHEL} 6, 7, or 8 operating system to {SmartProxyServer}s that you configure for load balancing.
For more information about registering clients and configuring them to use Puppet, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in the _Managing Hosts_ guide.

To register clients, proceed to one of the following procedures:

* xref:registering-clients-using-the-host-registration[]
* xref:registering-clients-using-the-bootstrap-script[]
* xref:registering-clients-manually[]

[id='registering-clients-using-the-host-registration']
== {ProjectName} host registration

include::../common/modules/snip_host-registration-steps.adoc[]

[id='registering-clients-using-the-bootstrap-script']
== **(Deprecated)** Registering Clients Using the Bootstrap Script

To register clients, enter the following command on the client.
You must complete the registration procedure for each client.

.Prerequisite

Ensure that you install the bootstrap script on the client and change the script's file permissions to executable.
For more information, see {ManagingHostsDocURL}Registering_a_Host_Using_the_Bootstrap_Script_managing-hosts[Registering Hosts to {ProjectName} Using The Bootstrap Script] in the _Managing Hosts_ guide.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _loadbalancer.example.com_ \
--organization="_Your_Organization_" \
--location="_Your_Location_" \
--hostgroup="_Your_Hostgroup_" \
--activationkey=_your_activation_key_ \
--enablerepos={project-client-RHEL7-url} \
--puppet-ca-port 8141 \    <1>
--force                    <2>
----
<1> Include the `--puppet-ca-port 8141` option if you use Puppet.
<2> Include the `--force` option to register the client that has been previously registered to a standalone {SmartProxy}.


* On Red{nbsp}Hat Enterprise Linux 7, 6, or 5, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# python bootstrap.py --login=_admin_ \
--server _loadbalancer.example.com_ \
--organization="_Your_Organization_" \
--location="_Your_Location_" \
--hostgroup="_Your_Hostgroup_" \
--activationkey=_your_activation_key_ \
--enablerepos={project-client-RHEL7-url} \
--puppet-ca-port 8141 \    <1>
--force                    <2>
----
<1> Include the `--puppet-ca-port 8141` option if you use Puppet.
<2> Include the `--force` option to register the client that has been previously registered to a standalone {SmartProxy}.

The script prompts for the password corresponding to the {Project} user name you entered with the `--login` option.

[id='registering-clients-manually']
== **(Deprecated)** Registering Clients Manually with katello-ca-consumer rpm

To register clients manually, complete the following procedure on each client that you register.

.Procedure

. Remove the `katello-ca-consumer` package if it is installed:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# yum remove 'katello-ca-consumer*'
----

. Install the `katello-ca-consumer` package from the load balancer:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# rpm -Uvh \
http://_loadbalancer.example.com_/pub/katello-ca-consumer-latest.noarch.rpm
----

. Register the client and include the `--serverurl` and `--baseurl` options:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# subscription-manager register --org=_Your_Organization_ \
--activationkey=_Your_Activation_Key_ \
--serverurl=https://_loadbalancer.example.com_:8443/rhsm \
--baseurl=https://_loadbalancer.example.com_/pulp/content/
----
