[appendix]
[[Importing_Content_ISOs_into_Connected_Satellite]]
== Importing Content ISOs into a Connected {Project}

Even if {ProjectServer} can connect directly to the Red{nbsp}Hat Customer Portal, you can perform the initial synchronization from locally mounted content ISOs.
When the initial synchronization is completed from the content ISOs, you can switch back to downloading content through the network connection.
To accomplish this, download the Content ISOs for {ProjectName} from the Red{nbsp}Hat Customer Portal and import them into {ProjectServer}.
For locations with bandwidth limitations, using an *On Demand* download policy might be more efficient than downloading and importing Content ISOs.

Note that Content ISOs previously hosted at redhat.com for import into {ProjectServer} have been deprecated and will be removed in the next {Project} version.

[IMPORTANT]
You can only import content ISO images for Red{nbsp}Hat Enterprise Linux 8 because repodata checksum from CDN does not match the repodata checksum from the content ISO images for Red{nbsp}Hat Enterprise Linux 7 and lower.

Note that if you synchronize a Red{nbsp}Hat Enterprise Linux ISO, all minor versions of Red{nbsp}Hat Enterprise Linux also synchronize.
You require adequate storage on your {Project} to account for this.

[IMPORTANT]
This section is not required if your {ProjectServer} is connected to the Internet.

This example procedure performs the first synchronization of the Red{nbsp}Hat Enterprise Linux 8 repository from content ISO images.

.Procedure

. Log in to the Red Hat Customer Portal at https://access.redhat.com/.
. In the upper left of the window, click *Downloads* and select *Red Hat Satellite*.
. Click the Content ISOs tab.
This page lists all the products that are available in your subscription.
. Click the link for the product name, such as RHEL 8 (x86_64), to reveal links to download ISO images.
. Download the ISO images.
. On {Project}, create a directory to act as a temporary store for all of the required Satellite content ISO images.
This example uses `/tmp/isos/rhel8`:
+
----
# mkdir -p /tmp/isos/rhel8
----

. On your workstation, copy the ISO files to {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ scp ~/Downloads/_iso_file_ root@_{foreman-example-com}_:/tmp/isos/rhel8
----

. On {ProjectServer}, create a directory to serve as a mount point for the ISOs:
+
----
# mkdir /mnt/iso
----

. Create a working directory to store ISO images:
+
----
# mkdir /mnt/rhel8
----

. Temporarily mount the first ISO image:
+
[subs="+quotes"]
----
# mount -o loop /tmp/isos/_iso_file_ /mnt/iso
----

. Recursively copy the contents of the first ISO to the working directory:
+
----
# cp -ruv /mnt/iso/* /mnt/rhel8/
----

. Unmount the ISO image:
+
----
# umount /mnt/iso
----

. Repeat the above step for each ISO until you have copied all the data from the Content ISO images into `/mnt/rhel8`.

. If required, remove the empty directory used as the mount point:
+
----
# rmdir /mnt/iso
----

. If required, remove the temporary working directory and its contents to regain space:
+
----
# rm -rf /tmp/isos/
----

. Set the owner and the SELinux context for the directory and its contents to be the same as `/var/lib/pulp`:
+
----
# chcon -R --reference /var/lib/pulp  /mnt/rhel8/
# chown -R apache:apache /mnt/rhel8/
----

. Create or edit the `/etc/pulp/content/sources/conf.d/local.conf` file.
Append the following text into the file:
+
----
[rhel-8-server]
enabled: 1
priority: 0
expires: 3d
name: Red Hat Enterprise Linux 8
type: yum
base_url: file:///mnt/rhel8/content/dist/rhel/server/8/x86_64/os/
----
The `base_url` path might differ in your content ISO.
The directory specified in `base_url` must contain the `repodata` directory, otherwise the synchronization fails.
To synchronize multiple repositories, create a separate entry for each of them in the configuration file `/etc/pulp/content/sources/conf.d/local.conf`.

. In the {Project}, navigate to *Content* > *Red{nbsp}Hat Repositories* and enable the following repositories:
+
* *Red Hat Enterprise Linux 8 for x86_64 - BaseOS RPMs 8*
* *Red Hat Enterprise Linux 8 for x86_64 - AppStream RPMs 8*

. Under *Content* > *Sync Status* select the repositories to be synchronized and click *Synchronize Now*.

Note that the Satellite web UI does not indicate which source is being used.
In case of problems with a local source, Satellite pulls content through the network.
To monitor the process, enter the following command on Satellite:

----
# journalctl -f -l SYSLOG_IDENTIFIER=pulp | grep -v worker[\-,\.]heartbeat
----

The above command displays interactive logs.
First, {ProjectServer} connects to the Red{nbsp}Hat Customer Portal to download and process repository metadata.
Then, the local repository is loaded.
In case of any errors, cancel the synchronization in the {Project} web UI and verify your configuration.

After successful synchronization you can detach the local source by removing its entry from `/etc/pulp/content/sources/conf.d/local.conf`.
