[[Managing_Container_Authentication]]
= Managing Container Registry Authentication

By default, users must authenticate to access containers images in {Project}.

You can specify whether you want users to authenticate to access container images in {Project} in a lifecycle environment.
For example, you might want to permit users to access container images from the `Production` lifecycle without any authentication requirement and restrict access the `Development` and `QA` environments to authenticated users.

.Procedure

To manage the authentication settings for accessing containers images from {Project}, complete the following steps:

. In the {Project} web UI, navigate to *Content* > *Lifecycle Environments* and select the lifecycle environment that you want to manage authentication for.
. To permit unauthenticated access to the containers in this lifecycle environment, select the *Unauthenticated Pull* check box.
To restrict unauthenticated access, clear the *Unauthenticated Pull* check box.
. Click *Save*.
