[[Introduction]]
== Introduction

In the context of {ProjectX}, _content_ is defined as the software installed on systems. This includes, but is not limited to, the base operating system, middleware services, and end-user applications. With {ProjectNameX}, you can manage the various types of content for Red Hat Enterprise Linux systems at every stage of the software life cycle.

ifeval::["{build}" == "foreman"]
[IMPORTANT]
The Katello plug-in provides content management features to Foreman. You can only use this guide if you have the Katello plug-in installed.
endif::[]

{ProjectNameX} manages the following content:

Subscription management::
  This provides organizations with a method to manage their Red Hat subscription information.

Content management::
  This provides organizations with a method to store Red Hat content and organize it in various ways.


[[Introduction-Content_Type]]
=== Content Management Types Overview

With {ProjectNameX}, you can manage the following Red Hat content types:

RPM Packages::
  Import RPM files from repositories related to your Red Hat subscriptions. {ProjectServer} downloads the RPM files from Red Hat's Content Delivery Network and stores them locally. You can use these repositories and their RPM files in Content Views.

Kickstart Trees::
  Import the kickstart trees for creating a system. New systems access these kickstart trees over a network to use as base content for their installation. {ProjectNameX} also contains some predefined kickstart templates as well as the ability to create your own, which are used to provision systems and customize the installation.

You can also manage other types of {customcontent} in {Project}. For example:

ISO and KVM Images::
  Download and manage media for installation and provisioning. For example, {Project} downloads, stores and manages ISO images and guest images for specific Red Hat Enterprise Linux and non-Red Hat operating systems.

Puppet Modules::
  You can upload Puppet modules alongside RPM content so that Puppet can configure the system's state after provisioning. Users can also manage Puppet classes and parameters as part of the provisioning process.

OSTree::
  You can import OSTree branches and publish this content to an HTTP location.

You can use the procedure to add {customcontent} for any type of content you require, for example, SSL certificates and OVAL files.
