[[Managing_Custom_File_Type_Content]]
== Managing {customfiletypetitle} Content

In {Project}, you might require methods of managing and distributing SSH keys and source code files or larger files such as virtual machine images and ISO files.
To achieve this, (customproduct)s in {ProjectName} include repositories for {customfiletype}s.
This provides a generic method to incorporate arbitrary files in a product.

You can upload files to the repository and synchronize files from an upstream {ProjectServer}.
When you add files to a {customfiletype} repository, you can use the normal {Project} management functions such as adding a specific version to a Content View to provide version control and making the repository of files available on various {SmartProxyServer}s.
Clients must download the files over HTTP or HTTPS using `curl -O`.

You can create a file type repository in {ProjectServer} only in a (customproduct), but there is flexibility in how you create the file type repository.
You can create an independent file type repository in a directory on the system where {Project} is installed, or on a remote HTTP server, and then synchronize the contents of that directory into {Project}.
This method is useful when you have multiple files to add to a {Project} repository.

[[Importing_Content-Creating_a_Custom_File_Type_Repository]]
=== Creating a {customfiletypetitle} Repository in {ProjectName}

The procedure for creating a {customfiletype} repository is the same as the procedure for creating any {customcontent}, except that when you create the repository, you select the *file* type.
You must create a product and then add a {customrepo}.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-custom-file-type-repository_{context}[].

.Procedure

To create a {customproduct}, complete the following procedure:

. In the {ProjectWebUI}, navigate to *Content* > *Products*, click *Create Product* and enter the following details:
. In the *Name* field, enter a name for the product.
{Project} automatically completes the *Label* field based on what you have entered for *Name*.
. Optional: From the *GPG Key* list, select the GPG key for the product.
. Optional: From the *Sync Plan* list, select a synchronization plan for the product.
. In the *Description* field, enter a description of the product, and then click *Save*.

To create a repository for your {customproduct}, complete the following procedure:

. In the Products window, select the name of a product that you want to create a repository for.
. Click the *Repositories* tab, and then click *New Repository*.
. In the *Name* field, enter a name for the repository.
{Project} automatically completes the *Label* field based on the name.
. From the *Type* list, select *file*.
. In the *Upstream URL* field, enter the URL of the upstream repository to use as a source.
. Select the *Verify SSL* check box if you want to verify that the upstream repository's SSL certificates are signed by a trusted CA.
. In the *Upstream Username* field, enter the user name for the upstream repository if required for authentication.
Clear this field if the repository does not require authentication.
. In the *Upstream Password* field, enter the corresponding password for the upstream repository.
Clear this field if the repository does not require authentication.
. Click *Save*.

[id="cli-creating-a-custom-file-type-repository_{context}"]
.CLI procedure

. Create a {customproduct}
+
[options="nowrap" subs="+quotes"]
----
# hammer product create \
--name "_My File Product_" \
--sync-plan "_Example Plan_" \
--description "_My files_" \
--organization "_My_Organization_"
----
+
.Optional Parameters for the `hammer product create` Command
[width="50%",cols="<m1,<a3"]
|====
| *Option* | *Description*

| `--gpg-key` _gpg_key_name_          | Key name to search by
| `--gpg-key-id` _gpg_key_id_         | GPG key numeric identifier
| `--sync-plan` _sync_plan_name_      | Sync plan name to search by
| `--sync-plan-id` _sync_plan_id_     | Sync plan numeric identifier
|====


. Create a File Type Repository
+
[options="nowrap" subs="+quotes"]
----
# hammer repository create \
--name "My Files" \
--content-type "file" \
--product "My File Product" \
--organization "_My_Organization_"
----
+
.Optional Parameters for the `hammer repository create` Command
[width="80%",cols="<m1,<a3"]
|====
| *Option* | *Description*

| `--checksum-type` _sha_version_                 | Repository checksum, currently 'sha1' & 'sha256' are supported
| `--download-policy` _policy_name_       | Download policy for yum repos (either 'immediate' or 'on_demand').
| `--gpg-key` _gpg_key_name_                  | Key name to search by
| `--gpg-key-id` _gpg_key_id_                 | GPG key numeric identifier
| `--mirror-on-sync` _boolean_         | Must this repo be mirrored from the source, and stale RPMs removed, when synced? Set to `true` or `false`, `yes` or `no`, `1` or `0`.
| `--publish-via-http` _boolean_               | Must this also be published using HTTP? Set to `true` or `false`, `yes` or `no`, `1` or `0`.
| `--upstream-username` _repository_username_   | Upstream repository user, if required for authentication
| `--upstream-password` _repository_password_   | Password for the upstream repository user
| `--url` _source_repo_url_                                 | URL of the Source repository
| `--verify-ssl-on-sync` _boolean_   | Must Katello verify that the upstream URL's SSL certificates are signed by a trusted CA? Set to `true` or `false`, `yes` or `no`, `1` or `0`.
|====


[[Importing_Content-Creating_a_Custom_File_Type_Repository_Local_Directory]]
=== Creating a {customfiletypetitle} Repository in a Local Directory

You can create a {customfiletype} repository, from a directory of files, on the base system where {Project} is installed using the `pulp-manifest` command.
You can then synchronize the files into {ProjectServer}.
When you add files to a file type repository, you can work with the files as with any other repository.

Use this procedure to configure a repository in a directory on the base system where {Project} is installed.
To create a file type repository in a directory on a remote server, see xref:Managing_Custom_File_Type_Content-Creating_a_Remote_File_Type_Repository[].

.Procedure

To create a file type repository in a local directory, complete the following procedure:

. Ensure the Server and {project-client-name} repositories are enabled.
ifdef::satellite[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL7Server} \
--enable={project-client-RHEL7-url}
----
endif::[]

. Install the Pulp Manifest package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} python3-pulp-manifest
----
+
Note that this command stops the {Project} service and re-runs {foreman-installer}.
Alternatively, to prevent downtime caused by stopping the service, you can use the following:
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable {RepoRHEL7ServerSatelliteToolsProductVersion}
# {foreman-maintain} packages unlock
# yum install install python-pulp-manifest -y
# {foreman-maintain} packages lock
# subscription-manager repos --disable {RepoRHEL7ServerSatelliteToolsProductVersion}
----
This installs the package without downtime.
. Create a directory that you want to use as the file type repository in the HTTP server's public folder:
+
[options="nowrap" subs="+quotes"]
----
# mkdir __my_file_repo__
----
+
. Add files to the directory or create a test file:
+
[options="nowrap" subs="+quotes"]
----
# touch __my_file_repo__/_test.txt_
----
+
. Enter the Pulp Manifest command to create the manifest:
+
[options="nowrap" subs="+quotes"]
----
# pulp-manifest __my_file_repo__
----
+
. Verify the manifest was created:
+
[options="nowrap" subs="+quotes"]
----
# ls __my_file_repo__
PULP_MANIFEST test.txt
----

.Importing Files from a File Type Repository

To import files from a file type repository in a local directory, complete the following procedure:

. Ensure a {customproduct} exists in {ProjectServer}.
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select the name of a product.
. Click the *Repositories* tab and select *New Repository*.
. In the *Name* field, enter a name for the repository.
{Project} automatically completes this field based on what you enter for *Name*.
. From the *Type* list, select the content type of the repository.
. In the *Upstream URL* field, enter the local directory with the repository to use as the source, in the form `\file:///__my_file_repo__`.
. Select the *Verify SSL* check box to check the SSL certificate for the repository or clear the *Verify SSL* check box.
. Optional: In the *Upstream Username* field, enter the upstream user name that you require.
. Optional: In the *Upstream Password* field, enter the corresponding password for your upstream user name.
. Select *Save* to save this repository entry.

.Updating a File Type Repository

To update the file type repository, complete the following steps:

. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select the name of a product.
. Select the name of the repository you want to update.
. From the *Select Action* menu, select *Sync Now*.
. Visit the URL where the repository is published to see the files.

[[Managing_Custom_File_Type_Content-Creating_a_Remote_File_Type_Repository]]
=== Creating a Remote File Type Repository

You can create a {customfiletype} repository from a directory of files that is external to {ProjectServer} using the `pulp-manifest` command.
You can then synchronize the files into {ProjectServer} over HTTP or HTTPS.
When you add files to a file type repository, you can work with the files as with any other repository.

Use this procedure to configure a repository in a directory on a remote server.
To create a file type repository in a directory on the base system where {ProjectServer} is installed, see xref:Importing_Content-Creating_a_Custom_File_Type_Repository_Local_Directory[].

.Prerequisites

Before you create a remote file type repository, ensure the following conditions exist:

* You have a Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 server registered to your {Project} or the Red{nbsp}Hat CDN.
ifdef::satellite[]
* Your server has an entitlement to the Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}Server and {project-client-name} repositories.
endif::[]
* You have installed an HTTP server.
For more information about configuring a web server, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-web_servers#s1-The_Apache_HTTP_Server[The Apache HTTP Server] in the Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 _System Administrator's Guide_.

.Procedure

To create a file type repository in a remote directory, complete the following procedure:

. On your remote server, ensure that the Server and {project-client-name} repositories are enabled.
ifdef::satellite[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL7Server} \
--enable={project-client-RHEL7-url}
----
endif::[]
+
. Install the Pulp Manifest package:
+
[options="nowrap" subs="+quotes"]
----
# yum install python3-pulp-manifest
----
+
. Create a directory that you want to use as the file type repository in the HTTP server's public folder:
+
[options="nowrap" subs="+quotes"]
----
# mkdir /var/www/html/pub/__my_file_repo__
----
+
. Add files to the directory or create a test file:
+
[options="nowrap" subs="+quotes"]
----
# touch /var/www/html/pub/__my_file_repo/test.txt__
----
+
. Enter the Pulp Manifest command to create the manifest:
+
[options="nowrap" subs="+quotes"]
----
# pulp-manifest /var/www/html/pub/__my_file_repo__
----
+
. Verify the manifest was created:
+
[options="nowrap" subs="+quotes"]
----
# ls /var/www/html/pub/__my_file_repo__
PULP_MANIFEST test.txt
----

.Importing Files from a Remote a File Type Repository

To import files from a remote file type repository, complete the following procedure:

. Ensure a {customproduct} exists in {ProjectServer}, or create a {customproduct}.
For more information see xref:Importing_Content-Creating_a_Custom_File_Type_Repository[]
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select the name of a product.
. Click the *Repositories* tab and select *New Repository*.
. In the *Name* field, enter a name for the repository.
{ProjectNameX} automatically completes this field based on what you enter for *Name*.
. From the *Type* list, select *file*.
. In the *Upstream URL* field, enter the URL of the upstream repository to use as a source.
. Select the *Verify SSL* check box if you want to verify that the upstream repository's SSL certificates are signed by a trusted CA.
. In the *Upstream Username* field, enter the user name for the upstream repository if required for authentication.
Clear this field if the repository does not require authentication.
. In the *Upstream Password* field, enter the corresponding password for the upstream repository.
Clear this field if the repository does not require authentication.
. Click *Save*.
. To update the file type repository, navigate to *Content* > *Products*.
Select the name of a product that contains the repository that you want to update.
. In the product's window, select the name of the repository you want to update.
. From the *Select Action* menu, select *Sync Now*.

Visit the URL where the repository is published to view the files.

[[Importing_Content-Uploading_Files_To_a_Custom_File_Type_Repository]]
=== Uploading Files To a {customfiletypetitle} Repository in {ProjectName}

Use this procedure to upload files to a {customfiletype} repository.

.Procedure

. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select a {customproduct} by name.
. Select a file type repository by name.
. Click *Browse* to search and select the file you want to upload.
. Click *Upload* to upload the selected file to {ProjectServer}.
. Visit the URL where the repository is published to see the file.

.CLI procedure

[options="nowrap" subs="+quotes"]
----
# hammer repository upload-content \
--id _repo_ID_ \
--organization "_My_Organization_" \
--path _example_file_
----

The `--path` option can indicate a file, a directory of files, or a glob expression of files.
Globs must be escaped by single or double quotes.

[[Importing_Content-Downloading_Files_From_a_Custom_File_Type_Repository]]
=== Downloading Files to a Host From a {customfiletypetitle} Repository in {ProjectName}

You can download files to a client over HTTPS using `curl -O`, and optionally over HTTP if the *Publish via HTTP* repository option is selected.

.Prerequisites

* You have a {customfiletype} repository.
See xref:Importing_Content-Creating_a_Custom_File_Type_Repository[] for more information.
* You know the name of the file you want to download to clients from the file type repository.
* To use HTTPS you require the following certificates on the client:
+
. The `katello-server-ca.crt`.
For more information, see {AdministeringDocURL}sect-Administering-Installing_the_Katello_Root_CA_Certificate[Installing the Katello Root CA Certificate] in the _Administering {ProjectName}_ guide.
. An Organization Debug Certificate.
See xref:Managing_Organizations-Creating_an_Organization_Debug_Certificate[] for more information.

.Procedure

. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select a {customproduct} by name.
. Select a file type repository by name.
. Check to see if *Publish via HTTP* is enabled.
If it is not, you require the certificates to use HTTPS.
. Copy the URL where the repository is published.

.CLI procedure

. List the file type repositories.
+
[options="nowrap" subs="+quotes"]
----
# hammer repository list --content-type file
---|----------|-----------------|--------------|----
ID | NAME     | PRODUCT         | CONTENT TYPE | URL
---|----------|-----------------|--------------|----
7  | _My Files_ | _My File Product_ | file         |
---|----------|-----------------|--------------|----
----
+
. Display the repository information.
+
[options="nowrap",subs="+quotes"]
----
# hammer repository info --name "_My Files_" --product "_My File Product_" --organization-id 1
----
+
If HTTP is enabled, the output is similar to this:
+
[options="nowrap" subs="+quotes,attributes"]
----
Publish Via HTTP:   yes
Published At:       http://_{foreman-example-com}_/pulp/isos/_uuid_/
----
+
If HTTP is not enabled, the output is similar to this:
+
[options="nowrap" subs="+quotes,attributes"]
----
Publish Via HTTP:   no
Published At:       https://_{foreman-example-com}_/pulp/isos/_uuid_/
----

. On the client, enter a command in the appropriate format for HTTP or HTTPS:
+
For HTTP:
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -O _{foreman-example-com}_/pulp/isos/_uuid_/_my_file_
----
+
For HTTPS:
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -O --cert _./Default\ Organization-key-cert.pem_ --cacert katello-server-ca.crt _{foreman-example-com}_/pulp/isos/_uuid_/_my_file_
----
