[[basic-content-management-workflow]]
=== Basic content management workflow

This is a quick overview of the tasks involved in the basic content management workflow in {Project}.
If you have installed {Project} with Katello and want to synchronize and manage Enterprise Linux content on your hosts, follow the steps in this chapter.

* Create {customrepo} to mirror content from CentOS Stream.
* Synchronize the Content.
* Create `Activation Keys`.
* Register Hosts to consume this content.
* Manage RPMs on hosts using the `katello-agent`.


==== Creating repositories to synchronize

Use this procedure to discover available repositories in the CentOS Stream, then select the repositories to mirror into a {customproduct}.

.Procedure
. In the {Project} web UI, navigate to *Content* > *Products*.
. Click *Repo Discovery*.
. In the *Repository Type* field, select *Yum Repositories*.
. In the *URL to Discover* field, enter the CentOS Stream URL `http://mirror.centos.org/centos/8-stream`.
. Click *Discover*.
. Select `/AppStream/x86_64/os/` and `/BaseOS/x86_64/os/` repositories.
. Click *Create Selected*.
. In the *Product* field select *New Product*.
. In the *Name* field enter *CentOS Stream* or desired product name.
. Click *Run Repository Creation*.

To view your newly created product, navigate to *Content* > *Products*, and select the name of the new product.


==== Synchronizing content from an upstream repository

Use the following procedure to mirror the contents of the upstream Centos repositories.

.Procedure
. In the {Project} web UI, navigate to *Content* > *Products*
. Select your new *CentOS Stream* product from the previous procedure.
. Locate the *AppStream x86_64 os* and *BaseOS x86_64 os* repositories.
. Select both repositories
. Click *Sync Now*


==== Creating an Activation Key

Use the following procedure to create an activation key that you can use to subscribe your hosts to content managed by {Project}.

. In the {Project} web UI, navigate to *Content* > *Activation keys* and click *Create Activation Key*.
. In the *Name* field, enter the name of the activation key.
. In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the *Library*.
. From the *Content View* list, select *Default Organization View*.
. Click *Save*.

. Click on the *Subscriptions* tab on the Activation Key's details page.
. Click on the *Add* tab.
. Select all the product subscriptions in the table.
. Click *Add Selected* to save.

==== Registering a CentOS Stream host to {Project}

Use the following procedure to register an existing CentOS Stream host to {Project}

. Log on to the Centos 8 host you want register.
. Download the consumer RPM for your {ProjectServer}.
. This is located in the `pub` directory on {ProjectServer}'s web server.
For example, for a {ProjectServer} with the host name `{foreman-example-com}`, enter the following command on the host to register:
+
[options="nowrap" subs="+quotes,attributes"]
----
# rpm -Uvh _http://{foreman-example-com}_/pub/katello-ca-consumer-latest.noarch.rpm
----
+
This RPM installs the necessary certificates for accessing repositories on {ProjectServer} and configures Red Hat Subscription Manager to use the server's URL.
+
. On the host, enter the following command to register the host to {Project} using the activation key:
+
[options="nowrap" subs="+quotes"]
----
# subscription-manager register --activationkey="_My_Activation_Key_"  --org="_My_Organization_"
----
. After registration, enter the yum repolist command to update `/etc/yum.repos.d/redhat.repo` and enable content from {ProjectServer}.
+
[options="nowrap" subs="+quotes"]
----
# yum repolist

repo id                                                           repo name
Default_Organization_Centos_Stream_AppStream_x86_64_os            AppStream x86_64 os
Default_Organization_Centos_Stream_BaseOS_x86_64_os               BaseOS x86_64
Uploading Enabled Repositories Report
----
. Check the `/etc/yum.repos.d/redhat.conf` and ensure that the appropriate repositories have been enabled.

==== Using Content Views

{Project} uses the concept of Content Views to create snapshots of a set of repositories and make them available to hosts registered to it.

For example, if you want a group of hosts to have access to a specific version of a set of repositories, add those repositories to a Content View, publish and promote to a lifecycle environment.
You can then register hosts to this Content View. These hosts have access only to repositories at the version specified in the Content View.

This means that you can continue to update repositories on your server while your hosts still consume only the versions of the repositories that they are registered to.

If you do not use Content Views and lifecycle environments, all your hosts consume content from the Default Content View and Library environment, which is a snapshot of the latest version of the content on your server.

For more information about content management using Content Views and application lifecycles, see:

* xref:Managing_Content_Views[]
* xref:Creating_an_Application_Life_Cycle[]

==== Creating a Content View

Use the following procedure to create a Content view.

. In the {Project} web UI, navigate to *Content* > *Content Views* and click *Create New View*.
. In the *Name* field, enter *Centos content view*.
. In the *Description* field, enter a description for the Content View.
. Click *Save*.

==== Adding Repositories

Use the following procedure to add the upstream CentOS repositories to your Content view.

. In the {Project} web UI, navigate to *Content* > *Content Views* > Select *CentOS content view* > *Yum Content* Dropdown> *Repositories*.
. Click on *Add* section on the Repository selection page.
. Locate the *AppStream x86_64 os* and *BaseOS x86_64 os* repositories.
. Select both repositories
. Click *Add Repositories*

==== Publishing the Content View

Use the following procedure to publish the Content View.

. In the {Project} web UI, navigate to *Content* > *Content Views*, and select your new Content View.
. Click on *Publish New Version* button on the top right of page.
. Click *Save*

==== Creating an Activation Key to consume the Content View

Use the following procedure to create an activation key that you can use to subscribe your hosts to content managed by {Project}.

. In the {Project} web UI, navigate to *Content* > *Activation keys* and click *Create Activation Key*.
. In the *Name* field, enter *CentOS* or the name of your new activation key.
. In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the *Library*.
. From the *Content View* list, select *Centos content view*.
. Click *Save*.
. Click the *Subscriptions* tab on the Activation Key's details page.
. Click the *Add* tab.
. Select your new *CentOS Stream* product in the table.
. Click *Add Selected* to save.

Use your activation key to register a host to the Content View. For more information on registering a host, see {ManagingHostsDocURL}registering-a-host_managing-hosts

==== Registering a CentOS Stream host to consume content from published Content View

You can also register the host to the published Content View without an activation key using the following command:

+
[options="nowrap" subs="+quotes"]
----
# subscription-manager register --org=__My_Organization__ --environment=Library/Centos_content_view
----

==== Managing the Lifecycle of the Content View

The default location of any new Content View is in the Library Environment. Optionally, you can add a new environment and promote your Content View to it.
Use the following procedure to create a new Lifecycle Enviroment.

. In the {Project} web UI, navigate to *Content* > *Lifecycle Environment* and click *Create Environment Path*.
. In the *Name* field, enter *Production* or the name of your new environment to add to the end of Library environment.
. In the *Description* field, add an optional description for your new lifecycle environment.
. Click *Save*

==== Promoting your Content View to the new Lifecycle Environment

You can now promote your new Content View to the *Production* environment using the following procedure.

. In the {Project} web UI, navigate to *Content* > *Content Views* > *Select your Content View*
. On the *Versions* tab Click *Promote* for desired version under the Actions column.
. Select *Production* lifecycle environment from the available promotion paths.
. Add an optional *Description*
. Click *Promote Version*

==== Registering a CentOS Stream host to consume content from a promoted Content View in the production environment

To register a host to consume content from the Content View in the Production lifecycle environment, enter the following command:

[options="nowrap" subs="+quotes"]
----
# subscription-manager register --org="_My_Organization_" --environment="Production/Centos_content_view"
----
