Needs tech review:
- changed-files:
  - any-glob-to-any-file: ['guides/**']

Needs style review:
- changed-files:
  - any-glob-to-any-file: ['guides/**']

Needs testing:
- changed-files:
  - any-glob-to-any-file: ['guides/common/assembly_*.adoc','guides/common/modules/proc_*.adoc']
