[[chap-Red_Hat_Satellite-Architecture_Guide-Provisioning_Concepts]]

== Provisioning Concepts
An important feature of {ProjectName} is unattended provisioning of hosts. To achieve this, {ProjectName} uses DNS and DHCP infrastructures, PXE booting, TFTP, and Kickstart. Use this chapter to understand the working principle of these concepts.

=== PXE Booting
Preboot execution environment (PXE) provides the ability to boot a system over a network. Instead of using local hard drives or a CD-ROM, PXE uses DHCP to provide host with standard information about the network, to discover a TFTP server, and to download a boot image.
ifeval::["{build}" == "satellite"]
For more information about setting up a PXE server see the Red{nbsp}Hat Knowledgebase solution https://access.redhat.com/solutions/163253[How to set-up/configure a PXE Server].
endif::[]


==== PXE Sequence

. The host boots the PXE image if no other bootable image is found.
. A NIC of the host sends a broadcast request to the DHCP server.
. The DHCP server receives the request and sends standard information about the network: IP address, subnet mask, gateway, DNS, the location of a TFTP server, and a boot image.
. The host obtains the boot loader `image/pxelinux.0` and the configuration file `pxelinux.cfg/00:MA:CA:AD:D` from the TFTP server.
. The host configuration specifies the location of a kernel image, `initrd` and Kickstart.
. The host downloads the files and installs the image.

For an example of using PXE Booting by {ProjectServer}, see {BaseURL}provisioning_guide/provisioning-introduction#provisioning-workflow_provisioning[Provisioning Workflow] in the _Provisioning Guide_.

==== PXE Booting Requirements
To provision machines using PXE booting, ensure that you meet the following requirements:

.Network requirements

* Optional: If the host and the DHCP server are separated by a router, configure the DHCP relay agent and point to the DHCP server.

.Client requirements

* Ensure that all the network-based firewalls are configured to allow clients on the subnet to access the {SmartProxy}. For more information, see xref:figu-Satellite_Topology_with_Isolated_Capsule[].

* Ensure that your client has access to the DHCP and TFTP servers.

.{Project} requirements

* Ensure that the UDP ports 67 and 68 are accessible by the client to enable the client to receive a DHCP offer with the boot options.

* Ensure that the UDP port 69 is accessible by the client so that the client can access the TFTP server on the {SmartProxy}.

* Ensure that the TCP port 80 is accessible by the client to allow the client to download files and Kickstart templates from the {SmartProxy}.

* Ensure that the host provisioning interface subnet has a DHCP {SmartProxy} set.

* Ensure that the host provisioning interface subnet has a TFTP {SmartProxy} set.

* Ensure that the host provisioning interface subnet has a Templates {SmartProxy} set.

* Ensure that DHCP with the correct subnet is enabled using the {Project} installer.

* Enable TFTP using the {Project} installer.

=== HTTP Booting
You can use HTTP booting to boot systems over a network using HTTP.

==== HTTP Booting Requirements
To provision machines through HTTP booting ensure that you meet the following requirements:

.Network requirements

* Optional: If the host and the DHCP server are separated by a router, configure the DHCP relay agent and point to the DHCP server.

.Client requirements

* Ensure that all the network-based firewalls are configured to allow clients on the subnet to access the {SmartProxy}. For more information, see xref:figu-Satellite_Topology_with_Isolated_Capsule[].

* Ensure that your client has access to the DHCP and TFTP servers.

.{Project} requirements

* Ensure that the UDP ports 67 and 68 are accessible by the client so that the client can send and receive a DHCP request and offer.

* Ensure that the UDP port 69 is accessible by the client so that the client can access the TFTP server on the {SmartProxy}.

* Ensure that the TCP port 8000 is open for the client to download files and Kickstart templates from the {SmartProxy}.

* Ensure that the host provisioning interface subnet has a DHCP {SmartProxy} set.

* Ensure that the host provisioning interface subnet has a TFTP {SmartProxy} set.

* Ensure that the host provisioning interface subnet has a Templates {SmartProxy} set.

* Update the `grub2-efi` package to the latest version:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} grub2-efi
----

* Enable httpboot, http and tftp modules using the {foreman-installer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {installer-scenario} \
--foreman-proxy-httpboot true \
--foreman-proxy-http true \
--foreman-proxy-tftp true
----

=== Kickstart
You can use Kickstart to automate the installation process of a {ProjectName} or {SmartProxyServer} by creating a Kickstart file that contains all the information that is required for the installation. For more information about Kickstart, see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Installation_Guide/chap-kickstart-installations.html[Kickstart Installations] in the _{RHEL} 7 Installation Guide_.

==== Workflow
When you run a {ProjectName} Kickstart script, the following workflow occurs:

. It specifies the installation location of a {ProjectServer} or a {SmartProxyServer}.
. It installs the predefined packages.
. It installs Red{nbsp}Hat Subscription Manager.
. It uses Activation Keys to subscribe the hosts to {ProjectName}.
. It installs Puppet, and configures a `puppet.conf` file to indicate the {ProjectName} or {SmartProxy} instance.
. It enables Puppet to run and request a certificate.
. It runs user defined snippets.
