[id="Content_Types_in_{ProjectNameID}_{context}"]
= Content Types in {ProjectName}

With {ProjectName}, you can import and manage many content types.

For example, {Project} supports the following content types:

RPM Packages::
ifdef::satellite[]
Import RPM packages from repositories related to your Red{nbsp}Hat subscriptions.
endif::[]
ifndef::satellite[]
Import RPM packages from any repository, for example from Red{nbsp}Hat, SUSE, and custom repositories.
endif::[]
ifdef::satellite[]
{ProjectServer} downloads the RPM files from the Red{nbsp}Hat Content Delivery Network and stores them locally.
endif::[]
ifndef::satellite[]
{ProjectServer} downloads the RPM files and stores them locally.
endif::[]
You can use these repositories and their RPM files in content views.

ifndef::satellite[]
DEB Packages::
Import DEB packages from repositories, for example for Debian or Ubuntu.
You can also import single DEB packages or synchronize custom repositories.
You can use these repositories and their DEB files in content views.
endif::[]

ifdef::satellite[]
Kickstart Trees::
Import the Kickstart trees for creating a system.
New systems access these Kickstart trees over a network to use as base content for their installation.
{ProjectName} contains some predefined Kickstart templates.
You can also create your own Kickstart templates.
endif::[]

ifndef::satellite[]
Provisioning Templates::
Templates to provision hosts running EL based on synchronized content and Debian, Ubuntu, or SUSE Linux Enterprise Server based on local installation media.
{Project} contains predefined AutoYaST, Kickstart, and Preseed templates as well as the ability to create your own, which are used to provision systems and customize the installation.
endif::[]

ISO and KVM Images::
Download and manage media for installation and provisioning.
For example, {Project} downloads, stores, and manages ISO images and guest images for specific {RHEL} and non-Red{nbsp}Hat operating systems.

OSTree::
Import OSTree branches and publish this content to an HTTP location for consumption by OSTree clients.

{customfiletypetitle}::
Manage {customcontent} for any type of file you require, such as SSL certificates and OVAL files.
