:_mod-docs-content-type: CONCEPT

[id="automated-installation-with-kickstart"]
= Automated installation with Kickstart

[role="_abstract"]
You can automate the installation process of a {ProjectServer} or {SmartProxyServer} by creating a Kickstart file that contains all the information that is required for the installation.

When you run a {ProjectName} Kickstart script, the script performs the following actions:

. It specifies the installation location of a {ProjectServer} or a {SmartProxyServer}.
. It installs the predefined packages.
. It installs Subscription Manager.
. It uses Activation Keys to subscribe the hosts to {ProjectName}.
. It installs Puppet, and configures a `puppet.conf` file to indicate the {ProjectName} or {SmartProxy} instance.
. It enables Puppet to run and request a certificate.
. It runs user defined snippets.

ifndef::foreman-deb[]
.Additional resources
ifdef::orcharhino[]
* {RHELDocsBaseURL}9/html/automatically_installing_rhel/automated-installation-workflow_rhel-installer[Automated installation workflow in _Automatically installing RHEL{nbsp}9_]
endif::[]
ifndef::containerized[]
ifdef::foreman-el,katello[]
* {RHELDocsBaseURL}9/html/automatically_installing_rhel/automated-installation-workflow_rhel-installer[Automated installation workflow in _Automatically installing RHEL{nbsp}9_]
endif::[]
endif::[]
ifdef::containerized[]
ifndef::orcharhino[]
* {RHELDocsBaseURL}10/html/automatically_installing_rhel/automated-installation-workflow[Automated installation workflow in _Automatically installing RHEL{nbsp}10_]
endif::[]
endif::[]
endif::[]
