:_mod-docs-content-type: CONCEPT

[id="installing-disconnected-{project-context}-server"]
= Installing disconnected {ProjectServer}

[role="_abstract"]
Use the following procedures to install {ProjectServer} in a disconnected environment, perform the initial configuration, and import subscription manifests.

You can deploy {ProjectServer} with a default internal database or with an external database.

When the intended host for {ProjectServer} is in a disconnected environment, you can install {ProjectServer} by using an external computer to download an ISO image of the packages, and copying the packages to the system you want to install {ProjectServer} on.
This method is not recommended for any other situation as ISO images might not contain the latest updates, bug fixes, and functionality.

After you install {ProjectServer}, you can add {SmartProxyServers} in your disconnected environment by installing them from an ISO image.
For more information, see {InstallingSmartProxyDocURL}installing-{smart-proxy-context}-server-from-iso[Installing {SmartProxyServer} from ISO] in _{InstallingSmartProxyDocTitle}_.

[NOTE]
====
You cannot register {ProjectServer} to itself.
====
