[id="planning-{project-context}-upgrade"]
= Planning {Project} upgrade

Upgrading to {Project} {ProjectVersion} affects your entire {Project} infrastructure because {Project} services are shut down during the upgrade.
The upgrade process duration varies depending on your hardware configuration, network speed, and the amount of data that is stored on the server.
Plan carefully before proceeding.

* Read the {ProjectName} {ProjectVersion} {ReleaseNotesDocURL}[Release Notes].
* Consider whether any of your scripts need updating.
Some {Project} API endpoints, Hammer CLI commands, and modules from the {Project} Ansible Collection can differ between versions of {Project}.
ifdef::satellite[]
For information about changes in these tools, see the {ProjectName} {ProjectVersion} {ReleaseNotesDocURL}[Release Notes].
endif::[]
ifdef::satellite[]
* Optional: You can test the upgrade on a clone of your {ProjectServer}.
After you successfully test the upgrade on the clone, you can repeat the upgrade on your primary {ProjectServer} and discard the clone, or you can promote the clone to your primary {ProjectServer} and discard the previous primary {ProjectServer}.
For more information, see {AdministeringDocURL}cloning_satellite_server[Cloning {ProjectServer}] in _{AdministeringDocTitle}_.
endif::[]
ifndef::foreman-deb[]
* If your {ProjectServer} runs on a RHEL system that is not operating in FIPS mode, you cannot upgrade it to a RHEL system that is operating in FIPS mode.
In this situation, you must install {Project} on a freshly provisioned RHEL system in FIPS mode.
endif::[]
