[id="planning-for-disaster-recovery_{context}"]
= Planning for disaster recovery

Ensure to back up your {Project} data so that you can recover your {Project} deployment in case of a disaster.

To create backups of your {ProjectServer} and {SmartProxyServers}, use the `{foreman-maintain} backup` command.
For more information, see {AdministeringDocURL}backing-up-{project-context}-server-and-{smart-proxy-context}_admin[Backing Up {ProjectServer} and {SmartProxyServer}] in _{AdministeringDocTitle}_.

To backup your hosts, you can use remote execution to configure recurring backup tasks that {Project} will run on the hosts.
For more information, see {ManagingHostsDocURL}Configuring_and_Setting_Up_Remote_Jobs_managing-hosts[Configuring and Setting up Remote Jobs] in _{ManagingHostsDocTitle}_.

ifndef::satellite[]
To create snapshots of hosts, you can use the Snapshot Management plugin.
For more information, see {ManagingHostsDocURL}Creating_Snapshots_of_a_Host_managing-hosts[Creating snapshots of a host] in _{ManagingHostsDocTitle}_.
endif::[]
