:_mod-docs-content-type: CONCEPT

[id="host-global-status-overview_{context}"]
= Host global status overview

[role="_abstract"]
You can use the host global status in {Project} to see at a glance whether a host is OK, needs attention (Warning), or has errors.
The status appears on the Hosts Overview page and helps you prioritize which hosts to investigate.

The host global status can have one of three possible values: *OK*, *Warning*, or *Error*.
You can find global status on the Hosts Overview page.
The status displays a small icon next to the host name and has a color that corresponds with the status.
Hovering over the icon renders a tooltip with sub-status information to quickly find out more details.
To view the global status for a host, in the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.

OK::
No errors were reported by any sub-status.
This status is highlighted with the color green.

Warning::
While no error was detected, some sub-status raised a warning.
For example, there are no configuration management reports for the host even though the host is configured to send reports.
It is a good practice to investigate any warnings to ensure that your deployment remains healthy.
This status is highlighted with the color yellow.

Error::
Some sub-status reports a failure.
For example, a run contains some failed resources.
This status is highlighted with the color red.

.Additional resources
* {AdministeringDocURL}working-efficiently-with-web-ui[Working efficiently with {ProjectWebUI} in _{AdministeringDocTitle}_]
