[id="content-sources-in-{ProjectNameID}_{context}"]
= Sources of content in {Project}

ifdef::satellite[]
With {ProjectName}, you can use Red{nbsp}Hat content as well as custom content and organize it into {Project} products.
endif::[]
ifdef::foreman-el,katello[]
With {ProjectName}, you can use content from upstream as well as from Canonical, Oracle, Red{nbsp}Hat, SUSE, and custom content.
endif::[]

Red{nbsp}Hat content::
The Red{nbsp}Hat subscription manifest determines what Red{nbsp}Hat repositories your {ProjectServer} can access.
Red{nbsp}Hat content is already organized into products.
+
For example, {RHEL} Server is a product in {Project}.
The repositories for the {RHEL}{nbsp}Server product consist of different versions, architectures, and add-ons.
When you enable a Red{nbsp}Hat repository, {Project} automatically creates an associated product.

Other sources of content::
{Project} creates a subscription for each {customproduct} you create.
To distribute content from custom sources, you must create products and repositories manually.
You can organize other content into {customproduct}s however you want.
+
For example, you can create an EPEL (Extra Packages for Enterprise Linux) Product and add an "EPEL 7 x86_64" repository to it.
