:_mod-docs-content-type: CONCEPT

[id="configuring-ssh-certificate-authentication-for-remote-execution"]
= Configuring {SmartProxy} and hosts to authenticate with SSH certificates during remote execution

[role="_abstract"]
By default, {Project} follows the Trust on First Use (TOFU) model during a remote execution connection.
You can reconfigure your {SmartProxy} to use SSH certificates instead.
SSH certificates are signed by a Certificate Authority (CA), which allows centralized trust management and revocation capabilities.

You can configure SSH certificate authentication in the following ways.
You can configure one or both of these authentication methods depending on your security requirements:

{SmartProxy} authentication::
When your {SmartProxy} connects to hosts, it presents a signed certificate.
Hosts trust the CA that signed the certificate, eliminating the need to distribute individual SSH public keys to each host.

Host authentication::
When your {SmartProxy} connects to hosts, the hosts present signed certificates.
{SmartProxy} verifies that it is connecting to legitimate hosts, helping prevent man-in-the-middle attacks.
