:_mod-docs-content-type: CONCEPT

[id="installing-a-{project-context}-server_{context}"]
= Installing a {ProjectServer}

[role="_abstract"]
Installing an instance of {ProjectServer} on a dedicated server is the first step to a working {Project} infrastructure.

ifdef::satellite[]
You can install a {ProjectServer} in a connected or disconnected setup:

* Connected deployment is suitable for networked environments where your {ProjectServer} is connected to the Red{nbsp}Hat CDN.
* Disconnected deployment is suitable for high-security environments where direct internet access is restricted or prohibited.

In the disconnected setup, your {ProjectServer} uses Inter-Server Synchronization (ISS) to obtain content from another, connected {ProjectServer}.
Although a disconnected {ProjectServer} is isolated from Red{nbsp}Hat CDN, you can still provision systems with the latest security updates, errata, packages, and other content.
endif::[]

.Additional resources
* {InstallingServerDocURL}[_{InstallingServerDocTitle}_]
ifdef::orcharhino,satellite[]
* {InstallingServerDisconnectedDocURL}[_{InstallingServerDisconnectedDocTitle}_]
endif::[]
