:_mod-docs-content-type: CONCEPT

[id="{insights-id}-overview"]
= {Insights} overview

[role="_abstract"]
{Insights} is a set of analytical services by Red{nbsp}Hat for hosts running {RHEL}.
{Insights} services analyze host data and provide suggestions for host improvements.

{Insights} services::
+
--
{Insights} services include:

* Advisor, which provides recommendations for host improvements.
* Vulnerability, which provides reports on vulnerabilities found on your hosts.
* Compliance, which provides reports on compliance with regulatory requirements.

{Insights} services hosted in the {RHCloud} are not limited to the listed services.

ifdef::satellite[]
.Availability of {Insights} services
[options="header", cols="1,1,1"]
|===
| Service | Hosted {Insights} | {insights-iop}
| Advisor | Available | Available
| Vulnerability | Available | Available
| Compliance | Available | -
|===
endif::[]
--

Hosted {Insights}::
When you use {Insights} hosted in the {RHCloud}, the Insights client on your hosts collects data and {Project} forwards it to the hosted {Insights} services for analysis.
+
--
If you use {Insights} in the {RHCloud}:

* You can use {Insights} services online in the {RHCloud}.
* The Insights client collects data of your hosts and {Project} forwards the data to the {RHCloud} to calculate recommendations.
* You can view and remediate those recommendations both in the {ProjectWebUI} and in the {RHCloud}.
* {Project} uploads host inventory reports to the {RHCloud}.
* You have control over how much information is included in those reports.
ifdef::satellite[]
* You cannot use local {insights-iop}.
endif::[]
--

ifdef::satellite[]
{insights-iop}::
When you use {insights-iop}, the {Insights} services run locally on your {ProjectServer} without connecting to the {RHCloud}.
The Insights client on your hosts collects data and {Project} forwards it to the local {Insights} services for analysis.
+
--
If you use {insights-iop}:

* The {Insights} services run locally on your {ProjectServer}.
* {Project} only communicates with the locally running services of {insights-iop}.
* {Project} does not send any reports to the {RHCloud}.
* {Project} does not forward any data through the Insights client to the {RHCloud}.
* You cannot use any of the hosted services on the {RHCloud}.
--
endif::[]

.Additional resources
* xref:data-control-settings-for-hosted-{insights-id}[]
ifndef::admin[]
* {AdministeringDocURL}configuring-{project-context}-for-{insights-id}-analytics[Configuring {Project} for {Insights} analytics in _{AdministeringDocTitle}_]
* {ManagingHostsDocURL}monitoring-hosts-by-using-{insights-id}-in-cloud[Monitoring hosts by using {Insights} in {RHCloud} in _{ManagingHostsDocTitle}_]
* {ManagingHostsDocURL}monitoring-hosts-by-using-{insights-iop-id}[Monitoring hosts by using {insights-iop} in _{ManagingHostsDocTitle}_]
endif::[]
* https://console.redhat.com[{RHCloud}]
* https://console.redhat.com/insights/dashboard[{Insights} dashboard]
* https://docs.redhat.com/en/documentation/red_hat_lightspeed/[Red{nbsp}Hat Lightspeed documentation]
