[id="transport-modes-for-remote-execution_{context}"]
= Transport modes for remote execution

You can configure your {Project} to use two different modes of transport for remote job execution.

On {SmartProxies} in `ssh` mode, remote execution uses the SSH service to transport job details.
This is the default transport mode.
The SSH service must be enabled and active on the target hosts.
The remote execution {SmartProxy} must have access to the SSH port on the target hosts.
Unless you have a different setting, the standard SSH port is 22.

[NOTE]
====
If your {SmartProxy} already uses the `pull-mqtt` mode and you want to switch back to the `ssh` mode, run this `{foreman-installer}` command:

[options="nowrap",subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --foreman-proxy-plugin-remote-execution-script-mode=ssh
----
====

On {SmartProxies} in `pull-mqtt` mode, remote execution uses Message Queueing Telemetry Transport (MQTT) to publish jobs it receives from {ProjectServer}.
The host subscribes to the MQTT broker on {SmartProxy} for job notifications using the `yggdrasil` pull client.
After the host receives a notification, it pulls job details from {SmartProxy} over HTTPS, runs the job, and reports results back to {SmartProxy}.

To use the `pull-mqtt` mode, you must enable it on {SmartProxyServer} and configure the pull client on the target hosts.

.Additional resources
* To enable pull mode on {SmartProxyServer}, see {InstallingSmartProxyDocURL}configuring-remote-execution-for-pull-client_{smart-proxy-context}[Configuring Remote Execution for Pull Client] in _{InstallingSmartProxyDocTitle}_.
ifdef::katello,orcharhino,satellite[]
* To enable pull mode on an existing host, continue with xref:Configuring_a_Host_to_Use_the_Pull_Client_{context}[].
endif::[]
ifdef::managing-hosts[]
* To enable pull mode on a new host, continue with either of the following procedures:

** xref:Creating_a_Host_{context}[]
** xref:Registering_Hosts_by_Using_Global_Registration_{context}[].
endif::[]
ifndef::managing-hosts[]
* To enable pull mode on a new host, continue with either of the following procedures in _{ManagingHostsDocTitle}_:

** {ManagingHostsDocURL}Creating_a_Host_managing-hosts[Creating a Host]
** {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts]
endif::[]
