[id="Introduction_to_Content_Management_{context}"]
= Introduction to Content Management

In the context of {Project}, _content_ is defined as the software installed on systems.
This includes, but is not limited to, the base operating system, middleware services, and end-user applications.
ifdef::satellite[]
With {ProjectName}, you can manage the various types of content for {RHEL} systems at every stage of the software life cycle.
endif::[]
ifndef::satellite[]
With {Project}, you can manage the various types of content at every stage of the software life cycle.
endif::[]

ifdef::foreman-el,katello[]
[IMPORTANT]
The Katello plug-in provides content management features to Foreman.
You can only use this guide if you have the Katello plug-in installed.
endif::[]

{ProjectName} manages the following content:

Subscription management::
This provides organizations with a method to manage their Red Hat subscription information.

Content management::
ifdef::satellite[]
This provides organizations with a method to store Red Hat content and organize it in various ways.
endif::[]
ifdef::foreman-el,katello,orcharhino[]
This provides organizations with a method to store APT and YUM content and organize it in various ways.
endif::[]
