:_mod-docs-content-type: CONCEPT

[id="Provisioning_Virtual_Machines_on_KVM_{context}"]
= Provisioning virtual machines on KVM (libvirt)

[role="_abstract"]
{Project} can connect to the `libvirt` API on the hypervisor to provision hosts and control certain virtualization functions.

Only Virtual Machines created through {Project} can be managed.
Virtual Machines with other than directory storage pool types are unsupported.

You can use KVM provisioning to create hosts over a network connection or from an existing image.

Before you use KVM to provision virtual machines, ensure that your environment meets the following requirements:

include::snip_prerequisites-common-compute-resource.adoc[]
* A {SmartProxyServer} managing a network on the KVM server.
Ensure no other DHCP services run on this network to avoid conflicts with {SmartProxyServer}.
For more information about network service configuration for {SmartProxyServers}, see {ProvisioningDocURL}preparing-networking[Preparing networking] in _{ProvisioningDocTitle}_.
ifdef::satellite[]
* A {RHEL} server running KVM virtualization tools (libvirt daemon).
For more information, see the {RHELDocsBaseURL}8/html/configuring_and_managing_virtualization/index[_{RHEL}{nbsp}8 Configuring and managing virtualization_].
endif::[]
ifndef::satellite[]
* A server running KVM virtualization tools (libvirt daemon).
* A virtual network running on the libvirt server.
Only NAT and isolated virtual networks can be managed through {Project}.
endif::[]
* An existing virtual machine image if you want to use image-based provisioning.
Ensure that this image exists in a storage pool on the KVM host.
The `default` storage pool is usually located in `/var/lib/libvirt/images`.
Only directory pool storage types can be managed through {Project}.
* Optional: The examples in these procedures use the root user for KVM.
If you want to use a non-root user on the KVM server, you must add the user to the `libvirt` group on the KVM server:
+
[options="nowrap" subs="+quotes"]
----
# usermod -a -G libvirt _non_root_user_
----
* Ensure the provisioning user has the required permissions to provision hosts.
For more information, see xref:permissions-required-to-provision-hosts[].

include::snip_warning-destroy-vm-on-host-delete.adoc[]
