:_mod-docs-content-type: CONCEPT

[id="activation-keys-and-host-registration"]
= Activation keys and host registration

[role="_abstract"]
Use activation keys during provisioning or when registering existing {client-os} hosts to apply subscription and content settings automatically.

[NOTE]
====
ifdef::orcharhino,satellite[]
The `{client-provisioning-template-type}` provisioning templates in {Project} contain commands to register the host, using an activation key that is defined when creating a host.
endif::[]
ifdef::katello[]
The `Agama`, `AutoYaST`, `Kickstart`, `Preseed`, and `Preseed Autoinstall` provisioning templates in {Project} contain commands to register the host, using an activation key that is defined when creating a host.
endif::[]
====

You can use multiple activation keys when registering a host.
For example, you can use one activation key to enable specific repositories and another to assign content view environments.

If there are conflicting settings in activation keys, the rightmost key takes precedence.

* Settings that conflict: *Service Level*, *Release Version*, *Environment*, *Content View*, and *Product Content*.
* Settings that do not conflict and the host gets the union of them: *Host Collections*.
* Settings that influence the behavior of the key itself and not the host configuration: *Content Host Limit*.

.Additional resources
* {ManagingHostsDocURL}registering-hosts-to-{project-context}[Registering hosts to {Project} in _{ManagingHostsDocTitle}_]
