:_mod-docs-content-type: CONCEPT

[id="Content_Filter_Examples_{context}"]
= Content filter examples

[role="_abstract"]
Use any of the following examples with the procedure that follows to build custom content filters.

[NOTE]
====
Filters can significantly increase the time to publish a content view.
For example, if a content view publish task completes in a few minutes without filters, it can take 30 minutes after adding an exclude or include errata filter.
====

.Example 1
Create a repository with the base {client-os} packages.
This filter requires a {client-os} repository added to the content view.

*Filter:*

  * *Inclusion Type:* Include
  * *Content Type:* Package Group
  * *Filter:* Select only the *Base* package group

.Example 2
Create a repository that excludes all errata, except for security updates, after a certain date.
This is useful if you want to perform system updates on a regular basis with the exception of critical security updates, which must be applied immediately.
This filter requires a {client-os} repository added to the content view.

*Filter:*

  * *Inclusion Type:* Exclude
  * *Content Type:* Erratum (by Date and Type)
  * *Filter:* Select only the *Bugfix* and *Enhancement* errata types, and clear the *Security* errata type.
Set the *Date Type* to *Updated On*.
Set the *Start Date* to the date you want to restrict errata.
Leave the *End Date* blank to ensure any new non-security errata is filtered.

.Example 3
A combination of Example 1 and Example 2 where you only require the operating system packages and want to exclude recent bug fix and enhancement errata.
This requires two filters attached to the same content view.
The content view processes the Include filter first, then the Exclude filter.

*Filter 1:*

  * *Inclusion Type:* Include
  * *Content Type:* Package Group
  * *Filter:* Select only the *Base* package group

*Filter 2:*

  * *Inclusion Type:* Exclude
  * *Content Type:* Erratum (by Date and Type)
  * *Filter:* Select only the *Bugfix* and *Enhancement* errata types, and clear the *Security* errata type.
Set the *Date Type* to *Updated On*.
Set the *Start Date* to the date you want to restrict errata.
Leave the *End Date* blank to ensure any new non-security errata is filtered.

ifdef::client-content-dnf[]
.Example 4
Filter a specific module stream in a content view.

*Filter 1:*

* *Inclusion Type:* Include
* *Content Type:* Module Stream
* *Filter:* Select only the specific module stream that you want for the content view, for example *ant*, and click *Add Module Stream*.

*Filter 2:*

* *Inclusion Type:* Exclude
* *Content Type:* Package
* *Filter:* Add a rule to filter any non-modular packages that you want to exclude from the content view.
If you do not filter the packages, the content view filter includes all non-modular packages associated with the module stream *ant*.
Add a rule to exclude all `*` packages, or specify the package names that you want to exclude.
endif::[]

ifndef::orcharhino[]
For another example of how content filters work, see the following article: https://access.redhat.com/solutions/1564953["How do content filters work in Satellite 6"].
endif::[]
