[id="Resolving_Package_Dependencies_{context}"]
= Resolving package dependencies

{Project} can add dependencies of packages in a content view to the dependent repository when publishing the content view.
To configure this, you can enable _dependency solving_.

For example, dependency solving is useful when you incrementally add a single package to a content view version.
You might need to enable dependency solving to install that package.

However, dependency solving is unnecessary in most situations.
For example:

* When incrementally adding a security errata to a content view, dependency solving can cause significant delays to content view publication without major benefits.
* Packages from a newer erratum might have dependencies that are incompatible with packages from an older content view version.
Incrementally adding the erratum by solving dependencies might include unwanted packages.
As an alternative, consider updating the content view.

[NOTE]
====
Dependency solving only considers packages within the repositories of the content view.
It does not consider packages installed on clients.
ifeval::["{client-os-family}" == "Red Hat"]
For example, if a content view includes only AppStream, dependency solving does not include dependent BaseOS content at publish time.
endif::[]

For more information, see {ContentManagementDocURL}Limitations_to_Repository_Dependency_Resolution_content-management[Limitations to Repository Dependency Resolution] in _{ContentManagementDocTitle}_.
====

Dependency solving can lead to the following problems:

Significant delay in content view publication::
{Project} examines every repository in a content view for dependencies.
Therefore, publish time increases with more repositories.
+
To mitigate this problem, use multiple content views with fewer repositories and combine them into composite content views.

Ignored content view filters on dependent packages::
{Project} prioritizes resolving package dependencies over the rules in your filter.
+
For example, if you create a filter for security purposes but enable dependency solving, {Project} can add packages that you might consider insecure.
+
To mitigate this problem, carefully test filtering rules to determine the required dependencies.
If dependency solving includes unwanted packages, manually identify the core basic dependencies that the extra packages and errata need.

ifeval::["{client-os-family}" == "Red Hat"]
[id="Combining_exclusion_filters_with_dependency_solving_{context}"]
.Combining exclusion filters with dependency solving
====
You want to recreate {RHEL}{nbsp}8.3 by using content view filters and include selected errata from a later {RHEL}{nbsp}8 minor release.
To achieve this, you create filters to exclude most of the errata after the {RHEL}{nbsp}8.3 release date, except a few that you need.
Then, you enable dependency solving.

In this situation, dependency solving might include more packages than expected.
As a result, the host diverges from being a {RHEL}{nbsp}8.3 machine.

If you do not need the extra errata and packages, do not configure content view filtering.
Instead, enable and use the {RHEL}{nbsp}8.3 repository on the *Content* > *Red Hat Repositories* page in the {ProjectWebUI}.
====
endif::[]

ifeval::["{client-os-family}" == "Red Hat"]
[id="Excluding_packages_and_dependency_solving_with_DNF_{context}"]
.Excluding packages sometimes makes dependency solving impossible for DNF
====
If you make a {RHEL}{nbsp}8.3 repository with a few excluded packages, `dnf update` can sometimes fail.

Do not enable dependency solving to resolve the problem.
Instead, investigate the error from `dnf` and adjust the filters to stop excluding the missing dependency.

Else, dependency solving might cause the repository to diverge from {RHEL}{nbsp}8.3.
====
endif::[]
