[id="Managing_DHCP_Using_Smart_Proxy_{context}"]
= Managing DHCP Using {SmartProxy}

{Project} can integrate with a DHCP service using your {SmartProxy}.
A {SmartProxy} has multiple DHCP providers that you can use to integrate {Project} with your existing DHCP infrastructure or deploy a new one.
You can use the DHCP module of {SmartProxy} to query for available IP addresses, add new, and delete existing reservations.
Note that your {SmartProxy} cannot manage subnet declarations.

.Available DHCP providers
* `dhcp_infoblox` {endash} For more information, see {ProvisioningDocURL}Using_Infoblox_as_DHCP_and_DNS_Providers_provisioning[Using Infoblox as DHCP and DNS Providers] in _{ProvisioningDocTitle}_.
* `dhcp_isc` {endash} ISC DHCP server over OMAPI.
For more information, see {InstallingSmartProxyDocURL}configuring-dns-dhcp-and-tftp_smart-proxy[Configuring DNS, DHCP, and TFTP on {SmartProxyServer}] in _{InstallingSmartProxyDocTitle}_.
* `dhcp_remote_isc` {endash} ISC DHCP server over OMAPI with leases mounted through networking.
For more information, see {InstallingSmartProxyDocURL}configuring-external-dhcp_smart-proxy[Configuring an External DHCP Server to Use with {SmartProxyServer}] in _{InstallingSmartProxyDocTitle}_.
ifndef::satellite[]
* `dhcp_libvirt` {endash} dnsmasq DHCP via libvirt API
endif::[]
ifdef::orcharhino[]
* `dhcp_native_ms` {endash} Microsoft Active Directory using API
endif::[]
