[id="converting-a_host-with-convert2rhel_{context}"]
= Converting a Host to {RHEL} with Convert2RHEL

Convert2RHEL enables the conversion of {RHEL} derivative distributions into a supportable {RHEL} state while retaining existing applications and configurations.

The conversion process is similar to a minor release upgrade of {RHEL} in which every RPM package on the system is replaced.
Third-party packages and non-{Team} packages not available in {RHEL} are not replaced.

You can convert:

* CentOS 7 to {RHEL} 7
* Oracle 7 to {RHEL} 7
* CentOS 8 to {RHEL} 8

You cannot convert a version 7 package into {RHEL} 8, or a version 8 package into {RHEL} 7.

Note that if you want to create data for Oracle 7 you must set `foreman-convert2rhel_enable_oracle7: true`.

Convert2RHEL removes unnecessary packages such as logos, or packages known to cause issues during the conversion, and replaces the `CentOS-release` or `Oracle-release` package with the `rhel-release` package.
It subscribes the system to {ProjectName} and replaces all packages signed by CentOS or Oracle.
ifdef::satellite[]
For {Project}, it also subscribes the system to {Team} Subscription Management.
endif::[]

The amount of time taken to do this can vary depending on how many packages need to be replaced, network speed, storage speed, and similar variables.

Use the global registration template to register and subscribe your system before the conversion.
For more information, see {ManagingHostsDocURL}registering-a-host_managing-hosts[Registering a Host to {ProjectName} Using the Global Registration Template] in the _Managing Hosts_ guide.

Parts of the process can be achieved using an Ansible Role assigned to the host or host groups.
The Ansible role prepares data, that is, repositories, certificates, activation keys and host groups required for the host conversion.
The role enables the `rhel-7-server-rpms` repository with the 7Server release and x86_64 architecture, as well as `rhel-8-for-x86_64-baseos-rpms` and `rhel-8-for-x86_64-appstream-rpms`.

Using the Ansible role to automate the Convert2RHEL process generates activation keys.
As these are used elsewhere in the process, they are listed here:

* convert2rhel_centos7 - used for registering centos7 hosts.
* convert2rhel_centos8 - used for registering centos8 hosts.
* convert2rhel_oracle7 - used for registering oracle7 hosts.
* convert2rhel_rhel7 - used for re-registering a host converted to RHEL 7.
* convert2rhel_rhel8 - used for re-registering a hosts converted to RHEL 8.

To convert hosts to {RHEL} with convert2RHEL, you must complete the following procedures:

. xref:installing-convert2rhel_{context}[].
. xref:Creating_an_Activation_Key_{context}[].
. xref:preparing-the-host-group_{context}[].
. xref:registering-hosts-for-conversion_{context}[].
. xref:converting-hosts-with-convert2rhel_{context}[]

.Prerequisites
ifndef::orcharhino[]
* You must have completed the steps listed in https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index#proc_preparing-for-a-rhel-conversion_converting-from-a-linux-distribution-to-rhel[Preparing for a RHEL conversion].
endif::[]
* If you are providing the organization ID and activation key to register and subscribe your system, you must have created an activation key in {ProjectName}.
ifdef::satellite[]
For {Project} you can also create an activation key in Subscription Manager.
endif::[]
ifndef::orcharhino[]
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in this guide, and https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/using_red_hat_subscription_management/index#activation_keys_con[Understanding activation keys] in Subscription Manager documentation.
endif::[]
* Ensure you have a subscription manifest uploaded to your {Project} and that there are sufficient {RHEL} subscriptions for the conversion.
* If you are providing the organization ID and activation key to register and subscribe your system, you must have created an activation key in {ProjectName} or Subscription Manager.
ifndef::orcharhino[]
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in this guide, and https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/using_red_hat_subscription_management/index#activation_keys_con[Understanding activation keys] in Subscription Manager documentation.
endif::[]
* Ensure you have a subscription manifest uploaded to your {Project} and that there are sufficient {RHEL} subscriptions for the conversion.
+
The manifest provides access to all enabled content for the role to work properly.
You can download the manifest and put it in the correct folder.
The subscription manifest is retrieved from the specified path on the Ansible target host.
Optionally, it can be fetched first from the RHSM portal using the provided login credentials and manifest UUID.
It will be uploaded to the specified organization.
+
If you do not want to download the manifest and synchronize repositories, you can run the role with `foreman_convert2rhel_manage_subscription: false`.

* If you are accessing {RHEL} packages using {ProjectServer}, you must use the organization ID and activation key to run the `convert2rhel` command.
