[id="{ProjectServerID}-Overview_{context}"]
= {ProjectServerTitle} overview

{ProjectServer} is the central component of a {Project} deployment where you plan and manage the content lifecycle.

A typical {Project} deployment includes one {ProjectServer} on which you perform the following operations:

* Content lifecycle management
* Configuration of {SmartProxyServers}
* Configuration of managed hosts
* Host provisioning
* Patch management
* Subscription management

{ProjectServer} delegates content distribution, host provisioning, and communication to {SmartProxyServers}.
{ProjectServer} itself also includes a default, integrated {SmartProxyServer}.

{ProjectServer} also contains a fine-grained authentication system.
You can grant {Project} operators permissions to access precisely the parts of the infrastructure for which they are responsible.

.Additional resources

* See {AdministeringDocURL}Managing_Users_and_Roles_admin[_Managing Users and Roles_] in {AdministeringDocTitle} for information about managing permissions.