:_mod-docs-content-type: CONCEPT

[id="advanced-synchronization-for-repository-recovery"]
= Advanced synchronization for repository recovery

[role="_abstract"]
You can use advanced synchronization to recover corrupted repositories on {ProjectServer}.

Advanced synchronization has the following options:

Optimized Sync::
Synchronizes the repository bypassing packages that have no detected differences from the upstream packages.

Complete Sync::
Synchronizes all packages regardless of detected changes.
Use this option if specific packages could not be downloaded to the local repository even though they exist in the upstream repository.

ifdef::client-content-dnf[]
Verify Content Checksum::
Synchronizes all packages and then verifies the checksum of all packages locally.
If the checksum of an RPM differs from the upstream, it re-downloads the RPM.
This option is relevant only for Yum content.
Use this option if you have one of the following errors:

* Specific packages cause a `404` error while synchronizing with `yum`.
* `Package does not match intended download` error, which means that specific packages are corrupted.
endif::[]
