:_mod-docs-content-type: CONCEPT

[id="Provisioning-Methods-in-{ProjectNameID}_{context}"]
= Provisioning methods in {ProjectName}

With {ProjectName}, you can provision hosts by using the following provisioning methods.

Network based::
You can use this method with hosts that provide PXE booting or UEFI HTTP booting.
+
You are required to configure the necessary network booting services, such as DHCP and TFTP servers.
When you create a host, you select a PXE loader that can configure DHCP options for network booting if {SmartProxy} is set up to configure the DHCP service automatically.
+
This method uses an operating system installer, such as Anaconda, Debian Installer, or YaST, and template-generated file with installation options automation from {Project}, such as Kickstart, Preseed, or AutoYaST.

Boot disk based::
You can use this method with PXE-less hosts or when you do not have the option of configuring network booting services, such as DHCP.
+
This method supplies the booting capability but the rest of the provisioning process still downloads an installer and template-generated files to automate the installation.

Image based::
You can use this method with virtual machines or cloud instances.
+
This method uses a virtual image template or a cloud image from a compute resource to provision the operating system.
{Project} can customize the image by running either a pre-boot or post-boot configuration script generated from a provisioning template.

ifndef::satellite[]
.Choosing a provisioning method
image::common/provisioning-method-selection.svg["Choosing a provisioning method", title="Choosing a provisioning method"]
endif::[]
