:_mod-docs-content-type: CONCEPT

[id="Provisioning_Cloud_Instances_OpenStack_{context}"]
= Provisioning cloud instances on {OpenStack}

[role="_abstract"]
{OpenStack} provides the foundation to build a private or public Infrastructure-as-a-Service (IaaS) cloud.
It offers a massively scalable, fault-tolerant platform for the development of cloud-enabled workloads.
In {Project}, you can interact with {OpenStack} REST API to create cloud instances and control their power management states.

Before you can provision cloud instances on {OpenStack}, ensure that your environment meets the following requirements:

include::snip_prerequisites-common-compute-resource.adoc[]
* A {SmartProxyServer} managing a network in your OpenStack environment.
For more information, see {ProvisioningDocURL}preparing-networking[Preparing networking] in _{ProvisioningDocTitle}_.
* An image added to OpenStack Image Storage (glance) service for image-based provisioning.
ifndef::orcharhino[]
For more information, see the {RHDocsBaseURL}red_hat_openstack_platform/16.0/html/instances_and_images_guide/index[{OpenStack} _Instances and Images Guide_].
endif::[]

include::snip_warning-destroy-vm-on-host-delete.adoc[]
