:_mod-docs-content-type: CONCEPT

[id="defining-your-content-library-and-content-access-strategy"]
= Defining your content library and content access strategy

[role="_abstract"]
To ensure that your {ProjectServer} can manage software and provide it to your hosts, you must create repositories and synchronize them.
When defining your content lifecycle in {Project}, you can use content views and lifecycle environments to define which hosts can access which content and content versions.

Your {Project} content library can include the following types of content:

Red{nbsp}Hat content::
The Red{nbsp}Hat subscription manifest determines what Red{nbsp}Hat repositories your {ProjectServer} can access.
Red{nbsp}Hat content is already organized into products.
+
For example, {RHEL}{nbsp}Server is a product in {Project}.
The repositories for the {RHEL}{nbsp}Server product consist of different versions, architectures, and add-ons.
When you enable a Red{nbsp}Hat repository, {Project} automatically creates an associated product.

ifdef::katello,orcharhino[]
Oracle ULN content::
You can use {Project} to manage hosts running Oracle Linux.

SUSE content::
You can use {Project} to manage hosts running {SLES}.

Ubuntu ESM content::
You can use {Project} to manage hosts running Ubuntu.
endif::[]

Other sources of content::
To distribute content from custom sources, you must create products and repositories manually.
You can organize other content into {customproduct}s however you want.
+
For example, you can create an EPEL (Extra Packages for Enterprise Linux) product and add an "EPEL 9 x86_64" repository to it.

Creating repositories allows you to choose the specific software required for your environment.
By creating only the necessary repositories, you avoid downloading unnecessary content.

Synchronizing repositories downloads the content from Red{nbsp}Hat CDN or another source to your {ProjectServer}.
The synchronized content is stored on your {ProjectServer}, eliminating the need for hosts to access the repositories.
You can synchronize repositories manually, or you can create a sync plan to ensure synchronization runs on a regular basis.

By default, {Project} includes the _Default Organization View_ content view and the _Library_ lifecycle environment.

Default Organization View::
The _Default Organization View_ is the default content view in {Project} that contains all the content that is synchronized to {Project}.
After you update your content, such as by adding or removing a repository, the update is immediately reflected in _Default Organization View_.

Library::
The _Library_ lifecycle environment is the default lifecycle environment in {Project}.
Every newly published content view version is automatically published to the Library lifecycle environment.
You can also promote specific content view versions to the Library lifecycle environment if needed.

In smaller deployments or when you do not require content versioning and environment promotion, you can associate a host to the _Library_ environment under the _Default Organization View_ without configuring additional lifecycle environments.

.Additional resources
ifdef::katello,oracle_linux[]
* {ContentManagementDocURL}uln-repositories[ULN repositories in _{ContentManagementDocTitle}_]
endif::[]
ifdef::katello,suse_linux_enterprise_server[]
* {ContentManagementDocURL}Managing_SUSE_Content_content-management[Managing SUSE content in _{ContentManagementDocTitle}_]
endif::[]
ifdef::katello,ubuntu[]
* {ContentManagementDocURL}Synchronizing-Ubuntu-Expanded-Security-Maintenance-content_content-management[Synchronizing Ubuntu Expanded Security Maintenance content in _{ContentManagementDocTitle}_]
endif::[]
ifdef::katello[]
* {ContentManagementDocURL}Basic_Content_Management_Workflow_content-management[Basic content management workflow in _{ContentManagementDocTitle}_]
endif::[]
ifdef::katello,debian,ubuntu[]
* {ContentManagementDocURL}adding-deb-repositories-by-using-web-ui[Adding Deb repositories by using {ProjectWebUI} in _{ContentManagementDocTitle}_]
endif::[]
ifdef::katello,almalinux,amazon_linux,centos,oracle_linux,red_hat_enterprise_linux,rocky_linux,suse_linux_enterprise_server[]
* {ContentManagementDocURL}adding-custom-rpm-repositories-by-using-web-ui[Adding {customrpm} repositories by using {ProjectWebUI} in _{ContentManagementDocTitle}_]
endif::[]
* {ContentManagementDocURL}adding-content-to-{project-context}[Adding content to {Project} in _{ContentManagementDocTitle}_]
* {ContentManagementDocURL}content-access-control-for-hosts[Content access control for {Project} hosts in _{ContentManagementDocTitle}_]
* {ContentManagementDocURL}Managing_Application_Lifecycles_content-management[Managing application lifecycles in _{ContentManagementDocTitle}_]
* {ContentManagementDocURL}managing-content-views-and-content-view-environments[Managing content views and content view environments in _{ContentManagementDocTitle}_]
* xref:common-deployment-scenarios[]
