:_mod-docs-content-type: CONCEPT

[id="using-the-{project-context}-container-registry"]
= Using the {Project} container registry

[role="_abstract"]
Use Podman or Docker to push container images to the {Project} container registry or pull images that you publish and promote through content views.

The {Project} container registry follows the Open Containers Initiative (OCI) specification, so you can push content to {Project} by using the same methods that apply to other container registries.
For more information about OCI, see link:https://opencontainers.org/[Open Container Initiative Distribution Specification].

ifndef::orcharhino[]
Container registries on {SmartProxies}::
On {SmartProxies} with content, the https://github.com/Katello/smart_proxy_container_gateway[Container Gateway] {SmartProxy} plugin acts as the container registry.
It caches authentication information from Katello and proxies incoming requests to Pulp.
The Container Gateway is available by default on {SmartProxies} with content.
endif::[]
