[id="{ProjectServerID}-with-external-database_{context}"]
= Configuring {ProjectServer} with external database

Running the `{foreman-installer}` command, used to install a {ProjectServer}, also installs PostgreSQL databases on the server.
However, you can configure your {ProjectServer} to use external databases instead.
Moving to external databases distributes the workload and can provide increased working memory for {Project}.

ifdef::satellite[]
[NOTE]
====
Red{nbsp}Hat does not provide support or tools for external database maintenance.
If you deploy {Project} with external databases, you will need to support and maintain the external databases yourself.
Managing backups, upgrades, and database tuning.
====
endif::[]

Consider using external databases if you plan to use your {Project} deployment for the following scenarios:

* Frequent remote execution tasks.
This requires a high volume of records in PostgreSQL and generates heavy database workloads.
* High disk I/O workloads from frequent repository synchronization or content view publishing.
This requires {Project} to create a record in PostgreSQL for each job.
* High volume of hosts.
* High volume of synced content.

ifeval::["{context}" == "planning"]
.Additional resources
ifndef::satellite[]
* For more information about using an external database, see {InstallingServerDocURL}using-external-databases_{project-context}[Using External Databases with {Project}] in _{InstallingServerDocTitle}_.
endif::[]
ifdef::satellite[]
* For more information about using an external database, see the following documents:
** {InstallingServerDocURL}using-external-databases_{project-context}[Using External Databases with {Project}] in _{InstallingServerDocTitle}_
** {InstallingServerDisconnectedDocURL}using-external-databases_{project-context}[Using External Databases with {Project}] in _{InstallingServerDisconnectedDocTitle}_
endif::[]
endif::[]
