:_mod-docs-content-type: CONCEPT

[id="using-ipxe-to-reduce-provisioning-times_{context}"]
= Using iPXE to reduce provisioning times

[role="_abstract"]
iPXE is an open-source network-boot firmware.
It provides a full PXE implementation enhanced with additional features, such as booting from an HTTP server.
For more information about iPXE, see link:https://ipxe.org[iPXE website].

ifdef::satellite[]
[IMPORTANT]
====
The iPXE network boot is **deprecated** and will be removed in a future release.
====
endif::[]

You can use iPXE if the following restrictions prevent you from using PXE:

* A network with unmanaged DHCP servers.
* A PXE service that is unreachable because of, for example, a firewall restriction.
* A TFTP UDP-based protocol that is unreliable because of, for example, a low-bandwidth network.

Booting a virtual machine has the following workflow:

. Virtual machine starts.
. iPXE retrieves the network credentials, including an HTTP URL, by using DHCP.
. iPXE loads the iPXE bootstrap template from {SmartProxy}.
. iPXE loads the iPXE template with MAC as a URL parameter from {SmartProxy}.
. iPXE loads the kernel and initial RAM disk of the installer.

Chainbooting iPXE has the following workflow:

. Host powers on.
. PXE driver retrieves the network credentials by using DHCP.
. PXE driver retrieves the PXELinux firmware `pxelinux.0` by using TFTP.
. PXELinux searches for the configuration file on the TFTP server.
. PXELinux chainloads iPXE `ipxe.lkrn` or `undionly-ipxe.0`.
. iPXE retrieves the network credentials, including an HTTP URL, by using DHCP again.
. iPXE chainloads the iPXE template from your Templates {SmartProxy}.
. iPXE loads the kernel and initial RAM disk of the installer.
