[id="Salt_Architecture_{context}"]
= Salt Architecture

You need a Salt Master that either runs on your {ProjectServer} or {SmartProxyServer} with the Salt plug-in enabled.
You can also use an existing Salt Master by installing and configuring the relevant {SmartProxy} features on the existing Salt Master host.

For more information on installing a Salt Master, consult the https://docs.saltproject.io/en/latest/[official Salt documentation].

.Terminology
* Managed hosts are referred to as _Salt Minions_.
* Information in form of key-value pairs gathered from Salt Minions is referred to as _Salt Grains_.
* Configuration templates are referred to as _Salt States_.
* Bundles of Salt States are referred to as _Salt Environments_.

Use the same Salt version on the Salt Master as you are using on your Salt Minions.
You can use content management in {Project} to provide managed hosts with the correct version of the Salt Minion client software.

.Required Ports from Salt Master to Salt Minions
[cols="24%,20%,18%,38%",options="header"]
|====
| Port | Protocol | Service | Required For
| 4505 and 4506 | TCP | HTTPS | Salt Master to Salt Minions
| 9191 | TCP | HTTPS | Salt API
|====
