:_mod-docs-content-type: CONCEPT

[id="configuring-sso-and-2fa-with-keycloak-wildfly-in-project_{context}"]
= Configuring SSO and 2FA with {keycloak-wildfly} in {Project}

[role="_abstract"]
:FeatureName: Configuring {Project} with {keycloak-wildfly}
include::snip_deprecated-feature.adoc[]

ifndef::satellite[]
[NOTE]
====
The default {keycloak} distribution is now based on Quarkus.

{keycloak-quarkus} replaces {keycloak-wildfly} in {Project} deployments.
For information about configuring {keycloak-quarkus} authentication, see xref:common/modules/con_configuring-sso-and-2fa-with-keycloak-quarkus-in-project.adoc#configuring-sso-and-2fa-with-keycloak-in-project_keycloak-quarkus[].

For information about migrating from {keycloak-wildfly} to {keycloak-quarkus}, see link:https://www.keycloak.org/migration/migrating-to-quarkus[Migrating to Quarkus distribution].
====
endif::[]
ifdef::satellite[]
[NOTE]
====
The {keycloak-wildfly}{nbsp}7 product family has reached End of Full Support.
Use {keycloak-quarkus} instead in your {Project} deployments.
For information about configuring {keycloak-quarkus} authentication, see xref:common/modules/con_configuring-sso-and-2fa-with-keycloak-quarkus-in-project.adoc#configuring-sso-and-2fa-with-keycloak-in-project_keycloak-quarkus[].

For information about migrating from {keycloak-wildfly} to {keycloak-quarkus}, see link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/26.0[documentation for {keycloak-quarkus}].
====
endif::[]

{keycloak} is an open-source identity and access management solution that provides authentication features, such as single sign-on functionality, user federation, and centralized authentication management.
With {keycloak-wildfly}, you can integrate {ProjectServer} with your existing {keycloak} server to delegate user authentication and authorization to {keycloak}.

{keycloak} users can log in using the following login methods:

* User name and password in {ProjectWebUI}
* User name and password in Hammer CLI

[NOTE]
====
{keycloak} users cannot use both {ProjectWebUI} and Hammer CLI authentication in {Project} at the same time.
====

* Time-based one-time password (TOTP)
ifndef::satellite,orcharhino[]
* {PIV} cards
endif::[]

ifdef::satellite[]
For information about {RHSSO}, see link:https://docs.redhat.com/en/documentation/red_hat_single_sign-on[{RHSSO} documentation].
endif::[]
