[id="defining-content-access-strategies-for-hosts-{context}"]
= Defining content access strategies for hosts

When defining your content lifecycle in {Project}, you can use content views and lifecycle environments to define which hosts can access which content and content versions.

{Project} includes _Default Organization View_ and the _Library_ lifecycle environment by default.

Default Organization View::
The _Default Organization View_ is the default content view in {Project} that contains all the content that is synchronized to {Project}.
After you update your content, such as by adding or removing a repository, the update is immediately reflected in _Default Organization View_.

Library::
The _Library_ lifecycle environment is the default lifecycle environment in {Project} that always contains the latest content from the repositories in a given content view.

In smaller deployments or when you do not require content versioning and environment promotion, you can associate a host to the _Library_ environment under the _Default Organization View_ without configuring additional lifecycle environments.

.Additional resources
* For more information, see {ContentManagementDocURL}[Managing content views] and {ContentManagementDocURL}Restricting_Hosts_Access_to_Content_content-management[Restricting hosts' access to content] in _{ContentManagementDocTitle}_.
* For examples of content view deployments, see xref:chap-Architecture_Guide-Deployment_Scenarios[].
