[id="Provisioning_Cloud_Instances_on_Microsoft_Azure_Resource_Manager_{context}"]
= Provisioning Cloud Instances on Microsoft Azure Resource Manager

:context: azure-provisioning
:azure-provisioning:
:CRname: Microsoft Azure Resource Manager

{ProjectName} can interact with Microsoft Azure Resource Manager, including creating new virtual machines and controlling their power management states.
Only image-based provisioning is supported for creating Azure hosts.
This includes provisioning using Marketplace images, custom images, and shared image gallery.

For more information about Azure Resource Manager concepts, see https://docs.microsoft.com/en-us/azure/azure-resource-manager/[Azure Resource Manager documentation].

.Prerequisites
include::snip_common-compute-resource-prereqs.adoc[]
* Ensure that you have the correct permissions to create an Azure Active Directory application.
For more information, see https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#required-permissions[Check Azure AD permissions] in the _Microsoft identity platform (Azure Active Directory for developers)_ documentation.
* You must create and configure an Azure Active Directory application and service principle to obtain Application or _client_ ID, Directory or _tenant_ ID, and Client Secret.
For more information, see https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[Use the portal to create an Azure AD application and service principal that can access resources] in the _Microsoft identity platform (Azure Active Directory for developers)_ documentation.
* Optional: If you want to use Puppet with Azure hosts, navigate to *Administer* > *Settings* > *Puppet* and enable the `Use UUID for certificates` setting to configure Puppet to use consistent Puppet certificate IDs.
* Based on your needs, associate a `finish` or `user_data` provisioning template with the operating system you want to use.
For more information about provisioning templates, see {ProvisioningDocURL}provisioning-templates_provisioning[Provisioning Templates].
* Optional: If you want the virtual machine to use a static private IP address, create a subnet in {Project} with the *Network Address* field matching the Azure subnet address.
* Before creating RHEL BYOS images, you must accept the image terms either in the Azure CLI or Portal so that the image can be used to create and manage virtual machines for your subscription.
