[id="Prerequisites_for_Image_Based_Provisioning_{context}"]
= Prerequisites for Image Based Provisioning

.Post-Boot Configuration Method
Images that use the `finish` post-boot configuration scripts require a managed DHCP server, such as {Project}'s integrated {SmartProxy} or an external {SmartProxy}.
The host must be created with a subnet associated with a DHCP {SmartProxy}, and the IP address of the host must be a valid IP address from the DHCP range.

It is possible to use an external DHCP service, but IP addresses must be entered manually.
The SSH credentials corresponding to the configuration in the image must be configured in {Project} to enable the post-boot configuration to be made.

Check the following items when troubleshooting a virtual machine booted from an image that depends on post-configuration scripts:

* The host has a subnet assigned in {ProjectServer}.
* The subnet has a DHCP {SmartProxy} assigned in {ProjectServer}.
* The host has a valid IP address assigned in {ProjectServer}.
* The IP address acquired by the virtual machine using DHCP matches the address configured in {ProjectServer}.
* The virtual machine created from an image responds to SSH requests.
* The virtual machine created from an image authorizes the user and password, over SSH, which is associated with the image being deployed.
* {ProjectServer} has access to the virtual machine via SSH keys.
This is required for the virtual machine to receive post-configuration scripts from {ProjectServer}.

.Pre-Boot Initialization Configuration Method
Images that use the `cloud-init` scripts require a DHCP server to avoid having to include the IP address in the image.
A managed DHCP {SmartProxy} is preferred.
The image must have the `cloud-init` service configured to start when the system boots and fetch a script or configuration data to use in completing the configuration.

Check the following items when troubleshooting a virtual machine booted from an image that depends on initialization scripts included in the image:

* There is a DHCP server on the subnet.
* The virtual machine has the `cloud-init` service installed and enabled.

ifdef::satellite[]
For information about the differing levels of support for `finish` and `cloud-init` scripts in virtual-machine images, see the Red Hat Knowledgebase Solution https://access.redhat.com/solutions/2987171[What are the supported compute resources for the finish and cloud-init scripts] on the Red Hat Customer Portal.
endif::[]
