[[Repository_Sets]]
= Repository Sets in {Project}

ifdef::satellite[]
Both Red Hat content and {customcontent} in {Project} have similarities:
endif::[]

ifdef::foreman-el,katello[]
Both Red Hat content and non-RH {customcontent} in {Project} have similarities:
endif::[]

ifdef::orcharhino[]
Content from upstream as well as from Canonical, Oracle, Red Hat, SUSE, and custom content in {Project} have similarities:
endif::[]

Repository sets show available repositories to each host. You can enable and disable the repositories.
If your host is subscribed to a particular Content View and Lifecycle environment, the default repository set is limited to the repositories that are specifically available to that host. However, you also have the option to show all.

The default states for repository sets are Enabled and Disabled. You can override the default state by using the action menus on each table row by changing Override to disabled, Override to enabled, and Reset to default. The Status Flag will indicate that the repository has been overridden.

On the Overview tab for a selected host in the Content View Details, you can see the specific content view and environment for the host. For hosts not in a default view or a Lifecycle environment, the repository tab looks different. It will default to showing only the repositories that are relevant to the host. You can select Show all or Limit to environment to see the available repositories.
