[id="Managing_Red_Hat_Subscriptions_{context}"]
= Managing Red Hat subscriptions

{ProjectName} can import content from the Red{nbsp}Hat Content Delivery Network (CDN).
{Project} requires a Red{nbsp}Hat subscription manifest to find, access, and download content from the corresponding repositories.
You must have a Red{nbsp}Hat subscription manifest containing a subscription allocation for each organization on {ProjectServer}.
All subscription information is available on the {RHCloud}.

Use this chapter to import a Red{nbsp}Hat subscription manifest and manage the manifest within the {ProjectWebUI}.

.Subscription allocations and organizations
You can manage more than one organization if you have more than one subscription allocation.
{Project} requires a single allocation for each organization configured in {ProjectServer}.
The advantage of this is that each organization maintains separate subscriptions so that you can support multiple organizations, each with their own Red{nbsp}Hat accounts.

.Future-dated subscriptions
You can use future-dated subscriptions in a subscription manifest.
When you add future-dated subscriptions to your manifest before the expiry date of the existing subscriptions, you can have uninterrupted access to repositories.

.Subscriptions service capabilities
The Subscriptions service is a service on the {RHCloud} that helps organizations track and manage their Red{nbsp}Hat subscription usage across connected and disconnected environments. 

* Allows customers to view subscription usage.
* When configured, it displays usage data from both connected and disconnected environments.
* Tracks Red{nbsp}Hat product usage and capacity at the organization or account level.
* Generates a daily snapshot of usage data across all tracked systems.
* Displays data in a filterable dashboard at the {RHCloud}.
* Collects historical data for analytics, purchasing decisions, capacity planning, and risk mitigation.
* Supports the transition to Simple Content Access (SCA), which enforces subscriptions across the organization rather than on individual systems.

.Configuring your system to use the Subscriptions service
ifndef::satellite[]
.Prerequisites
* Enable the `foreman_rh_cloud` plugin:
[subs="nowrap" subs="+quotes,verbatim,attributes"]
----
# foreman-installer --enable-foreman-plugin-rh-cloud
----

Connected {Project} Users::
Configure the `foreman_rh_cloud` plugin to share inventory information with the Hybrid Cloud Console.
Ensure that the *Automatic Inventory Upload* setting is enabled.
The plugin enables the subscriptions service to track usage information across connected systems.

You can configure the plugin to omit data that is not needed for subscription tracking, such as host names and IP addresses.
endif::[]

Disconnected users::
If you cannot or do not want to connect your system directly, you can export a local summary of your product usage and import it into a CMDB, spreadsheet, or another tracking tool.

Disconnected ({Project})::
Export usage data in one of the following ways:

** Through the `foreman_rh_cloud` plugin, which generates its report locally and allows you to download it from the {ProjectWebUI}.  
This report is in JSON format and is most suitable for automated scripts or machine ingestion. 
You can generate this report by using CLI:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# foreman-rake rh_cloud_inventory:report:generate
----

** Through the *Host - Installed Products* report by navigating to *Monitor* > *Reports* > *Report Templates*. 
This report can be exported in multiple formats, including CSV, HTML, and YAML, for use in spreadsheet tools or other applications.

ifndef::orcharhino[]
.Additional resources
ifndef::satellite[]
* {InstallingServerDocURL}configuring-{project-context}-server-to-consume-content-from-a-custom-cdn_{project-context}[Configuring {ProjectServer} to Consume Content from a Custom CDN] in _{InstallingServerDocTitle}_.
endif::[]
ifdef::satellite[]
* {InstallingServerDisconnectedDocURL}configuring-{project-context}-server-to-consume-content-from-a-custom-cdn_{project-context}[Configuring {ProjectServer} to Consume Content from a Custom CDN] in _{InstallingServerDisconnectedDocTitle}_.
endif::[]
endif::[]
