[id="Installing_Server_Connected_{context}"]
= Installing {ProjectServer}

ifdef::satellite[]
When you install {ProjectServer} from a connected network, you can obtain packages and receive updates directly from the Red Hat Content Delivery Network.

[NOTE]
====
You cannot register {ProjectServer} to itself.
====

Use the following procedures to install {ProjectServer}, perform the initial configuration, and import subscription manifests.
For more information on subscription manifests, see {ContentManagementDocURL}Managing_Red_Hat_Subscriptions_content-management[Managing Red Hat Subscriptions] in _{ContentManagementDocTitle}_.
endif::[]

ifndef::satellite[]
Use the following procedures to install {ProjectServer} and perform the initial configuration.
endif::[]

ifdef::foreman-el[]
On {EL}, you can install {Project} with or without the Katello plugin.
If you are a new user, consider installing {Project} with the Katello plugin.
endif::[]

Note that the {Project} installation script is based on Puppet, which means that if you run the installation script more than once, it might overwrite any manual configuration changes.
⁠
To avoid this and determine which future changes apply, use the `--noop` argument when you run the installation script.
This argument ensures that no actual changes are made.
Potential changes are written to `{installer-log-file}`.

Files are always backed up and so you can revert any unwanted changes.
For example, in the foreman-installer logs, you can see an entry similar to the following about Filebucket:

[options="wrap"]
----
/Stage[main]/Dhcp/File[/etc/dhcp/dhcpd.conf]: Filebucketed /etc/dhcp/dhcpd.conf to puppet with sum 622d9820b8e764ab124367c68f5fa3a1
----

You can restore the previous file as follows:

[options="wrap"]
----
# puppet filebucket -l \
restore /etc/dhcp/dhcpd.conf 622d9820b8e764ab124367c68f5fa3a1
----
