[id="Using_PXE_to_Provision_Hosts_{context}"]
= Using PXE to provision hosts

You can provision bare-metal instances with {Project} by using one of the following methods:

Unattended Provisioning::
New hosts are identified by a MAC address.
{ProjectServer} provisions the host by using a PXE boot process.

Unattended Provisioning with Discovery::
New hosts use PXE boot to load the {Project} Discovery service.
This service identifies hardware information about the host and lists it as an available host to provision.
For more information, see xref:discovering-hosts-on-a-network_{context}[].

PXE-less Provisioning::
ifndef::satellite[]
New hosts are provisioned with a boot disk or PXE-less discovery image that {ProjectServer} generates.

PXE-less Provisioning with Discovery::
New hosts use an ISO boot disk that loads the {Project} Discovery service.
This service identifies hardware information about the host and lists it as an available host to provision.
For more information, see xref:discovery-in-pxeless-mode_{context}[].
endif::[]
ifdef::satellite[]
New hosts are provisioned with a boot disk image that {ProjectServer} generates.
endif::[]

ifndef::satellite[]
[NOTE]
====
Discovery workflows are only available when the Discovery plugin is installed.
For more information, see xref:discovering-hosts-on-a-network_{context}[].
====
endif::[]

.BIOS and UEFI support
With {ProjectName}, you can perform both BIOS and UEFI based PXE provisioning.
Both BIOS and UEFI interfaces work as interpreters between the operating system and firmware of a computer, initializing hardware components and starting the operating system at boot time.

.PXE loaders
In {Project} provisioning, the PXE loader option defines the DHCP `filename` option to use during provisioning.

* For BIOS systems, select the *PXELinux BIOS* option to enable a provisioned host to download the `pxelinux.0` file over TFTP.
* For UEFI systems, select the *Grub2 UEFI* option to enable a TFTP client to download `grubx64.efi` file, or select the *Grub2 UEFI HTTP* option to enable an UEFI HTTP client to download `grubx64.efi` with the HTTP Boot feature.

ifndef::satellite[]
{ProjectName} supports UEFI Secure Boot.
SecureBoot PXE loaders enable a client to download the `shim.efi` bootstrap boot loader that then loads the signed `grubx64.efi`.
Use the *Grub2 UEFI SecureBoot* PXE loader for PXE-boot provisioning or *Grub2 UEFI HTTPS SecureBoot* for HTTP-boot provisioning.

By default, you can provision operating systems from the vendor of the operating system of your {ProjectServer} on Secure Boot enabled hosts.
To provision operating systems on Secure Boot enabled hosts from different vendors, you have to provide signed shim and GRUB2 binaries provided by the vendor of your operating system.
ifndef::orcharhino[]
For more information, see:

* xref:configuring-{smart-proxy-context}-to-provision-almalinux-on-Secure-Boot-enabled-hosts[]
* xref:configuring-{smart-proxy-context}-to-provision-debian-on-Secure-Boot-enabled-hosts[]
* xref:configuring-{smart-proxy-context}-to-provision-rocky-on-Secure-Boot-enabled-hosts[]
* xref:configuring-{smart-proxy-context}-to-provision-ubuntu-on-Secure-Boot-enabled-hosts[]
endif::[]
endif::[]

ifdef::satellite[]
For more information about supported workflows, see https://access.redhat.com/solutions/2674001[Supported architectures and provisioning scenarios].
endif::[]
ifndef::orcharhino,satellite[]
Other PXE loaders like *PXELinux UEFI*, *Grub2 ELF* or *iPXE Chain*, require additional configuration.
These workflows are not documented.
endif::[]

ifndef::satellite[]
.Template association with operating systems
For BIOS provisioning, you must associate a PXELinux template with the operating system.
For UEFI provisioning, you must associate a PXEGrub2 template with the operating system.
If you associate both PXELinux and PXEGrub2 templates, {Project} deploys configuration files for both on a TFTP server, so that you can switch between PXE loaders easily.
endif::[]

.Bonded network interfaces
You can configure a bonded interface that {Project} will use during the installation process, for example, to download installation content.
After provisioning completes, the provisioned system can also use the bonded interface.

[IMPORTANT]
====
{Project} cannot PXE boot a bonded interface that requires configuration on a network switch as well as on your host.

After your host loads the kernel of an installer or the kernel of an operating system, bonding works as expected.
Therefore, you can use a boot disk to work around PXE boot limitations when your bonded interface requires configuration on both a switch and your host.
====
