[id="Load_Balancing_Solution_Architecture_{context}"]
= Load balancing solution architecture

This guide outlines how to prepare {ProjectServer} and {SmartProxyServer} for load balancing, and provides guidelines on how to configure a load balancer and register clients in a load-balanced setup.

A load balancer works with the following services and features:

* Registration using `subscription-manager`
* Content management with Yum repositories
* Optional: Puppet

[NOTE]
====
In the load-balanced setup, a load balancer distributes load only for the services and features mentioned above.
If other services, such as provisioning or virt-who, are running on the individual {SmartProxies}, you must access them directly through {SmartProxies} and not through the load balancer.
====

.Managing Puppet limitations
Puppet Certificate Authority (CA) management does not support certificate signing in a load-balanced setup.
Puppet CA stores certificate information, such as the serial number counter and CRL, on the file system.
Multiple writer processes that attempt to use the same data can corrupt it.

To manage this Puppet limitation, complete the following steps:

. Configure Puppet certificate signing on one {SmartProxyServer}, typically the first system where you configure {SmartProxyServer} for load balancing.
. Configure the clients to send CA requests to port 8141 on a load balancer.
. Configure a load balancer to redirect CA requests from port 8141 to port 8140 on the system where you configure {SmartProxyServer} to sign Puppet certificates.
