[id="command-line-assistant-on-{project-context}-hosts"]
= Command-line assistant on {Project} hosts

You can use the command-line assistant powered by RHEL Lightspeed on systems that are registered to {ProjectName}.
The command-line assistant is available on {RHEL} 9.6, 10.0, or later.

You can proxy the assistant traffic through {ProjectServer} or {SmartProxyServer}.
To do so, you have to modify configuration of the command-line assistant.
For more information, see {RHELDocsBaseURL}10/html/interacting_with_the_command-line_assistant_powered_by_rhel_lightspeed/provisioning-the-command-line-assistant-to-rhel-deployments-with-red-hat-satellite[Provisioning the command-line assistant to RHEL deployments with Red Hat Satellite].

Note that if you enable the {advisorengine} plugin, {Project} will not be able to intermediate the connection for the command-line assistant.

[role="_additional-resources"]
.Additional resources
* {RHELDocsBaseURL}10/html/interacting_with_the_command-line_assistant_powered_by_rhel_lightspeed/index[_{RHEL}{nbsp}10 Interacting with the command-line assistant powered by RHEL Lightspeed_]
