[id="converting-a_host-with-convert2rhel_{context}"]
= Converting a Host to {RHEL} with Convert2RHEL

Convert2RHEL enables the conversion of {RHEL} derivative distributions into a supportable {RHEL} state while retaining existing applications and configurations.

The conversion process is similar to a minor release upgrade of {RHEL} in which every RPM package on the system is replaced.
Third-party packages and non-{Team} packages not available in {RHEL} are not replaced.

Convert2RHEL removes unnecessary packages such as logos, or packages known to cause issues during the conversion, and replaces the `CentOS-release` package with the `rhel-release` package.
It subscribes the system to {ProjectName} and replaces all packages signed by CentOS.
ifdef::satellite[]
For {Project}, it also subscribes the system to {Team} Subscription Management.
endif::[]

The amount of time taken to do this can vary depending on how many packages need to be replaced, network speed, storage speed, and similar variables.

Use the global registration template to register and subscribe your system before the conversion.
For more information, see {ManagingHostsDocURL}registering-a-host_managing-hosts[Registering a Host to {ProjectName} Using the Global Registration Template] in the _Managing Hosts_ guide.

To convert hosts to {RHEL} with convert2RHEL, you must complete the following procedures:

. xref:installing-convert2rhel_{context}[].
. xref:Creating_an_Activation_Key_{context}[].
. xref:preparing-the-host-group_{context}[].
. xref:registering-hosts-for-conversion_{context}[].
. xref:converting-hosts-with-convert2rhel_{context}[]

.Prerequisites
ifndef::orcharhino[]
* You must have completed the steps listed in https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/converting_from_an_rpm-based_linux_distribution_to_rhel/index#proc_preparing-for-a-rhel-conversion_converting-from-a-linux-distribution-to-rhel[Preparing for a RHEL conversion].
endif::[]
* If you are providing the organization ID and activation key to register and subscribe your system, you must have created an activation key in {ProjectName}.
ifdef::satellite[]
For {Project} you can also create an activation key in Subscription Manager.
endif::[]
ifndef::orcharhino[]
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in this guide, and https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/using_red_hat_subscription_management/index#activation_keys_con[Understanding activation keys] in Subscription Manager documentation.
endif::[]
* Ensure you have a subscription manifest uploaded to your {Project} and that there are sufficient {RHEL} subscriptions for the conversion.
* If you are providing the organization ID and activation key to register and subscribe your system, you must have created an activation key in {ProjectName} or Subscription Manager.
ifndef::orcharhino[]
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in this guide, and https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html-single/using_red_hat_subscription_management/index#activation_keys_con[Understanding activation keys] in Subscription Manager documentation.
endif::[]
* Ensure you have a subscription manifest uploaded to your {Project} and that there are sufficient {RHEL} subscriptions for the conversion.
* If you are accessing {RHEL} packages using {ProjectServer}, you must use the organization ID and activation key to run the `convert2rhel` command.
