:_mod-docs-content-type: CONCEPT

[id="http-booting-in-{project-context}"]
= HTTP booting in {Project}

[role="_abstract"]
You can use HTTP booting to boot systems over a network using HTTP.

HTTP booting requirements with managed DHCP::
* Client requirements:
** All the network-based firewalls are configured to allow clients on the subnet to access the {SmartProxy}.
For more information, see xref:networking-considerations-in-{project-context}[].
** Your client has access to the DHCP and DNS servers.
** Your client has access to the HTTP UEFI Boot {SmartProxy}.
* Network requirements:
** Optional: If the host and the DHCP server are separated by a router, configure the DHCP relay agent and point to the DHCP server.
* {Project} requirements:
+
[NOTE]
====
Although TFTP protocol is not used for HTTP UEFI Booting, {Project} uses TFTP {SmartProxy} API to deploy boot loader configuration.
====
+
** Both {ProjectServer} and {SmartProxy} have DNS configured and are able to resolve provisioned host names.
** The UDP ports 67 and 68 are accessible by the client so that the client can send and receive a DHCP request and offer.
** Ensure that the TCP port 8000 is open for the client to download the boot loader and Kickstart templates from the {SmartProxy}.
** The TCP port {smartproxy_port} is open for the client to download the boot loader from the {SmartProxy} using the HTTPS protocol.
** The subnet that functions as the host's provisioning interface has a DHCP {SmartProxy}, an HTTP Boot {SmartProxy}, a TFTP {SmartProxy}, and a Templates {SmartProxy}

HTTP booting requirements with unmanaged DHCP::
* Client requirements:
** HTTP UEFI Boot URL must be set to one of:
*** `\http://{smartproxy-example-com}:8000`
*** `\https://{smartproxy-example-com}:{smartproxy_port}`
** Ensure that your client has access to the DHCP and DNS servers.
** Ensure that your client has access to the HTTP UEFI Boot {SmartProxy}.
** Ensure that all the network-based firewalls are configured to allow clients on the subnet to access the {SmartProxy}.
For more information, see xref:networking-considerations-in-{project-context}[].
* Network requirements:
** An unmanaged DHCP server available for clients.
** An unmanaged DNS server available for clients.
In case DNS is not available, use IP address to configure clients.
* {Project} requirements:
+
[NOTE]
====
Although TFTP protocol is not used for HTTP UEFI Booting, {Project} use TFTP {SmartProxy} API to deploy boot loader configuration.
====
+
** Ensure that both {ProjectServer} and {SmartProxy} have DNS configured and are able to resolve provisioned host names.
** Ensure that the UDP ports 67 and 68 are accessible by the client so that the client can send and receive a DHCP request and offer.
** Ensure that the TCP port 8000 is open for the client to download boot loader and Kickstart templates from the {SmartProxy}.
** Ensure that the TCP port {smartproxy_port} is open for the client to download the boot loader from the {SmartProxy} through HTTPS.
** Ensure that the host provisioning interface subnet has an HTTP Boot {SmartProxy} set.
** Ensure that the host provisioning interface subnet has a TFTP {SmartProxy} set.
** Ensure that the host provisioning interface subnet has a Templates {SmartProxy} set.
