[id="Load_Balancing_Considerations_{context}"]
= Load Balancing Considerations

Distributing load between several {SmartProxyServers} prevents any one {SmartProxy} from becoming a single point of failure.
Configuring {SmartProxies} to use a load balancer can provide resilience against planned and unplanned outages.
This improves availability and responsiveness.

Consider the following guidelines when configuring load balancing:

* If you use Puppet, Puppet certificate signing is assigned to the first {SmartProxy} that you configure.
If the first {SmartProxy} is down, clients cannot obtain Puppet content.
* This solution does not use Pacemaker or other similar HA tools to maintain one state across all {SmartProxies}.
To troubleshoot issues, reproduce the issue on each {SmartProxy}, bypassing the load balancer.

.Additional Maintenance Required for Load Balancing
Configuring {SmartProxies} to use a load balancer results in a more complex environment and requires additional maintenance.

The following additional steps are required for load balancing:

* You must ensure that all {SmartProxies} have the same Content Views and synchronize all {SmartProxies} to the same Content View versions
* You must upgrade each {SmartProxy} in sequence
* You must backup each {SmartProxy} that you configure regularly

.Upgrading {SmartProxyServersTitle} in a Load Balancing Configuration
ifdef::satellite[]
To upgrade {SmartProxyServers} from {ProductVersionPrevious} to {ProductVersion}, complete the {UpgradingDocURL}upgrading_capsule_server[Upgrading {SmartProxyServers}] procedure in _{UpgradingDocTitle}_.
endif::[]
There are no additional steps required for {SmartProxyServers} in a load balancing configuration.
