[id="Adding_Network_Interfaces_{context}"]
= Adding Network Interfaces

{Project} supports specifying multiple network interfaces for a single host.
You can configure these interfaces when creating a new host as described in xref:Creating_a_Host_{context}[] or when editing an existing host.

There are several types of network interfaces that you can attach to a host.
When adding a new interface, select one of:

* *Interface*: Allows you to specify an additional physical or virtual interface.
There are two types of virtual interfaces you can create.
Use *VLAN* when the host needs to communicate with several (virtual) networks using a single interface, while these networks are not accessible to each other.
Use *alias* to add an additional IP address to an existing interface.
+
For more information about adding a physical interface, see xref:Adding_a_Physical_Interface_{context}[].
+
For more information about adding a virtual interface, see xref:Adding_a_Virtual_Interface_{context}[].

* *Bond*: Creates a bonded interface.
NIC bonding is a way to bind multiple network interfaces together into a single interface that appears as a single device and has a single MAC address.
This enables two or more network interfaces to act as one, increasing the bandwidth and providing redundancy.
For more information, see xref:Adding_a_Bonded_Interface_{context}[].

* *BMC*: Baseboard Management Controller (BMC) allows you to remotely monitor and manage the physical state of machines.
For more information about BMC, see {InstallingServerDocURL}enabling-power-management-on-managed-hosts_{project-context}[Enabling Power Management on Managed Hosts] in _{InstallingServerDocTitle}_.
For more information about configuring BMC interfaces, see xref:Adding_a_Baseboard_Management_Controller_Interface_{context}[].

[NOTE]
====
Additional interfaces have the *Managed* flag enabled by default, which means the new interface is configured automatically during provisioning by the DNS and DHCP {SmartProxyServers} associated with the selected subnet.
This requires a subnet with correctly configured DNS and DHCP {SmartProxyServers}.
If you use a Kickstart method for host provisioning, configuration files are automatically created for managed interfaces in the post-installation phase at `/etc/sysconfig/network-scripts/ifcfg-_interface_id_`.
====

[NOTE]
====
Virtual and bonded interfaces currently require a MAC address of a physical device.
Therefore, the configuration of these interfaces works only on bare-metal hosts.
====
