[id="Content-Views-in-{ProjectNameID}_{context}"]
= Content Views in {ProjectName}

A content view is a deliberately curated subset of content that your hosts can access.
By creating a content view, you can define the software versions used by a particular environment or {SmartProxyServer}.

Each content view creates a set of repositories across each environment.
The {ProjectServer} stores and manages these repositories.
For example, you can create content views in the following ways:

* A content view with older package versions for a production environment and another content view with newer package versions for a Development environment.
* A content view with a package repository required by an operating system and another content view with a package repository required by an application.
* A composite content view that combines other content views for easier management.

.Default Organization View
A _Default Organization View_ is an application-controlled content view for all content that is synchronized to {Project}.
With the Default Organization View, you can register a host to {Project} and access content by using a subscription and without manipulating content views and lifecycle environments.

.Promoting a content view across environments
When you promote a content view from one environment to the next environment in the application life cycle, the respective repository on {ProjectServer} updates and publishes the packages.

.Promoting a package from Development to Testing
====
The repositories for Testing and Production contain the `_<example_software>_-1.0-0.{client-pkg-arch}.{client-pkg-ext}` package:

|===
| | Development | Testing | Production

| Version of the content view | Version 2 | Version 1 | Version 1
| Contents of the content view | _<example_software>_-1.1-0.{client-pkg-arch}.{client-pkg-ext} | _<example_software>_-1.0-0.{client-pkg-arch}.{client-pkg-ext} | _<example_software>_.0-0.{client-pkg-arch}.{client-pkg-ext}
|===

If you promote Version 2 of the content view from Development to Testing, the repository for Testing updates to contain the `_example_software_-1.1-0.{client-pkg-arch}.{client-pkg-ext}` package:

|===
| | Development | Testing | Production

| Version of the content view | Version 2  | *Version 2* | Version 1 
| Contents of the content view | _<example_software>_-1.1-0.{client-pkg-arch}.{client-pkg-ext} | *_<example_software>_-1.1-0.{client-pkg-arch}.{client-pkg-ext}* | _<example_software>_-1.0-0.{client-pkg-arch}.{client-pkg-ext}
|===

This ensures systems are designated to a specific environment but receive updates when that environment uses a new version of the content view.
====

ifeval::["{context}" == "planning"]
[role="_additional-resources"]
.Additional resources

* For details on managing content views, see {ContentManagementDocURL}Managing_Content_Views_content-management[_{ContentManagementDocTitle}_].
endif::[]
