:_mod-docs-content-type: CONCEPT

[id="content-view-environment-categories"]
= Content view environment categories

[role="_abstract"]
{Project} labels content view environments according to the lifecycle environment and content view they represent.

The content view environments available in your organization fall into the following categories:

Library environment::
{Project} assigns the Library environment to represent the Library lifecycle environment and the *Default Organization View* content view.
{Project} labels this environment as `Library`.

Unpromoted content views::
For each content view that you publish but do not promote to a lifecycle environment, {Project} creates a content view environment.
{Project} labels these environments using the format: `Library/<content_view_label>`.

Promoted content views::
For each content view that you promote to a specific lifecycle environment, {Project} creates a corresponding content view environment.
{Project} labels these environments using the format: `<lifecycle_environment_label>/<content_view_label>`.
