[id="Content_Delivery_Network_Structure_{context}"]
= Content Delivery Network structure

ifdef::katello,orcharhino[]
[NOTE]
====
Information in this section only applies if you consume Red{nbsp}Hat content using a Red{nbsp}Hat manifest.
====
endif::[]

Red{nbsp}Hat Content Delivery Network (CDN), located at `cdn.redhat.com`, is a geographically distributed series of static webservers which include content and errata designed to be used by systems.
This content can be accessed directly through a system registered using Subscription Manager or through the {ProjectWebUI}.
The accessible subset of the CDN is configured through content available to a system using https://access.redhat.com/management/[Red{nbsp}Hat Subscription Management] or using {ProjectServer}.

Red{nbsp}Hat Content Delivery network is protected by X.509 certificate authentication to ensure that only valid users can access it.

.Directory structure of the CDN

----
$ tree -d -L 11
└── content  // <1>
    ├── beta  // <2>
    │   └── rhel  // <3>
    │       └── server  // <4>
    │           └── 7 // <5>
    │               └── x86_64  // <6>
    │                   └── sat-tools  // <7>
    └── dist
        └── rhel
            └── server
                └── 7
                ├── 7.2
                │   └── x86_64
                │       └── kickstart
                └── 7Server
                    └── x86_64
                        └── os
----

<1> The `content` directory.
<2> Directory responsible for the lifecycle of the content.
Common directories include `beta` (for Beta code), `dist` (for Production) and `eus` (For Extended Update Support) directories.
<3> Directory responsible for the product name.
Usually `rhel` for {RHEL}.
<4> Directory responsible for the type of the product.
For {RHEL} this might include `server`, `workstation`, and `computenode` directories.
<5> Directory responsible for the release version, such as `7`, `7.2` or `7Server`.
<6> Directory responsible for the base architecture, such as `i386` or `x86_64`.
<7> Directory responsible for the repository name, such as `sat-tools`, `kickstart`, `rhscl`.
Some components have additional subdirectories which might vary.

This directory structure is also used in the Red{nbsp}Hat Subscription Manifest.
