[id="provisioning-templates_{context}"]
= Provisioning Templates

A provisioning template defines the way {ProjectServer} installs an operating system on a host.

{ProjectName} includes many template examples.
In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning templates* to view them.
You can create a template or clone a template and edit the clone.
For help with templates, navigate to *Hosts* > *Provisioning templates* > *Create Template* > *Help*.

Templates accept the Embedded Ruby (ERB) syntax.
For more information, see {ManagingHostsDocURL}Template_Writing_Reference_managing-hosts[Template Writing Reference] in _Managing Hosts_.

You can download provisioning templates.
Before you can download the template, you must create a debug certificate.
ifdef::satellite[]
For more information, see {ContentManagementDocURL}Managing_Organizations-Creating_an_Organization_Debug_Certificate[Creating an Organization Debug Certificate] in the _Content Management Guide_.
endif::[]
ifndef::satellite[]
For more information, see {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate] in the in the _Managing Organizations and Locations in {Project} Guide_.
endif::[]

You can synchronize templates between {ProjectServer} and a Git repository or a local directory.
For more information, see {ManagingHostsDocURL}Synchronizing_Templates_Repositories_managing-hosts[Synchronizing Templates Repositories] in the _Managing Hosts_ guide.

To view the history of changes applied to a template, navigate to *Hosts* > *Provisioning templates*, select one of the templates, and click *History*.
Click *Revert* to override the content with the previous version.
You can also revert to an earlier change.
Click *Show Diff* to see information about a specific change:

* The *Template Diff* tab displays changes in the body of a provisioning template.
* The *Details* tab displays changes in the template description.
* The *History* tab displays the user who made a change to the template and date of the change.
