:_mod-docs-content-type: CONCEPT

[id="installing-a-{project-context}-server"]
= Installing a {ProjectServer}

[role="_abstract"]
Installing an instance of {ProjectServer} on a dedicated server is the first step to a working {Project} infrastructure.

ifdef::satellite[]
You can install a {ProjectServer} in a connected or disconnected setup:

* Connected deployment is suitable for networked environments where your {ProjectServer} is connected to the Red{nbsp}Hat CDN.
* Disconnected deployment is suitable for high-security environments where direct internet access is restricted or prohibited.

In the disconnected setup, your {ProjectServer} uses {ISS} (ISS) to obtain content from another, connected {ProjectServer}.
Although a disconnected {ProjectServer} is isolated from Red{nbsp}Hat CDN, you can still provision hosts with the latest security updates, errata, packages, and other content.
endif::[]

A default {ProjectServer} installation includes installing PostgreSQL databases on the server.
However, you can configure your {ProjectServer} to use external databases instead.
Moving to external databases distributes the workload and can reduce overall {Project} memory usage.

ifdef::satellite[]
[NOTE]
====
Red{nbsp}Hat does not provide support or tools for external database maintenance.
If you deploy {Project} with external databases, you will need to support and maintain the external databases yourself.
====
endif::[]

Consider using external databases if you plan to use your {Project} deployment for the following scenarios:

* Frequent remote execution tasks.
This requires a high volume of records in PostgreSQL and generates heavy database workloads.
ifdef::katello,orcharhino,satellite[]
* High disk I/O workloads from frequent repository synchronization or content view publishing.
This requires {Project} to create a record in PostgreSQL for each job.
endif::[]
* High volume of hosts.
ifdef::katello,orcharhino,satellite[]
* High volume of synchronized content.
endif::[]

.Additional resources
* {InstallingServerDocURL}[_{InstallingServerDocTitle}_]
ifdef::orcharhino,satellite[]
* {InstallingServerDisconnectedDocURL}[_{InstallingServerDisconnectedDocTitle}_]
endif::[]
ifdef::orcharhino[]
* {AdministeringDocURL}Migrating_from_Internal_Databases_to_External_Databases_admin[Migrating from internal {Project} databases to external databases in _{AdministeringDocTitle}_]
endif::[]
