[id="Migrating_from_Internal_Databases_to_External_Databases_{context}"]
= Migrating from Internal {Project} Databases to External Databases

When you install {ProjectName}, the *{foreman-installer}* command installs PostgreSQL databases on the same server as {Project}.
If you are using the default internal databases but want to start using external databases to help with the server load, you can migrate your internal databases to external databases.

To confirm whether your {ProjectServer} has internal or external databases, you can query the status of your databases:

For PostgreSQL, enter the following command:
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service status --only postgresql
----

ifdef::satellite[]
Red Hat does not provide support or tools for external database maintenance.
This includes backups, upgrades, and database tuning.
You must have your own database administrator to support and maintain external databases.
endif::[]

ifndef::foreman-deb[]
To migrate from the default internal databases to external databases, you must complete the following procedures:

. xref:preparing-a-host-for-external-databases_{context}[].
Prepare a {RHEL} 8 server to host the external databases.
. xref:installing-postgresql_{context}[].
Prepare PostgreSQL with databases for {Project}, Pulp and Candlepin with dedicated users owning them.
. xref:migrating-to-external-databases_{context}[].
Edit the parameters of `{foreman-installer}` to point to the new databases, and run `{foreman-installer}`.
endif::[]
