:_mod-docs-content-type: CONCEPT

[id="cloning-process-overview"]
= Cloning process overview

[role="_abstract"]
The cloning process involves backing up your source server, transferring it to a target server, and reconfiguring it to operate in the new environment.

You cannot use the {Project} clone tool on a {SmartProxyServer}.
Instead, you must backup the existing {SmartProxyServer}, restore it on the target server, and then reconfigure {SmartProxyServer}.

Cloning {ProjectServer} consists of the following high-level steps:

. Back up the source server.
. Clone the source server to the target server.
. Power off the source server.
. Update the network configuration on the target server to match the IP address of the target server with its new host name.
. Test the new target server.

Note that because of the high volume of data that you must copy and transfer as part of the cloning process, it can take a significant amount of time to complete.

[NOTE]
====
If you create a new instance of the {ProjectServer}, decommission the old instances after restoring the backup.
Cloned instances are not supposed to run in parallel in a production environment.
====

Review the following definitions before proceeding:

*Source server*:: The old server to be cloned.

*Target server*:: The new server that you copy files to and clone the source server to.
