:_mod-docs-content-type: CONCEPT

[id="supported-usage-of-project-components_{context}"]
= Supported usage of {Project} components

[role="_abstract"]
Usage of all {ProjectName} components is supported within the context of {ProjectName} only as described below.

ifdef::satellite[]
{RHELServer}::
Each {ProjectName} subscription includes one supported instance of {RHELServer}.
Reserve this instance solely for the purpose of running {ProjectName}.
+
Not supported: Using the operating system included with {Project} to run other daemons, applications, or services within your environment.
endif::[]

Foreman::
You can extend Foreman with plugins packaged with {ProjectName}.
ifdef::satellite[]
See https://access.redhat.com/articles/1343683[Satellite 6 Component Versions] in Red{nbsp}Hat Knowledgebase for information about supported Foreman plugins.
+
Not supported: Extending Foreman with plugins in the _{ProjectName} Optional_ repository.
+
endif::[]
{ProjectName} also includes components, configuration, and functionality to provision and configure operating systems other than {EL}.
ifdef::satellite[]
While these features are included, Red{nbsp}Hat supports their usage only for {RHEL}.
endif::[]

Pulp::
Interact with Pulp only by using the {ProjectWebUI}, CLI, and API.
+
Not supported: Direct modification or interaction with the Pulp local API or database.
This can cause irreparable damage to the {ProjectName} databases.

Candlepin::
Interact with Candlepin only by using the {ProjectWebUI}, CLI, and API.
+
Not supported: Direct interaction with Candlepin, its local API, or database.
This can cause irreparable damage to the {ProjectName} databases.

Embedded Tomcat Application Server::
Interact with the embedded Tomcat application server only by using the {ProjectWebUI}, API, and database.
+
Not supported: Direct interaction with the embedded Tomcat application server local API or database.

Puppet::
When you run the {Project} installation program, you can install and configure Puppet servers as part of {SmartProxyServers}.
A Puppet module, running on a Puppet server on your {ProjectServer} or any {SmartProxyServer}, is also supported by {Team}.

ifdef::satellite[]
.Additional resources
* Red{nbsp}Hat supports many different scripting and other frameworks.
See https://access.redhat.com/articles/369183[How does Red{nbsp}Hat support scripting frameworks] in Red{nbsp}Hat Knowledgebase.
endif::[]
