:_mod-docs-content-type: CONCEPT

[id="http-booting-requirements-with-unmanaged-dhcp"]
= HTTP booting requirements with unmanaged DHCP

[role="_abstract"]
Your environment must meet the following requirements before you can provision machines through HTTP booting without managed DHCP.

.Client requirements
* HTTP UEFI Boot URL must be set to one of:
** `\http://{smartproxy-example-com}:8000`
** `\https://{smartproxy-example-com}:{smartproxy_port}`
* Ensure that your client has access to the DHCP and DNS servers.
* Ensure that your client has access to the HTTP UEFI Boot {SmartProxy}.
* Ensure that all the network-based firewalls are configured to allow clients on the subnet to access the {SmartProxy}.
For more information, see xref:networking-considerations-in-{project-context}[].

.Network requirements
* An unmanaged DHCP server available for clients.
* An unmanaged DNS server available for clients.
In case DNS is not available, use IP address to configure clients.

.{Project} requirements
Although TFTP protocol is not used for HTTP UEFI Booting, {Project} use TFTP {SmartProxy} API to deploy boot loader configuration.

* Ensure that both {ProjectServer} and {SmartProxy} have DNS configured and are able to resolve provisioned host names.
* Ensure that the UDP ports 67 and 68 are accessible by the client so that the client can send and receive a DHCP request and offer.
* Ensure that the TCP port 8000 is open for the client to download boot loader and Kickstart templates from the {SmartProxy}.
* Ensure that the TCP port {smartproxy_port} is open for the client to download the boot loader from the {SmartProxy} through HTTPS.
* Ensure that the host provisioning interface subnet has an HTTP Boot {SmartProxy} set.
* Ensure that the host provisioning interface subnet has a TFTP {SmartProxy} set.
* Ensure that the host provisioning interface subnet has a Templates {SmartProxy} set.
