[id="planning-organization-and-location-context_{context}"]
= Planning organization and location context

Context in {Project} consists of organizations and locations.
You can associate most resources (such as hosts, subnets, or domains) with at least one organization and location context.

Resources and users can generally only access resources within their own context, which makes configuring organizations and locations an integral part of user management in {Project}.

[IMPORTANT]
====
If you use host groups to bundle provisioning and configuration information, avoid mismatching resources from mutually exclusive contexts.
For example, setting a subnet from one organization or location and a compute resource from a different organization or location creates an invalid host group.
====

Some resources in {Project}, such as Ansible roles and operating systems, are not part of any organization or location context.

ifeval::["{context}" == "planning"]
.Additional resources
* For examples of deployment scenarios, see xref:chap-Architecture_Guide-Deployment_Scenarios[].
ifdef::katello[]
* For information about managing organizations and locations, see {ManagingOrganizationsLocationsDocURL}[_{ManagingOrganizationsLocationsDocTitle}_].
endif::[]
ifdef::satellite[]
* For information about managing organizations, see {AdministeringDocURL}Managing_Organizations_admin[Managing organizations] in _{AdministeringDocTitle}_.
* For information about managing locations, see {AdministeringDocURL}Managing_Locations_admin[Managing locations] in _{AdministeringDocTitle}_.
endif::[]
endif::[]
