[id="lifecycle_status_of_rhel_hosts_{context}"]
= Lifecycle Status of RHEL Hosts

{Project} provides multiple mechanisms to display information about upcoming End of Support (EOS) events for your {RHEL} hosts:

* Notification banner
* A column on the Hosts index page
* *Search* field

You can find the {EL} lifecycle status on the *Host status* card on the host details page.
You will see an alert on the Hosts index page for each host that runs {EL} with an upcoming End of Support (EOS) event in a year as well as when support has ended.
For any hosts that are not running {EL}, *Unknown* displays in the *RHEL Lifecycle status* and *Last report* columns.

.EOS Notification Banner
When either the end of maintenance support or the end of extended lifecycle support approaches in a year, you will see a notification banner in the {ProjectWebUI} if you have hosts with that {EL} version.
The notification provides information about the {EL} version, the number of hosts running that version in your environment, the lifecycle support, and the expiration date.
Along with other information, the {EL} lifecycle column is visible in the notification.
