[id="available-upgrade-paths"]
= Available upgrade paths

Upgrading to {ProjectName} {ProjectVersion} from {ProjectName} {ProjectVersionPrevious} includes the following high-level steps:

ifdef::satellite[]
. Upgrading your {ProjectServer}s and {SmartProxyServers} to {Project} {ProjectVersionPrevious}.
endif::[]
ifndef::foreman-deb[]
. Upgrading your {ProjectServer}:
.. Upgrading your {ProjectServer} to {ProjectVersion}.
+
ifdef::satellite[]
.. Synchronizing the new {ProjectVersion} repositories.
endif::[]
. Upgrading your {SmartProxyServers} to {ProjectVersion}.
endif::[]
ifdef::foreman-deb[]
. Upgrading your {ProjectServer} to {ProjectVersion}.
. Upgrading your {SmartProxyServers} to {ProjectVersion}.
endif::[]
ifdef::orcharhino[]
Because {SmartProxies} at version {ProjectVersionPrevious} will keep working with your upgraded {ProjectServer} {ProjectVersion}, you can upgrade your {SmartProxies} separately over multiple maintenance windows.
endif::[]
ifndef::orcharhino[]
You can upgrade your {SmartProxies} separately over multiple maintenance windows because {SmartProxies} at version {ProjectVersionPrevious} and {ProjectVersionPrevious-Previous} will keep working with your upgraded {ProjectServer} {ProjectVersion}.
endif::[]

Upgrading {SmartProxies} separately after upgrading {Project} can be useful in the following situations:

* If you want to have several smaller outage windows instead of one larger window.
* If {SmartProxies} in your organization are managed by several teams and are located in different locations.
ifdef::katello,orcharhino,satellite[]
* If you use a load-balanced configuration, you can upgrade one load-balanced {SmartProxy} and keep other load-balanced {SmartProxies} at one version lower.
This allows you to upgrade all {SmartProxies} one after another without any outage.
endif::[]

ifdef::orcharhino[]
{SmartProxies} at version {ProjectVersionPrevious} retain all of their previous functionality.
endif::[]
ifndef::orcharhino[]
{SmartProxies} at version {ProjectVersionPrevious} and {ProjectVersionPrevious-Previous} retain all of their previous functionality.
endif::[]
New functionality added in the {ProjectVersion} release will not work until you upgrade {SmartProxies} to {ProjectVersion}.
