[id="provisioning-contexts_{context}"]
= Provisioning Contexts

A provisioning context is the combination of an organization and location that you specify for {Project} components.
The organization and location that a component belongs to sets the ownership and access for that component.

Organizations divide {ProjectName} components into logical groups based on ownership, purpose, content, security level, and other divisions.
You can create and manage multiple organizations through {ProjectName} and assign components to each individual organization.
This ensures {ProjectServer} provisions hosts within a certain organization and only uses components that are assigned to that organization.
For more information about organizations, see {ContentManagementDocURL}Managing_Organizations[Managing Organizations] in the _Content Management Guide_.

Locations function similar to organizations.
The difference is that locations are based on physical or geographical setting.
Users can nest locations in a hierarchy.
For more information about locations, see {ContentManagementDocURL}Managing_Locations[Managing Locations] in the _Content Management Guide_.
