:_mod-docs-content-type: CONCEPT

[id="Synchronizing_Content_Between_Servers_{context}"]
= Synchronizing content between {ProjectServer}s

[role="_abstract"]
In a {Project} setup with multiple {ProjectServer}s, you can use {ISS} (ISS) to synchronize content from one upstream server to one or more downstream servers.

There are two possible ISS configurations of {Project}, depending on how you deployed your infrastructure:

ISS Network Sync::
If your upstream server can communicate with the downstream server over a network, you can synchronize content over HTTPS.
+
Configure your {Project} to synchronize content over a network.
ifndef::satellite[]
For more information, see xref:configuring-server-to-synchronize-content-over-a-network_{context}[].
endif::[]

ISS Export Sync::
If your upstream and downstream servers are air gapped, you can synchronize content by using export and import.
+
Configure your {Project} to synchronize content by using export and import.
ifndef::satellite[]
For more information, see xref:configuring-projectserver-to-synchronize-content-by-using-exports_{context}[].
endif::[]

.Additional resources
* {PlanningDocURL}iss-scenarios_planning[{ISS} scenarios in _{PlanningDocTitle}_]
ifdef::satellite[]
* https://access.redhat.com/solutions/7013903[Hammer content export fails with "Path '/the/path' is not an allowed export path" in the _Red{nbsp}Hat Knowledgebase_]
endif::[]
