[id="defining-content-access-strategies-for-hosts_{context}"]
= Defining content access strategies for hosts

When defining your content lifecycle in {Project}, you can use content views and lifecycle environments to make content, such as errata and packages, available only to certain hosts.
This enables you to restrict the content your hosts have access to.

Implement your content access strategies in the following order:

. _Define content views and lifecycle environments_.
Associate content views with your lifecycle environments.
Incorporate content view filters as needed.
+
* For more information see link:{ContentManagementDocURL}Managing_Content_Views_content-management[Managing content views] and link:{ContentManagementDocURL}Managing_Application_Lifecycles_content-management[Managing content views] in _{ContentManagementDocTitle}_.
. _Define content overrides_.
By using content overrides, you can override the default enablement value of either *Enabled* or *Disabled* for any repository.
You can add content overrides to hosts or activation keys.
+
[NOTE]
====
By default, content hosted by {Project} can be either enabled or disabled.
When a repository is enabled, hosts can access the repository packages or other content, allowing hosts to download and install the available content.
When a repository is disabled, the host is not able to access the repository content.

ifdef::orcharhino[]
ifdef::red_hat_enterprise_linux[]
In custom products, repositories are always disabled by default, while Red{nbsp}Hat products can be either enabled or disabled by default depending on the specific repository.
endif::[]
ifndef::red_hat_enterprise_linux[]
In custom products, repositories are always disabled by default.
endif::[]
endif::[]
ifndef::orcharhino[]
In custom products, repositories are always disabled by default, while Red{nbsp}Hat products can be either enabled or disabled by default depending on the specific repository.
endif::[]
====
+
* For more information, see {ManagingHostsDocURL}Enabling_and_Disabling_Repositories_on_Hosts_managing-hosts[Enabling and Disabling Repositories on Hosts] in _{ManagingHostsDocTitle}_ and {ContentManagementDocURL}enabling-and-disabling-repositories-on-activation-key_content-management[Enabling and disabling repositories on activation key] in _{ContentManagementDocTitle}_.
. _Define composite content views_.
You can use composite content views to combine and give hosts access to the content from multiple content views.
+
For more information, see {ContentManagementDocURL}Creating_a_Composite_Content_View_content-management[Creating a composite content view] in _{ContentManagementDocTitle}_.
. _Define architecture and operating system version restrictions._
In custom products, you can set restrictions on the architecture and operating system versions for `{client-content-type}` repositories on which the product will be available.
For example, if you restrict a custom repository to *{client-os} {client-os-major}*, it is only available on hosts running {client-os} {client-os-major}.
+
ifdef::orcharhino[]
ifdef::red_hat_enterprise_linux[]
Red{nbsp}Hat repositories set architecture and operating system version restrictions automatically.
endif::[]
endif::[]
ifndef::orcharhino[]
Red{nbsp}Hat repositories set architecture and operating system version restrictions automatically.
endif::[]
+
[IMPORTANT]
====
Architecture and operating system version restrictions hold the highest priority among all other strategies.
They cannot be overridden or invalidated by content overrides, changes to content views, or changes to lifecycle environments.
For this reason, consider the other strategies before implementing architecture or operating system version restrictions.
====
. _Define release version restrictions._
ifndef::orcharhino[]
Certain Red{nbsp}Hat repositories, such as the {RHEL} minor release repositories, include a *Release version* in their repository metadata.
If present, the release version is compared with the release version specified in the *System purpose* properties of the host.
Based on this comparison, {Project} limits or restricts access to content.
+
For more information about setting system purpose attributes, see {ManagingHostsDocURL}Creating_a_Host_managing-hosts[Creating a host in {ProjectName}] in _{ManagingHostsDocTitle}_.
endif::[]
ifdef::orcharhino[]
ifdef::red_hat_enterprise_linux[]
Certain Red{nbsp}Hat repositories, such as the {RHEL} dot release repositories, include a *Release version* in their repository metadata.
If present, the release version is compared with the release version specified in the *System purpose* properties of the host.
Based on this comparison, {Project} limits or restricts access to content.
+
For more information about setting system purpose attributes, see {ManagingHostsDocURL}Creating_a_Host_managing-hosts[Creating a host in {ProjectName}] in _{ManagingHostsDocTitle}_.
endif::[]
endif::[]

After you define your content access policies as described above, a package or repository is available to a host only if all of the following conditions are met:

* The repository is included in the content view and lifecycle environment of the host.
* The content view of the host has been published after the repository was added to it.
* The repository has not been filtered out by a content view filter.
* The repository is enabled by default or overridden to *Enabled* by using a content override.
* The repository has no architecture or operating system version restrictions or it has architecture or operating system version restrictions that match the host.
ifndef::orcharhino[]
* For certain Red{nbsp}Hat repositories, either no release version is set or the release version matches the release version of the host.
endif::[]
ifdef::orcharhino[]
ifdef::red_hat_enterprise_linux[]
* For certain Red{nbsp}Hat repositories, either no release version is set or the release version matches the release version of the host.
endif::[]
endif::[]

Using activation keys can simplify the workflow for some of these strategies.
You can use activation keys to perform the following actions:

* Assign hosts to content views and lifecycle environments
* Add content overrides to hosts
* Set system purpose attributes on hosts, including release version

Activation keys only affect hosts during registration.
If a host is already registered, you can change the above attributes individually for each host or by using content host bulk actions.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in _{ContentManagementDocTitle}_.

.Additional resources
* For examples of content view deployments, see xref:chap-Architecture_Guide-Deployment_Scenarios[].
