[id="planning-{project-context}-upgrade"]
= Planning {Project} upgrade

Upgrading to {Project} {ProjectVersion} affects your entire {Project} infrastructure.
Plan carefully before proceeding.

* Read the {ProjectName} {ProjectVersion} {ReleaseNotesDocURL}[{ReleaseNotesDocTitle}].
* Consider whether any of your integrations need updating.
Some {Project} API endpoints, Hammer CLI commands, and modules from the {Project} Ansible Collection can differ between versions of {Project}.
ifdef::satellite[]
For information about changes in these tools, see the {ProjectName} {ProjectVersion} {ReleaseNotesDocURL}[{ReleaseNotesDocTitle}].
endif::[]
* Consider whether you have edited any of the default templates in {Project}.
To confirm if a template has been edited, view its *History* in the {ProjectWebUI} before upgrading or view the changes in the audit log after upgrading.
In the {ProjectWebUI}, navigate to *Monitor* > *Audits* and search for the template to see a record of changes made.
+
If you have edited the default templates, back up your changes by cloning the templates or exporting them.
+
** If you back up the templates by cloning, the upgrade process will not overwrite them.
** If you back up the templates by exporting, you will be able to compare the exported and default templates and then manually apply your changes after the upgrade finishes.
ifdef::satellite[]
* Optional: You can test the upgrade on a clone of your {ProjectServer}.
After you successfully test the upgrade on the clone, you can repeat the upgrade on your primary {ProjectServer} and discard the clone, or you can promote the clone to your primary {ProjectServer} and discard the previous primary {ProjectServer}.
For more information, see {AdministeringDocURL}cloning_satellite_server[Cloning {ProjectServer}] in _{AdministeringDocTitle}_.
endif::[]

{Project} services are shut down during the upgrade.
Ensure to plan for the required downtime.
The upgrade process duration varies depending on your hardware configuration, network speed, and the amount of data that is stored on the server:

* On average installations, upgrading {ProjectServer} takes up to 30 minutes and upgrading a single {SmartProxyServer} takes up to 10 minutes.
* On very large installations, upgrading {ProjectServer} can take up to 1{range}2 hours and upgrading a single {SmartProxyServer} can take up to 15{range}30 minutes.
