[id="Report_Template_Safe_Mode_{context}"]
= Report Template Safe Mode

When you create report templates in {Project}, safe mode is enabled by default.
Safe mode limits the macros and variables that you can use in the report template.
Safe mode prevents rendering problems and enforces best practices in report templates.
The list of supported macros and variables is available in the {ProjectWebUI}.

To view the macros and variables that are available, in the {ProjectWebUI}, navigate to *Monitor*{nbsp}>{nbsp}*Report Templates* and click *Create Template*.
In the Create Template window, click the *Help* tab and expand *Safe mode methods*.

While safe mode is enabled, if you try to use a macro or variable that is not listed in *Safe mode methods*, the template editor displays an error message.

To view the status of safe mode in {Project}, in the {ProjectWebUI}, navigate to *Administer*{nbsp}>{nbsp}*Settings* and click the *Provisioning* tab.
Locate the *Safemode rendering* row to check the value.
