:_mod-docs-content-type: CONCEPT

[id="overview-of-the-{foreman-installer}-utility"]
= Considerations for using the {foreman-installer} utility

[role="_abstract"]
The {foreman-installer} utility is a collection of Puppet modules.
Before using it to install {ProjectServer}, consider that installations can take tens of minutes and that repeated runs might overwrite manual configuration changes.

* The installation process can take tens of minutes to complete.
If you are connecting remotely to the system, use a utility such as `tmux` that allows suspending and reattaching a communication session so that you can check the installation progress in case you become disconnected from the remote system.
If you lose connection to the shell where the installation command is running, see the log at `{installer-log-file}` to determine if the process completed successfully.
* The {Project} installation script is based on Puppet, which means that if you run the installation script more than once, it might overwrite any manual configuration changes.
+
To avoid this and determine which future changes apply, use the `--noop` argument when you run the installation script.
This argument ensures that no actual changes are made.
Potential changes are written to `{installer-log-file}`.
+
Files are always backed up and so you can revert any unwanted changes.
For example, in the logs of `foreman-installer`, you can see an entry similar to the following about Filebucket:
+
[options="wrap"]
----
/Stage[main]/Dhcp/File[/etc/dhcp/dhcpd.conf]: Filebucketed /etc/dhcp/dhcpd.conf to puppet with sum 622d9820b8e764ab124367c68f5fa3a1
----
+
You can restore the previous file as follows:
+
[options="wrap"]
----
# puppet filebucket -l \
restore /etc/dhcp/dhcpd.conf 622d9820b8e764ab124367c68f5fa3a1
----
* Use the `{installer-scenario} --help` command to display the most commonly used options and any default values.
* Use the `{installer-scenario} --full-help` command to display advanced options.
ifdef::foreman-el,foreman-deb[]
* By default, {ProjectServer} is installed with the Puppet agent running as a service.
If required, you can disable Puppet agent on {ProjectServer} using the `--puppet-runmode=none` option.
endif::[]
