:_mod-docs-content-type: CONCEPT

[id="Provisioning-Methods-in-{ProjectNameID}_{context}"]
= Provisioning methods in {ProjectName}

With {ProjectName}, you can provision hosts by using the following provisioning methods.

Network based::
You can use this method with hosts that are capable of PXE booting or UEFI HTTP booting.
+
You must configure the necessary network booting services, such as DHCP or TFTP.
When you create a host, you select a PXE loader that can configure DHCP options for network booting if {SmartProxy} is set up to configure the DHCP service automatically.
+
ifdef::satellite[]
This method uses the Anaconda operating system installer and template-generated Kickstart script for installation automation downloaded from {Project}.
endif::[]
ifndef::satellite[]
This method uses an operating system installer, such as Anaconda, Debian Installer, or YaST, and template-generated file with installation options automation from {Project}, such as Kickstart, Preseed, or AutoYaST.
endif::[]

PXEX-based Discovery:::
You can create host entries manually or by discovering hosts on a network.
You can automate provisioning of discovered hosts by creating Discovery rules.

PXE-less Discovery with kexec:::
You can use this method with PXE-less hosts.
+
You must configure DHCP for host discovery.
+
This method uses the Discovery image to boot the host and report its hardware details to {Project}.
Using kernel execution (kexec), the Discovery image runs the installer downloaded from {Project}.

Boot disk based::
You can use this method with PXE-less hosts or when you do not have the option of configuring network booting services, such as DHCP.
+
This method supplies the booting capability but the rest of the provisioning process still downloads the installer and template-generated files from {Project} to automate the installation.

Image based::
You can use this method with virtual machines or cloud instances.
+
This method uses a virtual image template or a cloud image from a compute resource to provision the operating system.
{Project} can customize the image by running either a pre-boot or post-boot configuration script generated from a provisioning template.

ifndef::satellite[]
.Choosing a provisioning method
image::common/provisioning-method-selection.svg["Choosing a provisioning method", title="Choosing a provisioning method"]
endif::[]
