[id="backup-and-restore-{smart-proxy-context}-using-a-virtual-machine-snapshot_{context}"]
= Backup and Restore {SmartProxyServer} Using a Virtual Machine Snapshot

If your {SmartProxyServer} is a virtual machine, you can restore it from a snapshot.
Creating weekly snapshots to restore from is recommended.
In the event of failure, you can install, or configure a new {SmartProxyServer}, and then synchronize the database content from {ProjectServer}.

If required, deploy a new {SmartProxyServer}, ensuring the host name is the same as before, and then install the {SmartProxy} certificates.
You may still have them on {ProjectServer}, the package name ends in -certs.tar, alternately create new ones.
Follow the procedures in {InstallingSmartProxyDocURL}[Installing {SmartProxyServer}] until you can confirm, in the {ProjectWebUI}, that {SmartProxyServer} is connected to {ProjectServer}.
Then use the procedure xref:synchronizing-an-external-{smart-proxy-context}_{context}[] to synchronize from {Project}.
