:_mod-docs-content-type: CONCEPT

[id="prerequisites-for-network-boot-provisioning"]
= Prerequisites for network-boot provisioning

The requirements for network-boot provisioning include:

* Provisioning infrastructure services (DNS, DHCP, TFTP) are integrated with {Project} and configured.
ifndef::satellite[]
* Provisioning templates are associated with a client operating system.
+
For BIOS provisioning, you must associate a PXELinux template with the operating system.
For UEFI provisioning, you must associate a PXEGrub2 template with the operating system.
If you associate both PXELinux and PXEGrub2 templates, {Project} deploys configuration files for both on a TFTP server, so that you can switch between PXE loaders easily.
endif::[]
* A bare-metal host or a blank virtual machine.
include::snip_prerequisites-common-compute-resource.adoc[]

[role="_additional-resources"]
.Additional resources
* {IntegratingProvisioningInfrastructureServicesDocURL}[{IntegratingProvisioningInfrastructureServicesDocTitle}]
* xref:preparing-networking[]
* xref:associating-templates-with-operating-systems[]
* xref:discovering-hosts-on-a-network[]
* xref:configuring-the-security-token-validity-duration[]
