:_mod-docs-content-type: CONCEPT

[id="managing-ssh-keys"]
= Managing SSH keys

[role="_abstract"]
Add SSH keys to user accounts so {Project} can deploy those keys during host provisioning.

.Additional resources
* {ProvisioningDocURL}deploying-ssh-keys-during-provisioning[Deploying SSH keys during provisioning in _{ProvisioningDocTitle}_]
ifdef::containerized[]
ifdef::katello[]
[NOTE]
====
For containerized {Katello} users, select the reference related to your current operating system.
====
endif::[]
endif::[]
ifdef::foreman-el,katello[]
* {RHELDocsBaseURL}9/html-single/configuring_basic_system_settings/index#assembly_using-secure-communications-between-two-systems-with-openssh_configuring-basic-system-settings[Using secure communications between two systems with OpenSSH in _{RHEL}{nbsp}9 Configuring basic system settings_]
endif::[]
ifdef::containerized[]
ifndef::orcharhino[]
* {RHELDocsBaseURL}10/html/securing_networks/using-secure-communications-between-two-systems-with-openssh[Using secure communications between two systems with OpenSSH in _Securing Networks_]
endif::[]
endif::[]
