[id="applying-custom-configuration_{context}"]
= Applying custom configuration to {ProjectName}

[IMPORTANT]
====
Applying custom configuration to {Project} can have unintended consequences that affect performance or functionality.
Before applying the custom configuration to your production environment, test your changes in a staging environment or run `{foreman-installer}` with the `--noop` and `--verbose` options.
If the custom configuration causes problems, remove the offending lines from `/etc/foreman-installer/custom-hiera.yaml` and rerun the `{foreman-installer}`.
====

The `{installer-scenario} --full-help` command displays all `{foreman-installer}` flags available for custom configuration.
Additionally, some Puppet classes are not exposed to `{foreman-installer}`.
You can manage these Puppet classes manually by specifying configuration values in the `/etc/foreman-installer/custom-hiera.yaml` file. 
Values specified in this file persist when you rerun `{foreman-installer}`.

The `/etc/foreman-installer/custom-hiera.yaml` file accepts entries in the following format:

[source, yaml, options="nowrap", subs="+quotes,attributes"]
----
_Puppet_Module_::__Parameter_Name__: _Parameter_Value_
----

For a list of available Puppet modules, see the contents of the `/usr/share/foreman-installer/modules/` directory.
For a list of classes, parameters, and values available for a module, see the `.pp` files in the directory for that module, such as `_Module_Name_/manifests/_Example_PP_File_.pp`.

.Example `/etc/foreman-installer/custom-hiera.yaml` entries
[options="header"]
|====
|Entry|Explanation
a|[source, yaml, options="nowrap", subs="+quotes,attributes"]
----
apache::server_tokens: Prod
----
|Sets the `ServerTokens` directive to return only the product name.
a|[source, yaml, options="nowrap", subs="+quotes,attributes"]
----
apache::server_signature: Off
----
|Disables the Apache server signature.
|====

.Additional resources
* The `/etc/foreman-installer/custom-hiera.yaml` file on your {ProjectServer}
