:_mod-docs-content-type: CONCEPT

[id="provision-hosts-through-opentofu"]
= Provision hosts through OpenTofu

[role="_abstract"]
{Project} can interact with multiple clouds and virtualization solutions through OpenTofu.
You can create hosts and control their power management states through {Project}.

{Project} uses OpenTofu to act as a unified interface to provision and manage hosts on several clouds and virtualization platforms.
After an initial setup, you can create hosts on different compute resource providers with the same workflow.

Enable OpenTofu-based host provisioning::
. Install the OpenTofu plugin on your {ProjectServer}.
. Connect {Project} to a supported compute resource target.
. Define an image from your compute resource target in {Project}.
. Create a compute profile to bundle hardware settings.

Customize OpenTofu-based host provisioning::
. Depending on your use case, create additional compute profiles.
. Create a host group as blue print to standardize host deployments.

Provision hosts::
. Select a host group.
. Customize settings to your needs.
. Provision a host.
