:_mod-docs-content-type: CONCEPT

[id="enable-host-configuration-management-integrations"]
= Enable host configuration management integrations

[role="_abstract"]
Before you can start using a configuration management framework to define the desired state of your hosts, you must enable the integration of your preferred framework with {Project}.

To keep operational consistency across large deployments and prevent configuration drift, organizations rely on configuration management frameworks.
{Project} supports integration with the following configuration management tools:

* Ansible
* Puppet

{Project} acts as the central orchestration hub for these tools, allowing you to organize, assign, and run configurations across large numbers of physical, virtual, and cloud-based hosts.

Before you can import roles, playbooks, or modules and enforce policies on managed systems, you must enable the integration on your {ProjectServer}.

.Additional resources
* xref:configuration-management-with-puppet-in-{project-context}[]
