[id="configuring-provisioning_{context}"]
= Configuring provisioning

After your basic {Project} infrastructure is in place, you can start configuring provisioning to ensure that {Project} can seamlessly create, configure, and manage hosts.

The process depends on whether you want to provision bare-metal hosts, virtual machines, or cloud instances, but it includes defining installation media, configuring provisioning templates, and other tasks.
If you are provisioning virtual machines or cloud instances, you must also integrate your compute provider with {Project} by connecting the provider as a compute resource to {Project}.

The following {Project} features support automating the provisioning of your hosts:

* Provisioning templates enable you to define the way {Project} installs an operating system on your hosts.
* The Discovery service enables you to detect unknown hosts and virtual machines on the provisioning network.
* Host groups enable you to standardize provisioning of host configurations.

.Additional resources
* For a complete guide to provisioning, see {ProvisioningDocURL}[_{ProvisioningDocTitle}_].
