:_mod-docs-content-type: CONCEPT

[id="overview-of-image-mode-for-hosts"]
= Overview of image mode for hosts

[role="_abstract"]
{Project} identifies an image mode host as any system that reports a container image from its bootc status through Subscription Manager. 
It classifies all other hosts as package mode hosts.

In image mode, users can install and manage packages, but with limitations. 
Job templates run the `bootc usr-overlay` command or use the `dnf --transient` flag to ensure that packages are installed correctly.
Any packages installed on image mode hosts are temporary and disappear after a reboot. 
Because of this, installing packages is generally discouraged, except for debugging purposes or, in some cases, when applying critical security patches.
If you need new packages on an image mode host, consider building a new container image the includes the necessary packages.
After upgrading the image mode host to this image, the new packages will be installed permanently.

On the *All Hosts* page, you can display the *Type* column, which includes a mode indicator. 
This column is disabled by default.

Image mode hosts include additional fields that reflect their boot status.
These fields track the container images used in various scenarios:

* *Booted Image & Digest*: Indicates the container image the host is currently using.
* *Staged Image & Digest*: Indicates the container image the host uses after the next reboot.
* *Available Image & Digest*: Represents the container image cached by running `bootc upgrade --check`.
* *Rollback Image & Digest*: Represents the container image the host reverts to after the next reboot if `Bootc rollback` is applied.

ifndef::orcharhino[]
.Additional resources
* https://www.redhat.com/en/blog/image-mode-red-hat-enterprise-linux-quick-start-guide[RHEL Image Mode quick start guide]
endif::[]
