[id="{context}_introduction"]
= Introduction

_Application Centric Deployment_ (ACD) describes a fundamentally different approach to provisioning and configuring hosts in {Project}.
Traditionally, {ProjectName} has pursued a host-centric approach.
Now, the ACD approach presents a new idea: deploying hosts to run an application that requires a predefined set of services.

Generally, an application consists of multiple services and therefore requires different kinds of hosts connected to each other.
These hosts have dependencies on each other, for example, an application server might require a database server.

The number of deployed hosts depends on the expected usage of the application.
You can scale an application instance vertically via compute profile or horizontally by choosing multiple hosts to run the same service to handle increased workloads.

Within ACD, Ansible playbooks are executed on {ProjectServer}.
Ensure that {ProjectServer} can connect to all managed hosts using Ansible.

.Host Centric vs. Application Centric Deployment
[caption=]
[cols="20%,40%,40%"]
|===
|
|Host Centric Deployment
|Application Centric Deployment

|Requirements
|none (possible by default)
|ACD plugin

|Focus
|individual hosts
|applications

|Number of Hosts
|one
|one to many

|Automation
|via Host Group
|via Ansible playbook and application definition

|Advantages
|full control over each host
|deploy a number of hosts at once; self service for technically less inclined; scale vertically and/or horizontally

|Disadvantages
|extra abstraction layer between a host and its purpose
|dependency on/limitation to existing application templates
|===

[id="{context}_usage_example"]
== Usage Example

The following application centric deployment example illustrates the deployment of hosts in an application centric approach.
The web application requires an HAProxy, an Apache web server, a Tomcat application server, and a database server.

Using ACD, this web application can be deployed and configured in a single step:

. Import the Ansible playbook
+
Upload the Ansible playbook to your {ProjectServer}.
Specify the path and the name of the Ansible playbook via management UI.
. Create an application definition
+
This example requires four different services: proxy servers, web servers, application servers, and database servers.
Those hosts are ideally part of a host group.
. Optional: Customize Ansible variables
+
You can either use the default values, change values, or lock the Ansible variables from being edited for an application instance.
Ansible variables are read from the group variables of the Ansible playbook.
. Optional: Overwrite variables from the host group
+
For example, change the compute profile or set a different lifecycle environment.
. Deploy an application instance
+
You may simply deploy the application instance; run the Ansible playbook as is; or customize the Ansible playbook before running it.

[NOTE]
====
If you want to install a package using an Ansible playbook and the host is subscribed to {ProjectServer}, ensure that the package exists in the Content View.
====

[id="{context}_key_terms"]
== Key Terms in Application Centric Deployment

.ACD
ACD stands for _Application_ _Centric_ _Deployment_ and describes a new approach to provision and configure hosts based on the service they provide.

.Ansible Playbooks
xref:{context}_ansible_playbooks[Ansible playbooks] are the core of the application definition.
They connect the different services and provide a whole application with one click of a button.
These playbooks contain roles, which in turn contain tasks to properly configure hosts.

.Application Definitions
xref:{context}_application_definitions[Application definitions] are blueprints of how to deploy an application and its services.

.Application Instances
xref:{context}_application_instances[Application instances] are configured application definitions.
You can define how many hosts to deploy per service and choose unique host names.

There might be different configurations based on a testing or production environment or its expected usage.
For example, deploying a wiki platform for 20 users might use the `1-small` compute profile, whereas hundreds of expected users might require the `3-large` compute profile.

.Service
A service is a type of host necessary to run an application.
For example, the _LAMP_ stack consists of three services: an https://httpd.apache.org/[Apache] webserver, a https://www.mysql.com/[MySQL] database, and https://www.php.net/[PHP] scripting language all running on Linux servers.

.Host Groups
Host groups are predefined sets of provisioning and configuration settings for a new host.
ifdef::foreman-el,foreman-deb,katello,satellite[]
For more information, see {ManagingHostsDocURL}creating-a-host-group[Creating a Host Group].
endif::[]

[id="{context}_prerequisites"]
== Prerequisites for Application Centric Deployment

In order to use the ACD plugin, your {ProjectName} instance must be able to deploy a host and offer properly configured host groups.
ifdef::foreman-el,foreman-deb,katello[]
For more information, see https://docs.theforeman.org/[Foreman and Katello documentation].
endif::[]
