[id="overview-of-{project-context}-integration-with-insights"]
= Overview of {Project} integration with Insights

ifdef::installing-satellite-server-connected[]
In a connected {Project} environment, you can use the hosted Insights services or you can install {insights-advisor} locally.
endif::[]
ifdef::installing-satellite-server-disconnected[]
In a disconnected {Project} environment, you can install {insights-advisor} locally.
endif::[]

ifdef::installing-satellite-server-connected[]
Hosted Insights services::
Registering your {ProjectServer} with Insights gives you access to all Insights services, including the Advisor, Vulnerability, and Subscriptions services.
+
Note that you do not require a Red{nbsp}Hat Insights entitlement in your subscription manifest.
endif::[]

{insights-advisor}::
Installing {insights-advisor} on your {ProjectServer} gives you access to the Advisor service locally.
{insights-advisor} analyzes system health and configuration by applying predefined rules to a small set of local data, such as installed packages, running services, and configuration settings.
When you install {insights-advisor} locally, you can generate Insights recommendations without sending system data to Red{nbsp}Hat services.
+
Note that with {insights-advisor} enabled, you cannot use the hosted Subscriptions service.
Enabling {insights-advisor} prevents you from using any Red{nbsp}Hat Hybrid Cloud Console services.

:FeatureName: {insights-advisor}
include::snip_technology-preview.adoc[]

.Additional resources
* For more information about {Project} and Red{nbsp}Hat Insights, see https://access.redhat.com/products/red-hat-insights/#satellite[Red Hat Insights on {Project} {RHEL} (RHEL)].
