[id="Performance_Tuning_Quickstart_{context}"]
= Performance Tuning Quickstart

You can tune your {ProjectServer} based on expected managed host counts and hardware allocation using built in tuning profiles included in {Project} that are available using the installation routine's tuning flag.
For more information, see {InstallingProjectDocURL}tuning-with-predefined-profiles_{project-context}[Tuning {ProjectServer} with Predefined Profiles] in _{InstallingServerDocTitle}_.

There are four sizes provided based on estimates of the number of managed hosts your {Project} manages.
You can find the specific tuning settings for each profile in the configuration files contained in `/usr/share/foreman-installer/config/foreman.hiera/tuning/sizes`.

[width="100%",cols="25%,25%,25%,25%",options="header"]
|===
|Name |Number of managed hosts |Recommend RAM |Recommend Cores
|default |0-5000 |20 GiB |4
|medium |5000-10000 |32 GiB |8
|large |10000-20000 |64 GiB |16
|extra-large |20000-60000 |128 GiB |32
|extra-extra-large |60000+ |256 GiB+ |48+
|===

.Procedure
. Select an installation size: `default`, `medium`, `large`, `extra-large`, or `extra-extra-large`.
The default value is `default`.
. Run `{foreman-installer}`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --tuning "_My_Installation_Size_"
----
. Optional: Tune the Ruby app server directly using the Puma Tuning section.
For more information, see xref:Puma_Tunings_{context}[].
