:_mod-docs-content-type: CONCEPT

[id="provisioning-contexts-for-{project-context}-resources"]
= Provisioning contexts for {Project} resources

[role="_abstract"]
A provisioning context is the combination of an organization and location that you specify for {Project} resources.
The organization and location that a resource belongs to sets the ownership and access for that resource.

*Organizations* divide {ProjectName} resources into logical groups based on ownership, purpose, content, security level, and other divisions.
You can create and manage multiple organizations through {ProjectName} and assign resources to each individual organization.
This ensures {ProjectServer} provisions hosts within a certain organization and only uses resources that are assigned to that organization.
ifdef::satellite[]
For more information about organizations, see {AdministeringDocURL}managing-organizations-in-{project-context}_admin[Managing organizations in {Project}] in _{AdministeringDocTitle}_.
endif::[]
ifndef::satellite[]
For more information about organizations, see {ManagingOrganizationsLocationsDocURL}managing-organizations-in-{project-context}_managing-organizations-locations[Managing organizations in {Project}] in _{ManagingOrganizationsLocationsDocTitle}_.
endif::[]

*Locations* function similar to organizations.
The difference is that locations are based on physical or geographical setting.
Users can nest locations in a hierarchy.
ifdef::satellite[]
For more information about locations, see {AdministeringDocURL}Managing_Locations_admin[Managing Locations] in _{AdministeringDocTitle}_.
endif::[]
ifndef::satellite[]
For more information about locations, see {ManagingOrganizationsLocationsDocURL}Managing_Locations_managing-organizations-locations[Managing Locations] in _{ManagingOrganizationsLocationsDocTitle}_.
endif::[]
