[id="Template_Writing_Reference_{context}"]
= Template Writing Reference

Embedded Ruby (ERB) is a tool for generating text files based on templates that combine plain text with Ruby code.
{ProjectName} uses ERB syntax in the following cases:

Provisioning templates::
For more information, see {ProvisioningDocURL}creating-provisioning-templates_provisioning[Creating Provisioning Templates] in the _Provisioning Guide_.

Remote execution job templates::
For more information, see xref:Configuring_and_Setting_Up_Remote_Jobs_{context}[].

Report templates::
For more information, see xref:Using_Report_Templates_to_Monitor_Hosts_{context}[].

Templates for partition tables::
For more information, see {ProvisioningDocURL}creating-partition-tables_provisioning[Creating Partition Tables] in the _Provisioning Guide_.

ifndef::orcharhino[]
Smart Variables::
For more information, see {MultiBaseURL}puppet_guide/chap-red_hat_satellite-puppet_guide-adding_puppet_modules_to_red_hat_satellite_6#sect-{Project_Link}-Puppet_Guide-Adding_Puppet_Modules_to_{Project_Link}_6-Configuring_Smart_Variables[Configuring Smart Variables] in the _Puppet Guide_.
endif::[]

ifndef::orcharhino[]
Smart Class Parameters::
For more information, see {MultiBaseURL}puppet_guide/chap-red_hat_satellite-puppet_guide-adding_puppet_modules_to_red_hat_satellite_6#sect-{Project_Link}-Puppet_Guide-Adding_Puppet_Modules_to_{Project_Link}_6-Configuring_Smart_Class_Parameters[Configuring Smart Class Parameters] in the _Puppet Guide_.
endif::[]

This section provides an overview of {Project}-specific macros and variables that can be used in ERB templates along with some usage examples.
Note that the default templates provided by {ProjectName} (*Hosts* > *Provisioning templates*, *Hosts* > *Job templates*, *Monitor* > *Report Templates* ) also provide a good source of ERB syntax examples.

When provisioning a host or running a remote job, the code in the ERB is executed and the variables are replaced with the host specific values.
This process is referred to as *rendering*.
{ProjectServer} has the safemode rendering option enabled by default, which prevents any harmful code being executed from templates.
