[id="salt_guide_salt_architecture_{context}"]
= Salt Architecture

You need a Salt Master which either runs on your {ProjectServer} or {SmartProxyServer} with the Salt plugin enabled.
You can also use an existing Salt Master by installing and configuring the relevant {SmartProxy} features on the existing Salt Master host.

For more information on installing a Salt Master, consult the https://docs.saltproject.io/en/latest/[official Salt documentation].
Alternatively, use the bootstrap instructions found in the https://repo.saltproject.io/[official Salt package repository].

[TIP]
====
{Team} recommends using the same Salt version on the Salt Master as you are using on your Salt Minions.
====

In Salt terminology, managed hosts are referred to as _Salt Minions_.

{Team} recomends using the same Salt version on your Salt Minions as you are using on your Salt Master.
Therefore, we also recommend using {Project}'s content management to provide managed hosts with the correct version of the Salt client software.
