[id="Overview_of_Hosts_{context}"]
= Overview of Hosts in {Project}

A host is any Linux client that {ProjectName} manages.
Hosts can be physical or virtual.
ifdef::foreman-el,foreman-deb,katello[]
Virtual hosts can be deployed on any platform supported by {ProjectName}, such as Amazon EC2, Google Compute Engine, KVM, libvirt, Microsoft Azure, OpenStack, {oVirt}, Proxmox, Rackspace Cloud Services, or VMware vSphere.
endif::[]
ifdef::satellite[]
Virtual hosts can be deployed on any platform supported by {ProjectName}, such as Amazon EC2, Google Compute Engine, KVM, libvirt, Microsoft Azure, OpenStack, {oVirt}, Rackspace Cloud Services, or VMware vSphere.
endif::[]
ifdef::orcharhino[]
Virtual hosts can be deployed on any platform supported by {ProjectName}, such as Amazon EC2, Google Compute Engine, libvirt, Microsoft Azure, Oracle Linux Virtualization Manager, oVirt, Proxmox, RHV, and VMware vSphere.
endif::[]

{ProjectName} enables host management at scale, including monitoring, provisioning, remote execution, configuration management, software management, and subscription management.
You can manage your hosts from the {ProjectWebUI} or from the command line.

In the {ProjectWebUI}, you can browse all hosts recognized by {ProjectServer}, grouped by type:

* *All Hosts* {endash} a list of all hosts recognized by {ProjectServer}.
* *Discovered Hosts* {endash} a list of bare-metal hosts detected on the provisioning network by the Discovery plug-in.
* *Content Hosts* {endash} a list of hosts that manage tasks related to content and subscriptions.
* *Host Collections* {endash} a list of user-defined collections of hosts used for bulk actions such as errata installation.

To search for a host, type in the *Search* field, and use an asterisk ({asterisk}) to perform a partial string search.
For example, if searching for a content host named `dev-node.example.com`, click the *Content Hosts* page and type `dev-node*` in the *Search* field.
Alternatively, `{asterisk}node{asterisk}` will also find the content host `dev-node.example.com.`

WARNING: {ProjectServer} is listed as a host itself even if it is not self-registered.
Do not delete {ProjectServer} from the list of hosts.
