[id="migrating-project-to-el8_{context}"]
ifdef::satellite[]
= Migrating {ProjectName} to {RHEL} 8
endif::[]
ifndef::satellite[]
= Migrating {ProjectName} to Enterprise Linux 8
endif::[]

When you migrate your {Project}, you create a backup of your {ProjectServer} and your {SmartProxy}, install a fresh instance on a new server, and restore your backup on the new server.
After your migration is complete, you can then decommission the earlier instance of {ProjectServer} and {SmartProxy}.

.Terminology
Ensure that you understand the following terms:

*Source server*:: The origin of migration on which you create a backup.

*Target server*:: The new server on which you restore the backup.

.High-Level Procedure
To migrate your {Project} to new hardware, follow these high-level steps:

. Create a backup of the {ProjectServer} or {SmartProxyServer} on the source server.
. Perform a fresh installation of the {ProjectServer} or {SmartProxyServer} on a target server.
ifdef::satellite[]
* Install a minimal {RHEL} 8 instance with the capacity to store backup files.
endif::[]
ifndef::satellite[]
* Install a minimal Enterprise Linux 8 (CentOS Stream, {RHEL} or a {RHEL} rebuild) instance with the capacity to store backup files.
endif::[]
* Do not install any operating system software groups or third-party applications.
ifdef::satellite[]
+
For more information, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_installation/index[Performing a standard {RHEL} installation].
endif::[]
. Restore the backup on the target server.
