[id="{ProjectServerID}-Overview_{context}"]
= {ProjectServer} overview

{ProjectServer} is the central component of a {Project} deployment where you plan and manage the content lifecycle.

A typical {Project} deployment includes one {ProjectServer} on which you perform the following operations:

* Content lifecycle management
* Configuration of {SmartProxyServers}
* Configuration of hosts
* Host provisioning
* Patch management
* Subscription management

{ProjectServer} delegates content distribution, host provisioning, and communication to {SmartProxyServers}.
{ProjectServer} itself also includes a {SmartProxy}.

{ProjectServer} also contains a fine-grained authentication system.
You can grant {Project} users permissions to access precisely the parts of the infrastructure for which they are responsible.

{ProjectServer} consists of the following components:

* Foreman
* Foreman plugins, such as bootdisk and Katello
* Foreman services
** Apache
** Candlepin
** PostgreSQL
** Pulp
** Puppet Server
** Redis
+
* {SmartProxy}

.Additional resources
* For more information about managing permissions, see {AdministeringDocURL}Managing_Users_and_Roles_admin[Managing users and roles] in _{AdministeringDocTitle}_.
ifdef::foreman-deb,foreman-el,katello[]
* https://theforeman.github.io/foreman-plugin-overview/[Foreman plugin overview]
endif::[]
