[id="dns-service-providers"]
= DNS service providers

{Project} can manage DNS records by using your {SmartProxy}.
DNS management contains updating and removing DNS records from existing DNS zones.
A {SmartProxy} has multiple DNS providers that you can use to integrate {Project} with your existing DNS infrastructure or deploy a new one.

After you have enabled DNS, your {SmartProxy} can manipulate any DNS server that complies with RFC 2136 by using the `dns_nsupdate` provider.
Other providers provide more direct integration, such as `dns_infoblox` for https://www.infoblox.com/[Infoblox].

.Available DNS providers
ifdef::orcharhino[]
* `dns_dnscmd` {endash} Static DNS records in Microsoft Active Directory.
endif::[]

* `dns_nsupdate_gss` {endash} Dynamic DNS update with GSS-TSIG.
For more information, see xref:integrating-idm-dns-update-with-gss-tsig-authentication_{context}[].

* `dns_nsupdate` {endash} Dynamic DNS update using nsupdate.
For more information, see xref:integrating-a-generic-dns-server-by-using-dns-nsupdate_{context}[].

ifndef::satellite[]
* `dns_libvirt` {endash} Dnsmasq DNS via libvirt API.
For more information, see xref:integrating-dnsmasq-dns-by-using-the-libvirt-api_{context}[].

* `dns_powerdns` {endash} https://www.powerdns.com/[PowerDNS].
For more information, see xref:integrating-powerdns_{context}[].
endif::[]

ifdef::foreman-el,foreman-deb,katello[]
For more information, see https://projects.theforeman.org/projects/foreman/wiki/List_of_Smart-Proxy_Plugins#DNS-plugins[List of DNS plugins]
endif::[]

