[id="how-to-synchronize-content-using-export-and-import_{context}"]
= How to Synchronize Content Using Export and Import

There are multiple approaches for synchronizing content using the export and import workflow:

* You employ the upstream {ProjectServer} as a content store, which means that you sync the whole Library rather than Content View versions.
This approach offers the simplest export/import workflow.
In such case, you can manage the versions downstream.
For more information, see xref:Using_Upstream_Server_as_a_Content_Store_{context}[].
* You use the upstream {ProjectServer} to sync Content View versions.
This approach offers more control over what content is synced between {ProjectServer}s.
For more information, see xref:Using_Upstream_Server_to_Sync_Content_View_Versions_{context}[].
* You sync a single repository.
This can be useful if you use the Content-View syncing approach, but you want to sync an additional repository without adding it to an existing Content View.
For more information, see xref:synchronizing-a-single-repository_{context}[].
+
[NOTE]
====
Synchronizing content using export and import requires the same major, minor, and patch version of {Project} on both the downstream and upstream {ProjectServer}s.

When you are unable to match upstream and downstream {Project} versions, you can use:

* Syncable exports and imports.
* {ISS} (ISS) with your upstream {Project} connected to the Internet and your downstream {Project} connected to the upstream {Project}.
====
