[id="dhcp-serivce-proviers"]
= DHCP service providers

{Project} can integrate with a DHCP service by using your {SmartProxy}.
A {SmartProxy} has multiple DHCP providers that you can use to integrate {Project} with your existing DHCP infrastructure or deploy a new one.
You can use the DHCP module of {SmartProxy} to query for available IP addresses, add new, and delete existing reservations.
Note that your {SmartProxy} cannot manage subnet declarations.

.Available DHCP providers

* `dhcp_infoblox` {endash} For more information, see xref:integrating-infoblox-dhcp_{context}[].

* `dhcp_isc` {endash} ISC DHCP server over OMAPI.

* `dhcp_remote_isc` {endash} ISC DHCP server over OMAPI with leases mounted through networking.
For more information, see xref:integrating-a-generic-dhcp-server[].

ifndef::satellite[]
* `dhcp_libvirt` {endash} dnsmasq DHCP via libvirt API.
For more information, see xref:integrating-dnsmas-dhcp-by-using-the-libvirt-api_{context}[].
endif::[]

ifdef::orcharhino[]
* `dhcp_native_ms` {endash} Microsoft Active Directory by using API
endif::[]

