:_mod-docs-content-type: CONCEPT

[id="repository-synchronization"]
= Repository synchronization

[role="_abstract"]
You must synchronize repositories to download content into {Project}.
You can use one-time synchronization for an initial synchronization of repositories or to synchronize repositories manually as you need.

You can also sync all repositories in an organization.
For more information, see xref:Synchronizing_All_Repositories_in_an_Organization_{context}[].

Create a sync plan to ensure updates on a regular basis.
For more information, see xref:creating-a-sync-plan-by-using-web-ui[].

The synchronization duration depends on the size of each repository and the speed of your network connection.
The following table provides estimates of how long it would take to synchronize content, depending on the available Internet bandwidth:

|===
| |Single Package (10Mb)|Minor Release (750Mb)|Major Release (6Gb)

|256 Kbps|5 Mins 27 Secs|6 Hrs 49 Mins 36 Secs|2 Days 7 Hrs 55 Mins
|512 Kbps|2 Mins 43.84 Secs|3 Hrs 24 Mins 48 Secs|1 Day 3 Hrs 57 Mins
|T1 (1.5 Mbps)|54.33 Secs|1 Hr 7 Mins 54.78 Secs|9 Hrs 16 Mins 20.57 Secs
|10 Mbps|8.39 Secs|10 Mins 29.15 Secs|1 Hr 25 Mins 53.96 Secs
|100 Mbps|0.84 Secs|1 Min 2.91 Secs|8 Mins 35.4 Secs
|1000 Mbps|0.08 Secs|6.29 Secs|51.54 Secs
|===

ifdef::katello[]
.Additional resources
* xref:troubleshooting-synchronization-errors[]
endif::[]
