:_mod-docs-content-type: CONCEPT

[id="content-view-environment-categories"]
= Content view environment categories

[role="_abstract"]
Organize your content view environments into Library, unpromoted content views, and promoted content views to represent different lifecycle stages.
{Project} automatically labels these environments based on their category and content view assignments.

Library environment::
{Project} assigns the Library environment to represent the Library lifecycle environment and the *Default Organization View* content view.

Unpromoted content views::
For each content view that you publish but do not promote to a lifecycle environment, {Project} creates a content view environment.
{Project} labels these environments using the format: `Library/<content_view_label>`.

Promoted content views::
For each content view that you promote to a specific lifecycle environment, {Project} creates a corresponding content view environment.
{Project} labels these environments using the format: `<lifecycle_environment_label>/<content_view_label>`.
