:_mod-docs-content-type: CONCEPT

[id="uln-repository-upstream-and-channel-labels"]
= ULN upstream URLs and channel labels

[role="_abstract"]
Compared with generic Yum repositories, ULN requires `uln://` channel labels and Oracle account authentication.
You copy channel labels from the ULN channels interface.

There are two main differences compared to generic Yum content:

* The *Upstream URL* field consists of a protocol prefix `uln://` and an `ULN Channel Label`, for example, `ol7_x86_64_MySQL80_community`.
Combined, `uln://ol7_x86_64_MySQL80_community` is a valid upstream URL for a Yum repository.
* Authentication against the repository through an *Upstream Username* and *Upstream Password* is mandatory.
Use your single sign-on user name and token of your Oracle account to authenticate from {Project}.

To obtain a list of available ULN channel labels, log in to Oracle Unbreakable Linux Network.
Navigate to the *channels* tab and select an operating system release version and architecture.
Copy the required *ULN Channel Label* from the list of available content.

Adding ULN repositories is different compared to Yum repositories for {client-os}, for example, `\https://yum.oracle.com/oracle-linux-9.html`, which you can add as Yum-type content.

{Team} recommends that you limit the number of retained packages on {Project}.

.Additional resources
* https://docs.oracle.com/en/operating-systems/oracle-linux/uln/uln-GeneratingAuthToken.html[Generating an Authentication Token in _Unbreakable Linux Network User's Guide_]
* https://linux.oracle.com/[Oracle Unbreakable Linux Network]
* xref:adding-custom-rpm-repositories-by-using-web-ui[]
* xref:limiting-growth-of-synchronized-content-by-using-web-ui[]
