:_mod-docs-content-type: CONCEPT

[id="red-hat-offline-knowledge-portal_{context}"]
= Red{nbsp}Hat Offline Knowledge Portal

[role="_abstract"]
The Red{nbsp}Hat Offline Knowledge Portal (RHOKP) is a lightweight, secure, offline version of the online Red{nbsp}Hat Customer Portal and Knowledgebase that you can use offline and at the Edge. 

RHOKP is available with your {ProjectName} subscription.
You can install RHOKP to access Red{nbsp}Hat documentation and search the Red{nbsp}Hat Knowledgebase offline in environments with limited or no internet connectivity.

{ProjectWebUI} includes links to related documentation sources on selected pages.
If a custom RHOKP instance is available in your environment, you can configure {ProjectWebUI} to point to your RHOKP documentation source rather than the default online Red{nbsp}Hat Customer Portal documentation source at `docs.redhat.com`.

.Additional resources
* {RHDocsBaseURL}red_hat_offline_knowledge_portal/1[Red{nbsp}Hat Offline Knowledge Portal documentation]
* {AdministeringDocURL}general_settings_information_admin[Documentation for the *Red{nbsp}Hat documentation server URL* setting in _{AdministeringDocTitle}_]
