:_mod-docs-content-type: CONCEPT

[id="preparing-client-platforms"]
= Preparing client platforms

[role="_abstract"]
You have to configure the platforms that you will provision.
That entails creating a hardware model, CPU architecture, and operating system.

ifdef::katello,orcharhino,satellite[]
[NOTE]
====
The records for Red{nbsp}Hat supported platforms are created automatically when you enable a Red{nbsp}Hat repository.
====
endif::[]

Compute profiles::
+
--
You can predefine virtual machine hardware details such as CPUs, memory, and storage, by using compute profiles.

A default installation of {ProjectName} contains three predefined profiles:

* `1-Small`
* `2-Medium`
* `3-Large`

You can apply compute profiles to all supported compute resources. For supported compute resources, see the following information:

* xref:supported-cloud-providers[]
* xref:supported-virtualization-infrastructures[]

For information on creating a custom compute profile, see xref:creating-compute-profiles[].
--
