:_mod-docs-content-type: CONCEPT

[id="overview-of-the-installation-process"]
= Overview of the installation process

The {Project} installation process consists of the following main phases:
* Planning
* Server preparation
* Installation and configuration

Planning::
Make sure that your infrastructure meets the prerequisites for installation:

* Ensure your hardware and software meet the minimum requirements for CPU, RAM, and storage space.
* Plan your network setup, including DNS resolution and port and firewall configuration.
* For large deployments of more than 5,000 hosts, consider using a predefined tuning profile to optimize {Project} performance.

Server preparation::
Configure the operating system and the repositories for installing {Project}:

ifndef::foreman-deb[]
* Install {EL} 9 on a newly deployed system.
endif::[]
ifdef::foreman-deb[]
* Install Debian 12 or Ubuntu 22.04 on a newly deployed system.
endif::[]
* Verify that the hostname of your {ProjectServer} resolves correctly.
* Configure your system to access the necessary repositories, which contain the {Project} packages.

Installation and configuration::
Install {Project} packages,  execute the `{foreman-installer}`, and perform any additional configuration

* Install the {Project} package and all its dependencies.
* Use the `{foreman-installer}` command to perform the initial server setup.
ifndef::foreman-el,foreman-deb[]
* Import your subscription manifest.
endif::[]
* Optional: Enable additional features like remote execution, configuring custom SSL certificates, and email notifications.

.Additional resources
* {PlanningDocURL}[{PlanningDocTitle}]
