:_mod-docs-content-type: CONCEPT

[id="boot-disk-types"]
= Boot disk types

[role="_abstract"]
You can perform boot disk-based provisioning if your your network does not provide a DHCP service.

You can generate the following types of boot disks:

Full host image::
A boot ISO that contains the installer kernel and initial RAM disk image for a specific host.
The boot loader on this image chain loads the installer directly from the image.
This image is useful if the host fails to chain load from {ProjectServer} or {SmartProxyServer} correctly.
The provisioning template still downloads from {ProjectServer}.
+
This image is based on SYSLINUX and GRUB2 and works with most network cards.
+
This image contains a provisioning security token, therefore the generated image has a limited lifespan.
For more information about configuring the security token, see xref:configuring-the-security-token-validity-duration[].

Subnet image::
A boot ISO that is not associated with a specific host.
You can use this image if you have an environment with multiple subnets, where hosts do not have access to {ProjectServer} but can access {SmartProxy} in the particular subnet.
You can use this image to boot multiple hosts on the same subnet.
The boot loader on this image chain loads the installer from the TFTP {SmartProxy} of the host.
+
The ISO sends the MAC address of the host to {SmartProxy}, which matches the MAC address against the host entry.
The image does not store IP address details and requires access to a DHCP server on the network to bootstrap.
This image is generic to all hosts with a provisioning NIC on the same subnet.
+
This image is based on iPXE boot firmware.
Only a limited number of network cards is supported.
For more information, see https://ipxe.org/appnote/hardware_drivers[supported hardware drivers at ipxe.org].

ifndef::satellite[]
Generic image::
A boot ISO that is not associated with a specific host.
The boot loader on this image chain loads the installer from {ProjectServer}.
+
The ISO sends the MAC address of the host to {SmartProxy}, which matches the MAC address against the host entry.
The image does not store IP address details and requires access to a DHCP server on the network to bootstrap.
+
This image is based on iPXE boot firmware.
Only a limited number of network cards is supported.
For more information, see https://ipxe.org/appnote/hardware_drivers[supported hardware drivers at ipxe.org].
+
This image does not support UEFI systems.

Host image::
A boot ISO for a specific host.
This image contains only the boot files that are necessary to access the installation media on {ProjectServer}.
You define the subnet data in {Project} and the image is created with static networking.
+
This image is based on iPXE boot firmware.
Only a limited number of network cards is supported.
For more information, see https://ipxe.org/appnote/hardware_drivers[supported hardware drivers at ipxe.org].
+
This image contains a provisioning security token, therefore the generated image has a limited lifespan.
For more information about configuring the security token, see xref:configuring-the-security-token-validity-duration[].
+
This image does not support UEFI systems.
endif::[]
