[id="configuring-kerberos-sso-with-{FreeIPA-context}-in-project_{context}"]
= Configuring Kerberos SSO with {FreeIPA} in {Project}

{FreeIPA} is an open-source identity management solution that provides centralized authentication, authorization, and account management services.
With {Project}, you can integrate {ProjectServer} with your existing {FreeIPA} server to enable {FreeIPA} users to authenticate to {Project}.

With your {FreeIPA} server configured as an external identity provider, users defined in {FreeIPA} can log in to {Project} with their {FreeIPA} credentials.
If cross-forest trust is configured between {FreeIPA} and Active{nbsp}Directory, Active{nbsp}Directory users can also log in to {Project}.

{FreeIPA} users can log in using the following methods:

* Username and password
* Kerberos single sign-on

When cross-forest trust is configured between {FreeIPA} and Active{nbsp}Directory, Active{nbsp}Directory users can log in to {Project} with their user principal name (UPN) and password.

ifndef::orcharhino[]
For information about {FreeIPA}, including its cross-forest trust functionality, see link:{RHELDocsBaseURL}8/html/planning_identity_management/index[{RHEL}{nbsp}8 _Planning Identity Management_] and link:{RHELDocsBaseURL}8/html/installing_identity_management/index[{RHEL}{nbsp}8 _Installing Identity Management_].
endif::[]
