[id="Products_and_Repositories_{context}"]
= Products and Repositories in {Project}

ifdef::satellite[]
Both Red Hat content and custom content in {Project} have similarities:
endif::[]
ifdef::foreman-el,katello[]
Content from upstream as well as from Canonical, Oracle, Red Hat, SUSE, and custom content in {Project} have similarities:
endif::[]

ifndef::orcharhino[]
* The relationship between a Product and its repositories is the same and the repositories still require synchronization.
* {customproducttitle}s require a subscription for hosts to access, similar to subscriptions to Red Hat Products.
{Project} creates a subscription for each {customproduct} you create.

Red Hat content is already organized into Products.
For example, {RHEL} Server is a _Product_ in {Project}.
The repositories for that Product consist of different versions, architectures, and add-ons.
For Red{nbsp}Hat repositories, Products are created automatically after enabling the repository.
For more information, see xref:Enabling_Red_Hat_Repositories_{context}[].

Other content can be organized into {customproduct}s however you want.
For example, you might create an EPEL (Extra Packages for Enterprise Linux) Product and add an "EPEL 7 x86_64" repository to it.
endif::[]

ifdef::orcharhino[]
You can organize content in Products.
Products bundle an arbitrary number of repositories.

{customproducttitle}s require a subscription for hosts to access.
{Project} creates a subscription for each {customproduct} you create.
endif::[]

ifdef::satellite[]
For more information about creating and packaging RPMs, see the https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/rpm_packaging_guide/[_{RHEL} RPM Packaging Guide_].
endif::[]
