[id="configuring-sso-and-2fa-with-keycloak-in-project_{context}"]
= Configuring SSO and 2FA with {keycloak-quarkus} in {Project}

{keycloak-quarkus} is an open-source identity and access management solution that provides authentication features, such as single sign-on functionality, user federation, and centralized authentication management.
With {keycloak-quarkus}, you can integrate {ProjectServer} with your existing {keycloak-quarkus} server to delegate user authentication and authorization to {keycloak-quarkus}.

{keycloak} users can log in using the following login methods:

* User name and password in {ProjectWebUI} and Hammer CLI
* Time-based one-time password (TOTP), an implementation of two-factor authentication (2FA)
ifndef::satellite,orcharhino[]
* {PIV} cards
endif::[]

ifdef::satellite[]
For information about {RHBK}, see link:{RHDocsBaseURL}red_hat_build_of_keycloak[{RHBK} documentation].
endif::[]
ifndef::satellite[]
For information about {keycloak}, see link:https://www.keycloak.org/documentation[{keycloak} documentation].
endif::[]
