:_mod-docs-content-type: CONCEPT

[id="single-locations-with-segregated-subnets"]
= Single location with segregated subnets

[role="_abstract"]
You can deploy many isolated subnets in a single geographic location by using a single {SmartProxy} to manage hosts and compute resources in segregated networks.
This ensures they only access the {SmartProxy} for provisioning and management.

Your infrastructure might require multiple isolated subnets even if {ProjectName} is deployed in a single geographic location.
This can be achieved for example by deploying multiple {SmartProxyServers} with DHCP and DNS services, but the recommended way is to create segregated subnets using a single {SmartProxy}.
This {SmartProxy} is then used to manage hosts and compute resources in those segregated networks to ensure they only have to access the {SmartProxy} for provisioning, configuration, errata, and general management.
For more information on configuring subnets, see {ManagingHostsDocURL}[_{ManagingHostsDocTitle}_].
