:_mod-docs-content-type: CONCEPT

[id="Using_Content_Views_{context}"]
= Using content views

[role="_abstract"]
{Project} uses the concept of content views to create snapshots of a set of repositories and make them available to hosts registered to it.
For example, if you want a group of hosts to have access to a specific version of a set of repositories, add those repositories to a content view, publish and promote to a lifecycle environment.
You can then register hosts to this content view.
These hosts have access only to repositories at the version specified in the content view.
This means that you can continue to update repositories on your server while your hosts still consume only the versions of the repositories that they are registered to.
If you do not use content views and lifecycle environments, all your hosts consume content from the Default content view and Library environment, which is a snapshot of the latest version of the content on your server.
For more information about content management using content views and application lifecycles, see:

* xref:Managing_Content_Views_{context}[]
* xref:Managing_Application_Lifecycles_{context}[]
