:_mod-docs-content-type: CONCEPT

[id="managing-flatpak-repositories-in-project"]
= Managing Flatpak repositories in {Project}

[role="_abstract"]
Distribute and manage Flatpak applications across your desktop environments using {Project} Flatpak repositories.
Centralized Flatpak management enables controlled application deployment while maintaining access to portable desktop applications.

Flatpak repositories function similarly to other content repositories in {Project}. 
You can synchronize, manage access permissions, and assign repositories to specific lifecycle environments to control which applications are available to systems. 
You can also use Hammer CLI to manage Flatpak repositories.

For more information, see {RHELDocsBaseURL}9/html/administering_the_system_using_the_gnome_desktop_environment/assembly_installing-applications-using-flatpak_administering-the-system-using-the-gnome-desktop-environment[Installing applications using Flatpak].

ifdef::orcharhino[]
include::snip_important-consuming-content-requires-a-subscription.adoc[]
endif::[]
