[id="upgrading_prerequisites_{context}"]
== Prerequisites

Upgrading to {Project} {ProjectVersion} affects your entire {Project} infrastructure.
Before proceeding, complete the following:

* Read the {ProjectName} {ProjectVersion} {ReleaseNotesDocURL}[Release Notes].
* Ensure that you have sufficient storage space on your server.
For more information, see {InstallingServerDocURL}Preparing_your_Environment_for_Installation_{project-context}[Preparing your Environment for Installation] in _{InstallingServerDocTitle}_ and {InstallingSmartProxyDocURL}preparing-environment-for-capsule-installation[Preparing your Environment for Installation] in _Installing {SmartProxyServer}_.
* Back up your {ProjectServer} and all {SmartProxyServers}.
For more information, see {AdministeringDocURL}backing-up-{project-context}-server-and-{smart-proxy-context}_admin[Backing Up {ProjectServer} and {SmartProxyServer}] in _{AdministeringDocTitle}_.
* Plan for updating any scripts you use that contain {Project} API commands because some API commands differ between versions of {Project}.
ifdef::satellite[]
* Ensure that all {ProjectServer}s are on the same version.
ifeval::["{mode}" == "connected"]
* If you use Red{nbsp}Hat Insights, unregister the {ProjectServer} in Insights before upgrading to avoid duplicate entries.
For more information, see https://docs.redhat.com/en/documentation/red_hat_insights/1-latest/html-single/client_configuration_guide_for_red_hat_insights/index#proc-unregistering-system-insights_insights-cg-configuring-client[Unregistering your system with Red Hat Insights]. 
Re-register the {ProjectServer} to Insights after the upgrade.
endif::[]
endif::[]

include::snip_warning-maintain-config-noop.adoc[]
