[id="SCAP_Content_{context}"]
= SCAP Content

SCAP content is a datastream format containing the configuration and security baseline against which hosts are checked.
Checklists are described in the extensible checklist configuration description format (XCCDF) and vulnerabilities in the open vulnerability and assessment language (OVAL).
Checklist items, also known as rules express the desired configuration of a system item.
For example, you may specify that no one can log in to a host over SSH using the `root` user account.
Rules can be grouped into one or more profiles, allowing multiple profiles to share a rule.
SCAP content consists of both rules and profiles.

You can either create SCAP content or obtain it from a vendor.
Supported profiles are provided for {RHEL} in the `scap-security-guide` package.
ifndef::orcharhino[]
The creation of SCAP content is outside the scope of this guide, but see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/security_hardening/[{RHEL} 8 Security Hardening] for information on how to download, deploy, modify, and create your own content.
endif::[]

The default SCAP content provided with the OpenSCAP components of {Project} depends on the version of {RHEL}.
On {RHEL} 7, content for both {RHEL} 6 and {RHEL} 7 is installed.
