[id="prerequisites-for-integrating-{project-context}-with-keycloak_{context}"]
= Prerequisites for Configuring {Project} with {Keycloak} Authentication

Before configuring {Project} with {Keycloak} external authentication, ensure that you meet the following requirements:

* A working installation of {Keycloak} server that uses HTTPS instead of HTTP.
* A {Keycloak} account with admin privileges.
* A realm for {Project} user accounts created in {Keycloak}.
* If the certificates or the CA are self-signed, ensure that they are added to the end-user certificate trust store.
* Users imported or added to {Keycloak}.
+
If you have an existing user database configured such as LDAP or Kerberos, you can import users from it by configuring user federation.
ifndef::orcharhino[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/server_administration_guide/user-storage-federation[User Storage Federation] in the _Red{nbsp}Hat Single Sign-On Server Administration Guide_.
endif::[]
+
If you do not have an existing user database configured, you can manually create users in {Keycloak}.
ifndef::orcharhino[]
For more information, see https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.4/html/server_administration_guide/user_management#create-new-user[Creating New Users] in the _Red{nbsp}Hat Single Sign-On Server Administration Guide_.
endif::[]
