[id="Active_Directory_with_Cross_Forest_Trust_{context}"]
= Active Directory with Cross-Forest Trust

Kerberos can create `cross-forest trust` that defines a relationship between two otherwise separate domain forests.
A domain forest is a hierarchical structure of domains; both AD and {FreeIPA} constitute a forest.
With a trust relationship enabled between AD and {FreeIPA}, users of AD can access Linux hosts and services using a single set of credentials.
ifndef::orcharhino[]
For more information on cross-forest trusts, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/windows_integration_guide/active-directory-trust[Creating Cross-forest Trusts with Active Directory and Identity Management] in the _{RHEL} Windows Integration_ guide.
endif::[]

From the {Project} point of view, the configuration process is the same as integration with {FreeIPA} server without cross-forest trust configured.
{ProjectServer} has to be enrolled in the IdM domain and integrated as described in xref:Using_FreeIPA_{context}[].
