[id="Registering_Hosts_to_Server_{context}"]
= Registering Hosts to {Project}

There are three main methods for registering hosts to {ProjectServer} or {SmartProxyServer}:

. *(Default method)* Generate a `curl` command from {Project} and run this command from unlimited number of hosts to register them using the global registration template.
This method is suited for hosts that haven't been registered to {Project} yet.
+
By using this method you can also deploy {Project} SSH keys to hosts during registration to {Project} to enable hosts for remote execution jobs.
For more information about the remote execution jobs, see {ManagingHostsDocURL}Configuring_and_Setting_Up_Remote_Jobs_managing-hosts[Configuring and Setting up Remote Jobs].
+
By using this method you can also configure hosts with Red{nbsp}Hat Insights during registration to {Project}.
For more information about using Insights with {Project} hosts, see {ManagingHostsDocURL}Using_Red_Hat_Insights_with_Hosts_managing-hosts[Monitoring Hosts Using Red{nbsp}Hat Insights].
. *(Deprecated)* Download and install the consumer RPM `_{foreman-example-com}_/pub/katello-ca-consumer-latest.noarch.rpm` and then run Subscription Manager.
This method is suited for hosts that haven't been provisioned through {Project}.
. *(Deprecated)* Download and run the bootstrap script (`_{foreman-example-com}_/pub/bootstrap.py`).
This method is suited for hosts that haven't been provisioned through {Project}.

You can also register Atomic Hosts to {ProjectServer} or {SmartProxyServer}.

Use one of the following procedures to register a host:

* xref:Registering_Hosts_{context}[]
* xref:Registering_an_Atomic_Host_{context}[]
* xref:Registering_a_Host_Using_the_Bootstrap_Script_{context}[]

Use the following procedures to install and configure host tools:

* xref:Installing_the_Katello_Agent_{context}[]
* xref:Installing_Tracer_{context}[]
* xref:Installing_and_Configuring_the_Puppet_Agent_on_a_Host_Manually_{context}[]

ifdef::satellite[]
.Supported Host Operating Systems

Hosts must use one of the following {RHEL} versions:

* 6.1 or later*
* 7.0 or later
* 8.0 or later

NOTE: Red{nbsp}Hat Enterprise{nbsp}Linux versions 6.1, 6.2, and 6.3 require `subscription-manager` and related packages to be updated manually.
For more information, see https://access.redhat.com/solutions/1256763[].

.Supported Architectures

All architectures of {RHEL} are supported:

* i386
* x86_64
* s390x
* ppc_64
endif::[]
