[id="requirements-for-installation-in-an-ipv6-network_{context}"]
= Requirements for {Project} Installation in an IPv6 Network

Before installing {Project} in an IPv6 network, ensure that you meet the following requirements:

ifdef::satellite[]
* If you plan to provision hosts from {Project} or {SmartProxies}, you must install {Project} and {SmartProxies} on {RHEL} version 7.9 or higher because these versions include the latest version of the `grub2` package.
endif::[]

ifndef::satellite[]
* If you plan to provision hosts from {Project} or {SmartProxy}, you must install {Project} and {SmartProxies} on a system with `grub2` version 2.05 or higher or system with fixes for HTTP Boot, for example CentOS version 7.9 or 8.3 or higher.
For other operating systems, copy the newest GRUB build to `/var/lib/tftpboot/grub2/grubx64.efi`.
endif::[]

* You must deploy an external DHCP IPv6 server as a separate unmanaged service to bootstrap clients into GRUB2, which then configures IPv6 networking either using DHCPv6 or or assigning static IPv6 address.
This is required because the DHCP server in {RHEL} (ISC DHCP) does not provide an integration API for managing IPv6 records, therefore the {SmartProxy} DHCP plug-in that provides DHCP management is limited to IPv4 subnets.

* You must deploy an external IPv4 HTTP proxy server.
This is required because the Red Hat Content Delivery Network distributes content only over IPv4 networks, therefore you must use this proxy to pull content into the {Project} on your IPv6 network.
ifndef::satellite[]
+
Note that this requirement is for Katello users only.
endif::[]

* You must configure {Project} to use this IPv4 HTTP proxy server as the default proxy.
For more information, see {InstallingProjectDocURL}adding-a-default-http-proxy_{project-context}[Adding a Default HTTP Proxy to Satellite].
