[id="PostgreSQL_Tuning_{context}"]
= PostgreSQL Tuning

PostgreSQL is the primary SQL based database that is used by {Project} for the storage of persistent context across a wide variety of tasks that {Project} does.
The database sees an extensive usage is usually working on to provide the {Project} with the data which it needs for its smooth functioning.
This makes PostgreSQL a heavily used process which if tuned can have a number of benefits on the overall operational response of {Project}.

We recommend disabling Transparent Huge Pages on server running PostgreSQL.
For more about it please see xref:Disable_Transparent_Huge_Pages_{context}[].

You can apply a set of tunings to PostgreSQL to improve its response times, which will modify the `postgresql.conf` file.

.Procedure
. Append `/etc/foreman-installer/custom-hiera.yaml` to tune PostgreSQL:
+
[source,yaml]
----
postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 2GB
  work_mem: 8MB
  autovacuum_vacuum_cost_limit: 2000
----
+
You can use this to effectively tune down your {Project} instance irrespective of a tuning profile.
. Apply your changes to {ProjectServer}.
For more information, see xref:Applying_configurations_{context}[].

In the above tuning configuration, there are a certain set of keys which we have altered:

* `max_connections`: The key defines the maximum number of connections that can be accepted by the PostgreSQL processes that are running.
* `shared_buffers`: The shared buffers define the memory used by all the active connections inside PostgreSQL to store the data for the different database operations.
An optimal value for this will vary between 2 GiB to a maximum of 25% of your total system memory depending upon the frequency of the operations being conducted on {Project}.
* `work_mem`: The work_mem is the memory that is allocated on per process basis for PostgreSQL and is used to store the intermediate results of the operations that are being performed by the process.
Setting this value to 8 MB should be more than enough for most of the intensive operations on {Project}.
* `autovacuum_vacuum_cost_limit`: The key defines the cost limit value for the vacuuming operation inside the autovacuum process to clean up the dead tuples inside the database relations.
The cost limit defines the number of tuples that can be processed in a single run by the process.
{Team} recommends setting the value to `2000` as it is for the _medium_, _large_, _extra-large_, and _extra-extra-large_ profiles, based on the general load that {Project} pushes on the PostgreSQL server process.

ifndef::orcharhino[]
For more information, see https://bugzilla.redhat.com/show_bug.cgi?id=1867311#c12[BZ1867311: Upgrade fails when checkpoint_segments postgres parameter configured].
endif::[]
