:_mod-docs-content-type: CONCEPT

[id="ssl-authentication-overview"]
= SSL authentication overview

[role="_abstract"]
{ProjectName} uses HTTPS, which provides a degree of encryption and identity verification when communicating with {ProjectServer}.
{Project} {ProjectVersion} does not support non-SSL communications.

By default, {ProjectServer} uses a self-signed certificate.
This certificate acts as both the server certificate to verify the encryption key and the certificate authority (CA) to trust the identity of {ProjectServer}.

You can configure {ProjectServer} to use a custom SSL certificate.
For more information, see {InstallingServerDocURL}configuring-{project-context}-server-with-a-custom-ssl-certificate[Configuring {ProjectServer} with a custom SSL certificate] in _{InstallingServerDocTitle}_.
ifdef::satellite[]
For more information on disconnected {ProjectServer}, see {InstallingServerDisconnectedDocURL}configuring-{project-context}-server-with-a-custom-ssl-certificate[Configuring {ProjectServer} with a custom SSL certificate] in _{InstallingServerDisconnectedDocTitle}_.
endif::[]
