:_mod-docs-content-type: CONCEPT

[id="pulp-data-considerations"]
= Pulp data considerations

[role="_abstract"]
You can clone {ProjectServer} without Pulp data, but you must transfer the Pulp data afterwards to achieve a fully working environment.

You can clone {ProjectServer} without including Pulp data.
However, for your cloned environment to work, you do require Pulp data.
If the target server does not have Pulp data, it is not a fully working {Project}.

To transfer Pulp data to a target server, you have two options:

* Clone using backup with Pulp data
* Clone using backup without Pulp data and copy `/var/lib/pulp` manually from the source server.
+
If your `pulp_data.tar` file is greater than 500 GB, or if you use a slow storage system, such as NFS, and your `pulp_data.tar` file is greater than 100 GB, do not include `pulp_data.tar` in the backup because this can cause memory errors during extraction.
Instead, copy the `pulp_data.tar` file from the source server to the target server.
