:_mod-docs-content-type: CONCEPT

[id="how-predefined-tuning-profiles-apply"]
= How predefined tuning profiles apply

[role="_abstract"]
When you run the `{foreman-installer}` command with the `--tuning` option, deployment configuration settings from multiple sources are applied to {Project} in a specific order.
This order defines the priority of these settings.

{Project} loads tuning configuration settings from the following sources:

Custom Hiera settings::
If you use custom Hiera settings on your {ProjectServer}, you can find them in the `/etc/foreman-installer/custom-hiera.yaml` file.

Default tuning profile::
The settings for this profile are defined in the `/usr/share/foreman-installer/config/foreman.hiera/tuning/common.yaml` file.

Predefined tuning profile::
This is the profile that you select when running the `{foreman-installer}` command with the `--tuning` option.
The settings for these profiles are defined in the `/usr/share/foreman-installer/config/foreman.hiera/tuning/sizes/` directory.

When merging these settings, {Project} applies them in the following order:

* Custom settings in the `/etc/foreman-installer/custom-hiera.yaml` file override the settings in the predefined and default profiles.
* The predefined profile overrides the settings in the default profile.
