[id="Managing_Activation_Keys_{context}"]
= Managing activation keys

Activation keys provide a method to automate system registration.
You can create multiple keys and associate them with different environments and content views.
For example, you might create a basic activation key that enables certain Red Hat repositories and associate it with the appropriate content view.

You can use activation keys during content host registration to improve the speed, simplicity and consistency of the process.
Note that activation keys are used only when hosts are registered.
If changes are made to an activation key, it is applicable only to hosts that are registered with the amended activation key in the future.
The changes are not made to existing hosts.

Activation keys can define the following properties for content hosts:

* Available products and repositories
* A lifecycle environment and a content view
* Host collection membership
* System purpose

.Content view conflicts between host creation and registration
When you provision a host, {Project} uses provisioning templates and other content from the content view that you set in the host group or host settings.
When the host is registered, the content view from the activation key overwrites the original content view from the host group or host settings.
Then {Project} uses the content view from the activation key for every future task, for example, rebuilding a host.

When you rebuild a host, ensure that you set the content view that you want to use in the activation key and not in the host group or host settings.

.Using multiple activation keys with a content host
A host can be associated with multiple activation keys that are combined to define the host settings.
In case of conflicting settings, the last specified activation key takes precedence.
You can specify the order of precedence by setting a host group parameter as follows:

[options="nowrap" subs="+quotes"]
----
$ hammer hostgroup set-parameter \
--hostgroup "_My_Host_Group_" \
--name "_My_Activation_Key_" \
--value "_name_of_first_key_", "_name_of_second_key_", ...
----
