[id="Quick-start-overview_{context}"]
= Using this guide

The {Project} installer is a collection of Puppet modules that installs everything required for a full working {Project} setup.
It uses native OS packaging (`.rpm` or `.deb` packages) and adds necessary configuration for the complete installation.

The {Project} components include the web UI, {SmartProxy}, a Puppet server, TFTP, DNS, and DHCP servers.
It is configurable and the Puppet modules can be read or run in "no-op" mode to see what changes it will make.

You can quickly install and configure your {ProjectServer} if the following assumptions apply to your environment:

* You are performing a fresh installation.
* You can connect to the Red{nbsp}Hat Content Delivery Network, located at `cdn.redhat.com`, to obtain packages and receive updates.
* You have an existing host that you want to register to {Project} to use for patching.
// To be confirmed with Ian Ballou or Jeremy Lenz
* Your deployment uses simple Content Views.

If your environment does not fit with these assumptions, see the following resources:

* link:{InstallingServerDocURL}[{InstallingServerDocTitle}]
* link:{InstallingServerDisconnectedDocURL}[{InstallingServerDisconnectedDocTitle}]
