:_mod-docs-content-type: CONCEPT

[id="conditions-for-content-availability"]
= Conditions for content availability

[role="_abstract"]
Ensure your hosts can access required packages by verifying content view settings, repository enablement, and architecture compatibility.
Content availability depends on a combination of content view publication, filter settings, and repository overrides.

* The repository is included in the content view environments of the host.
* The content view of the host has been published after the repository was added to it.
* The repository has not been filtered out by a content view filter.
* The repository is enabled by default or overridden to *Enabled* by using a content override.
* The repository has no architecture or operating system version restrictions or it has architecture or operating system version restrictions that match the host.
ifndef::orcharhino[]
* For certain Red{nbsp}Hat repositories either no release version is set or the release version matches that of the host.
endif::[]
ifdef::orcharhino[]
ifdef::red_hat_enterprise_linux[]
* For certain Red{nbsp}Hat repositories either no release version is set or the release version matches that of the host.
endif::[]
endif::[]
