:_mod-docs-content-type: CONCEPT

[id="Registering_Hosts_by_Using_Global_Registration_{context}"]
= Registering hosts by using global registration

[role="_abstract"]
You can register hosts to {Project} by generating a `curl` or `wget` registration command on {Project} and running this command on multiple hosts.

Global registration uses two provisioning templates: *Global Registration* template and *Linux host_init_config default* template.
That gives you complete control over the host registration process.

With this registration method, you can modify the initial configuration templates to enable additional features.
For example, you can deploy {Project} SSH keys to hosts to enable remote execution jobs, configure hosts with {Insights}, or install the OpenVox agent on hosts to enable configuration management with Puppet.

ifndef::satellite[]
If you use the Resource Quota plugin, registered hosts are automatically assigned to the `Unassigned` resource quota.
However, if you have the setting `Resource Quota optional assignment` set to `No` and no quotas to that a host can be assigned to, the host registration will fail because there is no valid quota the host can be assigned to.
For more information, see {AdministeringDocURL}limiting-host-resources[Limiting host resources] in _{AdministeringDocTitle}_.
endif::[]

ifndef::satellite,orcharhino[]
You can extend registration options by plugins.
For more information, see https://github.com/theforeman/foreman/blob/develop/developer_docs/how_to_create_a_plugin.asciidoc[How to Create a Plugin] and https://github.com/theforeman/foreman/blob/develop/developer_docs/slot-and-fill.asciidoc[Slot and Fill].
endif::[]
