[id="Remote-Execution-in-{Project}_{context}"]
= Remote Execution in {ProjectName}

[role="_abstract"]
With remote execution, you can run jobs on hosts remotely from {SmartProxies} using shell scripts or Ansible tasks and playbooks.

Use remote execution for the following benefits in {Project}:

* Run jobs on multiple hosts at once.
* Use variables in your commands for more granular control over the jobs you run.
* Use host facts and parameters to populate the variable values.
* Specify custom values for templates when you run the command.

Communication for remote execution occurs through {SmartProxyServer}, which means that {ProjectServer} does not require direct access to the target host, and can scale to manage many hosts.
ifeval::["{context}" == "ansible"]
For more information, see xref:transport-modes-for-remote-execution_{context}[].
endif::[]

[NOTE]
====
Any {SmartProxyServer} base operating system is a client of the internal {SmartProxy} in the {ProjectServer}, and therefore this section applies to any type of host connected to {ProjectServer}, including {SmartProxies}.
====

To use remote execution, you must define a _job template_.
A job template is a command that you want to apply to remote hosts.
You can execute a job template multiple times.

{Project} uses ERB syntax job templates.
ifdef::managing-hosts[]
For more information, see xref:Template_Writing_Reference_{context}[].
endif::[]
ifndef::managing-hosts[]
For more information, see {ManagingHostsDocURL}Template_Writing_Reference_managing-hosts[Template Writing Reference] in _{ManagingHostsDocTitle}_.
endif::[]

Several job templates for shell scripts and Ansible are included by default.
For more information, see {ManagingHostsDocURL}setting-up-job-templates_managing-hosts[Setting up Job Templates] in _{ManagingHostsDocTitle}_.

.Additional resources
* See {ManagingHostsDocURL}executing-a-remote-job_managing-hosts[Executing a Remote Job] in _{ManagingHostsDocTitle}_.
ifeval::["{context}" == "planning"]
* See {ManagingConfigurationsAnsibleDocURL}Configuring_and_Setting_Up_Remote_Jobs_ansible[_Configuring and Setting Up Remote Jobs_].
endif::[]
