[id="provisioning-overview_{context}"]
= Provisioning Overview

Provisioning is a process that starts with a bare physical or virtual machine and ends with a fully configured, ready-to-use operating system.
Using {ProjectName}, you can define and automate fine-grained provisioning for a large number of hosts.

There are many provisioning methods.
ifndef::satellite[]
For example, you can use {ProjectServer}'s integrated {SmartProxy} or an external {SmartProxyServer} to provision bare metal hosts using both PXE based and non-PXE based methods.
endif::[]
ifdef::satellite[]
For example, you can use {ProjectServer}'s integrated {SmartProxy} or an external {SmartProxyServer} to provision bare metal hosts using PXE based methods.
endif::[]
You can also provision cloud instances from specific providers through their APIs.
These provisioning methods are part of the {ProjectName} application life cycle to create, manage, and update hosts.

{ProjectName} has different methods for provisioning hosts:

Bare Metal Provisioning::
{Project} provisions bare metal hosts primarily through PXE boot and MAC address identification.
You can create host entries and specify the MAC address of the physical host to provision.
You can also boot blank hosts to use {Project}'s discovery service, which creates a pool of ready-to-provision hosts.
ifndef::satellite[]
You can also boot and provision hosts through PXE-less methods.
endif::[]

Cloud Providers::
{Project} connects to private and public cloud providers to provision instances of hosts from images that are stored with the Cloud environment.
This also includes selecting which hardware profile or flavor to use.

Virtualization Infrastructure::
  {Project} connects to virtualization infrastructure services such as {oVirt} and VMware to provision virtual machines from virtual image templates or using the same PXE-based boot methods as bare metal providers.

ifdef::orcharhino[]
Refer to the xref:sources/compute_resources.adoc[compute resource chapter] for more information.
endif::[]
