[id="provisioning-contexts_{context}"]
= Provisioning Contexts

A provisioning context is the combination of an organization and location that you specify for {Project} components.
The organization and location that a component belongs to sets the ownership and access for that component.

Organizations divide {ProjectName} components into logical groups based on ownership, purpose, content, security level, and other divisions.
You can create and manage multiple organizations through {ProjectName} and assign components to each individual organization.
This ensures {ProjectServer} provisions hosts within a certain organization and only uses components that are assigned to that organization.
ifdef::satellite[]
For more information about organizations, see {ContentManagementDocURL}Managing_Organizations_content-management[Managing Organizations] in _{ContentManagementDocTitle}_.
endif::[]
ifndef::satellite[]
For more information about organizations, see {ManagingOrganizationsLocationsDocURL}Managing_Organizations_managing-organizations-locations[Managing Organizations] in _{ManagingOrganizationsLocationsDocTitle}_.
endif::[]

Locations function similar to organizations.
The difference is that locations are based on physical or geographical setting.
Users can nest locations in a hierarchy.
ifdef::satellite[]
For more information about locations, see {ContentManagementDocURL}Managing_Locations_content-management[Managing Locations] in _{ContentManagementDocTitle}_.
endif::[]
ifndef::satellite[]
For more information about locations, see {ManagingOrganizationsLocationsDocURL}Managing_Locations_managing-organizations-locations[Managing Locations] in _{ManagingOrganizationsLocationsDocTitle}_.
endif::[]
