:_mod-docs-content-type: CONCEPT

[id="Download_Policies_Overview_{context}"]
= Download policies overview

[role="_abstract"]
Control when {Project} downloads repository packages using Immediate, On Demand, or Inherit download policies.
On Demand policies save time and storage by downloading only metadata during synchronization and fetching packages when clients request them.

{ProjectServer} has the following policies:

Immediate::
{ProjectServer} downloads all metadata and packages during synchronization.

On Demand::
{ProjectServer} downloads only the metadata during synchronization.
{ProjectServer} only fetches and stores packages on the file system when {SmartProxies} or directly connected clients request them.
This setting has no effect if you set a corresponding repository on a {SmartProxy} to *Immediate* because {ProjectServer} is forced to download all the packages.

The *On Demand* policy acts as a _Lazy Synchronization_ feature because they save time synchronizing content.
ifdef::satellite[]
The lazy synchronization feature must be used only for Yum repositories.
endif::[]
ifndef::satellite[]
The lazy synchronization feature must be used only for Deb and Yum repositories.
endif::[]
You can add the packages to content views and promote to lifecycle environments as normal.

{SmartProxyServer} has the following policies:

Immediate::
{SmartProxyServer} downloads all metadata and packages during synchronization.
Do not use this setting if the corresponding repository on {ProjectServer} is set to *On Demand* as {ProjectServer} is forced to download all the packages.

On Demand::
{SmartProxyServer} only downloads the metadata during synchronization.
{SmartProxyServer} fetches and stores packages only on the file system when directly connected clients request them.
When you use an *On Demand* download policy, content is downloaded from {ProjectServer} if it is not available on {SmartProxyServer}.

Inherit::
{SmartProxyServer} inherits the download policy for the repository from the corresponding repository on {ProjectServer}.

Streamed Download Policy::
Streamed Download Policy for {SmartProxies} permits {SmartProxies} to avoid caching any content.
When content is requested from the {SmartProxy}, it functions as a proxy and requests the content directly from the {Project}.
