[id="permissions-for-remote-execution_{context}"]
= Permissions for Remote Execution

You can control which roles can run which jobs within your infrastructure, including which hosts they can target.
The remote execution feature provides two built-in roles:

* *Remote Execution Manager*: Can access all remote execution features and functionality.

* *Remote Execution User*: Can only run jobs.

You can clone the *Remote Execution User* role and customize its filter for increased granularity.
If you adjust the filter with the `view_job_templates` permission on a customized role, you can only see and trigger jobs based on matching job templates.
You can use the `view_hosts` and `view_smart_proxies` permissions to limit which hosts or {SmartProxies} are visible to the role.

The `execute_template_invocation` permission is a special permission that is checked immediately before execution of a job begins.
This permission defines which job template you can run on a particular host.
This allows for even more granularity when specifying permissions.

You can run remote execution jobs against {ProjectName} and {SmartProxy} registered as hosts to {ProjectName} with the `execute_jobs_on_infrastructure_hosts` permission.
Standard *Manager* and *Site Manager* roles have this permission by default.
If you use either the *Manager* or *Site Manager* role, or if you use a custom role with the `execute_jobs_on_infrastructure_hosts` permission, you can execute remote jobs against registered {ProjectName} and {SmartProxy} hosts.

For more information on working with roles and permissions, see {AdministeringDocURL}Creating_and_Managing_Roles_admin[Creating and Managing Roles] in _{AdministeringDocTitle}_.

The following example shows filters for the `execute_template_invocation` permission:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
name = Reboot and host.name = staging.example.com
name = Reboot and host.name ~ *.staging.example.com
name = "Restart service" and host_group.name = webservers
----

Use the first line in this example to apply the *Reboot* template to one selected host.
Use the second line to define a pool of hosts with names ending with *.staging.example.com*.
Use the third line to bind the template with a host group.

[NOTE]
====
Permissions assigned to users with these roles can change over time.
If you have already scheduled some jobs to run in the future, and the permissions change, this can result in execution failure because permissions are checked immediately before job execution.
====
