[id="applying-custom-configuration_{context}"]
= Applying Custom Configuration to {ProjectName}

When you install and configure {Project} for the first time using `{foreman-installer}`, you can specify that the DNS and DHCP configuration files are not to be managed by Puppet using the installer flags `--foreman-proxy-dns-managed=false` and `--foreman-proxy-dhcp-managed=false`.
If these flags are not specified during the initial installer run, rerunning of the installer overwrites all manual changes, for example, rerun for upgrade purposes.
If changes are overwritten, you must run the restore procedure to restore the manual changes.
For more information, see {InstallingServerDocURL}restoring-manual-changes-overwritten-by-a-puppet-run_{project-context}[Restoring Manual Changes Overwritten by a Puppet Run].

To view all installer flags available for custom configuration, run `{installer-scenario} --full-help`.
Some Puppet classes are not exposed to the {Project} installer.
To manage them manually and prevent the installer from overwriting their values, specify the configuration values by adding entries to configuration file `/etc/foreman-installer/custom-hiera.yaml`.
This configuration file is in YAML format, consisting of one entry per line in the format of `<puppet class>::<parameter name>: <value>`.
Configuration values specified in this file persist across installer reruns.

Common examples include:

* For Apache, to set the ServerTokens directive to only return the Product name:
+
----
apache::server_tokens: Prod
----
+
* To turn off the Apache server signature entirely:
+
----
apache::server_signature: Off
----

The Puppet modules for the {Project} installer are stored under `/usr/share/foreman-installer/modules`.
Check the `.pp` files (for example: _moduleName_/manifests/_example_.pp) to look up the classes, parameters, and values.
Alternatively, use the `grep` command to do keyword searches.

Setting some values may have unintended consequences that affect the performance or functionality of {ProjectName}.
Consider the impact of the changes before you apply them, and test the changes in a non-production environment first.
If you do not have a non-production {Project} environment, run the {Project} installer with the `--noop` and `--verbose` options.
If your changes cause problems, remove the offending lines from `custom-hiera.yaml` and rerun the {Project} installer.
If you have any specific questions about whether a particular value is safe to alter, contact Red Hat support.
