[id="Managing_Red_Hat_Subscriptions_{context}"]
= Managing Red Hat Subscriptions

{ProjectName} can import content from the Red{nbsp}Hat Content Delivery Network (CDN).
{Project} requires a Red{nbsp}Hat Subscription Manifest to find, access, and download content from the corresponding repositories.
You must have a Red{nbsp}Hat Subscription Manifest containing a subscription allocation for each organization on {ProjectServer}.
All subscription information is available in your Red Hat Customer Portal account.

Before you can complete the tasks in this chapter, you must create a Red{nbsp}Hat Subscription Manifest in the Customer Portal.

ifdef::satellite[]
Note that legacy subscription management, including the need to attach subscriptions to hosts and activation keys, is deprecated and will be removed in a future release.
{Team} recommends that you use https://access.redhat.com/articles/simple-content-access[Simple Content Access] as a substitute.
endif::[]

ifndef::orcharhino[]
To create, manage, and export a Red{nbsp}Hat Subscription Manifest in the Customer Portal, see https://access.redhat.com/documentation/en-us/red_hat_subscription_management/2022/html/using_red_hat_subscription_management/using_manifests_con[Using Manifests] in _Using Red Hat Subscription Management_.
endif::[]

Use this chapter to import a Red{nbsp}Hat Subscription Manifest and manage the manifest within the {ProjectWebUI}.

.Subscription Allocations and Organizations

You can manage more than one organization if you have more than one subscription allocation.
{Project} requires a single allocation for each organization configured in {ProjectServer}.
The advantage of this is that each organization maintains separate subscriptions so that you can support multiple organizations, each with their own Red Hat accounts.

.Future-Dated subscriptions

You can use future-dated subscriptions in a subscription allocation.
When you add future-dated subscriptions to content hosts before the expiry date of the existing subscriptions, you can have uninterrupted access to repositories.

Manually attach the future-dated subscriptions to your content hosts before the current subscriptions expire.
Do not rely on the auto-attach method because this method is designed for a different purpose and might not work.
For more information, see xref:Attaching_Red_Hat_Subscriptions_to_Content_Hosts_{context}[].

.Additional resources
ifndef::satellite[]
* {InstallingServerDocURL}configuring-{project-context}-server-to-consume-content-from-a-custom-cdn_{project-context}[Configuring {ProjectServerTitle} to Consume Content from a Custom CDN] in _{InstallingServerDocTitle}_
endif::[]
ifdef::satellite[]
* {InstallingServerDisconnectedDocURL}configuring-{project-context}-server-to-consume-content-from-a-custom-cdn_{project-context}[Configuring {ProjectServerTitle} to Consume Content from a Custom CDN] in _{InstallingServerDisconnectedDocTitle}_
endif::[]
