[id="Monitoring_Hosts_Using_Red_Hat_Insights_{context}"]
= Monitoring hosts using Red{nbsp}Hat Insights

You can use Insights to diagnose systems and downtime related to security exploits, performance degradation, and stability failures.
You can use the Insights dashboard to quickly identify key risks to stability, security, and performance.
You can sort by category, view details of the impact and resolution, and then determine what systems are affected.

To use Insights to monitor hosts that you manage with {Project}, you must first install Insights on your hosts and register your hosts with Insights.

For new {Project} hosts, you can install and configure Insights during host registration to {Project}.
For more information, see xref:Registering_Hosts_by_Using_Global_Registration_{context}[].

For hosts already registered to {Project}, you can install and configure Insights on your hosts by using an Ansible role.
For more information, see xref:deploying-red-hat-insights-using-the-ansible-role_{context}[].

.Additional information
* To view the logs for all plugins, go to `/var/log/foreman/production.log`.
* If you have problems connecting to Insights, ensure that your certificates are up-to-date.
Refresh your subscription manifest to update your certificates.
* You can change the default schedule for running `insights-client` by configuring `insights-client.timer` on a host.
ifdef::satellite[]
For more information, see {RHDocsBaseURL}/red_hat_insights/1-latest/html/client_configuration_guide_for_red_hat_insights/assembly-client-changing-schedule[Changing the insights-client schedule] in the _Client Configuration Guide for Red Hat Insights_.
endif::[]
