[id="Content_Filter_Overview_{context}"]
= Content filter overview

ifdef::satellite[]
Content views also use filters to include or restrict certain Yum content.
endif::[]
ifndef::satellite[]
Content views also use filters to include or restrict certain Deb and Yum content.
endif::[]
Without these filters, a content view includes everything from the selected repositories.

There are two types of content filters:

.Filter types
[cols="1,3"]
|===
| Filter Type | Description

| *Include* | You start with no content, then select which content to add from the selected repositories.
Use this filter to combine multiple content items.
| *Exclude* | You start with all content from selected repositories, then select which content to remove.
Use this filter when you want to use most of a particular content repository while excluding certain packages.
The filter uses all content in the repository except for the content you select.
|===

.Include and Exclude filter combinations
If using a combination of Include and Exclude filters, publishing a content view triggers the include filters first, then the exclude filters.
In this situation, select which content to include, then which content to exclude from the inclusive subset.

.Content types

You can filter content based on the following content types:

.Content types
[cols="2,3"]
|===
| Content Type | Description

ifdef::client-content-dnf[]
|*RPM* | Filter packages based on their name and version number.
The *RPM* option filters non-modular RPM packages and errata.
Source RPMs are not affected by this filter and will still be available in the content view.
endif::[]
ifdef::client-content-apt[]
|*Deb* | Filter packages based on their name.
The *Deb* option filters Deb packages.
endif::[]
|*Package Group* | Filter packages based on package groups.
The list of package groups is based on the repositories added to the content view.
| *Erratum (by ID)* | Select which specific errata to add to the filter.
The list of Errata is based on the repositories added to the content view.
| *Erratum (by Date and Type)* | Select a issued or updated date range and errata type (Bugfix, Enhancement, or Security) to add to the filter.
ifdef::client-content-dnf[]
| *Module Streams* | Select whether to include or exclude specific module streams.
The *Module Streams* option filters modular RPMs and errata, but does not filter non-modular content that is associated with the selected module stream.
endif::[]
| *Container Image Tag* | Select whether to include or exclude specific container image tags.
|===
