:_mod-docs-content-type: CONCEPT

[id="{project-context}-api-overview"]
= {Project} API overview

[role="_abstract"]
Integrate with enterprise systems, automate repetitive tasks, and manage your infrastructure programmatically using the resource-based REST model of the {Project} API.
You can use any HTTP client to interact with {Project}.

Using the REST API has the following benefits:

* Broad client support {endash} any programming language, framework, or system with support for HTTP protocol can use the API.
* Self-descriptive {endash} client applications require minimal knowledge of the {Project} infrastructure because users discover many details at runtime.
* Resource-based model {endash} the resource-based REST model provides a natural way to manage a virtualization platform.

You can use the REST API to perform the following tasks:

* Integrate with enterprise IT systems.
* Integrate with third-party applications.
* Perform automated maintenance or error checking tasks.
* Automate repetitive tasks with scripts.

Scripts based on API commands communicate directly with the {Project} API, which makes them faster than scripts based on Hammer commands or Ansible Playbooks relying on modules within {ansible-namespace}.

[IMPORTANT]
====
API commands differ between versions of {Project}.
When you prepare to upgrade {ProjectServer}, update all the scripts that contain {Project} API commands.
====

.Additional resources
* {APIDocURL}[_{APIDocTitle}_]
