[[configuring_satellite_external_dns]]

= Configuring {Project} with External DNS

You can configure {Project} to use an external server to provide DNS service.

. Deploy a Red Hat Enterprise Linux Server and install the ISC DNS Service.
+
[options="nowrap" subs="+quotes,attributes"]
----
# {install} bind bind-utils
----

. Create the configuration file for a domain.
+
The following example configures a domain `virtual.lan` as one subnet 192.168.38.0/24, a security key named `capsule`, and sets forwarders to Google's public DNS addresses (8.8.8.8 and 8.8.4.4). 192.168.38.2 is the IP address of a DNS server and 192.168.38.1 is the IP address of a {ProjectServer} or a {SmartProxyServer}.
+
[options="nowrap"]
----
# cat /etc/named.conf
include "/etc/rndc.key";

controls  {
    inet 127.0.0.1 port 953 allow { 127.0.0.1; } keys { "capsule"; };
    inet 192.168.38.2 port 953 allow { 192.168.38.1; 192.168.38.2; } keys { "capsule"; };
};

options  {
    directory "/var/named";
    forwarders { 8.8.8.8; 8.8.4.4; };
};

include "/etc/named.rfc1912.zones";

zone "38.168.192.in-addr.arpa" IN {
    type master;
    file "dynamic/38.168.192-rev";
    update-policy {
        grant "capsule" zonesub ANY;
    };
};

zone "virtual.lan" IN {
    type master;
    file "dynamic/virtual.lan";
    update-policy {
        grant "capsule" zonesub ANY;
    };
};
----
+
The `inet` line must be entered as one line in the configuration file.

. Create a key file.
+
[options="nowrap"]
----
# ddns-confgen -k capsule
----
+
This command can take a long time to complete.

. Copy and paste the output from the key section into a separate file called `/etc/rndc.key`.
+
[options="nowrap"]
----
# cat /etc/rndc.key
key "capsule" {
        algorithm hmac-sha256;
        secret "GeBbgGoLedEAAwNQPtPh3zP56MJbkwM84UJDtaUS9mw=";
};
----
+
IMPORTANT: This is the key used to change DNS server configuration. Only the root user should read and write to it.

. Create zone files.
+
[options="nowrap"]
----
# cat /var/named/dynamic/virtual.lan
$ORIGIN .
$TTL 10800      ; 3 hours
virtual.lan             IN SOA  service.virtual.lan. root.virtual.lan. (
                                9          ; serial
                                86400      ; refresh (1 day)
                                3600       ; retry (1 hour)
                                604800     ; expire (1 week)
                                3600       ; minimum (1 hour)
                                )
                        NS      service.virtual.lan.
$ORIGIN virtual.lan.
$TTL 86400      ; 1 day
capsule                 A       192.168.38.1
service                 A       192.168.38.2
----

. Create the reverse zone file.
+
[options="nowrap"]
----
# cat /var/named/dynamic/38.168.192-rev
$ORIGIN .
$TTL 10800      ; 3 hours
38.168.192.in-addr.arpa IN SOA  service.virtual.lan. root.38.168.192.in-addr.arpa. (
                                4          ; serial
                                86400      ; refresh (1 day)
                                3600       ; retry (1 hour)
                                604800     ; expire (1 week)
                                3600       ; minimum (1 hour)
                                )
                        NS      service.virtual.lan.
$ORIGIN 38.168.192.in-addr.arpa.
$TTL 86400      ; 1 day
1                PTR     capsule.virtual.lan.
2                PTR     service.virtual.lan.
----
+
There should be no extra non-ASCII characters.
