[[disabling_dns_dhcp_tftp_for_unmanaged_networks]]

= Disabling DNS, DHCP, and TFTP for Unmanaged Networks

If you want to manage TFTP, DHCP, and DNS services manually, you must prevent Satellite from maintaining these services on the operating system and disable orchestration to avoid DHCP and DNS validation errors. However, Satellite does not remove the back-end services on the operating system.

.Procedure

To prevent Satellite from maintaining DHCP, DNS, and TFTP services on the operating system, and disable orchestration, complete the following steps:

. On Satellite Server, enter the following command:
+
----
# satellite-installer --foreman-proxy-dhcp false \
--foreman-proxy-dns false \
--foreman-proxy-tftp false
----

. In the Satellite web UI, navigate to *Infrastructure* > *Subnets* and select a subnet.

. Click the *Capsules* tab and clear the *DHCP Capsule*, *TFTP Capsule*, and *Reverse DNS Capsule* fields.

. Navigate to *Infrastructure* > *Domains* and select a domain.

. Clear the *DNS Capsule* field.

. Optional: If you use a DHCP service supplied by a third party, configure your DHCP server to pass the following options:
+
[options="nowrap" subs="+quotes"]
----
Option 66: __IP_address_of_Satellite_or_Capsule__
Option 67: /pxelinux.0
----
+
For more information about DHCP options, see https://tools.ietf.org/html/rfc2132[RFC 2132].

[NOTE]
Satellite 6 does not perform orchestration when a Capsule is not set for a given subnet and domain. When enabling or disabling Capsule associations, orchestration commands for existing hosts can fail if the expected records and configuration files are not present. When associating a Capsule to turn orchestration on, make sure the required DHCP and DNS records as well as the TFTP files are in place for the existing Satellite hosts in order to prevent host deletion failures in the future.
