[[downloading_installing_satellite_disconnected]]

= Downloading and Installing from a Disconnected Network

When the intended host for the {ProjectName} Server is in a disconnected environment, it is possible to install the {ProjectServer} by using an ISO image. This method is not recommended for any other situation as ISO images might not contain the latest updates, bug fixes, and functionality.

.Before You Begin

* A copy of the repositories used in the installation are stored in the `/opt/` directory. Ensure you have a minimum of 3 GB of space for this file system and directory.

== Downloading the Binary DVD Images

. Go to https://access.redhat.com/[Red Hat Customer Portal] and log in.

. Click *DOWNLOADS*.

. Select *Red Hat Enterprise Linux*.

. Ensure that you have the correct product and version for your environment.
+
* *Product Variant* is set to *Red Hat Enterprise Linux Server*.
* *Version*  is set to the latest minor version of the product you plan to use as the base operating system.
* *Architecture* is set to the 64 bit version.

. On the *Product Software* tab, download the Binary DVD image for the latest Red Hat Enterprise Linux Server version.

. Click *DOWNLOADS* and select *{ProjectName}*.

. Ensure that you have the correct product and version for your environment.
+
* *Product Variant* is set to *{ProjectName}*.
* *Version*  is set to the latest minor version of the product you plan to use as the base operating system.
* *Architecture* is set to the 64 bit version.

. On the *Product Software* tab, download the Binary DVD image for the latest {ProjectName} version.

. Copy the ISO files to `/var/tmp` on the {Project} base operating system or other accessible storage device.
+
[options="nowrap"]
----
# scp localfile username@hostname:remotefile
----

== Configuring the Base Operating System with Offline Repositories

. Create a directory to serve as the mount point for the ISO file corresponding to the base operating system's version.
+
[options="nowrap"]
----
# mkdir /media/rhel7-server
----


. Mount the ISO image for Red Hat Enterprise Linux to the mount point.
+
[options="nowrap" subs="+quotes"]
----
# mount -o loop _rhel7-Server-DVD_.iso /media/rhel7-server
----
+
. Copy the ISO file's repository data file.
+
[options="nowrap"]
----
# cp /media/rhel7-server/media.repo /etc/yum.repos.d/rhel7-server.repo
----

. Edit the repository data file and add the `baseurl` directive.
+
[options="nowrap"]
----
baseurl=file:///media/rhel7-server/
----
+
. Verify that the repository has been configured.
+
[options="nowrap"]
----
# yum repolist
----

. Create a directory to serve as the mount point for the ISO file of the {ProjectServer}.
+
[options="nowrap"]
----
# mkdir /media/sat6
----

. Mount the ISO image for {ProjectName} Server to the mount point.
+
[options="nowrap" subs="+quotes"]
----
# mount -o loop _sat6-DVD_.iso /media/sat6
----

[[installing_from_the_offline_repositories]]
== Installing from the Offline Repositories

. Ensure the ISO images for Red Hat Enterprise Linux Server and {ProjectName} are mounted:
+
[options="nowrap"]
----
# findmnt -t iso9660
----
+
. Import the Red Hat GPG keys:
+
[options="nowrap"]
----
# rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
----

. Ensure the base operating system is up to date with the Binary DVD image:
+
[options="nowrap"]
----
# yum update
----

. Change to the directory where the {Project} ISO is mounted:
+
[options="nowrap"]
----
# cd /media/sat6/
----

. Run the installation script in the mounted directory:
+
[options="nowrap"]
----
# ./install_packages
----
+
If you have successfully installed the {Project} packages, the following message is displayed: `Install is complete. Please run {foreman-installer} --scenario satellite`.
