[[enabling_satellite_tools_repository]]

= Enabling the {Project} Tools Repository

The {Project} Tools repository provides the `katello-agent` and `puppet` packages for clients registered to {ProjectServer}. Installing the Katello agent is recommended to allow remote updates of clients. The base system of a {SmartProxyServer} is a client of {ProjectServer} and therefore must also have the Katello agent installed.

ifeval::["{mode}" == "disconnected"]
.Prerequisites
* Ensure that you import all content ISO images that you require into {ProjectServer}. For more information, see https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersion}/html/content_management_guide/importing_content_isos_into_disconnected_satellite[Importing Content ISOs into a Disconnected {Project}] in the _Content Management Guide_.
endif::[]

.Procedure
To enable the {Project} Tools repository, complete the following steps:

. In the {Project} web UI, navigate to *Content* > *Red Hat Repositories*.

. Use the Search field to enter the following repository name: *{ProjectName} Tools {ProductVersionRepoTitle} (for RHEL 7 Server) (RPMs)*.

. In the Available Repositories pane, click on *{ProjectName} Tools {ProductVersionRepoTitle} (for RHEL 7 Server) (RPMs)* to expand the repository set.
+
If the *{ProjectName} Tools {ProductVersionRepoTitle}* items are not visible, it may be because they are not included in the Subscription Manifest obtained from the Customer Portal. To correct that, log in to the Customer Portal, add these repositories, download the Subscription Manifest and import it into {Project}.

. For the `x86_64` entry, click the *Enable* icon to enable the repository.

Enable the {Project} Tools repository for every supported major version of Red Hat Enterprise Linux running on your hosts. After enabling a Red Hat repository, a Product for this repository is automatically created.

.For CLI Users

Enable the {Project} Tools repository using the `hammer repository-set enable` command:
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository-set enable --organization _"initial_organization_name"_ \
--product '{RHEL}' \
--basearch='x86_64' \
--name 'Red Hat Satellite Tools {ProductVersionRepoTitle} (for RHEL 7 Server) (RPMs)'
----
