[[performing_initial_configuration_sat_server_answerfile]]
= Performing the Initial Configuration Automatically using an Answer File

You can use answer files to automate installations with customized options. The initial answer file is sparsely populated and after you run the `satellite-installer` script the first time, the answer file is populated with the standard parameter values for installation. You can change the configuration of Satellite Server at any time.

You should use the FQDN instead of the IP address where possible in case of network changes.

*Automatically configuring Satellite Server using an Answer File*

. Copy the default answer file `/etc/foreman-installer/scenarios.d/satellite-answers.yaml` to a location on your local file system.
+
[options="nowrap", subs="+quotes"]
----
# cp /etc/foreman-installer/scenarios.d/satellite-answers.yaml \
/etc/foreman-installer/scenarios.d/__my-answer-file.yaml__
----

. To view all of the configurable options, enter the `satellite-installer --scenario satellite --help` command.

. Open your copy of the answer file, edit the values to suit your environment, and save the file.

. Open the `/etc/foreman-installer/scenarios.d/satellite.yaml` file and edit the answer file entry to point to your custom answer file.
+
[options="nowrap", subs="+quotes"]
----
:answer_file: /etc/foreman-installer/scenarios.d/__my-answer-file.yaml__
----

. Run the `satellite-installer` script.
+
[options="nowrap", subs="+quotes"]
----
# satellite-installer --scenario satellite
----

. If you have been installing in a disconnected environment, unmount the ISO images.
+
[options="nowrap"]
----
# umount /media/sat6
# umount /media/rhel7-server
----
