:_mod-docs-content-type: PROCEDURE

[id="adding-openstack-connection-by-using-web-ui_{context}"]
= Adding a {OpenStack} connection to {ProjectServer} by using {ProjectWebUI}

[role="_abstract"]
You can add {OpenStack} as a compute resource in {Project}.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources*.
. Click *Create Compute Resource*.
. In the *Name* field, enter a name for the new compute resource.
ifdef::satellite[]
. From the *Provider* list, select *RHEL OpenStack Platform*.
endif::[]
ifndef::satellite[]
. From the *Provider* list, select *OpenStack*.
endif::[]
. Optional: In the *Description* field, enter a description for the compute resource.
. In the *URL* field, enter the URL for the OpenStack Authentication keystone service's API at the `tokens` resource, such as `\http://openstack.example.com:5000/v2.0/tokens` or `\http://openstack.example.com:5000/v3/auth/tokens`.
. In the *Username* and *Password* fields, enter the user authentication for {Project} to access the environment.
. Optional: In the *Project (Tenant) name* field, enter the name of your tenant (v2) or project (v3) for {ProjectServer} to manage.
. In the *User domain* field, enter the user domain for v3 authentication.
. In the *Project domain name* field, enter the project domain name for v3 authentication.
. In the *Project domain ID* field, enter the project domain ID for v3 authentication.
. Optional: Select *Allow external network as main network* to use external networks as primary networks for hosts.
. Optional: Click *Test Connection* to verify that {Project} can connect to your compute resource.
. Click the *Locations* and *Organizations* tabs and verify that the location and organization that you want to use are set to your current context.
Add any additional contexts that you want to these tabs.
. Click *Submit* to save the {OpenStack} connection.
