[id="Loading_the_Default_SCAP_Contents_{context}"]
= Loading the default SCAP contents

By loading the default SCAP contents on {ProjectServer}, you ensure that the data streams from the SCAP Security Guide (SSG) are loaded and assigned to all organizations and locations.

SSG is provided by the operating system of {ProjectServer} and installed in `/usr/share/xml/scap/ssg/content/`.
Note that the available data streams depend on the operating system version on which {Project} runs.
ifdef::satellite[]
You can only use this SCAP content to scan hosts that have the same minor RHEL version as your {ProjectServer}.
For more information, see xref:getting-supported-scap-contents-for-rhel_{context}[].
endif::[]

.Prerequisites
* Your user account has a role assigned that has the `create_scap_contents` permission.

.Procedure
* Use the following Hammer command on {ProjectServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer scap-content bulk-upload --type default
----
