[id="puppet_guide_installing_a_puppet_module_from_puppet_forge_{context}"]
= Installing a Puppet Module from Puppet Forge

The Puppet Forge is a repository for pre-built Puppet modules.
Puppet modules flagged as _supported_ are officially supported and tested by Puppet Inc.

This example shows how to add the _ntp module_ to managed hosts.

.Procedure
. In the {ProjectWebUI}, navigate to https://forge.puppet.com/[forge.puppet.com] and search for `ntp`.
One of the first modules is _puppetlabs/ntp_.
. Connect to your {ProjectServer} using SSH and install the Puppet module:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# puppet module install puppetlabs-ntp -i /etc/puppetlabs/code/environment/production/modules
----
+
Use the `-i` parameter to specify the path and Puppet environment, for example `production`.
+
Once the installation is completed, the output looks as follows:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
Notice: Preparing to install into /etc/puppetlabs/code/environment/production/modules ...
Notice: Created target directory /etc/puppetlabs/code/environment/production/modules
Notice: Downloading from https://forgeapi.puppet.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environment/production/modules
|-| puppetlabs-ntp (v8.3.0)
  |-- puppetlabs-stdlib (v4.25.1) [/etc/puppetlabs/code/environments/production/modules]
----

An alternative way to install a Puppet module is to copy a folder containing the Puppet module to the module path as mentioned above.
Ensure to resolve its dependencies manually.
