:_mod-docs-content-type: PROCEDURE

[id="importing-a-subscription-manifest-and-enabling-red-hat-repositories"]
= Importing a subscription manifest and enabling Red Hat repositories

[role="_abstract"]
To distribute Red{nbsp}Hat content, you must first import a subscription manifest that entitles your {ProjectServer} to download content from the Red{nbsp}Hat CDN.
After that, you enable the specific Red{nbsp}Hat repositories you want to synchronize.

.Prerequisites
* You have a Red{nbsp}Hat subscription manifest file exported from the https://console.redhat.com[Red{nbsp}Hat Hybrid Cloud Console].
For more information, see {ContentManagementDocURL}obtaining-a-red-hat-subscription-manifest[Obtaining a Red{nbsp}Hat subscription manifest] in _{ContentManagementDocTitle}_.
* Your {ProjectWebUI} account has administrative privileges.

.Procedure
. In the {ProjectWebUI}, ensure the context is set to the organization you want to use.
. Navigate to *Content* > *Subscriptions*.
To upload the manifest:
.. From the options menu, select *Manage Manifest*.
.. In the *Manage Manifest* window, click *Choose File*.
Upload the manifest file.
.. After the manifest imports successfully, close the *Manage Manifest* window.
. Navigate to *Content* > *Red{nbsp}Hat Repositories*.
To enable repositories:
.. Search for the repository you want to enable.
You can toggle the *Recommended Repositories* option to view repositories that are used in a typical setup.
.. Expand the repository set and click the *Enable* icon next to the base architecture and release version that matches your hosts.

.Verification
* The repository you enabled is listed in the *Enabled Repositories* list.

.Next steps
* Follow xref:synchronizing-your-content[] to synchronize the new repository so that {Project} downloads its metadata and makes it available for distribution.

.Additional resources
ifndef::containerized[]
* xref:importing-a-red-hat-subscription-manifest-by-using-web-ui[]
endif::[]
ifndef::orcharhino[]
* xref:enabling-red-hat-repositories-by-using-web-ui[]
endif::[]
