[id="Configuring_the_Discovery_Service_{context}"]
= Configuring the Discovery service








Ensure that the DHCP range of all subnets that you plan to use for discovery do not intersect with the DHCP lease pool configured for the managed DHCP service.
The DHCP range is set in the {ProjectWebUI}, while the lease pool range is set using the `{foreman-installer}` command.
For example, in a 10.1.0.0/16 network range 10.1.0.0 to 10.1.127.255 could be allocated for leases and 10.1.128.0 to 10.1.255.254 could be allocated for reservations.

ifndef::orcharhino[]
Since network interface names are not expected to always be the same https://access.redhat.com/solutions/5984311[between major versions] of {RHEL},
ifdef::foreman-el,katello[]
or any other operating system being provisioned,
endif::[]
hosts or virtual machines can be created with incorrect network configurations. On Dell servers, the new naming scheme can be disabled via `biosdevname=1` kernel command line option, for other hardware or virtual machines, the new naming scheme can be completely turned off via `net.ifnames=1`.
endif::[]
