[id="integrating-a-local-self-managed-dns-service"]
= Integrating a local, self-managed DNS service

The installer exposes a limited feature set for the {Project} installer-managed DNS service.
For example, you can configure only a single forward DNS zone.
As an alternative to the installer-managed DNS service, you can run a DNS server locally on the {Project} or {SmartProxyServer} to bypass these limitations.

Perform the steps on the {ProjectServer} or {SmartProxyServer} that runs the self-managed DNS service.


.Prerequisites
* You installed and configured a DNS service on the {ProjectServer} or {SmartProxyServer} host.
* The DNS service supports RFC 2136-compatible updates


.Procedure

. Configure {Project} or {SmartProxy} as DNS server:
+
[options="nowrap",subs="+quotes,attributes"]
....
# {foreman-installer} \
--foreman-proxy-dns true \
--foreman-proxy-dns-provider nsupdate \
--foreman-proxy-dns-managed false \
--foreman-proxy-dns-server "127.0.0.1"
....

. For each affected {SmartProxy}, update the configuration of that {SmartProxy} in the {ProjectWebUI}. See xref:associating-the-dns-service-with-a-domain-and-subnet[].

