[id="adding-kubevirt-connection_{context}"]
= Adding {a-KubeVirt} connection to {ProjectServer}

Use this procedure to add {KubeVirt} as a compute resource in {Project}.

.Procedure

. Enter the following `{foreman-installer}` command to enable the {KubeVirt} plugin for {Project}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-plugin-kubevirt
----

. Obtain a token to use for HTTP and HTTPs authentication:

.. Log in to the {Kubernetes} cluster and list the secrets that contain tokens:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ {kubevirt-command} get secrets
----

.. Obtain the token for your secret:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ {kubevirt-command} get secrets _MY_SECRET_ -o jsonpath='{.data.token}' | base64 -d | xargs
----

.. Record the token to use later in this procedure.

. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources*, and click *Create Compute Resource*.
. In the *Name* field, enter a name for the new compute resource.
. From the *Provider* list, select *{KubeVirt}*.
. In the *Description* field, enter a description for the compute resource.
. In the *Hostname* field, enter the FQDN, hostname, or IP address of the {Kubernetes} cluster.
. In the *API Port* field, enter the port number that you want to use for provisioning requests from {Project} to {KubeVirt}.
. In the *Namespace* field, enter the user name of the {Kubernetes} cluster.
. In the *Token* field, enter the bearer token for HTTP and HTTPs authentication.
. Optional: In the *X509 Certification Authorities* field, enter a certificate to enable client certificate authentication for API server calls.
