[id="Creating_Image_Based_Hosts_on_Amazon_EC2_{context}"]
= Creating image-based hosts on Amazon EC2

The Amazon EC2 provisioning process creates hosts from existing images on the Amazon EC2 server.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-hosts-on-amazon-ec2_{context}[].

.Procedure
include::snip_steps-create-a-host-tab-host.adoc[]
. From the *Deploy on* list, select the EC2 connection.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine-based settings.
include::snip_steps-create-a-host-tab-interfaces.adoc[]
. Click the *Operating System* tab and confirm that all fields are populated with values.
. Click the *Virtual Machine* tab and confirm that all fields are populated with values.
ifdef::katello,satellite,orcharhino[]
include::snip_step-parameter-ak.adoc[]
endif::[]
. Click *Submit* to save your changes.

This new host entry triggers the Amazon EC2 server to create the instance, using the pre-existing image as a basis for the new volume.

[id="cli-creating-hosts-on-amazon-ec2_{context}"]
.CLI procedure
* Create the host with the `hammer host create` command and include `--provision-method image` to use image-based provisioning.
+
[options="nowrap" subs="+quotes"]
----
$ hammer host create \
--compute-attributes="flavor_id=m1.small,image_id=TestImage,availability_zones=us-east-1a,security_group_ids=Default,managed_ip=Public" \
--compute-resource "_My_EC2_Compute_Resource_" \
--enabled true \
--hostgroup "_My_Host_Group_" \
--image "_My_Amazon_EC2_Image_" \
--interface "managed=true,primary=true,provision=true,subnet_id=EC2" \
--location "_My_Location_" \
--managed true \
--name "My_Host_Name_" \
--organization "_My_Organization_" \
--provision-method image
----

For more information about additional host creation parameters for this compute resource, enter the `hammer host create --help` command.
