[id="registering-hosts-for-conversion_{context}"]
= Registering Hosts for Conversion

Use this procedure to register CentOS hosts to {Project}.

Activation keys produced by the Ansible role are as follows:

* convert2rhel_centos7 - used for registering centos7 hosts.
* convert2rhel_centos8 - used for registering centos8 hosts.
* convert2rhel_oracle7 - used for registering oracle7 hosts.
* convert2rhel_oracle8 - used for registering oracle8 hosts.
* convert2rhel_rhel7 - used for re-registering a host converted to RHEL 7.
* convert2rhel_rhel8 - used for re-registering a host converted to RHEL 8.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* *>* *All Hosts* and click *Register Host*.
. In the *Host Group* field, select the Host Group you want to use as a template for the conversion.
You can also select one of the following predefined Host groups:

* CentOS7 converting
* CentOS8 converting
* Oracle Linux 7 converting
* Oracle Linux 8 converting

The activation keys for these Host groups are automatically applied.

. Optional, In the *Operating System* field, select the Operating System you are converting from.
. Optional: In the *{SmartProxy}* field, select the required {SmartProxy}.
. Optional: Check the *Insecure* box if the hosts might not trust the {Project} CA.
. Optional: In the *Remote Execution Interface* field, if the host has multiple interfaces and remote execution must use a single one, select the appropriate network interface.
. In the *Activation Key(s)* field, enter the name of the content activation key.
. Click *Generate Command*.

When you run the command on the hosts you want to convert, it is registered in *Hosts* *>* *All Hosts*.
If the host subscription status warns of Unknown subscription status, it can be ignored.
