[id="Extracting_GPG_Public_Key_Fingerprints_from_Release_Files_{context}"]
= Extracting GPG public key fingerprints from Release files

You can use GPG public keys to verify the authenticity of Deb repositories by verifying the signature of the `Release` file.
This example verifies the signature for the `Release` file from Debian 11.

.Procedure
. Download the `Release` and `Release.gpg` files:
+
[options="nowrap" subs="+quotes"]
----
$ wget https://deb.debian.org/debian/dists/bullseye/Release
$ wget https://deb.debian.org/debian/dists/bullseye/Release.gpg
----
. Verify the signature:
+
[options="nowrap" subs="+quotes"]
----
$ gpg --verify Release.gpg Release
----
+
Note the GPG key fingerprint for any missing public GPG keys above the `Can't check signature: No public key` message.
These fingerprints will be used in the next step.
. If you cannot verify the signature, import the missing GPG public keys based on their fingerprint:
+
[options="nowrap" subs="+quotes"]
----
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys A7236886F3CCCAAD148A27F80E98404D386FA1D9
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 4CB50190207B4758A3F73A796ED0E7B82643E131
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys A4285295FC7B1A81600062A9605C66F00D6C9793
----
. Optional: Verify the signature again:
+
[options="nowrap" subs="+quotes"]
----
$ gpg --verify Release.gpg Release
----
. Export the _ASCII-armored_ GPG public keys to a file:
+
[options="nowrap" subs="+quotes"]
----
$ gpg --armor --export A7236886F3CCCAAD148A27F80E98404D386FA1D9 4CB50190207B4758A3F73A796ED0E7B82643E131 A4285295FC7B1A81600062A9605C66F00D6C9793 > debian_11.txt
----
+
Ensure that `gpg` returns a `Good signature` message for each signature.
+
Use this `.txt` file and upload it to {Project} as described below.

Continue to xref:Importing_a_Custom_GPG_Key_{context}[import the custom GPG public key] into {Project}.
