[id="configuring-dhcpd-to-use-with-server_{context}"]
= Configuring dhcpd to use with {ProductName}

ifdef::foreman-deb[]
[NOTE]
====
Note that this procedure describes how to run an external DHCP server on {EL} 8.
====
endif::[]

To configure an external DHCP server running {EL} to use with {ProductName}, you must install the ISC DHCP Service and Berkeley Internet Name Domain (BIND) utilities packages.
You must also share the DHCP configuration and lease files with {ProductName}.
The example in this procedure uses the distributed Network File System (NFS) protocol to share the DHCP configuration and lease files.

[NOTE]
====
If you use dnsmasq as an external DHCP server, enable the `dhcp-no-override` setting.
This is required because {Project} creates configuration files on the TFTP server under the `grub2/` subdirectory.
If the `dhcp-no-override` setting is disabled, hosts fetch the boot loader and its configuration from the root directory, which might cause an error.
====

include::snip_firewalld.adoc[]

.Procedure
. On your {EL} host, install the ISC DHCP Service and Berkeley Internet Name Domain (BIND) utilities packages:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {client-package-install-el8} dhcp-server bind-utils
----
. Generate a security token:
+
[options="nowrap"]
----
# tsig-keygen -a hmac-md5 omapi_key
----
. Edit the `dhcpd` configuration file for all subnets and add the key generated by `tsig-keygen`.
The following is an example:
+
[options="nowrap" subs="+quotes"]
----
# cat /etc/dhcp/dhcpd.conf
default-lease-time 604800;
max-lease-time 2592000;
log-facility local7;

subnet _192.168.38.0_ netmask _255.255.255.0_ {
	range _192.168.38.10 192.168.38.100_;
	option routers _192.168.38.1_;
	option subnet-mask _255.255.255.0_;
	option domain-search "_virtual.lan_";
	option domain-name "_virtual.lan_";
	option domain-name-servers _8.8.8.8_;
}

omapi-port 7911;
key omapi_key {
	algorithm hmac-md5;
	secret "_My_Secret_";
};
omapi-key omapi_key;
----
+
Note that the `option routers` value is the IP address of your {ProjectServer} or {SmartProxyServer} that you want to use with an external DHCP service.
. On {ProjectServer}, define each subnet.
Do not set DHCP {SmartProxy} for the defined Subnet yet.
+
To prevent conflicts, set up the lease and reservation ranges separately.
For example, if the lease range is 192.168.38.10 to 192.168.38.100, in the {ProjectWebUI} define the reservation range as 192.168.38.101 to 192.168.38.250.
. Configure the firewall for external access to the DHCP server:
+
[options="nowrap"]
----
# firewall-cmd --add-service dhcp
----
include::snip_make-firewall-settings-persistent.adoc[]
. On {ProjectServer}, determine the UID and GID of the `foreman` user:
+
[options="nowrap" subs="+quotes"]
----
# id -u foreman
__993__
# id -g foreman
_990_
----
. On the DHCP server, create the `foreman` user and group with the same IDs as determined in a previous step:
+
[options="nowrap" subs="+quotes"]
----
# groupadd -g _990_ foreman
# useradd -u _993_ -g _990_ -s /sbin/nologin foreman
----
. To ensure that the configuration files are accessible, restore the read and execute flags:
+
[options="nowrap"]
----
# chmod o+rx /etc/dhcp/
# chmod o+r /etc/dhcp/dhcpd.conf
# chattr +i /etc/dhcp/ /etc/dhcp/dhcpd.conf
----
. Enable and start the DHCP service:
+
[options="nowrap"]
----
# systemctl enable --now dhcpd
----
. Export the DHCP configuration and lease files using NFS:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {client-package-install-el8} {nfs-server-package}
# systemctl enable --now nfs-server
----
. Create directories for the DHCP configuration and lease files that you want to export using NFS:
+
[options="nowrap"]
----
# mkdir -p /exports/var/lib/dhcpd /exports/etc/dhcp
----
. To create mount points for the created directories, add the following line to the `/etc/fstab` file:
+
[options="nowrap"]
----
/var/lib/dhcpd /exports/var/lib/dhcpd none bind,auto 0 0
/etc/dhcp /exports/etc/dhcp none bind,auto 0 0
----
. Mount the file systems in `/etc/fstab`:
+
[options="nowrap"]
----
# mount -a
----
. Ensure the following lines are present in `/etc/exports`:
+
[options="nowrap" subs="+quotes"]
----
/exports _192.168.38.1_(rw,async,no_root_squash,fsid=0,no_subtree_check)

/exports/etc/dhcp _192.168.38.1_(ro,async,no_root_squash,no_subtree_check,nohide)

/exports/var/lib/dhcpd _192.168.38.1_(ro,async,no_root_squash,no_subtree_check,nohide)
----
+
Note that the IP address that you enter is the {Project} or {SmartProxy} IP address that you want to use with an external DHCP service.
. Reload the NFS server:
+
[options="nowrap"]
----
# exportfs -rva
----
. Configure the firewall for DHCP omapi port 7911:
+
[options="nowrap"]
----
# firewall-cmd --add-port=7911/tcp
----
. Optional: Configure the firewall for external access to NFS.
Clients are configured using NFSv3.
+
[options="nowrap"]
----
# firewall-cmd \
--add-service mountd \
--add-service nfs \
--add-service rpc-bind \
--zone public
----
include::snip_make-firewall-settings-persistent.adoc[]
