[id="Adding_an_Amazon_EC2_Connection_to_Server_{context}"]
= Adding an Amazon EC2 Connection to the {ProjectServer}

Use this procedure to add the Amazon EC2 connection in {ProjectServer}'s compute resources.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-amazon-ec2-connection_{context}[].

.Time Settings and Amazon Web Services
Amazon Web Services uses time settings as part of the authentication process.
Ensure that {ProjectServer}'s time is correctly synchronized.
Ensure that an NTP service, such as `ntpd` or `chronyd`, is running properly on {ProjectServer}.
Failure to provide the correct time to Amazon Web Services can lead to authentication failures.

For more information about synchronizing time in {Project}, see {InstallingProjectDocURL}synchronizing-the-system-clock-with-chronyd_{project-context}[Synchronizing Time] in _{InstallingServerDocTitle}_.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources* and in the Compute Resources window, click *Create Compute Resource*.
. In the *Name* field, enter a name to identify the Amazon EC2 compute resource.
. From the *Provider* list, select *EC2*.
. In the *Description* field, enter information that helps distinguish the resource for future use.
. Optional: From the *HTTP proxy* list, select an HTTP proxy to connect to external API services.
You must add HTTP proxies to {Project} before you can select a proxy from this list.
For more information, see xref:Using_an_HTTP_Proxy_with_Compute_Resources_Amazon_EC2_{context}[].
. In the *Access Key* and *Secret Key* fields, enter the access keys for your Amazon EC2 account.
For more information, see http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html[Managing Access Keys for your AWS Account] on the Amazon documentation website.
. Optional: Click the *Load Regions* button to populate the *Regions* list.
. From the *Region* list, select the Amazon EC2 region or data center to use.
. Click the *Locations* tab and ensure that the location you want to use is selected, or add a different location.
. Click the *Organizations* tab and ensure that the organization you want to use is selected, or add a different organization.
. Click *Submit* to save the Amazon EC2 connection.
. Select the new compute resource and then click the *SSH keys* tab, and click *Download* to save a copy of the SSH keys to use for SSH authentication.
ifndef::orcharhino[]
Until https://bugzilla.redhat.com/show_bug.cgi?id=1793138[BZ1793138] is resolved, you can download a copy of the SSH keys only immediately after creating the Amazon EC2 compute resource.
endif::[]
If you require SSH keys at a later stage, follow the procedure in xref:Connecting_to_an_Amazon_EC2_Instance_Using_SSH_{context}[].

[id="cli-adding-amazon-ec2-connection_{context}"]
.CLI procedure
* Create the connection with the `hammer compute-resource create` command.
Use `--user` and `--password` options to add the access key and secret key respectively.
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create \
--description "Amazon EC2 Public Cloud` \
--locations "_My_Location_" \
--name "_My_EC2_Compute_Resource_" \
--organizations "_My_Organization_" \
--password "_My_Secret_Key_" \
--provider "EC2" \
--region "_My_Region_" \
--user "_My_User_Name_"
----
