[id="uploading-content-larger-than-2-mb"]
= Uploading content larger than 2 MB

The following example demonstrates how to split a large file into chunks, create an upload request, upload the individual files, import them to {Project}, and then delete the upload request.
Note that this example uses sample content, host names, user names, repository ID, and file names.

[id="api-uploading-content-larger-than-2-mb"]
.API procedure
. Assign the package name to the variable `name`:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export name=bpftool-3.10.0-1160.2.1.el7.centos.plus.x86_64.rpm
----
. Assign the checksum of the file to the variable `checksum`:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export checksum=$(sha256sum $name|cut -c 1-65)
----
. Assign the file size to the variable `size`:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export size=$(du -bs $name|cut -f 1)
----
. The following command creates a new upload request and returns the upload ID of the request using `size` and `checksum`.
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header 'Content-Type: application/json' \
--request POST \
--user _My_User_Name_:__My_Password__ \
--data "{\"size\": \"$size\", \"checksum\":\"$checksum\"}" \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads
----
+
where 76, in this case, is an example Repository ID.
+
Example output
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
{"upload_id":"37eb5900-597e-4ac3-9bc5-2250c302fdc4"}
----
. Assign the upload ID to the variable `upload_id`:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export upload_id=37eb5900-597e-4ac3-9bc5-2250c302fdc4
----
. Split the file in 2MB chunks:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ split \
--bytes 2MB \
--numeric-suffixes \
--suffix-length=1 \
bpftool-3.10.0-1160.2.1.el7.centos.plus.x86_64.rpm bpftool
----
+
View the file chunks:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ ls -l bpftool[0-9]
----
+
Example output:
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
-rw-r--r--. 1 root root 2000000 Mar 31 14:15 bpftool0
-rw-r--r--. 1 root root 2000000 Mar 31 14:15 bpftool1
-rw-r--r--. 1 root root 2000000 Mar 31 14:15 bpftool2
-rw-r--r--. 1 root root 2000000 Mar 31 14:15 bpftool3
-rw-r--r--. 1 root root  868648 Mar 31 14:15 bpftool4
----
. Assign the prefix of the split files to the variable path.
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export path=/root/tmp/bpftool
----
. Upload the file chunks.
The offset starts at 0 bytes for the first chunk and increases by 2000000 bytes for each file.
Note the use of the offset parameter and how it relates to the file size.
Note also that the indexes are used after the path variable, for example, $\{path}0, $\{path}1.
+
Example requests:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--user _My_User_Name_:__My_Password__ \
--header Accept:application/json \
--header Content-Type:multipart/form-data \
--request PUT \
--data-urlencode size=$size \
--data-urlencode offset=0 \
--data-urlencode content@$\{path}0 \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id

$ curl \
--user _My_User_Name_:__My_Password__ \
--header Accept:application/json \
--header Content-Type:multipart/form-data \
--request PUT \
--data-urlencode size=$size \
--data-urlencode offset=2000000 \
--data-urlencode content@$\{path}1 \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id

$ curl \
--user _My_User_Name_:__My_Password__ \
--header Accept:application/json \
--header Content-Type:multipart/form-data \
--request PUT \
--data-urlencode size=$size \
--data-urlencode offset=4000000 \
--data-urlencode content@$\{path}2 \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id

$ curl \
--user _My_User_Name_:__My_Password__ \
--header Accept:application/json \
--header Content-Type:multipart/form-data \
--request PUT \
--data-urlencode size=$size \
--data-urlencode offset=6000000
--data-urlencode content@$\{path}3 \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id

$ curl \
--user _My_User_Name_:__My_Password__ \
--header Accept:application/json \
--header Content-Type:multipart/form-data \
--request PUT \
--data-urlencode size=$size \
--data-urlencode offset=8000000 \
--data-urlencode content@$\{path}4 \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id
----
. Import the complete upload to the repository:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header "Content-Type:application/json" \
--request PUT \
--user _My_User_Name_:__My_Password__ \
--data "{\"uploads\":[{\"id\": \"$upload_id\", \"name\": \"$name\", \"checksum\": \"$checksum\" }]}" \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/import_uploads
----
. Delete the upload request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header 'Content-Type: application/json' \
--request DELETE \
--user _My_User_Name_:__My_Password__ \
--data "{}" \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id
----
