[id="synchronizing-a-single-repository_{context}"]
= Synchronizing a Single Repository

In this scenario, you export and import a single repository.

.On the upstream {ProjectServer}
. Ensure that the repository is using the *Immediate* download policy in one of the following ways:
.. For existing repositories using *On Demand*, change their download policy on the repository details page to *Immediate*.
.. For new repositories, ensure that the *Default Red Hat Repository download policy* setting is set to *Immediate* before enabling Red Hat repositories, and that the *Default download policy* is set to *Immediate* for custom repositories.

+
For more information, see xref:Download_Policies_Overview_{context}[].
. Enable the content that you want to synchronize.
For more information, see xref:Enabling_Red_Hat_Repositories_{context}[].
+
If you want to sync custom content, first xref:Creating_a_Custom_Product_{context}[create a custom Product] and xref:Synchronizing_Repositories_{context}[synchronize Product repositories].
. Synchronize the enabled content:
.. On the first export, perform a `complete` repository export so that all the synchronized content is exported.
This generates content archives that you can later import into one or more downstream {ProjectServer}s.
For more information on performing a complete repository export, see xref:Exporting_a_Repository_{context}[].
.. Export all future updates on the upstream {ProjectServer} incrementally.
This generates leaner content archives that contain only a recent set of updates.
For more information on performing an incremental repository export, see xref:Exporting_Repository_Incrementally_{context}[].

.On the downstream {ProjectServer}
. Bring the content exported from the upstream {ProjectServer} over to the hard disk.
. Place it inside a directory under `/var/lib/pulp/imports`.
. Import the content to an organization. See xref:Importing_a_Repository_{context}[].
+
You can then manage content using Content Views or Lifecycle Environments as you require.
