:_mod-docs-content-type: PROCEDURE

[id="configuring-a-baseboard-management-controller-interface"]
= Configuring a baseboard management controller (BMC) interface

[role="_abstract"]
To control the power status of bare-metal hosts from {Project}, you can configure a baseboard management controller (BMC) interface for hosts that support this feature. 

.Prerequisites
* Power management is enabled on {ProjectServer}.
For more information, see {InstallingServerDocURL}enabling-power-management-on-hosts_{project-context}[Enabling power management on hosts] in _{InstallingServerDocTitle}_.
* If you want to use {SmartProxyServer} instead of {ProjectServer}, ensure that power management is enabled on your {SmartProxyServer}.
For more information, see {InstallingSmartProxyDocURL}enabling-power-management-on-hosts_{project-context}[Enabling power management on hosts] in _{InstallingSmartProxyDocTitle}_.
* You know the MAC address, IP address, and other details of the BMC interface on the host, and authentication credentials for that interface.
+
[NOTE]
====
You only need the MAC address for the BMC interface if the BMC interface is managed, so that it can create a DHCP reservation.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Edit your host.
. On the *Interfaces* tab, click *Add Interface*.
. Select *BMC* from the *Type* list.
. Specify the general interface settings:
.. If the BMC is managed, specify a *MAC address*.
.. Specify the *Device Identifier*.
. Specify the configuration options specific to BMC interfaces:
.. *Username* and *Password*: Specify any authentication credentials required by BMC.
.. *Provider*: Specify the BMC provider.
. Click *OK* to save the interface configuration.
. Click *Submit* to apply the changes to the host.
