:_mod-docs-content-type: PROCEDURE

[id="Configuring_Your_{project-context}_to_Run_Ansible_Roles_{context}"]
= Configuring your {Project} to run Ansible roles

[role="_abstract"]
In {Project}, you can import Ansible roles to help with automation of routine tasks.
ifdef::satellite[]
Ansible is enabled by default on {ProjectServer}.
endif::[]
ifndef::satellite[]
To enable Ansible on {ProjectServer}, see xref:Enabling_Ansible_Integration_with_{project-context}_{context}[].
endif::[]

.Procedure
. Add the roles to a directory in an Ansible path on {ProjectServer} and all {SmartProxyServers} from where you want to use the roles.
For more information, see xref:ansible-role-and-collection-paths-in-{project-context}[].
+
If you want to use custom or third party Ansible roles, ensure to configure an external version control system to synchronize roles between {ProjectServer} and {SmartProxyServers}.

. On all {SmartProxyServers} that you want to use to run Ansible roles on hosts, enable the Ansible plugin:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-proxy-plugin-ansible
----
. Distribute SSH keys to enable {SmartProxies} to connect to hosts using SSH.
For more information, see xref:Distributing_SSH_Keys_for_Remote_Execution_{context}[].
{Project} runs Ansible roles the same way it runs remote execution jobs.
. Import the Ansible roles into {Project}.
. Proceed to xref:using-ansible-roles-to-automate-repetitive-tasks-on-hosts[].
