:_mod-docs-content-type: PROCEDURE

[id="Exporting_a_Repository_{context}"]
= Exporting a repository

[role="_abstract"]
You can export a repository from the Library environment to an archive file and recreate the same repository on another {ProjectServer} or organization.

include::snip_content-types-export.adoc[]

The export contains the following data:

* Two JSON files containing repository metadata.
* One or more archive files containing the contents of the repository from the Library environment of the organization.

You need all the files, `tar.gz`, `toc.json` and `metadata.json`, to be able to import.

.Prerequisites
* The export directory has enough free storage space to accommodate the export.
* The `/var/lib/pulp/exports/` directory has enough free storage space equivalent to the size of the repository that you export.
* Download policy is set to *Immediate* for the repository you export.
For more information, see xref:Download_Policies_Overview_{context}[].
* Products that you export are synchronized to the required date.
* The user exporting the content has the _Content Exporter_ role.

.Procedure
. Export a repository:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-export complete repository \
--name="_My_Repository_" \
--product="_My_Product_" \
--organization="_My_Organization_"
----
+
[NOTE]
====
The size of the exported archive depends on the number and size of the packages within the repository.
If you want to split the exported archive into chunks, export your repository using the `--chunk-size-gb` argument to limit the size by an integer value in gigabytes, for example `--chunk-size-gb=_2_`.
====
. Optional: Verify that the exported archive is located in the export directory:
+
[options="nowrap" subs="+quotes"]
----
# ls -lh /var/lib/pulp/exports/_My_Organization_/Export-_My_Repository_/1.0/2022-09-02T03-35-24-00-00/
----
