[id="Creating_a_Custom_File_Type_Repository_{context}"]
= Creating a {customfiletypetitle} Repository

The procedure for creating a {customfiletype} repository is the same as the procedure for creating any {customcontent}, except that when you create the repository, you select the *file* type.
You must create a product and then add a {customrepo}.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-custom-file-type-repository_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content > Products*.
. Select a product that you want to create a repository for.
. On the *Repositories* tab, click *New Repository*.
. In the *Name* field, enter a name for the repository.
{Project} automatically completes the *Label* field based on the name.
. Optional: In the *Description* field, enter a description for the repository.
. From the *Type* list, select `file` as type of repository.
. Optional: In the *Upstream URL* field, enter the URL of the upstream repository to use as a source.
If you do not enter an upstream URL, you can manually upload packages.
For more information, see xref:Uploading_Files_To_a_Custom_File_Type_Repository_{context}[].
. Select the *Verify SSL* checkbox if you want to verify that the upstream repository's SSL certificates are signed by a trusted CA.
. Optional: In the *Upstream Username* field, enter the user name for the upstream repository if required for authentication.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Password* field, enter the corresponding password for the upstream repository.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Authentication Token* field, provide the token of the upstream repository user for authentication.
Leave this field empty if the repository does not require authentication.
. From the *Mirroring Policy* list, select the type of content synchronization {ProjectServer} performs.
For more information, see xref:Mirroring_Policies_Overview_{context}[].
. Optional: In the *HTTP Proxy Policy* field, select or deselect using a HTTP proxy.
By default, it uses the `Global Default` HTTP proxy.
. Optional: You can clear the *Unprotected* checkbox to require a subscription entitlement certificate for accessing this repository.
By default, the repository is published through HTTP.
. Optional: In the *SSL CA Cert* field, select the SSL CA Certificate for the repository.
. Optional: In the *SSL Client Cert* field, select the SSL Client Certificate for the repository.
. Optional: In the *SSL Client Key* field, select the SSL Client Key for the repository.
. Click *Save* to create the repository.

[id="cli-creating-a-custom-file-type-repository_{context}"]
.CLI procedure
. Create a {customproduct}:
+
[options="nowrap" subs="+quotes"]
----
# hammer product create \
--description "_My_Files_" \
--name "_My_File_Product_" \
--organization "_My_Organization_" \
--sync-plan "_My_Sync_Plan_"
----
+
.Optional Parameters for the `hammer product create` Command
[cols="<m1,<a3"]
|====
| *Option* | *Description*

| `--gpg-key-id` _gpg_key_id_         | GPG key numeric identifier
| `--sync-plan-id` _sync_plan_id_     | Sync plan numeric identifier
| `--sync-plan` _sync_plan_name_      | Sync plan name to search by
|====

. Create a `file` type repository:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository create \
--content-type "file" \
--name "_My_Files_" \
--organization "_My_Organization_" \
--product "_My_File_Product_"
----
+
.Optional Parameters for the `hammer repository create` Command
[cols="<m1,<a3"]
|====
| *Option* | *Description*

| `--checksum-type` _sha_version_                 | Repository checksum, currently 'sha1' & 'sha256' are supported
| `--download-policy` _policy_name_       | Download policy for yum repos (either 'immediate' or 'on_demand').
| `--gpg-key-id` _gpg_key_id_                 | GPG key numeric identifier
| `--gpg-key` _gpg_key_name_                  | Key name to search by
| `--mirror-on-sync` _boolean_         | Must this repo be mirrored from the source, and stale RPMs removed, when synced? Set to `true` or `false`, `yes` or `no`, `1` or `0`.
| `--publish-via-http` _boolean_               | Must this also be published using HTTP? Set to `true` or `false`, `yes` or `no`, `1` or `0`.
| `--upstream-password` _repository_password_   | Password for the upstream repository user
| `--upstream-username` _repository_username_   | Upstream repository user, if required for authentication
| `--url` _source_repo_url_                                 | URL of the Source repository
| `--verify-ssl-on-sync` _boolean_   | Must Katello verify that the upstream URL's SSL certificates are signed by a trusted CA? Set to `true` or `false`, `yes` or `no`, `1` or `0`.
|====
