[id="Upgrading_Hosts_to_Next_Major_RHEL_Release_{context}"]
= Upgrading Hosts to Next Major {RHEL} Release

You can use a job template to upgrade your {RHEL} hosts to the next major release.
Below upgrade paths are possible:

* {RHEL} 7 to {RHEL} 8
* {RHEL} 8 to {RHEL} 9

.Prerequisites
* Ensure that your {RHEL} hosts meet the requirements for the upgrade.
ifndef::orcharhino[]
** For {RHEL} 7 to {RHEL} 8 upgrade, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/upgrading_from_rhel_7_to_rhel_8/planning-an-upgrade_upgrading-from-rhel-7-to-rhel-8[Planning an upgrade] in _Upgrading from RHEL 7 to RHEL 8_.
** For {RHEL} 8 to {RHEL} 9 upgrade, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/upgrading_from_rhel_8_to_rhel_9/planning-an-upgrade_upgrading-from-rhel-8-to-rhel-9[Planning an upgrade] in _Upgrading from RHEL 8 to RHEL 9_.
endif::[]
* Prepare your {RHEL} hosts for the upgrade.
ifndef::orcharhino[]
** For {RHEL} 7 to {RHEL} 8 upgrade, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/upgrading_from_rhel_7_to_rhel_8/index#preparing-a-rhel-7-system-for-the-upgrade_upgrading-from-rhel-7-to-rhel-8[Preparing a RHEL 7 system for the upgrade] in _Upgrading from RHEL 7 to RHEL 8_.
** For {RHEL} 8 to {RHEL} 9 upgrade, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/upgrading_from_rhel_8_to_rhel_9/assembly_preparing-for-the-upgrade_upgrading-from-rhel-8-to-rhel-9#preparing-a-rhel-8-system-for-the-upgrade_upgrading-from-rhel-8-to-rhel-9[Preparing a RHEL 8 system for the upgrade] in _Upgrading from RHEL 8 to RHEL 9_.
endif::[]
* Enable remote execution feature on {Project}.
For more information, see xref:Configuring_and_Setting_Up_Remote_Jobs_{context}[].
* Distribute {Project} SSH keys to the hosts that you want to upgrade.
For more information, see xref:Distributing_SSH_Keys_for_Remote_Execution_{context}[].

.Procedure
. On {Project}, enable the Leapp plugin:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-plugin-leapp
----
. In the {ProjectWebUI}, navigate to *Hosts*{nbsp}>{nbsp}*All Hosts*.
. Select the hosts that you want to upgrade to the next major {RHEL} version.
. In the upper right of the Hosts window, from the *Select Action* list, select *Preupgrade check with Leapp*.
. Click *Submit* to start the pre-upgrade check.
. When the check is finished, click the *Leapp preupgrade report* tab to see if Leapp has found any issues on your hosts.
Issues that have the *Inhibitor* flag are considered crucial and are likely to break the upgrade procedure.
Issues that have the *Has Remediation* flag contain remediation that can help you fix the issue.
.. Click an issue that is flagged as *Has Remediation* to expand it.

* If the issue contains a remediation *Command*, you can fix it directly from {Project} using remote execution.
Select the issue.
* If the issue contains only a remediation *Hint*, use the hint to fix the issue on the host manually.

+
+
Repeat this step for other issues.
.. After you selected any issues with remediation commands, click *Fix Selected* and submit the job.
.. After the issues are fixed, click the *Rerun* button, and then click *Submit* to run the pre-upgrade check again to verify that the hosts you are upgrading do not have any issues and are ready to be upgraded.
. If the pre-upgrade check verifies that the hosts do not have any issues, click the *Run Upgrade* button and click *Submit* to start the upgrade.
. Optional: You can also upgrade by selecting the *Schedule a Job* dropdown in the host details page.
