:_mod-docs-content-type: PROCEDURE

[id="deleting-an-organization-by-using-cli"]
= Deleting an organization by using Hammer CLI

[role="_abstract"]
You can delete an organization by using Hammer CLI if you no longer need it for resource management.

[IMPORTANT]
====
ifndef::orcharhino[]
Do not delete *Default Organization* created during installation because the default organization is a placeholder for any unassociated hosts in your {Project} environment.
endif::[]
There must be at least one organization in the environment at any given time.
====

.Procedure
ifdef::foreman-deb,foreman-el[]
. If there are any host groups associated with the organization you are about to delete, remove them by navigating to *Administer* > *Organizations* and clicking the relevant organization.
endif::[]
ifdef::katello,orcharhino,satellite[]
. If there are any lifecycle environments or host groups associated with the organization you are about to delete, remove them by navigating to *Administer* > *Organizations* and clicking the relevant organization.
endif::[]
. View all organizations:
+
----
$ hammer organization list
----
+
From the output, note the ID of the organization that you want to delete.
. Delete an organization:
+
[subs="+quotes"]
----
$ hammer organization delete --id _My_Organization_ID_
----
