[id="Examining_the_Exports_{context}"]
= Examining the Exports

When importing content to several {ProjectServer}s, the --destination-server option is especially useful for keeping track of which content was exported and to where.

You can use this flag to let the exporting {ProjectServer} keep track of content in specific servers.
The `--destination-server` option functions to indicate the destination server that your content is imported to.
The following example uses `--destination-server=mirror1` to export content to `mirror1`.
The archive is created on the exporting {ProjectServer}.
However, a record of each export is also maintained.
This can be very useful when incrementally exporting.

[options="nowrap" subs="+quotes"]
----
# hammer content-export complete version \
--content-view=view --version=1.0 \
--organization=export-21527 \
--destination-server=mirror1
----

[[Incremental-Export]]
.Incremental Export

Exporting complete versions can be a very expensive operation on storage space and resources.
Content View versions that have multiple {RHEL} trees can occupy several gigabytes of the space on {ProjectServer}.

You can use the *Incremental Export* functionality to help reduce demands on your infrastructure.
*Incremental Export* exports only content that changes from the previously exported version.
Generally, incremental changes are smaller than full exports.
ln the following example, since version `1.0` has already been exported and the command targets version 2.0 for export.
To use incremental export, complete the following steps.

----
# hammer content-export incremental version \
 --content-view=view \
 --version=2.0 \
 --organization=export-21527

# ls -lh /var/lib/pulp/exports/export-21527/view/2.0/2021-02-25T21-45-34-00-00/
----
