:_mod-docs-content-type: PROCEDURE

[id="customizing-xccdf-profiles-with-tailoring-files"]
= Customizing XCCDF profiles with tailoring files

[role="_abstract"]
You can use tailoring files to customize existing XCCDF profiles without editing the original SCAP content.
After uploading a tailoring file, you can apply it in a compliance policy to customize an XCCDF profile.

A single tailoring file can contain customizations of multiple XCCDF profiles.

You can create a tailoring file by using the https://www.open-scap.org/tools/scap-workbench/[SCAP Workbench] tool.
For more information on using the SCAP Workbench tool, see https://www.open-scap.org/resources/documentation/customizing-scap-security-guide-for-your-use-case/[Customizing SCAP Security Guide for your use case].

Then you can assign a tailoring file to a compliance policy to customize an XCCDF profile in the policy.

.Prerequisites
* Your user account has a role assigned that has the `create_tailoring_files` permission.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Compliance* > *Tailoring Files*.
. Click *New Tailoring File*.
. Enter a name in the *Name* text box.
. Click *Choose File*, navigate to the location containing the tailoring file and select *Open*.
. Click *Submit* to upload the chosen tailoring file.
