[id="creating-compute-profiles_{context}"]
= Creating compute profiles

You can use compute profiles to predefine virtual machine hardware details such as CPUs, memory, and storage.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-compute-profiles_{context}[].

A default installation of {ProjectName} contains three predefined profiles:

* `1-Small`
* `2-Medium`
* `3-Large`

You can apply compute profiles to all supported compute resources:

* xref:supported-cloud-providers_{context}[]
* xref:supported-virtualization-infrastructures_{context}[]

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Profiles* and click *Create Compute Profile*.
. In the *Name* field, enter a name for the profile.
. Click *Submit*.
A new window opens with the name of the compute profile.
. In the new window, click the name of each compute resource and edit the attributes you want to set for this compute profile.

[id="cli-creating-compute-profiles_{context}"]
.CLI procedure
. Create Compute Profile:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile create --name "_My_Compute_Profile_"
----
+
. Set atributes for the Compute Profile using:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile values create \
--compute-atributes "flavor=m1.small,cpus=2,memory=4GB,cpu_mode=default \
--compute-resource "_My_Compute_Resource_" \
--compute-profile "_My_Compute_Profile_" \
--volume size=40GB
----
+
. Optional: To update the attributes of a Compute Profile, specify the atributes you want to change. To change the number of CPUs, memory, volume size use the following command:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile values update \ 
--compute-resource "_My_Compute_Resource_" \
--compute-profile "_My_Compute_Profile_" \
--attributes "cpus=2,memory=4GB" \
--interface "type=network,bridge=br1,index=1" \
--volume "size=40GB,index=2"
----
+
. To change the name of the compute profile you can use `--new-name` atribute:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile update \
--name "_My_Compute_Profile_" \
--new-name "_My_New_Compute_Profile_"
----
+
. Optional: Delete a Compute Profile:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile delete \ 
--name "_My_Compute_Profile_" \
--id "_My_Compute_Profile_Id_"
----
+
. Optional: View all Compute Profiles:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile list
----
+
. Optional: View details of a Compute Profile:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile show --name "_My_Compute_Profile_"
----
