:_mod-docs-content-type: PROCEDURE

[id="Impersonating_a_Different_User_Account_{context}"]
= Impersonating a different user account

[role="_abstract"]
As an administrator, you can impersonate another user by logging on to the {ProjectWebUI} as that user.
Impersonating another user is useful for testing and troubleshooting purposes because you can access exactly what the impersonated user can access in the system, including the same menus.

Audits are created to record the actions that the administrator performs while impersonating another user.
However, all actions that an administrator performs while impersonating another user are recorded as having been performed by the impersonated user.

.Prerequisites
* You are logged on to the {ProjectWebUI} as a user with administrator privileges for {Project}.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Users*.
. To the right of the user that you want to impersonate, from the list in the *Actions* column, select *Impersonate*.
+
When you want to stop the impersonation session, in the upper right of the main menu, click the impersonation icon.
