:_mod-docs-content-type: PROCEDURE

[id="adding-a-subnet-to-server-by-using-web-ui{context}"]
= Adding a subnet to {ProjectServer} by using {ProjectWebUI}

[role="_abstract"]
You must add information for each of your subnets to {ProjectServer} because {Project} configures interfaces for new hosts.
To configure interfaces, {ProjectServer} must have all the information about the network that connects these interfaces.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets*, and in the Subnets window, click *Create Subnet*.
. In the *Name* field, enter a name for the subnet.
. In the *Description* field, enter a description for the subnet.
. In the *Network address* field, enter the network address for the subnet.
. In the *Network prefix* field, enter the network prefix for the subnet.
. In the *Network mask* field, enter the network mask for the subnet.
. In the *Gateway address* field, enter the external gateway for the subnet.
. In the *Primary DNS server* field, enter a primary DNS for the subnet.
. In the *Secondary DNS server*, enter a secondary DNS for the subnet.
. From the *IPAM* list, select the method that you want to use for IP address management (IPAM).
For more information about IPAM, see xref:Network_Resources_{context}[].
+
. Enter the information for the IPAM method that you select.
ifdef::satellite,orcharhino[]
Click the *Remote Execution* tab and select the {SmartProxy} that controls the remote execution.
endif::[]
ifndef::satellite,orcharhino[]
. If you use the remote execution plugin, click the *Remote Execution* tab and select the {SmartProxy} that controls the remote execution.
endif::[]
. Click the *Domains* tab and select the domains that apply to this subnet.
. Click the *{SmartProxies}* tab and select the {SmartProxy} that applies to each service in the subnet, including DHCP, TFTP, and reverse DNS services.
. Click the *Parameters* tab and configure any subnet level parameters to apply to hosts attached to this subnet.
For example, user defined Boolean or string parameters to use in templates.
. Click the *Locations* tab and select the locations that use this {SmartProxy}.
. Click the *Organizations* tab and select the organizations that use this {SmartProxy}.
. Click *Submit* to save the subnet information.
