:_mod-docs-content-type: PROCEDURE

[id="changing-the-default-download-policy-by-using-cli"]
= Changing the default download policy by using Hammer CLI

[role="_abstract"]
You can set the default download policy that {Project} applies to repositories that you create in all organizations.

ifdef::satellite[]
Depending on whether it is a Red Hat or non-Red Hat {customrepo}, {Project} uses separate settings.
endif::[]
ifndef::satellite[]
Depending on whether it is a Red Hat, SUSE, or {customrepo}, {Project} uses separate settings.
endif::[]
Changing the default value does not change the setting in existing repositories, but only the default setting for new repositories.

.Procedure
* To change the default download policy for Red Hat repositories to one of `immediate` or `on_demand`, enter the following command:
+
[subs="+quotes"]
----
$ hammer settings set \
--name default_redhat_download_policy \
--value _immediate_
----
ifndef::satellite[]
* To change the default download policy for a {customrepo} to one of `immediate` or `on_demand`, enter the following command:
endif::[]
ifdef::satellite[]
* To change the default download policy for a non-Red Hat {customrepo} to one of `immediate` or `on_demand`, enter the following command:
endif::[]
+
[subs="+quotes"]
----
$ hammer settings set \
--name default_download_policy \
--value _immediate_
----
