:_mod-docs-content-type: PROCEDURE

[id="Creating_a_Lifecycle_Environment_Path_{context}"]
= Creating a lifecycle environment path

[role="_abstract"]
To create an application lifecycle for developing and releasing software, use the _Library_ environment as the initial environment to create environment paths.
Then optionally add additional environments to the environment paths.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Lifecycle Environments*.
. Click *New Environment Path* to start a new application lifecycle.
. In the *Name* field, enter a name for your environment.
. In the *Description* field, enter a description for your environment.
. Click *Save*.
. Optional: To add an environment to the environment path, click *Add New Environment*, complete the *Name* and *Description* fields, and select the prior environment from the *Prior Environment* list.

.CLI procedure
. Create a lifecycle environment path by tying your first environment to Library:
+
[options="nowrap" subs="+quotes"]
----
$ hammer lifecycle-environment create \
--name "_My First Lifecycle Environment_" \
--description "_Environment Path Description_" \
--prior "Library" \
--organization "_My_Organization_"
----
. Optional: Add another environment to the environment path by tying it to the prior environment:
+
[options="nowrap" subs="+quotes"]
----
$ hammer lifecycle-environment create \
--name "_My Second Lifecycle Environment_" \
--description "_Environment Description_" \
--prior "_My First Lifecycle Environment_" \
--organization "_My_Organization_"
----
. View the chain of the lifecycle environment path:
+
[options="nowrap" subs="+quotes"]
----
$ hammer lifecycle-environment paths --organization "_My_Organization_"
----
