[id="adding-kvm-images_{context}"]
= Adding KVM Images to {ProjectServer}

To create hosts using image-based provisioning, you must add information about the image to your {ProjectServer}, such as access details and the image location.

.Supported Storage Types
Note that you can manage only directory pool storage types through {ProjectX}.

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*, and in the Compute Resources window, click the name of your KVM connection.
. Click the *Image* tab, and then click *Create Image*.
. In the *Name* field, enter a name for the image.
. From the *Operatingsystem* list, select the image's base operating system.
. From the *Architecture* list, select the operating system architecture.
. In the *Username* field, enter the SSH user name for image access. This is normally the `root` user.
. In the *Password* field, enter the SSH password for image access.
. In the *Image path* field, enter the full path that points to the image on the KVM server. For example:
+
[options="nowrap" subs="+quotes"]
----
 /var/lib/libvirt/images/TestImage.qcow2
----
+
. Click *Submit* to save the image details.

.For CLI Users

* Create the image with the `hammer compute-resource image create` command. Use the `--uuid` field to store the full path of the image location on the KVM server.
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-resource image create --name "Test KVM Image" \
--operatingsystem "RedHat _version_" --architecture "x86_64" --username root \
--user-data false --uuid "/var/lib/libvirt/images/TestImage.qcow2" \
--compute-resource "_My_KVM_Server_"
----
