[id="configuring-repositories-proxy_{context}"]

= Configuring Repositories

ifdef::foreman-el,katello[]
This procedure is only for Katello plug-in and {RHEL}-based operating system users.
endif::[]

Use this procedure to enable the repositories that are required to install {ProductName}.
Select the option that corresponds with operating system and version you want to install on:

ifdef::foreman-el,katello,satellite[]
* xref:#repositories-rhel-8[{RHEL} 8]
* xref:#repositories-rhel-7[{RHEL} 7]
endif::[]

ifdef::foreman-el,katello,satellite[]
== [[repositories-rhel-8]]{RHEL} 8

:distribution-major-version: 8
:package-manager: dnf

. Disable all repositories:
+
[options="nowrap"]
----
# subscription-manager repos --disable "*"
----
+
endif::[]

. Enable the following repositories:
ifdef::satellite[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL8BaseOS} \
--enable={RepoRHEL8AppStream} \
--enable={RepoRHEL8ServerSatelliteCapsuleProductVersion} \
--enable={RepoRHEL8ServerSatelliteMaintenanceProductVersion}
----

. Enable the module:
+
[options="nowrap"]
----
# dnf module enable satellite-capsule:el8
----
+
endif::[]

ifdef::foreman-el,katello,satellite[]

== [[repositories-rhel-7]]{RHEL} 7

:distribution-major-version: 7
:package-manager: yum

. Disable all repositories:
+
[options="nowrap"]
----
# subscription-manager repos --disable "*"
----
+
. Enable the following repositories:
ifdef::foreman-el,katello[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL7Server} \
--enable {RepoRHEL7ServerOptional} \
--enable {RepoRHEL7ServerSoftwareCollections}
----
+
endif::[]
ifdef::satellite[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL7Server} \
--enable={RepoRHEL7ServerSatelliteCapsuleProductVersion} \
--enable={RepoRHEL7ServerSatelliteMaintenanceProductVersion} \
--enable={project-client-RHEL7-url} \
--enable={RepoRHEL7ServerSoftwareCollections} \
--enable={RepoRHEL7ServerAnsible}
----
+
endif::[]

NOTE: If you are installing {ProductName} as a virtual machine hosted on {oVirt}, you must also enable the *Red{nbsp}Hat Common* repository, and install {oVirt} guest agents and drivers.
For more information, see https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/virtual_machine_management_guide/installing_guest_agents_and_drivers_linux#Installing_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux[Installing the Guest Agents and Drivers on {RHEL}] in the _Virtual Machine Management Guide_.
+
. Clear any metadata:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-clean} all
----
+
. Optional: Verify that the required repositories are enabled:
+
[options="nowrap"]
----
# yum repolist enabled
----

ifdef::foreman-el,katello[]
+
. Install the `foreman-release.rpm` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum localinstall https://yum.theforeman.org/releases/{ProjectVersion}/el7/x86_64/foreman-release.rpm
----
+
. Install the `katello-repos-latest.rpm` package
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum localinstall https://yum.theforeman.org/katello/{KatelloVersion}/katello/el7/x86_64/katello-repos-latest.rpm
----
+
. Install the `puppet6-release-el-7.noarch.rpm` package:
+
----
# yum localinstall https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
----
+
. Install the `epel-release-latest-7.noarch.rpm` package:
+
----
# yum localinstall https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
----
endif::[]

ifdef::foreman-el,katello[]

.CentOS Users
If you use a CentOS operating system, complete the following steps:

. Install the `foreman-release.rpm` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum localinstall https://yum.theforeman.org/releases/{ProjectVersion}/el7/x86_64/foreman-release.rpm
----
+
. Install the `katello-repos-latest.rpm` package
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum localinstall https://yum.theforeman.org/katello/{KatelloVersion}/katello/el7/x86_64/katello-repos-latest.rpm
----
+
. Install the `puppet6-release-el-7.noarch.rpm` package:
+
----
# yum localinstall https://yum.puppet.com/puppet6-release-el-7.noarch.rpm
----
+
. Install the `epel-release` package:
+
----
# yum install epel-release
----
+
. Install the `centos-release-scl-rh` package:
+
----
# yum install centos-release-scl-rh
----
endif::[]
