[id="Downloading_Files_to_a_Host_from_a_Python_Type_Repository_{context}"]
= Downloading files to a host from a Python type repository

You can download files to a client over HTTPS using `curl -O`, and optionally over HTTP if the *Unprotected* option for repositories is selected.

.Prerequisites
* You have a Python type repository.
* You know the name of the Python package you want to download to clients from the Python type repository.
* To download the Python packages over HTTPS to your hosts, you require:
** The `katello-server-ca.crt`.
For more information, see {AdministeringDocURL}Importing_the_Katello_Root_CA_Certificate_admin[Importing the Katello Root CA Certificate] in _{AdministeringDocTitle}_.
** An Organization Debug Certificate.
For more information, see {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate] in _{ManagingOrganizationsLocationsDocTitle}_.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select a {customproduct} by name.
. Select a Python type repository by name.
. Optional: Select the *Unprotected* checkbox to access the repository published through HTTP.
. Copy the *Published At* URL.
include::snip_step-downloading-file-from-server.adoc[]

.CLI procedure
. List all `file` type repositories:
+
[options="nowrap" subs="+quotes"]
----
$ hammer repository list --content-type python
----
. View the repository information:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
$ hammer repository info \
--name "_My_Python_Repository_" \
--organization-id _My_Organization_ID_ \
--product "__My_{customproductFirstCap}__"
----
include::snip_step-downloading-file-from-server.adoc[]
