:_mod-docs-content-type: PROCEDURE

[id="configuring-the-active-directory-authentication-source-on-projectserver_{context}"]
= Configuring the Active Directory authentication source on {ProjectServer}

[role="_abstract"]
Enable Active Directory (AD) users to access {Project} by configuring the corresponding authentication provider on your {ProjectServer}.

.Prerequisites
* The base system of your {ProjectServer} must be joined to an Active Directory (AD) domain.
To enable AD users to sign in with Kerberos single sign-on, use the System Security Services Daemon (SSSD) and Samba services to join the base system to the AD domain:
+
Install the following packages on {ProjectServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {project-package-install} adcli krb5-workstation oddjob-mkhomedir oddjob realmd samba-winbind-clients samba-winbind samba-common-tools samba-winbind-krb5-locator sssd
----
+
Specify the required software when joining the AD domain:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# realm join _AD.EXAMPLE.COM_ --membership-software=samba --client-software=sssd
----
ifndef::orcharhino[]
+
For more information on direct AD integration, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html-single/integrating_rhel_systems_directly_with_windows_active_directory/index#connecting-rhel-systems-directly-to-ad-using-samba-winbind_integrating-rhel-systems-directly-with-active-directory[Connecting RHEL systems directly to AD using Samba Winbind].
endif::[]

.Procedure
. Define AD realm configuration in a location where {Project} expects it:
.. Create a directory named `/etc/ipa/`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir /etc/ipa/
----
+
.. Create the `/etc/ipa/default.conf` file with the following contents to configure the Kerberos realm for the AD domain:
+
[source, ini, options="nowrap", subs="+quotes,verbatim,attributes"]
----
[global]
realm = _AD.EXAMPLE.COM_
----
. Configure the Apache keytab for Kerberos connections:
.. Update the `/etc/samba/smb.conf` file with the following settings to configure how Samba interacts with AD:
+
[source, ini, options="nowrap", subs="+quotes,verbatim,attributes"]
----
[global]
workgroup = _AD.EXAMPLE_
realm = _AD.EXAMPLE.COM_
kerberos method = system keytab
security = ads
----
+
.. Add the Kerberos service principal to the keytab file at `/etc/httpd/conf/http.keytab`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# KRB5_KTNAME=FILE:/etc/httpd/conf/http.keytab net ads keytab create HTTP -U Administrator -s /etc/samba/smb.conf
----
+
[NOTE]
====
The `net ads keytab create` command was introduced in Samba version 4.21.1.
If your system uses an earlier version of Samba, use the `net ads keytab add` command.
====
. Configure the System Security Services Daemon (SSSD) on your {ProjectServer}:
.. Configure the AD access control provider to evaluate and enforce Group Policy Object (GPO) access control rules for the `foreman` PAM service.
In the `[domain/_ad.example.com_]` section of your `/etc/sssd/sssd.conf` file, set the `ad_gpo_access_control` and `ad_gpo_map_service` options as follows:
+
[source, ini, options="nowrap", subs="+quotes,verbatim,attributes"]
----
[domain/_ad.example.com_]
ad_gpo_access_control = enforcing
ad_gpo_map_service = +foreman
----
ifndef::orcharhino[]
+
For more information on GPOs, see https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/integrating_rhel_systems_directly_with_windows_active_directory/managing-direct-connections-to-ad_integrating-rhel-systems-directly-with-active-directory#how-sssd-interprets-gpo-access-control-rules_applying-group-policy-object-access-control-in-rhel[How SSSD interprets GPO access control rules] in _Integrating RHEL systems directly with Windows Active Directory (RHEL{nbsp}9)_.
endif::[]
.. If your {ProjectServer} runs in an IPv6-only network and also runs on RHEL{nbsp}9.6 and earlier or RHEL{nbsp}10.0, set the `lookup_family_order` option in the `[domain/_ad.example.com_]` section of the `/etc/sssd/sssd.conf` file:
+
[source, ini, options="nowrap", subs="+quotes,verbatim,attributes"]
----
[domain/_ad.example.com_]
lookup_family_order = ipv6_only
----
+
If the DNS name of the AD server can be translated to both an IPv4 and IPv6 address but the IPv4 address is not accessible, SSSD requires `lookup_family_order` to translate the DNS name correctly.
Without the option, AD users are unable to use `kinit` to authenticate to {Project}.
// Related SSSD issue: https://github.com/SSSD/sssd/issues/3057
.. Restart SSSD:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart sssd
----
. Enable the authentication source:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
ifdef::foremanctl[]
# foremanctl deploy --external-authentication ipa
endif::[]
ifndef::foremanctl[]
# {foreman-installer} --foreman-ipa-authentication true
endif::[]
----

.Verification
* To verify that AD users can log in to {Project} by entering their credentials, log in to {ProjectwebUI} at \https://{foreman-example-com}.
Enter the user name in the user principal name (UPN) format, for example: `_ad_user_@_AD.EXAMPLE.COM_`.
* To verify that AD users can authenticate by using Kerberos single sign-on:
** Obtain a Kerberos ticket-granting ticket (TGT) on behalf of an AD user:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ kinit _ad_user_@_AD.EXAMPLE.COM_
----
** Verify user authentication by using your TGT:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ curl -k -u : --negotiate https://_{foreman-example-com}_/users/extlogin
----
+
If external authentication is configured correctly, the `curl` command redirects you to `\https://{foreman-example-com}/hosts`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
<html><body>You are being <a href="_{foreman-example-com}_/hosts">redirected</a>.</body></html>
----


.Troubleshooting
* Connecting to the AD LDAP can sometimes fail with an error such as the following appearing in the logs:
+
[source, none, options="nowrap", subs="+quotes,verbatim,attributes"]
----
Authentication failed with status code: {
  "error": { "message": "ERF77-7629 [Foreman::LdapException]: Error while connecting to 'server.com' LDAP server at 'ldap.example.com' during authentication ([Net::LDAP::Error]: Connection reset by peer - SSL_connect)" } }
----
+
If you see this error, verify which cipher is used for the connection:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# openssl s_client -connect _ldap.example.com_:636
----
+
If the `TLS_DHE_RSA_WITH_AES_256_GCM_SHA384` cipher is used, disable it on either the {ProjectServer} side or on the AD side.
The `TLS_DHE_RSA_WITH_AES_256_GCM_SHA384` cipher is known to cause incompatibilities.
+
ifdef::satellite[]
For more information, see the Red{nbsp}Hat Knowledgebase solution link:https://access.redhat.com/solutions/4870221[API calls to Red Hat Satellite 6 fail intermittently on LDAP authentication].
endif::[]
ifdef::foreman-el,katello[]
For information on configuring system-wide cryptographic policies, see link:https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening[Using system-wide cryptographic policies] in _{RHEL}{nbsp}9 Security hardening_.
endif::[]

.Additional resources
ifndef::orcharhino[]
* https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SSO[Configuring Firefox to use Kerberos for single sign-on in _{RHEL}{nbsp}9 Configuring authentication and authorization in RHEL_]
endif::[]
* xref:resetting-external-authentication-configuration-for-kerberos-sso[]
