[id="preparing-for-disaster-recovery-with-two-active-project-servers"]
= Preparing for disaster recovery with two active {ProjectServer}s

Create a second {ProjectServer} by restoring a backup of your first {ProjectServer}.
Configure both servers to operate independently in their respective data centers, but ensure that their content, such as repositories or host configuration, does not drift apart over time.

.Procedure
. Back up your {ProjectServer}.
For more information, see xref:backing-up-{project-context}-server-and-{smart-proxy-context}_admin[].
. Restore the backup on a system that will serve as your other {ProjectServer}.
For more information, see xref:restoring-{project-context}-server-or-{smart-proxy-context}-from-a-backup_admin[].
+
[NOTE]
====
Each server must have a distinct hostname and IP address.
This enables you to re-register hosts if one of the servers fails.
====
. Ensure that content on your servers remains consistent:
** If you want both servers to act as sources for synchronization and content view creation, follow these guidelines to prevent content drift:
*** Regularly synchronize repositories on both servers.
For more information, see {ContentManagementDocURL}[Synchronizing repositories] in _{ContentManagementDocTitle}_.
*** Ensure that content views on both servers match.
// *** What else?
** If you want only one server to manage synchronization and content views and let the other server synchronize its content from the first server, configure Inter-Server Synchronization (ISS).
For more information, see {ContentManagementDocURL}Synchronizing_Content_Between_Servers_content-management[Synchronizing content between {ProjectServer}s] in _{ContentManagementDocTitle}_.
. Register hosts to your servers so that each server manages hosts in its respective data center.
. Automate running the `{foreman-maintain} health check` command on both servers.
The health check verifies whether the servers remain fully operational.


.Verification
Perform this test in an isolated staging environment:

. Mimic a full outage on one of your servers.
To verify that the server is inaccessible, you can turn the machine off, halt the virtual machine (VM) if your server runs on a VM, or isolate the machine by using a firewall.
. Verify that your `{foreman-maintain} health check` automation reported an error.
. Re-register all hosts from the inaccessible server to the other server.
. Verify that hosts have been properly re-registered.
// How?
. Perform these verification checks regularly.

.Additional resources
* Ansible playbooks can help you automate failover, re-registration, and synchronization.
For more information, see {AdministeringDocURL}managing-{project-context}-with-ansible[Managing {Project} with Ansible] in _{AdministeringDocTitle}_.
