:_mod-docs-content-type: PROCEDURE

[id="adding-errata-to-an-incremental-content-view-by-using-web-ui"]
= Adding errata to an incremental content view by using {ProjectWebUI}

[role="_abstract"]
If errata are available but not installable, you can create an incremental content view version in {ProjectWebUI} to add the errata to your content hosts.
For example, if the content view is version 1.0, it becomes content view version 1.1, and when you publish, it becomes content view version 2.0.

[IMPORTANT]
====
If your content view version is old, you might encounter incompatibilities when incrementally adding enhancement errata.
This is because enhancements are typically designed for the most current software in a repository.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Content Types* > *Errata*.
. From the *Errata* list, click the name of the errata that you want to apply.
. Select the content hosts that you want to apply the errata to, and click *Apply to Hosts*.
This creates the incremental update to the content view.
. If you want to apply the errata to the content host, select the *Apply Errata to Content Hosts immediately after publishing* checkbox.
. Click *Confirm* to apply the errata.
