[id="Assigning_a_Host_to_a_Specific_Location_{context}"]
= Assigning a Host to a Specific Location

Use this procedure to assign a host to a specific location.
For general information about locations and how to configure them, see {ContentManagementDocURL}Creating_a_Location_content-management[Creating a Location] in _{ContentManagementDocTitle}_.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All hosts*.
. Select the checkbox of the host you want to change.
. From the *Select Action* list, select *Assign Location*.
A new option window opens.
. Navigate to the *Select Location* list and choose the location that you want for your host.
Select the checkbox *Fix Location on Mismatch*.
+
[NOTE]
====
A mismatch happens if there is a resource associated with a host, such as a domain or subnet, and at the same time not associated with the location you want to assign the host to.
The option *Fix Location on Mismatch* will add such a resource to the location, and is therefore the recommended choice.
The option *Fail on Mismatch* will always result in an error message.
For example, reassigning a host from one location to another will fail, even if there is no actual mismatch in settings.
====
. Click *Submit*.
