[id="Creating_a_Host_Group_{context}"]
= Creating a Host Group

If you create a high volume of hosts, many of the hosts can have common settings and attributes.
Adding these settings and attributes for every new host is time consuming.
If you use host groups, you can apply common attributes to hosts that you create.

A host group functions as a template for common host settings, containing many of the same details that you provide to hosts.
When you create a host with a host group, the host inherits the defined settings from the host group.
You can then provide additional details to individualize the host.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-host-group_{context}[].

.Host Group Hierarchy
You can create a hierarchy of host groups.
Aim to have one base level host group that represents all hosts in your organization and provide general settings, and then nested groups to provide specific settings.
For example, you can have a base level host group that defines the operating system, and two nested host groups that inherit the base level host group:

* *Hostgroup:* `Base` ({RHEL}  7.6)
** *Hostgroup:* `Webserver` (applies the `httpd` Puppet class)
*** *Host:* `webserver1.example.com` (web server)
*** *Host:* `webserver2.example.com` (web server)
** *Hostgroup:* `Storage` (applies the `nfs` Puppet class)
*** *Host:* `storage1.example.com` (storage server)
*** *Host:* `storage2.example.com` (storage server)
** *Host:* `custom.example.com` (custom host)

In this example, all hosts use {RHEL} 7.6 as their operating system because of their inheritance of the `Base` host group.
The two web server hosts inherit the settings from the `Webserver` host group, which includes the `httpd` Puppet class and the settings from the `Base` host group.
The two storage servers inherit the settings from the `Storage` host group, which includes the `nfs` Puppet class and the settings from the `Base` host group.
The custom host only inherits the settings from the `Base` host group.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups* and click *Create Host Group*.
. If you have an existing host group that you want to inherit attributes from, you can select a host group from the *Parent* list.
If you do not, leave this field blank.
. Enter a *Name* for the new host group.
. Enter any further information that you want future hosts to inherit.
. Click the *Ansible Roles* tab, and from the *Ansible Roles* list, select one or more roles that you want to add to the host.
Use the *arrow* icon to manage the roles that you add or remove.
. Click the additional tabs and add any details that you want to attribute to the host group.
+
[NOTE]
====
Puppet fails to retrieve the Puppet CA certificate while registering a host with a host group associated with a Puppet environment created inside a `Production` environment.

To create a suitable Puppet environment to be associated with a host group, manually create a directory and change the owner:

[options="nowrap", subs="+quotes,attributes"]
----
# mkdir /etc/puppetlabs/code/environments/_example_environment_
# chown apache /etc/puppetlabs/code/environments/_example_environment_
----
====
. Click *Submit* to save the host group.

[id="cli-creating-a-host-group_{context}"]
.CLI procedure
* Create the host group with the `hammer hostgroup create` command.
For example:
+
----
# hammer hostgroup create --name "Base" \
--architecture "My_Architecture" \
--content-source-id _My_Content_Source_ID_ \
--content-view "_My_Content_View_" \
--domain "_My_Domain_" \
--lifecycle-environment "_My_Lifecycle_Environment_" \
--locations "_My_Location_" \
--medium-id _My_Installation_Medium_ID_ \
--operatingsystem "_My_Operating_System_" \
--organizations "_My_Organization_" \
--partition-table "_My_Partition_Table_" \
--puppet-ca-proxy-id _My_Puppet_CA_Proxy_ID_ \
--puppet-environment "_My_Puppet_Environment_" \
--puppet-proxy-id _My_Puppet_Proxy_ID_ \
--root-pass "My_Password" \
--subnet "_My_Subnet_"
----
