[id="registering-to-satellite-server_{context}"]

= Registering to {ProjectServer}

ifeval::["{build}" == "foreman"]
This procedure is only for Katello users.
endif::[]

Use this procedure to register the base operating system on which you want to install {SmartProxyServer} to {ProjectServer}.

.Prerequisites
Before registering it to {ProjectServer}, ensure that the base operating system on which you want to install {SmartProxy} meets the following conditions:

.Subscription Manifest Prerequisites
* On {ProjectServer}, a manifest must be installed and it must contain the appropriate repositories for the organization you want {SmartProxy} to belong to.
* The manifest must contain repositories for the base operating system on which you want to install {SmartProxy}, as well as any clients that you want to connect to {SmartProxy}.
* The repositories must be synchronized.

For more information on manifests and repositories, see {ContentManagementDocURL}managing_subscriptions/[Managing Subscriptions] in the _{ProjectName} Content Management Guide_.

.Proxy and Network Prerequisites
* The {ProjectServer} base operating system must be able to resolve the host name of the {SmartProxy} base operating system and vice versa.
ifeval::["{build}" != "foreman-deb"]
* The base operating system on which you want to install {SmartProxyServer} must not be configured to use a proxy to connect to the Red Hat CDN.
endif::[]
* You must configure the host and network-based firewalls accordingly. For more information, see xref:capsule-ports-and-firewalls-requirements_{smart-proxy-context}[].
* You must have a {ProjectServer} user name and password. For more information, see {AdministeringDocURL}chap-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication[Configuring External Authentication] in _Administering {ProjectName}_.

.Procedure
To register your system to {ProjectServer}, complete the following steps:

. Download the `katello-ca-consumer-latest.noarch.rpm` package on the base operating system on which you want to install {SmartProxy}. The consumer RPM configures the host to download content from the content source that is specified in {Project}.
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl --insecure --output katello-ca-consumer-latest.noarch.rpm https://_{foreman-example-com}_/pub/katello-ca-consumer-latest.noarch.rpm
----
+
. Install the `katello-ca-consumer-latest.noarch.rpm` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum localinstall katello-ca-consumer-latest.noarch.rpm
----

. Register the {SmartProxy} base operating system with the environments that you want {SmartProxy} to belong to. Use an activation key to simplify specifying the environments. For more information about activation keys, see {ContentManagementDocURL}Managing_Activation_Keys[Managing Activation Keys] in the _Content Management Guide_.
+
[options="nowrap" subs="+quotes"]
----
# subscription-manager register --org=_organization_name_ --activationkey=_example_activation_key_
----
