:_mod-docs-content-type: PROCEDURE

[id="Enabling_Connections_from_a_Client_to_Server_{context}"]
= Enabling connections from a client to {ProjectServer}

{SmartProxies} and hosts that are clients of a {ProjectServer}'s internal {SmartProxy} require access through {Project}'s host-based firewall and any network-based firewalls.
For the components of {Project} architecture to communicate, ensure that the required network ports are open and free on the base operating system.
You must also ensure that the required network ports are open on any network-based firewalls.

The installation of a {SmartProxyServer} fails if the ports between {ProjectServer} and {SmartProxyServer} are not open before installation starts.

Note that some cloud solutions must be specifically configured to allow communications between machines because they isolate machines similarly to network-based firewalls.
If you use an application-based firewall, ensure that the application-based firewall permits all applications that are listed in the tables and known to your firewall.
If possible, disable the application checking and allow open port communication based on the protocol.

Use this procedure to configure the host-based firewall on the system that {Project} is installed on, to enable incoming connections from Clients, and to make the configuration persistent across system reboots.
For more information on the ports used, see {InstallingServerDocURL}Port_and_firewall_requirements_{project-context}[Port and firewall requirements] in _{InstallingServerDocTitle}_.

include::snip_firewalld.adoc[]

A DHCP {SmartProxy} performs ICMP ping and TCP echo connection attempts to hosts in subnets with DHCP IPAM set to find out if an IP address considered for use is free.
This behavior can be turned off using `{foreman-installer} --foreman-proxy-dhcp-ping-free-ip false`.

.Procedure
ifdef::katello,satellite,orcharhino[]
. Open the ports for clients on {ProjectServer}:
+
[options="nowrap"]
----
# firewall-cmd \
--add-port="8000/tcp" \
--add-port="9090/tcp"
----
endif::[]
. Allow access to services on {ProjectServer}:
+
[options="nowrap"]
----
# firewall-cmd \
--add-service=dns \
--add-service=dhcp \
--add-service=tftp \
--add-service=http \
--add-service=https \
ifndef::katello,satellite,orcharhino[]
--add-service=foreman-proxy \
endif::[]
--add-service=puppetmaster
----
include::snip_make-firewall-settings-persistent.adoc[]

include::snip_verify-firewall-settings.adoc[]
