:_mod-docs-content-type: PROCEDURE

[id="Removing_Lifecycle_Environments_from_{smart-proxy-context-titlecase}_{context}"]
= Removing lifecycle environments from {SmartProxyServer}

When lifecycle environments are no longer relevant to the host system or environments are added incorrectly to {SmartProxyServer}, you can remove the lifecycle environments from {SmartProxyServer}.

You can use both the {ProjectWebUI} and the Hammer CLI to remove lifecycle environments from {SmartProxy}.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*, and select the {SmartProxy} that you want to remove a lifecycle from.
. Click *Edit* and click the *Lifecycle Environments* tab.
. From the right menu, select the lifecycle environments that you want to remove from {SmartProxy}, and then click *Submit*.
. To synchronize {SmartProxy}'s content, click the *Overview* tab, and then click *Synchronize*.
. Select either *Optimized Sync* or *Complete Sync*.

.CLI procedure
. Select {SmartProxyServer} that you want from the list and take note of its *id*:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {hammer-smart-proxy} list
----
. To verify {SmartProxyServer}'s details, enter the following command:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {hammer-smart-proxy} info \
--id __My_{smart-proxy-context-titlecase}_ID__
----
. Verify the list of lifecycle environments currently attached to {SmartProxyServer} and take note of the *Environment ID*:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {hammer-smart-proxy} content lifecycle-environments \
--id __My_{smart-proxy-context-titlecase}_ID__
----
. Remove the lifecycle environment from {SmartProxyServer}:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {hammer-smart-proxy} content remove-lifecycle-environment \
--id __My_{smart-proxy-context-titlecase}_ID__ \
--lifecycle-environment-id _My_Lifecycle_Environment_ID_
----
+
Repeat this step for every lifecycle environment that you want to remove from {SmartProxyServer}.
. Synchronize the content from {ProjectServer}'s environment to {SmartProxyServer}:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {hammer-smart-proxy} content synchronize \
--id __My_{smart-proxy-context-titlecase}_ID__
----
