:_mod-docs-content-type: PROCEDURE

[id="registering-a-host-to-{project-context}-by-using-ansible"]
= Registering a host to {Project} by using Ansible

[role="_abstract"]
You can register a host with an Ansible playbook by using registration templates and set up various integration features and host tools during the registration process.

.Prerequisites
include::snip_registering-a-host-prerequisites.adoc[]

.Procedure
* Use the `{ansible-namespace}.registration_command` module.
+
For more information, see the Ansible module documentation with `ansible-doc {ansible-namespace}.registration_command`.

ifdef::katello,orcharhino,satellite[]
include::snip_verification-repositories-enabled.adoc[]

ifdef::managing-hosts[]
.Next steps
* xref:configuring-tracer-on-a-host_managing-hosts[]
endif::[]
endif::[]

.Additional resources
ifdef::managing-hosts[]
* xref:registration-command-customization[]
endif::[]
ifndef::managing-hosts[]
* {ManagingHostsDocURL}registering-hosts-to-{project-context}[Registering hosts to {Project} in _{ManagingHostsDocTitle}_]
endif::[]
