[id="Using_{FreeIPA}_credentials_to_log_in_to_the_{Project}_Hammer_CLI_{context}"]
= Using {FreeIPA} credentials to log in to the {Project} Hammer CLI

This section describes how to log in to your {Project} Hammer CLI with your {FreeIPA} (IdM) login and password.

.Prerequisites
* You have enrolled your {ProjectServer} into {FreeIPA} and configured it to use {FreeIPA} for authentication.
More specifically, you have enabled access both to the {ProjectWebUI} and the {Project} API.
For more information, see {InstallingServerDocURL}Using_FreeIPA_{project-context}[Using {FreeIPA}] in _{InstallingServerDocTitle}_.
* The host on which you run this procedure is configured to use {FreeIPA} credentials to log users in to your {Project} Hammer CLI.
For more information, see {InstallingServerDocURL}Configuring_the_Hammer_CLI_to_Use_FreeIPA_User_Authentication_{project-context}[Configuring the Hammer CLI to Use {FreeIPA} User Authentication] in _{InstallingServerDocTitle}_.
* The host is an {FreeIPA} client.
* An {FreeIPA} server is running and reachable by the host.

.Procedure
. Obtain a Kerberos ticket-granting ticket (TGT) on behalf of a {Project} user:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ kinit idm_user
----
+
[WARNING]
====
If, when you were setting {FreeIPA} to be the authentication provider, you enabled access to both the {Project} API and the {ProjectWebUI}, an attacker can now obtain an API session after the user receives the Kerberos TGT.
The attack is possible even if the user did not previously enter the {Project} login credentials anywhere, for example in the browser.
====
. If automatic negotiate authentication is not enabled, use the TGT to authenticate to Hammer manually:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer auth login negotiate
----
. Optional: Destroy all cached Kerberos tickets in the collection:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ kdestroy -A
----
[NOTE]
====
You are still logged in, even after destroying the Kerberos ticket.
====

.Verification
* Use any `hammer` command to ensure that the system does not ask you to authenticate again:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer host list
----

[NOTE]
====
To log out of Hammer, enter: `hammer auth logout`.
====
