[id="Creating_an_Image_for_Amazon_EC2_{context}"]
= Creating an Image for Amazon EC2

You can create images for Amazon EC2 from within {Project}.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure > Compute Resources*.
. Select your Amazon EC2 provider.
. Click *Create Image*.

* In the *Name* field, enter a meaningful and unique name for your EC2 image.
* In the *Operating System* drop down menu, associate the image to an operating system within {Project}.
* In the *Architecture* drop down menu, associate the image to an architecture within {Project}.
* Enter the *Username* needed to SSH into the machine.
* Enter the *Image ID* provided by Amazon or a operating system vendor.
ifndef::satellite[]
This ID can be found within Amazon AWS or on operating system specific pages like https://wiki.debian.org/Cloud/AmazonEC2Image/Buster[debian.org] or https://cloud-images.ubuntu.com/locator/ec2/[ubuntu.com].
endif::[]
* Optional: Select the *User Data* check box to enable support for user data input.
* Optional: Set an *Iam Role* for _Fog_ to use when creating this image.
* Click *Submit* to save your changes to {Project}.
