[id="performing-post-upgrade-tasks_{context}"]
= Performing post-upgrade tasks

* Optional: If you are using the {oVirt} compute resource, you can pre-migrate your data by executing the `foreman-rake ovirt:drop` task on your {ProjectServer}.
You can set `OVIRT_PRETEND=true` to preview the changes.
The {oVirt} compute resource will be officially phased out in a future release and this migration will be triggered automatically during a future upgrade.
ifndef::satellite[]
{Team} recommends also removing the {oVirt} package by executing `{project-package-remove} foreman-ovirt` to prevent users from adding a new {oVirt} compute resource.
endif::[]
* Optional: If the default provisioning templates have been changed during the upgrade, recreate any templates cloned from the default templates.
If the custom code is executed before and/or after the provisioning process, use custom provisioning snippets to avoid recreating cloned templates.
For more information about configuring custom provisioning snippets, see {ProvisioningDocURL}Creating_Custom_Provisioning_Snippets_provisioning[Creating Custom Provisioning Snippets] in _{ProvisioningDocTitle}_.

ifdef::katello,orcharhino,satellite[]
* Pulp is introducing more data about container manifests to the API.
This information allows Katello to display manifest labels, annotations, and information about the manifest type, such as if it is bootable or represents flatpak content.
As a result, migrations must be performed to pull this content from manifests into the database.
endif::[]

ifdef::katello[]
This migration takes time, so if you depend on container content and need minimal upgrade downtime, use this procedure to migrate data.

.Procedure
. Enter the following command in a `tmux` window on {ProjectServer} for a pre-migration.
This command migrates data while {Project} is running without any need for downtime and reduces future upgrade downtime:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} advanced procedure run pulpcore-container-handle-image-metadata
----
. If the manifest represents bootable or flatpak content, allow the container image API to display manifest labels, annotations by entering the following command:
+
[options="nowrap" subs="attributes"]
----
# foreman-rake katello:import_container_manifest_labels
----
endif::[]

ifdef::satellite,orcharhino[]
This migration takes time, so a pre-migration runs automatically after the upgrade to {ProjectVersion} to reduce future upgrade downtime.
While the pre-migration is running, {ProjectServer} is fully functional but uses more hardware resources.
endif::[]
