[id="adding-installation-media_{context}"]
= Adding Installation Media to {Project}

Installation media are sources of packages that {ProjectServer} uses to install a base operating system on a machine from an external repository.
ifdef::foreman-el,katello[]
When you install the Katello plug-in, you can download packages from a Pulp mirror.
In this case, installation media are ignored.
endif::[]
ifdef::satellite,orcharhino[]
You can use this parameter to install third-party content.
Red Hat content is delivered through repository syncing instead.
endif::[]

Installation media must be in the format of an operating system installation tree, and must be accessible to the machine hosting the installer through an HTTP URL.
You can view installation media by navigating to *Hosts* > *Installation Media* menu.

ifndef::orcharhino[]
By default, {Project} includes installation media for some official Linux distributions.
Note that some of those installation media are targeted for a specific version of an operating system.
For example *CentOS mirror (7.x)* must be used for CentOS 7 or earlier, and *CentOS mirror (8.x)* must be used for CentOS 8 or later.
endif::[]

If you want to improve download performance when using installation media to install operating systems on multiple host, you must modify the *Path* of the installation medium to point to the closest mirror or a local copy.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-installation-media_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Installation Media* and click *Create Medium*.
. In the *Name* field, enter a name to represent the installation media entry.
. In the *Path* enter the URL or NFS share that contains the installation tree.
You can use following variables in the path to represent multiple different system architectures and versions:
  * `$arch` - The system architecture.
  * `$version` - The operating system version.
  * `$major` - The operating system major version.
  * `$minor` - The operating system minor version.
+
Example HTTP path:
+
----
http://download.example.com/centos/$version/Server/$arch/os/
----
+
Example NFS path:
+
----
nfs://download.example.com:/centos/$version/Server/$arch/os/
----
+
Synchronized content on {SmartProxyServer}s always uses an HTTP path.
{SmartProxyServer} managed content does not support NFS paths.
+
. From the *Operating system family* list, select the distribution or family of the installation medium.
For example, CentOS and Fedora are in the `Red Hat` family.
ifndef::satellite[]
Debian and Ubuntu belong to the `Debian` family.
endif::[]
. Click the *Organizations* and *Locations* tabs, to change the provisioning context.
{ProjectServer} adds the installation medium to the set provisioning context.
. Click *Submit* to save your installation medium.

[id="cli-adding-installation-media_{context}"]
.CLI procedure
* Create the installation medium using the `hammer medium create` command:
+
[options="nowrap" subs="+quotes"]
----
# hammer medium create --name "CustomOS" --os-family "Redhat" \
--path 'http://download.example.com/centos/$version/Server/$arch/os/' \
--organizations "_My_Organization_" --locations "_My_Location_"
----
