[id="Editing_the_System_Purpose_of_Multiple_Hosts_{context}"]
= Editing the System Purpose of Multiple Hosts

You can edit the system purpose attributes of {RHEL} hosts.
System purpose attributes define which subscriptions to attach automatically to hosts.
ifndef::orcharhino[]
For more information about system purpose, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/graphical-installation_graphical-installation?extIdCarryOver=true&sc_cid=701f2000001Css5AAC#system_purposes-adoc_connect-to-red-hat[Introduction to System Purpose] in _Performing a standard RHEL 8 installation_.
endif::[]

.Prerequisites
* The hosts that you want to edit must be registered with the subscription-manager.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts*{nbsp}>{nbsp}*Content Hosts* and select {RHEL} 8 hosts that you want to edit.
. Click the *Select Action* list and select *Manage System Purpose*.
. Select the system purpose attributes that you want to assign to the selected hosts.
You can select one of the following values:
+
* A specific attribute to set an all selected hosts.
* *No Change* to keep the attribute set on the selected hosts.
* *None (Clear)* to clear the attribute on the selected hosts.
. Click *Assign*.
. In the {ProjectWebUI}, navigate to *Hosts*{nbsp}>{nbsp}*Content Hosts* and select the same {RHEL} 8 hosts to automatically attach subscriptions based on the system purpose.
. Click the *Select Action* list and select *Manage Subscriptions*.
. Click *Auto-Attach* to attach subscriptions to all selected hosts automatically based on their system role.
