[id="managing-puppet-limitations-with-load-balancing-in-project_{context}"]
= Managing Puppet limitations with load balancing in {Project}

If you use Puppet, Puppet certificate signing is assigned to the first {SmartProxy} that you configure.
If the first {SmartProxy} is down, clients cannot obtain Puppet content.

Puppet Certificate Authority (CA) management does not support certificate signing in a load-balanced setup.
Puppet CA stores certificate information, such as the serial number counter and CRL, on the file system.
Multiple writer processes that attempt to use the same data can corrupt it.

To manage this Puppet limitation, complete the following steps:

. Configure Puppet certificate signing on one {SmartProxyServer}, typically the first system where you configure {SmartProxyServer} for load balancing.
. Configure the clients to send CA requests to port 8141 on a load balancer.
. Configure a load balancer to redirect CA requests from port 8141 to port 8140 on the system where you configure {SmartProxyServer} to sign Puppet certificates.