:_mod-docs-content-type: PROCEDURE

[id="generating-host-monitoring-reports-by-using-web-ui"]
= Generating host monitoring reports by using {ProjectWebUI}

To view the report templates in the {ProjectWebUI}, navigate to *Monitor* > *Reports* > *Report Templates*.
You can also schedule reports from the {ProjectWebUI}.

.Procedure
. In the {ProjectWebUI}, navigate to *Monitor* > *Reports* > *Report Templates*.
For example, the *Host {endash} Installed Products* template generates a report with installed product information along with other metrics, including system purpose attributes.
. To the right of the report template that you want to use, click *Generate*.
. Optional: To schedule a report, to the right of the *Generate at* field, click the icon to select the date and time you want to generate the report at.
. Optional: To send a report to an e-mail address, select the *Send report via e-mail* checkbox, and in the *Deliver to e-mail addresses* field, enter the required e-mail address.
. Optional: Apply search query filters.
To view all available results, do not populate the filter field with any values.
. Click *Submit*.
A CSV file that contains the report is downloaded.
If you have selected the *Send report via e-mail* checkbox, the host monitoring report is sent to your e-mail address.
