:_mod-docs-content-type: PROCEDURE

[id="disabling-recommendations"]
= Disabling recommendations

[role="_abstract"]
You can disable recommendations per organization or per host.
{Project} does not show disabled recommendations in dashboards or reports.

.Prerequisites
* Your {Project} account has a role that grants the following permissions: `view_foreman_rh_cloud`, `view_insights_hits`, `view_advisor`, and `edit_advisor`.
You can get these permissions with the `ForemanRhCloud` built-in role.
* Ensure an organization and location are selected in the top bar of the {ProjectWebUI}.

.Procedure
. In the {ProjectWebUI}, navigate to *{Insights}* > *Recommendations*.
. Disable the recommendation:
* To disable the recommendation for an organization:
.. Click the recommendation menu icon next to the recommendation you want to disable.
.. Select *Disable recommendation*.
.. Optional: Enter a justification for disabling the recommendation.
.. Click *Save*.
* To disable the recommendation for a host:
.. Click the name of the recommendation to view affected hosts.
.. Click the host menu icon next to the host for which you want to disable the recommendation.
.. Select *Disable recommendation for system*.
.. Optional: Enter a justification for disabling the recommendation.
.. Click *Save*.
