[id="Locating_a_Red_Hat_Subscription_{context}"]
= Locating a Red Hat Subscription

When you import a Red{nbsp}Hat Subscription Manifest into {ProjectServer}, the subscriptions from your manifest are listed in the Subscriptions window.
If you have a high volume of subscriptions, you can filter the results to find a specific subscription.

.Prerequisite
* You must have a Red{nbsp}Hat Subscription Manifest file imported to {ProjectServer}.
For more information, see xref:Importing_a_Red_Hat_Subscription_Manifest_into_Server_{context}[].

.Procedure
. In the {ProjectWebUI}, ensure the context is set to the organization you want to use.
. In the {ProjectWebUI}, navigate to *Content*{nbsp}>{nbsp}*Subscriptions*.
. In the Subscriptions window, click the *Search* field to view the list of search criteria for building your search query.
. Select search criteria to display further options.
. When you have built your search query, click the search icon.

For example, if you place your cursor in the *Search* field and select *expires*, then press the space bar, another list appears with the options of placing a *>*, *<*, or *=* character.
If you select *>* and press the space bar, another list of automatic options appears.
You can also enter your own criteria.
