[id="installing-and-configuring-puppet-agent-during-host-registration_{context}"]
= Installing and Configuring Puppet Agent during Host Registration

Use this procedure to install and configure the Puppet agent on the host during registration.

ifdef::satellite[]
.Prerequisites
* You enabled and synchronized the *{project-client-name}* repository to {Project}.
For more information, see {ContentManagementDocURL}Importing_Content_content-management[Importing Content] in _{ContentManagementDocTitle}_.
* You created an activation key that enables the *{project-client-name}* repository for hosts.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in _{ContentManagementDocTitle}_.
endif::[]
ifdef::katello,orcharhino[]
.Prerequisites
* You created a Product and repository for the upstream Puppet agent, such as `\https://yum.puppet.com` or `\https://apt.puppet.com`, and synchronized the repository to {Project}.
For more information, see {ContentManagementDocURL}Importing_Content_content-management[Importing Content] in _{ContentManagementDocTitle}_.
* You created an activation key that enables the Puppet agent repository for hosts.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in _{ContentManagementDocTitle}_.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Global Parameters* to add host parameters globally.
Alternatively, you can navigate to *Configure* > *Host Groups* and edit or create a host group to add host parameters only to a host group.
ifdef::katello,orcharhino,satellite[]
. Enable the Puppet agent using a host parameter in global parameters or a host group.
Add a host parameter named `enable-puppet7`, select the *boolean* type, and set the value to `true`.
endif::[]
ifndef::katello,orcharhino,satellite[]
. Enable the Puppet agent from the official Puppet repository using one of the following host parameters in global parameters or a host group:

* Add a host parameter named `enable-puppetlabs-repo` for the latest stable Puppet release in the unversioned repository.
* Add a host parameter named `enable-official-puppet7-repo` for the Puppet 7 release repository.

+
Select the *boolean* type and set the value to `true`.
endif::[]
. Specify configuration for the Puppet agent using the following host parameters in global parameters or a host group:
* Add a host parameter named `puppet_server`, select the *string* type, and set the value to the hostname of your Puppet server, such as `puppet.example.com`.
* Optional: Add a host parameter named `puppet_ca_server`, select the *string* type, and set the value to the hostname of your Puppet CA server, such as `puppet-ca.example.com`.
If `puppet_ca_server` is not set, the Puppet agent will use the same server as `puppet_server`.
* Optional: Add a host parameter named `puppet_environment`, select the *string* type, and set the value to the Puppet environment you want the host to use.

+
Until the https://bugzilla.redhat.com/show_bug.cgi?id=2177730[BZ2177730] is resolved, you must use host parameters to specify the Puppet agent configuration even in integrated setups where the Puppet server is a {SmartProxyServer}.
ifdef::katello,orcharhino,satellite[]
. Navigate to *Hosts* > *Register Host* and register your host using an appropriate activation key.
endif::[]
ifndef::katello,orcharhino,satellite[]
. Navigate to *Hosts* > *Register Host* and register your host.
endif::[]
ifeval::[{context} == "managing-hosts"]
For more information, see xref:Registering_Hosts_{context}[].
endif::[]
ifeval::[{context} != "managing-hosts"]
For more information, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in _{ManagingHostsDocTitle}_.
endif::[]
. Navigate to *Infrastructure* > *{SmartProxies}*.
. From the list in the *Actions* column for the required {SmartProxyServer}, select *Certificates*.
. Click *Sign* to the right of the required host to sign the SSL certificate for the Puppet agent.

ifndef::managing-configurations-puppet[]
.Additional Resources
* For more information about Puppet, see {ManagingConfigurationsPuppetDocURL}[_{ManagingConfigurationsPuppetDocTitle}_].
endif::[]