:_mod-docs-content-type: PROCEDURE

[id="adding-custom-rpm-repositories-by-using-web-ui"]
= Adding {customrpm} repositories by using {ProjectWebUI}

[role="_abstract"]
You can add {customrpm} repositories to {Project} by using the {ProjectWebUI}.

The *Products* window in the {ProjectWebUI} also provides a *Repo Discovery* function that finds all repositories from a URL and you can select which ones to add to your {customproduct}.
For example, you can use the *Repo Discovery* to search `https://download.postgresql.org/pub/repos/yum/16/redhat/` and list all repositories for different {EL} versions and architectures.
This helps users save time importing multiple repositories from a single source.

ifdef::satellite[]
.Support for {customrpm}s
Red Hat does not support the upstream RPMs directly from third-party sites.
These RPMs are used to demonstrate the synchronization process.
For any issues with these RPMs, contact the third-party developers.
endif::[]

.Prerequisites
* You have imported the GPG key that you want to use to verify signatures of the RPM packages.
For more information, see xref:importing-a-custom-gpg-key-by-using-web-ui[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products* and select the product that you want to use, and then click *New Repository*.
. In the *Name* field, enter a name for the repository.
{Project} automatically completes the *Label* field based on what you have entered for *Name*.
. Optional: In the *Description* field, enter a description for the repository.
. From the *Type* list, select `yum` as type of repository.
. Optional: From the *Restrict to Architecture* list, select an architecture.
If you want to make the repository available to all hosts regardless of the architecture, ensure to select *No restriction*.
. Optional: From the *Restrict to OS Version* list, select the operating system version.
If you want to make the repository available to all hosts regardless of the operating system version, ensure to select *No restriction*.
. Optional: In the *Upstream URL* field, enter the URL of the external repository to use as a source.
{Project} supports three protocols: `http://`, `https://`, and `file://`.
If you are using a `file://` repository, you have to place it under `/var/lib/pulp/sync_imports/` directory.
+
If you do not enter an upstream URL, you can manually upload packages.
. Optional: Check the *Ignore SRPMs* checkbox to exclude source RPM packages from being synchronized to {Project}.
. Optional: Check the *Ignore treeinfo* checkbox if you receive the error `Treeinfo file should have INI format`.
All files related to Kickstart will be missing from the repository if `treeinfo` files are skipped.
. Select the *Verify SSL* checkbox if you want to verify that the upstream repository's SSL certificates are signed by a trusted CA.
. Optional: In the *Upstream Username* field, enter the user name for the upstream repository if required for authentication.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Password* field, enter the corresponding password for the upstream repository.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Authentication Token* field, provide the token of the upstream repository user for authentication.
Leave this field empty if the repository does not require authentication.
. From the *Download Policy* list, select the type of synchronization {ProjectServer} performs.
For more information, see xref:Download_Policies_Overview_{context}[].
. From the *Mirroring Policy* list, select the type of content synchronization {ProjectServer} performs.
For more information, see xref:Mirroring_Policies_Overview_{context}[].
. Optional: In the *Retain package versions* field, enter the number of versions you want to retain per package.
. Optional: In the *HTTP Proxy Policy* field, select an HTTP proxy.
. From the *Checksum* list, select the checksum type for the repository.
. Optional: You can clear the *Unprotected* checkbox to require a subscription entitlement certificate for accessing this repository.
By default, the repository is published through HTTP.
. Optional: From the *GPG Key* list, select the GPG key for the product.
. Optional: In the *SSL CA Cert* field, select the SSL CA Certificate for the repository.
. Optional: In the *SSL Client cert* field, select the SSL Client Certificate for the repository.
. Optional: In the *SSL Client Key* field, select the SSL Client Key for the repository.
. Click *Save* to create the repository.

.Next steps
* xref:repository-synchronization[]
