:_mod-docs-content-type: PROCEDURE

[id="migrating-to-external-databases_{context}"]
= Migrating to external databases

[role="_abstract"]
Back up and transfer existing data, then use the `{foreman-installer}` command to configure {Project} to connect to an external PostgreSQL database server.

.Prerequisites
* You have installed and configured a PostgreSQL server on an external server.

.Procedure
. On {ProjectServer}, stop all {Project} services except for PostgreSQL:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-maintain} service stop --exclude postgresql
----
. Create your target directory for the {Project} backup:
+
[options="nowrap", subs="+quotes,attributes"]
----
# mkdir /var/_My_Migration_Backup_Directory_
----
. Back up the internal databases:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-maintain} backup online \
--preserve-directory \
ifndef::foreman-el,foreman-deb[]
--skip-pulp-content \
endif::[]
/var/_My_Migration_Backup_Directory_
----
. Transfer the data to the new external databases:
+
[options="nowrap", subs="+quotes,attributes"]
----
PGPASSWORD='_Foreman_Password_' pg_restore --host=_postgres.example.com_ --username=foreman --dbname=foreman < /var/_My_Migration_Backup_Directory_/foreman.dump
ifndef::foreman-el,foreman-deb[]
PGPASSWORD='_Candlepin_Password_' pg_restore --host=_postgres.example.com_ --username=candlepin --dbname=candlepin < /var/_My_Migration_Backup_Directory_/candlepin.dump
PGPASSWORD='_Pulpcore_Password_' pg_restore --host=_postgres.example.com_ --username=pulp --dbname=pulpcore < /var/_My_Migration_Backup_Directory_/pulpcore.dump
endif::[]
----
. Use the `{foreman-installer}` command to update {Project} to point to the new 
ifndef::foreman-deb,foreman-el[]
databases:
endif::[]
ifdef::foreman-deb,foreman-el[]
database:
endif::[]
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} \
ifndef::foreman-deb,foreman-el[]
--katello-candlepin-manage-db false \
--katello-candlepin-db-host _postgres.example.com_ \
--katello-candlepin-db-name candlepin \
--katello-candlepin-db-user candlepin \
--katello-candlepin-db-password _Candlepin_Password_ \
--foreman-proxy-content-pulpcore-manage-postgresql false \
--foreman-proxy-content-pulpcore-postgresql-host _postgres.example.com_ \
--foreman-proxy-content-pulpcore-postgresql-db-name pulpcore \
--foreman-proxy-content-pulpcore-postgresql-user pulp \
--foreman-proxy-content-pulpcore-postgresql-password _Pulpcore_Password_ \
endif::[]
--foreman-db-manage false \
--foreman-db-host _postgres.example.com_ \
--foreman-db-database foreman \
--foreman-db-username foreman \
--foreman-db-password _Foreman_Password_
----
. Remove the PostgreSQL package on {ProjectServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-remove} {postgresql-server-package}
----
. Remove the PostgreSQL data directory:
+
[options="nowrap", subs="+quotes,attributes"]
----
# rm -fr {postgresql-data-dir}
----
ifdef::foreman-deb[]
+
If you run {ProjectServer} on Debian 12, you have to adjust the paths of PostgreSQL config and data directories which depend on the PostgreSQL version.
endif::[]
