[id="Using_Activation_Keys_for_Host_Registration_{context}"]
= Using Activation Keys for Host Registration

You can use activation keys to complete the following tasks:

* Registering new hosts during provisioning through {ProjectNameX}.
The kickstart provisioning templates in {ProjectNameX} contain commands to register the host using an activation key that is defined when creating a host.
* Registering existing Red Hat Enterprise Linux hosts.
Configure Subscription Manager to use {ProjectServer} for registration and specify the activation key when running the `subscription-manager register` command.

.Procedure

To use an activation key for host registration with an existing Red Hat Enterprise Linux 7 host to {ProjectServer}, complete the following steps:

. Download the consumer RPM for your {ProjectServer}.
This is located in the `pub` directory on the host's web server.
For example, for a {ProjectServer} with the host name `{foreman-example-com}`, enter the following command on the host to register:
+
[options="nowrap" subs="+quotes,attributes"]
----
# rpm -Uvh _http://{foreman-example-com}_/pub/katello-ca-consumer-latest.noarch.rpm
----
+
This RPM installs the necessary certificates for accessing repositories on {ProjectServer} and configures Subscription Manager to use the server's URL.
. On the host, enter the following command to register the host to {Project} using the activation key:
+
[options="nowrap" subs="+quotes"]
----
# subscription-manager register --activationkey="_My_Activation_Key_" \
--org="_My_Organization_"
----
. To view a list of hosts for an organization, on {ProjectServer}, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# hammer host list --organization "_My_Organization_"
----

.Multiple Activation Keys

You can use multiple activation keys when registering a content host.
You can then create activation keys for specific subscription sets and combine them according to content host requirements.
For example, the following command registers a content host to your organization with both VDC and OpenShift subscriptions:

[options="nowrap" subs="+quotes"]
----
# subscription-manager register --org="_My_Organization_" \
--activationkey="ak-VDC,ak-OpenShift"
----

.Settings Conflicts
If there are conflicting settings in activation keys, the rightmost key takes precedence.

* Settings that conflict: *Service Level*, *Release Version*, *Environment*, *Content View*, and *Product Content*.
* Settings that do not conflict and the host gets the union of them: *Subscriptions* and *Host Collections*.
* Settings that influence the behavior of the key itself and not the host configuration: *Content Host Limit* and *Auto-Attach*.
