[id="creating-a-host-activation-key_{context}"]
= Creating an Activation Key for the Hosts

Use this procedure to create an activation key for the hosts to use.

.Procedure
ifndef::orcharhino[]
. In the {ProjectWebUI}, navigate to *Content* *>* *Red Hat Repositories*.
. Enable the {RHEL} 7 Server repository.
endif::[]
. In the {ProjectWebUI}, navigate to *Content* *>* *Activation keys* and click *Create Activation Key*.
. In the *Name* field, enter the name of the host activation key.
. If you want to set a limit, clear the *Unlimited hosts* check box, and in the *Limit* field, enter the maximum number of systems you can register with the activation key.
If you want unlimited hosts to register with the activation key, ensure the *Unlimited Hosts* check box is selected.
. Optional: In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the environment to use.
. From the *Content View* list, select a Content View to use.
. Click *Save*.
. If SCA is not enabled:
.. Click the *Subscriptions* tab, then click the *Add* submenu.
.. Click the checkbox under the subscription you created before.
.. Click *Add Selected*.
. If SCA is enabled:
.. In the *Repository Sets* tab, ensure only your named repository is enabled.
