:_mod-docs-content-type: PROCEDURE

[id="enabling-rh-cloud-and-insights-client-reports-on-hosts_{context}"]
= Enabling RH Cloud and {Insights} client reports on hosts

[role="_abstract"]
You can enable the {Insights} client on hosts and have {Project} upload hosts inventory to the {Insights} service in the {RHCloud}.

ifdef::katello,foreman-el,foreman-deb[]
{Insights} is a service by Red Hat for {RHEL} hosts.
Ensure to set this parameter for {RHEL} hosts only.
If you set the parameter on any non-{RHEL} operating systems, {Project} automatically uploads new reports to the {RHCloud} when enabled in RH Cloud {Project} settings.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Host* > *Provisioning Setup* > *Operating Systems*.
. Select any {RHEL} operating systems for which you want to change the value.
. On the *Parameters* tab, add the `host_registration_insights` parameter, select the *boolean* type, and set the value to *True*.
. Click *Submit* to save the parameter.
+
You can set this parameter at any level.
For more information, see {ProvisioningDocURL}Host_Parameter_Hierarchy_provisioning[Host parameter hierarchy] in _{ProvisioningDocTitle}_.
