[id="Installing_and_Configuring_Puppet_Agent_during_Host_Provisioning_{context}"]
= Installing and Configuring Puppet Agent during Host Provisioning

You can install and configure the Puppet agent on a host during the provisioning process.
A configured Puppet agent is required on the host for Puppet integration with your {Project}.

ifdef::satellite[]
.Prerequisites
* Puppet must be enabled in your {Project}.
For more information, see xref:Enabling_Puppet_Integration_{context}[].
* You enabled and synchronized the *{project-client-name}* repository to {Project}.
For more information, see {ContentManagementDocURL}Importing_Content_content-management[Importing Content] in _{ContentManagementDocTitle}_.
* You created an activation key that enables the *{project-client-name}* repository for hosts.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in _{ContentManagementDocTitle}_.
endif::[]
ifdef::katello,orcharhino[]
.Prerequisites
* You created a Product and repository for the upstream Puppet agent, such as `\https://yum.puppet.com` or `\https://apt.puppet.com`, and synchronized the repository to {Project}.
For more information, see {ContentManagementDocURL}Importing_Content_content-management[Importing Content] in _{ContentManagementDocTitle}_.
* You created an activation key that enables the Puppet agent repository for hosts.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in _{ContentManagementDocTitle}_.
endif::[]

.Procedure
. Navigate to *Hosts* > *Provisioning Templates*.
. Select a provisioning template depending on your host provisioning method.
For more information, see {ProvisioningDocURL}types-of-provisioning-templates_provisioning[Types of Provisioning Templates] in _{ProvisioningDocTitle}_.
ifndef::katello,orcharhino,satellite[]
. Ensure the `puppetlabs_repo` snippet is included as follows:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
<%= snippet 'puppetlabs_repo' %>
----
+
Note that this snippet is already included in the templates shipped with {Project}, such as `Kickstart default` or `Preseed default`.
endif::[]
. Ensure the `puppet_setup` snippet is included as follows:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
<%= snippet 'puppet_setup' %>
----
+
Note that this snippet is already included in the templates shipped with {Project}, such as `Kickstart default` or `Preseed default`.
ifdef::katello,orcharhino,satellite[]
. Enable the Puppet agent using a host parameter in global parameters, a host group, or for a single host.
Add a host parameter named `enable-puppet7`, select the *boolean* type, and set the value to `true`.
endif::[]
ifndef::katello,orcharhino,satellite[]
. Enable the Puppet agent from the official Puppet repository using one of the following host parameters in global parameters, a host group, or for a single host:

* Add a host parameter named `enable-puppetlabs-repo` for the latest stable Puppet release in the unversioned repository.
* Add a host parameter named `enable-official-puppet7-repo` for the Puppet 7 release repository.

+
Select the *boolean* type and set the value to `true`.
endif::[]
. Set configuration for the Puppet agent.
* If you use an integrated Puppet server, ensure that you select a Puppet {SmartProxy}, Puppet CA {SmartProxy}, and Puppet environment when you create a host.
* If you use a non-integrated Puppet server, either set the following host parameters in global parameters, or a host group, or when you create a host:
** Add a host parameter named `puppet_server`, select the *string* type, and set the value to the hostname of your Puppet server, such as `puppet.example.com`.
** Optional: Add a host parameter named `puppet_ca_server`, select the *string* type, and set the value to the hostname of your Puppet CA server, such as `puppet-ca.example.com`.
If `puppet_ca_server` is not set, the Puppet agent will use the same server as `puppet_server`.
** Optional: Add a host parameter named `puppet_environment`, select the *string* type, and set the value to the Puppet environment you want the host to use.
ifdef::katello,orcharhino,satellite[]
. Ensure your host has access to the Puppet agent packages from {ProjectServer} by using an appropriate activation key.
endif::[]
