[id="provisioning-from-a-builder-image-on-an-http-server"]
= Provisioning from a {LoraxCompose} image on an HTTP server

You can upload a {LoraxCompose} image to an HTTP server and use this image to provision hosts.

ifndef::satellite[]
[NOTE]
====
This feature is available for {EL} hosts only.
====
endif::[]

When you provision from a {LoraxCompose} image, Anaconda installer partitions disks, downloads and mounts the image, and copies files over to a host.

.Prerequisites
* An existing ISO image created by using {LoraxCompose}.
Ensure that your blueprint to build the image includes a kernel package.

.Procedure
. Copy the ISO image to an existing HTTP server which installed hosts can reach.
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*.
. Select the host group that you want to use.
. Click the *Parameters* tab, and then click *Add Parameter*.
. In the *Name* field, enter `kickstart_liveimg`.
. From the *Type* list, select *string*.
. In the *Value* field, enter the URL of the image location, such as `https://_webserver.example.com_/_path_/_image_name.iso_`.
. Click *Submit* to save your changes.

ifdef::provisioning[]
You can use this image for bare-metal provisioning and provisioning using a compute resource.
For more information about bare-metal provisioning, see xref:Using_PXE_to_Provision_Hosts_{context}[].
For more information about provisioning with different compute resources, see the relevant chapter for the compute resource that you want to use.
endif::[]
ifdef::provisioning-installer[]
You can use this image for network-boot provisioning.
For more information, see xref:using-network-boot-to-provision-hosts[].
endif::[]
