:_mod-docs-content-type: PROCEDURE

[id="Refreshing_Content_Counts_on_{smart-proxy-context-titlecase}_{context}"]
= Refreshing content counts on {SmartProxy}

[role="_abstract"]
If your {SmartProxies} have synchronized content enabled, you can refresh the number of content counts available to the environments associated with the {SmartProxy}.
This displays the content views inside those environments available to the {SmartProxy}.
You can then expand the content view to view the repositories associated with that content view version.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*, and select the {SmartProxy} where you want to see the synchronized content.
. Select the *Overview* tab.
. Under *Content Sync*, toggle the *Synchronize* button to do an *Optimized Sync* or a *Complete Sync* to synchronize the {SmartProxy} which refreshes the content counts.
. Select the *Content* tab.
. Choose an *Environment* to view content views available to those {SmartProxies} by clicking *>*.
. Expand the content view by clicking *>* to view repositories available to the content view and the specific version for the environment.
. View the number of content counts under *Packages* specific to {client-content-type} repositories.
. View the number of errata, package groups, files, container tags, container manifests, and Ansible collections under *Additional content*.
. Click the vertical ellipsis in the column to the right next to the environment and click *Refresh counts* to refresh the content counts synchronized on the {SmartProxy} under *Packages*.
