[id="configuring-compliance-policy-deployment-methods_{context}"]
= Configuring Compliance Policy Deployment Methods

Use one the following procedures to configure {Project} for the method that you have selected to deploy compliance policies.
You select one of these methods when you later xref:Creating_a_Compliance_Policy_{context}[create a compliance policy].

.Procedure for Ansible deployment
. Import the `theforeman.foreman_scap_client` Ansible role.
+
For more information, see {ManagingConfigurationsAnsibleDocURL}[_{ManagingConfigurationsAnsibleDocTitle}_].
. Assign the created policy and the `theforeman.foreman_scap_client` Ansible role to a host or host group.
. To trigger the deployment, run the Ansible role on the host or host group either manually, or set up a recurring job using remote execution for regular policy updates.
+
For more information, see {ManagingHostsDocURL}Configuring_and_Setting_Up_Remote_Jobs_managing-hosts[Configuring and Setting Up Remote Jobs] in _{ManagingHostsDocTitle}_.

.Procedure for Puppet deployment
. Ensure Puppet is enabled.
. Ensure the Puppet agent is installed on hosts.
. Import the Puppet environment that contains the `foreman_scap_client` Puppet module.
+
For more information, see {ManagingConfigurationsPuppetDocURL}[_{ManagingConfigurationsPuppetDocTitle}_].
. Assign the created policy and the `foreman_scap_client*` Puppet classes to a host or host group.
+
Puppet triggers the deployment on the next regular run or you can run Puppet manually.
Puppet runs every 30 minutes by default.

.Procedure for manual deployment
* For the manual deployment method, no additional {Project} configuration is required.
ifdef::satellite[]
+
For information on manual deployment, see https://access.redhat.com/solutions/6389101[How to set up OpenSCAP Policies using Manual Deployment option] in the _Red{nbsp}Hat Knowledgebase_.
endif::[]
