[id="adding-rhv-details-to-a-compute-profile_{context}"]
= Adding {oVirt} Details to a Compute Profile

Use this procedure to add {oVirt} hardware settings to a compute profile.
When you create a host on KVM using this compute profile, these settings are automatically populated.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-rhv-details-to-a-compute-profile_{context}[].

.Procedure

. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*Compute Profiles*.
. In the Compute Profiles window, click the name of an existing compute profile, or click *Create Compute Profile*, enter a *Name*, and click *Submit*.
. Click the name of the {oVirt} compute resource.
. From the *Cluster* list, select the target host cluster in the {oVirt} environment.
. From the *Template* list, select the {oVirtShort} template to use for the *Cores* and *Memory* settings.
. In the *Cores* field, enter the number of CPU cores to allocate to the new host.
. In the *Memory* field, enter the amount of memory to allocate to the new host.
. From the *Image* list, select image to use for image-based provisioning.
. In the *Network Interfaces* area, enter the network parameters for the host's network interface.
You can create multiple network interfaces.
However, at least one interface must point to a {SmartProxy}-managed network.
For each network interface, enter the following details:
.. In the *Name* field, enter the name of the network interface.
.. From the *Network* list, select The logical network that you want to use.
. In the *Storage* area, enter the storage parameters for the host.
You can create multiple volumes for the host.
For each volume, enter the following details:
.. In the *Size (GB)* enter the size, in GB, for the new volume.
.. From the *Storage domain* list, select the storage domain for the volume.
.. From the *Preallocate disk*, select either thin provisioning or preallocation of the full disk.
.. From the *Bootable* list, select whether you want a bootable or non-bootable volume.
. Click *Submit* to save the compute profile.

[id="cli-adding-rhv-details-to-a-compute-profile_{context}"]
.CLI procedure

. To create a compute profile, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer compute-profile create --name "{oVirt} CP"
----
+
. To set the values for the compute profile, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer compute-profile values create --compute-profile "{oVirt} CP" \
--compute-resource "__My_{oVirtShort}__" \
--interface "compute_interface=_Interface_Type_,compute_name=eth0,compute_network=satnetwork" \
--volume "size_gb=20G,storage_domain=Data,bootable=true" \
--compute-attributes "cluster=Default,cores=1,memory=1073741824,start=true""
----
