[id="setting-discovery-as-the-default-PXE-boot-option_{context}"]
= Setting Discovery as the default PXE boot option

Set the Discovery service as the default service that boots for hosts that are not present in your current {Project} inventory.

When you start an unknown host in PXE mode, {ProjectServer} or {SmartProxyServer} provides a boot menu with a default boot option.
The boot menu has two basic options: `local` and `discovery`.
The default setting of the global PXE templates is to select `local` to boot the host from the local hard drive.
Change the setting to select `discovery` to boot from the Discovery image.

.Prerequisites
* Your {Project} account has the `view_settings`, `edit_settings`, and `view_provisioning_templates` permissions.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. On the *Provisioning* tab, enter `discovery` in the *Default PXE global template entry* field.
. Navigate to *Hosts* > *Templates* > *Provisioning Templates* and click *Build PXE Default*.
+
The boot menus are built as the following files:

** `/var/lib/tftpboot/pxelinux.cfg/default`
** `/var/lib/tftpboot/grub2/grub.cfg`

+
{Project} propagates the default boot menus to all TFTP {SmartProxies}.
