:_mod-docs-content-type: PROCEDURE

[id="recover-from-failed-ansible-content-imports-by-using-api"]
= Recover from failed Ansible content imports by using {Project} API

[role="_abstract"]
If you try to import Ansible content to {Project} and the import workflow fails, you can recover database inconsistencies.
The consistency check ensures that your {Project} database only contains properly imported Ansible content.

.Prerequisites
* Your {Project} account has a role that grants the `destroy_ansible_content`, `view_ansible_content`, and `view_organizations` permissions.

.Procedure
* Perform a consistency check on {Project} to recover from failed Ansible content imports:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--request POST \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_content/consistency_check/ \
| jq
----

.Verification
* Query the {Project} API to verify that the task finished successfully:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/foreman_tasks/api/tasks/_My_Task_ID_/details/ \
| jq ".state,.result"
----

.Next steps
* If your Ansible content import failed due to network issues, you can retry to import Ansible content.
