:_mod-docs-content-type: PROCEDURE

[id="registering-the-host-and-testing-package-delivery_{context}"]
= Register the host and test package delivery

[role="_abstract"]
Register a host to {Project} and verify that it receives packages from your content view.
Registration connects the host to {ProjectServer} and assigns the lifecycle environment and content view from the activation key.

.Prerequisites
* You have created an activation key that is associated with a lifecycle environment and a content view.
* The host can resolve the FQDN of your {ProjectServer}.
* You have root access to the host.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Register Host*.
. From the *Activation Keys* list, select the activation key you created, for example `my-dev-key`.
ifdef::katello,satellite[]
. Ensure the *Insecure* option is selected if you have not deployed a CA-signed certificate on {ProjectServer}.
endif::[]
. Click *Generate* to generate the registration command.
. Copy the registration command.
. On your host, run the registration command as the root user:
+
[options="nowrap" subs="+quotes"]
----
# _<paste the registration command>_
----
. After registration completes, install a package to verify that the host pulls content from {Project}:
+
ifdef::katello,satellite,almalinux,amazon_linux,centos,oracle_linux,red_hat_enterprise_linux,rocky_linux,suse_linux_enterprise_server[]
[options="nowrap" subs="+quotes"]
----
# dnf install _tree_
----
endif::[]
ifdef::debian,ubuntu[]
[options="nowrap" subs="+quotes"]
----
# apt install _tree_
----
endif::[]
+
Verify that {ProjectServer} delivers the package instead of external mirrors.

.Verification
. In the {ProjectWebUI}, navigate to *Hosts* > *Content Hosts*.
. Verify that your host is displayed in the list with the correct lifecycle environment and content view.
. On the host, verify that the repository configuration points to {ProjectServer}:
+
ifdef::katello,satellite,almalinux,amazon_linux,centos,oracle_linux,red_hat_enterprise_linux,rocky_linux,suse_linux_enterprise_server[]
----
# dnf repolist
----
endif::[]
ifdef::debian,ubuntu[]
----
# apt-cache policy
----
endif::[]

Your content pipeline is now working end to end.
Hosts registered with your activation key receive packages from the content view snapshot in the Dev lifecycle environment.

When you are ready to promote content to production, publish a new content view version and promote it through your lifecycle environment path.

.Additional resources
* {ManagingHostsDocURL}registering-hosts-by-using-global-registration[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_
* {ContentManagementDocURL}creating-a-content-view-by-using-web-ui[Creating a content view by using {ProjectWebUI}] in _{ContentManagementDocTitle}_
