[id="registering-a-host_{context}"]
= Registering a host

You can register a host by using registration templates and set up various integration features and host tools during the registration process.

.Prerequisites
* Your {Project} account has the *Register hosts* role assigned or a role with equivalent permissions.
* You must have root privileges on the host that you want to register.
* You have configured the host for registration.
For more information, see xref:Configuring_a_Host_for_Registration_{context}[].
ifdef::satellite,orcharhino,katello[]
* An activation key must be available for the host.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in _{ContentManagementDocTitle}_.
endif::[]
ifdef::satellite[]
* Optional: If you want to register hosts to Red{nbsp}Hat Insights, you must synchronize the `{RepoRHEL8BaseOS}` and `{RepoRHEL8AppStream}` repositories and make them available in the activation key that you use.
This is required to install the `insights-client` package on hosts.
endif::[]
ifdef::katello,orcharhino,satellite[]
include::snip_prerequisite-project-client-repository-ak.adoc[]
This repository is required for the remote execution pull client, Puppet agent, Tracer, and other tools.
endif::[]
include::snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc[]
ifdef::katello,orcharhino,satellite[]
* If your {ProjectServer} or {SmartProxyServer} is behind an HTTP proxy, configure the Subscription Manager on your host to use the HTTP proxy for connection.
endif::[]
ifdef::satellite[]
For more information, see https://access.redhat.com/solutions/65300[How to access Red Hat Subscription Manager (RHSM) through a firewall or proxy] in the _Red{nbsp}Hat Knowledgebase_.
endif::[]
ifdef::orcharhino[]
ifdef::debian[]
* Ensure that your host has `gpg` installed to import the GPG public key.
endif::[]
endif::[]
ifndef::satellite[]
* You have configured the operating system entry on {Project} for {client-os}.
endif::[]
ifdef::orcharhino[]
+
include::snip_creating-os-on-orcharhino.adoc[]
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Register Host*.
. Enter the details for how you want the registered hosts to be configured.
ifdef::katello,satellite,orcharhino[]
. On the *General* tab, in the *Activation Keys* field, enter one or more activation keys to assign to hosts.
endif::[]
. Click *Generate* to generate a `curl` command.
. Run the `curl` command as `root` on the host that you want to register.
After registration completes, any Ansible roles assigned to a host group you specified when configuring the registration template will run on the host.

The registration details that you can specify include the following:

* On the *General* tab, in the *{SmartProxy}* field, you can select the {SmartProxy} to register hosts through.
A {SmartProxy} behind a load balancer takes precedence over a {SmartProxy} selected in the {ProjectWebUI} as the content source of the host.
* On the *General* tab, you can select the *Insecure* option to make the first call insecure.
During this first call, the host downloads the CA file from {Project}.
The host will use this CA file to connect to {Project} with all future calls making them secure.
+
{Team} recommends that you avoid insecure calls.
+
If an attacker, located in the network between {Project} and a host, fetches the CA file from the first insecure call, the attacker will be able to access the content of the API calls to and from the registered host and the JSON Web Tokens (JWT).
Therefore, if you have chosen to deploy SSH keys during registration, the attacker will be able to access the host using the SSH key.
* On the *Advanced* tab, in the *Repositories* field, you can list repositories to be added before the registration is performed.
You do not have to specify repositories if you provide them in an activation key.
* On the *Advanced* tab, in the *Token lifetime (hours)* field, you can change the validity duration of the JSON Web Token (JWT) that {Project} uses for authentication.
The duration of this token defines how long the generated `curl` command works.
+
Note that {Project} applies the permissions of the user who generates the `curl` command to authorization of hosts.
If the user loses or gains additional permissions, the permissions of the JWT change too.
Therefore, do not delete, block, or change permissions of the user during the token duration.
+
The scope of the JWTs is limited to the registration endpoints only and cannot be used anywhere else.

.CLI procedure
. Use the `hammer host-registration generate-command` to generate the `curl` command to register the host.
. On the host that you want to register, run the `curl` command as `root`.

For more information, see the Hammer CLI help with `hammer host-registration generate-command --help`.

.Ansible procedure
* Use the `{ansible-namespace}.registration_command` module.

For more information, see the Ansible module documentation with `ansible-doc {ansible-namespace}.registration_command`.

.API procedure
* Use the `POST /api/registration_commands` resource.

For more information, see the full API reference at `\https://{foreman-example-com}/apidoc/v2.html`.
