[id="Exporting_the_Library_Environment_in_a_Syncable_Format_{context}"]
= Exporting the Library Environment in a Syncable Format

You can export contents of all yum repositories, Kickstart repositories and file repositories in the Library environment of an organization to a syncable format that you can use to create your custom CDN and synchronize the content from the custom CDN over HTTP/HTTPS.

ifdef::satellite[]
You can then serve the generated content via a local webserver on the importing  {ProjectServer} or in another {ProjectServer} organization.

You cannot directly import Syncable Format exports.
Instead on the importing {ProjectServer} you must:

* Copy the generated content to an HTTP/HTTPS webserver that is accessible to importing {ProjectServer}.
* Update your CDN configuration to *Custom CDN*.
* Set the CDN URL to point to the web server.
* Optional: Set an SSL CA Credential if the web server requires it.
* Enable the Repository.
* Synchronize the Repository.
endif::[]

ifndef::satellite[]
You can use the generated content to create the same repositories in another {ProjectServer} or in another {ProjectServer} organization via content import.
On import, the products and repositories are mirrored on your downstream {ProjectServer}.
endif::[]

You can export the following content in a syncable format from {ProjectServer}:

* RPM repositories
* Kickstart repositories
* File repositories

You cannot export Ansible and Docker content.

ifndef::satellite[]
You cannot export DEB repositories from {ProjectServer}.
endif::[]

The export contains the following data:

Directories containing the RPMs, *listing* files and metadata of each repository in yum format that can be used to synchronize in the importing {ProjectServer}.

.Prerequisites

* Ensure that you set the download policy to *Immediate* for all repositories within the Library lifecycle environment you export.
For more information, see xref:Download_Policies_Overview_{context}[].
* Ensure that you synchronize products you export to the required date.
* Ensure that the user exporting the content has the `Content Exporter` role.

.Procedure
. Use the organization name or ID to export:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-export complete library \
--organization="_My_Organization_" \
--format=syncable
----
. Optional: Verify that the exported content is located in the export directory:
+
[options="nowrap" subs="+quotes"]
----
# du -sh /var/lib/pulp/exports/_My_Organization_/Export-_My_Repository_/1.0/2021-03-02T03-35-24-00-00
----
