[id="Searching_Compliance_Reports_{context}"]
= Searching Compliance Reports

Use the Compliance Reports search field to filter the list of available reports on any given subset of hosts.

.Procedure
* To apply a filter, enter the search query in the *Search* field and click *Search*.
The search query is case insensitive.

.Search Use Cases
* The following search query finds all compliance reports for which more than five rules failed:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
failed > 5
----
* The following search query finds all compliance reports created after January 1, _YYYY_, for hosts with host names that contain the `prod-` group of characters:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
host ~ prod- AND date > "Jan 1, _YYYY_"
----
* The following search query finds all reports generated by the `rhel7_audit` compliance policy from an hour ago:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
"1 hour ago" AND compliance_policy = date = "1 hour ago" AND compliance_policy = rhel7_audit
----
* The following search query finds reports that pass an XCCDF rule:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
xccdf_rule_passed = xccdf_org.ssgproject.content_rule_firefox_preferences-auto-download_actions
----
* The following search query finds reports that fail an XCCDF rule:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
xccdf_rule_failed = xccdf_org.ssgproject.content_rule_firefox_preferences-auto-download_actions
----
* The following search query finds reports that have a result different than fail or pass for an XCCDF rule:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
xccdf_rule_othered = xccdf_org.ssgproject.content_rule_firefox_preferences-auto-download_actions
----

.Additional Information
* To see a list of available search parameters, click the empty *Search* field.
* You can create complex queries with the following logical operators: `and`, `not` and `has`.
For more information about logical operators, see xref:Supported_Operators_for_Granular_Search_{context}[].
* You cannot use regular expressions in a search query.
However, you can use multiple fields in a single search expression.
For more information about all available search operators, see xref:Supported_Operators_for_Granular_Search_{context}[].
* You can bookmark a search to reuse the same search query.
For more information, see xref:Creating_Bookmarks_{context}[].
