[id="using-ansible-vault-with-{project-context}_{context}"]
= Using Ansible Vault with {Project}

You can encrypt sensitive Ansible data files using the Ansible Vault tool and configure Ansible to access the encrypted files using a password stored in a file.

.Procedure
. If you customized `/etc/ansible/ansible.cfg`, copy your configuration from `/etc/ansible/ansible.cfg` to `/usr/share/foreman-proxy/.ansible.cfg`.
. Encrypt the sensitive file using the `ansible-vault` command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ansible-vault encrypt /etc/ansible/roles/_Role_Name_/vars/main.yml
----
+
Note that `ansible-vault` changes the file permissions to `600`.
. Change the group and permissions of the encrypted file to ensure that the `foreman-proxy` user can read it:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# chgrp foreman-proxy /etc/ansible/roles/_Role_Name_/vars/main.yml
# chmod 0640 /etc/ansible/roles/_Role_Name_/vars/main.yml
----
. Create the `/usr/share/foreman-proxy/.ansible_vault_password` file and enter the Vault password into it.
. Change the user and permissions of the `.ansible_vault_password` file to ensure that only the `foreman-proxy` user can read it:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# chown foreman-proxy:foreman-proxy /usr/share/foreman-proxy/.ansible_vault_password
# chmod 0400 /usr/share/foreman-proxy/.ansible_vault_password
----
. Add the path of the Vault password file to the `[defaults]` section in `/usr/share/foreman-proxy/.ansible.cfg`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
[defaults]
vault_password_file = /usr/share/foreman-proxy/.ansible_vault_password
----
+
The path to the Vault password file must be absolute.
