:_mod-docs-content-type: PROCEDURE

[id="creating-an-installation-medium-for-ubuntu-22-04"]
= Creating an installation medium for Ubuntu 22.04

[role="_abstract"]
To provision Ubuntu 22.04, you need to provide both the ISO image and the extracted ISO image on your {ProjectServer}.

:iso_image: ubuntu-22.04.3-live-server-amd64.iso

.Procedure
. Connect to your {ProjectServer} using SSH:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ssh root@{foreman-example-com}
----
. Download the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cd /tmp/
# wget https://releases.ubuntu.com/22.04/{iso_image}
----
. Mount the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mount {iso_image} /mnt
----
. Provide the ISO image and the extracted directory under _{foreman-example-com}/pub_:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /var/www/html/pub/installation_media/ubuntu/22.04-x86_64/
# cp {iso_image} /var/www/html/pub/installation_media/ubuntu/22.04-x86_64.iso
# cp -a /mnt/* /var/www/html/pub/installation_media/ubuntu/22.04-x86_64/
----
+
Ensure the path in `/pub/` matches the path in your _Preseed default PXELinux Autoinstall_ template.
. Unmount and delete the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# umount /mnt/
# rm -f {iso_image}
----
+
[TIP]
====
If you manage this with Puppet or a similar configuration management system, you can take an alternative approach.
Instead of copying the ISO image content, you can create a symbolic link at `/var/www/html/pub/installation_media/ubuntu/22.04-x86_64` that points to the mounted image.
Keep the ISO image mounted so that it is accessible to HTTP clients.

Do not mount the ISO image directly under `/var/lib/foreman`.
On Debian and Ubuntu, mounting under this directory causes the package `postinst` script to fail during the `chmod -Rf /var/lib/foreman` command.
====
+
Use `\http://{foreman-example-com}/pub/installation_media/ubuntu/22.04-x86_64/` to set up your installation media entry in {Project}.
For more information, see xref:adding-installation-media-by-using-web-ui[].
