:_mod-docs-content-type: PROCEDURE

[id="creating-a-content-view-by-using-cli"]
= Creating a content view by using Hammer CLI

[role="_abstract"]
Use this procedure to create a content view by using Hammer CLI.

ifdef::katello,satellite,almalinux,amazon_linux,centos,oracle_linux,red_hat_enterprise_linux,rocky_linux,suse_linux_enterprise_server[]
While you can stipulate whether you want to resolve any package dependencies on a content view by content view basis, you might want to change the default {Project} settings to enable or disable package resolution for all content views.
For more information, see xref:dependency-solving-for-content-views[].
endif::[]

.Procedure
. Obtain a list of repository IDs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer repository list --organization "_My_Organization_"
----
. Create the content view and add repositories:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer content-view create \
--description "_My_Content_View_" \
--name "_My_Content_View_" \
--organization "_My_Organization_" \
--repository-ids _My_Repository_ID_1_,_My_Repository_ID_2_
----
. Optional: Add another repository to your content view:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer content-view add-repository \
--name "_My_Content_View_" \
--organization "_My_Organization_" \
--repository-id _My_Repository_ID_3_
----
. Publish the content view:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer content-view publish \
--description "_My_Content_View_" \
--name "_My_Content_View_" \
--organization "_My_Organization_"
----
+
{ProjectServer} creates the new version of the view and publishes it to the Library environment.
