[id="Assigning_a_Tailoring_File_to_a_Policy_{context}"]
= Assigning a Tailoring File to a Policy

In the {ProjectWebUI}, assign a Tailoring file to a policy.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Compliance {endash} Policies*.
. Click *New Policy*, or *New Compliance Policy* if there are existing Compliance Policies.
. Enter a name in the *Name* text box, and click *Next*.
. Select a *Scap content* from the dropdown menu.
. Select a *XCCDF Profile* from the dropdown menu.
. Select a *Tailoring File* from the dropdown menu.
. Select a *XCCDF Profile in Tailoring File* from the dropdown menu.
+
It is important to select the XCCDF Profile because Tailoring Files are able to contain multiple XCCDF Profiles.
. Click *Next*.
. Select a *Period* from the dropdown menu.
. Select a *Weekday* from the dropdown menu, and click *Next*.
. Select a *Location* to move it to the *Selected Items* window, and click *Next*.
. Select an *Organization* to move it to the *Selected Items* window, and click *Next*.
. Select a *Hostgroup* to move it to the *Selected Items* window, and click *Submit*.
