:_mod-docs-content-type: PROCEDURE

[id="Updating_and_Refreshing_Red_Hat_Subscription_Manifests_{context}"]
= Updating and refreshing Red Hat subscription manifests

[role="_abstract"]
Every time that you change a subscription allocation, you must refresh the manifest to reflect these changes.
For example, you must refresh the manifest if you take any of the following actions:

* Renewing a subscription
* Adjusting subscription quantities
* Purchasing additional subscriptions

You can refresh the manifest directly in the {ProjectWebUI}.
Alternatively, you can import an updated manifest that contains the changes.

The {ProjectWebUI} provides a notification before the subscription manifest expires.

.Procedure
. In the {ProjectWebUI}, ensure the context is set to the organization you want to use.
. In the {ProjectWebUI}, navigate to *Content* > *Subscriptions*.
. In the Subscriptions window, click *Manage Manifest*.
. In the Manage Manifest window, click *Refresh*.

ifdef::satellite[]
.Additional resources
* https://access.redhat.com/solutions/11101[How and when does a Red Hat Satellite manifest certificate expire?]
endif::[]
