:_mod-docs-content-type: PROCEDURE

[id="importing-red-hat-subscription-manifest-by-using-cli"]
= Importing Red Hat subscription manifest by using Hammer CLI

[role="_abstract"]
You can import a Red{nbsp}Hat subscription manifest into {ProjectServer} by using Hammer CLI.

.Prerequisites
* You must have a Red{nbsp}Hat subscription manifest file.
For more information, see xref:Importing_a_Red_Hat_Subscription_Manifest_into_Server_{context}[].

.Procedure
. Copy the Red{nbsp}Hat subscription manifest file from your local machine to {ProjectServer}:
+
[subs="+quotes,attributes"]
----
$ scp ~/_manifest_file_.zip root@_{foreman-example-com}_:~/.
----
. Log in to {ProjectServer} over SSH as the `root` user.
. Import the Red{nbsp}Hat subscription manifest file:
+
[subs="+quotes"]
----
$ hammer subscription upload \
--file ~/_manifest_file_.zip \
--organization "_My_Organization_"
----

.Next steps
* You can now enable and synchronize Red{nbsp}Hat repositories.
For more information, see {ContentManagementDocURL}Importing_Content_content-management[Importing content] in _{ContentManagementDocTitle}_.
