[id="Downloading_Files_to_a_Host_from_a_{custompythontypeid}_Repository_{context}"]
= Downloading Files to a Host From a {custompythontypetitle} Repository

You can download files to a client over HTTPS using `curl -O`, and optionally over HTTP if the *Unprotected* option for repositories is selected.

.Prerequisites
* You have a {custompythontype} repository.
* You know the name of the python package you want to download to clients from the {custompythontype} repository.
* To download the python packages over HTTPS to your managed hosts, you require:
+
. The `katello-server-ca.crt`.
For more information, see {AdministeringDocURL}Importing_the_Katello_Root_CA_Certificate_admin[Importing the Katello Root CA Certificate] in _{AdministeringDocTitle}_.
. An Organization Debug Certificate.
For more information, see {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate] in _{ManagingOrganizationsLocationsDocTitle}_.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select a {customproduct} by name.
. Select a `python` type repository by name.
. Optional: Select the *Unprotected* checkbox to access the repository published through HTTP.
. Copy the *Published At* URL.

.CLI procedure
. List all `file` type repositories:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository list --content-type python
----
. View the repository information:
+
[options="nowrap",subs="+quotes"]
----
# hammer repository info \
--name "_My_{custompythonrepoid}_" \
--organization-id _My_Organization_ID_ \
--product "_My_{customproductid}_"
----
. On your client, download a file from your {custompythonrepo}:
+
For HTTPS:
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -O --cert _./_My-Organization_-key-cert.pem_ --cacert katello-server-ca.crt https://_{foreman-example-com}_/pulp/content/_My_Organization_Label_/Library/custom/_My_File_Product_Label_/_My_Files_Label_/_My_File_
----
+
For HTTP:
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -O http://_{foreman-example-com}_/pulp/content/_My_Organization_Label_/Library/custom/_My_File_Product_Label_/_My_Files_Label_/_My_File_
----
