:_mod-docs-content-type: PROCEDURE

[id="enabling-{insights-iop-id}"]
= Enabling {insights-iop}

[role="_abstract"]
If you have previously disabled {insights-iop}, you can re-enable it.

If you need to enable {insights-iop} for the first time, see the installation instructions in the additional resources.

.Prerequisites
* {insights-iop} is disabled on your {ProjectServer}.
* {insights-iop} was previously enabled on your {ProjectServer}.

.Procedure
* On {ProjectServer}, re-enable {insights-iop}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --iop-ensure present
----

.Verification
* TODO: Add verification steps

.Next steps
* Run `insights-client` on your hosts to start reporting to {Project}.

.Additional resources
* {InstallingServerDocURL}installing-and-configuring-{insights-iop-id}[Installing and configuring {insights-iop} in _{InstallingServerDocTitle}_]
* {InstallingServerDisconnectedDocURL}installing-and-configuring-{insights-iop-id}[Installing and configuring {insights-iop} in _{InstallingServerDisconnectedDocTitle}_]
