:_mod-docs-content-type: PROCEDURE

[id="updating-insights-iop-container-images"]
= Updating {insights-iop} container images

[role="_abstract"]
If you have {insights-iop} enabled on your {ProjectServer}, prepare the {insights-iop} container images for {Project} {ProjectVersion} and load them on the disconnected server before running the upgrade.

.Prerequisites
* {insights-iop} is enabled on your disconnected {ProjectServer}.
* You know which method you used for the initial installation of {insights-iop}: the ISO image method or the export and import method.

.Procedure
* If you used the ISO image method for the initial installation of {insights-iop}, update the {insights-iop} container images from the ISO image for {ProjectVersion}:
.. Download and mount the {Project} installation ISO.
For more information, see {InstallingServerDisconnectedDocURL}installing-from-the-offline-repositories_{context}[Installing the {Project} packages from the offline repositories] in _{InstallingServerDisconnectedDocTitle}_.
.. Set up the local repositories for disconnected environments.
For more information, see {InstallingServerDisconnectedDocURL}installing-from-the-offline-repositories_{context}[Installing the {Project} packages from the offline repositories] in _{InstallingServerDisconnectedDocTitle}_.
.. Run the container setup script from the mounted ISO so that the {insights-iop} images for {ProjectVersion} are loaded:
+
[options="nowrap"]
----
# /media/sat6/setup_containers
----
* If you used the export and import method for the initial installation of {insights-iop}, update the {insights-iop} container images from the exported archive files:
.. On a connected system, log in to the container registry:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ skopeo login --username _My_Username_ --password _My_Password_ registry.redhat.io
----
.. On the connected system, export the container images.
Save the following script to a file and execute it on the connected system so that the {insights-iop} container images for {ProjectVersion} are exported:
+
[bash, options="nowrap", subs="+quotes,verbatim,attributes"]
----
#!/bin/bash

images=(
  "{project-context}/iop-ingress-rhel9:{ProjectVersion}"
  "{project-context}/iop-advisor-frontend-rhel9:{ProjectVersion}"
  "{project-context}/iop-host-inventory-rhel9:{ProjectVersion}"
  "{project-context}/iop-vmaas-rhel9:{ProjectVersion}"
  "{project-context}/iop-remediations-rhel9:{ProjectVersion}"
  "{project-context}/iop-vulnerability-frontend-rhel9:{ProjectVersion}"
  "{project-context}/iop-host-inventory-frontend-rhel9:{ProjectVersion}"
  "{project-context}/iop-advisor-backend-rhel9:{ProjectVersion}"
  "{project-context}/iop-puptoo-rhel9:{ProjectVersion}"
  "{project-context}/iop-yuptoo-rhel9:{ProjectVersion}"
  "{project-context}/iop-insights-engine-rhel9:{ProjectVersion}"
  "{project-context}/iop-vulnerability-engine-rhel9:{ProjectVersion}"
  "{project-context}/iop-gateway-rhel9:{ProjectVersion}"
  "amq-streams/kafka-39-rhel9:2.9.1-1"
)

for image in "${images[@]}"; do
  name=$(basename "$\{image}" | cut -d: -f1)
  image_url="registry.redhat.io/$\{image}"
  echo "Processing $\{image}..."
  # Pull the image
  skopeo copy docker://$\{image_url} containers-storage:$\{image_url}
  # Copy image to archive
  skopeo copy containers-storage:$\{image_url} oci-archive:/tmp/$\{name}.tar
done
----
.. Transfer the archive files from `/tmp` on the connected system to the disconnected {ProjectServer}.
Place the archive files in the `/tmp` directory on the disconnected server.
.. On the disconnected {ProjectServer}, import the container images.
Save the following script to a file and execute it on the disconnected {ProjectServer} so that the {insights-iop} container images for {ProjectVersion} are imported:
+
[bash, options="nowrap", subs="+quotes,verbatim,attributes"]
----
#!/bin/bash

images=(
  "{project-context}/iop-ingress-rhel9:{ProjectVersion}"
  "{project-context}/iop-advisor-frontend-rhel9:{ProjectVersion}"
  "{project-context}/iop-host-inventory-rhel9:{ProjectVersion}"
  "{project-context}/iop-vmaas-rhel9:{ProjectVersion}"
  "{project-context}/iop-remediations-rhel9:{ProjectVersion}"
  "{project-context}/iop-vulnerability-frontend-rhel9:{ProjectVersion}"
  "{project-context}/iop-host-inventory-frontend-rhel9:{ProjectVersion}"
  "{project-context}/iop-advisor-backend-rhel9:{ProjectVersion}"
  "{project-context}/iop-puptoo-rhel9:{ProjectVersion}"
  "{project-context}/iop-yuptoo-rhel9:{ProjectVersion}"
  "{project-context}/iop-insights-engine-rhel9:{ProjectVersion}"
  "{project-context}/iop-vulnerability-engine-rhel9:{ProjectVersion}"
  "{project-context}/iop-gateway-rhel9:{ProjectVersion}"
  "amq-streams/kafka-39-rhel9:2.9.1-1"
)

for image in "${images[@]}"; do
  name=$(basename "$\{image}" | cut -d: -f1)
  image_url="registry.redhat.io/$\{image}"
  echo "Processing $\{image}..."
  # Import the image
  skopeo copy oci-archive:/tmp/$\{name}.tar containers-storage:$\{image_url}
done
----
