:_mod-docs-content-type: PROCEDURE

[id="assign-an-ansible-execution-environment-to-an-ansible-lifecycle-environment-by-using-web-ui"]
= Assign an Ansible Execution Environment to an Ansible lifecycle environment by using {ProjectWebUI}

[role="_abstract"]
You can assign an Ansible Execution Environment to an Ansible lifecycle environment by using {ProjectWebUI}.
Ansible Execution Environments provide the environment to run Ansible to configure hosts.

.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_lifecycle_environment_paths`, `edit_ansible_lifecycle_environment_paths`, `view_ansible_content`, `view_ansible_lifecycle_environment_paths`, `view_ansible_lifecycle_environments`, and `view_organizations` permissions.
* Your {Project} contains an Ansible lifecycle environment path.
* Your {Project} contains an Ansible Execution Environment.

.Procedure
. In the {ProjectWebUI}, navigate to *Ansible* > *Environments*.
. In your Ansible lifecycle environment path, for your Ansible lifecycle environment, click *None* next to *Execution Environment*.
. From the list of Ansible Execution Environments, click *Assign* for the Execution Environment that you want to use for this lifecycle environment.

.Verification
. In the {ProjectWebUI}, navigate to *Ansible* > *Environments*.
. Verify that {Project} shows your newly assigned Ansible Execution Environment for your selected Ansible lifecycle environment.
