:_mod-docs-content-type: PROCEDURE

[id="Restoring_from_Incremental_Backups_{context}"]
= Restoring from incremental backups

[role="_abstract"]
Restore {ProjectServer} or {SmartProxyServer} from an incremental backup to return the system to the state at the time of the backup.
When the restore process completes, all processes are online, and all databases and system configuration revert to the state at the time of the backup.

If you have multiple branches of incremental backups, select your full backup and each incremental backup for the _branch_ you want to restore, in chronological order.

.Prerequisites
ifndef::foreman-deb[]
* If the backed up system had FIPS enabled, the system on which you are restoring must also have FIPS enabled.
endif::[]

.Procedure
. Restore the last full backup using the instructions in xref:Restoring_from_a_Full_Backup_{context}[].
. Remove the full backup data from the local file system on {ProjectServer}, for example, `/var/` or `/var/tmp/`.
. Copy the incremental backup data to the local file system on {ProjectServer}, for example, `/var/` or `/var/tmp/`.
. Restore the incremental backups in the same sequence that they are made:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} restore _/var/backup_directory_/FIRST_INCREMENTAL
# {foreman-maintain} restore _/var/backup_directory_/SECOND_INCREMENTAL
----

.Next steps
* If you create a new instance of {ProjectServer} or {SmartProxyServer}, decommission the old instance after restoring the backup.
Cloned instances are not supposed to run in parallel in a production environment.

.Troubleshooting
* Review the `/var/log/foreman/production.log` and `/var/log/messages` log files.
