:_mod-docs-content-type: PROCEDURE

[id="creating-hosts-with-pxe-boot-provisioning-by-using-cli"]
= Creating hosts with PXE boot provisioning by using Hammer CLI

[role="_abstract"]
PXE boot provisioning is a method of unattended host provisioning that requires minimal interaction during the process.

You enter the host details on {ProjectServer} and boot your host.
{ProjectServer} automatically manages the PXE configuration, organizes networking services, and provides the operating system and configuration for the host.

Create a host entry to add the host details.
When you save the host entry, {Project} creates the relevant provisioning settings.
This also includes creating the necessary directories and files for PXE booting.
When you boot the host, the host requests a DHCP lease.
The DHCP service responds with a lease which includes the location of the installation content.
The host uses the installation content to install the operating system.

ifdef::katello,satellite,orcharhino[]
During the installation, the host registers to {ProjectServer} by using the activation key, installs the necessary host management tools from the {project-client-name} repository, and performs initial configuration.
endif::[]
ifndef::katello,satellite,orcharhino[]
During the installation, the host registers to {ProjectServer} and performs initial configuration.
endif::[]

.Procedure
. Create the host:
+
[options="nowrap" subs="+quotes"]
----
$ hammer host create \
--build true \
--enabled true \
--hostgroup "_My_Host_Group_" \
--location "_My_Location_" \
--mac "_My_MAC_Address_" \
--managed true \
--name "_My_Host_Name_" \
--organization "_My_Organization_"
----
. Configure the network interface:
+
----
$ hammer host interface update \
--host "_My_Host_Name_" \
--managed true \
--primary true \
--provision true
----
