[id="Creating_an_Activation_Key_{context}"]
= Creating an activation key

Activation key attaches subscriptions automatically.

. Activation key providing a custom set of subscription for auto-attach.
If there are subscriptions specified and auto-attach is enabled, hosts using the activation key select the best fitting subscription from the list specified in the activation key.
Setting system purpose on the activation key does not affect this scenario.
. Activation key with the exact set of subscriptions.
If there are subscriptions specified and auto-attach is disabled, hosts using the activation key are associated with all subscriptions specified in the activation key.
Setting system purpose on the activation key does not affect this scenario.

.Custom Products
If a {customproduct}, typically containing content not provided by Red Hat, is assigned to an activation key, this product is always enabled for the registered content host regardless of the auto-attach setting.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-an-activation-key_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Activation Keys* and click *Create Activation Key*.
. In the *Name* field, enter the name of the activation key.
. If you want to set a limit, clear the *Unlimited hosts* checkbox, and in the *Limit* field, enter the maximum number of systems you can register with the activation key.
If you want unlimited hosts to register with the activation key, ensure the *Unlimited Hosts* checkbox is selected.
. Optional: In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the environment to use.
. From the *Content View* list, select a content view to use.
ifndef::orcharhino[]
. In the *Repository Sets* tab, ensure only your named repository is enabled.
endif::[]
. Click *Save*.
. Optional: In the *System Purpose* section, you can configure the activation key with system purpose to set on hosts during registration.
You can configure the activation key to set system purpose attributes on hosts during registration.
This can help determine which repositories are available on the host, and also helps with reporting in the Subscriptions service of the Red Hat Hybrid Cloud Console.

[id="cli-creating-an-activation-key_{context}"]
.CLI procedure
. Create the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key create \
--name "_My_Activation_Key_" \
--unlimited-hosts \
--description "_Example Stack in the Development Environment_" \
--lifecycle-environment "_Development_" \
--content-view "_Stack_" \
--organization "_My_Organization_"
----
. Optional: For {RHEL} 8 hosts, enter the following command to configure the activation key with system purpose to set on hosts during registration to enhance subscriptions auto attachment.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key update \
--organization "_My_Organization_" \
--name "_My_Activation_Key_" \
--service-level "_Standard_" \
--purpose-usage "_Development/Test_" \
--purpose-role "_{RHELServer}_" \
--purpose-addons "_addons_"
----
. Obtain a list of your subscription IDs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer subscription list --organization "_My_Organization_"
----
. Attach the {RHEL} subscription UUID to the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key add-subscription \
--name "_My_Activation_Key_" \
--subscription-id _My_Subscription_ID_ \
--organization "_My_Organization_"
----
. List the product content associated with the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key product-content \
--content-access-mode-all true \
--name "_My_Activation_Key_" \
--organization "_My_Organization_"
----
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key product-content \
--name "_My_Activation_Key_" \
--organization "_My_Organization_"
----
. Override the default auto-enable status for the {project-client-name} repository.
The default status is set to disabled.
To enable, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key content-override \
--name "_My_Activation_Key_" \
--content-label {project-client-RHEL7-url} \
--value 1 \
--organization "_My_Organization_"
----
