[id="Viewing_Compliance_Policy_Statistics_{context}"]
= Viewing Compliance Policy Statistics

You can view a compliance policy dashboard to verify compliance reports of a particular policy.
The compliance policy dashboard provides a statistical summary of compliance of hosts and the ability to view report details for each host within the scope of that policy.

Consider prioritizing the following hosts when viewing compliance reports:

* Hosts which were evaluated as `Failed`
* Hosts labelled as `Never audited` because their status is unknown

The dashboard provides the following information:

* A ring chart illustrating a high-level view of compliance of hosts with the policy.
* A statistical breakdown of compliance of hosts with the policy, in a tabular format.
* Links to the latest policy report for each host.

.Prerequisite
* Your user account has the `view_policies` permission.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Policies*.
. In the row of the required policy, navigate to the *Actions* column and click *Dashboard*.
