:_mod-docs-content-type: PROCEDURE

[id="Managing_Container_Name_Patterns_{context}"]
= Managing container name patterns

[role="_abstract"]
Configure registry name patterns to override default container naming conventions and prevent conflicts when pulling container images.
Custom name patterns ensure globally unique container names across lifecycle environments and content views.

[WARNING]
====
Proceed with caution when defining registry naming patterns for your containers.

If you use a registry name pattern to manage container naming conventions, because registry naming patterns must generate globally unique names, you might experience naming conflict problems.
For example:

* If you set the `repository.docker_upstream_name` registry name pattern, you cannot publish or promote content views with container content with identical repository names to the `Production` lifecycle.
* If you set the `lifecycle_environment.name` registry name pattern, this can prevent the creation of a second container repository with the identical name.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Lifecycle Environments*.
. Create a lifecycle environment or select an existing lifecycle environment to edit.
. In the *Container Image Registry* area, click the edit icon to the right of *Registry Name Pattern* area.
. Use the list of variables and examples to determine which registry name pattern you require.
. In the *Registry Name Pattern* field, enter the registry name pattern that you want to use.
For example, to use the `repository.docker_upstream_name`:
+
----
<%= repository.docker_upstream_name %>
----
+
. Click *Save*.
