:_mod-docs-content-type: PROCEDURE

[id="connecting-the-mcp-client-to-the-mcp-server"]
= Connecting the MCP client to the MCP server

[role="_abstract"]
Connect your MCP client to the MCP server.

Perform these steps on the same system where you initiated the MCP server.

.Prerequisites
* Your MCP client must support setting custom HTTP headers.
* You have a personal access token (PAT).
+
[NOTE]
====
{Team} recommends to set an expiration date for a PAT used to configure the MCP client.
====

.Procedure
* Configure your client to pass credentials in an HTTP authorization request header.
The exact configuration steps depend on your MCP client.
+
For example, some clients require you to create a configuration file with the following contents:
+
[options="nowrap", subs="+quotes,attributes"]
----
"my-mcp-server": {
	"url": "http://localhost:8080/mcp/sse",
	"type": "http",
	"headers": {
		"FOREMAN_USERNAME": "_My_Username_",
		"FOREMAN_TOKEN": "_My_PAT_"
	}
}
----

.Additional resources
* {APIDocURL}creating-a-personal-access-token_rest-api[Creating a Personal Access Token in _{APIDocTitle}_]
