:_mod-docs-content-type: PROCEDURE

[id="Restoring_from_a_Full_Backup_{context}"]
= Restoring from a full backup

[role="_abstract"]
Restore {ProjectName} or {SmartProxyServer} from a full backup return the system to the state at the time of the backup.
When the restore process completes, all processes are online, and all databases and system configuration revert to the state at the time of the backup.

.Prerequisites
* Your {ProjectServer} must have the same host name, configuration, and be the same minor version (X.Y) as the original system.
* The target directory must exist and be writable.
The target directory is read from the configuration files contained within the backup archive.
ifndef::foreman-deb[]
* If the backed up system had FIPS enabled, the system on which you are restoring must also be FIPS enabled.
endif::[]

.Procedure
. Ensure that you have enough space to store the backup data on the base system of {ProjectServer} or {SmartProxyServer} as well as enough space after the restoration to contain all the data in the `/etc/` and `/var/` directories contained within the backup.
+
To check the space used by a directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# du -sh _/var/backup_directory_
----
+
To check for free space:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# df -h _/var/backup_directory_
----
+
Add the ``--total`` option to get a total of the results from more than one directory.
ifndef::foreman-deb[]
. Restore the correct SELinux contexts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# restorecon -Rv /
----
endif::[]
. Choose the appropriate method to install {Project} or {SmartProxy}:
** To install {ProjectServer} from a connected network, follow the procedures in {InstallingServerDocURL}[{InstallingServerDocTitle}].
ifdef::satellite[]
+
If you have used {insights-iop}, enable it.
For more information, see {InstallingServerDocURL}installing-and-configuring-{insights-iop-id}[Installing and configuring {insights-iop}].
** To install {ProjectServer} from a disconnected network, follow the procedures in {InstallingServerDisconnectedDocURL}[{InstallingServerDisconnectedDocTitle}].
+
If you have used {insights-iop}, enable it.
For more information, see {InstallingServerDisconnectedDocURL}installing-and-configuring-{insights-iop-id}[Installing and configuring {insights-iop}].
endif::[]
** To install a {SmartProxyServer}, follow the procedures in {InstallingSmartProxyDocURL}[{InstallingSmartProxyDocTitle}].
. Copy the backup data to the local file system on {ProjectServer}.
Use `/var/` or `/var/tmp/`.
. Run the restoration script.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} restore __/var/backup_directory__
----
+
Where _backup_directory_ is the time-stamped directory or subdirectory containing the backed-up data.
+
The restore process can take a long time to complete, because of the amount of data to copy.

.Next steps
* If you create a new instance of {ProjectServer} or {SmartProxyServer}, decommission the old instance after restoring the backup.
Cloned instances are not supposed to run in parallel in a production environment.

.Troubleshooting
* Review the `/var/log/foreman/production.log` and `/var/log/messages` log files.
