:_mod-docs-content-type: PROCEDURE

[id="configuring-selinux-to-ensure-access-to-{project-context}-on-custom-ports"]
= Configuring SELinux to ensure access to {Project} on custom ports

ifdef::satellite[]
SELinux ensures access of {ProjectName} and Subscription Manager only to specific ports.
In the case of the HTTP cache, the TCP ports are 8080, 8118, 8123, and 10001{range}10010.
If you use a port that does not have SELinux type `http_cache_port_t`, complete the following steps.
endif::[]

ifdef::foreman-el,katello[]
SELinux ensures access of {ProjectName} only to specific ports.
In the case of the HTTP cache, the TCP ports are 8080, 8118, 8123, and 10001{range}10010.
If you use a port that does not have SELinux type `http_cache_port_t`, complete the following steps.
endif::[]

.Procedure
. On {Project}, verify the ports that are permitted by SELinux for the HTTP cache:
+
[options="nowrap",subs="+quotes"]
----
# semanage port -l | grep http_cache
----
+
The output should contain a line similar to the following:
+
[source, none, options="nowrap",subs="+quotes"]
----
http_cache_port_t       tcp    8080, 8118, 8123, 10001-10010
----
. To configure SELinux to permit a port for the HTTP cache, for example 8088, enter a command as follows:
+
[options="nowrap",subs="+quotes"]
----
# semanage port -a -t http_cache_port_t -p tcp 8088
----
