:_mod-docs-content-type: PROCEDURE

[id="Resetting_the_Administrative_User_Password_{context}"]
= Resetting the administrative user password

[role="_abstract"]
You can reset the administrative password to randomly generated characters or set a new administrative password for a specific user.
This might be useful when you forget the password, when the administrative user is deleted, or for assigning administrative privileges to a user.

.Procedure
. Log in to the base operating system where your {ProjectServer} is installed.
. Reset the administrative user password:
* To set a randomly generated administrative user password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake permissions:reset
Reset to user: admin, password: qwJxBptxb7Gfcjj5
----
* To set a new administrative user password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake permissions:reset username=_My_User_Name_ password=_My_New_Password_
----
+
Replace `_My_User_Name_` with the username of the user whose password you want to reset.
+
[NOTE]
====
Be aware of the following behaviors:

* If you enter a username that does not exist, the `foreman-rake` utility creates a new administrative user with the defined password.
* If you enter a username of a user without administrative privileges, that user gains administrative privileges.
* If you do not enter a username, the password resets for the `admin` user by default.
====
. To use the new password with the Hammer CLI, add the password and username to the `~/.hammer/cli.modules.d/foreman.yml` file on your {ProjectServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# vi ~/.hammer/cli.modules.d/foreman.yml
----

.Verification
* Use the new password to log in to the {ProjectWebUI}.
