:_mod-docs-content-type: PROCEDURE

[id="Monitoring_Puppet_{context}"]
= Monitoring Puppet

[role="_abstract"]
You can monitor Puppet activity and certificate management through the Smart Proxy interface.
This helps you verify that Puppet services run correctly and troubleshoot any issues.

[NOTE]
====
The *Puppet* and *Puppet CA* tabs are available only if you have Puppet enabled in your {Project}.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}* and click the name of the selected {SmartProxy}.
* At the *Puppet* tab you can find the following:
** A summary of Puppet events, an overview of latest Puppet runs, and the synchronization status of associated hosts at the *General* sub-tab.
** A list of Puppet environments at the *Environments* sub-tab.
* At the *Puppet CA* tab you can find the following:
** A certificate status overview and the number of autosign entries at the *General* sub-tab.
** A table of CA certificates associated with the {SmartProxy} at the *Certificates* sub-tab.
Here you can inspect the certificate expiry data, or cancel the certificate by clicking *Revoke*.
** A list of autosign entries at the *Autosign entries* sub-tab.
Here you can create an entry by clicking *New* or delete one by clicking *Delete*.

.Additional resources
* {ManagingConfigurationsPuppetDocURL}Enabling_Puppet_Integration_managing-configurations-puppet[Enabling Puppet Integration with {Project} in _{ManagingConfigurationsPuppetDocTitle}_]
