[id="Editing_the_System_Purpose_of_a_Host_{context}"]
= Editing the System Purpose of a Host

You can edit the system purpose attributes for a {RHEL} host.
System purpose allows you to set the intended use of a system on your network and improves reporting accuracy in the Subscriptions service of the Red Hat Hybrid Cloud Console.
ifndef::orcharhino[]
For more information about system purpose, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/graphical-installation_graphical-installation?extIdCarryOver=true&sc_cid=701f2000001Css5AAC#system_purposes-adoc_connect-to-red-hat[Introduction to System Purpose] in _Performing a standard RHEL 8 installation_.
endif::[]

.Prerequisites
* The host that you want to edit must be registered with the subscription-manager.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Click the name of the host you want to modify.
. On the *Overview* tab, click *Edit* on the *System purpose* card.
. Select the system purpose attributes for your host.
. Click *Save*.
// Is there a way to auto-attach subscriptions here?

.CLI procedure
. Log in to the host and edit the required system purpose attributes.
For example, set the usage type to `Production`, the role to `{RHELServer}`, and add the `addon` add on.
ifndef::orcharhino[]
For the list of values, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/graphical-installation_graphical-installation?extIdCarryOver=true&sc_cid=701f2000001Css5AAC#system_purposes-adoc_connect-to-red-hat[Introduction to System Purpose] in  _Performing a standard RHEL 8 installation_.
endif::[]
+
[subs="+quotes"]
----
# subscription-manager syspurpose set usage '_Production_'
# subscription-manager syspurpose set role '_Red Hat Enterprise Linux Server_'
# subscription-manager syspurpose add addons '_your_addon_'
----
. Verify the system purpose attributes for this host:
+
[subs="+quotes"]
----
# subscription-manager syspurpose
----
. Automatically attach subscriptions to this host:
+
[subs="+quotes"]
----
# subscription-manager attach --auto
----
. Verify the system purpose status for this host:
+
[subs="+quotes"]
----
# subscription-manager status
----
