[id="Viewing_multiple_content_view_environment_activation_keys_{context}"]
= Viewing multiple content view environment activation keys

You can view multiple content view environment activation keys in the {ProjectWebUI} and the Hammer CLI.

.Prerequisites
* Ensure you have activation keys created.
For more information, see xref:Creating_an_Activation_Key_{context}[Creating an activation key].
* Ensure *Allow multiple content views* is set to *yes* in the {ProjectWebUI}.
* In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
* Under the *Content* tab, change the default setting under *Allow multiple content views* to *Yes*. 

Before you view multiple content view environment activation keys in Hammer CLI, you must perform the following steps in the {ProjectWebUI}:

. Navigate to *Content* > *Lifecycle* > *Content Views*.
. Select a content view.
. Click *Publish new version*
. Toggle the *Promote* button to on.
. Select a lifecycle environment from the available promotion paths below to promote a new version to create two new content view enviornments. 
You can select more than one.
. Click *Next*.
. Click *Finish*.
. Navigate to *Content* > *Lifecycle* > *Content Views*.
. Select another content view.
. Click *Publish new version*.
. Toggle the *Promote* button to on.
. Select a lifecycle environment from the available promotion paths below to promote a new version. 
. You can select more than one.
. Click *Next*.
. Click *Finish*

.Procedure
. In the {ProjectwebUI}, navigate to *Content* > *Lifecycle* > *Activation Keys*.      
. Select an activation key.
. Under the *Details* tab, the *Content view environments* are displayed.

[WARNING]
====
This activation key has multiple content view environments which cannot yet be edited in the web UI. 
To change this activation key's content view environments, update the activation key with Hammer.
====

.CLI procedure
. Connect to {ProjectServer} using your SSH. 
. Run the following command to see a list of content view environments:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view-environment list --organization “Default Organization”
----
This displays a list of available content view environments.
+
. Run the following command to create a multiple content view environment activation key:
+
[options="nowrap" subs="+quotes"]
----
$ hammer activation-key create --name ”My_Activation_Key”  - -organization “Default Organization” - -content-view-environments “Content_View_Environment_1”,“Content_View_Environment_2”
----
+
. Run the following command to view multiple content view environment activation key organizations:
+
[options="nowrap" subs="+quotes"]
----
$ hammer activation-key list --organization “Default Organization”
----
The multiple content view activation key organizations are displayed.
+
. Run the following command to view multiple content view environment activation key information:
+
[options="nowrap" subs="+quotes"]
----
$ hammer activation-key info --_”Information_ID”_
----
The information for the activation key is displayed including content view environments.


