:_mod-docs-content-type: PROCEDURE

[id="republishing-repository-metadata-by-using-web-ui"]
= Republishing repository metadata by using {ProjectWebUI}

[role="_abstract"]
Republish repository metadata when published packages do not match repository contents, preferring a complete sync or new content view version when possible.

[WARNING]
====
Use with caution.
{Team} recommends a complete repository sync or publishing a new content view version to repair broken metadata instead.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select the product that includes the repository for which you want to republish metadata.
. On the *Repositories* tab, select a repository.
. To republish metadata for the repository, click *Republish Repository Metadata* from the *Select Action* menu.
+
[NOTE]
====
This action is not available for repositories that use the *Complete Mirroring* policy because the metadata is copied verbatim from the upstream source of the repository.
====
