:_mod-docs-content-type: PROCEDURE

[id="Creating_a_Host_Group_with_Salt_{context}"]
= Creating a host group with Salt

You can create a host group with Salt enabled to bundle provisioning and configuration settings for hosts.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*.
. Click *Create Host Group*.
. Click the *Host Group* tab and select a *Salt Environment* and a *Salt Master*.
. Click the *Salt States* tab and assign *Salt States* to your host group.
ifdef::katello,orcharhino[]
. Click the *Activation Keys* tab and select an activation key containing the Salt Minion client software.
endif::[]
. Click *Submit* to save your host group.

ifdef::katello,orcharhino[]
Hosts deployed using this host group automatically install and configure the required Salt Minion client software and register with your Salt Master.
endif::[]
For more information, see {ManagingHostsDocURL}Working_with_Host_Groups_managing-hosts[Creating a Host Group] _{ManagingHostsDocTitle}_.
