[id="Restoring_from_a_Full_Backup_{context}"]
= Restoring from a Full Backup

Use this procedure to restore {ProjectName} or {SmartProxyServer} from a full backup.
When the restore process completes, all processes are online, and all databases and system configuration revert to the state at the time of the backup.

.Prerequisites
* Ensure that you are restoring to the correct instance.
The {ProjectName} instance must have the same host name, configuration, and be the same minor version (X.Y) as the original system.
* Ensure that you have an existing target directory.
The target directory is read from the configuration files contained within the archive.
* Ensure that you have enough space to store this data on the base system of {ProjectServer} or {SmartProxyServer} as well as enough space after the restoration to contain all the data in the `/etc/` and `/var/` directories contained within the backup.
+
To check the space used by a directory, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# du -sh _/var/backup_directory_
----
+
To check for free space, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# df -h _/var/backup_directory_
----
+
Add the ``--total`` option to get a total of the results from more than one directory.

* Ensure that all SELinux contexts are correct.
Enter the following command to restore the correct SELinux contexts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# restorecon -Rv /
----

.Procedure
. Choose the appropriate method to install {Project} or {SmartProxy}:
** To install {ProjectServer} from a connected network, follow the procedures in {InstallingServerDocURL}[{InstallingServerDocTitle}].
ifdef::satellite[]
** To install {ProjectServer} from a disconnected network, follow the procedures in {InstallingServerDisconnectedDocURL}[{InstallingServerDisconnectedDocTitle}].
endif::[]
** To install a {SmartProxyServer}, follow the procedures in {InstallingSmartProxyDocURL}[{InstallingSmartProxyDocTitle}].
. Copy the backup data to {ProjectServer}’s local file system.
Use `/var/` or `/var/tmp/`.
. Run the restoration script.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} restore __/var/backup_directory__
----
+
Where _backup_directory_ is the time-stamped directory or subdirectory containing the backed-up data.
+
The restore process can take a long time to complete, because of the amount of data to copy.

.Additional Resources
* For troubleshooting, you can check `/var/log/foreman/production.log` and `/var/log/messages`.
