[id="configuring-your-deployment-to-run-Ansible-roles_{context}"]

= Configuring your Deployment to Run Ansible Roles

ifdef::satellite[]
In {Project}, you can import Ansible roles to help with automation of routine tasks.
Ansible is enabled by default on {ProjectServer}.
endif::[]

ifndef::satellite[]
In {Project}, you can import Ansible roles to help with automation of routine tasks.
To enable the Ansible plug-in in {Project}, enter the following command:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-plugin-ansible \
--enable-foreman-proxy-plugin-ansible
----
endif::[]

[id="Ansible-paths_{context}"]
.Ansible paths

{Project} imports and runs Ansible roles from the following paths:

* `/etc/ansible/roles`
* `/usr/share/ansible/roles`
* `/etc/ansible/collections`
* `/usr/share/ansible/collections`

Roles and collections from installed packages are placed under `/usr/share/ansible`.
If you want to add custom roles or collections, place them under `/etc/ansible`.

ifdef::satellite[]
Note that Red{nbsp}Hat provides support only for Ansible roles and collections obtained from Red{nbsp}Hat.
endif::[]

The paths are configured by {Project}.
For more information, see xref:customizing-ansible-configuration_{context}[].

.Procedure
. Add the roles to a directory in an xref:Ansible-paths_{context}[Ansible path] on {ProjectServer} and all {SmartProxyServers} from where you want to use the roles.
If you want to use custom or third party Ansible roles, ensure to configure an external version control system to synchronize roles between {ProjectServer} and {SmartProxyServers}.

. On all {SmartProxyServers} that you want to use to run Ansible roles on hosts, enable the Ansible plug-in:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {installer-scenario-smartproxy} \
--enable-foreman-proxy-plugin-ansible
----

. Distribute SSH keys to enable {SmartProxies} to connect to hosts using SSH.
For more information, see {ManagingHostsDocURL}ssh-keys-for-remote-execution-overview_managing-hosts[Distributing SSH Keys for Remote Execution] in _{ManagingHostsDocTitle}_.
{Project} runs Ansible roles the same way it runs remote execution jobs.

. Import the Ansible roles into {Project}.

. Proceed to xref:using-ansible-roles_{context}[].
