:_mod-docs-content-type: PROCEDURE

[id="importing-an-iso-image-by-using-web-ui"]
= Importing an ISO image by using {ProjectWebUI}

[role="_abstract"]
Use this procedure to manually import ISO images to {ProjectServer} by using {ProjectWebUI}.
However, if the size of the file that you want to upload is larger than 15 MB, you must use the Hammer CLI to upload it to a repository.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products* and click *Create Product*.
. In the *Name* field, enter a name to identify the product.
This name populates the *Label* field.
. Optional: In the *GPG Key* field, enter a GPG Key for the product.
. Optional: From the *Sync Plan* list, select a synchronization plan for the product.
. Optional: In the *Description* field, enter a description of the product.
. Click *Save*.
. In the *Products* window, click the new product and then click *Create Repository*.
. In the *Name* field, enter a name for the repository.
This automatically populates the *Label* field.
. From the *Type* list, select *file*.
. In the *Upstream URL* field, enter the URL of the registry to use as a source.
Add a corresponding user name and password in the *Upstream Username* and *Upstream Password* fields.
. Click *Save*.
. Select the new repository.
. Navigate to *Upload File* and click *Browse*.
. Select the `.iso` file and click *Upload*.
