[id='using-insights-with-server_{context}']
[id='using-insights-with-satellite-server_{context}']
= Using Red{nbsp}Hat Insights with {ProjectServer}

You can use Red{nbsp}Hat Insights to diagnose systems and downtime related to security exploits, performance degradation and stability failures.
You can use the dashboard to quickly identify key risks to stability, security, and performance.
You can sort by category, view details of the impact and resolution, and then determine what systems are affected.

Note that you do not require a Red{nbsp}Hat Insights entitlement in your subscription manifest.
For more information about {Project} and Red{nbsp}Hat Insights, see https://access.redhat.com/products/red-hat-insights/#satellite[Red Hat Insights on {Project} {RHEL} (RHEL)].

To maintain your {ProjectServer}, and improve your ability to monitor and diagnose problems you might have with {Project}, install Red{nbsp}Hat Insights on {ProjectServer} and register {ProjectServer} with Red{nbsp}Hat Insights.

.Scheduling insights-client

Note that you can change the default schedule for running `insights-client` by configuring `insights-client.timer` on {Project}.
For more information, see https://access.redhat.com/documentation/en-us/red_hat_insights/2020-10/html/client_configuration_guide_for_red_hat_insights/changing-the-client-schedule[Changing the insights-client schedule] in the _Client Configuration Guide for Red Hat Insights_.

.Procedure

. To install Red{nbsp}Hat Insights on {ProjectServer}, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {project-package-install} insights-client
----
+
. To register {ProjectServer} with Red{nbsp}Hat Insights, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --register-with-insights
----
