[id="remediating-compliance-failures_{context}"]
= Remediating compliance failures

With {Project}, you can examine compliance reports and, in some cases, remediate cases of non-compliance.
You can remediate compliance failures by using a remediation wizard or by applying remediation snippets manually.

[WARNING]
====
Always test the recommended remedial actions or scripts in a non-production environment before implementing them in production.
Remediation might render the system non-functional.
====

.Prerequisites
* Your user account has a role assigned that has the following permissions: `view_arf_reports`, `view_hosts`, `create_job_invocations`

.Procedure
To examine a simplified compliance policy report and run the compliance failure remediation wizard:

. In the {ProjectWebUI}, navigate to *Hosts* > *Compliance* > *Reports*.
. In the *Reported At* column, click the time link of the report you want to examine.
{Project} displays a list of log messages describing the results of the scan.
. Locate a log message that describes a failed compliance check.
In the *Actions* column, select *Remediation* to open the compliance remediation wizard.
Follow the wizard to remediate the compliance failure.
+
The remediation wizard might not be available for all compliance failures.

To examine a full compliance policy report:

. In the {ProjectWebUI}, navigate to *Hosts* > *Compliance* > *Reports* to list all compliance reports.
. In the *Actions* column, click *Full Report*.
{Project} displays the complete details of an evaluation report.
. In the *Rule Overview* section, click the title of a rule in the *Title* column to inspect further result details.
. Click *Remediation Shell script*, *Remediation Ansible snippet*, *Remediation Puppet snippet*, or *Remediation Anaconda snippet* to display remediation advice.
+
Remediation snippets might not be available for all compliance failures.

.Additional resources
* You can apply the remediation snippet by manually configuring a remote job.
For more information, see {ManagingHostsDocURL}Configuring_and_Setting_Up_Remote_Jobs_managing-hosts[Configuring and setting up remote jobs] in _{ManagingHostsDocTitle}_.
