:_mod-docs-content-type: PROCEDURE

[id="adding-a-default-http-proxy-by-using-web-ui"]
= Adding a default HTTP proxy to {Project} by using {ProjectWebUI}

[role="_abstract"]
If your network uses an HTTP Proxy, you can configure {ProjectServer} to use an HTTP proxy for requests to the Red{nbsp}Hat Content Delivery Network (CDN) or another content source.
Use the FQDN instead of the IP address where possible to avoid losing connectivity because of network changes.

The following procedure configures a proxy only for downloading content for {Project}.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *HTTP Proxies*.
. Click *New HTTP Proxy*.
. In the *Name* field, enter the name for the HTTP proxy.
. In the *Url* field, enter the URL of the HTTP proxy in the following format: `\https://http-proxy.example.com:8080`.
. Optional: If authentication is required, in the *Username* field, enter the username to authenticate with.
. Optional: If authentication is required, in the *Password* field, enter the password to authenticate with.
. To test connection to the proxy, click *Test Connection*.
ifdef::katello,orcharhino,satellite[]
. Select the *Default content HTTP proxy* option to set the new HTTP proxy as default for content synchronization.
endif::[]
. Click *Submit*.
