:_mod-docs-content-type: PROCEDURE

[id="importing-a-custom-gpg-key-by-using-cli"]
= Importing a {customgpg} key by using Hammer CLI

[role="_abstract"]
When hosts consume signed {customcontent}, ensure that the hosts are configured to validate the installation of packages with the appropriate GPG Key.
This helps to ensure that only packages from authorized sources can be installed.

ifdef::satellite[]
Red{nbsp}Hat content is already configured with the appropriate GPG key and thus GPG Key management of Red{nbsp}Hat repositories is not supported.
endif::[]

.Prerequisites
ifdef::client-content-dnf[]
* Ensure that you have a copy of the GPG key used to sign the RPM content that you want to use and manage in {Project}.
Most RPM distribution vendors provide their GPG Key on their website.
You can also extract GPG key files from an RPM package.
For more information, see xref:Extracting_GPG_Keys_from_RPM_Packages_{context}[].
endif::[]
ifndef::client-content-dnf[]
* Extract the GPG public key fingerprints from a signed `Release` file for Deb content.
For more information, see xref:Extracting_GPG_Public_Key_Fingerprints_from_Release_Files_{context}[].
endif::[]

.Procedure
. Copy the GPG key to your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
ifdef::client-content-dnf[]
$ scp ~/etc/pki/rpm-gpg/RPM-GPG-KEY-_EXAMPLE-95_ root@{foreman-example-com}:~/.
endif::[]
ifndef::client-content-dnf[]
$ scp ~/_My_GPG_Public_Key_ root@{foreman-example-com}:~/.
endif::[]
----
. Upload the GPG key to {Project}:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-credentials create \
--content-type gpg_key \
--name "_My_GPG_Key_" \
--organization "_My_Organization_" \
ifdef::client-content-dnf[]
--path ~/RPM-GPG-KEY-_EXAMPLE-95_
endif::[]
ifndef::client-content-dnf[]
--path ~/_My_GPG_Public_Key_
endif::[]
----
