[id="Managing_Packages_on_the_Base_Operating_System_{context}"]
= Managing packages on the base operating system of {ProjectServer} or {SmartProxyServer}

{Project} provides the `{foreman-maintain} packages` command to install and update packages on the base operating system of your {ProjectServer} or {SmartProxyServers}.

[WARNING]
====
Installing and updating individual packages with `yum` is not supported.
While {Project} provides the `{foreman-maintain} packages unlock` command to bypass `{foreman-maintain} packages` and enable package management with `yum`, this can lead to package inconsistencies and compromise the stability of the system.
Always use `{foreman-maintain} packages` to manage packages.
====

The `{foreman-maintain} packages` command restarts some services on the base operating system because it runs the `{foreman-installer}` command after installing packages.

You can manage packages using `{foreman-maintain} packages` command as follows:

* To install packages on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-install} _package_1_ _package_2_
----
* To check for available package updates on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-check-update}
----
* To update all packages on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-update}
----
* To update specific packages on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-update} _package_1_ _package_2_
----
* To revert `{foreman-maintain} unlock` and configure {Project} to ensure the stability of the base operating system by preventing users from managing packages with `yum`:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-maintain} packages lock
----

.Additional resources
* For information about updating {Project} to the next patch version, see {UpdatingDocURL}[_{UpdatingDocTitle}_].
* For a complete reference about using `{foreman-maintain} packages`, see the Hammer CLI help with `{foreman-maintain} packages --help`.
