[id="Configuring_a_Bonded_Interface_{context}"]
= Configuring a bonded interface

You can combine multiple physical interfaces together by configuring a bonded interface for the host.

[NOTE]
====
Bonded interfaces currently require a MAC address of a physical device.
Therefore, the configuration of these interfaces works only on bare-metal hosts.
====

.Procedure
. Navigate to the *Add Interface* form:
+
--
* In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
* Click *Edit* next to the host you want to edit.
* On the *Interfaces* tab, click *Add Interface*.
--

. Select *Bond* from the *Type* list.

. Specify the general interface settings:
+
--
* In the *Device Identifier* field, specify the interface ID in the `bond0` format .
* Specify a *MAC address*.
* If you are configuring a secondary interface, select *Managed*.
Otherwise, {Project} does not apply the configuration.
--

. Add the configuration specific to bonded interfaces:
+
--
* *Mode*: Select the bonding mode.
* *Attached devices*: Specify a comma-separated list of identifiers of attached devices.
These can be physical interfaces or VLANs.
* *Bond options*: Specify a space-separated list of configuration options, for example `miimon=100`.
--

. Click *OK* to save the interface configuration.
. Click *Submit* to apply the changes to the host.

