:_mod-docs-content-type: PROCEDURE

[id="preparing-a-synchronized-kickstart-repository"]
= Preparing a synchronized Kickstart repository

[role="_abstract"]
You can use synchronized Kickstart repositories as the source of the operating system during host provisioning.

.Prerequisites
* *BaseOS* and *AppStream Kickstart* are enabled before provisioning.

.Procedure
. Add the synchronized Kickstart repository that you want to use to the existing content view, or create a new content view and add the Kickstart repository.
+
For {EL} 8, ensure that you add both *{EL} 8 for x86_64 - AppStream Kickstart x86_64 8* and *{EL} 8 for x86_64 - BaseOS Kickstart x86_64 8* repositories.
ifdef::satellite,orcharhino[]
+
If you use a disconnected environment, you must import the Kickstart repositories from your {EL} binary DVD.
endif::[]
+
. Publish a new version of the content view where the Kickstart repository is added and promote it to a required lifecycle environment.
. When you create a host, in the *Operating System* tab, for *Media Selection*, select the *Synced Content* checkbox.

.Verification
* View the Kickstart tree:
+
[subs="+quotes"]
----
$ hammer medium list --organization "_My_Organization_"
----

.Additional resources
* {ContentManagementDocURL}managing-content-views-and-content-view-environments[Managing content views and content view environments]
