:_mod-docs-content-type: PROCEDURE

[id="querying-the-mcp-server-for-{project-context}"]
= Querying the MCP server for {Project}

[role="_abstract"]
With your AI application connected to the MCP server for {Project}, you can use the AI application chatbot to request information about your {Project} deployment.
The AI application retrieves and processes the relevant data from the {Project} inventory.

[WARNING]
====
Always review content generated by AI before using it in production.
====

.Procedure
* Type a query into your AI application.
For example:
+
[options="nowrap", subs="+quotes,attributes"]
----
Show a list of hosts that require patching.
----
+
The AI application interprets the query and asks the MCP client to retrieve the relevant data from {Project} inventory through the MCP server.
The MCP client fetches the data and returns it to the AI application, which then processes it to provide an answer to the user.

.Query examples
====
Querying hosts::
+
To obtain a list of hosts that require patching and refine it, you can use the following prompts:
+
[options="nowrap", subs="+quotes,attributes"]
----
Show a list of hosts that require patching on my {Project}.
----
+
[options="nowrap", subs="+quotes,attributes"]
----
Categorize the list into hosts that require security patches
and hosts that require bug fix patches.
----
Querying subnets::
+
To obtain a report of all subnets in {Project} inventory, you can use the following prompts:
+
[options="nowrap", subs="+quotes,attributes"]
----
Generate a static report of all subnets on my {Project}.
Read API documentation for each of the needed resources
before doing any searches.
----
+
[options="nowrap", subs="+quotes,attributes"]
----
For each subnet, report its name, address, network mask,
and number of hosts which are assigned to it.
----
====
