[id="Creating_a_Report_Template_{context}"]
= Creating a Report Template

In {Project}, you can create a report template and customize the template to suit your requirements.
You can import existing report templates and further customize them with snippets and template macros.

Report templates use Embedded Ruby (ERB) syntax.
To view information about working with ERB syntax and macros, in the {ProjectWebUI}, navigate to *Monitor*{nbsp}>{nbsp}*Report Templates*, and click *Create Template*, and then click the *Help* tab.

When you create a report template in {Project}, safe mode is enabled by default.
For more information about safe mode, see xref:Report_Template_Safe_Mode_{context}[].

For more information about writing templates, see the xref:Template_Writing_Reference_{context}[].
For more information about macros you can use in report templates, see xref:Template_Macros_{context}[].

ifdef::satellite[]
To view a step by step example of populating a template, see xref:Creating_a_Report_Template_to_Monitor_Entitlements_{context}[].
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Monitor*{nbsp}>{nbsp}*Report Templates*, and click *Create Template*.
. In the *Name* field, enter a unique name for your report template.
. If you want the template to be available to all locations and organizations, select *Default*.
. Create the template directly in the template editor or import a template from a text file by clicking *Import*.
For more information about importing templates, see xref:Importing_Report_Templates_{context}[].
. Optional: In the *Audit Comment* field, you can add any useful information about this template.
. Click the *Input* tab, and in the *Name* field, enter a name for the input that you can reference in the template in the following format: `input('name')`.
Note that you must save the template before you can reference this input value in the template body.
. Select whether the input value is mandatory.
If the input value is mandatory, select the *Required* checkbox.
. From the *Value Type* list, select the type of input value that the user must input.
. Optional: If you want to use facts for template input, select the *Advanced* checkbox.
. Optional: In the *Options* field, define the options that the user can select from.
If this field remains undefined, the users receive a free-text field in which they can enter the value they want.
. Optional: In the *Default* field, enter a value, for example, a host name, that you want to set as the default template input.
. Optional: In the *Description* field, you can enter information that you want to display as inline help about the input when you generate the report.
. Optional: Click the *Type* tab, and select whether this template is a snippet to be included in other templates.
. Click the *Location* tab and add the locations where you want to use the template.
. Click the *Organizations* tab and add the organizations where you want to use the template.
. Click *Submit* to save your changes.
