:_mod-docs-content-type: PROCEDURE

[id="customize-default-values-of-ansible-variables-by-using-api"]
= Customize default values of Ansible variables by using {Project} API

[role="_abstract"]
You can set custom default values of Ansible variables in {Project} by using {Project} API.
Global custom values help you define a baseline for your environment.

// TODO: Retest: there is at least one permission missing to actually load the "edit" window
.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_variable_overrides`, `destroy_ansible_variable_overrides`, `destroy_ansible_variables`, `edit_ansible_variable_overrides`, `edit_ansible_variables`, `view_ansible_content`, `view_ansible_variable_overrides`, `view_ansible_variables`, and `view_organizations` permissions.
* Your {Project} contains imported Ansible content.

.Procedure
. Optional: Get a list of Ansible content IDs:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_content/ \
| jq ".results [] .id"
----
+
Note down the ID of your Ansible content in {Project}.
. Optional: Get a list of Ansible roles in your Ansible content:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_content/_My_Ansible_Content_ID_/ \
| jq ".roles [] .name"
----
. Optional: Get a list of variables in your Ansible roles:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_content/_My_Ansible_Content_ID_/ \
| jq ".roles []" | jq 'select(.name == "_My_Ansible_Role_Name_")' | jq ".variables []"
----
+
Note down the ID of the Ansible variable that you want to customize.
. Create a JSON file, for example, `data.json` to define your custom default value:
+
[source, json, options="nowrap", subs="verbatim,quotes,attributes"]
----
{
  "ansible_variable": {
    "key": "_My_Ansible_Variable_Name_",
    "type": "_My_Ansible_Variable_Type_",
    "default_value": "_My_Default_Value_",
    "overridable": true
  }
}
----
. Set a custom default value for an Ansible variable:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--data @data.json \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--request POST \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_variables/_My_Ansible_Variable_ID_/ \
| jq
----

.Verification
* Query the {Project} API to verify that {Project} set the Ansible variable override successfully:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_content/_My_Ansible_Content_ID_/ \
| jq ".roles []" | jq 'select(.name == "_My_Ansible_Role_Name_")' | jq ".variables []" | jq 'select (.name == "_My_Ansible_Variable_Name_")'
----

.Additional resources
* xref:types-of-overrides[]
* xref:ansible-variable-precedence[]
