:_mod-docs-content-type: PROCEDURE

[id="configuring-{project-context}-server-for-cloud-connection"]
= Configuring {ProjectServer} for cloud connection

[role="_abstract"]
You can configure {ProjectServer} to connect to the {RHCloud} by using remote execution.
This enables inventory upload and cloud-based features such as {Insights} for your hosts.

.Prerequisites
ifndef::satellite[]
* You have installed the Red{nbsp}Hat Cloud plugin on your {ProjectServer}.
For more information, see xref:installing-red-hat-cloud-plugin[].
* Your environment is configured for remote execution.
For more information, see {ManagingHostsDocURL}configuring-and-setting-up-remote-jobs[Configuring and setting up remote jobs] in _{ManagingHostsDocTitle}_.
endif::[]
* {ProjectServer} must be registered with Red{nbsp}Hat Subscription Management.
You can verify the status by running `subscription-manager status`.
* You have added the SSH key to authorized keys on your {ProjectServer}.
For more information, see xref:adding-{project-context}-server-ssh-key-to-authorized-keys[].
* Your {Project} account has a role that grants the `execute_jobs_on_infrastructure_hosts` permission.
+
Note that this permission is not included in the default *Remote Execution User* role.

.Procedure
. In the {ProjectWebUI}, navigate to *{Insights}* > *Inventory Upload*.
. Click *Configure cloud connector*.
. Click *Confirm*.

.Verification
. In the {ProjectWebUI}, navigate to *Monitor* > *{Project} Tasks* > *Tasks*.
. Find the job with the name `Remote action: Configure cloud connector`.
. Verify that the job completed successfully.

.Next steps
* Install the Insights client on hosts.
For more information, see {ManagingHostsDocURL}monitoring-hosts-by-using-{insights-id}-in-cloud[Monitoring hosts by using {Insights} in {RHCloud} in _{ManagingHostsDocTitle}_].
