:_mod-docs-content-type: PROCEDURE

[id="registering-a-host-to-{project-context}-by-using-cli"]
= Registering a host to {Project} by using Hammer CLI

[role="_abstract"]
You can register a host to {Project} by using Hammer CLI with registration templates.
This also enables you to set up various integration features and host tools during the registration process.

.Prerequisites
include::snip_registering-a-host-prerequisites.adoc[]

.Procedure
. Generate the host registration command:
+
ifndef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command \
--insecure true
----
endif::[]
ifdef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command \
--activation-keys "_My_Activation_Key_"
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command \
--activation-keys "_My_Activation_Key_" \
--insecure true
----
endif::[]
. Connect to your host using SSH and run the registration command as `root`.
+
For more information, see the Hammer CLI help with `hammer host-registration generate-command --help`.

ifdef::katello,orcharhino,satellite[]
include::snip_verification-repositories-enabled.adoc[]
endif::[]

.Next steps
* To set up monitoring of outdated services and applications using Tracer, see {ManagingHostsDocURL}configuring-tracer-on-a-host_managing-hosts[Configuring Tracer on a host] in _{ManagingHostsDocTitle}_.

.Additional resources
* {ManagingHostsDocURL}registering-hosts-to-{project-context}[Registering hosts to {Project} in _{ManagingHostsDocTitle}_]
ifdef::managing-hosts[]
* xref:registration-command-customization[]
endif::[]
