:_mod-docs-content-type: PROCEDURE

[id="uploading-content-to-custom-rpm-repositories-by-using-web-ui"]
= Uploading content to {customrpm} repositories by using {ProjectWebUI}

[role="_abstract"]
You can upload individual RPMs to {customrpm} repositories by using {ProjectWebUI}.

You must use the Hammer CLI to upload source RPMs.
For more information, see xref:uploading-content-to-custom-rpm-repositories-by-using-cli[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Click the name of the {customproduct}.
. In the *Repositories* tab, click the name of the {customrpm} repository.
. Under *Upload Package*, click *Browse...* and select the RPM you want to upload.
. Click *Upload*.

.Verification
* To view all RPMs in this repository, click the number next to *Packages* under *Content Counts*.

.Next steps
* Add your {customrpm} repository to a content view.
For more information, see xref:creating-a-content-view-by-using-web-ui[].
* If your {customrpm} is unprotected, hosts can consume its content by using the *Published At* URL.
+
In the Default Organization View content view, the URL consists of your {SmartProxy} FQDN, `/pulp/content/`, your organization label, `/Library/custom/`, your product label, `/`, your repository label, and a trailing `/`, for example, `\https://foreman.example.com/pulp/content/Example/Library/custom/my-software/my-app/`.
ifdef::orcharhino[]
+
include::snip_important-consuming-content-requires-a-subscription.adoc[]
endif::[]
