:_mod-docs-content-type: PROCEDURE

[id="mirroring-remote-flatpak-repositories-to-{project-context}-products-by-using-web-ui"]
= Mirroring remote Flatpak repositories to {Project} products by using {ProjectWebUI}

[role="_abstract"]
Mirror a Flatpak repository from a scanned remote into an existing product in {ProjectWebUI} so you can synchronize it and publish application content to hosts through content views.

This action creates a new repository inside the product you selected.
You can now synchronize the repository to pull down its content.
Flatpak repositories are container repositories and you can add them to content views like other container repositories.

Flatpak applications require a corresponding runtime environment, which the Flatpak remote also provides.
ifdef::katello,satellite,almalinux,oracle_linux,red_hat_enterprise_linux,rocky_linux[]
To make the {EL} 10 Mozilla Firefox Flatpak available to a host, ensure that the host can access the matching `rhel10/flatpak-runtime` repository.
endif::[]

.Prerequisites
* Your {Project} account has a role that grants the `view_flatpak_remotes` and `edit_flatpak_remotes` permissions.
* Ensure that Flatpak runtime repositories are available to hosts alongside application repositories.
ifdef::katello,satellite,almalinux,oracle_linux,red_hat_enterprise_linux,rocky_linux[]
Flatpak applications, such as `rhel9/firefox-flatpak`, depend on the runtime for installation.
endif::[]
* You have created a {customproduct} on {Project}.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Flatpak Remotes*.
. In the list of Flatpak Remotes, click the name of the remote you want to mirror.
. In the list of remote repositories, locate the repository you want to mirror.
. Select the *Mirror Action* menu on the row of the repository.
. In the *Mirror* window, select the existing product where you want to create the new repository.
. Click *Mirror*.
