:_mod-docs-content-type: PROCEDURE

[id="adding-images-to-server-by-using-web-ui_{context}"]
= Adding {CRname} images to {ProjectServer} by using {ProjectWebUI}

[role="_abstract"]
To create hosts using image-based provisioning, you must add information about the image, such as access details and the image location, to your {ProjectServer}.

ifdef::kvm-provisioning[Note that you can manage only directory pool storage types through {Project}.]

.Procedure

. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources* and click the name of the {CRname} connection.
. Click *Create Image*.
. In the *Name* field, enter a name for the image.
. From the *Operating System* list, select the base operating system of the image.
. From the *Architecture* list, select the operating system architecture.
. In the *Username* field, enter the SSH user name for image access.
ifdef::kvm-provisioning,openstack-provisioning[This is normally the `root` user.]
ifdef::gce-provisioning[Specify a user other than `root`, because the `root` user cannot connect to a GCE instance using SSH keys. The username must begin with a letter and consist of lowercase letters and numbers.]
ifdef::azure-provisioning[You cannot use the `root` user.]

ifdef::kvm-provisioning,openstack-provisioning[. In the *Password* field, enter the SSH password for image access.]
ifdef::azure-provisioning[. Optional: In the *Password* field, enter a password to authenticate with.]

ifdef::kvm-provisioning[]
. In the *Image path* field, enter the full path that points to the image on the KVM server.
For example:
+
[options="nowrap" subs="+quotes"]
----
 /var/lib/libvirt/images/TestImage.qcow2
----
endif::[]
ifdef::openstack-provisioning,gce-provisioning[. From the *Image* list, select an image from the {CRname} compute resource.]
ifdef::azure-provisioning[]
. In the *Azure Image Name* field, enter an image name in the format `_prefix://UUID_`.
+
* For a custom image, use the prefix `custom`.
For example, *custom://image-name*.
* For a shared gallery image, use the prefix `gallery`.
For example, *gallery://Templates/image-name*.
* For public and RHEL Bring Your Own Subscription (BYOS) images, use the prefix `marketplace`.
For example, *marketplace://OpenLogicCentOS:7.5:latest*.
+
For more information, see https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage[Find Linux VM images in the Azure Marketplace with the Azure CLI].
endif::[]

. Optional: Select the *User Data* checkbox if the image supports user data input, such as `cloud-init` data.
. Click *Submit* to save the image details.
