[id="Chainbooting_iPXE_from_PXELinux_{context}"]
= Chainbooting iPXE from PXELinux

Use this procedure to set up iPXE to use a built-in driver for network communication or UNDI interface.
To use HTTP with iPXE, use iPXE build with built-in drivers (`ipxe.lkrn`).
Universal Network Device Interface (UNDI) is a minimalistic UDP/IP stack that implements TFTP client, however, cannot support other protocols like HTTP (`undionly-ipxe.0`).
You can choose to either load `ipxe.lkrn` or `undionly-ipxe.0` file depending on the networking hardware capabilities and iPXE driver availability.

.Chainbooting iPXE directly or with UNDI workflow
. Host powers on
. PXE driver retrieves the network credentials using DHCP
. PXE driver retrieves the PXELinux firmware `pxelinux.0` using TFTP
. PXELinux searches for the configuration file on the TFTP server
. PXELinux chainloads iPXE `ipxe.lkrn` or `undionly-ipxe.0`
. iPXE retrieves the network credentials using DHCP again
. iPXE retrieves HTTP address using DHCP
. iPXE chainloads the iPXE template from the template {SmartProxy}
. iPXE loads the kernel and initial RAM disk of the installer

.Configuring {ProjectServer} to use iPXE
You can use the default template to configure iPXE booting for hosts.
If you want to change the default values in the template, clone the template and edit the clone.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning Templates*.
. Enter `PXELinux chain iPXE` to use `ipxe.lkrn` or, for BIOS systems, enter `PXELinux chain iPXE UNDI` to use `undionly-ipxe.0`, and click *Search*.
. Optional: If you want to change the template, click *Clone*, enter a unique name, and click *Submit*.
. Click the name of the template you want to use.
. If you clone the template, you can make changes you require on the *Template* tab.
. Click the *Association* tab, and select the operating systems that your host uses.
. Click the *Locations* tab, and add the location where the host resides.
. Click the *Organizations* tab, and add the organization that the host belongs to.
. Click *Submit* to save the changes.
. In the *Provisioning Templates* page, enter `Kickstart default iPXE` into the search field and click *Search*.
. Optional: If you want to change the template, click *Clone*, enter a unique name, and click *Submit*.
. Click the name of the template you want to use.
. If you clone the template, you can make changes you require on the *Template* tab.
. Click the *Association* tab, and associate the template with the operating system that your host uses.
. Click the *Locations* tab, and add the location where the host resides.
. Click the *Organizations* tab, and add the organization that the host belongs to.
. Click *Submit* to save the changes.
. In the {ProjectWebUI}, navigate to *Hosts* > *Operating systems* and select the operating system of your host.
. Click the *Templates* tab.
. From the *PXELinux template* list, select the template you want to use.
. From the *iPXE template* list, select the template you want to use.
. Click *Submit* to save the changes.
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*, and select the host group you want to configure.
. Select the *Operating System* tab.
. Set *PXE Loader* to *PXELinux BIOS* to chainboot iPXE via PXELinux, or to *iPXE Chain BIOS* to load `undionly-ipxe.0` directly.
. Select the *Templates* tab, and from the *PXELinux template* list, select *Review* to verify the template is the correct template.
. From the *iPXE template* list, select *Review* to verify the template is the correct template.
If there is no PXELinux entry, or you cannot find the new template, navigate to *Hosts* > *All Hosts*, and on your host, click *Edit*.
Click the *Operating system* tab and click the Provisioning Template *Resolve* button to refresh the list of templates.
. On {ProjectServer}, run:
+
[options="nowrap" subs="+quotes,attributes"]
----
{foreman-installer} --foreman-proxy-dhcp-ipxefilename "http://{foreman-example-com}/unattended/iPXE?bootstrap=1"
----
+
[NOTE]
====
Ensure that `--foreman-trusted-proxies` is configured correctly on the {ProjectServer}.
====