[id="creating-an-installation-medium-for-ubuntu-22-04"]
= Creating an installation medium for Ubuntu 22.04

To provision Ubuntu 22.04, you need to provide both the ISO image and the extracted ISO image on your {ProjectServer}.

:iso_image: ubuntu-22.04.3-live-server-amd64.iso

.Procedure
. Connect to your {ProjectServer} using SSH:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ssh root@{foreman-example-com}
----
. Download the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cd /tmp/
# wget https://releases.ubuntu.com/22.04/{iso_image}
----
. Mount the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mount {iso_image} /mnt
----
. Provide the ISO image and the extracted directory under _{foreman-example-com}/pub_:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /var/www/html/pub/installation_media/ubuntu/22.04-x86_64/
# cp {iso_image} /var/www/html/pub/installation_media/ubuntu/22.04-x86_64.iso
# cp -a /mnt/* /var/www/html/pub/installation_media/ubuntu/22.04-x86_64/
----
+
Ensure the path in `/pub/` matches the path in your _Preseed default PXELinux Autoinstall_ template.
. Unmount and delete the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# umount /mnt/
# rm -f {iso_image}
----

As an alternative to copying the content of the ISO image, one may instead mount the ISO image somewhere, such as under `/mnt`,
then create `/var/www/html/pub/installation_media/ubuntu/22.04-x86_64` as a symbolic link to the mounted image. The ISO image
should not be mounted directly under `/var/lib/foreman`, because on Debian and Ubuntu this will cause the package postinst script
to fail at the `chmod -Rf /var/lib/foreman` command.

Use `\http://{foreman-example-com}/pub/installation_media/ubuntu/22.04-x86_64/` to set up your installation media entry in {Project}.
For more information, see xref:adding-installation-media_{context}[].
