[id="synchronizing-templates-with-an-existing-repository_{context}"]
= Synchronizing templates with an existing repository

If you store templates in a repository under a version control system, you can synchronize the templates between your {ProjectServer} and the repository.

In this procedure, a Git repository is used for demonstration purposes.

.Procedure
. Configure connection to the repository.
Skip this step if you want to use an HTTP proxy, an HTTPS proxy, or a regular HTTP connection to connect to the repository.
.. To use HTTPS to connect to the repository if your Git server uses a self-signed certificate authority (CA):
... Create a new directory under the `/usr/share/foreman/` directory to store the Git configuration for the certificate:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# mkdir --parents /usr/share/foreman/.config/git
----
... Create a file named `config` in the new directory:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# touch /usr/share/foreman/.config/git/config
----
... Allow the `foreman` user access to the `.config` directory:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# chown --recursive foreman /usr/share/foreman/.config
----
... Update the Git global configuration for the `foreman` user with the path to your self-signed CA certificate:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# sudo --user foreman git config --global http.sslCAPath _Path_To_CA_Certificate_
----
.. To use SSH to connect to the repository:
... Create an SSH key pair if you do not already have it.
Do not specify a passphrase.
+
----
# sudo --user foreman ssh-keygen
----
... Configure your version control server with the public key from your {Project}, which resides in `/usr/share/foreman/.ssh/id_rsa.pub`.
... Accept the Git SSH host key as the `foreman` user:
+
[subs="+quotes"]
----
# sudo --user foreman ssh _git.example.com_
----
. In the {ProjectWebUI}, provide details for your Git repository:
.. Navigate to *Administer > Settings*.
.. Click the *Template Sync* tab.
.. Change the *Branch* setting to match the target branch of the repository.
.. Change the *Repo* setting to match the repository URL.

.Next steps

* To import templates from your repository, continue with xref:Importing_Templates_{context}[].
* To export templates from your repository, continue with xref:Exporting_Templates_{context}[].
