[id="Connecting_to_an_Amazon_EC2_Instance_Using_SSH_{context}"]
= Connecting to an Amazon EC2 instance using SSH

You can connect remotely to an Amazon EC2 instance from {ProjectServer} using SSH.
However, to connect to any Amazon Web Services EC2 instance that you provision through {ProjectName}, you must first access the private key that is associated with the compute resource in the Foreman database, and use this key for authentication.

.Procedure
. To locate the compute resource list, on your {ProjectServer} base system, enter the following command, and note the ID of the compute resource that you want to use:
+
----
# hammer compute-resource list
----
. Switch user to the `postgres` user:
+
[options="nowrap" subs="+quotes"]
----
# su - postgres
----
. Initiate the `postgres` shell:
+
[options="nowrap" subs="+quotes"]
----
$ psql
----
. Connect to the Foreman database as the user `postgres`:
+
[options="nowrap" subs="+quotes"]
----
# postgres=# \c foreman
----
. Select the secret from `key_pairs` where `compute_resource_id = 3`:
+
[options="nowrap" subs="+quotes"]
----
# select secret from key_pairs where compute_resource_id = 3; secret
----
. Copy the key from after `-----BEGIN RSA PRIVATE KEY-----` until `-----END RSA PRIVATE KEY-----`.
. Create a `.pem` file and paste your key into the file:
+
[options="nowrap" subs="+quotes"]
----
# vim _Keyname_.pem
----
. Ensure that you restrict access to the `.pem` file:
+
[options="nowrap" subs="+quotes"]
----
# chmod 600 _Keyname_.pem
----
. To connect to the Amazon EC2 instance, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
ssh -i _Keyname_.pem   ec2-user@_example.aws.com_
----
