[id="Configuring_a_Host_for_OpenSCAP_{context}"]
= Configuring a Host for OpenSCAP

Use this procedure to configure all the OpenSCAP requirements for a host.

.Prerequisites
* Enable OpenSCAP on {SmartProxy}.
For more information, see {InstallingSmartProxyDocURL}Enabling_OpenSCAP_on_{smart-proxy-context}_Servers_{smart-proxy-context}[Enabling OpenSCAP on {SmartProxyServersTitle}] in _{InstallingSmartProxyDocTitle}_.
* Assign an OpenSCAP {SmartProxy}.
* Assign a Puppet environment that contains the Puppet classes to deploy the OpenSCAP policies.
* Assign the `foreman_scap_client` and `foreman_scap_client::params` Puppet classes.
* Assign any compliance policies that you want to add.

For information about creating and administering hosts, see the {ManagingHostsDocURL}[Managing Hosts] guide.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*, and select *Edit* on the host you want to configure for OpenSCAP reporting.
. From the *Puppet Environment* list, select the Puppet environment that contains the `foreman_scap_client` and `foreman_scap_client::params` Puppet classes.
. From the *OpenSCAP {SmartProxy}* list, select the {SmartProxy} with OpenSCAP enabled that you want to use.
. Click the *Puppet Classes* tab, and add the `foreman_scap_client` and `foreman_scap_client::params` Puppet classes.
. To add a compliance policy, navigate to one of the following locations:
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Select the host or hosts to which you want to add the policy.
. Click *Select Action*.
. Select *Assign Compliance Policy* from the list.
. In the Policy window, select the policy that you want from the list of available policies and click *Submit*.
