[id="Using_a_Custom_Repository_on_a_Connected_Server_{context}"]
= Using a Custom Repository on a Connected Server

Use this procedure to synchronize content from a custom repository on a connected {ProjectServer} and a disconnected {ProjectServer} via Inter-Satellite Synchronization (ISS) Network Sync.

[NOTE]
====
Follow the procedure for the connected {ProjectServer} before completing the procedure for the disconnected {ProjectServer}.
====

.Connected {ProjectServer}
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Click on the custom product.
. Click on the custom repository.
On this page, you can see the link in front of *Published At:*.
. Copy the link.
Follow these steps to synchronize content from a custom repository on a disconnected server via Inter-Satellite Synchronization (ISS) Network Sync:

.Disconnected {ProjectServer}
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
You need to create your custom product and custom repository.
. Create your custom product with the following:
* Upstream URL: Copy the link in front of *Published At:*.
* SSL CA Cert: You can select the SSL certificate that was created from your connected server.

After completing these steps, the disconnected {ProjectServer} will synchronize the custom repository as normal.
