[id="Browsing_Repository_Content_Using_an_Organization_Debug_Certificate_{context}"]
= Browsing Repository Content Using an Organization Debug Certificate

You can view an organization's repository content using a web browser or using the API if you have a debug certificate for that organization.

.Prerequisites
ifndef::satellite[]
. Create and download an organization certificate as described in {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate].
endif::[]
ifdef::satellite[]
. Create and download an organization certificate as described in xref:Creating_an_Organization_Debug_Certificate_{context}[].
endif::[]
. Open the X.509 certificate, for example, for the default organization:
+
----
$ vi 'Default Organization-key-cert.pem'
----
. Copy the contents of the file from `-----BEGIN RSA PRIVATE KEY-----` to `-----END RSA PRIVATE KEY-----`, into a `key.pem` file.
. Copy the contents of the file from `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----`, into a `cert.pem` file.

.Procedure

To use a browser, you must first convert the X.509 certificate to a format your browser supports and then import the certificate.

.For Firefox Users

To use an organization debug certificate in Firefox, complete the following steps:

. To create a PKCS12 format certificate, enter the following command:
+
[subs="+quotes"]
----
$ openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -export -in cert.pem -inkey key.pem -out _organization_label_.pfx -name _My_Organization_
----
+
. In the Firefox browser, navigate to *Edit* > *Preferences* > *Advanced Tab*.
. Select *View Certificates*, and click the *Your Certificates* tab.
. Click *Import* and select the `.pfx` file to load.
. Enter the following URL in the address bar to browse the accessible paths for all the repositories and check their contents:
+
[options="nowrap" subs="+quotes,attributes"]
----
https://_{foreman-example-com}_/pulp/content/
----
+
Pulp uses the organization label, therefore, you must enter the organization label into the URL.

.For CURL Users

To use the organization debug certificate with CURL, enter the following command:
[options="nowrap" subs="+quotes,attributes"]
----
$ curl -k --cert cert.pem --key key.pem \
https://_{foreman-example-com}_/pulp/content/_organization_label_/Library/content/dist/rhel/server/7/7Server/x86_64/os/
----
Ensure that the paths to `cert.pem` and `key.pem` are the correct absolute paths otherwise the command fails silently.
