:_mod-docs-content-type: PROCEDURE

[id="preparing-for-disaster-recovery-by-virtualizing-your-{project-context}-server"]
= Preparing for disaster recovery by virtualizing your {ProjectServer}

Implement a reliable process for regularly taking VM snapshots of your virtualized {ProjectServer} and for backing up your snapshots for long-term storage.

.Procedure
. Define a schedule for taking periodic snapshots of your virtualized {ProjectServer}.
Consider your tolerance for potential data loss:
Taking snapshots frequently will result in smaller amounts of data loss in case of a disaster.
However, creating a snapshot takes time, and the snapshots also require storage space.
. Define your snapshot retention policy.
Consider how many snapshots you want to store: Regularly removing outdated snapshots helps optimize storage usage.
. Using your hypervisor, schedule periodic snapshots of your {ProjectServer}.
. Schedule periodic backups of the snapshots to prevent data loss in case of hypervisor failure.
+
[NOTE]
====
While snapshots provide quick recovery points, backing up your snapshots gives you the ability for long-term storage and provides extra safety in case of a disaster on the side of your hypervisor.
====
. If you are using an external database that runs on a different machine than your {ProjectServer}, create snapshots and backups on the same schedule as your {ProjectServer}.

.Verification
. Verify that your hypervisor takes the snapshots according to the schedule that you defined.
. Use the latest snapshot of your {ProjectServer} and restore it in an isolated environment.
. To verify that you will be able to restore {Project} services in case of a disaster, assess the functionality of the test {ProjectServer}.
For more information, see xref:retrieving-the-status-of-services-by-using-cli[].
. Perform these verification checks regularly.
