[id="Updating_Server_{context}"]
= Updating {ProjectServer}

ifdef::satellite[]
Update your connected {ProjectServer} to the next patch version.
You can follow this process to update the underlying operating system between minor release versions.
For information to update a disconnected {Project} setup, see xref:Updating-Disconnected-{project-context}_{context}[].
endif::[]
ifndef::satellite[]
Update your {ProjectServer} to the next patch version.
endif::[]

.Prerequisites
* Back up your {ProjectServer}.
For more information, see {AdministeringDocURL}backing-up-{project-context}-server-and-{smart-proxy-context}_admin[Backing Up {ProjectServer} and {SmartProxyServer}] in _{AdministeringDocTitle}_.

include::snip_warning-maintain-config-noop.adoc[]

.Procedure
ifdef::satellite[]
. Ensure the {Project} Maintenance repository is enabled:
** On {RHEL} 9:
+
[options="nowrap" subs="attributes"]
----
# subscription-manager repos --enable \
{RepoRHEL9ServerSatelliteMaintenanceProjectVersion}
----

** On {RHEL} 8:
+
[options="nowrap" subs="attributes"]
----
# subscription-manager repos --enable \
{RepoRHEL8ServerSatelliteMaintenanceProjectVersion}
----
endif::[]
. Use the health check option to determine if the system is ready for update.
On first use of this command, `{foreman-maintain}` prompts you to enter the hammer admin user credentials and saves them in the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} update check
----
+
Review the results and address any highlighted error conditions before performing the update.
. Because of the lengthy update time, use a utility such as `tmux` to suspend and reattach a communication session.
You can then check the update progress without staying connected to the command shell continuously.
+
If you lose connection to the command shell where the update command is running, you can see the logged messages in the `{installer-log-file}` file to check if the process completed successfully.
. Perform the update:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} update run
----

include::snip_steps-needs-reboot.adoc[]

.Additional resources
* To restore the backup of the {ProjectServer} or {SmartProxyServer}, see {AdministeringDocURL}Restoring_from_a_Full_Backup_admin[Restoring {ProjectServer} or {SmartProxyServer} from a Backup]
