[id="adding-kvm-connection_{context}"]
= Adding a KVM Connection to {ProjectServer}

Use this procedure to add KVM as a compute resource in {Project}.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-kvm-connection_{context}[].

.Procedure

. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources* and click *Create Compute Resource*.
. In the *Name* field, enter a name for the new compute resource.
. From the *Provider* list, select *Libvirt*.
. In the *Description* field, enter a description for the compute resource.
. In the *URL* field, enter the connection URL to the KVM server.
For example:
+
[options="nowrap" subs="+quotes"]
----
 qemu+ssh://_root@kvm.example.com_/system
----
. From the *Display type* list, select either *VNC* or *Spice*.
. Optional: To secure console access for new hosts with a randomly generated password, select the *Set a randomly generated password on the display connection* checkbox.
You can retrieve the password for the VNC console to access the guest virtual machine console from the output of the following command executed on the KVM server:
+
[options="nowrap" subs="+quotes"]
----
# virsh edit _your_VM_name_
<graphics type='vnc' port='-1' autoport='yes' listen='0.0.0.0' passwd='_your_randomly_generated_password_'>
----
+
The password is randomly generated every time the console for the virtual machine is opened, for example, with virt-manager.
+
. Click *Test Connection* to ensure that {ProjectServer} connects to the KVM server without fault.
. Verify that the *Locations* and *Organizations* tabs are automatically set to your current context.
If you want, add additional contexts to these tabs.
. Click *Submit* to save the KVM connection.

[id="cli-adding-kvm-connection_{context}"]
.CLI procedure

* To create a compute resource, enter the `hammer compute-resource create` command:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create --name "_My_KVM_Server_" \
--provider "Libvirt" --description "KVM server at _kvm.example.com_" \
--url "qemu+ssh://root@_kvm.example.com/system_" --locations "New York" \
--organizations "_My_Organization_"
----
