:_mod-docs-content-type: PROCEDURE

[id="customize-values-of-ansible-variables-using-custom-matchers-by-using-cli"]
= Customize values of Ansible variables using custom matchers by using Hammer CLI

[role="_abstract"]
You can set custom default values of Ansible variables in {Project} by using Hammer CLI.
Global custom values help you define a baseline for your environment.

// TODO: Retest: there is at least one permission missing to actually load the "edit" window
.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_variable_overrides`, `destroy_ansible_variable_overrides`, `destroy_ansible_variables`, `edit_ansible_variable_overrides`, `edit_ansible_variables`, `view_ansible_content`, `view_ansible_variable_overrides`, `view_ansible_variables`, and `view_organizations` permissions.
* Your {Project} contains imported Ansible content.
* You have installed the Hammer CLI plugin for Ansible Director.
For more information, see xref:install-the-hammer-cli-plugin-for-ansible-director[].

.Procedure
* Set a custom value for an Ansible variable:
+
----
$ hammer
----

.Verification
* Verify that {Project} set the Ansible variable override successfully:
+
----
$ hammer
----

.Additional resources
* xref:types-of-overrides[]
* xref:ansible-variable-precedence[]
