:_mod-docs-content-type: PROCEDURE

[id="disabling-dhcp-for-integration"]
= Disabling DHCP for integration

[role="_abstract"]
If you want to manually manage a DHCP service and not integrate it into {ProjectServer}, you must prevent {Project} from maintaining this service on the operating system and disable orchestration to avoid errors.

[NOTE]
====
Disabling DHCP in {Project} does not remove the related backend service on the operating system.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets*.
. For each subnet that is associated with the DHCP {SmartProxy}:
.. Select the subnet.
.. On the *{SmartProxies}* tab, clear the *DHCP {SmartProxy}* field.
.. Click *Submit*.
. On {ProjectServer} and {SmartProxyServer}, enter:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-proxy-dhcp false
----
+
[NOTE]
====
{Project} does not perform orchestration when a {SmartProxy} is not set for a given subnet.
When you disable {SmartProxy} associations, orchestration commands for existing hosts can fail if the expected records and configuration files are not present.
====
