:_mod-docs-content-type: PROCEDURE

[id="registering-a-host-to-{project-context}-by-using-api_{context}"]
= Registering a host to {Project} by using {Project} API

[role="_abstract"]
You can register a host to {Project} by using {Project} API with registration templates.
During the registration process, you can set up various integration features and host tools.

.Prerequisites
include::snip_registering-a-host-prerequisites.adoc[]

.Procedure
. Generate the host registration command using the {Project} API:
+
ifndef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
$ curl \
--header 'Content-Type: application/json' \
--request POST \
--user "_My_User_Name_" \
https://{foreman-example-com}/api/registration_commands
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ curl \
--data '{ "registration_command": { "insecure": true }}' \
--header 'Content-Type: application/json' \
--request POST \
--user "_My_User_Name_" \
https://{foreman-example-com}/api/registration_commands
----
endif::[]
ifdef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
$ curl \
--data '{ "registration_command": { "activation_keys": ["_My_Activation_Key_1_, _My_Activation_Key_2_"] }}' \
--header 'Content-Type: application/json' \
--request POST \
--user "_My_User_Name_" \
https://{foreman-example-com}/api/registration_commands
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ curl \
--data '{ "registration_command": { "activation_keys": ["_My_Activation_Key_1_, _My_Activation_Key_2_"], "insecure": true }}' \
--header 'Content-Type: application/json' \
--request POST \
--user "_My_User_Name_" \
https://{foreman-example-com}/api/registration_commands
----
+
Use an activation key to simplify specifying the environments.
endif::[]
+
To enter a password as a command line argument, use `username:password` syntax.
Keep in mind this can save the password in the shell history.
Alternatively, you can use a temporary personal access token instead of a password.
To generate a token in the {ProjectWebUI}, navigate to *My Account* > *Personal Access Tokens*.
. Connect to your host using SSH and run the registration command.

ifdef::katello,orcharhino,satellite[]
include::snip_verification-repositories-enabled.adoc[]

ifdef::managing-hosts[]
.Next steps
* xref:configuring-tracer-on-a-host_managing-hosts[]
endif::[]
endif::[]

.Additional resources
ifdef::managing-hosts[]
* xref:registration-command-customization[]
endif::[]
ifndef::managing-hosts[]
* {ManagingHostsDocURL}registering-hosts-to-{project-context}[Registering hosts to {Project} in _{ManagingHostsDocTitle}_]
endif::[]
