[id="Creating_a_Content_View_{context}"]
= Creating a Content View

Use this procedure to create a simple Content View.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-content-view_{context}[].

.Prerequisites

While you can stipulate whether you want to resolve any package dependencies on a Content View by Content View basis, you might want to change the default {Project} settings to enable or disable package resolution for all Content Views.
For more information, see xref:Resolving_Package_Dependencies_{context}[].

.Procedure
. Navigate to *Content > Content Views* and click *Create content view*.
. Enter a name.
{Project} automatically completes the *Label* field from the name you enter.
. Optional: Enter a description.
. Optional: If you want to solve dependencies automatically every time you publish this Content View, select the *Solve Dependencies* check box.
. In the *Type* field, click a *Content View* or a *Composite Content View*.
. Click *Create content view* to create a Content View.
. On the *Repositories* tab, click one or more repositories you want to add to your Content View.
. Optional: Use the *Type* drop-down list to filter for repository types.
. Optional: Use the *Status* drop-down list to filter for added repositories.
. Click *Add repositories*.
. Click *Publish new version*.
. Optional: In the *Description* field, enter information about the version to log changes.
. Optional: You can enable a promotion path by clicking *Promote* and choose a lifecycle environment from the available promotion paths.
. Click *Next*.
. On the *Review* page, you can review the environments as they publish.
. Click *Finish*.

You can view the Content View in the Content Views window.
To view more information about the Content View, click the Content View name.
To register a host to your Content View, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in the _Managing Hosts_ guide.

[id="cli-creating-a-content-view_{context}"]
.CLI procedure
. Obtain a list of repository IDs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer repository list --organization "_My_Organization_"
----
. Create the Content View and add repositories:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer content-view create \
--description "_My_Content_View_" \
--name "_My_Content_View_" \
--organization "_My_Organization_" \
--repository-ids 1,2
----
+
For the `--repository-ids` option, you can find the IDs in the output of the `hammer repository list` command.
. Publish the view:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer content-view publish \
--description "_My_Content_View_" \
--name "_My_Content_View_" \
--organization "_My_Organization_"
----
. Optional: To add a repository to an existing Content View, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer content-view add-repository \
--name "_My_Content_View_" \
--organization "_My_Organization_" \
--repository-id _repository_ID_
----

{ProjectServer} creates the new version of the view and publishes it to the Library environment.
