[id="configuring-external-dns_{context}"]
= Configuring {ProductName} with External DNS

You can configure {ProductName} with external DNS.
{ProductName} uses the `nsupdate` utility to update DNS records on the remote server.

To make any changes persistent, you must enter the `{foreman-installer}` command with the options appropriate for your environment.

.Prerequisites

* You must have a configured external DNS server.
* This guide assumes you have an existing installation.

.Procedure

. Copy the `/etc/rndc.key` file from the external DNS server to {ProductName}:
+
[options="nowrap" subs="+quotes"]
----
# scp root@_dns.example.com_:/etc/rndc.key /etc/foreman-proxy/rndc.key
----

. Configure the ownership, permissions, and SELinux context:
+
[options="nowrap"]
----
ifndef::foreman-deb[]
# restorecon -v /etc/foreman-proxy/rndc.key
endif::[]
# chown -v root:foreman-proxy /etc/foreman-proxy/rndc.key
# chmod -v 640 /etc/foreman-proxy/rndc.key
----

. To test the `nsupdate` utility, add a host remotely:
+
[options="nowrap", subs="+quotes"]
----
# echo -e "server _DNS_IP_Address_\n \
update add aaa.example.com 3600 IN A _Host_IP_Address_\n \
send\n" | nsupdate -k /etc/foreman-proxy/rndc.key
# nslookup aaa.example.com _DNS_IP_Address_
# echo -e "server _DNS_IP_Address_\n \
update delete aaa.example.com 3600 IN A _Host_IP_Address_\n \
send\n" | nsupdate -k /etc/foreman-proxy/rndc.key
----

. Enter the `{foreman-installer}` command to make the following persistent changes to the `/etc/foreman-proxy/settings.d/dns.yml` file:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-proxy-dns=true \
--foreman-proxy-dns-managed=false \
--foreman-proxy-dns-provider=nsupdate \
--foreman-proxy-dns-server="_DNS_IP_Address_" \
--foreman-proxy-keyfile=/etc/foreman-proxy/rndc.key
----

. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*{SmartProxies}*.
. Locate the {ProductName} and select *Refresh* from the list in the *Actions* column.
. Associate the DNS service with the appropriate subnets and domain.
