:_mod-docs-content-type: PROCEDURE

[id="importing-a-red-hat-subscription-manifest-by-using-cli"]
= Importing a Red Hat subscription manifest by using Hammer CLI

[role="_abstract"]
You can import a Red{nbsp}Hat subscription manifest into {ProjectServer} by using Hammer CLI.
Import the manifest so that you can enable and synchronize Red{nbsp}Hat repositories in your organization.

.Prerequisites
* You have a Red{nbsp}Hat subscription manifest file.
For more information, see xref:obtaining-a-red-hat-subscription-manifest[].

.Procedure
. Copy the Red{nbsp}Hat subscription manifest file from your local machine to {ProjectServer}:
+
[subs="+quotes,attributes"]
----
$ scp ~/_manifest_file_.zip root@_{foreman-example-com}_:~/.
----
. Log in to {ProjectServer} over SSH as the `root` user.
. Import the Red{nbsp}Hat subscription manifest file:
+
[subs="+quotes"]
----
$ hammer subscription upload \
--file ~/_manifest_file_.zip \
--organization "_My_Organization_"
----

ifdef::content-management[]
.Next steps
* If you use the manifest from the {RHCloud}, add subscriptions to the manifest.
For more information, see xref:adding-red-hat-subscriptions-to-subscription-manifests[].
endif::[]
ifeval::["{mode}" == "disconnected"]
.Next steps
* You can now enable and synchronize Red{nbsp}Hat repositories.
For more information, see {ContentManagementDocURL}adding-content-to-{project-context}[Adding content to {Project}] in _{ContentManagementDocTitle}_.
endif::[]
