[id="Viewing_multiple_content_view_environment_hosts{context}"]
= Viewing multiple content view environment hosts

Use this procedure to view hosts with multiple content view environments or multi-environment hosts in the {ProjectWebUI} and Hammer CLI.

.Prerequisites
Ensure that you have at least one multi-environment host. 

.Procedure
. In the {ProjectwebUI}, navigate to *Hosts* > *All Hosts*.
+
[NOTE]
====
If you have the *Show new host overview page* setting enabled, the new UI appears by default.
====
+
. Click *Manage columns*.
. Under *Content*, click the *Content view environments* checkbox and click *Save*.
. Content view environments for each host are displayed under the *Content view environments* column.
. Click on the content view environments to display details.

On the *Host Details* page, the *Content view environments* card displays the details of the content view environments.

[NOTE]
====
If you reassign the content view environment of a multi-environment host from the *Content view environments* card, the host's content view environments are overwritten and is no longer a multi-environment host. 
To retain multiple environments, use Hammer to reassign the host's content view environments.
====

.CLI procedure
. Run the following command to view a list of hosts in your organization:
+
[options="nowrap" subs="+quotes"]
----
$ hammer host list --organization “Default Organization”
----
The `CONTENT VIEW ENVIRONMENTS` column displays the labels of content view environments associated with each host. The `MULTI CONTENT VIEW ENVIRONMENT` column shows `Yes` for multi-environment hosts.
+
. Run the following command to view multi-environment information for a host:
+
[options="nowrap" subs="+quotes"]
----
$ hammer host info --id
----
The information for the host is displayed including multiple content view environments.
