[id="configuring-an-alternative-directory-to-execute-remote-jobs-on-hosts_{context}"]
= Configuring {Project} to Use an Alternative Directory to Execute Remote Jobs on Hosts

ifeval::["{context}" == "managing-hosts"]

By default, {Project} uses the `/var/tmp` directory on the client system to execute the remote execution jobs.
If the client system has `noexec` set for the `/var/` volume or file system, you must configure {Project} to use an alternative directory because otherwise the remote execution job fails since the script cannot be run.

endif::[]

ifeval::["{context}" == "ansible"]

Ansible puts its own files it requires into the `$HOME/.ansible/tmp` directory, where `$HOME` is the home directory of the remote user.
You have the option to set a different directory if required.

endif::[]

.Procedure

. Create a new directory, for example _new_place_:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir /_remote_working_dir_
----

ifndef::foreman-deb[]
. Copy the SELinux context from the default `var` directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# chcon --reference=/var _/remote_working_dir_
----
endif::[]

ifeval::["{context}" == "managing-hosts"]

. Configure the system:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --foreman-proxy-plugin-remote-execution-script-remote-working-dir _/remote_working_dir_
----

endif::[]

ifeval::["{context}" == "ansible"]

. Configure the system:
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --foreman-proxy-plugin-ansible-working-dir _/remote_working_dir_
----

endif::[]
