:_mod-docs-content-type: PROCEDURE

[id="creating-an-rhui-alternate-content-source-by-using-web-ui"]
= Creating an RHUI alternate content source by using {ProjectWebUI}

[role="_abstract"]
You can create an RHUI alternate content source (ACS) to synchronize content from your Red{nbsp}Hat Update Infrastructure (RHUI) server.
Leverage your existing RHUI investment and accelerate content synchronization.

{Project} searches content paths that combine a base URL with subpaths.
For example, if your base URL is `\https://{server-example-com}` and your subpaths are `rhel10/` and `rhel9/`, then {Project} searches `\https://{server-example-com}/rhel10/` and `\https://{server-example-com}/rhel9/`.

.Prerequisites
* The client entitlement certificates for the required repositories are generated on the RHUA node.
For more information, see {RHDocsBaseURL}red_hat_update_infrastructure/4/html/configuring_and_managing_red_hat_update_infrastructure/assembly_cmg-creating-client-ent-cert-config-rpm_configuring-and-managing-red-hat-update-infrastructure#proc_cmg-creating-client-entitlement-certificate_assembly_cmg-creating-client-ent-cert-config-rpm[Creating a client entitlement certificate with the Red Hat Update Infrastructure Management Tool] in _Configuring and Managing Red Hat Update Infrastructure 4_.
* The client entitlement certificates are imported into {Project}.
For more information, see {ContentManagementDocURL}importing-custom-ssl-certificates-by-using-web-ui[Importing {customssl} certificates by using {ProjectWebUI}] in _{ContentManagementDocTitle}_.
* You have the base URL of the Red{nbsp}Hat Update Infrastructure CDS node.

.Procedure
. On your RHUA server, display details for the required repositories:
+
[options="nowrap" subs="+quotes,attributes"]
----
# rhui-manager repo info --repo_id _My_Repo_ID_
----
+
Record the relative paths from the command output to use as subpaths.
. In the {ProjectWebUI}, navigate to *Content* > *Alternate Content Sources*.
. Click *Add source*.
. Set the *Source type* to *RHUI*.
. Generate RHUI certificates using the command provided in the {ProjectWebUI}.
Ensure that you pass the repo labels of the desired repositories.
. In the *Name* field, enter a name for your RHUI ACS.
. Optional: In the *Description* field, provide a description for the ACS.
. Select {SmartProxies} to which you want to synchronize content from your alternate content source.
. If you require synchronizing content through the HTTP proxy of your {SmartProxies}, select *Use HTTP proxies*.
. In the *Base URL* field, enter the base URL of the Red{nbsp}Hat Update Infrastructure CDS node.
. In the *Subpaths* field, provide a comma-separated list of subpaths.
. If your alternate content source requires authentication, provide the *SSL client certificate* and *SSL client key*.
. If SSL verification is required, enable *Verify SSL* and select the SSL CA certificate.
. Click *Add*.
. Navigate to *Content* > *Alternate Content Sources*.
. Click the vertical ellipsis next to the newly created alternate content source and click *Refresh*.
