:_mod-docs-content-type: PROCEDURE

[id="deleting-an-organization-by-using-web-ui"]
= Deleting an organization by using {ProjectWebUI}

[role="_abstract"]
You can delete an organization from the {ProjectWebUI} if you no longer need it for resource management.

[IMPORTANT]
====
ifndef::orcharhino[]
Before deleting the organization configured as *Default organization*, navigate to *Administer* > *Settings* > *Facts* and select a different organization for the setting.
endif::[]
There must be at least one organization in the environment at any given time.
====

.Procedure
ifdef::foreman-deb,foreman-el[]
. If there are any host groups associated with the organization you are about to delete, remove them by navigating to *Administer* > *Organizations* and clicking the relevant organization.
endif::[]
ifdef::katello,orcharhino,satellite[]
. If there are any lifecycle environments or host groups associated with the organization you are about to delete, remove them by navigating to *Administer* > *Organizations* and clicking the relevant organization.
endif::[]
. In the {ProjectWebUI}, navigate to *Administer* > *Organizations*.
. From the list to the right of the name of the organization you want to delete, select *Delete*.
. Click *OK* to delete the organization.
