[id='configuring-project-with-an-alternate-cname_{context}']
= Configuring {Project} with an Alternate CNAME
Use this procedure to configure {Project} with an alternate CNAME. Note that the procedures for users of a default {Project} certificate and custom certificate differ. Note that if you have any hosts registered to {Project}, you must update the `katello-ca-consumer` package on the hosts after regenerating the {Project} SSL certificate.

.For Default {Project} Certificate Users

* If you have installed {Project} with a default {Project} certificate and want to configure {Project} with an alternate CNAME, enter the following command on {Project} to generate a new default {Project} SSL certificate with an additional CNAME.
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --certs-cname _alternate_fqdn_ --certs-reset
----

* If you have not installed {Project}, you can add the `--certs-cname _alternate_fqdn_` option to the `{foreman-installer}` command to install {Project} with an alternate CNAME.

.For Custom Certificate Users

If you use {Project} with a custom certificate, when creating a custom certificate, include the alternate CNAME records to the custom certificate. For more information, see {BaseURL}installing_satellite_server_from_a_connected_network/performing-additional-configuration#creating-a-custom-certificate_satellite[Creating a Custom SSL Certificate for {Project} Server].
