:_mod-docs-content-type: PROCEDURE

[id="deploying-a-custom-ssl-certificate-to-{smart-proxy-context}-server_{context}"]
= Deploying a custom SSL certificate to {SmartProxyServer}

[role="_abstract"]
If your {ProjectServer} is configured with a custom certificate, you must configure your {SmartProxyServer} with a custom SSL certificate signed by a Certificate Authority.

ifndef::containerized[]
The `{foreman-installer}` command, which the `{certs-generate}` command returns, is unique to each {SmartProxyServer}.
Do not use the same command on more than one {SmartProxyServer}.
endif::[]

.Prerequisites
* {ProjectServer} is configured with a custom certificate.
For more information, see {InstallingServerDocURL}configuring-{project-context}-server-with-a-custom-ssl-certificate[Configuring {ProjectServer} with a custom SSL certificate] in _{InstallingServerDocTitle}_.
* {SmartProxyServer} is registered to {ProjectServer}.
ifndef::orcharhino[]
For more information, see xref:registering-{smart-proxy-context}-server[].
endif::[]
* {SmartProxyServer} packages are installed.
ifndef::orcharhino[]
For more information, see xref:installing-{smart-proxy-context}-packages[].
endif::[]
* The required ports are open.
ifndef::orcharhino[]
For more information, see xref:opening-required-ports[].
endif::[]
ifdef::containerized[]
* {SmartProxyServer} packages are installed.
For more information, see xref:installing-{smart-proxy-context}-packages[].
endif::[]

.Procedure
ifdef::containerized[]
. On your {ProjectServer}, generate an authentication bundle for the {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} auth-bundle _{smartproxy-example-com}_
----
. On your {ProjectServer}, copy the authentication bundle to {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# scp /var/lib/foremanctl/certs/bundles/_{smartproxy-example-com}_.tar.gz \
root@_{smartproxy-example-com}_:/root/_{smartproxy-example-com}_.tar.gz
----
+
[IMPORTANT]
====
The authentication bundle contains TLS private keys and OAuth credentials.
Treat the bundle as highly sensitive and delete any copies after deployment.
====
. On the {SmartProxyServer}, deploy the configuration:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} deploy-proxy \
--flavor {foremanctl-proxy-scenario} \
--auth-bundle /root/_{smartproxy-example-com}_.tar.gz \
--foreman-fqdn _{foreman-example-com}_
--certificate-source custom_server \
--certificate-server-certificate "_/root/{project-context}_cert/{project-context}_cert.pem_" \
--certificate-server-key "_/root/{project-context}_cert/{project-context}_cert_key.pem_" \
--certificate-server-ca-certificate "_/root/{project-context}_cert/ca_cert_bundle.pem_"
----
+
--
The options used in the command include the following:

`--certificate-source custom_server`:: Sets the certificate source to custom server certificates provided by the user.
`--certificate-server-certificate`:: Path to {ProjectServer} certificate file that is signed by a Certificate Authority.
`--certificate-server-key`:: Path to the private key for the {ProjectServer} certificate.
`--certificate-server-ca-certificate`:: Path to the Certificate Authority bundle.
--
endif::[]
ifndef::containerized[]
. On your {ProjectServer}, generate a certificate bundle:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {certs-generate} \
--foreman-proxy-fqdn _{smartproxy-example-com}_ \
--certs-tar ~/_{smartproxy-example-com}_-certs.tar \
--server-cert /root/__{smart-proxy-context}_cert/{smart-proxy-context}_cert.pem__ \
--server-key /root/__{smart-proxy-context}_cert/{smart-proxy-context}_cert_key.pem__ \
--server-ca-cert /root/__{smart-proxy-context}_cert/ca_cert_bundle.pem__
----
+
The options specified in the command include the following:
+
`--server-cert`:: Path to {SmartProxyServer} certificate file that is signed by a Certificate Authority
`--server-key`:: Path to the private key that was used to sign {SmartProxyServer} certificate
`--server-ca-cert`:: Path to the Certificate Authority bundle
+
. Retain a copy of the `{foreman-installer}` command that the `{certs-generate}` command returns for deploying the certificate to your {SmartProxyServer}.
+
.Example output of `{certs-generate}`
[options="nowrap", subs="+quotes,attributes"]
----
_output omitted_
{installer-scenario-smartproxy} \
--certs-tar-file "/root/_{smartproxy-example-com}_-certs.tar" \
--foreman-proxy-foreman-base-url "https://_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{smartproxy-example-com}_" \
--foreman-proxy-oauth-consumer-key "_My_OAuth_Consumer_Key_" \
--foreman-proxy-oauth-consumer-secret "_My_OAuth_Consumer_Secret_"
----
. On your {ProjectServer}, copy the certificate archive file to your {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# scp ~/_{smartproxy-example-com}_-certs.tar \
root@_{smartproxy-example-com}_:/root/_{smartproxy-example-com}_-certs.tar
----
. On your {SmartProxyServer}, to deploy the certificate, enter the `{foreman-installer}` command that the `{certs-generate}` command returns.
endif::[]
+
[IMPORTANT]
====
Do not delete the certificate archive file after you deploy the certificate.
It is required, for example, when upgrading {SmartProxyServer}.
====
