[id="Synchronizing_Python_Repositories_{context}"]
= Synchronizing Python repositories

On {Project}, you can synchronize your Python repositories from any mirror and other {Project} instances.
You can view the Python packages in the {ProjectWebUI} at *Content* > *Content Types* > *Other Content Types*.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select a {customproduct} by name.
. In the *Products* window, select the name of a Product that you want to create a repository for.
. Click the *Repositories* tab, and then click *New Repository*.
. In the *Name* field, enter a name for the repository.
+
The *Label* field is populated automatically based on the name.
. From the *Type* list, select *python*.
. In the *Upstream URL* field, enter the URL for the upstream content source, for example `\https://pypi.org`.
. Optional: In the *Upstream Username* field, enter the user name for the upstream repository if required for authentication.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Password* field, enter the corresponding password for the upstream repository.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Authentication Token* field, provide the token of the upstream repository user for authentication.
Leave this field empty if the repository does not require authentication.
. Optional: In the *Excludes* field, enter a list of Python packages separated by newlines to exclude from synchronizing to {Project}.
. Optional: In the *Includes* field, enter a list of Python packages separated by newlines to limit the synchronization only to the included packages.
. Optional: In the *Package Types* field, enter a list of package types separated by comma.
You can use this field to only synchronize the source distribution if you enter `.tar.gz` or the built distribution if you enter `.whl`.
. From the *Mirroring Policy* list, select the type of content synchronization {ProjectServer} performs.
For more information, see xref:Mirroring_Policies_Overview_{context}[].
. Optional: In the *HTTP Proxy Policy* field, select an HTTP proxy.
. Optional: You can clear the *Unprotected* checkbox to require a subscription entitlement certificate for accessing this repository.
By default, the repository is published through HTTP.
. Optional: In the *SSL CA Cert* field, select the SSL CA Certificate for the repository.
. Optional: In the *SSL Client cert* field, select the SSL Client Certificate for the repository.
. Optional: In the *SSL Client Key* field, select the SSL Client Key for the repository.
. Click *Save* to create the repository.
. Select your repository.
. From the *Select Action* menu, select *Sync Now*.
