[id="enabling-the-project-client-name-repository_{context}"]
= Enabling the {project-client-name} repository

Enable the {project-client-name} repository for every major version of {RHEL} that you intend to run on your hosts.
After enabling a Red Hat repository, {Project} creates a Product for this repository automatically.

.Prerequisites
* Ensure that a subscription manifest has been imported to your organization.
For more information, see {ContentManagementDocURL}Managing_Red_Hat_Subscriptions_content-management[Managing Red Hat Subscriptions] in _{ContentManagementDocTitle}_.
ifeval::["{mode}" == "disconnected"]
* Ensure that all required content ISO images are imported into {ProjectServer}.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Red Hat Repositories*.
. Ensure that the *RPM* repository type is selected.
. In the search field, type `name ~ "Satellite Client"` and press *Enter*.
Optionally, enable the *Recommended Repositories* filter to limit the results.
. Click the name of the required repository to expand the repository set.
. For the required architecture, click the *+* icon to enable the repository.
