[id="recovering-from-disaster-with-active-and-passive-server-with-external-storage"]
= Recovering from disaster with active and passive server with external storage

If your active {ProjectServer} fails, detach it from the network-attached storage (NAS) and make sure your passive server can access the data stored on the NAS.
This turns the passive server into your new active server.

.Procedure
. Verify that the failed active server is powered off or fully detached from the NAS.
This ensures that the failed server cannot keep writing to the NAS, which helps prevent further data corruption on the connected databases.
// Is foreman-maintain service stop enough?
. Switch DNS records of the active server with the DNS records of the passive server.
This ensures that hosts remain connected and you do not need to re-register them.
. If your NAS was mounted by both your active and passive servers, your passive server can already access the data.
. If your NAS was mounted only to your active server, re-mount it to your passive server.
. Assess the functionality of your new active {ProjectServer}.
See xref:Retrieving_the_Status_of_Services_{context}[].
// What about the old active server? Does it make sense to troubleshoot it and try to bring it back?
