[id="deploying-red-hat-insights-by-using-the-ansible-role_{context}"]
= Deploying Red{nbsp}Hat Insights by using the Ansible role

The *RedHatInsights.insights-client* Ansible role is used to automate the installation and registration of hosts with Insights.
For more information about adding this role to your {Project}, see {ManagingConfigurationsAnsibleDocURL}Getting_Started_with_Ansible_in_{project-context}_ansible[Getting Started with Ansible in {Project}] in _{ManagingConfigurationsAnsibleDocTitle}_.

.Procedure
. Add the *RedHatInsights.insights-client* role to the hosts.
+
For new hosts, see xref:Creating_a_Host_{context}[].
+
For existing hosts, see {ManagingConfigurationsAnsibleDocURL}Using_Ansible_Roles_to_Automate_Repetitive_Tasks_on_Clients_ansible[Using Ansible Roles to Automate Repetitive Tasks on Clients] in _{ManagingConfigurationsAnsibleDocTitle}_.
+
. To run the *RedHatInsights.insights-client* role on your host, navigate to *Hosts* > *All Hosts* and click the name of the host that you want to use.
. On the host details page, expand the *Schedule a job* dropdown menu.
. Click *Run Ansible roles*.
