:_mod-docs-content-type: PROCEDURE

[id="provisioning-from-a-builder-image-on-{smart-proxy-context}"]
= Provisioning from a {LoraxCompose} image on {SmartProxy}

You can upload a {LoraxCompose} image to {Project} and use this image to provision hosts by using network boot.

ifndef::satellite[]
[NOTE]
====
This feature is available for {EL} hosts only.
====
endif::[]

When you provision from a {LoraxCompose} image, Anaconda installer partitions disks, downloads and mounts the image, and copies files over to a host.

.Prerequisites
* An existing TAR image created by using {LoraxCompose}.
Ensure that your blueprint to build the image includes a kernel package.

.Procedure
. On {Project}, create a custom product, add a custom file repository to this product, and upload the image to the repository.
For more information, see {ContentManagementDocURL}Importing_Individual_ISO_Images_and_Files_content-management[Importing individual ISO images and files] in _{ContentManagementDocTitle}_.
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*.
. Select the host group that you want to use.
. Click the *Parameters* tab, and then click *Add Parameter*.
. In the *Name* field, enter `kickstart_liveimg`.
. From the *Type* list, select *string*.
. In the *Value* field, enter the URL or a relative path that points to the image, for example:
* URL: `\https://{smartproxy-example-com}/pulp/content/_My_Organization_Label_/Library/custom/_My_Product_Label_/_My_Repository_Label_/_My_Image_Name_.tar`
* Relative path: `custom/_product_/_repository_/_image_name.tar_`
. Click *Submit* to save your changes.

.Additional resources
* xref:using-network-boot-to-provision-hosts[]
