[id="configuring-remote-execution-for-pull-client-on-{project-context}-server_{context}"]
= Configuring Remote Execution for Pull Client on {ProjectServer}

By default, Remote Execution uses SSH as the transport mechanism for the Script provider.
However, Remote Execution also offers pull-based transport, which you can use if your infrastructure prohibits outgoing connections from {Project} to hosts.

This comprises `pull-mqtt` mode on {Project} in combination with a pull client running on hosts.
If you still use Katello Agent, configure the `pull-mqtt` mode for migration which is a deprecated method of pull-based transport.

[NOTE]
====
The `pull-mqtt` mode works only with the Script provider.
Ansible and other providers will continue to use their default transport settings.
====

To use `pull-mqtt` mode on {ProjectServer}, follow the procedure below:

.Procedure
. Enable the pull-based transport on your {ProjectServer}:
+
[options="nowrap" subs="quotes,attributes"]
----
 # {installer-scenario} \
--foreman-proxy-plugin-remote-execution-script-mode pull-mqtt
----
. Configure the firewall to allow MQTT service on port 1883:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# firewall-cmd --add-port="1883/tcp"
# firewall-cmd --runtime-to-permanent
----
+
In `pull-mqtt` mode, hosts subscribe for job notifications to either your {Project} or any {SmartProxyServer} through which they are registered.
Therefore, it is recommended to ensure that {ProjectServer} sends remote execution jobs to that same {Project} (or {SmartProxy}).
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. On the *Content* tab, set the value of *Prefer registered through {SmartProxy} for remote execution* to *Yes*.

After you set up the pull-based transport on {Project}, you must also configure it on each host.
For more information, see {ManagingHostsDocURL}transport-modes-for-remote-execution_managing-hosts[Transport Modes for Remote Execution] in _{ManagingHostsDocTitle}_.
