:_mod-docs-content-type: PROCEDURE

[id="Preparing_SUSE_Installation_Media_{context}"]
= Preparing SUSE installation media

Use this procedure to extract the SUSE installation medium on your {ProjectServer} to provision hosts in a disconnected environment.
This example prepares the installation medium for {SLES} {client-os-major}.{client-os-minor}.

.Procedure
. Download the `SLES {client-os-major}.{client-os-minor}` installation medium from https://www.suse.com/download/sles/[suse.com/download/sles].
. Download the signature and checksum from https://www.suse.com/support/security/download-verification/[suse.com].
. Transfer the `.iso` image, the signature, and the checksum from your local machine to {ProjectServer} using `scp`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso root@{foreman-example-com}:/tmp/
# scp SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso.sha256 root@{foreman-example-com}:/tmp/
# scp SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso.sha256.asc root@{foreman-example-com}:/tmp/
----
. On your {ProjectServer}, verify the integrity and authenticity of the `.iso` image using GPG public keys:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cd /tmp
# gpg --verify SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso.sha256.asc SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso.sha256
# echo '{client-iso-sha256-checksum} SLES-{client-os-major}-{client-os-minor}-Full-x86_64-GM.install.iso' | sha256sum --check
----
. Mount the `.iso` image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mount SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso /mnt
----
. Copy the content of the mounted installation medium to the `pub` directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /var/www/html/pub/installation_media/sles/{client-os-major}.{client-os-minor}
# cp -a /mnt/* /var/www/html/pub/installation_media/sles/{client-os-major}.{client-os-minor}/
----
. Unmount and delete the `.iso` image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cd
# umount /mnt
# rm -f /tmp/SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso
# rm -f /tmp/SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso.sha256
# rm -f /tmp/SLES-{client-os-major}.{client-os-minor}-Full-x86_64-GM.install.iso.sha256.asc
----

You can use the path to the local installation media files when creating an installation medium, for example `\http://{foreman-example-com}/pub/installation_media/sles/{client-os-major}.{client-os-minor}/`.
For more information, see {ProvisioningDocURL}adding-installation-media-by-using-web-ui[Adding installation media to {Project} by using {ProjectWebUI}] in _{ProvisioningDocTitle}_.
