[id="configuring-repositories_{context}"]

= Configuring Repositories

Use this procedure to enable the repositories that are required to install {ProductName}. Choose from the available list which operating system and version you are installing on:

ifdef::foreman-el,katello[]
* xref:#repositories-centos-8[CentOS 8]
* xref:#repositories-centos-7[CentOS 7]
endif::[]
ifdef::foreman-el,katello,satellite[]
* xref:#repositories-rhel-8[{RHEL} 8]
* xref:#repositories-rhel-7[{RHEL} 7]
endif::[]
ifdef::foreman-deb[]
* xref:#repositories-debian-11[Debian 11 (Bullseye)]
* xref:#repositories-ubuntu-2004[Ubuntu 20.04 (Focal)]
endif::[]

ifdef::foreman-el,katello[]
== [[repositories-centos-8]]CentOS 8

:distribution: el
:distribution-major-version: 8
:package-manager: dnf

include::proc_configuring-repositories-el.adoc[]

ifdef::foreman-el[]
+
. Enable the Foreman module:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-manager} module enable foreman:el8
----
endif::[]

ifdef::katello[]
+
. Enable `powertools` repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-manager} config-manager --set-enabled powertools
----

+
. Enable the Katello and Pulpcore modules:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-manager} module enable katello:el8 pulpcore:el8
----
endif::[]

If this fails to enable, see {InstallingProjectDocURL}troubleshooting_dnf_modules[DNF module enablement troubleshooting].

== [[repositories-centos-7]]CentOS 7

:distribution: el
:distribution-major-version: 7
:package-manager: yum
include::proc_configuring-repositories-el.adoc[]

+
. Install the `epel-release` and `centos-release-scl-rh` packages:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-manager} install epel-release centos-release-scl-rh
----
endif::[]

ifdef::foreman-el,katello,satellite[]
== [[repositories-rhel-8]]{RHEL} 8

:distribution: rhel
:distribution-major-version: 8
:package-manager: dnf

. Disable all repositories:
+
[options="nowrap"]
----
# subscription-manager repos --disable "*"
----
+

. Enable the following repositories:
+
[options="nowrap" subs="+quotes,attributes"]
ifdef::foreman-el,katello[]
----
# subscription-manager repos --enable={RepoRHEL8BaseOS} \
--enable={RepoRHEL8AppStream}
----
endif::[]
ifdef::satellite[]
----
# subscription-manager repos --enable={RepoRHEL8BaseOS} \
--enable={RepoRHEL8AppStream} \
--enable={RepoRHEL8ServerSatelliteServerProductVersion} \
--enable={RepoRHEL8ServerSatelliteMaintenanceProductVersion}
----
endif::[]
+

ifdef::foreman-el,katello[]
include::proc_configuring-repositories-el.adoc[]
endif::[]

. Enable the module:
+
[options="nowrap"]
ifdef::foreman-el[]
----
# dnf module enable foreman:el8
----
endif::[]
ifdef::katello[]
----
# dnf module enable katello:el8 pulpcore:el8
----
endif::[]
ifdef::satellite[]
----
# dnf module enable satellite:el8
----
+
[NOTE]
====
Enablement of the module `satellite:el8` warns about a conflict with `postgresql:10` and `ruby:2.5` as these modules are set to the default module versions on {RHEL} 8. The module `satellite:el8` has a dependency for the modules `postgresql:12` and `ruby:2.7` that will be enabled with the `satellite:el8` module. These warnings do not cause installation process failure, hence can be ignored safely.

For more information about modules and lifecycle streams on {RHEL} 8, see https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle.
====
endif::[]
endif::[]

+

ifdef::foreman-el,katello,satellite[]

== [[repositories-rhel-7]]{RHEL} 7

:distribution: rhel
:distribution-major-version: 7
:package-manager: yum

. Disable all repositories:
+
[options="nowrap"]
----
# subscription-manager repos --disable "*"
----
+
. Enable the following repositories:
ifdef::foreman-el,katello[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL7Server} \
--enable {RepoRHEL7ServerOptional} \
--enable {RepoRHEL7ServerSoftwareCollections}
----
+
. Install the `epel-release-latest-{distribution-major-version}.noarch.rpm` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-manager} localinstall https://dl.fedoraproject.org/pub/epel/epel-release-latest-{distribution-major-version}.noarch.rpm
----
endif::[]

ifdef::satellite[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL7Server} \
--enable={RepoRHEL7ServerSoftwareCollections} \
--enable={RepoRHEL7ServerAnsible} \
--enable={RepoRHEL7ServerSatelliteServerProductVersion} \
--enable={RepoRHEL7ServerSatelliteMaintenanceProductVersion}
----
endif::[]
+

ifdef::foreman-el,katello[]
include::proc_configuring-repositories-el.adoc[]
endif::[]

NOTE: If you are installing {ProductName} as a virtual machine hosted on {oVirt}, you must also enable the *Red{nbsp}Hat Common* repository, and install {oVirt} guest agents and drivers.
For more information, see https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/virtual_machine_management_guide/installing_guest_agents_and_drivers_linux#Installing_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux[Installing the Guest Agents and Drivers on {RHEL}] in the _Virtual Machine Management Guide_.
endif::[]

ifdef::foreman-deb[]
== [[repositories-debian-11]]Debian 11 (Bullseye)

:distribution-codename: bullseye
include::proc_configuring-repositories-deb.adoc[]

== [[repositories-ubuntu-2004]]Ubuntu 20.04 (Focal)

:distribution-codename: focal
include::proc_configuring-repositories-deb.adoc[]

endif::[]
