:_mod-docs-content-type: PROCEDURE

[id="Performing_a_Full_Backup_{context}"]
= Performing a full backup of {ProjectServer} or {SmartProxyServer}

[role="_abstract"]
{ProjectName} uses the `{foreman-maintain} backup` command to make backups.

.Remote databases
You can use the `{foreman-maintain} backup` command to back up remote databases.

.Backing up to a remote NFS share
To enable {Project} to save the backup to an NFS share, ensure that the `root` user of your {ProjectServer} or {SmartProxyServer} can write to the NFS share.
NFS export options such as `root_squash` and `all_squash` are known to prevent this.

ifndef::orcharhino[]
For more information, see link:{RHELDocsBaseURL}9/html/configuring_and_using_network_file_services/deploying-an-nfs-server_configuring-and-using-network-file-services[{RHEL} _Configuring and using network files services_] and link:{RHELDocsBaseURL}9/html/securing_networks/securing-network-services_securing-networks#export-options-for-securing-an-nfs-server_securing-the-nfs-service[{RHEL} _Securing network services_].
endif::[]

.Prerequisites
* Ensure that your backup location has sufficient available disk space to store the backup.
ifdef::katello,orcharhino,satellite[]
For more information, see xref:Estimating_the_Size_of_a_Backup_{context}[].
endif::[]

[WARNING]
====
Request other users of {ProjectServer} or {SmartProxyServer} to save any changes and warn them that {Project} services are unavailable for the duration of the backup.
Ensure no other tasks are scheduled for the same time as the backup.
====

.Procedure
* On {ProjectServer}, perform a full backup:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline _/var/{project-context}-backup_
----
* On {SmartProxyServer}, perform a full backup:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline _/var/foreman-proxy-backup_
----
