:_mod-docs-content-type: PROCEDURE

[id="changing-the-http-proxy-policy-for-a-repository-by-using-cli"]
= Changing the HTTP proxy policy for a repository by using Hammer CLI

[role="_abstract"]
You can set an HTTP proxy policy to synchronize repositories to {ProjectServer}.
Use an HTTP proxy for repository synchronization if your network restricts access to the internet.

To set the same HTTP proxy policy for all repositories in a product, see xref:Changing_the_HTTP_Proxy_Policy_for_a_Product_{context}[].

.Procedure
* Specify the HTTP proxy policy you want to use:
+
[subs="+quotes"]
----
$ hammer repository update \
--http-proxy-policy _My_HTTP_Proxy_Policy_ \
--id _My_Repository_ID_
----
+
Specify one of the following options for `--http-proxy-policy`:
+
** `none`: Do not use an HTTP proxy, even if a global default HTTP proxy is configured.
** `global_default_http_proxy`: Use the global default HTTP proxy setting.
** `use_selected_http_proxy`: Specify an HTTP proxy using either `--http-proxy _My_HTTP_Proxy_Name_` or `--http-proxy-id _My_HTTP_Proxy_ID_`.
To add a new HTTP proxy to {Project}, see xref:adding-an-http-proxy-by-using-cli[].
