[id="Importing_a_Repository_from_a_web_server_{context}"]
= Importing a repository from a web server

You can import an exported repository directly from a web server into an organization on another {ProjectServer}.
For more information about exporting the content of a repository, see xref:Exporting_a_Repository_{context}[].

.Prerequisites
* The exported files must be in a syncable format.
* The exported files must be accessible through HTTP/HTTPS.
ifdef::client-content-dnf[]
* If the export contains any Red Hat repositories, the manifest of the importing organization must contain subscriptions for the products contained within the export.
endif::[]
* The user importing the content view version must have the _Content Importer_ Role.

.Procedure
. Select the organization into which you want to import.
. To import the repository to {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer content-import repository \
--organization="_My_Organization_" \
--path=http://_{server-example-com}_/pub/exports/2021-02-25T21-15-22-00-00/
----
