:_mod-docs-content-type: PROCEDURE

[id="inspecting-available-errata-by-using-web-ui"]
= Inspecting available errata by using {ProjectWebUI}

[role="_abstract"]
View and filter available errata to find applicable or installable updates and review advisory metadata before promoting content or patching hosts.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Content Types* > *Errata* to view the list of available errata.
. Use the filtering tools at the top of the page to limit the number of displayed errata:
+
* Select the repository to be inspected from the list.
*All Repositories* is selected by default.
* The *Applicable* checkbox is selected by default to view only applicable errata in the selected repository.
Select the *Installable* checkbox to view only errata marked as installable.
* To search the table of errata, type the query in the *Search* field in the form of:
+
[subs="+quotes"]
----
__parameter operator value__
----
+
Automatic suggestion works as you type.
You can also combine queries with the use of *and* and *or* operators.
For example, to display only security advisories related to the *kernel* package, type:
+
----
type = security and package_name = kernel
----
+
Press *Enter* to start the search.
. Click the *Errata ID* of the erratum you want to inspect:
+
* The *Details* tab contains the description of the updated package as well as documentation of important fixes and enhancements provided by the update.
* On the *Content Hosts* tab, you can install installable errata on selected hosts.
* The *Repositories* tab lists repositories that already contain the erratum.
You can filter repositories by the environment and content view, and search for them by the repository name.

.Additional resources
* xref:Parameters_Available_for_Errata_Search_{context}[]
* {AdministeringDocURL}Supported_Operators_for_Granular_Search_admin[Supported operators for granular search in _{AdministeringDocTitle}_]
