[id="Creating_a_VMware_User_{context}"]
= Creating a VMware User

The VMware vSphere server requires an administration-like user for {ProjectServer} communication.
For security reasons, do not use the `administrator` user for such communication.
Instead, create a user with the following permissions:

For VMware vCenter Server version 6.7, set the following permissions:

* All Privileges -> Datastore -> Allocate Space, Browse datastore, Update Virtual Machine files, Low level file operations
* All Privileges -> Network -> Assign Network
* All Privileges -> Resource -> Assign virtual machine to resource pool
* All Privileges -> Virtual Machine -> Change Config (All)
* All Privileges -> Virtual Machine -> Interaction (All)
* All Privileges -> Virtual Machine -> Edit Inventory (All)
* All Privileges -> Virtual Machine -> Provisioning (All)

Note that the same steps also apply to VMware vCenter Server version 7.0.

For VMware vCenter Server version 6.5, set the following permissions:

* All Privileges -> Datastore -> Allocate Space, Browse datastore, Update Virtual Machine files, Low level file operations
* All Privileges -> Network -> Assign Network
* All Privileges -> Resource -> Assign virtual machine to resource pool
* All Privileges -> Virtual Machine -> Configuration (All)
* All Privileges -> Virtual Machine -> Interaction (All)
* All Privileges -> Virtual Machine -> Inventory (All)
* All Privileges -> Virtual Machine -> Provisioning (All)
