[id="Managing_Packages_on_the_Base_Operating_System_{context}"]
= Managing Packages on the Base Operating System of {ProjectServer} or {SmartProxyServerTitle}

To install and update packages on the {ProjectServer} or {SmartProxyServer} base operating system, you must enter the `{foreman-maintain} packages` command.
{Project} prevents users from installing and updating packages with `yum` because `yum` might also update the packages related to {ProjectServer} or {SmartProxyServer} and result in system inconsistency.

[IMPORTANT]
====
The `{foreman-maintain} packages` command restarts some services on the operating system where you run it because it runs the `{foreman-installer}` command after installing packages.
====

.Procedure
* To install packages on {ProjectServer} or {SmartProxyServer}, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-install} _package_1_ _package_2_
----
* To update specific packages on {ProjectServer} or {SmartProxyServer}, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {package-update-project} _package_1_ _package_2_
----
* To update all packages on {ProjectServer} or {SmartProxyServer}, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {package-update-project}
----

.Using yum to Check for Package Updates
If you want to check for updates using `yum`, enter the command to install and update packages manually and then you can use `yum` to check for updates:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} packages unlock
# yum check update
# {foreman-maintain} packages lock
----

Updating packages individually can lead to package inconsistencies in {ProjectServer} or {SmartProxyServer}.
For more information about updating packages in {ProjectServer}, see {UpgradingDocURL}updating_satellite_server_to_next_minor_version[Updating {ProjectServer}].

.Enabling yum for {ProjectServer} or {SmartProxyServerTitle} Package Management
If you want to install and update packages on your system using `yum` directly and control the stability of the system yourself, enter the following command:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} packages unlock
----

.Restoring Package Management to the Default Settings
If you want to restore the default settings and enable {ProjectServer} or {SmartProxyServer} to prevent users from installing and updating packages with `yum` and ensure the stability of the system, enter the following command:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} packages lock
----
