[id="Installing_and_Configuring_the_Puppet_Agent_on_a_Host_Manually_{context}"]
= Installing and Configuring Puppet Agent on a Host Manually

Install and configure the Puppet agent on a host manually.

.Prerequisites
* The host must have a Puppet environment assigned to it.
ifdef::satellite[]
* The *{project-client-name}* repository must be enabled and synchronized to {ProjectServer}, and enabled on the host.
For more information, see {ContentManagementDocURL}Importing_Content_content-management[Importing Content] in _{ContentManagementDocTitle}_.
endif::[]
ifndef::satellite[]
* Ensure a repository containing the Puppet agent is enabled on the host, for example https://apt.puppet.com/[apt.puppet.com] or https://yum.puppet.com/[yum.puppet.com].
endif::[]

.Procedure
. Log in to the host as the `root` user.
. Install the Puppet agent package.
* On hosts running {EL} 8 and above:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# dnf install puppet-agent
----
* On hosts running {EL} 7 and below:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# yum install puppet-agent
----
ifndef::satellite[]
* On hosts running Debian:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# apt-get install puppet-agent
----
* On hosts running SUSE Linux Enterprise Server:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# zypper install puppet-agent
----
endif::[]
. Add the Puppet agent to `PATH` in your current shell using the following script:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
. /etc/profile.d/puppet-agent.sh
----
. Configure the Puppet agent.
Set the `environment` parameter to the name of the Puppet environment to which the host belongs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet config set server _{foreman-example-com}_ --section agent
# puppet config set environment _My_Puppet_Environment_ --section agent
----
. Start the Puppet agent service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet resource service puppet ensure=running enable=true
----
. Create a certificate for the host:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet ssl bootstrap
----
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*.
. From the list in the *Actions* column for the required {SmartProxyServer}, select *Certificates*.
. Click *Sign* to the right of the required host to sign the SSL certificate for the Puppet agent.
. On the host, run the Puppet agent again:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet ssl bootstrap
----

ifndef::managing-configurations-puppet[]
.Additional Resources
* For more information about Puppet, see {ManagingConfigurationsPuppetDocURL}[_{ManagingConfigurationsPuppetDocTitle}_].
endif::[]