[[Browsing_Repository_Content_Using_an_Organization_Debug_Certificate]]
= Browsing Repository Content Using an Organization Debug Certificate

You can view an organization's repository content using a web browser or using the API if you have a debug certificate for that organization.

.Prerequisites
. Create and download an organization certificate as described in xref:Creating_an_Organization_Debug_Certificate[].
. Open the X.509 certificate, for example, for the default organization:
+
----
$ vi 'Default Organization-key-cert.pem'
----
. Copy the contents of the file from `-----BEGIN RSA PRIVATE KEY-----` to `-----END RSA PRIVATE KEY-----`, into a `key.pem` file.
. Copy the contents of the file from `-----BEGIN CERTIFICATE-----` to `-----END CERTIFICATE-----`, into a `cert.pem` file.

.Procedure

To use a browser, you must first convert the X.509 certificate to a format your browser supports and then import the certificate.

.For Firefox Users

To use an organization debug certificate in Firefox, complete the following steps:

. To create a PKCS12 format certificate, enter the following command:
+
[subs="+quotes"]
----
$ openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -export -in cert.pem -inkey key.pem -out _organization_label_.pfx -name _organization_name_
----
+
. In the Firefox browser, navigate to *Edit* > *Preferences* > *Advanced Tab*.
. Select *View Certificates*, and click the *Your Certificates* tab.
. Click *Import* and select the `.pfx` file to load.
. In the address bar, enter a URL in the following format to browse for repositories:
+
[options="nowrap" subs="+quotes,attributes"]
----
http://_{foreman-example-com}_/pulp/repos/_organization_label_
----
+
Pulp uses the organization label, therefore, you must enter the organization label into the URL.

.For CURL Users

To use the organization debug certificate with CURL, enter the following command:
[options="nowrap" subs="+quotes,attributes"]
----
$ curl -k --cert cert.pem --key key.pem \
http://_{foreman-example-com}_/pulp/repos/Default_Organization/Library/content/dist/rhel/server/7/7Server/x86_64/sat-tools/{ProductVersion}/os/
----
Ensure that the paths to `cert.pem` and `key.pem` are the correct absolute paths otherwise the command fails silently.
