[id="Creating_Snapshots_of_a_Managed_Host_{context}"]
= Creating Snapshots of a Managed Host

You can use the Snapshot Management plug-in to create snapshots of managed hosts.

.Prerequisites
* You have installed the Snapshot Management plug-in successfully.
ifndef::orcharhino[]
For more information, see https://github.com/ATIX-AG/foreman_snapshot_management[github.com/ATIX-AG/foreman_snapshot_management].
endif::[]
* Your managed host is running on VMware vSphere or Proxmox.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts > All Hosts* and select a host.
. On the *Snapshots* tab, click *Create Snapshot*.
. Enter a *Name*.
. Optional: Enter a *Description*.
. Optional: In the *Snapshot Mode* field, select *Memory* if you want to include the RAM in your snapshot or *Quiecse* if you want to ensure the full state of the VM is written to disk before creating the snapshot.
. Click *Submit* to create a snapshot.

[CAUTION]
====
Keeping more than three snapshots per host slows down the creation and rollback process.
Consider deleting older snapshots when creating new ones.
====
