[id="customizing-registration-by-using-snippets"]
= Customizing registration by using snippets

You can customize the registration process by creating snippets with pre-defined names.
The `Global Registration` template includes these snippets automatically.
To add custom steps to registration, create one or both of the following snippets:

`before_registration`:: This snippet is loaded and executed by the `Global Registration` template before registering your host to {Project}.
`after_registration`:: This snippet is loaded and executed by the `Global Registration` template after registering your host to {Project}.

Ensure you name the snippets precisely.
Otherwise, the `Global Registration` template cannot load them.

.Prerequisites
* Your {Project} account has a role that grants the `view_provisioning_templates` and `create_provisioning_templates` permissions.
* You have selected a particular organization and location context.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Templates* > *Provisioning Templates*.
. Click *Create Template*.
. In the *Name* field, enter the name of the required snippet, `before_registration` or `after_registration`.
. In the template editor, create your snippet.
. On the *Type* tab, select *Snippet*.
. Click *Submit*.
