[id="Creating_an_Activation_Key_to_Consume_the_Content_View_{context}"]
= Creating an Activation Key to Consume the Content View

Use the following procedure to create an activation key that you can use to subscribe your hosts to content managed by {Project}.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Activation keys* and click *Create Activation Key*.
. In the *Name* field, enter *CentOS* or the name of your new activation key.
. In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the *Library*.
. From the *Content View* list, select *Centos Content View*.
. Click *Save*.
. Click the *Subscriptions* tab on the Activation Key's details page.
. Click the *Add* tab.
. Select your new *CentOS Stream* product in the table.
. Click *Add Selected* to save.

Use your activation key to register a host to the Content View.
For more information on registering a host, see {ManagingHostsDocURL}registering-a-host_managing-hosts[Registering a Host] in the _Managing Hosts_ guide.
