[id="Keeping_Track_of_Your_Exports_{context}"]
= Keeping track of your exports

{Project} keeps records of all exports.
Each time you export content on the upstream {ProjectServer}, the export is recorded and maintained for future querying.
You can use the records to organize and manage your exports, which is useful especially when exporting incrementally.

When exporting content from the upstream {ProjectServer} for several downstream {ProjectServer}s, you can also keep track of content exported for specific servers.
This helps you track which content was exported and to where.

Use the `--destination-server` argument during export to indicate the target server.
This option is available for all `content-export` operations.

.Tracking destinations of Library exports
* Specify the destination server when exporting the Library:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-export complete library \
--destination-server=_My_Downstream_Server_1_ \
--organization="_My_Organization_" \
--version=1.0
----

.Tracking destinations of content view exports
* Specify the destination server when exporting a content view version:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-export complete version \
--content-view="_Content_View_Name_" \
--destination-server=_My_Downstream_Server_1_ \
--organization="_My_Organization_" \
--version=1.0
----

.Querying export records
* List content exports using the following command:
+
[subs="+quotes"]
----
$ hammer content-export list --organization="_My_Organization_"
----
