[id="registering-a-host_{context}"]
= Registering a host

You can register a host by using registration templates and set up various integration features and host tools during the registration process.

.Prerequisites
* Your {Project} account has the *Register hosts* role assigned or a role with equivalent permissions.
* You must have root privileges on the host that you want to register.
* You must have installed either `curl` or `wget` on the host that you want to register.
* You have configured your host for registration.
For more information, see xref:Configuring_a_Host_for_Registration_{context}[].
ifdef::satellite,orcharhino,katello[]
include::snip_prerequisite-activation-key-available.adoc[]
endif::[]
ifdef::satellite[]
* Optional: If you want to register your host to Red{nbsp}Hat Insights, you must synchronize the `{RepoRHEL8BaseOS}` and `{RepoRHEL8AppStream}` repositories and make them available in the activation key that you use.
This is required to install the `insights-client` package on your host.
endif::[]
ifdef::katello,orcharhino,satellite[]
include::snip_prerequisite-project-client-repository-ak.adoc[]
This repository is required for the remote execution pull client, Puppet agent, Tracer, and other tools.
endif::[]
include::snip_prerequisite-configured-smart-proxy-registration-provisioning.adoc[]
ifdef::katello,orcharhino,satellite[]
* If your {ProjectServer} or {SmartProxyServer} is behind an HTTP proxy, configure the Subscription Manager on your host to use the HTTP proxy for connection.
endif::[]
ifdef::satellite[]
For more information, see https://access.redhat.com/solutions/65300[How to access Red Hat Subscription Manager (RHSM) through a firewall or proxy] in the _Red{nbsp}Hat Knowledgebase_.
endif::[]
ifdef::orcharhino[]
ifdef::debian[]
* Ensure that your host has `gpg` installed to import the GPG public key.
endif::[]
endif::[]
ifndef::satellite[]
* You have configured the operating system entry on {Project} for {client-os}.
endif::[]
ifdef::orcharhino[]
+
include::snip_creating-os-on-orcharhino.adoc[]
endif::[]
ifdef::orcharhino[]
ifdef::suse_linux_enterprise_server[]
include::snip_prerequisites-content-for-sles.adoc[]
endif::[]
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Register Host*.
. Enter the details for how you want the registered host to be configured.
* If you select a host group from the *Host Group* list, the following fields inherit their values from the host group:
+
** *Operating system*
ifdef::katello,satellite,orcharhino[]
** *Activation Keys*
endif::[]
** *Lifecycle environment*
ifdef::katello,satellite,orcharhino[]
* A {SmartProxy} behind a load balancer takes precedence over the {SmartProxy} selected in the {ProjectWebUI} as the content source of the host.
. On the *General* tab, in the *Activation Keys* field, enter one or more activation keys to assign to your host.
endif::[]
. Click *Generate* to generate a `curl` command.
. Run the `curl` command as `root` on the host that you want to register.
After registration completes, any Ansible roles assigned to a host group you specified when configuring the registration template will run on the host.

The registration details that you can specify include the following:

* On the *General* tab, in the *{SmartProxy}* field, you can select the {SmartProxy} to register your host through.
A {SmartProxy} behind a load balancer takes precedence over a {SmartProxy} selected in the {ProjectWebUI} as the content source of the host.
* On the *General* tab, in the *Download utility* field, you can select `wget` if you want to register your host by using a `wget` command.
By default, {Project} generates a `curl` command.
* On the *General* tab, you can select the *Insecure* option to make the first call insecure.
During this first call, your host downloads the CA file from {Project}.
Your host will use this CA file to connect to {Project} with all future calls making them secure.
+
{Team} recommends that you avoid insecure calls.
+
If an attacker, located in the network between {Project} and your host, fetches the CA file from the first insecure call, the attacker will be able to access the content of the API calls to and from your host and the JSON Web Tokens (JWT).
Therefore, if you have chosen to deploy SSH keys during registration, the attacker will be able to access your host using the SSH key.
* On the *Advanced* tab, in the *Repositories* field, you can list repositories to be added before the registration is performed.
You do not have to specify repositories if you provide them in an activation key.
ifdef::orcharhino[]
ifdef::debian,ubuntu[]
+
To verify synchronized {client-content-type} content, you can use the `pulp_deb_signing.key` file on your {SmartProxy} as GPG public key.
For example, `\https://{foreman-example-com}/pub/pulp_deb_signing.key`.
endif::[]
ifndef::debian,ubuntu[]
+
To verify synchronized {client-content-type} content, you can use {Project} API to get associated GPG public keys of repositories.
For example, `\https://{foreman-example-com}/katello/api/v2/repositories/_My_Repository_ID_/gpg_key_content`.
endif::[]
endif::[]
* On the *Advanced* tab, you can configure remote execution, Red{nbsp}Hat Insights, and packages to be installed.
* On the *Advanced* tab, in the *Token lifetime (hours)* field, you can change the validity duration of the JSON Web Token (JWT) that {Project} uses for authentication.
The duration of this token defines how long the generated registration command works.
+
Note that {Project} applies the permissions of the user who generates the registration command to authorization of your host.
If the user loses or gains additional permissions, the permissions of the JWT change too.
Therefore, do not delete, block, or change permissions of the user during the token duration.
+
The scope of the JWTs is limited to the registration endpoints only and cannot be used anywhere else.

[NOTE]
====
{Project} generates the registration command with parameters that search resources by ID.
You can edit the registration command to search the following resources by title:

Organization:: URL fragment example: `organization=My%20Organization` or `organization=My+Organization`
Location:: URL fragment example: `location=My%20Location` or `location=My+Location`
Host group:: If a host group is nested, include the parent group separated with the slash character (`/`).
+
URL fragment example: `hostgroup=Parent%20Group%2FMy%20Host%20Group`
Operating system:: URL fragment example: `operatingsystem=My%20Operating%20System` or `operatingsystem=My+Operating+System`

The parameter values must be URL encoded.
====

.CLI procedure
. Use the `hammer host-registration generate-command` to generate the registration command to register your host.
. On your host that you want to register, run the registration command as `root`.

For more information, see the Hammer CLI help with `hammer host-registration generate-command --help`.

.Ansible procedure
* Use the `{ansible-namespace}.registration_command` module.

For more information, see the Ansible module documentation with `ansible-doc {ansible-namespace}.registration_command`.

.API procedure
* Use the `POST /api/registration_commands` resource.

For more information, see the full API reference at `\https://{foreman-example-com}/apidoc/v2.html`.

.Next steps
* To set up monitoring of outdated services and applications using Tracer, see {ManagingHostsDocURL}enabling-tracer-on-a-host_managing-hosts[Enabling Tracer on a host] in _{ManagingHostsDocTitle}_.
