[id="Promoting_a_Content_View_{context}"]
= Promoting a Content View

Use this procedure to promote Content Views across different lifecycle environments.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-promoting-a-content-view_{context}[].

.Permission Requirements for Content View Promotion

Non-administrator users require two permissions to promote a Content View to an environment:

. `promote_or_remove_content_views`
. `promote_or_remove_content_views_to_environment`.

The `promote_or_remove_content_views` permission restricts which Content Views a user can promote.

The `promote_or_remove_content_views_to_environment` permission restricts the environments to which a user can promote Content Views.

With these permissions you can assign users permissions to promote certain Content Views to certain environments, but not to other environments.
For example, you can limit a user so that they are permitted to promote to test environments, but not to production environments.

You must assign both permissions to a user to allow them to promote Content Views.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Content Views* and select the Content View that you want to promote.
. Select the version that you want to promote, click the vertical ellipsis icon, and click *Promote*.
. Select the environment where you want to promote the Content View and click *Promote*.

Now the repository for the Content View appears in all environments.

[id="cli-promoting-a-content-view_{context}"]
.CLI procedure
. Promote the Content View using the `hammer content-view version promote` each time:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view version promote \
--content-view "Database" \
--version 1 \
--to-lifecycle-environment "Development" \
--organization "_My_Organization_"
# hammer content-view version promote \
--content-view "Database" \
--version 1 \
--to-lifecycle-environment "Testing" \
--organization "_My_Organization_"
# hammer content-view version promote \
--content-view "Database" \
--version 1 \
--to-lifecycle-environment "Production" \
--organization "_My_Organization_"
----
+
Now the database content is available in all environments.
+
. Alternatively, you can promote Content Views across all lifecycle environments within an organization using the following Bash script:
+
[source, Bash, options="nowrap" subs="verbatim,quotes"]
----
ORG="_My_Organization_"
CVV_ID=_My_Content_View_ID_

for i in $(hammer --no-headers --csv lifecycle-environment list --organization $ORG | awk -F, {'print $1'} | sort -n)
do
   hammer content-view version promote --organization $ORG --to-lifecycle-environment-id $i --id $CVV_ID
done
----
. Display information about your Content View version to verify that it is promoted to the required lifecycle environments:
+
[options="nowrap" subs="verbatim,quotes"]
----
# hammer content-view version info --id _3_
----
+
To register a host to your Content View, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in _{ManagingHostsDocTitle}_.
