[id="Synchronizing_Templates_Using_the_API_{context}"]
= Synchronizing Templates Using the {Project} API

.Prerequisites
* Each template must contain the location and organization that the template belongs to.
This applies to all template types.
Before you import a template, ensure that you add the following section to the template:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
<%#
kind: provision
name: _My_Provisioning_Template_
oses:
- _My_first_OS_
- _My_second_OS_
locations:
- _My_first_Location_
- _My_second_Location_
organizations:
- _My_first_Organization_
- _My_second_Organization_
%>
----

.Procedure
. Configure a version control system that uses SSH authorization, for example gitosis, gitolite, or git daemon.
. Configure the TemplateSync plug-in settings on a *TemplateSync* tab.
.. Change the *Branch* setting to match the target branch on a Git server.
.. Change the *Repo* setting to match the Git repository.
For example, for the repository located in `git@git.example.com/templates.git` set the setting into `ssh://git@git.example.com/templates.git`.
. Accept Git SSH host key as the `foreman` user:
+
[subs="+quotes"]
----
# sudo -u foreman ssh _git.example.com_
----
+
You can see the `Permission denied, please try again.` message in the output, which is expected, because the SSH connection cannot succeed yet.
. Create an SSH key pair if you do not already have it.
Do not specify a passphrase.
+
----
# sudo -u foreman ssh-keygen
----
. Configure your version control server with the public key from your {Project}, which resides in `/usr/share/foreman/.ssh/id_rsa.pub`.
. Export templates from your {ProjectServer} to the version control repository specified in the *TemplateSync* menu:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ curl -H "Accept:application/json" \
-H "Content-Type:application/json" \
-u _login_:__password__ \
-k https://_{foreman-example-com}/api/v2/templates/export \
-X POST

{"message":"Success"}
----
. Import templates to {ProjectServer} after their content was changed:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ curl -H "Accept:application/json" \
-H "Content-Type:application/json" \
-u _login_:__password__ \
-k https://_{foreman-example-com}/api/v2/templates/import \
-X POST

{“message”:”Success”}
----
+
Note that templates provided by {Project} are locked and you cannot import them by default.
To overwrite this behavior, change the `Force import` setting in the *TemplateSync* menu to `yes` or add the `force` parameter `-d '{ "force": "true" }’` to the import command.
