:_mod-docs-content-type: PROCEDURE

[id="creating-a-location-by-using-web-ui"]
= Creating a location by using {ProjectWebUI}

[role="_abstract"]
From the {ProjectWebUI}, use this procedure to create a location so that you can manage your hosts and resources by location.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Locations*.
. Click *New Location*.
. Optional: From the *Parent* list, select a parent location.
This creates a location hierarchy.
. In the *Name* field, enter a name for the location.
. Optional: In the *Description* field, enter a description for the location.
. Click *Submit*.
. If you have hosts with no location assigned, add any hosts that you want to assign to the new location, then click *Proceed to Edit*.
. Assign any infrastructure resources that you want to add to the location.
This includes networking resources, installation media, Kickstart templates, and other parameters.
You can return to this page at any time by navigating to *Administer* > *Locations* and then selecting a location to edit.
. Click *Submit* to save your changes.
