[id="creating-a-webhook_{context}"]
= Creating a Webhook

You can customize events, payloads, HTTP authentication, content type, and headers through the {ProjectWebUI}.

Use the following procedure to create a webhook in the {ProjectWebUI}.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Webhooks*.
. Click *Create new*.
. From the *Subscribe to* list, select an event.
. Enter a *Name* for your webhook.
. Enter a *Target URL*.
Webhooks make HTTP requests to pre-configured URLs.
The target URL can be a dynamic URL.
. Click *Template* to select a template.
Webhook templates are used to generate the body of the HTTP request to {ProjectServer} when a webhook is triggered.
. Enter an HTTP method.
. Optional: If you do not want activate the webhook when you create it, uncheck the *Enabled* flag.
. Click the *Credentials* tab.
. Optional: If HTTP authentication is required, enter *User* and *Password*.
. Optional: Uncheck *Verify SSL* if you do not want to verify the server certificate against the system certificate store or {Project} CA.
. On the *Additional* tab, enter the *HTTP Content Type*.
For example, `application/json`, `application/xml` or `text/plain` on the payload you define.
The application does not attempt to convert the content to match the specified content type.
. Optional: Provide HTTP headers as JSON.
ERB is also allowed.

ifndef::foreman-deb[]
When configuring webhooks with endpoints with non-standard HTTP or HTTPS ports, an SELinux port must be assigned, see {InstallingServerDocURL}configuring-selinux-to-ensure-access-on-custom-ports_{context}[Configuring SELinux to Ensure Access to {Project} on Custom Ports] in _{InstallingServerDocTitle}_.
endif::[]
