[id="logging-in-to-project-configured-with-keycloak-wildflly-as-an-authentication-source_{context}"]
= Logging in to {Project} configured with {keycloak-wildfly} as an authentication source

With {keycloak-wildfly} configured as an external authentication source for {Project}, users defined in a {keycloak-wildfly} realm can log in to {ProjectServer}.
The particular login methods available to users depend on how you configured integration between {keycloak-wildfly} and {Project}.

.Procedure

To authenticate to the {ProjectWebUI}:

* In your browser, log in to {Project} and enter your credentials.

To authenticate to the Hammer CLI:

. To authenticate to the {Project} CLI using the code grant type, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer auth login oauth \
--two-factor \
--oidc-token-endpoint 'https://_{keycloak-example-com}_/auth/realms/ssl-realm/protocol/openid-connect/token' \
--oidc-authorization-endpoint 'https://_{keycloak-example-com}_/auth' \
--oidc-client-id '_{foreman-example-com}_-foreman-openidc' \
--oidc-redirect-uri urn:ietf:wg:oauth:2.0:oob
----
+
You will be prompted to enter a success code.
. To retrieve the success code, navigate to the URL that the command returns.
. Enter the success code in CLI.

To authenticate to the {ProjectWebUI} by using {keycloak} TOTP authentication:

. In your browser, log in to {Project}.
{Project} redirects you to the {keycloak} login screen.
. Enter your username and password, and click *Log In*.
. On your first login attempt, {keycloak} requests you to configure your client by scanning the bar code and entering your PIN.
Once authenticated, your browser redirects you back to {Project} and logs you in.

ifndef::satellite,orcharhino[]
To log in to the {ProjectWebUI} using the {keycloak-wildfly} {PIV} cards:

. In Firefox, log in to {Project} and enter your credentials.
. When prompted, enter the PIN of the {PIV} card.
. Choose the certificate for authentication.
Browser verifies this certificate with {keycloak-wildfly}.
Once authenticated, browser redirects you back to {Project} and logs you in.
endif::[]
