[id="setting-an-alternative-directory-for-remote-execution-jobs-in-push-mode_{context}"]
ifeval::["{context}" == "managing-hosts"]
= Setting an Alternative Directory for Remote Execution Jobs in Push Mode

By default, {Project} uses the `/var/tmp` directory on hosts for remote execution jobs in push mode.
If the `/var/tmp` directory on your host is mounted with the `noexec` flag, {Project} cannot execute remote execution job scripts in this directory.
You can use `{foreman-installer}` to set an alternative directory for executing remote execution jobs in push mode.

:rex-default-working-dir: /var/tmp
:installer-change-working-dir-opt: --foreman-proxy-plugin-remote-execution-script-remote-working-dir
:rex-target-machine: host
endif::[]
ifeval::["{context}" == "ansible"]
= Configuring {Project} to Use an Alternative Directory to Execute Remote Jobs on Hosts

Ansible puts its own files it requires on the server side into the `/tmp` directory.
You have the option to set a different directory if required.

:rex-default-working-dir: /tmp
:installer-change-working-dir-opt: --foreman-proxy-plugin-ansible-working-dir
:rex-target-machine: {ProjectServer} or {SmartProxyServer}
endif::[]

.Procedure
. On your {rex-target-machine}, create a new directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir _/My_Remote_Working_Directory_
----
ifndef::foreman-deb[]
+
. Copy the SELinux context from the default `{rex-default-working-dir}` directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# chcon --reference={rex-default-working-dir} _/My_Remote_Working_Directory_
----
endif::[]
. Configure your {ProjectServer} or {SmartProxyServer} to use the new directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
{installer-change-working-dir-opt} _/My_Remote_Working_Directory_
----

:!rex-default-working-dir:
:!installer-change-working-dir-opt:
:!rex-target-machine:
