:_mod-docs-content-type: PROCEDURE

[id="purging-content-view-versions-by-using-cli"]
= Purging content view versions by using Hammer CLI

[role="_abstract"]
You can purge excess numbers of content view versions on {Project} to limit disk space usage.
By default, {Project} keeps every version of a content view.
Removing content view versions is a tradeoff between disk space and possibly bandwidth during content synchronizations to {SmartProxyServers} and the possibility to roll back to older content snapshots.

{Project} only considers deleting content view versions that are not part of any lifecycle environment.

.Procedure
. Optional: View your content view versions:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ hammer content-view info \
--name "_My_Content_View_Name_" \
--organization-id _My_Organization_ID_
----
. Clean up content view versions:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ hammer content-view purge \
--name "_My_Content_View_Name_" \
--organization-id _My_Organization_ID_ \
--versions-to-keep _My_Number_Of_Versions_To_Keep_
----

.Verification
* Verify that {Project} deleted the content view versions:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ hammer content-view info \
--name "_My_Content_View_Name_" \
--organization-id _My_Organization_ID_
----

.Additional resources
* {AdministeringDocURL}recovering-from-a-full-disk[Recovering from a full disk in _{AdministeringDocTitle}_]
