[id="creating-a-rolling-content-view"]
= Creating a rolling content view

You can create a rolling content view in the {ProjectWebUI}.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-rolling-content-view[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Content Views*.
. Click *Create content view*.
. In the *Create content view* window, enter a name for the content view in the *Name* field.
{Project} automatically completes the *Label* field from the name you enter.
. Optional: In the *Description* field, enter a description of the content view.
. On the *Type* tab, select *Rolling content view*.
. Click *Create content view*.
. Click *Show repositories*.
. Select the repositories that you want to add to your rolling content view.
. Click *Add repositories* to add all selected repositories to your rolling content view.

[id="cli-creating-a-rolling-content-view"]
.CLI procedure
. List all available repositories to identify IDs of repositories to add to your rolling content view:
+
[options="nowrap" subs="+quotes"]
----
$ hammer repository list \
--fields id,name,product \
--organization "_My_Organization_"
----
. Create your rolling content view:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view create \
--name "_My_Rolling_Content_View_" \
--organization "_My_Organization_" \
--repository-ids _My_List_Of_Repository_IDs_ \
--rolling
----

.Next steps
* You cannot publish or promote your rolling content view.
Instead, continue by adding it to your activation key.
For more information, see xref:Creating_an_Activation_Key_{context}[].
* To register a host to your rolling content view, see {ManagingHostsDocURL}registering-a-host_managing-hosts[Registering a host] in _{ManagingHostsDocTitle}_.
