[id="configuring-isc-dhcp-to-use-with-server"]
= Configuring ISC DHCP to use with {ProjectServer}

To configure an external DHCP server running {EL} to use with {ProductName}, you must install the ISC DHCP Service and Berkeley Internet Name Domain (BIND) utilities packages.
You must also share the DHCP configuration and lease files with {ProductName}.
The example in this procedure uses the distributed Network File System (NFS) protocol to share the DHCP configuration and lease files.

ifdef::foreman-deb[]
[NOTE]
====
This procedure describes how to run a remote ISC DHCP server on {EL} 9.
====
endif::[]

.Procedure
. Perform the following steps on the DHCP server:
.. Install the required packages:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {client-package-install-el8} dhcp-server bind-utils
----
.. Generate a security token:
+
[options="nowrap" subs="+quotes"]
----
# tsig-keygen -a hmac-md5 _omapi_key_
key "omapi_key" {
	algorithm hmac-md5;
	secret "4z1jwYO0RGUTJbWDepFBdg==";
};
----
.. Edit the `/etc/dhcp/dhcpd.conf` file for all subnets, and add the key generated by `tsig-keygen`.
The following is an example:
+
[options="nowrap" subs="+quotes"]
----
# cat /etc/dhcp/dhcpd.conf
default-lease-time 604800;
max-lease-time 2592000;
log-facility local7;

subnet _192.168.38.0_ netmask _255.255.255.0_ {
	range _192.168.38.10 192.168.38.100_;
	option routers _192.168.38.1_;
	option subnet-mask _255.255.255.0_;
	option domain-search "_virtual.lan_";
	option domain-name "_virtual.lan_";
	option domain-name-servers _8.8.8.8_;
}

omapi-port 7911;
key _omapi_key_ {
	algorithm hmac-md5;
	secret "_key_secret_";
};
omapi-key _omapi_key_;
----
+
Note that the `option routers` value is the IP address of your {ProjectServer} or {SmartProxyServer} that you want to use with an external DHCP service.
.. Open the DHCP port in the `firewalld` service:
+
[options="nowrap"]
----
# firewall-cmd --add-service dhcp
----
.. Make the changes persistent:
+
[options="nowrap"]
----
# firewall-cmd --runtime-to-permanent
----
. On {ProjectServer}, determine both the UID and the primary GID of the `foreman-proxy` user:
+
[options="nowrap" subs="+quotes"]
----
# id -u foreman-proxy
_993_

# id -g foreman-proxy
_990_
----
. Perform the following steps on the DHCP server:
.. Create the `foreman-proxy` group with the same group ID as determined in a previous step:
+
[options="nowrap" subs="+quotes"]
----
# groupadd -g _990_ foreman-proxy
----
.. Create the `foreman-proxy` user with the same user ID and primary group ID as determined in a previous step:
+
[options="nowrap" subs="+quotes"]
----
# useradd -u _993_ -g _990_ -s /sbin/nologin foreman-proxy
----
.. Ensure that the configuration files are accessible:
+
[options="nowrap"]
----
# chmod o+rx /etc/dhcp/
# chmod o+r /etc/dhcp/dhcpd.conf
# chattr +i /etc/dhcp/ /etc/dhcp/dhcpd.conf
----
.. Enable and start the `dhcpd` service:
+
[options="nowrap"]
----
# systemctl enable --now dhcpd
----
.. Install the `nfs-server` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {client-package-install-el8} {nfs-server-package}
----
.. Enable and start the NFS server service:
+
[options="nowrap" subs="+quotes,attributes"]
----
# systemctl enable --now nfs-server
----
.. Create directories for the DHCP configuration and lease files that you want to export by using NFS:
+
[options="nowrap"]
----
# mkdir -p /exports/var/lib/dhcpd /exports/etc/dhcp
----
.. Edit the `/etc/fstab` file and add bind mount entries for the exported directories:
+
[options="nowrap"]
----
/var/lib/dhcpd  /exports/var/lib/dhcpd  none  bind,auto  0 0
/etc/dhcp       /exports/etc/dhcp       none  bind,auto  0 0
----
+
These entries use bind mounts which mount the original directories to the ones you use for the export in NFS.
.. Activate the bind mounts from the `/etc/fstab` file:
+
[options="nowrap"]
----
# mount -a
----
.. Edit the `/etc/exports` file, and export the required directories in NFS:
+
[options="nowrap" subs="+quotes"]
----
/exports               _192.168.38.1_(rw,async,no_root_squash,fsid=0,no_subtree_check)
/exports/etc/dhcp      _192.168.38.1_(ro,async,no_root_squash,no_subtree_check,nohide)
/exports/var/lib/dhcpd _192.168.38.1_(ro,async,no_root_squash,no_subtree_check,nohide)
----
+
Use the IP address of the {Project} or {SmartProxy} in the export options to ensure that only these hosts have access. 
.. Reload the NFS server:
+
[options="nowrap"]
----
# exportfs -rva
----
.. Enable the `dhcpd` OMAPI port in `firewalld`:
+
[options="nowrap"]
----
# firewall-cmd --add-port=7911/tcp
----
.. Enable the services required for NFSv3 in `firewalld`:
+
[options="nowrap"]
----
# firewall-cmd \
--add-service mountd \
--add-service nfs \
--add-service rpc-bind \
--zone public
----
.. Make the changes persistent:
+
[options="nowrap"]
----
# firewall-cmd --runtime-to-permanent
----
