[id="Increasing_the_Logging_Levels_to_Help_with_Debugging_{context}"]
= Increasing the Logging Levels to Help with Debugging

By default, {Project} comes with `:INFO` level logging enabled.
You can increase or decrease the log levels on your {Project}.

.Enabling debug level logging on all components
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer admin logging --all --level-debug
# {foreman-maintain} service restart
----

.Enabling debug level logging for a specific component
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer admin logging --components "_Component_" --level-debug
----

.Reverting debug level logging to `INFO`
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer admin logging --all --level-production
# {foreman-maintain} service restart
----

.Listing all components and changed configuration files
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer admin logging --list
-----------|-------------------------------------|-------------------------------------
COMPONENT  | AUTO-DETECTED BY EXISTENCE OF       | DESTINATIONS
-----------|-------------------------------------|-------------------------------------
dhcpd      | /etc/dhcp/dhcpd.conf                | syslog /var/log/dhcpd-debug.log
postgresql | /var/lib/pgsql/data/postgresql.conf | syslog /var/lib/pgsql/data/pg_log/
proxy      | /etc/foreman-proxy/settings.yml     | /var/log/foreman-proxy/proxy.log
qpidd      | /etc/qpid/qpidd.conf                | syslog
rails      | /etc/foreman/settings.yaml          | /var/log/foreman/production.log
tomcat     | /etc/candlepin/candlepin.conf       | /var/log/candlepin/ /var/log/tomcat/
virt-who   | /etc/sysconfig/virt-who             | syslog
-----------|-------------------------------------|-------------------------------------
----

== Increasing the Logging Level For Hammer

You can find the log for Hammer in `~/.hammer/log/hammer.log`.
Edit `/etc/hammer/cli_config.yml` and set the `:log_level:`:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
:log_level: 'debug'
----

== Increasing the Logging Level On {SmartProxy}

You can find the log for {SmartProxy} in `/var/log/foreman-proxy/proxy.log`.
Uncomment the `DEBUG` line in `/etc/foreman-proxy/settings.yml`:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
:log_level: DEBUG
----

Ensure to restart the `foreman-proxy` service afterwards:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart foreman-proxy
----

[CAUTION]
====
Running the installer will revert this change back.
====

== Increasing the Logging Level For Candlepin

You can find the log for Candlepin in `/var/log/candlepin/candlepin.log`.
Errors are also logged to a separate file for easier debugging `/var/log/candlepin/error.log`.

Extend `/etc/candlepin/candlepin.conf`:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
log4j.logger.org.candlepin=DEBUG
----

Ensure to restart the `tomcat` service afterwards:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart tomcat
----

If the candlepin log files are too verbose, you can decrease the default debug level:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
log4j.logger.org.candlepin.resource.ConsumerResource=WARN
log4j.logger.org.candlepin.resource.HypervisorResource=WARN
----

== Increasing the Logging Level On {Project}

You can find the log for {Project} in `/var/log/foreman/production.log`.

{Project} stores logs for Apache in:

* `/var/log/httpd/foreman_error.log`
* `/var/log/httpd/foreman_access.log`
* `/var/log/httpd/foreman_ssl_error.log`
* `/var/log/httpd/foreman_ssl_access.log`

.Procedure
. Set the logging level in `/etc/foreman/settings.yaml`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
:logging:
  :production:
    :type: file
    :layout: pattern
    :level: debug
----
. Enable selected loggers in `/etc/foreman/settings.yaml`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
:loggers:
  :ldap:
    :enabled: true
  :permissions:
    :enabled: true
  :sql:
    :enabled: true
----
+
Note that to see logging from some area, debug logging has to be set.
. Restart the {Project} services:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service restart
----

You can find the complete list of loggers with their default values in `/usr/share/foreman/config/application.rb` in the `Foreman::Logging.add_loggers` command.

== Increasing the Logging Level For Qpid Dispatch Router

Qpid logs to syslog and can be viewed in `/var/log/messages` or with `journalctl`.
Enable debug logging in `/etc/qpid-dispatch/qdrouterd.conf`:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
enable: debug+
----

Ensure to restart the Qpid Dispatch Router afterwards:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart qdrouterd
----

[CAUTION]
====
Running the installer will revert this change back.
====

== Increasing the Logging Level For Qpid Broker

Qpid logs to syslog and can be viewed in `/var/log/messages` or with `journalctl`.
Set the log level in `/etc/qpid/qpidd.conf`:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
log-enable=debug+
----

Ensure to restart the Qpid Broker afterwards:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart qpidd
----

[CAUTION]
====
Running the installer will revert this change.
====

== Increasing the Logging Level For Redis

You can find the log for Redis in `/var/log/redis/redis.log`.
Set the log level in `/etc/opt/rh/rh-redis5/redis.conf`:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
loglevel debug
----

Ensure to restart the Redis service afterwards:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart rh-redis5-redis
----

== Increasing the Logging Level For Postgres

You can find the log for Postgres in `/var/opt/rh/rh-postgresql12/lib/pgsql/data/log/`.
Uncomment the `log_statement` in `/var/opt/rh/rh-postgresql12/lib/pgsql/data/postgresql.conf`:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
log_statement = 'all'
----

Ensure to restart the {Project} services afterwards:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service restart
----

[CAUTION]
====
Based on the size of your {Project} installation, this can cause disk space to fill up very quickly.
Only turn this on if absolutely needed.
====

For more debug log settings, refer to the https://www.postgresql.org/docs/current/runtime-config-logging.html[Postgresql documentation].

== Increasing the Logging Level For {Project} Installer

You can find the log files in `/var/log/foreman-installer/`.
To increase the log level of the {Project} Installer during an install:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --verbose-log-level debug
----

== Increasing the Logging Level For Pulp

By default, Pulp logs to syslog and can be viewed in `/var/log/messages` or with `journalctl`.
Add the following config to the `/etc/pulp/settings.py` file:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
LOGGING = {"dynaconf_merge": True, "loggers": {'': {'handlers': ['console'], 'level': 'DEBUG'}}}
----

Ensure to restart the Pulp services afterwards:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart \
pulpcore-api \
pulpcore-content \
pulpcore-resource-manager \
pulpcore-worker@1 \
pulpcore-worker@2 \
rh-redis5-redis
----

ifdef::foreman-el,orcharhino[]
== Increasing the Logging Level For Salt

You can increase the log level for Salt Master (`/etc/salt/master`) and Salt Minion (`/etc/salt/minion`) by changing the following option:

[yaml, options="nowrap", subs="+quotes,verbatim,attributes"]
----
log_level: debug
----

Salt Master logs to `/var/log/salt/master` and Salt Minions log to `/var/log/salt/minion`.
endif::[]
