[id="Creating_an_Activation_Key_{context}"]
= Creating an activation key

Create an activation key to assign various attributes to hosts during registration.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-an-activation-key_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Activation Keys* and click *Create Activation Key*.
. In the *Name* field, enter the name of the activation key.
. If you want to set a limit, clear the *Unlimited hosts* checkbox, and in the *Limit* field, enter the maximum number of systems you can register with the activation key.
If you want unlimited hosts to register with the activation key, ensure the *Unlimited Hosts* checkbox is selected.
. Optional: In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the environment to use.
. From the *Content View* list, select a content view to use.
ifndef::orcharhino[]
. In the *Repository Sets* tab, override repositories to Enabled or Disabled as desired.
For more information, see xref:enabling-and-disabling-repositories-on-activation-key_{context}[].
endif::[]
. Click *Save*.
. Optional: In the *System Purpose* section, you can configure the activation key to set system purpose attributes on hosts during registration.
This helps determine which repositories are available on the host.
It also helps with reporting in the Subscriptions service of the Red Hat Hybrid Cloud Console.

[id="cli-creating-an-activation-key_{context}"]
.CLI procedure
. Create the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer activation-key create \
--name "_My_Activation_Key_" \
--unlimited-hosts \
--description "_Example Stack in the Development Environment_" \
--lifecycle-environment "_Development_" \
--content-view "_Stack_" \
--organization "_My_Organization_"
----
. Optional: Enter the following command to configure the activation key with system purpose attributes to set on hosts during registration.
This helps determine which repositories are available on the host.
It also helps with reporting in the Subscriptions service of the Red Hat Hybrid Cloud Console.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer activation-key update \
--organization "_My_Organization_" \
--name "_My_Activation_Key_" \
--service-level "_Standard_" \
--purpose-usage "_Development/Test_" \
--purpose-role "_{RHELServer}_"
----
. List the product content associated with the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer activation-key product-content \
--content-access-mode-all true \
--name "_My_Activation_Key_" \
--organization "_My_Organization_"
----
. Override the default auto-enable status for the {project-client-name} repository.
The default status is set to disabled.
To enable, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer activation-key content-override \
--name "_My_Activation_Key_" \
--content-label {project-client-name} \
--value 1 \
--organization "_My_Organization_"
----
