:_mod-docs-content-type: PROCEDURE

[id="altering-the-privilege-elevation-method_{context}"]
= Altering the privilege elevation method

[role="_abstract"]
By default, push-based remote execution uses `sudo` to switch from the SSH user to the effective user that executes the script on your host.
In some situations, you might require to use another method, such as `su` or `dzdo`.
You can globally configure an alternative method in your {Project} settings.

[NOTE]
====
If the SSH user and effective user for push-based transport are non-root users, ensure the `acl` package is installed on the host and the remote execution working directory is mounted on a filesystem that supports ACLs.
====

.Prerequisites
* Your user account has a role assigned that grants the `view_settings` and `edit_settings` permissions.
* If you want to use `dzdo` for Ansible jobs, ensure the `community.general` Ansible collection, which contains the required *dzdo* become plugin, is installed.
For more information, see https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html[Installing collections] in _Ansible documentation_.

.Procedure
. Navigate to *Administer* > *Settings*.
. Select the *Remote Execution* tab.
. Click the value of the *Effective User Method* setting.
. Select the new value.
. Click *Submit*.
