:_mod-docs-content-type: PROCEDURE

[id="formatting-hammer-output"]
= Formatting Hammer output

[role="_abstract"]
You can modify the default formatting of the output of Hammer commands to simplify the processing of this output by other command line tools and applications.

Hammer provides several output formats:

* `table` {endash} generates output in the form of a human readable table (default).
* `base` {endash} generates output in the form of key-value pairs.
* `yaml` {endash} generates output in the YAML format.
* `csv` {endash} generates output in the Comma Separated Values format.
Output in CSV format is useful for example when you need to parse IDs and use them in a *for* loop.
+
To define a custom separator, use the `--csv` and `--csv-separator` options instead.
* `json` {endash} generates output in the JavaScript Object Notation format.
* `silent` {endash} suppresses the output.

.Procedure
* Set the output format with the `--output` option:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ hammer --output _output_format_ organization list
----
* Define a custom separator for the CSV format:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ hammer --csv --csv-separator ";" organization list
----
