[id='configuring-pcp-data-collection_{context}']
= Configuring PCP Data Collection

This procedure describes how to configure PCP to collect metrics about processes, {Project}, Apache HTTP Server, and PostgreSQL.

.Procedure
. To configure PCP to collect data about {Project} processes, configure the process monitoring PMDA to use the {Project} specific config:
+
----
# ln -s /var/lib/pcp/pmdas/proc/hotproc.conf /etc/pcp/proc/foreman-hotproc.conf
----
+
By default, PCP collects basic system metrics.
This step enables detailed metrics about the following {Project} processes:
+
* Java
* PostgreSQL
* Redis
* Dynflow
* Puma
ifndef::foreman-el,foreman-deb[]
* Pulpcore
endif::[]

. Install the process monitoring PMDA.
+
----
# cd /var/lib/pcp/pmdas/proc
# ./Install
----

. Configure PCP to collect metrics from Apache HTTP Server.
+
.. Enable the Apache HTTP Server extended status module.
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {foreman-installer} --enable-apache-mod-status
----
.. Enable the Apache HTTP Server PMDA.
+
----
# cd /var/lib/pcp/pmdas/apache
# ./Install
----
. Configure PCP to collect metrics from PostgreSQL:
+
----
# cd /var/lib/pcp/pmdas/postgresql
# ./Install
----
. Enable telemetry functionality in {Project}:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {foreman-installer} --foreman-telemetry-prometheus-enabled true
----
. Configure PCP to collect data from {Project}.
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# cd /var/lib/pcp/pmdas/openmetrics
# echo "https://_{foreman-example-com}_/metrics" > config.d/foreman.url
# ./Install
----
. Restart PCP to begin data collection:
+
----
# systemctl restart pmcd pmlogger
----
