[id="Synchronizing_Smart_Proxy_Directly_From_Red_Hat_CDN_{context}"]
= Synchronizing {SmartProxy} Directly From Red Hat CDN

You can use simplified alternate content sources to configure the {SmartProxy} to sync content directly from Red Hat CDN.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Alternate Content Sources*.
. Click *Add Source* and set the *Source type* as *Simplified*.
. Set the *Content type* to *Yum*.
. In the *Name* field, enter a name for the alternate content source.
. Optional: In the *Description* field, provide a description for the alternate content source.
. Select {SmartProxies} that you want to sync directly from Red Hat CDN.
. Optional: Select Use *HTTP proxies* if you want the ACS to use the {SmartProxyServer}’s HTTP proxy.
. Select the Red Hat products that should be synced to the {SmartProxy} from Red Hat CDN.
. Review details and click *Add*.
. Navigate to *Content* > *Alternate Content Sources*, click the vertical ellipsis next to the newly created alternate content source, and select *Refresh*.
