[id="configuring-for-uefi-http-boot-provisioning-in-an-ipv6-network_{context}"]
= Configuring {Project} for UEFI HTTP Boot Provisioning in an IPv6 Network

Use this procedure to configure {Project} to provision hosts in an IPv6 network with UEFI HTTP Boot provisioning.

.Prerequisites

* Ensure that your clients can access DHCP and HTTP servers.

* Ensure that the UDP ports 67 and 68 are accessible by clients so clients can send DHCP requests and receive DHCP offers.

* Ensure that the TCP port 8000 is open for clients to download files and Kickstart templates from {Project} and {SmartProxies}.

* Ensure that the host provisioning interface subnet has an HTTP Boot {SmartProxy}, and Templates {SmartProxy} set. For more information, see https://access.redhat.com/documentation/en-us/red_hat_satellite/6.7/html/provisioning_guide/configuring_networking#Configuring_Networking-Adding_a_Subnet_to_the_Satellite_Server[Adding a Subnet to {ProjectServer}] in the _Provisioning Guide_.

* Navigate to *Administer* > *Settings* > *Provisioning* and ensure that the *Token duration* setting is not set to *0*. {Project} cannot identify clients that are booting from the network by a remote IPv6 address because of unmanaged DHCPv6 service, therefore provisioning tokens must be enabled.

.Procedure

. You must disable DHCP management in the installer or not use it.

. For all IPv6 subnets created in {Project}, set the *DHCP {SmartProxy}* to blank.

. Optional: If the host and the DHCP server are separated by a router, configure the DHCP relay agent and point to the DHCP server.

. On {Project} or {SmartProxy} from which you provision, update the `grub2-efi` package to the latest version:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} grub2-efi
----

. Synchronize the {RHEL} 8 kickstart repository.
ifeval::["{build}" != "satellite"]
+
Note that this step is for Katello users only.
endif::[]
