:_mod-docs-content-type: PROCEDURE

[id="creating-a-custom-product-by-using-web-ui"]
= Creating a {customproduct} by using {ProjectWebUI}

[role="_abstract"]
Create a {customproduct} so that you can add repositories to the {customproduct}.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*, click *Create Product*.
. In the *Name* field, enter a name for the product.
{Project} automatically completes the *Label* field based on what you have entered for *Name*.
. Optional: From the *GPG Key* list, select the GPG key for the product.
. Optional: From the *SSL CA Cert* list, select the SSL CA certificate for the product.
. Optional: From the *SSL Client Cert* list, select the SSL client certificate for the product.
. Optional: From the *SSL Client Key* list, select the SSL client key for the product.
. Optional: From the *Sync Plan* list, select an existing sync plan or click *Create Sync Plan* and create a sync plan for your product requirements.
. In the *Description* field, enter a description of the product.
. Click *Save*.
