[id="running-an-ansible-playbook-from-{project-context}_{context}"]
= Running an Ansible playbook from {Project}

You can run an Ansible playbook on a host or host group by executing a remote job in {Project}.

.Limitation of host parameters in Ansible playbook job templates
When you execute an Ansible playbook on multiple hosts and the playbook job template includes a host parameter, {Project} renders the playbook for all hosts in the batch, but only uses the playbook of the first host to execute it on all hosts in the batch.
Therefore, you cannot use a host parameter to modify the behavior of the playbook per host.
For more information, see link:https://bugzilla.redhat.com/show_bug.cgi?id=2282275[BZ#2282275].

.Prerequisites
* Ansible plugin in {Project} is enabled.
* Remote job execution is configured.
For more information, see xref:Configuring_and_Setting_Up_Remote_Jobs_{context}[].
* You have an Ansible playbook ready to use.

.Procedure
. In the {ProjectWebUI}, navigate to *Monitor* > *Jobs*.
. Click *Run Job*.
. In *Job category*, select `Ansible Playbook`.
. In *Job template*, select `Ansible - Run playbook`.
. Click *Next*.
. Select the hosts on which you want to run the playbook.
. In the *playbook* field, paste the content of your Ansible playbook.
. Follow the wizard to complete setting the remote job.
For more information, see xref:executing-a-remote-job_{context}[].
. Click *Submit* to run the Ansible playbook on your hosts.

.Additional resources
* Alternatively, you can import Ansible playbooks from {SmartProxyServers}.
For more information, see the following resources:
** xref:importing-an-ansible-playbook-by-name_{context}[]
** xref:importing-all-available-ansible-playbooks_{context}[]
