[id="Registering_Server_to_Server_{context}"]
= Registering to {ProjectServer}

Use this procedure to register the base operating system on which you want to install {SmartProxyServer} to {ProjectServer}.

.Red{nbsp}Hat Subscription Manifest Prerequisites
* On {ProjectServer}, a manifest must be installed and it must contain the appropriate repositories for the organization you want {SmartProxy} to belong to.
* The manifest must contain repositories for the base operating system on which you want to install {SmartProxy}, as well as any clients that you want to connect to {SmartProxy}.
* The repositories must be synchronized.

For more information on manifests and repositories, see {ContentManagementDocURL}Managing_Red_Hat_Subscriptions_content-management[Managing Red Hat Subscriptions] in _{ContentManagementDocTitle}_.

.Proxy and Network Prerequisites
* {ProjectServer} base operating system must be able to resolve the host name of the {SmartProxy} base operating system and vice versa.
ifndef::foreman-deb[]
* The base operating system on which you want to install {SmartProxyServer} must not be configured to use a proxy to connect to the Red Hat CDN.
endif::[]
* You must configure the host and network-based firewalls accordingly.
For more information, see {InstallingSmartProxyDocURL}capsule-ports-and-firewalls-requirements_{smart-proxy-context}[Ports and Firewalls Requirements].
* You must have a {ProjectServer} user name and password.
For more information, see {AdministeringDocURL}Configuring_External_Authentication_admin[Configuring External Authentication] in _{AdministeringDocTitle}_.

include::snip_host-registration-steps.adoc[]
