:_mod-docs-content-type: PROCEDURE

[id="serving-{smart-proxy-context}-container-images-from-{project-context}-server"]
= Serving {SmartProxy} container images from {ProjectServer}

[role="_abstract"]
A {SmartProxyServer} pulls its container images through your {ProjectServer} instead of directly from `registry.redhat.io`.
On your {ProjectServer}, synchronize the required container images before you install {SmartProxyServer}, so that {ProjectServer} can serve them to the {SmartProxy}.

.Prerequisites
* A Red{nbsp}Hat registry service account to authenticate the synchronization against `registry.redhat.io`.
For more information, see link:https://access.redhat.com/articles/RegistryAuthentication[Red Hat Container Registry Authentication].

.Procedure
. On your {ProjectServer}, create a product to contain all {SmartProxy} container images:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer product create \
--name "{SmartProxy} Container Images" \
--organization "_My_Organization_"
----
+
With the default registry name pattern of `<organization>/<product>/<repository>`, the published registry path uses the lowercased labels of your organization and product, for example `_my_organization_/{smart-proxy-context}_container_images/<repository>`.
For more information, see {ContentManagementDocURL}configuring-container-registry-name-patterns-for-a-lifecycle-environment[Configuring container registry name patterns for a lifecycle environment in _{ContentManagementDocTitle}_].
. On your {ProjectServer}, create a container repository for each required image.
Each repository name must match the final path component of the upstream image, and the tags must match the tags that the {SmartProxy} requests, or the image pull fails:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer repository create \
--name "foreman-proxy-rhel10" \
--product "{SmartProxy} Container Images" \
--organization "_My_Organization_" \
--content-type "docker" \
--url "https://registry.redhat.io" \
--docker-upstream-name "satellite/foreman-proxy-rhel10" \
--include-tags "{ProjectVersion}" \
--upstream-username "_My_Service_Account_Username_" \
--upstream-password "_My_Service_Account_Token_"

$ hammer repository create \
--name "pulp-rhel10" \
--product "{SmartProxy} Container Images" \
--organization "_My_Organization_" \
--content-type "docker" \
--url "https://registry.redhat.io" \
--docker-upstream-name "satellite/pulp-rhel10" \
--include-tags "{ProjectVersion}" \
--upstream-username "_My_Service_Account_Username_" \
--upstream-password "_My_Service_Account_Token_"

$ hammer repository create \
--name "postgresql-16" \
--product "{SmartProxy} Container Images" \
--organization "_My_Organization_" \
--content-type "docker" \
--url "https://registry.redhat.io" \
--docker-upstream-name "rhel10/postgresql-16" \
--include-tags "latest" \
--upstream-username "_My_Service_Account_Username_" \
--upstream-password "_My_Service_Account_Token_"

$ hammer repository create \
--name "valkey-8" \
--product "{SmartProxy} Container Images" \
--organization "_My_Organization_" \
--content-type "docker" \
--url "https://registry.redhat.io" \
--docker-upstream-name "rhel10/valkey-8" \
--include-tags "latest" \
--upstream-username "_My_Service_Account_Username_" \
--upstream-password "_My_Service_Account_Token_"
----
. On your {ProjectServer}, synchronize the product to download the container images to your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer product synchronize \
--name "{SmartProxy} Container Images" \
--organization "_My_Organization_"
----
+
The synchronized content is available in the Library environment through the Default Organization View.
When you register the {SmartProxy} with an activation key that assigns the Library environment and the Default Organization View, you do not need to publish or promote a content view for the {SmartProxy} to pull these images.

.Verification
* Confirm that the container images are published on your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ curl --cacert /var/lib/foremanctl/certs/certs/ca-bundle.crt --silent --user _admin_ \
https://_{foreman-example-com}_/v2/_catalog
----
+
The output lists the four repositories under your product path, for example:
+
[options="nowrap" subs="+quotes,attributes"]
----
my_organization/{smart-proxy-context}_container_images/foreman-proxy-rhel10
my_organization/{smart-proxy-context}_container_images/pulp-rhel10
my_organization/{smart-proxy-context}_container_images/postgresql-16
my_organization/{smart-proxy-context}_container_images/valkey-8
----

.Next steps
* Configure the {SmartProxy} to pull its container images from the product path, for example, `my_organization/{smart-proxy-context}_container_images`.
For more information, see xref:configuring-{smart-proxy-context}-server-to-pull-container-images-from-{project-context}-server[].
