:_mod-docs-content-type: PROCEDURE

[id="installing-{insights-iop-id}-with-the-{project-context}-iso-image"]
= Installing {insights-iop} with the {Project} ISO image

[role="_abstract"]
You can use the {Project} installation ISO image to access the required container content.

.Prerequisites
* `skopeo` is installed on your {ProjectServer}.
ifdef::satellite[]
For more information, see {RHELDocsBaseURL}9/html/building_running_and_managing_containers/assembly_starting-with-containers_building-running-and-managing-containers#proc_getting-container-tools_assembly_starting-with-containers[Getting container tools] in _{RHEL}{nbsp}9 Building, running, and managing containers_.
endif::[]
ifndef::satellite[]
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {project-package-install} skopeo
----
endif::[]

.Procedure
. Download and mount the {Project} ISO image:
For more information, see xref:preparing-the-system-for-{Project}-deployment-from-the-offline-repositories[].
. Set up the local repositories and containers for disconnected environments:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /media/satellite/prepare_system
----
include::snip_steps-adding-iop-vulnerability-metadata-files.adoc[]
