[id="remediating-compliance-failures_{context}"]
= Remediating compliance failures

You can examine compliance reports and, in some cases, remediate cases of non-compliance.

[WARNING]
====
Always test the recommended remedial actions or scripts in a non-production environment before implementing them in production.
Remediation might render the system non-functional.
====

.Prerequisites
* Your user account has a role assigned that has the `view_arf_reports` and `view_hosts` permissions.

.Procedure
To examine a simplified compliance policy report:

. In the {ProjectWebUI}, navigate to *Hosts* > *Compliance* > *Reports*.
. In the *Reported At* column, click the time link of the report you want to examine.
{Project} displays a simplified list of policy rules with the results of the scan.

To examine a full compliance policy report and remediate compliance failures manually:

. In the {ProjectWebUI}, navigate to *Hosts* > *Compliance* > *Reports* to list all compliance reports.
. In the *Actions* column, click *Full Report*.
{Project} displays the complete details of an evaluation report.
. In the *Rule Overview* section, click the title of a rule in the *Title* column to inspect further result details.
. Click *Remediation Shell script*, *Remediation Ansible snippet*, *Remediation Puppet snippet*, or *Remediation Anaconda snippet* to display remediation advice.
Remediation scripts and snippets are not available for all compliance rules.

.Additional resources
* You can apply the remediation script or snippet by using a remote job.
For more information, see link:{ManagingHostsDocURL}Configuring_and_Setting_Up_Remote_Jobs_managing-hosts[Configuring and setting up remote jobs] in _{ManagingHostsDocTitle}_.
