:_mod-docs-content-type: PROCEDURE

[id="adding-lifecycle-environments-by-using-cli"]
= Adding lifecycle environments to {SmartProxyServers} by using Hammer CLI

[role="_abstract"]
To distribute content through content-enabled {SmartProxyServer}, add lifecycle environments to your {SmartProxyServer}.
{SmartProxyServer} synchronizes the right repositories from {ProjectServer} and provides that content to hosts.

Do not assign the _Library_ lifecycle environment to your {SmartProxyServer} because it triggers an automated {SmartProxy} sync every time the CDN updates a repository.
This might consume multiple system resources on {SmartProxies}, network bandwidth between {Project} and {SmartProxies}, and available disk space on {SmartProxies}.

You can add an environment by using Hammer CLI.

Each {SmartProxyServer} is represented by multiple {SmartProxy} records in {Project}.
To add lifecycle environments, you must select the {SmartProxy} record that has the *Pulpcore* feature enabled.
This record is identified by a `-pulp` suffix in its name.

For example, if your {SmartProxyServer} hostname is `capsule.example.com`, you will see two {SmartProxy} records:

* `capsule.example.com` - Contains features such as Registration, Templates, and Logs
* `capsule.example.com-pulp` - Contains the *Pulpcore* feature for content management

You must use the record with the `-pulp` suffix to manage lifecycle environments.

.Procedure
. To display a list of all {SmartProxyServers}, on {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {hammer-smart-proxy} list
----
+
Identify the {SmartProxy} record with a `-pulp` suffix in its name.
Note the {SmartProxy} ID of this record.
. Using the ID, verify the details of your {SmartProxy} and confirm it has the *Pulpcore* feature:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {hammer-smart-proxy} info \
--id __My_{smart-proxy-context-titlecase}_ID__
----
+
In the output, verify that *Pulpcore* appears in the list of features.
. To view the lifecycle environments available for your {SmartProxyServer}, enter the following command and note the ID and the organization name:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {hammer-smart-proxy} content available-lifecycle-environments \
--id __My_{smart-proxy-context-titlecase}_ID__
----
. Add the lifecycle environment to your {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {hammer-smart-proxy} content add-lifecycle-environment \
--id __My_{smart-proxy-context-titlecase}_ID__ \
--lifecycle-environment-id _My_Lifecycle_Environment_ID_ \
--organization "_My_Organization_"
----
+
Repeat for each lifecycle environment you want to add to {SmartProxyServer}.
. Synchronize the content from {Project} to {SmartProxy}.
+
* To synchronize all content from your {ProjectServer} environment to {SmartProxyServer}, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {hammer-smart-proxy} content synchronize \
--id __My_{smart-proxy-context-titlecase}_ID__
----
+
* To synchronize a specific lifecycle environment from your {ProjectServer} to {SmartProxyServer}, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {hammer-smart-proxy} content synchronize \
--id __My_{smart-proxy-context-titlecase}_ID__ \
--lifecycle-environment-id _My_Lifecycle_Environment_ID_
----
+
* To synchronize all content from your {ProjectServer} to your {SmartProxyServer} without checking metadata:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {hammer-smart-proxy} content synchronize \
--id __My_{smart-proxy-context-titlecase}_ID__ \
--skip-metadata-check true
----
+
This equals selecting *Complete Sync* in the {ProjectWebUI}.
