:_mod-docs-content-type: PROCEDURE

[id="adding-errata-to-an-incremental-content-view-by-using-mcp"]
= Adding errata to an incremental content view by using MCP

[role="_abstract"]
You can use your AI application to perform an incremental update of a content view to add errata to it.

include::snip_warning-ai-output-review.adoc[]
:FeatureName: The MCP server for {Project} 
include::snip_technology-preview.adoc[]

.Procedure
. Allow the MCP server to trigger content view actions:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ podman run --interactive --tty --publish 127.0.0.1:8080:8080 \
  --volume _Path_to_My_CA_Bundle_:/app/ca.pem:ro,Z \
  {mcp-server-image} \
  --foreman-url https://_{foreman-example-com}_ \
  --allowed-cv-actions "incremental_update"
----
+
For more information, see {ManagingHostsDocURL}deploying-the-mcp-server-for-{project-context}[Deploying the MCP server for {Project}] in _{ManagingHostsDocTitle}_.
. Type a prompt in your AI application to list applicable errata:
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
Show a list of applicable errata on my {Project}.
----
. The MCP server will return a list of applicable errata to the AI application.
Review the information.
. The {Project} MCP server provides a prompt named `Add Errata to Content Views`, which you can use to perform an incremental update of a content view.
Refer to the documentation of your AI application to find more about how to use MCP server prompts.
Review all the steps that the AI application performs.
