[id="Adding_a_Microsoft_Azure_Resource_Manager_Connection_{context}"]
= Adding a Microsoft Azure Resource Manager Connection to {ProjectServer}

Use this procedure to add Microsoft Azure as a compute resource in {Project}.
Note that you must add a separate compute resource for each Microsoft Azure region that you want to use.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-Adding_a_Microsoft_Azure_Resource_Manager_Connection_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources* and click *Create Compute Resource*.
. In the *Name* field, enter a name for the compute resource.
. From the *Provider* list, select *Azure Resource Manager*.
. Optional: In the *Description* field, enter a description for the resource.
. By default, the *Cloud* is set to Public/Standard.
Azure Government Cloud supports the following regions:
  ** US Government
  ** China
  ** Germany
. In the *Client ID* field, enter your Application or _client_ ID.
. In the *Client Secret* field, enter your client secret.
. In the *Subscription ID* field, enter your subscription ID.
. In the *Tenant ID* field, enter your Directory or _tenant_ ID.
. Click *Load Regions*.
This tests if your connection to Azure Resource Manager is successful and loads the regions available in your subscription.
. From the *Azure Region* list, select the Azure region to use.
. Click *Submit*.

[id="cli-Adding_a_Microsoft_Azure_Resource_Manager_Connection_{context}"]
.CLI procedure
* Use `hammer compute-resource create` to add an Azure compute resource to {Project}.
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create \
--app-ident _My_Client_ID_ \
--name _My_Compute_Resource_Name_ \
--provider azurerm \
--region "_My_Region_" \
--secret-key _My_Client_Secret_ \
--sub-id _My_Subscription_ID_ \
--tenant _My_Tenant_ID_
----
+
Note that the value for the `--region` option must be in lowercase and must not contain special characters.

IMPORTANT: If you are using Azure Government Cloud then you must pass in the `--cloud` parameter.
The values for the `cloud` parameter are:

[%header,cols=2*]
|===
|Name of Azure Government Cloud
|Value for hammer --cloud

|US Government
|azureusgovernment

|China
|azurechina

|Germany
|azuregermancloud
|===
