[id="Creating_Hosts_with_Unattended_Provisioning_{context}"]
= Creating Hosts with Unattended Provisioning

Unattended provisioning is the simplest form of host provisioning.
You enter the host details on {ProjectServer} and boot your host.
{ProjectServer} automatically manages the PXE configuration, organizes networking services, and provides the operating system and configuration for the host.

This method of provisioning hosts uses minimal interaction during the process.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-hosts-with-unattended-provisioning_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Create Host*.
. In the *Name* field, enter a name for the host.
. Click the *Organization* and *Location* tabs and change the context to match your requirements.
. From the *Host Group* list, select a host group that you want to use to populate the form.
. Click the *Interface* tab, and on the host's interface, click *Edit*.
. Verify that the fields are populated with values.
Note in particular:
+
* The *Name* from the *Host* tab becomes the *DNS name*.
* {ProjectServer} automatically assigns an IP address for the new host.
+
. In the *MAC address* field, enter a MAC address for the host.
This ensures the identification of the host during the PXE boot process.
. Ensure that {ProjectServer} automatically selects the *Managed*, *Primary*, and *Provision* options for the first interface on the host.
If not, select them.
. In the *MAC address* field, enter a MAC address of the host's provisioning interface.
This ensures the identification of the host during the PXE boot process.
. Click *OK* to save.
To add another interface, click *Add Interface*.
You can select only one interface for *Provision* and *Primary*.
. Click the *Operating System* tab, and verify that all fields contain values.
Confirm each aspect of the operating system.
. Optional: Click *Resolve* in *Provisioning template* to check the new host can identify the right provisioning templates to use.
+
For more information about associating provisioning templates, see xref:provisioning-templates_{context}[].
ifdef::satellite,orcharhino[]
. Click the *Parameters* tab, and ensure that a parameter exists that provides an activation key.
If not, add an activation key.
endif::[]
ifdef::foreman-el,katello[]
. If you use the Katello plugin, click the *Parameters* tab, and ensure that a parameter exists that provides an activation key.
If not, add an activation key.
endif::[]
. Click *Submit* to save the host details.
+
For more information about network interfaces, see {ManagingHostsDocURL}Adding_Network_Interfaces_managing-hosts[Adding network interfaces] in _{ManagingHostsDocTitle}_.

This creates the host entry and the relevant provisioning settings.
This also includes creating the necessary directories and files for PXE booting the bare metal host.
If you start the physical host and set its boot mode to PXE, the host detects the DHCP service of {ProjectServer}'s integrated {SmartProxy}, receives HTTP endpoint of the Kickstart tree and installs the operating system.

ifdef::satellite,orcharhino[]
When the installation completes, the host also registers to {ProjectServer} using the activation key and installs the necessary configuration and management tools from the {project-client-name} repository.
endif::[]

ifdef::foreman-el,katello[]
If you use the Katello plug-in, when the installation completes, the host also registers to {ProjectServer} using the activation key and installs the necessary configuration and management tools from the {project-client-name} repository.
endif::[]

[id="cli-creating-hosts-with-unattended-provisioning_{context}"]
.CLI procedure
. Create the host with the `hammer host create` command:
+
[options="nowrap" subs="+quotes"]
----
# hammer host create --name "_My_Unattended_Host_" --organization "_My_Organization_" \
--location "_My_Location_" --hostgroup "_My_Host_Group_" --mac "_aa:aa:aa:aa:aa:aa_" \
--build true --enabled true --managed true
----
. Ensure the network interface options are set using the `hammer host interface update` command:
+
----
# hammer host interface update --host "test1" --managed true \
--primary true --provision true
----
