[id="Adding_Permissions_to_a_Role_{context}"]
= Adding permissions to a role

Use this procedure to add permissions to a role.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-permissions-to-a-role_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Roles*.
. Select *Add Filter* from the drop-down list to the right of the required role.
. Select the *Resource type* from the drop-down list.
The _(Miscellaneous)_ group gathers permissions that are not associated with any resource group.
. Click the permissions you want to select from the *Permission* list.
. For certain *Resource type* options, the *Unlimited* checkbox is available.
If *Unlimited* is selected, the permission is applied on all resources of the selected type.
If *Unlimited* is unselected, the *Search* field activates.
In this field you can specify further filtering with use of the {Project} search syntax.
For more information, see xref:Granular_Permission_Filtering_{context}[].
. Click *Next*.
. Click *Submit* to save changes.

[id="cli-adding-permissions-to-a-role_{context}"]
.CLI procedure
. List all available permissions:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ hammer filter available-permissions
----
. Add permissions to a role:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ hammer filter create \
--permission-ids _My_Permission_ID_1_,_My_Permission_ID_2_ \
--role _My_Role_Name_
----

For more information about roles and permissions parameters, enter the `hammer role --help` and `hammer filter --help` commands.
