[id="creating-a-job-template_{context}"]
= Creating a Job Template

Use this procedure to create a job template.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-job-template_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Job templates*.
. Click *New Job Template*.
. Click the *Template* tab, and in the *Name* field, enter a unique name for your job template.
. Select *Default* to make the template available for all organizations and locations.
. Create the template directly in the template editor or upload it from a text file by clicking *Import*.
. Optional: In the *Audit Comment* field, add information about the change.
. Click the *Job* tab, and in the *Job category* field, enter your own category or select from the default categories listed in {ManagingHostsDocURL}default-job-template-categories_managing-hosts[Default Job Template Categories] in _{ManagingHostsDocTitle}_.
. Optional: In the *Description Format* field, enter a description template.
For example, `Install package %\{package_name}`.
You can also use `%\{template_name}` and `%\{job_category}` in your template.
. From the *Provider Type* list, select *SSH* for shell scripts and *Ansible* for Ansible tasks or playbooks.
. Optional: In the *Timeout to kill* field, enter a timeout value to terminate the job if it does not complete.
. Optional: Click *Add Input* to define an input parameter.
Parameters are requested when executing the job and do not have to be defined in the template.
For examples, see the *Help* tab.
. Optional: Click *Foreign input set* to include other templates in this job.
. Optional: In the *Effective user* area, configure a user if the command cannot use the default `remote_execution_effective_user` setting.
. Optional: If this template is a snippet to be included in other templates, click the *Type* tab and select *Snippet*.
. Click the *Location* tab and add the locations where you want to use the template.
. Click the *Organizations* tab and add the organizations where you want to use the template.
. Click *Submit* to save your changes.

You can extend and customize job templates by including other templates in the template syntax.
For more information, see {ManagingHostsDocURL}template_writing_reference_managing-hosts[Template Writing Reference] and {ManagingHostsDocURL}job_template_examples_and_extensions_managing-hosts[Job Template Examples and Extensions] in _{ManagingHostsDocTitle}_.

[id="cli-creating-a-job-template_{context}"]
.CLI procedure
* To create a job template using a template-definition file, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer job-template create \
--file "_Path_to_My_Template_File_" \
--job-category "_My_Category_Name_" \
--name "_My_Template_Name_" \
--provider-type SSH
----
