[id="Importing_Container_Images_{context}"]
= Importing Container Images

ifndef::orcharhino[]
You can import container image repositories from Red Hat Registry or from other image registries.
endif::[]
ifdef::orcharhino[]
You can import container image repositories from any container image registry.
endif::[]

This procedure uses repository discovery to find container images and import them as repositories.
For more information about creating a product and repository manually, see xref:Importing_Content_{context}[].

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-importing-container-images[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products* and click *Repo Discovery*.
. From the *Repository Type* list, select *Container Images*.
. In the *Registry to Discover* field, enter the URL of the registry to import images from.
. In the *Registry Username* field, enter the name that corresponds with your user name for the container image registry.
. In the *Registry Password* field, enter the password that corresponds with the user name that you enter.
. In the *Registry Search Parameter* field, enter any search criteria that you want to use to filter your search, and then click *Discover*.
. Optional: To further refine the *Discovered Repository* list, in the *Filter* field, enter any additional search criteria that you want to use.
. From the *Discovered Repository* list, select any repositories that you want to import, and then click *Create Selected*.
. Optional: To change the download policy for this docker repository to _on demand_, see xref:changing_the_download_policy_for_a_repository_{context}[].
. Optional: If you want to create a product, from the *Product* list, select *New Product*.
. In the *Name* field, enter a product name.
. Optional: In the *Repository Name* and *Repository Label* columns, you can edit the repository names and labels.
. Click *Run Repository Creation*.
. When repository creation is complete, you can click each new repository to view more information.
. Optional: To filter the content you import to a repository, click a repository, and then navigate to *Limit Sync Tags*.
Click to edit, and add any tags that you want to limit the content that synchronizes to {Project}.
. In the {ProjectWebUI}, navigate to *Content* > *Products* and select the name of your product.
. Select the new repositories and then click *Sync Now* to start the synchronization process.

To view the progress of the synchronization, navigate to *Content* > *Sync Status* and expand the repository tree.

When the synchronization completes, you can click *Container Image Manifests* to list the available manifests.
From the list, you can also remove any manifests that you do not require.

[id="cli-importing-container-images"]
.CLI procedure
. Create the custom `{container-product-name}` product:
+
[options="nowrap" subs="+quotes"]
----
# hammer product create \
--description "_My_Description_" \
--name "{container-product-name}" \
--organization "_My_Organization_" \
--sync-plan "_My_Sync_Plan_"
----
. Create the repository for the container images:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository create \
--content-type "docker" \
--docker-upstream-name "{container-image-name}" \
--name "{container-repository-name}" \
--organization "_My_Organization_" \
--product "{container-product-name}" \
--url "{container-url}"
----
. Synchronize the repository:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository synchronize \
--name "{container-repository-name}" \
--organization "_My_Organization_" \
--product "{container-product-name}"
----
