[id="backing-up-custom-{project-context}-server-configuration-before-upgrading"]
= Backing up custom {ProjectServer} configuration before upgrading

If you are using any custom configuration on your {ProjectServer}, {Project} might override it during the upgrade.
Back up your custom configuration so that you can restore it after the upgrade.

.Procedure

. If you have edited any of the default templates, back up the template files.
You can choose one of the following options:
** Back up the templates by cloning them.
This is the recommended method.
If you back up the templates by cloning, the upgrade process will not overwrite them.
** Back up the templates by exporting them.
After you finish upgrading, you will be able to compare the exported and default templates, and then manually apply your changes.
+
[NOTE]
====
To confirm if a template has been edited, view its *History* before you upgrade.
Alternatively, view the changes in the audit log after you upgrade.
In the {ProjectWebUI}, navigate to *Monitor* > *Audits* and search for the template to see a record of changes made.
====
+
. If you have made manual edits to you DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, ensure DNS and DHCP configuration management is disabled:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} \
--foreman-proxy-dhcp-managed=false \
--foreman-proxy-dns-managed=false
----
+
This prevents the upgrade process from overwriting your DNS and DHCP configuration.
