:_mod-docs-content-type: PROCEDURE

[id="enabling-red-hat-repositories-by-using-web-ui"]
= Enabling Red{nbsp}Hat repositories by using {ProjectWebUI}

[role="_abstract"]
If outside network access requires usage of an HTTP proxy, configure a default HTTP proxy for your {ProjectServer}.
For more information, see {InstallingServerDocURL}adding-a-default-http-proxy_{project-context}[Adding a default HTTP proxy to {Project}].

To select the repositories to synchronize, you must first identify the product that contains the repository, and then enable that repository based on the relevant release version and base architecture.

For an overview of required repositories, see xref:required-red-hat-repositories[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Red{nbsp}Hat Repositories*.
. To find repositories, either enter the repository name, or toggle the *Recommended Repositories* button to the on position to view a list of repositories that you require.
. In the Available Repositories pane, click a repository to expand the repository set.
. Click the *Enable* icon next to the base architecture and release version that you want.
