:_mod-docs-content-type: PROCEDURE

[id="registering-a-host-by-using-cli"]
= Registering a host by using Hammer CLI

[role="_abstract"]
You can register a host by using Hammer CLI with registration templates.
This also enables you to set up various integration features and host tools during the registration process.

.Prerequisites
include::snip_registering-a-host-prerequisites.adoc[]

.Procedure
. Use the `hammer host-registration generate-command` to generate the registration command to register your host.
. On your host that you want to register, run the registration command as `root`.
+
For more information, see the Hammer CLI help with `hammer host-registration generate-command --help`.

ifdef::katello,orcharhino,satellite[]
.Verification
endif::[]
ifdef::orcharhino,satellite[]
* If your activation key was supposed to enable repositories, check the `{client-redhat-repo-path}` file and verify that the repositories have been enabled.
endif::[]
ifdef::katello[]
* If your activation key was supposed to enable repositories, verify that the repositories have been enabled:
+
* On {EL}: Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
* On {DL}: Check the `/etc/apt/sources.list` file and ensure that the appropriate repositories have been enabled.
* On {SLES}: Check the `/etc/zypp/repos.d/` directory and ensure that the appropriate repositories have been enabled.
endif::[]

.Next steps
* To set up monitoring of outdated services and applications using Tracer, see {ManagingHostsDocURL}configuring-tracer-on-a-host_managing-hosts[Configuring Tracer on a host] in _{ManagingHostsDocTitle}_.
