[id="adding-gce-connection_{context}"]
= Adding a Google Compute Engine Connection to {ProjectServer}

Use this procedure to add Google Compute Engine (GCE) as a compute resource in {Project}.

.Procedure

. In GCE, generate a service account key in JSON format and upload this file to the `/usr/share/foreman/` directory on {ProjectServer}.
. On {ProjectServer}, change the owner for the service account key to the `foreman` user:
+
[options="nowrap" subs="+quotes"]
----
# chown foreman /usr/share/foreman/_gce_key_.json
----
. Configure permissions for the service account key to ensure that the file is readable:
+
[options="nowrap" subs="+quotes"]
----
# chmod 0600 /usr/share/foreman/_gce_key_.json
----
. Restore SELinux context for the service account key:
+
[options="nowrap" subs="+quotes"]
----
# restorecon -vv /usr/share/foreman/_gce_key_.json
----
. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources* and click *Create Compute Resource*.
. In the *Name* field, enter a name for the compute resource.
. From the *Provider* list, select *Google*.
. Optional: In the *Description* field, enter a description for the resource.
. In the *Google Project ID* field, enter the project ID.
. In the *Client Email* field, enter the client email.
. In the *Certificate Path* field, enter the path to the service account key. For example, `/usr/share/foreman/_gce_key_.json`.
. Click *Load Zones* to populate the list of zones from your GCE environment.
. From the *Zone* list, select the GCE zone to use.
. Click *Submit*.

.For CLI Users

. In GCE, generate a service account key in JSON format and upload this file to the `/usr/share/foreman/` directory on {ProjectServer}.

. On {ProjectServer}, change the owner for the service account key to the `foreman` user:
+
[options="nowrap" subs="+quotes"]
----
# chown foreman /usr/share/foreman/_gce_key_.json
----

. Configure permissions for the service account key to ensure that the file is readable:
+
[options="nowrap" subs="+quotes"]
----
# chmod 0600 /usr/share/foreman/_gce_key_.json
----

. Restore SELinux context for the service account key:
+
[options="nowrap" subs="+quotes"]
----
# restorecon -vv /usr/share/foreman/_gce_key_.json
----

. Use the `hammer compute-resource create` command to add a GCE compute resource to {Project}:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create --name '_gce_cr_' \
--provider 'gce' \
--project '_gce_project_id_' \
--key-path '_gce_key_.json' \
--zone '_us-west1-b_' \
--email '_gce_email_'
----
