[id="Applying_Permissions_for_the_Host_Resource_Type_{context}"]
= Applying Permissions for the Host Resource Type

The following query applies any permissions specified for the Host resource type only to hosts in the group named host-editors.

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
hostgroup = host-editors
----

The following query returns records where the name matches _XXXX_, _Yyyy_, or _zzzz_ example strings:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
name ^ (XXXX, Yyyy, zzzz)
----

You can also limit permissions to a selected environment.
To do so, specify the environment name in the *Search* field, for example:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
Dev
----

You can limit user permissions to a certain organization or location with the use of the granular permission filter in the *Search* field.
However, some resource types provide a GUI alternative, an *Override* checkbox that provides the *Locations* and *Organizations* tabs.
On these tabs, you can select from the list of available organizations and locations.
For more information, see xref:Creating_an_Organization_Specific_Manager_Role_{context}[].
