[id="Importing_Puppet_Classes_and_Environments_{context}"]
= Importing Puppet Classes and Environments into {Project}

Import Puppet classes and environments from the installed Puppet modules to {ProjectServer} or any attached {SmartProxyServer} before you assign any of the classes to managed hosts.

.Prerequisite
* Ensure to select *Any Organization* and *Any Location* as context, otherwise the import might fail.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure > Classes*.
. Click the *Import* button in the upper right corner and select which {SmartProxy} you want to import modules from.
You may typically choose between your {ProjectServer} or any attached {SmartProxyServer}.
. Select the Puppet module you want to import:
.. Select the classes of your choice and check the _box_ on the left.
.. Click the *Update* button to import the Puppet classes to {Project}.
. The import should result in a notification as follows:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
Successfully updated environments and Puppet classes from the on-disk Puppet installation
----
