[id="Using_an_HTTP_Proxy_with_Compute_Resources_Amazon_EC2_{context}"]
= Using an HTTP Proxy with Compute Resources

In some cases, the EC2 compute resource that you use might require a specific HTTP proxy to communicate with {Project}.
In {Project}, you can create an HTTP proxy and then assign the HTTP proxy to your EC2 compute resource.

However, if you configure an HTTP proxy for {Project} in *Administer*{nbsp}>{nbsp}*Settings*, and then add another HTTP proxy for your compute resource, the HTTP proxy that you define in *Administer*{nbsp}>{nbsp}*Settings* takes precedence.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*HTTP Proxies*, and select *New HTTP Proxy*.
. In the *Name* field, enter a name for the HTTP proxy.
. In the *URL* field, enter the URL for the HTTP proxy, including the port number.
. Optional: Enter a username and password to authenticate to the HTTP proxy, if your HTTP proxy requires authentication.
. Click *Test Connection* to ensure that you can connect to the HTTP proxy from {Project}.
. Click the *Locations* tab and add a location.
. Click the *Organization* tab and add an organization.
. Click *Submit*.
