:_mod-docs-content-type: PROCEDURE

[id="upgrading-container-images-of-{insights-iop-id}"]
= Upgrading container images of {insights-iop}

[role="_abstract"]
If you have {insights-iop} enabled on your {ProjectServer}, prepare the container images of {insights-iop} for {Project} {ProjectVersion} and load them on the disconnected server before running the upgrade.

.Prerequisites
* {insights-iop} is enabled on your disconnected {ProjectServer}.

.Procedure
* Update the {insights-iop} container images from the ISO image for {ProjectVersion}:
.. Download and mount the {Project} installation ISO.
For more information, see {InstallingServerDisconnectedDocURL}installing-from-the-offline-repositories_{context}[Installing the {Project} packages from the offline repositories] in _{InstallingServerDisconnectedDocTitle}_.
.. Set up the local repositories for disconnected environments.
For more information, see {InstallingServerDisconnectedDocURL}installing-from-the-offline-repositories_{context}[Installing the {Project} packages from the offline repositories] in _{InstallingServerDisconnectedDocTitle}_.
.. Run the container setup script from the mounted ISO to load the {insights-iop} images for {ProjectVersion}:
+
[options="nowrap"]
----
# /media/sat6/prepare_system
----
