[id="Configuring_the_Fallback_to_any_{smart-proxy-context}_Remote_Execution_Setting_in_{project-context}_{context}"]
= Configuring the Fallback to Any {SmartProxy} Remote Execution Setting in {Project}

You can enable the *Fallback to Any {SmartProxy}* setting to configure {Project} to search for remote execution {SmartProxies} from the list of {SmartProxies} that are assigned to hosts.
This can be useful if you need to run remote jobs on hosts that have no subnets configured or if the hosts' subnets are assigned to {SmartProxies} that do not have the remote execution feature enabled.

If the *Fallback to Any {SmartProxy}* setting is enabled, {Project} adds another set of {SmartProxies} to select the remote execution {SmartProxy} from.
{Project} also selects the most lightly loaded {SmartProxy} from the set of all {SmartProxies} assigned to the host, such as the following:

* DHCP, DNS and TFTP {SmartProxies} assigned to the host's subnets
* DNS {SmartProxy} assigned to the host's domain
* Realm {SmartProxy} assigned to the host's realm
* Puppet server {SmartProxy}
* Puppet CA {SmartProxy}
* OpenSCAP {SmartProxy}

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. Click *Remote Execution*.
. Configure the *Fallback to Any {SmartProxy}* setting.

.CLI procedure
* Enter the `hammer settings set` command on {Project} to configure the *Fallback to Any {SmartProxy}* setting.
To set the value to `true`, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer settings set \
--name=remote_execution_fallback_proxy \
--value=true
----
