[id="executing-a-remote-job_{context}"]
= Executing a Remote Job

You can execute a job that is based on a job template against one or more hosts.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-executing-a-remote-job_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts* and select the target hosts on which you want to execute a remote job.
You can use the search field to filter the host list.
. From the *Select Action* list, select *Schedule Remote Job*.
. On the *Job invocation* page, define the main job settings:
. Select the *Job category* and the *Job template* you want to use.
. Optional: Select a stored search string in the *Bookmark* list to specify the target hosts.
. Optional: Further limit the targeted hosts by entering a *Search query*.
The *Resolves to* line displays the number of hosts affected by your query.
Use the refresh button to recalculate the number after changing the query.
The preview icon lists the targeted hosts.
. The remaining settings depend on the selected job template.
See {ManagingHostsDocURL}creating-a-job-template_managing-hosts[Creating a Job Template] for information on adding custom parameters to a template.
. Optional: To configure advanced settings for the job, click *Display advanced fields*.
Some of the advanced settings depend on the job template, the following settings are general:

* *Effective user* defines the user for executing the job, by default it is the SSH user.

* *Concurrency level* defines the maximum number of jobs executed at once, which can prevent overload of systems' resources in a case of executing the job on a large number of hosts.

* *Timeout to kill* defines time interval in seconds after which the job should be killed, if it is not finished already.
A task which could not be started during the defined interval, for example, if the previous task took too long to finish, is canceled.

* *Type of query* defines when the search query is evaluated.
This helps to keep the query up to date for scheduled tasks.

* *Execution ordering* determines the order in which the job is executed on hosts: alphabetical or randomized.
+
*Concurrency level* and *Timeout to kill* settings enable you to tailor job execution to fit your infrastructure hardware and needs.

. To run the job immediately, ensure that *Schedule* is set to *Execute now*.
You can also define a one-time future job, or set up a recurring job.
For recurring tasks, you can define start and end dates, number and frequency of runs.
You can also use cron syntax to define repetition.
ifndef::orcharhino[]
For more information about cron, see the https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-automating_system_tasks[Automating System Tasks] section of the Red Hat Enterprise Linux 7 _System Administrator's Guide_.
endif::[]

. Click *Submit*.
This displays the *Job Overview* page, and when the job completes, also displays the status of the job.

[id="cli-executing-a-remote-job_{context}"]
.CLI procedure

* Enter the following command on {Project}:

----
# hammer settings set --name=remote_execution_global_proxy --value=false
----

To execute a remote job with custom parameters, complete the following steps:

. Find the ID of the job template you want to use:
+
----
# hammer job-template list
----

. Show the template details to see parameters required by your template:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer job-template info --id _template_ID_
----

. Execute a remote job with custom parameters:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer job-invocation create \
--job-template "_template_name_" \
--inputs _key1_="_value_",_key2_="_value_",... \
--search-query "_query_"
----
+
Replace _query_ with the filter expression that defines hosts, for example `"name ~ rex01"`.
For more information about executing remote commands with hammer, enter `hammer job-template --help` and `hammer job-invocation --help`.
