:_mod-docs-content-type: PROCEDURE

[id="tuning-postgresql"]
= Tuning PostgreSQL

[role="_abstract"]
Configure PostgreSQL database settings to improve response times.
Tuning PostgreSQL reduces query latency and improves system responsiveness, especially with high database activity.

The PostgreSQL authors recommend disabling Transparent Hugepage on servers running PostgreSQL.
For more information, see xref:transparent-hugepage-and-database-performance[].

Tune PostgreSQL by modifying the `postgresql.conf` file.
This works regardless of the tuning profile.

.Procedure
. Append `/etc/foreman-installer/custom-hiera.yaml` to tune PostgreSQL:
+
[source, yaml]
----
postgresql::server::config_entries:
  max_connections: 1000
  shared_buffers: 2GB
  work_mem: 8MB
  autovacuum_vacuum_cost_limit: 2000
----
+
This tuning configuration alters the following keys:

`max_connections`:: Maximum number of connections PostgreSQL can accept.
`shared_buffers`:: Memory used by all active connections to store data for database operations.
Set this between 2 GiB to 25% of total system memory depending on database operation frequency.
`work_mem`:: Memory allocated per process to store temporary results of database operations.
Set this to 8 MB for most heavy operations.
`autovacuum_vacuum_cost_limit`:: Cost limit for the vacuuming operation that cleans up dead tuples in database relations.
This defines how many tuples can be processed in a single run.
{Team} recommends `2000` for the _medium_, _large_, _extra-large_, and _extra-extra-large_ profiles.
. Reconfigure your {Project}:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
+
----
# {foreman-installer}
----
