:_mod-docs-content-type: PROCEDURE

[id="customizing-job-templates"]
= Customizing job templates

[role="_abstract"]
{Project} provides default job templates that you can use for executing jobs.
Default job templates are locked for editing but you can clone them and edit the clone.

Job templates use the Embedded Ruby (ERB) syntax.
Ansible job templates use YAML syntax.

At run time, job templates can accept parameter variables that you define for a host.
Note that only the parameters visible on the *Parameters* tab at the host's edit page can be used as input parameters for job templates.

.Procedure
. Navigate to *Hosts* > *Templates* > *Job templates* to view the list of job templates.
. To clone a template, in the *Actions* column, select *Clone*.
. Enter a unique name for the clone and click *Submit* to save the changes.
. In the list of job templates, click the cloned template to start editing it.
+
[NOTE]
====
An Ansible template must begin with `---`.
You can embed an Ansible Playbook YAML file into the job template body.
You can also add ERB syntax to customize your YAML Ansible template.
====

.Additional resources
* {ManagingHostsDocURL}Template_Writing_Reference_managing-hosts[Template Writing Reference in _{ManagingHostsDocTitle}_]
* {AdministeringDocURL}synchronizing-template-repositories[Synchronizing template repositories in _{AdministeringDocTitle}_]
