:_mod-docs-content-type: PROCEDURE

[id="renaming-{project-context}_{context}"]
= Renaming {ProjectServer}

[role="_abstract"]
The host name of {ProjectServer} is used by {ProjectServer} components, all {SmartProxyServers}, and hosts registered to it for communication.
This procedure ensures that in addition to renaming {ProjectServer}, you also update all references to point to the new host name.

[WARNING]
====
Renaming your {ProjectServer} host shuts down all {Project} services on that host.
The services restart after the renaming is complete.
====

.Prerequisites
* Back up your {ProjectServer} before changing its host name.
If you fail to successfully rename it, restore it from the backup.
For more information, see xref:backing-up-{project-context}-server-and-{smart-proxy-context}_{context}[].
* Run the `hostname` and `hostname -f` commands on {ProjectServer}.
If both commands do not return the FQDN of {ProjectServer}, the `{project-change-hostname}` script will fail to complete.
+
If the `hostname` command returns the shortname of {ProjectServer} instead of the FQDN, use `hostnamectl set-hostname _My_Old_FQDN_` to set the old FQDN correctly before using the `{project-change-hostname}` script.
* If {ProjectServer} has a custom SSL certificate installed, obtain a new certificate for the new FQDN of the host.
ifndef::orcharhino[]
For more information, see {InstallingServerDocURL}configuring-satellite-custom-server-certificate_{project-context}[Configuring {ProjectServer} with a Custom SSL Certificate] in _{InstallingServerDocTitle}_.
endif::[]

.Procedure
. On {ProjectServer}, run the `{project-change-hostname}` script, and provide the new host name.
Choose one of the following methods:
+
* If your {ProjectServer} is installed with the default self-signed SSL certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {project-change-hostname} _new-{project-context}_ \
--username _My_Username_ \
--password '_My_Password_'
----
* If your {ProjectServer} is installed with custom SSL certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {project-change-hostname} _new-{project-context}_ \
--username _My_Username_ \
--password '_My_Password_' \
--custom-cert "/root/ownca/test.com/test.com.crt" \
--custom-key "/root/ownca/test.com/test.com.key"
----
. If you have created a custom SSL certificate for the new {ProjectServer} host name, run the {Project} installation script to install the certificate.
ifndef::orcharhino[]
For more information about installing a custom SSL certificate, see {InstallingServerDocURL}Deploying_a_Custom_SSL_Certificate_to_Server_{project-context}[Deploying a Custom SSL Certificate to {ProjectServer}] in _{InstallingServerDocTitle}_.
endif::[]
. Reregister all hosts and {SmartProxyServers} that are registered to {ProjectServer}.
For more information, see {ManagingHostsDocURL}Registering_Hosts_by_Using_Global_Registration_managing-hosts[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_.
. On all {SmartProxyServers}, run the {Project} installation script to update references to the new host name:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--foreman-proxy-foreman-base-url https://_new-{foreman-example-com}_ \
--foreman-proxy-trusted-hosts _new-{foreman-example-com}_
----
. On {ProjectServer}, list all {SmartProxyServers}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {hammer-smart-proxy} list
----
. On {ProjectServer}, synchronize content for each {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {hammer-smart-proxy} content synchronize \
--id __My_{smart-proxy-context-titlecase}_ID__
----
. If you use the _virt-who_ agent, update the _virt-who_ configuration files with the new host name.
ifdef::satellite[]
For more information, see {ConfiguringVMSubscriptionsDocURL}troubleshooting-virt-who#modifying-virt-who-configuration_vm-subs-satellite[Modifying a virt-who Configuration] in _{ConfiguringVMSubscriptionsDocTitle}_.
endif::[]
. If you use external authentication, reconfigure {ProjectServer} for external authentication after you run the `{project-change-hostname}` script.
For more information, see {ConfiguringUserAuthenticationDocURL}[_{ConfiguringUserAuthenticationDocTitle}_].
