:_mod-docs-content-type: PROCEDURE

[id="Importing_Report_Templates_{context}"]
= Importing report templates

You can import a report template into the body of a new template that you want to create.
Note that using the {ProjectWebUI}, you can only import templates individually.
For bulk actions, use the {Project} API.
For more information, see xref:Importing_Report_Templates_Using_the_API_{context}[].

.Prerequisites
* You must have exported templates from {Project} to import them to use in new templates.
For more information see xref:exporting-report-templates-by-using-web-ui[] and xref:exporting-report-templates-by-using-cli[].

.Procedure
. In the {ProjectWebUI}, navigate to *Monitor* > *Reports* > *Report Templates*.
. In the upper right of the Report Templates window, click *Create Template*.
. On the upper right of the *Editor* tab, click the folder icon, and select the `.erb` file that you want to import.
. Edit the template to suit your requirements.
. Click *Submit*.

For more information about customizing your new template, see xref:Template_Writing_Reference_{context}[].
