[id="Upgrading-Project-From-RHEL7-to-RHEL8_{context}"]
= Upgrading {Project} From {RHEL} 7 to {RHEL} 8

Use this procedure to upgrade your {Project} installation from {RHEL} 7 to {RHEL} 8.

.Prerequisites
* {Project} {ProjectVersion} is supported on both {RHEL} 7 and {RHEL} 8.
* Subsequent minor versions of {Project} {ProjectVersion} will be supported on {RHEL} 8 only.
* If you have {Project} {ProjectVersion} running on {RHEL} 7, you must migrate to {RHEL} 8 to stay up to date on {Project} {ProjectVersion} minor releases.
* An offline backup created by `{foreman-maintain}`.
This can be an older full backup with incremental backups leading to the point from where you want to restore.
* An identical machine that can be configured with the same hostname and IP address as the source.

.Fresh Install Migration
. You can create a {RHEL} 8 system with identical specifications and the same hostname as the {RHEL} 7 system using the fresh install migration method.
. You can choose how much of the {RHEL} 7 system to include in the backup to selectively import the relevant parts of the {RHEL} 7 system to {RHEL} 8.
. This method requires a considerable amount of system downtime while the system backup is restored on the {RHEL} 8 system.
. To reduce the amount of downtime, you can continue to use the {RHEL} 7 system on the target machine while the backup is being restored.
. Any new changes you make during this time are not included in the backup on the {RHEL} 8 system on the source machine.
. Storage space is required for the backup and access to a second machine to host the new {RHEL} 8 system.

.In-Place Migration Using LEAPP
. The in-place migration method requires several hours less downtime than the fresh install method.
. You do not need to provide storage space for a backup or a second machine for {RHEL} 8, as the migration can occur in place on the {RHEL} 7 machine.
. Downtime cannot be avoided entirely by using the {RHEL} 7 system while the {RHEL} 8 system is preparing because the in-place migration occurs on the same machine.
. The in-place migration using LEAPP is not possible with FIPS-enabled systems.
