[id="Creating-an-operating-system-for-{DL}-{DL-major-context}_{context}"]
= Creating an operating system for {DL} {DL-major}

Create an operating system in {Project} to provision hosts running {DL} {DL-major}.
This example creates an operating system entry for {DL} {DL-major}.

ifdef::orcharhino[]
include::snip_creating-os-on-orcharhino.adoc[]
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning Setup* > *Operating Systems*.
. Click *Create Operating System* to create an operating system entry for {DL}.
. Enter `{DL} {DL-major}` as *Name* for the operating system.
Choose a name as reported by Ansible, Puppet, or Salt as fact.
. Set the *Major Version* to `{DL-major}`.
. Leave the *Minor Version* field empty.
. Set the *Release Name* to `{DL-codename}` for {DL} {DL-major}.
. On the *Partition Table* tab, select the `Preseed` partition table.
+
For more information, see xref:creating-partition-tables_{context}[].
. On the *Templates* tab, select the `Preseed Finish` template as *Finish template*, the `Preseed` template as *Provisioning Template*, and the `Preseed PXELinux` template as *PXELinux template*.
ifdef::orcharhino[]
include::snip_host-parameters-for-orcharhino-clients.adoc[]
endif::[]
+
For more information, see xref:creating-provisioning-templates_{context}[].
. Click *Submit* to save the operating system entry for {DL}.
