[id="Creating_a_Custom_File_Type_Repository_in_a_Local_Directory_{context}"]
= Creating a {customfiletypetitle} Repository in a Local Directory

You can create a {customfiletype} repository, from a directory of files, on the base system where {Project} is installed using the `pulp-manifest` command.
You can then synchronize the files into {ProjectServer}.
When you add files to a file type repository, you can work with the files as with any other repository.

Use this procedure to configure a repository in a directory on the base system where {Project} is installed.
To create a file type repository in a directory on a remote server, see xref:Creating_a_Remote_File_Type_Repository_{context}[].

.Procedure

To create a file type repository in a local directory, complete the following procedure:

. Ensure the Server and {project-client-name} repositories are enabled.
ifdef::satellite[]
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL7Server} \
--enable={project-client-RHEL7-url}
----
endif::[]
. Install the Pulp Manifest package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} python3-pulp_manifest
----
+
Note that this command stops the {Project} service and re-runs {foreman-installer}.
Alternatively, to prevent downtime caused by stopping the service, you can use the following:
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable {RepoRHEL7ServerSatelliteToolsProductVersion}
# {foreman-maintain} packages unlock
# yum install install python-pulp-manifest -y
# {foreman-maintain} packages lock
# subscription-manager repos --disable {RepoRHEL7ServerSatelliteToolsProductVersion}
----
This installs the package without downtime.
. Create a directory that you want to use as the file type repository in the HTTP server's public folder:
+
[options="nowrap" subs="+quotes"]
----
# mkdir __my_file_repo__
----
. Add files to the directory or create a test file:
+
[options="nowrap" subs="+quotes"]
----
# touch __my_file_repo__/_test.txt_
----
. Enter the Pulp Manifest command to create the manifest:
+
[options="nowrap" subs="+quotes"]
----
# pulp-manifest __my_file_repo__
----
. Verify the manifest was created:
+
[options="nowrap" subs="+quotes"]
----
# ls __my_file_repo__
PULP_MANIFEST test.txt
----

.Importing Files from a File Type Repository

To import files from a file type repository in a local directory, complete the following procedure:

. Ensure a {customproduct} exists in {ProjectServer}.
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select the name of a product.
. Click the *Repositories* tab and select *New Repository*.
. In the *Name* field, enter a name for the repository.
{Project} automatically completes this field based on what you enter for *Name*.
. From the *Type* list, select the content type of the repository.
. In the *Upstream URL* field, enter the local directory with the repository to use as the source, in the form `\file:///__my_file_repo__`.
. Select the *Verify SSL* check box to check the SSL certificate for the repository or clear the *Verify SSL* check box.
. Optional: In the *Upstream Username* field, enter the upstream user name that you require.
. Optional: In the *Upstream Password* field, enter the corresponding password for your upstream user name.
. Optional: In the *Upstream Authentication Token* field, provide the token of the upstream repository user for authentication.
Leave this field empty if the repository does not require authentication.
. Optional: Check the *Mirror on Sync* checkbox to have this repository mirror the source repository during synchronization.
It defaults to `true` (checked).
. Optional: In the *HTTP Proxy Policy* field, select the desired HTTP proxy.
The default value is `Global Default`.
. Optional: Check the *Publish via HTTP* to have this repository published using HTTP during synchronization.
It defaults to `true` (checked).
. Optional: In the *GPG Key* field, select the GPG key for the repository.
. Optional: In the *SSL CA Cert* field, select the SSL CA Certificate for the repository.
. Optional: In the *SSL Client cert* field, select the SSL Client Certificate for the repository.
. Optional: In the *SSL Client Key* field, select the SSL Client Key for the repository.
. Select *Save* to save this repository entry.

.Updating a File Type Repository

To update the file type repository, complete the following steps:

. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select the name of a product.
. Select the name of the repository you want to update.
. From the *Select Action* menu, select *Sync Now*.
. Visit the URL where the repository is published to see the files.
