:_mod-docs-content-type: PROCEDURE

[id="enabling-red-hat-repositories-by-using-web-ui"]
= Enabling Red{nbsp}Hat repositories by using {ProjectWebUI}

[role="_abstract"]
Enable Red{nbsp}Hat repository sets for the product, release, and base architecture you need so {Project} can synchronize the packages your hosts require; see xref:required-red-hat-repositories[] for required sets.

[NOTE]
====
If outbound access uses an HTTP proxy, configure a default proxy on {ProjectServer} before you enable repositories: {InstallingServerDocURL}adding-a-default-http-proxy-by-using-web-ui[Adding a default HTTP proxy to {Project}].
====

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Red{nbsp}Hat Repositories*.
. To find repositories, either enter the repository name, or toggle the *Recommended Repositories* button to the on position to view a list of repositories that you require.
. In the Available Repositories pane, click a repository to expand the repository set.
. Click the *Enable* icon next to the base architecture and release version that you want.
