:_mod-docs-content-type: PROCEDURE

[id="uploading-content-to-custom-rpm-repositories-by-using-cli"]
= Uploading content to {customrpm} repositories by using Hammer CLI

[role="_abstract"]
You can upload individual RPMs and source RPMs to {customrpm} repositories by using Hammer CLI.

.Procedure
* Upload an RPM package:
+
[options="nowrap" subs="+quotes,verbatim"]
----
$ hammer repository upload-content \
--id _My_Repository_ID_ \
--path __/path/to/example-package.rpm__
----
* Upload a source RPM package:
+
[options="nowrap" subs="+quotes,verbatim"]
----
$ hammer repository upload-content \
--content-type srpm \
--id _My_Repository_ID_ \
--path __/path/to/example-package.src.rpm__
----

.Verification
* After the upload is complete, you can view information about a source RPM by using the commands `hammer srpm list` and `hammer srpm info --id _srpm_ID_`.

.Next steps
* Add your {customrpm} repository to a content view.
For more information, see xref:creating-a-content-view-by-using-cli[].
* If your {customrpm} is unprotected, hosts can consume its content by using the *Published At* URL.
+
In the Default Organization View content view, the URL consists of your {SmartProxy} FQDN, `/pulp/content/`, your organization label, `/Library/custom/`, your product label, `/`, your repository label, and a trailing `/`, for example, `\https://foreman.example.com/pulp/content/Example/Library/custom/my-software/my-app/`.
ifdef::orcharhino[]
+
include::snip_important-consuming-content-requires-a-subscription.adoc[]
endif::[]
