:_mod-docs-content-type: PROCEDURE

[id="Resetting_the_Administrative_User_Password_{context}"]
= Resetting the administrative user password

[role="_abstract"]
You can reset the administrative password to randomly generated characters or set a new administrative password.
This might be useful when you forget the password or when the administrative user is deleted.

.Procedure
* To reset the administrative user password:
.. Log in to the base operating system where {ProjectServer} is installed.
.. Enter the following command to reset the password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake permissions:reset
Reset to user: admin, password: qwJxBptxb7Gfcjj5
----
.. Use this password to reset the password in the {ProjectWebUI}.
.. Edit the `~/.hammer/cli.modules.d/foreman.yml` file on {ProjectServer} to add the new password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# vi ~/.hammer/cli.modules.d/foreman.yml
----
+
[NOTE]
====
Unless you update the `~/.hammer/cli.modules.d/foreman.yml` file, you cannot use the new password with Hammer CLI.
====

* To set a new administrative user password:
.. Log in to the base operating system where {ProjectServer} is installed.
.. To set the password for a user, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake permissions:reset username=_user_ password=_new_password_
----
+
Replace `_user_` with the username whose password you want to reset.
+
[NOTE]
====
If you enter a username that does not exist, the `foreman-rake` utility creates a new administrative user with the defined password.
====

.. Edit the `~/.hammer/cli.modules.d/foreman.yml` file on {ProjectServer} to add the new password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# vi ~/.hammer/cli.modules.d/foreman.yml
----
+
[NOTE]
====
Unless you update the `~/.hammer/cli.modules.d/foreman.yml` file, you cannot use the new password with Hammer CLI.
====
