[id="optimizing-performance-by-removing-nics-from-database_{context}"]
= Optimizing performance by removing NICs from database

Filter and exclude the connections using the `Exclude pattern for facts stored in {Project}` and `Ignore interfaces with matching identifier` option.
By default, these options are set to most common hypervisors.
If you name the virtual interfaces differently, you can update this filter to use it according to your requirements.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings* and select the *Facts* tab.
. To filter out all interfaces starting with specific names, for example, `blu`, add `blu*` to the `Ignore interfaces with matching identifier` option.
. To prevent databases from storing facts related to interfaces starting with specific names, for example, `blu`, add `blu*` to the `Exclude pattern for facts stored in {Project}` option.
+
By default, it contains the same list as the `Ignore interfaces with matching identifier` option.
You can override it based on the your requirements.
This filters out facts completely without storing them.

. To remove facts from the database, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake facts:clean
----
+
This command removes all facts matching with the filter added in *Administer* > *Settings* > *Facts* > the `Exclude pattern for facts stored in {Project}` option.

. To remove interfaces from the database, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake interfaces:clean
----
+
This command removes all interfaces matching with the filter added in *Administer* > *Settings* > *Facts* > the `Ignore interfaces with matching identifier` option.
