:_mod-docs-content-type: PROCEDURE

[id="creating-custom-alternate-content-sources-by-using-cli"]
= Creating custom alternate content sources by using Hammer CLI

[role="_abstract"]
You can create custom alternate content sources (ACS) to define alternate paths to download content during synchronization.

.Prerequisites
* If the repository requires SSL authentication, import the SSL certificate and key into {Project}.
For more information, see {ContentManagementDocURL}importing-custom-ssl-certificates-by-using-cli[Importing custom SSL certificates by using Hammer CLI] in _{ContentManagementDocTitle}_.
* You have the base URL and subpaths of your alternate content source.
For example, if your base URL is `\https://{server-example-com}` and your subpaths are `rhel10/` and `rhel9/`, then {Project} will search `\https://{server-example-com}/rhel10/` and `\https://{server-example-com}/rhel9/`.

.Procedure
. Create a custom alternate content source:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer alternate-content-source create \
--alternate-content-source-type custom \
--base-url "_https://local-repo.example.com:port_" \
--name "_My_ACS_Name_" \
--smart-proxy-ids __My_{smart-proxy-context-titlecase}_ID_1__,__My_{smart-proxy-context-titlecase}_ID_2__ \
--verify-ssl _true_
----
. Refresh your alternate content source:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer alternate-content-source refresh --name "_My_ACS_Name_"
----

.Verification
* Verify that the task ran successfully:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer task list --search "Refresh Alternate Content Source"
----
