:_mod-docs-content-type: PROCEDURE

[id="applying-errata-to-hosts-by-using-mcp"]
= Applying errata to hosts by using MCP

[role="_abstract"]
You can prompt your AI application to create remote execution jobs in {Project} to apply errata to hosts.
You can define the set of hosts through AI in natural language.

[WARNING]
====
Review the actions being performed by AI before using it in production.
====

.Prerequisites
* An AI application connected to the MCP server for {Project}.
For more information, see {ManagingHostsDocURL}connecting-ai-applications-to-the-mcp-server-for-{project-context}[Connecting AI applications to the MCP server for {Project}] in _{ManagingHostsDocTitle}_.

.Procedure
. Allow the MCP server to trigger remote execution jobs for errata installation:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ podman run --interactive --tty --publish 127.0.0.1:8080:8080 \
  --volume _Path_to_My_CA_Bundle_:/app/ca.pem:ro,Z \
  {mcp-server-image} \
  --foreman-url https://_{foreman-example-com}_
  --allowed-rex-features katello_errata_install,katello_errata_install_by_search
----
+
For more information, see {ManagingHostsDocURL}deploying-the-mcp-server-for-{project-context}[Deploying the MCP server for {Project}] in _{ManagingHostsDocTitle}_.
. Type a prompt in your AI application to list any host with outstanding errata.
+
[options="nowrap", subs="+quotes,attributes"]
----
Show a list of hosts that require patching on my {Project}.
----
+
[options="nowrap", subs="+quotes,attributes"]
----
Categorize the list into hosts that require security patches and hosts that require bug fix patches.
----
. The MCP server returns a list of hosts with installable errata to the AI application.
Review the information and if it is correct, use the prompt to apply errata to the hosts.
The MCP server for {Project} provides a prompt for this purpose:
+
[options="nowrap", subs="+quotes,attributes"]
----
Apply Errata to Hosts
----
+
Refer to the documentation of your AI application to find more about how to use prompts provided by MCP server.
Review all the steps that the AI application performs.
