:_mod-docs-content-type: PROCEDURE

[id="disabling-dns-for-integration"]
= Disabling DNS for integration

[role="_abstract"]
If you want to manually manage a DNS service and not integrate it into {ProjectServer}, you must prevent {Project} from maintaining this service on the operating system and disable orchestration to avoid errors.

[NOTE]
====
Disabling DNS in {Project} does not remove the related backend service on the operating system.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets*.
. For each subnet that is associated with the DNS {SmartProxy}:
.. Select the subnet.
.. On the *{SmartProxies}* tab, clear the *Reverse DNS {SmartProxy}* field.
.. Click *Submit*.
. Navigate to *Infrastructure* > *Domains*.
. For each domain that is associated with the DNS {SmartProxy}:
.. Select the domain.
.. Clear the *DNS {SmartProxy}* field.
.. Click *Submit*.
. On {ProjectServer}, enter:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-proxy-dns false
----
+
[NOTE]
====
{Project} does not perform orchestration when a {SmartProxy} is not set for a given subnet and domain.
When you disable {SmartProxy} associations, orchestration commands for existing hosts can fail if the expected records and configuration files are not present.
====
