[id="Using_Upstream_Server_as_a_Content_Store_{context}"]
= Using an Upstream {ProjectServer} as a Content Store

In this scenario, you use the upstream {ProjectServer} as a content store for updates rather than to manage content.
You use the downstream {ProjectServer} to manage content for all infrastructure behind the isolated network.
You export the Library content from the upstream {ProjectServer} and import it into the downstream {ProjectServer}.

.On the upstream {ProjectServer}
. Ensure that repositories are using the *Immediate* download policy in one of the following ways:
.. For existing repositories using *On Demand*, change their download policy on the repository details page to *Immediate*.
.. For new repositories, ensure that the *Default Red Hat Repository download policy* setting is set to *Immediate* before enabling Red Hat repositories, and that the *Default download policy* is set to *Immediate* for custom repositories.

+
For more information, see xref:Download_Policies_Overview_{context}[].
. Enable the content that you want to synchronize.
For more information, see xref:Enabling_Red_Hat_Repositories_{context}[].
+
If you want to sync custom content, first xref:Creating_a_Custom_Product_{context}[create a custom Product] and xref:Synchronizing_Repositories_{context}[synchronize Product repositories].
. Synchronize the enabled content:
.. On the first export, perform a `complete` Library export so that all the synchronized content is exported.
This generates content archives that you can later import into one or more downstream {ProjectServer}s.
For more information on performing a complete Library export, see xref:Exporting_the_Library_Environment_{context}[].
.. Export all future updates on the upstream {ProjectServer} incrementally.
This generates leaner content archives that contain only a recent set of updates.
For example, if you enable and synchronize a new repository, the next exported content archive contains content only from the newly enabled repository.
For more information on performing an incremental Library export, see xref:Exporting_Library_Incrementally_{context}[].

.On the downstream {ProjectServer}
. Bring the content exported from the upstream {ProjectServer} over to the hard disk.
. Place it inside a directory under `/var/lib/pulp/imports`.
. Import the content to an organization using the procedure outlined in xref:Importing_into_the_Library_Environment_{context}[].
+
You can then manage content using Content Views or Lifecycle Environments as you require.
