[id="Enabling_Connections_from_a_Client_to_Server_{context}"]
= Enabling Connections from a Client to {ProjectServer}

{SmartProxies} and Content Hosts that are clients of a {ProjectServer}'s internal {SmartProxy} require access through {Project}'s host-based firewall and any network-based firewalls.

Use this procedure to configure the host-based firewall on the system that {Project} is installed on, to enable incoming connections from Clients, and to make the configuration persistent across system reboots.
For more information on the ports used, see {InstallingServerDocURL}satellite-ports-and-firewalls-requirements_{project-context}[Ports and Firewalls Requirements].

include::snip_firewalld.adoc[]

.Procedure
. To open the ports for client to {Project} communication, enter the following command on the base operating system that you want to install {Project} on:
+
[options="nowrap", subs="+quotes,attributes"]
----
# firewall-cmd --add-service={firewalld-profile}
----
. Make the changes persistent:
+
[options="nowrap"]
----
# firewall-cmd --runtime-to-permanent
----
