[id="Configuring_a_Finish_Template_for_Amazon_EC2_{context}"]
= Configuring a finish template for an Amazon Web Service EC2 environment

ifdef::satellite[]
You can use {ProjectName} finish templates during the provisioning of {RHEL} instances in an Amazon EC2 environment.
endif::[]

ifndef::satellite[]
You can use {ProjectName} finish templates during the provisioning of Linux instances in an Amazon EC2 environment.
endif::[]

If you want to use a Finish template with SSH, {Project} must reside within the EC2 environment and in the correct security group.
{Project} currently performs SSH finish provisioning directly, not using {SmartProxyServer}.
If {ProjectServer} does not reside within EC2, the EC2 virtual machine reports an internal IP rather than the necessary external IP with which it can be reached.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Templates* > *Provisioning Templates*.
. In the *Provisioning Templates* page, enter `Kickstart default finish` into the search field and click *Search*.
. On the *Kickstart default finish* template, select *Clone*.
. In the *Name* field, enter a unique name for the template.
ifdef::satellite[]
. In the template, prefix each command that requires root privileges with `sudo`, except for `subscription-manager register` and `yum` commands, or add the following line to run the entire template as the sudo user:
endif::[]
ifndef::satellite[]
. In the template, prefix each command that requires root privileges with `sudo`, except for `yum` or equivalent commands, or add the following line to run the entire template as the `sudo` user:
endif::[]
+
----
sudo -s << EOS
_Template_ _Body_
EOS
----
+
. Click the *Association* tab, and associate the template with a {RHEL} operating system that you want to use.
. Click the *Locations* tab, and add the the location where the host resides.
. Click the *Organizations* tab, and add the organization that the host belongs to.
. Make any additional customizations or changes that you require, then click *Submit* to save your template.
. In the {ProjectWebUI}, navigate to *Hosts* > *Operating systems* and select the operating system that you want for your host.
. Click the *Templates* tab, and from the *Finish Template* list, select your finish template.
include::snip_steps-create-a-host-tab-host.adoc[]
. Click the *Parameters* tab and navigate to *Host parameters*.
ifdef::katello,satellite,orcharhino[]
. In *Host parameters*, click *Add Parameter* two times to add two new parameter fields.
Add the following parameters:
.. In the *Name* field, enter `activation_keys`.
In the corresponding *Value* field, enter your activation key.
endif::[]
ifndef::katello,satellite,orcharhino[]
. If you have the Remote Execution plugin installed, in *Host parameters*, click *Add Parameter*.
endif::[]
.. In the *Name* field, enter `remote_execution_ssh_user`.
In the corresponding *Value* field, enter `ec2-user`.
. Click *Submit* to save the changes.
