[id="Managing_Packages_on_the_Base_Operating_System_{context}"]
= Managing packages on the base operating system of {ProjectServer} or {SmartProxyServer}

{Project} provides the `{foreman-maintain} packages` command to install and update packages on the base operating system of your {ProjectServer} or {SmartProxyServers}.

[WARNING]
====
Installing and updating packages with `yum` is not supported because it can lead to package inconsistencies on your {ProjectServer} or {SmartProxyServers}.
Always use `{foreman-maintain} packages` to install or update packages.
====

The `{foreman-maintain} packages` command restarts some services on the base operating system because it runs the `{foreman-installer}` command after installing packages.

You can manage packages using `{foreman-maintain} packages` command as follows:

* To install packages on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-install} _package_1_ _package_2_
----
* To check for available package updates on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-check-update}
----
* To update all packages on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-update}
----
* To update specific packages on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {project-package-update} _package_1_ _package_2_
----

.Additional resources
* For information about updating {Project} to the next patch version, see {UpdatingDocURL}[_{UpdatingDocTitle}_].
* For a complete reference about using `{foreman-maintain} packages`, see the Hammer CLI help with `{foreman-maintain} packages --help`.
