:_mod-docs-content-type: PROCEDURE

[id="defining-lifecycle-environments"]
= Defining lifecycle environments

[role="_abstract"]
Lifecycle environments represent stages in your content promotion pipeline.
By adding lifecycle environments, you define the stages through which you will be promoting your content as you test it.

Every {Project} deployment starts with an initial *Library* lifecycle environment that holds all synchronized content.
In this example, you create a simple lifecycle path: From *Library* through *Development* to *Production*.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Lifecycle Environments*.
. Add an environment path:
.. Click *Create Environment Path* to start a new lifecycle environment path.
.. In the *Name* field, enter `Development`.
This is the lifecycle environment where development and testing of your content will happen.
.. Click *Save*.
. Extend the new environment path:
.. Click *Add New Environment* next to the *Development* environment.
.. In the *Name* field, enter `Production`.
.. Ensure that the *Prior Environment* dropdown list value is set to *Development*.
.. Click *Save*.

.Verification
* In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Lifecycle Environments*.
Review your new lifecycle environment path.

.Next steps
* Follow xref:publishing-and-promoting-a-content-view[] to create a content view so that you control which repositories are available in the new environments.

ifndef::containerized[]
.Additional resources
* xref:creating-a-lifecycle-environment-path-by-using-web-ui[]
endif::[]
