:_mod-docs-content-type: PROCEDURE

[id="running-the-{project-context}-installer_{context}"]
= Running the {Project} installer

The Foreman installer is a collection of Puppet modules that installs everything required for a full working Foreman setup.
It uses native operating system packaging (`.rpm` or `.deb` packages) and adds necessary configuration for the complete installation.

Components include the Foreman web UI, Smart Proxy, a Puppet server, TFTP, DNS and DHCP servers.
The installer is configurable and the Puppet modules can be read or run in "no-op" mode to see what changes it will make.

The installation run is non-interactive, but the configuration can be customized by supplying any of the options listed in `{foreman-installer} --help`, or by running `{foreman-installer} -i` for interactive mode.
More examples are described in the `Installation Options` section.
The `-v` option disables the progress bar and displays all changes.

.Procedure
* Run the {Project} installer:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {installer-scenario}
----

The script displays its progress and writes logs to `{installer-log-file}`.
