[id="Promoting_a_Content_View_{context}"]
= Promoting a Content View

Use this procedure to promote Content Views across different lifecycle environments.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-promoting-a-content-view_{context}[].

.Permission Requirements for Content View Promotion

Non-administrator users require two permissions to promote a Content View to an environment:

. `promote_or_remove_content_views`
. `promote_or_remove_content_views_to_environment`.

The `promote_or_remove_content_views` permission restricts which Content Views a user can promote.

The `promote_or_remove_content_views_to_environment` permission restricts the environments to which a user can promote Content Views.

With these permissions you can assign users permissions to promote certain Content Views to certain environments, but not to other environments.
For example, you can limit a user so that they are permitted to promote to test environments, but not to production environments.

You must assign both permissions to a user to allow them to promote Content Views.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Content Views* and select the Content View that you want to promote.
. Click the *Versions* tab for the Content View.
. Select the version that you want to promote and in the *Actions* column, click *Promote*.
. Select the environment where you want to promote the Content View, and click *Promote Version*.
. Click the *Promote* button again.
This time select the *Testing* environment and click *Promote Version*.
. Finally click on the *Promote* button again.
Select the *Production* environment and click *Promote Version*.

Now the repository for the Content View appears in all environments.

[id="cli-promoting-a-content-view_{context}"]
.CLI procedure
* Promote the Content View using the `hammer content-view version promote` each time:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view version promote \
--content-view "Database" \
--version 1 \
--to-lifecycle-environment "Development" \
--organization "_My_Organization_"
# hammer content-view version promote \
--content-view "Database" \
--version 1 \
--to-lifecycle-environment "Testing" \
--organization "_My_Organization_"
# hammer content-view version promote \
--content-view "Database" \
--version 1 \
--to-lifecycle-environment "Production" \
--organization "_My_Organization_"
----
+
Now the database content is available in all environments.

To register a host to your Content View, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[] in the _Managing Hosts_ guide.
