:_mod-docs-content-type: PROCEDURE

[id="creating-network-or-image-based-hosts-by-using-cli"]
= Creating hosts on {CRname} by using Hammer CLI

[role="_abstract"]
In {Project}, you can use {CRname} provisioning to create hosts over a network connection or from an existing image.

For more information about additional host creation parameters for this compute resource, enter the `hammer host create --help` command.

.Prerequisites
* For network-based provisioning, if you use a virtual network on the {CRname} server for provisioning, select a network that does not provide DHCP assignments.
* This causes DHCP conflicts with {ProjectServer} when booting new hosts.
* If you want to create a host over a network connection, the new host must be able to access your {ProjectServer} or {SmartProxyServers} on a {CRname} virtual network, so that the host has access to PXE provisioning services.
This new host entry triggers the {CRname} server to create and start a virtual machine.
If the virtual machine detects the defined {SmartProxyServer} through the virtual network, the virtual machine boots to PXE and begins to install the chosen operating system.

* If you want to create a host with an existing image, the new host entry triggers the {CRname} server to create the virtual machine using a pre-existing image as a basis for the new volume.

.Procedure

* Create a host by using one of the following methods:

** To use network-based provisioning, create the host with the `hammer host create` command and include `--provision-method build`.
Replace the values in the following example with the appropriate values for your environment.
ifeval::["{context}" == "kvm-provisioning"]
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host create \
--build true \
--compute-attributes="cpus=1,memory=1073741824" \
--compute-resource "_My_KVM_Server_" \
--enabled true \
--hostgroup "_My_Host_Group_" \
--interface "managed=true,primary=true,provision=true,compute_type=network,compute_network=_examplenetwork_" \
--location "_My_Location_" \
--managed true \
--name "_My_Host_Name_" \
--organization "_My_Organization_" \
--provision-method "build" \
--root-password "_My_Password_" \
--volume="pool_name=default,capacity=20G,format_type=qcow2"
----
endif::[]

** To use image-based provisioning, create the host with the `hammer host create` command and include `--provision-method image`.
Replace the values in the following example with the appropriate values for your environment.
ifeval::["{context}" == "kvm-provisioning"]
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host create \
--compute-attributes="cpus=1,memory=1073741824" \
--compute-resource "_My_KVM_Server_" \
--enabled true \
--hostgroup "_My_Host_Group_" \
--image "_My_KVM_Image_" \
--interface "managed=true,primary=true,provision=true,compute_type=network,compute_network=examplenetwork" \
--location "_My_Location_" \
--managed true \
--name "_My_Host_Name_" \
--organization "_My_Organization_" \
--provision-method "image" \
--volume="pool_name=default,capacity=20G,format_type=qcow2"
----
endif::[]
