[id="disabling-dns-dhcp-tftp-for-unmanaged-networks_{context}"]
= Disabling DNS, DHCP, and TFTP for Unmanaged Networks

If you want to manage TFTP, DHCP, and DNS services manually, you must prevent {Project} from maintaining these services on the operating system and disable orchestration to avoid DHCP and DNS validation errors.
However, {Project} does not remove the back-end services on the operating system.

.Procedure

. On {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-proxy-dhcp false \
--foreman-proxy-dns false \
--foreman-proxy-tftp false
----

. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*Subnets* and select a subnet.

. Click the *{SmartProxies}* tab and clear the *DHCP {SmartProxy}*, *TFTP {SmartProxy}*, and *Reverse DNS {SmartProxy}* fields.

. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*Domains* and select a domain.

. Clear the *DNS {SmartProxy}* field.

. Optional: If you use a DHCP service supplied by a third party, configure your DHCP server to pass the following options:
+
[options="nowrap" subs="+quotes,attributes"]
----
Option 66: __IP address of {Project} or {SmartProxy}__
Option 67: /pxelinux.0
----
+
For more information about DHCP options, see https://tools.ietf.org/html/rfc2132[RFC 2132].

[NOTE]
{Project} does not perform orchestration when a {SmartProxy} is not set for a given subnet and domain.
When enabling or disabling {SmartProxy} associations, orchestration commands for existing hosts can fail if the expected records and configuration files are not present.
When associating a {SmartProxy} to turn orchestration on, ensure the required DHCP and DNS records as well as the TFTP files are in place for the existing {Project} hosts in order to prevent host deletion failures in the future.
