[id="upgrading_a_connected_{project-context}_server_{context}"]
= Upgrading a connected {ProjectServer}

Use this procedure for a {ProjectServer} with access to the public internet

include::snip_warning-maintain-config-noop.adoc[]

.Upgrade {ProjectServer}

. Stop all {Project} services:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service stop
----
. Take a snapshot or create a backup:
* On a virtual machine, take a snapshot.
* On a physical machine, create a backup.
+
. Start all {Project} services:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service start
----

. Optional: If you made manual edits to DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, back up the configuration files because the installer only supports one domain or subnet, and therefore restoring changes from these backups might be required.

. Optional: If you made manual edits to DNS or DHCP configuration files and do not want to overwrite the changes, enter the following command:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} --foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false
----
. In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
On the Discovered Hosts page, power off and then delete the discovered hosts.
From the *Select an Organization* menu, select each organization in turn and repeat the process to power off and delete the discovered hosts.
Make a note to reboot these hosts when the upgrade is complete.
ifdef::satellite[]
. Upgrade {foreman-maintain} to its next version:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} self-upgrade
----

. Use the health check option to determine if the system is ready for upgrade.
When prompted, enter the hammer admin user credentials to configure `{foreman-maintain}` with hammer credentials.
These changes are applied to the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade check --target-version {ProjectVersion}
----
+
Review the results and address any highlighted error conditions before performing the upgrade.

. Optional: Because of the lengthy upgrade time, use a utility such as `tmux` to suspend and reattach a communication session.
You can then check the upgrade progress without staying connected to the command shell continuously.
+
If you lose connection to the command shell where the upgrade command is running, you can see the logged messages in the `{installer-log-file}` file to check if the process completed successfully.

. Perform the upgrade:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade run --target-version {ProjectVersion}
----
endif::[]
ifdef::katello[]
. Check for running tasks
+
[options="nowrap" subs="attributes"]
----
# foreman-rake katello:upgrade_check
----
endif::[]
ifdef::foreman-el,katello[]
. Update operating system packages:
+
[options="nowrap" subs="attributes"]
----
# {project-package-update}
----
. Update repositories
+
[options="nowrap" subs="attributes"]
----
ifdef::katello[]
# {project-package-update} https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm \
https://yum.theforeman.org/katello/{KatelloVersion}/katello/el8/x86_64/katello-repos-latest.rpm
endif::[]
ifdef::foreman-el[]
# {project-package-update} https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm
endif::[]
----
ifdef::katello[]
. Disable the pulpcore module if it is enabled:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf module disable pulpcore
----
endif::[]
. Switch to the PostgreSQL 13 module:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf -y module switch-to postgresql:13
----
. Ensure the module streams are enabled:
+
[options="nowrap" subs="attributes"]
----
# dnf module enable {dnf-module}
----
. Stop all services:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service stop
----
. Update the required packages:
+
[options="nowrap" subs="attributes"]
----
# {project-package-update}
----
+
. Run the installer:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer}
----
endif::[]
include::snip_steps-needs-reboot.adoc[]

include::snip_pulp-container-manifests-note.adoc[]
