:_mod-docs-content-type: PROCEDURE

[id="adding-errata-to-an-incremental-content-view-by-using-cli"]
= Adding errata to an incremental content view by using Hammer CLI

[role="_abstract"]
If errata are available but not installable, you can create an incremental content view version by using Hammer CLI to add the errata to your hosts.
For example, if the content view is version 1.0, it becomes content view version 1.1, and when you publish, it becomes content view version 2.0.

[IMPORTANT]
====
If your content view version is old, you might encounter incompatibilities when incrementally adding enhancement errata.
This is because enhancements are typically designed for the most current software in a repository.
====

.Procedure
. List the errata and its corresponding IDs:
+
[options="nowrap" subs="+quotes"]
----
$ hammer erratum list
----
. List the different content-view versions and the corresponding IDs:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view version list
----
. Apply a single erratum to content-view version.
You can add more IDs in a comma-separated list.
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view version incremental-update \
--content-view-version-id _My_Content_View_Version_ID_ \
--errata-ids _My_Erratum_ID_1_,_My_Erratum_ID_2_
----
