[id="Preparing_SUSE_Installation_Media_{context}"]
= Preparing SUSE Installation Media

Use this procedure to extract the SUSE installation medium on your {ProjectServer} to provision hosts in a disconnected environment.
This example prepares the installation medium for SUSE Linux Enterprise Server 15 SP3.

.Procedure
. Download the `SLES 15 SP3` installation medium from https://www.suse.com/download/sles/[suse.com/download/sles].
. Download the signature and checksum from https://www.suse.com/support/security/download-verification/[suse.com].
. Transfer the `.iso` image, the signature, and the checksum from your local machine to {ProjectServer} using `scp`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp SLE-15-SP3-Full-x86_64-GM-Media1.iso root@{foreman-example-com}:/tmp/
# scp SLE-15-SP3-Full-x86_64-GM-Media1.iso.sha256 root@{foreman-example-com}:/tmp/
# scp sles_15_sp3.signature root@{foreman-example-com}:/tmp/
----
. On your {ProjectServer}, verify the integrity and authenticity of the `.iso` image using GPG public keys:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cd /tmp
# gpg --verify sles_15_sp3.signature SLE-15-SP3-Full-x86_64-GM-Media1.iso.sha256
# echo '2a6259fc849fef6ce6701b8505f64f89de0d2882857def1c9e4379d26e74fa56 SLE-15-SP3-Full-x86_64-GM-Media1.iso' | sha256sum --check
----
. Mount the `.iso` image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mount SLE-15-SP3-Full-x86_64-GM-Media1.iso /mnt
----
. Copy the content of the mounted installation medium to the `pub` directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /var/www/html/pub/installation_media/sles/15sp3
# cp -a /mnt/* /var/www/html/pub/installation_media/sles/15sp3/
----
. Unmount and delete the `.iso` image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cd
# umount /mnt
# rm -f /tmp/SLE-15-SP3-Full-x86_64-GM-Media1.iso
# rm -f /tmp/SLE-15-SP3-Full-x86_64-GM-Media1.iso.sha256
# rm -f /tmp/sles_15_sp3.signature
----

You can use the path to the local installation media files when creating an installation medium, for example `\http://{foreman-example-com}/pub/installation_media/sles/15sp3/`.
For more information, see {ProvisioningDocURL}adding-installation-media_provisioning[Adding Installation Media to {Project}] in _{ProvisioningDocTitle}_.
