:_mod-docs-content-type: PROCEDURE

[id="deploying-a-virt-who-configuration-on-target-server_{context}"]
= Deploying a virt-who configuration on {a-target}

[role="_abstract"]
You deploy a virt-who configuration on {a-target} to enable virtual machine subscription tracking.
You download a virt-who configuration script from the {ProjectWebUI} and then you run the script on {the-target}.

Global configuration values apply to all virt-who configurations on this server and are overwritten if you deploy a new virt-who configuration.

.Prerequisites
* You have registered the VM running on {KubeVirt} to {ProjectServer}.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Virt-who Configurations*.
. Click a virt-who configuration.
. Click the *Deploy* tab.
. Under *Configuration script*, click *Download the script*.
. Copy the script from {ProjectServer} to {the-target}:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
$ scp _deploy_virt_who_config_1_.sh root@_{target-name}_:
----
. Log in to {the-target} and make the script executable:
+
[options="nowrap" subs="+quotes"]
----
$ chmod +x _deploy_virt_who_config_1_.sh
----
. Run the script:
+
[options="nowrap" subs="+quotes"]
----
$ sh _deploy_virt_who_config_1_.sh
----
. After the deployment is complete, delete the script:
+
[options="nowrap" subs="+quotes"]
----
$ rm _deploy_virt_who_config_1_.sh
----
