[id="{context}_adding_an_ansible_playbook"]
= Adding an Ansible Playbook

You can add xref:{context}_ansible_playbooks[Ansible playbooks] used for application centric deployment via your {ProjectServer} management UI.

.Procedure
. In the {ProjectWebUI}, navigate to *Applications > Ansible Playbooks*.
. Click *New Ansible Playbook*.
. In the *Name* field, enter the name of new Ansible playbook.
. In the *Description* field, enter an arbitrary description.
. In the *SCM Type* list, select either _directory_ if the Ansible playbook is located on your {ProjectServer} or _git_ to reference a remote git repository.
* If you select *directory*, enter the location of the Ansible playbook on your {ProjectServer} in the *Directory Path* field.
+
To avoid SELinux issues, add the Ansible playbook to the `/var/lib/foreman/foreman_acd/ansible-playbooks/` directory.
* If you select *git*, enter the remote location in the *Git Url* field and a git branch, commit, or tag in the *Git Branch/Commit/Tag* field.
+
Click *Sync Repository* to fetch the remote git repository.
. In the *Playfile* field, enter the name of the Ansible playbook.
. Click *Submit* to save your Ansible playbook.
. Once submitted, click the *Import groups* button to import Ansible group variables before this Ansible playbook can be used for an application definition.

[NOTE]
====
You can only edit the directory path or git URL as long as it is not used by any application definition.
====

[TIP]
====
Making changes to any Ansible roles included in your Ansible playbook does not require reimporting the Ansible playbook via management UI.
====
