:_mod-docs-content-type: PROCEDURE

[id="booting-virtual-machines"]
= Booting virtual machines

[role="_abstract"]
Some virtualization hypervisors use iPXE as primary firmware for PXE booting.
If you use such a hypervisor, you can boot virtual machines without TFTP and PXELinux.

.Prerequisites
* Your hypervisor must support iPXE.
The following virtualization hypervisors support iPXE:

** libvirt
ifndef::satellite[]
** VMWare (https://ipxe.org/howto/vmware[via custom firmware])
endif::[]
* You have configured your iPXE environment.
For more information, see xref:configuring-ipxe-environment[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Templates* > *Provisioning Templates*.
ifdef::foreman-el,foreman-deb,katello[]
. Search for the required template:
* For Debian hosts, select the `Preseed default iPXE` template.
* For {EL} hosts, select the `Kickstart default iPXE` template.
* For {SLES} hosts, select the `Agama default iPXE` template for SLES 16 or `AutoYaST default iPXE` for SLES 15 and SLES 12.
* For Ubuntu hosts, select the `Preseed default iPXE Autoinstall` template.
endif::[]
ifdef::orcharhino,satellite[]
. Search for the `{client-provisioning-template-default-ipxe}` template.
ifdef::ubuntu[]
+
For {client-os} 18.04 hosts, select the `Preseed default iPXE` template.
endif::[]
ifdef::suse_linux_enterprise_server[]
+
For {client-os} 15 and 12 hosts, select the `AutoYaST default iPXE` template.
endif::[]
endif::[]
. Click the name of the template.
. Click the *Association* tab and select the operating systems that your host uses.
. Click the *Locations* tab and add the location where the host resides.
. Click the *Organizations* tab and add the organization that the host belongs to.
. Click *Submit* to save the changes.
. In the {ProjectWebUI}, navigate to *Hosts* > *Operating systems* and select the operating system of your host.
. Click the *Templates* tab.
ifdef::foreman-el,foreman-deb,katello[]
. From the *iPXE template* list, select the required template:
* For Debian hosts, select the `Preseed default iPXE` template.
* For {EL} hosts, select the `Kickstart default iPXE` template.
* For {SLES} hosts, select the `Agama default iPXE` template for SLES 16 or `AutoYaST default iPXE` for SLES 15 and SLES 12.
* For Ubuntu hosts, select the `Preseed default iPXE Autoinstall` template.
endif::[]
ifdef::orcharhino,satellite[]
. From the *iPXE template* list, select the `{client-provisioning-template-default-ipxe}` template.
ifdef::ubuntu[]
+
For {client-os} 18.04 hosts, select the `Preseed default iPXE` template.
endif::[]
ifdef::suse_linux_enterprise_server[]
+
For {client-os} 15 and 12 hosts, select the `AutoYaST default iPXE` template.
endif::[]
endif::[]
. Click *Submit* to save the changes.
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. In the *Hosts* page, select the host that you want to use.
. Select the *Operating System* tab.
. Set *PXE Loader* to `iPXE Embedded`.
. Select the *Templates* tab.
. In *Provisioning Templates*, click *Resolve* and verify that the *iPXE template* resolves to the required template.
. Click *Submit* to save host settings.

.Additional resources
* xref:running-custom-code-during-host-provisioning-by-using-web-ui[]
