[id="Adding_a_Virtual_Interface_{context}"]
= Adding a Virtual Interface

Use this procedure to configure a virtual interface for a host.
This can be either a VLAN or an alias interface.

An alias interface is an additional IP address attached to an existing interface.
An alias interface automatically inherits a MAC address from the interface it is attached to; therefore, you can create an alias without specifying a MAC address.
The interface must be specified in a subnet with boot mode set to `static`.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All hosts*.
. Click *Edit* next to the host you want to edit.
. On the *Interfaces* tab, click *Add Interface*.
. Keep the *Interface* option selected in the *Type* list.
. Specify the general interface settings.
The applicable configuration options are the same as for the physical interfaces described in xref:Adding_a_Physical_Interface_{context}[].
+
Specify a *MAC address* for managed virtual interfaces so that the configuration files for provisioning are generated correctly.
However, a *MAC address* is not required for virtual interfaces that are not managed.
+
If creating a VLAN, specify ID in the form of *eth1.10* in the *Device Identifier* field.
If creating an alias, use ID in the form of *eth1:10*.
. Select the *Virtual NIC* checkbox.
Additional configuration options specific to virtual interfaces are appended to the form:
+
* *Tag*: Optionally set a VLAN tag to trunk a network segment from the physical network through to the virtual interface.
If you do not specify a tag, managed interfaces inherit the VLAN tag of the associated subnet.
User-specified entries from this field are not applied to alias interfaces.

* *Attached to*: Specify the identifier of the physical interface to which the virtual interface belongs, for example *eth1*.
This setting is required.

. Click *OK* to save the interface configuration.
. Click *Submit* to apply the changes to the host.
