[id="preparing-discovery-image-for-pxe-boot_{context}"]
= Preparing Discovery image for PXE boot

If you want to boot the Discovery images over a network, prepare the Discovery operating system images for PXE boot.

.Prerequisites
* You have installed the Foreman Discovery image or built a custom Discovery image ISO.
For more information, see one of the following resources:
** xref:Installing_the_Discovery_Service_{context}[]
** xref:Building_a_Discovery_Image_{context}[]

.Procedure
ifdef::satellite[]
. Extract the initial RAM disk and kernel files from the `.iso` file:
+
[options="nowrap" subs="+quotes"]
----
# discovery-iso-to-pxe fdi.iso
----
endif::[]
. Create a directory to store your boot files:
+
[options="nowrap" subs="+quotes"]
----
# mkdir /var/lib/tftpboot/boot/_My_Image_
----
ifndef::satellite[]
. Copy the `./tftpboot/initrd0.img` and `./tftpboot/vmlinuz0` files to your new directory.
endif::[]
ifdef::satellite[]
. Copy the `initrd0.img` and `vmlinuz0` files to your new directory.
endif::[]
. Edit the `KERNEL` and `APPEND` entries in the `/var/lib/tftpboot/pxelinux.cfg` file to add the information about your own initial ramdisk and kernel files.
