[id="setting-up-pull-client_{context}"]
= Setting Up the Remote Execution Pull Client

For {SmartProxies} in `pull-mqtt` mode, hosts can subscribe to remote jobs using the remote execution pull client.
No SSH connection is required.

Use this procedure to configure a host to use the pull client:

.Prerequisites
* The host is registered to {ProjectName}.
* The host's {SmartProxy} is in `pull-mqtt` mode.
* The {Team} {project-client-name} repository is enabled and synchronized on {ProjectServer}, and enabled on the host.
* The host is able to communicate with its {SmartProxy} over MQTT using port 1883.
* The host is able to communicate with its {SmartProxy} over HTTPS.

.Procedure
. On the host, install the `katello-pull-transport-migrate` RPM package:
+
----
# yum install katello-pull-transport-migrate
----
The host's `subscription-manager` configuration and consumer certificates are used to configure the `yggdrasil` client on the host, and the worker is started.


.Verification
. To verify that the host is configured to use the pull client, run the following command:
+
----
# systemctl status yggdrasild
----

NOTE: The `katello-pull-transport-migrate` package was created to help users migrate from `katello-agent` to remote execution with the pull client.
However, having `katello-agent` installed on the host is not a requirement.
You can use `katello-pull-transport-migrate` regardless of whether `katello-agent` is installed.