[id="Changing_the_HTTP_Proxy_Policy_for_a_Product_{context}"]
= Changing the HTTP Proxy Policy for a Product

For granular control over network traffic, you can set an HTTP proxy policy for each Product.
A Product's HTTP proxy policy applies to all repositories in the Product, unless you set a different policy for individual repositories.

To set an HTTP proxy policy for individual repositories, see xref:Changing_the_HTTP_Proxy_Policy_for_a_Repository_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products* and click the check box next to each of the Products that you want to change.
. From the *Select Action* list, click *Manage HTTP Proxy*.
. Select an *HTTP Proxy Policy* from the list:
* *Global Default*: Use the global default proxy setting.
* *No HTTP Proxy*: Do not use an HTTP proxy, even if a global default proxy is configured.
* *Use specific HTTP Proxy*: Select an *HTTP Proxy* from the list.
You must add HTTP proxies to {Project} before you can select a proxy from this list.
For more information, see xref:Adding_an_HTTP_Proxy_{context}[].
. Click *Update*.
