[id="Registering_Hosts_{context}"]
= Registering Hosts

Hosts can be registered to {Project} by generating a `curl` command on {Project} and running this command on hosts.
This method uses two templates: `global registration` template and `host initial configuration` template.
That gives you complete control over the host registration process.
You can set default templates by navigating to *Administer > Settings*, and clicking the *Provisioning* tab.

ifndef::satellite,orcharhino[]
Note that you can extend the parameters by plug-ins.
For more information, see https://github.com/theforeman/foreman/blob/develop/developer_docs/how_to_create_a_plugin.asciidoc[How to Create a Plugin] and https://theforeman.github.io/foreman/?path=/docs/introduction-slot-and-fill--page[Slot and Fill]
endif::[]

.Prerequisites
* The {Project} user that generates the `curl` command must have the `create_hosts` permission.
* You must have root privileges on the host that you want to register.
ifdef::satellite,orcharhino[]
* You must have an activation key created.
* Optional: If you want to register hosts to Red{nbsp}Hat Insights, you must synchronize the `{RepoRHEL7Server}` repository and make it available in the activation key that you use.
This is required to install the `insights-client` package on hosts.
* {ProjectServer}, any {SmartProxyServer}s, and all hosts must be synchronized with the same NTP server, and have a time synchronization tool enabled and running.
* The daemon *rhsmcertd* must be running on the hosts.
* An activation key must be available for the host.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in the _Content Management Guide_.
* Subscription Manager must be version 1.10 or later.
The package is available in the standard {RHEL} repository.
endif::[]
* Optional: If you want to register hosts through {SmartProxy}, ensure that the *Registration* and *Templates* features are enabled on this {SmartProxy}.
+
In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*, click the {SmartProxy} that you want to use, and locate the *Registration* feature in the *Active features* list.
+
Optional: If the *Registration* feature is not enabled on your {SmartProxy}, enter the following command on the {SmartProxy} to enable it (use a FQDN, not an IP address):
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-proxy-registration \
--foreman-proxy-templates \
--foreman-proxy-template-url 'http://{smartproxy-example-com}'
----

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Register Host*.
. Optional: Select a different *Organization*.
. Optional: Select a different *Location*.
. Optional: From the *Host Group* list, select the host group to associate the hosts with.
Fields that inherit value from *Host group*: *Operating system*, *Activation Keys* and *Lifecycle environment*.
. Optional: From the *Operating system* list, select the operating system of hosts that you want to register.
ifndef::satellite[]
Specifying an operating system is required when you register machines without `subscription-manager`, such as Debian or Ubuntu.
endif::[]
. Optional: From the *{SmartProxy}* list, select the {SmartProxy} to register hosts through.
. Optional: Select the *Insecure* option, if you want to make the first call insecure.
During this first call, hosts download the CA file from {Project}.
Hosts will use this CA file to connect to {Project} with all future calls making them secure.
+
{Team} recommends that you avoid insecure calls.
+
If an attacker, located in the network between {Project} and a host, fetches the CA file from the first insecure call, the attacker will be able to access the content of the API calls to and from the registered host and the JSON Web Tokens (JWT).
Therefore, if you have chosen to deploy SSH keys during registration, the attacker will be able to access the host using the SSH key.
+
Instead, you can manually copy and install the CA file on each host before registering the host.
+
To do this, find where {Project} stores the CA file by navigating to *Administer* > *Settings* > *Authentication* and locating the value of the *SSL CA file* setting.
+
Copy the CA file to the `/etc/pki/ca-trust/source/anchors/` directory on hosts and enter the following commands:
+
[options="nowrap", subs="+quotes,attributes"]
----
# update-ca-trust enable
# update-ca-trust
----
+
Then register the hosts with a secure `curl` command, such as:
+
[options="nowrap", subs="+quotes,attributes"]
----
# curl -sS https://{foreman-example-com}/register ...
----
+
The following is an example of the `curl` command with the `--insecure` option:
+
[options="nowrap", subs="+quotes,attributes"]
----
# curl -sS --insecure https://{foreman-example-com}/register ...
----
. Select the *Advanced* tab.
. From the *Setup REX* list, select whether you want to deploy {Project} SSH keys to hosts or not.
+
If set to `Yes`, public SSH keys will be installed on the registered host.
The inherited value is based on the `host_registration_remote_execution` parameter.
It can be inherited, for example from a host group, an operating system, or an organization.
When overridden, the selected value will be stored on host parameter level.
. From the *Setup Insights* list, select whether you want to install `insights-client` and register the hosts to Insights.
+
The Insights tool is available for {RHEL} only.
It has no effect on other operating systems.
+
You must enable the following repositories on a registered machine:

* RHEL 6: `rhel-6-server-rpms`
* RHEL 7: `rhel-7-server-rpms`
* RHEL 8: `rhel-8-for-x86_64-appstream-rpms`
+
The `insights-client` package is installed by default on RHEL 8 except in environments whereby RHEL 8 was deployed with "Minimal Install" option.
. Optional: In the *Install packages* field, list the packages (separated with spaces) that you want to install on the host upon registration.
This can be set by the `host_packages` parameter.
. Optional: Select the *Update packages* option to update all packages on the host upon registration.
This can be set by the `host_update_packages` parameter.
. Optional: In the *Repository* field, enter a repository to be added before the registration is performed.
For example, it can be useful to make the `subscription-manager` package available for the purpose of the registration.
For Red Hat family distributions, enter the URL of the repository, for example `\http://rpm.example.com/`.
ifndef::satellite[]
For Debian OS families, enter the whole line of list file content, for example `deb \http://deb.example.com/ buster 1.0`.
endif::[]
. Optional: In the *Repository GPG key URL* field, specify the public key to verify the signatures of GPG-signed packages.
It needs to be specified in the ASCII form with the GPG public key header.
. Optional: In the *Token lifetime (hours)* field, change the validity duration of the JSON Web Token (JWT) that {Project} uses for authentication.
The duration of this token defines how long the generated `curl` command works.
You can set the duration to 0 - 999 999 hours or unlimited.
+
Note that {Project} applies the permissions of the user who generates the `curl` command to authorization of hosts.
If the user loses or gains additional permissions, the permissions of the JWT change too.
Therefore, do not delete, block, or change permissions of the user during the token duration.
+
The scope of the JWTs is limited to the registration endpoints only and cannot be used anywhere else.
. Optional: In the *Remote Execution Interface* field, enter the identifier of a network interface that hosts must use for the SSH connection.
If you keep this field blank, {Project} uses the default network interface.

ifdef::satellite,orcharhino[]
. In the *Activation Keys* field, enter one or more activation keys to assign to hosts.
. Optional: Select the *Lifecycle environment*.
. Optional: Select the *Ignore errors* option if you want to ignore subscription manager errors.
. Optional: Select the *Force* option if you want to remove any `katello-ca-consumer` rpms before registration and run `subscription-manager` with the `--force` argument.
endif::[]

ifdef::foreman-el,foreman-deb,katello[]
. Optional: This step is for the Katello users only.
If you register RHEL or CentOS hosts, in the *Activation Keys* field, enter one or more activation keys to assign to registered hosts.
endif::[]

. Click the *Generate* button.
. Copy the generated `curl` command.
. On the hosts that you want to register, run the `curl` command as `root`.

ifdef::katello,satellite,orcharhino[]
[NOTE]
====
For {RHEL} 6.3 hosts, the release version defaults to {RHEL} 6 Server and needs to be pointed to the 6.3 repository:

. In the {ProjectWebUI}, navigate to *Hosts* > *Content Hosts*.
. Select the check box next to the host that needs to be changed.
. From the *Select Action* list, select *Set Release Version*.
. From the *Release Version* list, select *6.3*.
. Click *Done*.
====
endif::[]
