:_mod-docs-content-type: PROCEDURE

[id="creating-a-custom-alternate-content-source-by-using-web-ui"]
= Creating a custom alternate content source by using {ProjectWebUI}

[role="_abstract"]
You can create a custom alternate content source (ACS) to accelerate content synchronization by downloading from your local network or filesystem instead of remote upstream servers.

.Prerequisites
* If the repository requires SSL authentication, the SSL certificate and key must be imported into {Project}.
For more information, see {ContentManagementDocURL}importing-custom-ssl-certificates-by-using-web-ui[Importing custom SSL certificates by using {ProjectWebUI}] in _{ContentManagementDocTitle}_.
ifdef::katello,satellite,almalinux,amazon_linux,centos,oracle_linux,red_hat_enterprise_linux,rocky_linux,suse_linux_enterprise_server[]
* You have the base URL and subpaths of your alternate content source.
For example, if your base URL is `\https://{server-example-com}` and your subpaths are `{client-os-context}-{client-os-major}/` and `{client-os-context}-{client-os-major-previous}/`, then {Project} will search `\https://{server-example-com}/{client-os-context}-{client-os-major}/` and `\https://{server-example-com}/{client-os-context}-{client-os-major-previous}/`.
endif::[]
ifdef::debian,ubuntu[]
* You have the base URL and architectures, components, and releases of the Deb repository.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Alternate Content Sources*.
. Click *Add source*.
. Set the *Source type* to *Custom*.
. Select the *Content type* from the drop-down list.
. In the *Name* field, enter a name for your custom ACS.
. Optional: In the *Description* field, provide a description for the ACS.
. Select {SmartProxies} to which you want to synchronize content from your alternate content source.
. If you require synchronizing content through the HTTP proxy of your {SmartProxies}, select *Use HTTP proxies*.
. In the *Base URL* field, enter the base URL of the alternate content source.
ifdef::katello,satellite,almalinux,amazon_linux,centos,oracle_linux,red_hat_enterprise_linux,rocky_linux,suse_linux_enterprise_server[]
. In the *Subpaths* field, provide a comma-separated list of subpaths.
endif::[]
ifdef::debian,ubuntu[]
. In the *Distributions* field, provide a whitespace-separated list of distributions.
. Optional: In the *Components* field, provide a whitespace-separated list of components.
. Optional: In the *Architectures* field, provide a whitespace-separated list of architectures.
endif::[]
. If your alternate content source requires authentication, select the *Manual authentication* or *Content credentials*.
. If SSL verification is required, enable *Verify SSL* and select the SSL CA certificate.
. Click *Add*.
. Navigate to *Content* > *Alternate Content Sources*.
. Open the options menu next to the newly created alternate content source and click *Refresh*.

.Verification
. In the {ProjectWebUI}, navigate to *Monitor* > *{Project} Tasks* > *Tasks*.
. Search for `Refresh Alternate Content Source`.
. Verify that the task finished successfully.
