:_mod-docs-content-type: PROCEDURE

[id="publishing-and-promoting-a-content-view"]
= Publishing and promoting a content view

[role="_abstract"]
A content view is a curated snapshot of your repositories.
When you publish a content view, {Project} takes a point-in-time copy of the selected repositories, which you promote through your lifecycle environment path.

In this example, you create a content view, publish the first version, and promote it to the *Development* environment.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Content Views*.
. Create a content view:
.. Click *Create content view*.
.. In the *Name* field, enter a name.
For example: `My Content View`.
.. Ensure *Content view* is selected as the type.
.. Click *Create content view*.
. Define the properties of the new content view:
.. On the *Repositories* tab, select your preferred repository type from the *Type* list.
.. Click *Show repositories*, an select the repositories you want to include.
.. Click *Add repositories*.
. Publish a new version of the content view with the selected repositories:
.. Click *Publish new version*.
.. Optional: In the *Description* field, enter `Initial version`.
.. Toggle *Promote*, and select the *Development* lifecycle environment.
.. Click *Next*, and review the details.
.. Click *Finish*, and wait for the publishing task to complete.

.Verification
* In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Lifecycle Environments*.
Click the *Development* lifecycle environment.
On the *Content Views* tab, you can see that *My Content View* is listed.
* Navigate to *Content* > *Lifecycle* > *Content Views*.
Click the *My Content View* content view.
On the *Versions* tab, you can see the version of the content view that is published and the environments associated with *My Content View*.
Hosts registered to these environments with this content view will receive exactly the packages from this snapshot.

.Next steps
* Follow xref:creating-an-activation-key[] to you create an activation key that maps new hosts to this content view and lifecycle environment.

.Additional resources
* xref:creating-a-content-view-by-using-web-ui[]
