[id="creating-provisioning-templates_{context}"]
= Creating Provisioning Templates

A provisioning template defines the way {ProjectServer} installs an operating system on a host. Use this procedure to create a new provisioning template.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *Provisioning Templates* and click *Create Template*.
. In the *Name* field, enter a name for the provisioning template.
. Fill in the rest of the fields as required. The *Help* tab provides information about the template syntax and details the available functions, variables, and methods that can be called on different types of objects within the template.

.For CLI Users

. Before you create a template with the CLI, create a plain text file that contains the template. This example uses the `~/my-template` file.
. Create the template using the `hammer template create` command and specify the type with the `--type` option:
+
[options="nowrap" subs="+quotes"]
----
# hammer template create --name "My Provisioning Template" \
--file ~/my-template --type provision --organizations "_My_Organization_" \
--locations "_My_Location_"
----
