[id="creating-partition-tables_{context}"]
= Creating Partition Tables

A partition table is a type of template that defines the way {ProjectServer} configures the disks available on a new host.
A Partition table uses the same ERB syntax as provisioning templates.
{ProjectName} contains a set of default partition tables to use, including a `Kickstart default`.
You can also edit partition table entries to configure the preferred partitioning scheme, or create a partition table entry and add it to the operating system entry.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-partition-tables_{context}[].

.Procedure

. In the {ProjectWebUI}, navigate to *Hosts* > *Partition Tables* and click *Create Partition Table*.
. In the *Name* field, enter a name for the partition table.
. Select the *Default* checkbox if you want to set the template to automatically associate with new organizations or locations.
. Select the *Snippet* checkbox if you want to identify the template as a reusable snippet for other partition tables.
. From the *Operating System Family* list, select the distribution or family of the partitioning layout.
For example, {RHEL}, CentOS, and Fedora are in the Red Hat family.
. In the *Template editor* field, enter the layout for the disk partition.
+
include::snip_ptable-format.adoc[]
+
You can also use the file browser in the template editor to import the layout from a file.
. In the *Audit Comment* field, add a summary of changes to the partition layout.
. Click the *Organizations* and *Locations* tabs to add any other provisioning contexts that you want to associate with the partition table.
{Project} adds the partition table to the current provisioning context.
. Click *Submit* to save your partition table.

[id="cli-creating-partition-tables_{context}"]
.CLI procedure
. Create a plain text file, such as `_~/My_Partition_Table_`, that contains the partition layout.
+
include::snip_ptable-format.adoc[]
. Create the installation medium using the `hammer partition-table create` command:
+
[options="nowrap" subs="+quotes"]
----
# hammer partition-table create \
--file "_~/My_Partition_Table_" \
--locations "_My_Location_" \
--name "My Partition Table" \
--organizations "_My_Organization_" \
--os-family "My_OS_Family" \
--snippet false
----
