[id="adding-gce-details-to-a-compute-profile_{context}"]
= Adding Google Compute Engine Details to a Compute Profile

Use this procedure to add GCE hardware settings to a compute profile. When you create a host on GCE using this compute profile, these settings are automatically populated.

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Profiles*.
. In the Compute Profiles window, click the name of an existing compute profile, or click *Create Compute Profile*, enter a *Name*, and click *Submit*.
. Click the name of the GCE compute resource.
. From the *Machine Type* list, select the machine type to use for provisioning.
. From the *Image* list, select the image to use for provisioning.
. From the *Network* list, select the GCE network to use for provisioning.
. Optional: Select the *Associate Ephemeral External IP* check box to assign a dynamic ephemeral IP address that {Project} uses to communicate with the host. This public IP address changes when you reboot the host. If you need a permanent IP address, reserve a static public IP address on GCE and attach it to the host.
. In the *Size (GB)* field, enter the size of the storage to create on the host.
. Click *Submit* to save the compute profile.

.For CLI Users

. Create a compute profile to use with the GCE compute resource:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile create --name _gce_profile_
----

. Add GCE details to the compute profile.
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile values create --compute-profile _gce_profile_ \
--compute-resource '_gce_cr_' \
--volume "_size_gb=20_" \
--compute-attributes "machine_type=f1-micro,associate_external_ip=true,network=default"
----
