[id="synchronizing-the-project-client-name-repository-rhel-9-and-rhel-8"]
= Synchronizing the {project-client-name} repository for {RHEL} 9 and {RHEL} 8

To use the CLI instead of the {ProjectWebUI}, see the procedure relevant for your {RHEL} version:

* xref:CLI_Synchronizing_the_Client_Repository_rhel_9_{context}[]
* xref:CLI_Synchronizing_the_Client_Repository_rhel_8_{context}[]

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
. Click the arrow next to the *{RHEL} for x86_64* Product to view available content.
. Select *{Team} {project-client-name} for RHEL 9 x86_64 RPMs* or *{Team} {project-client-name} for RHEL 8 x86_64 RPMs*.
. Click *Synchronize Now*.

[id="CLI_Synchronizing_the_Client_Repository_rhel_9_{context}"]
.CLI procedure for {RHEL} 9
* Synchronize your {project-client-name} repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--name "{Team} {project-client-name} for RHEL 9 x86_64 RPMs" \
--organization "_My_Organization_" \
--product "{RHEL} for x86_64"
----

[id="CLI_Synchronizing_the_Client_Repository_rhel_8_{context}"]
.CLI procedure for {RHEL} 8
* Synchronize your {project-client-name} repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--name "{Team} {project-client-name} for RHEL 8 x86_64 RPMs" \
--organization "_My_Organization_" \
--product "{RHEL} for x86_64"
----

.Additional resources
* For details about the `hammer repository synchronize` command, enter `hammer repository synchronize --help`.
