[id="Adding_Life_Cycle_Environments_{context}"]
= Adding Life Cycle Environments to {SmartProxyServer}s

If your {SmartProxyServer} has the content functionality enabled, you must add an environment so that {SmartProxy} can synchronize content from {ProjectServer} and provide content to host systems.

Do not assign the _Library_ lifecycle environment to your {SmartProxyServer} because it triggers an automated {SmartProxy} sync every time the CDN updates a repository.
This might consume multiple system resources on {SmartProxies}, network bandwidth between {Project} and {SmartProxies}, and available disk space on {SmartProxies}.

You can use Hammer CLI on {ProjectServer} or the {ProjectWebUI}.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*{SmartProxies}*, and select the {SmartProxy} that you want to add a life cycle to.
. Click *Edit* and click the *Life Cycle Environments* tab.
. From the left menu, select the life cycle environments that you want to add to {SmartProxy} and click *Submit*.
. To synchronize the content on the {SmartProxy}, click the *Overview* tab and click *Synchronize*.
. Select either *Optimized Sync* or *Complete Sync*.
+
For definitions of each synchronization type, see {ContentManagementDocURL}Recovering_a_Corrupted_Repository_content-management[Recovering a Repository].

.CLI procedure
. To display a list of all {SmartProxyServer}s, on {ProjectServer}, enter the following command:
+
[options="nowrap"]
----
# hammer capsule list
----
+
Note the {SmartProxy} ID of the {SmartProxy} that you want to add a life cycle to.
. Using the ID, verify the details of your {SmartProxy}:
+
[options="nowrap" subs="+quotes"]
----
# hammer capsule info --id _capsule_id_
----
. To view the life cycle environments available for your {SmartProxyServer}, enter the following command and note the ID and the organization name:
+
[options="nowrap" subs="+quotes"]
----
# hammer capsule content available-lifecycle-environments --id _capsule_id_
----
. Add the life cycle environment to your {SmartProxyServer}:
+
[options="nowrap" subs="+quotes"]
----
# hammer capsule content add-lifecycle-environment \
--id _capsule_id_ --organization "_My_Organization_" \
--lifecycle-environment-id _lifecycle-environment_id_
----
+
Repeat for each life cycle environment you want to add to {SmartProxyServer}.
. Synchronize the content from {Project} to {SmartProxy}.
+
* To synchronize all content from your {ProjectServer} environment to {SmartProxyServer}, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# hammer capsule content synchronize --id _capsule_id_
----
+
* To synchronize a specific life cycle environment from your {ProjectServer} to {SmartProxyServer}, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# hammer capsule content synchronize --id _external_capsule_id_ \
--lifecycle-environment-id _lifecycle-environment_id_
----
