:_mod-docs-content-type: PROCEDURE

[id="installing-flatpak-applications-on-{project-context}-hosts"]
= Installing Flatpak applications on {Project} hosts

Use the command line to install selected applications from the enabled Flatpak remotes.

.Prerequisites
* Flatpak is installed on the host.
ifdef::satellite[]
* The {Team} Flatpak remote is enabled.
endif::[]
* Ensure that Podman is installed on the host.
* To install Flatpak applications from {Project}, ensure that your {Project} account has the `view_lifecycle_environments`, `view_products`, and `view_content_views` permissions, unless the lifecycle environment allows unauthenticated pull.
* Your {Project} account has a role that grants the `create_personal_access_tokens` permission to generate an access token for authentication.
The token generates automatically when you run `podman login`.

.Procedure
. On the managed host, add your {ProjectServer} as a Flatpak remote:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ flatpak remote-add --authenticator-name=org.flatpak.Authenticator.Oci katello oci+https://_{foreman-example-com}_/
----
. Configure the host to use container certificates for authentication.  
Authentication with certificates allows {Project} or {SmartProxy} to restrict the access of the host to container and Flatpak repositories based on the assigned content view and lifecycle environment.

* When registering a host to {Project} or {SmartProxy}, select the *Set up container registry certs* checkbox.
* Run the *Flatpak - Login to registry via podman* job template on the host.
* Set the *Set up certificate authentication* input to `true` and enter the FQDN of the {Project} or {SmartProxy} server as the registry URL.

. Alternatively, you can log in using Podman:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ podman login _{foreman-example-com}_
----
+
. Install your application.
For example, to install the Mozilla Firefox Flatpak:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ flatpak install firefox
----

.Additional resources
* For more information about launching Flatpak applications, see {RHELDocsBaseURL}9/html/administering_the_system_using_the_gnome_desktop_environment/assembly_installing-applications-using-flatpak_administering-the-system-using-the-gnome-desktop-environment#launching-flatpak-applications_assembly_installing-applications-using-flatpak[Launching Flatpak applications].
* For more information about updating Flatpak applications, see {RHELDocsBaseURL}9/html/administering_the_system_using_the_gnome_desktop_environment/assembly_installing-applications-using-flatpak_administering-the-system-using-the-gnome-desktop-environment#updating-flatpak-applications_assembly_installing-applications-using-flatpak[Updating Flatpak applications].
