:_mod-docs-content-type: PROCEDURE
:FeatureName: The {vulnerabilityengine}

[id="installing-{insights-iop-context}-on-a-connected-{project-context}-server"]
= Installing {insights-iop} on a connected {ProjectServer}

ifdef::satellite[]
You can pull the {insights-iop} from the Red{nbsp}Hat container registry if your {ProjectServer} has access to the registry.
endif::[]
ifndef::satellite[]
You can pull the {insights-iop} from the Quay container registry.
endif::[]

.Prerequisites
ifdef::satellite[]
* Ensure that the {ProjectServer} has access to the Red{nbsp}Hat container registry.
endif::[]
ifndef::satellite[]
* Ensure that the {ProjectServer} has access to the Quay container registry.
endif::[]
* Ensure that Podman is installed.
ifdef::satellite[]
For more information, see {RHELDocsBaseURL}9/html/building_running_and_managing_containers/assembly_starting-with-containers_building-running-and-managing-containers#proc_getting-container-tools_assembly_starting-with-containers[Getting container tools] in _{RHEL}{nbsp}9 Building, running, and managing containers_.
endif::[]
ifndef::satellite[]
For more information, see https://podman.io/docs/installation#installing-on-linux[Installing Podman on Linux].
endif::[]

.Procedure
ifdef::satellite[]
. Log in to the Red{nbsp}Hat registry by using Podman:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# podman login --authfile /etc/foreman/registry-auth.json registry.redhat.io
----
endif::[]
. Enable the plugin:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --enable-iop
----
. If you want to use the {vulnerabilityengine} and your {ProjectServer} connects to `\https://security.access.redhat.com` through an HTTP proxy, configure the `iop-cvemap-download` service to use the same HTTP proxy:
.. Edit the `iop-cvemap-download` service:
+
[source, ini, options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl edit iop-cvemap-download.service
----
.. Input the following content:
+
[source, ini, options="nowrap", subs="+quotes,verbatim,attributes"]
----
[Service]
Environment = HTTPS_PROXY=http://_http-proxy.example.com:port_
Environment = NO_PROXY=localhost
----

+
include::snip_technology-preview.adoc[]
