[id="registering-{project-context}-as-a-keycloak-client_{context}"]
= Registering {Project} as a {keycloak} client
Use this procedure to register {Project} to {keycloak} as a client and configure {Project} to use {keycloak} as an authentication source.

You can configure {Project} and {keycloak} with two different authentication methods:

. Users authenticate to {Project} using the {ProjectWebUI}.
. Users authenticate to {Project} using the {Project} CLI.

You must decide on how you want your users to authenticate in advance because both methods require different {Project} clients to be registered to {keycloak} and configured.
The steps to register and configure {Project} client in {keycloak} are distinguished within the procedure.

You can also register two different {Project} clients to {keycloak} if you want to use both authentication methods and configure both clients accordingly.

.Procedure

// python3-lxml is only needed on EL8 because of https://issues.redhat.com/browse/RHEL-31496
. On {ProjectServer}, install the following packages:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {project-package-install} mod_auth_openidc keycloak-httpd-client-install python3-lxml
----

. Register {Project} to {keycloak} as a client.
Note that you the registration process for logging in using the web UI and the CLI are different.
You can register two clients {Project} clients to {keycloak} to be able to log in to {Project} from the web UI and the CLI.
+
* If you want you users to authenticate to {Project} using the web UI, create a client as follows:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# keycloak-httpd-client-install --app-name foreman-openidc \
--keycloak-server-url "_https://{keycloak-example-com}_" \
--keycloak-admin-username "_admin_" \
--keycloak-realm "_{Project}_Realm_" \
--keycloak-admin-realm master \
--keycloak-auth-role root-admin \
-t openidc -l /users/extlogin --force
----
+
Enter the password for the administer account when prompted.
This command creates a client for {Project} in {keycloak}.
+
Then, configure {Project} to use {keycloak} as an authentication source:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {foreman-installer} --foreman-keycloak true \
--foreman-keycloak-app-name "foreman-openidc" \
--foreman-keycloak-realm "_{Project}_Realm_"
----
+
* If you want your users to authenticate to {Project} using the CLI, create a client as follows:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# keycloak-httpd-client-install --app-name hammer-openidc \
--keycloak-server-url "_https://{keycloak-example-com}_" \
--keycloak-admin-username "_admin_" \
--keycloak-realm "_{Project}_Realm_" \
--keycloak-admin-realm master \
--keycloak-auth-role root-admin \
-t openidc -l /users/extlogin --force
----
+
Enter the password for the administer account when prompted.
This command creates a client for {Project} in {keycloak}.

. Restart the `httpd` service:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# systemctl restart httpd
----
