[id="Building_a_Discovery_Image_{context}"]
= Building a Discovery Image

The Discovery image is a minimal operating system that is PXE-booted on hosts to acquire initial hardware information and to check in with {Project}.
Discovered hosts keep running the Discovery image until they are rebooted into Anaconda, which then initiates the provisioning process.

ifdef::satellite[]
The operating system image is based on {RHEL} 7.
endif::[]
ifdef::orcharhino[]
Run the following procedure on Rocky Linux 8.

The Discovery image is based on Cent OS Stream 8.
endif::[]
ifndef::satellite,orcharhino[]
The operating system image is based on CentOS Stream 8.
endif::[]

ifdef::satellite[]
The `foreman-discovery-image` package contains this image.
You must install the package on the {SmartProxy} that provides TFTP services.
endif::[]

Use this procedure to build a {Project} discovery image or rebuild an image if you change configuration files.

Do not use this procedure on your production {Project} or {SmartProxy}.
Use either a dedicated environment or copy the synchronized repositories and a kickstart file to a separate server.

ifdef::orcharhino[]
.Prerequisites
* Ensure that hardware virtualization is available on your host.
* Install the following packages:
+
[options="nowrap" subs="+quotes"]
----
# dnf install lorax anaconda pykickstart wget qemu-kvm
----
* Clone the `foreman-discovery-image` repository:
+
[options="nowrap" subs="+quotes"]
----
$ git clone https://github.com/theforeman/foreman-discovery-image.git
$ cd foreman-discovery-image
----

.Procedure
. Prepare the kickstart file:
+
[options="nowrap" subs="+quotes"]
----
$ ./build-livecd fdi-centos8.ks
----
. Build the ISO image:
+
[options="nowrap" subs="+quotes"]
----
$ sudo ./build-livecd-root _custom_ ./result "nomodeset nokaslr"
----
+
The options `nomodeset` and `nokaslr` instruct the Discovery image kernel to disable mode setting and to disable ASLR (Address Space Layout Randomization).
. Verify that your `./result/fdi-custom-XXXXXXX.iso` file is created:
+
[options="nowrap" subs="+quotes"]
----
$ ls -h ./result/*.iso
----

Use the following command to build a fully automated Discovery image with a static network configuration:
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ sudo ./build-livecd-root _custom_ ./result \
"nomodeset nokaslr \
fdi.pxip=192.168.140.20/24 fdi.pxgw=192.168.140.1 \
fdi.pxdns=192.168.140.2 proxy.url=https://{foreman-example-com}:8443 \
proxy.type=foreman fdi.pxmac=52:54:00:be:8e:8c fdi.pxauto=1"
----

For more information about configuration options, see xref:Unattended_Use_Customization_and_Image_Remastering_{context}[].

endif::[]
ifndef::orcharhino[]
.Prerequisites
* Install the `livecd-tools` package:
+
ifdef::foreman-el,katello,orcharhino[]
----
# yum install livecd-tools
----
endif::[]
ifdef::satellite[]
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} livecd-tools
----
endif::[]

ifdef::satellite[]
* For the following {RHEL} 7 repositories required to build the Discovery image, change the download policy to *Immediate*.
This is required because {Project} downloads all packages only during synchronization of repositories with the immediate download policy.
+
** The latest *{RHEL} 7 Server (Kickstart)* repository.
For example, *{RHEL} 7 Server Kickstart x86_64 7.7*.
** *Red Hat Satellite Capsule {ProductVersion} for RHEL 7 Server RPMs x86_64*.

+
For more information about changing download policies, see {ContentManagementDocURL}changing_the_download_policy_for_a_repository_content-management[Changing the Download Policy for a Repository] in the _Content Management Guide_.

* Synchronize the following {RHEL} 7 repositories required to build the Discovery image:
+
** The latest *{RHEL} 7 Server (Kickstart)* repository.
For example, *{RHEL} 7 Server Kickstart x86_64 7.7*.
** *Red Hat Satellite Capsule {ProductVersion} for RHEL 7 Server RPMs x86_64*.

+
For more information about synchronizing repositories, see {ContentManagementDocURL}Synchronizing_Repositories_content-management[Syncing Repositories] in the _Content Management Guide_.
endif::[]

.Procedure
. Open the `/usr/share/foreman-discovery-image/foreman-discovery-image.ks` file for editing:
+
[options="nowrap" subs="+quotes"]
----
# vim /usr/share/foreman-discovery-image/foreman-discovery-image.ks
----
. Replace the `repo` lines in the kickstart file with the repository URLs:
+
[options="nowrap" subs="quotes,attributes"]
----
ifdef::satellite[]
repo --name=rhel --baseurl=file:///var/lib/pulp/published/yum/https/repos/My_Organization/Library/content/dist/rhel/server/7/7.7/x86_64
repo --name=sat --baseurl=file:///var/lib/pulp/published/yum/https/repos/My_Organization/Library/content/dist/rhel/server/7/7Server/x86_64/sat-capsule/{ProductVersion}/os
endif::[]
ifdef::foreman-el,katello,orcharhino[]
repo --name=centos --mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=os
repo --name=centos-updates --mirrorlist=http://mirrorlist.centos.org/?release=7&arch=$basearch&repo=updates
repo --name=epel7 --mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
repo --name=centos-sclo-rh --mirrorlist=http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=sclo-rh
repo --name=foreman-el7 --baseurl=http://yum.theforeman.org/releases/{ProjectVersion}/el7/$basearch/
repo --name=foreman-plugins-el7 --baseurl=http://yum.theforeman.org/plugins/{ProjectVersion}/el7/$basearch/
endif::[]
----
. Run the `livecd-creator` tool:
+
[options="nowrap" subs="+quotes"]
----
# livecd-creator \
--cache=var/cache/build-fdi \
--compression-type=xz \
--config /usr/share/foreman-discovery-image/foreman-discovery-image.ks \
--fslabel fdi \
--title="_My_Discovery_Image_" \
--tmpdir /var/tmp
----
+
If you change `fdi` in the `--fslabel` option, you must also change the root label on the kernel command line when loading the image.
`fdi` or the alternative name is appended to the `.iso` file that is created as part of this procedure.
The PXE Discovery tool uses this name when converting from `.iso` to PXE.
+
Use `/var/tmp` because this process requires close to 3GB of space and `/tmp` might have problems if the system is low on swap space.
. Verify that your `fdi.iso` file is created:
+
[options="nowrap" subs="+quotes"]
----
# ls -h *.iso
----
endif::[]

When you create the `.iso` file, you can boot the `.iso` file over a network or locally.
Complete one of the following procedures.

If you want to boot the `.iso` file over a network, complete the following steps:

.Procedure
ifndef::orcharhino[]
. To extract the initial ramdisk and kernel files from the `.iso` file over a network, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# discovery-iso-to-pxe fdi.iso
----
endif::[]
. Create a directory to store your boot files:
+
[options="nowrap" subs="+quotes"]
----
# mkdir /var/lib/tftpboot/boot/_myimage_
----
ifdef::orcharhino[]
. Copy the `./tftpboot/initrd0.img` and `./tftpboot/vmlinuz0` files to your new directory.
endif::[]
ifndef::orcharhino[]
. Copy the `initrd0.img` and `vmlinuz0` files to your new directory.
endif::[]
. Edit the `KERNEL` and `APPEND` entries in the `/var/lib/tftpboot/pxelinux.cfg` file to add the information about your own initial ramdisk and kernel files.

If you want to create a hybrid `.iso` file for booting locally, complete the following steps:

.Procedure
. To convert the `.iso` file to an `.iso` hybrid file for PXE provisioning, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# isohybrid --partok fdi.iso
----
+
If you have `grub2` packages installed, you can also use the following command to install a `grub2` bootloader:
+
[options="nowrap" subs="+quotes"]
----
# isohybrid --partok --uefi fdi.iso
----
. To add `md5` checksum to the `.iso` file so it can pass installation media validation tests in {Project}, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# implantisomd5 fdi.iso
----
