:_mod-docs-content-type: PROCEDURE

[id="tracking-subscription-usage-by-using-the-subscriptions-service"]
= Tracking subscription usage by using the Subscriptions service

[role="_abstract"]
You can configure your {ProjectServer} to report usage data to the {RHCloud} by using the `foreman_rh_cloud` plugin.

ifndef::satellite[]
.Prerequisites
* Enable the `foreman_rh_cloud` plugin:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --enable-foreman-plugin-rh-cloud
----
endif::[]

Connected {Project}::
In the {ProjectWebUI}, navigate to *{Insights}* > *Inventory Upload* to configure the `foreman_rh_cloud` plugin and share inventory information with the {RHCloud}.
Ensure that the *Automatic Inventory Upload* setting is enabled.
The plugin enables the subscriptions service to track usage information across connected systems.
+
You can configure the plugin to omit data that is not needed for subscription tracking, such as host names and IP addresses.

Disconnected {Project}::
Export usage data in one of the following ways:

** Use the `foreman_rh_cloud` plugin to generate a report locally. 
You can download the report from the {ProjectWebUI}.  
The report is in JSON format and is easily integrated for automated scripts or machine processing. 
You can generate this report by using CLI:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# foreman-rake rh_cloud_inventory:report:generate
----

** View product usage by running the *Host - Installed Products* report. 
+
Navigate to *Monitor* > *Reports* > *Report Templates*. 
You can select the format that you want for the report. 
YAML, JSON, HTML, and CSV formats are supported.
