[id="Creating_Bookmarks_{context}"]
= Creating Bookmarks

This section details how to save a search query as a bookmark.
You must save the search query on the relevant page to create a bookmark for that page, for example, saving a host related search query on the Hosts page.

.Procedure
. In the {ProjectWebUI}, navigate to the page where you want to create a bookmark.
. In the *Search* field, enter the search query you want to save.
. Select the arrow to the right of the *Search* button and then select *Bookmark this search*.
. In the *Name* field, enter a name for the new bookmark.
. In the *Search query* field, ensure your search query is correct.
. Ensure the *Public* checkbox is set correctly:
* Select the *Public* checkbox to set the bookmark as public and visible to all users.
* Clear the *Public* checkbox to set the bookmark as private and only visible to the user who created it.
. Click *Submit*.

To confirm the creation, either select the arrow to the right of the *Search* button to display the list of bookmarks, or navigate to *Administer* > *Bookmarks* and then check the *Bookmarks* list for the name of the bookmark.
