[id="Editing_the_System_Purpose_of_a_Host_{context}"]
= Editing the System Purpose of a Host

You can edit the system purpose attributes for a {RHEL} host.
System purpose attributes define which subscriptions to attach automatically to the host.
ifndef::orcharhino[]
For more information about system purpose, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/graphical-installation_graphical-installation#configuring-system-purpose-standard_configuring-system-settings[Configuring system purpose] in the _Performing a standard RHEL installation_ guide.
endif::[]

.Prerequisites
* The host that you want to edit must be registered with the subscription-manager.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Select the hosts you want to modify.
. Click *Edit* next to the *System purpose* card.
. Select the purpose attributes for your host.
. Click *Save*.
// Is there a way to auto-attach subscriptions here?

.CLI procedure
. Log in to the host and edit the required system purpose attributes.
For example, set the usage type to `Production`, the role to `{RHELServer}`, and add the `addon` add on.
ifndef::orcharhino[]
For the list of values, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_8_installation/graphical-installation_graphical-installation#configuring-system-purpose-standard_configuring-system-settings[Configuring system purpose] in the _Performing a standard RHEL installation_ guide.
endif::[]
+
[subs="+quotes"]
----
# subscription-manager syspurpose set usage `_Production_`
# subscription-manager syspurpose set role `_Red Hat Enterprise Linux Server_`
# subscription-manager syspurpose add addons '_your_addon_'
----
. Verify the system purpose attributes for this host:
+
[subs="+quotes"]
----
# subscription-manager syspurpose
----
. Automatically attach subscriptions to this host:
+
[subs="+quotes"]
----
# subscription-manager attach --auto
----
. Verify the system purpose status for this host:
+
[subs="+quotes"]
----
# subscription-manager status
----
