[id="Performing_a_Full_Backup_{context}"]
= Performing a full backup of {ProjectServer} or {SmartProxyServer}

{ProjectName} uses the `{foreman-maintain} backup` command to make backups.

There are two main methods of backing up {ProjectServer}:

* Offline backup
* Online backup
+
For more information about each of these methods, you can view the usage statements for each backup method.

.Offline backups
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline --help
----

.Online backups
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup online --help
----

.Directory creation
The `{foreman-maintain} backup` command creates a time-stamped subdirectory in the backup directory that you specify.
The `{foreman-maintain} backup` command does not overwrite backups, therefore you must select the correct directory or subdirectory when restoring from a backup or an incremental backup.
The `{foreman-maintain} backup` command stops and restarts services as required.

When you run the `{foreman-maintain} backup offline` command, the following default backup directories are created:

* `{project-context}-backup` on {Project}
* `foreman-proxy-backup` on {SmartProxy}

If you want to set a custom directory name, add the `--preserve-directory` option and add a directory name.
The backup is then stored in the directory you provide in the command line.
If you use the `--preserve-directory` option, no data is removed if the backup fails.

Note that if you use a local PostgreSQL database, the `postgres` user requires write access to the backup directory.

.Remote databases
You can use the `{foreman-maintain} backup` command to back up remote databases.

You can use both online and offline methods to back up remote databases, but if you use offline method, the `{foreman-maintain} backup` command performs a database dump.

.Backing up to a remote NFS share

You can back up your {ProjectServer} or {SmartProxyServer} in a remote NFS share.

* Make sure you export the share in your NFS server with the `no_root_squash` option to disable root squashing.
For example:

[options="nowrap", subs="+quotes,attributes"]
----
/backup/{project-context}/backup {foreman-example-com}(rw,sync,no_root_squash)
----

* Make sure the NFS share has the appropriate permissions set on the NFS server.
Otherwise, {Project} might fail to save the backup to the NFS share.

.Prerequisites
* Ensure that your backup location has sufficient available disk space to store the backup.
For more information, see xref:Estimating_the_Size_of_a_Backup_{context}[].

[WARNING]
====
Request other users of {ProjectServer} or {SmartProxyServer} to save any changes and warn them that {Project} services are unavailable for the duration of the backup.
Ensure no other tasks are scheduled for the same time as the backup.
====

.Procedure
* On {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline _/var/{project-context}-backup_
----
* On {SmartProxyServer}, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline _/var/foreman-proxy-backup_
----
