:_mod-docs-content-type: PROCEDURE

[id="Importing_Ansible_Roles_and_Variables_{context}"]
= Importing Ansible roles and variables

[role="_abstract"]
You can import Ansible roles and variables from the Ansible paths on {ProjectServer} or {SmartProxyServers} that have Ansible enabled.

.Procedure
. Place the roles and variables in the appropriate Ansible paths on all {SmartProxies} from where you want to use the roles.
For more information, see xref:ansible-role-and-collection-paths-in-{project-context}[].
+
If you want to use custom or third party Ansible roles, ensure to configure an external version control system to synchronize roles between {ProjectServer} and {SmartProxyServers}.
. In the {ProjectWebUI}, navigate to *Configure* > *Ansible* > *Roles*.
. Click *Import* to select the {SmartProxy} from which you want to import.
. Select the roles that you want to import.
. Click *Submit*.

.Additional resources
* {ContentManagementDocURL}synchronizing-ansible-collections_{context}[Synchronizing Ansible Collections in _{ContentManagementDocTitle}_]
* {ContentManagementDocURL}consuming-content-from-an-ansible-collection-repository_{context}[Consuming Content from an Ansible Collection Repository in _{ContentManagementDocTitle}_]
