[id="enabling-openscap"]
= Enabling OpenSCAP

ifdef::satellite[]
The OpenSCAP plugin is enabled on your {ProjectServer} by default.
endif::[]
ifndef::satellite[]
You can install and enable the OpenSCAP plugin to generate SCAP compliance reports.
The OpenSCAP plugin consists of the OpenSCAP {Project} plugin, the OpenSCAP Hammer CLI plugin, the OpenSCAP {SmartProxy} plugin, and modules for policy deployment.
endif::[]
To use the OpenSCAP plugin and SCAP content on {SmartProxyServers}, you must enable OpenSCAP on each {SmartProxyServer}.

.Procedure
ifndef::satellite[]
. Install the OpenSCAP plugin on your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--enable-foreman-plugin-openscap \
--enable-foreman-cli-openscap \
--enable-foreman-proxy-plugin-openscap \
--foreman-proxy-plugin-openscap-ansible-module true \
--foreman-proxy-plugin-openscap-puppet-module true
----
endif::[]
ifdef::satellite[]
* Enable OpenSCAP on your {SmartProxyServer}:
endif::[]
ifndef::satellite[]
. Enable OpenSCAP on your {SmartProxyServer}:
endif::[]
+
[options="nowrap" subs="quotes,attributes"]
----
# {foreman-installer} \
--enable-foreman-proxy-plugin-openscap \
--foreman-proxy-plugin-openscap-ansible-module true \
--foreman-proxy-plugin-openscap-puppet-module true
----

.Verification
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*.
. Select your {SmartProxy}.
. Verify that the OpenSCAP feature is active.

ifdef::katello,orcharhino,satellite[]
.Next steps
ifdef::katello,orcharhino[]
* If you want to use Ansible to deploy compliance policies, you must enable it first.
For more information, see {ManagingConfigurationsAnsibleDocURL}[_{ManagingConfigurationsAnsibleDocTitle}_].
endif::[]
* If you want to use Puppet to deploy compliance policies, you must enable it first.
For more information, see {ManagingConfigurationsPuppetDocURL}[_{ManagingConfigurationsPuppetDocTitle}_].
endif::[]
