:_mod-docs-content-type: PROCEDURE

[id="changing-the-http-proxy-policy-for-a-repository-by-using-web-ui"]
= Changing the HTTP proxy policy for a repository by using {ProjectWebUI}

[role="_abstract"]
You can set an HTTP proxy policy to synchronize repositories to {ProjectServer}.
Use an HTTP proxy for repository synchronization if your network restricts access to the internet.

To set the same HTTP proxy policy for all repositories in a product, see xref:Changing_the_HTTP_Proxy_Policy_for_a_Product_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products* and click the name of the product that contains the repository.
. In the *Repositories* tab, click the name of the repository.
. Locate the *HTTP Proxy* field and click the edit icon.
. Select an *HTTP Proxy Policy* from the list:
* *Global Default*: Use the global default HTTP proxy setting.
* *No HTTP Proxy*: Do not use an HTTP proxy, even if a global default HTTP proxy is configured.
* *Use specific HTTP Proxy*: Select an *HTTP Proxy* from the list.
You must add HTTP proxies to {Project} before you can select a proxy from this list.
For more information, see xref:adding-an-http-proxy-by-using-web-ui[].
. Click *Save*.
