[id="Configuring_the_Discovery_Service_{context}"]
= Configuring the Discovery service










ifndef::orcharhino[]
Since network interface names are not expected to always be the same https://access.redhat.com/solutions/5984311[between major versions] of {RHEL},
ifdef::foreman-el,katello[]
or any other operating system being provisioned,
endif::[]
hosts or virtual machines can be created with incorrect network configurations. On Dell servers, the new naming scheme can be disabled via `biosdevname=1` kernel command line option, for other hardware or virtual machines, the new naming scheme can be completely turned off via `net.ifnames=1`.
endif::[]

[NOTE]
====
ifdef::satellite[]
The Foreman Discovery image provided with {Project} is based on {EL} 8.
endif::[]
ifdef::orcharhino[]
The Foreman Discovery image provided with {Project} is based on CentOS Stream 8.
endif::[]
ifndef::satellite,orcharhino[]
{Project} provides link:https://downloads.theforeman.org/discovery/releases/[multiple versions] of the Foreman Discovery image (FDI):

* FDI version 4.0 and newer are based on CentOS Stream 8
* FDI versions older than 4.0 are based on CentOS Stream 7
endif::[]
====
