[id="using-novnc-to-access-virtual-machines_{context}"]
= Using noVNC to Access Virtual Machines

You can use your browser to access the VNC console of VMs created by {Project}.

{Project} supports using noVNC on the following virtualization platforms:

* VMware
* Libvirt
* {oVirt}

.Prerequisites
* You must have a virtual machine created by {Project}.
* For existing virtual machines, ensure that the *Display type* in the *Compute Resource* settings is *VNC*.
* You must import the Katello root CA certificate into your {ProjectServer}.
Adding a security exception in the browser is not enough for using noVNC.
For more information, see {AdministeringDocURL}Importing_the_Katello_Root_CA_Certificate_admin[Installing the Katello Root CA Certificate] in _{AdministeringDocTitle}_.

.Procedure
. On the VM host system, configure the firewall to allow VNC service on ports 5900 to 5930:
+
ifndef::satellite[]
* On operating systems with the `iptables` command:

----
# iptables -A INPUT -p tcp --dport 5900:5930 -j ACCEPT
# service iptables save
----
* On operating systems with the `firewalld` service:
endif::[]
+
----
# firewall-cmd --add-port=5900-5930/tcp
# firewall-cmd --add-port=5900-5930/tcp --permanent
----
ifndef::satellite[]
+
include::snip_firewalld.adoc[]
+
endif::[]
. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*Compute Resources* and select the name of a compute resource.
. In the *Virtual Machines* tab, select the name of a VM host.
Ensure the machine is powered on and then select *Console*.
