:_mod-docs-content-type: PROCEDURE

[id="change-an-ansible-execution-environment-by-using-api"]
= Change an Ansible Execution Environment by using {Project} API

[role="_abstract"]
You can change an Ansible Execution Environment in {Project} by using {Project} API.
You can change the name, base container image, or version of `ansible-core`.

.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_execution_environments`, `edit_ansible_execution_environments`, `view_ansible_content`, `view_ansible_execution_environments`, and `view_organizations` permissions.

.Procedure
. Optional: Get a list of your Ansible Execution Environment:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/execution_environments/ \
| jq ".results | .[]"
----
. Create a JSON file, for example, `data.json` to define your Ansible Execution Environment:
+
[source, json, options="nowrap", subs="verbatim,quotes,attributes"]
----
{
  "execution_environment": {
    "name": "_My_Ansible_Execution_Environment_Name_",
    "base_image_url": "_My_Container_Image_URL_",
    "ansible_version": "_My_Ansible_Version_"
  }
}
----
+
You must provide values for all fields, even if you do not want to change them.
. Change your Ansible Execution Environment:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--data @data.json \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--request PATCH \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_content/_My_Ansible_Execution_Environment_ID_/ \
| jq
----

.Verification
* Query the {Project} API to verify that {Project} changed the Ansible Execution Environment successfully:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/execution_environments/ \
| jq ".results | .[]"
----

.Additional resources
* xref:build-an-ansible-execution-environment-by-using-api[]
