:_mod-docs-content-type: PROCEDURE

[id="assigning-content-view-environments-to-an-activation-key-by-using-web-ui"]
= Assigning content view environments to an activation key by using {ProjectWebUI}

[role="_abstract"]
You can assign content view environments to an activation key to provide hosts with access to content from each assigned environment.
Hosts registered with the activation key receive the environments in the order they are assigned.
For more information, see xref:content-view-environment-ordering-and-priority[].

.Prerequisites
* If you want to assign multiple content view environments, the *Allow multiple content views* setting must be enabled.
For more information, see xref:content-view-environments-overview[].
* You have created an activation key.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Activation Keys*.
. Click the name of the activation key to which you want to assign content view environments.
. On the the *Content view environments* card, click *Assign content view environments*.
. Select a lifecycle environment.
. Select a content view.
. Optional: Click *Assign another content view environment* to assign additional content view environments to the activation key.
. Optional: Drag and drop the content view environments to change the order of the content view environments.
. Click *Save*.

.Verification
* The *Details* tab of the activation key displays the assigned content view environments in order.

.Additional resources
* xref:multiple-activation-keys-and-content-view-environments[]
