[id="Configuring_a_Host_to_Use_the_Pull_Client_{context}"]
= Configuring a host to use the pull client

For {SmartProxies} configured to use `pull-mqtt` mode, hosts can subscribe to remote jobs using the remote execution pull client.
Hosts do not require an SSH connection from their {SmartProxyServer}.

.Prerequisites
* You have registered the host to {Project}.
* The {SmartProxy} through which the host is registered is configured to use `pull-mqtt` mode.
For more information, see {InstallingSmartProxyDocURL}configuring-pull-based-transport-for-remote-execution_{smart-proxy-context}[Configuring pull-based transport for remote execution] in _{InstallingSmartProxyDocTitle}_.
include::snip_prerequisite-project-client-repository-enabled.adoc[]
ifdef::foreman-el[]
* The AppStream repository is available for the host.
endif::[]
ifndef::foreman-el[]
* The AppStream repository for the operating system version of the host is synchronized on {ProjectServer}, available in the content view and the lifecycle environment of the host, and enabled for the host.
For more information, see {ContentManagementDocURL}Changing_the_Repository_Sets_Status_for-a-Host-in_{project-context}_content-management[Changing the repository sets status for a host in {Project}] in _{ContentManagementDocTitle}_.
endif::[]
* The host can communicate with its {SmartProxy} over MQTT using port `1883`.
* The host can communicate with its {SmartProxy} over HTTPS using port `{smartproxy_port}`.

.Procedure
* Install the `katello-pull-transport-migrate` package on your host:
ifdef::client-content-dnf[]
** On {EL} 10, {EL} 9, and {EL} 8 hosts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-el8} katello-pull-transport-migrate
----
ifdef::orcharhino,satellite[]
** On {EL} 7 hosts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-el7} katello-pull-transport-migrate
----
endif::[]
endif::[]
ifdef::client-content-apt[]
** On {DL} hosts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-deb} katello-pull-transport-migrate
----
endif::[]
ifdef::client-content-zypper[]
** On {SLES} hosts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-sles} katello-pull-transport-migrate
----
endif::[]

.Verification
. Determine which version of the `yggdrasil` package is installed on the host:
+
ifdef::satellite[]
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ rpm --query yggdrasil
----
endif::[]
ifndef::satellite[]
* On {EL} and {SLES} hosts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ rpm --query yggdrasil
----
endif::[]
ifdef::client-content-apt[]
* On {DL} hosts:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ dpkg-query --show yggdrasil-mqtt
----
endif::[]
. Check the status of the Yggdrasil services:
* If your host has `yggdrasil` version 0.4.z or later installed:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl status yggdrasil com.redhat.Yggdrasil1.Worker1.foreman
----
* If your host has `yggdrasil` version 0.2.z or earlier installed:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl status yggdrasild
----

If the services are running, you have successfully configured the host to use the pull client.
