[id="Downloading_Files_to_a_Host_from_a_Custom_File_Type_Repository_{context}"]
= Downloading Files to a Host From a {customfiletypetitle} Repository

You can download files to a client over HTTPS using `curl -O`, and optionally over HTTP if the *Publish via HTTP* repository option is selected.

.Prerequisites
* You have a {customfiletype} repository.
For more information, see xref:Creating_a_Custom_File_Type_Repository_{context}[].
* You know the name of the file you want to download to clients from the file type repository.
* To use HTTPS you require the following certificates on the client:
+
. The `katello-server-ca.crt`.
For more information, see {AdministeringDocURL}Installing_the_Katello_Root_CA_Certificate_admin[Installing the Katello Root CA Certificate] in the _Administering {ProjectName}_ guide.
. An Organization Debug Certificate.
ifndef::satellite[]
For more information, see {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate] in the _Managing Organizations and Locations in {Project}_ guide.
endif::[]
ifdef::satellite[]
For more information, see xref:Creating_an_Organization_Debug_Certificate_{context}[].
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select a {customproduct} by name.
. Select a file type repository by name.
. Check to see if *Publish via HTTP* is enabled.
If it is not, you require the certificates to use HTTPS.
. Copy the URL where the repository is published.

.CLI procedure
. List the file type repositories.
+
[options="nowrap" subs="+quotes"]
----
# hammer repository list --content-type file
---|------------|-------------------|--------------|----
ID | NAME       | PRODUCT           | CONTENT TYPE | URL
---|------------|-------------------|--------------|----
7  | _My_Files_ | _My_File_Product_ | file         |
---|------------|-------------------|--------------|----
----
. Display the repository information.
+
[options="nowrap",subs="+quotes"]
----
# hammer repository info \
--name "_My Files_" \
--organization-id _My_Organization_ID_ \
--product "_My_File_Product_"
----
+
If HTTP is enabled, the output is similar to this:
+
[options="nowrap" subs="+quotes,attributes"]
----
Publish Via HTTP:   yes
Published At:       http://_{foreman-example-com}_/pulp/isos/_uuid_/
----
+
If HTTP is not enabled, the output is similar to this:
+
[options="nowrap" subs="+quotes,attributes"]
----
Publish Via HTTP:   no
Published At:       https://_{foreman-example-com}_/pulp/isos/_uuid_/
----
. On the client, enter a command in the appropriate format for HTTP or HTTPS:
+
For HTTP:
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -O _{foreman-example-com}_/pulp/isos/_uuid_/_my_file_
----
+
For HTTPS:
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -O --cert _./Default\ Organization-key-cert.pem_ --cacert katello-server-ca.crt _{foreman-example-com}_/pulp/isos/_uuid_/_my_file_
----
