[id="installing-fapolicyd-on-server_{context}"]
ifeval::["{context}" == "{project-context}"]
= Installing fapolicyd on {ProjectServer}
endif::[]
ifeval::["{context}" == "{smart-proxy-context}"]
= Installing fapolicyd on {SmartProxyServer}
endif::[]

ifeval::["{context}" == "{project-context}"]
You can install `fapolicyd` along with {ProjectServer} or can be installed on an existing {ProjectServer}.
If you are installing `fapolicyd` along with the new {ProjectServer}, the installation process will detect the fapolicyd in your {EL} host and deploy the {ProjectServer} rules automatically.
endif::[]
ifeval::["{context}" == "{smart-proxy-context}"]
You can install `fapolicyd` along with {SmartProxyServer} or can be installed on an existing {SmartProxyServer}.
If you are installing `fapolicyd` along with the new {SmartProxyServer}, the installation process will detect the fapolicyd in your {EL} host and deploy the {SmartProxyServer} rules automatically.
endif::[]

.Prerequisites
* Ensure your host has access to the BaseOS repositories of {EL}.

.Procedure
. For a new installation, install fapolicyd:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf install fapolicyd
----
. For an existing installation, install fapolicyd using {project-package-install}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {project-package-install} fapolicyd
----
. Start the `fapolicyd` service:
+
[options="nowrap" subs="+quotes,attributes"]
----
# systemctl enable --now fapolicyd
----

.Verification
* Verify that the `fapolicyd` service is running correctly:
+
[options="nowrap" subs="+quotes"]
----
# systemctl status fapolicyd
----

.New {ProjectServer} or {SmartProxyServer} installations
In case of new {ProjectServer} or {SmartProxyServer} installation, follow the standard installation procedures after installing and enabling fapolicyd on your {EL} host.

.Additional resources
For more information on fapolicyd, see {RHELDocsBaseURL}9/html/security_hardening/assembly_blocking-and-allowing-applications-using-fapolicyd_security-hardening[Blocking and allowing applications using fapolicyd] in _{RHEL}{nbsp}9 Security hardening_.
