[id="Adding_Amazon_EC2_Images_to_Server_{context}"]
= Adding Amazon EC2 Images to {ProjectServer}

Amazon EC2 uses image-based provisioning to create hosts.
You must add image details to your {ProjectServer}.
This includes access details and image location.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-amazon-ec2-images_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*Compute Resources* and select an Amazon EC2 connection.
. Click the *Images* tab, and then click *New Image*.
. In the *Name* field, enter a name to identify the image for future use.
. From the *Operating System* list, select the operating system that corresponds with the image you want to add.
. From the *Architecture* list, select the operating system's architecture.
. In the *Username* field, enter the SSH user name for image access.
This is normally the `root` user.
. In the *Password* field, enter the SSH password for image access.
. In the *Image ID* field, enter the Amazon Machine Image (AMI) ID for the image.
This is usually in the following format: `ami-xxxxxxxx`.
. Optional: Select the *User Data* checkbox if the images support user data input, such as `cloud-init` data.
If you enable user data, the Finish scripts are automatically disabled.
This also applies in reverse: if you enable the Finish scripts, this disables user data.
. Optional: In the *IAM role* field, enter the Amazon security role used for creating the image.
. Click *Submit* to save the image details.

[id="cli-adding-amazon-ec2-images_{context}"]
.CLI procedure
* Create the image with the `hammer compute-resource image create` command.
Use the `--uuid` field to store the full path of the image location on the Amazon EC2 server.
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-resource image create \
--architecture "_My_Architecture_" \
--compute-resource "_My_EC2_Compute_Resource_" \
--name "_My_Amazon_EC2_Image_" \
--operatingsystem "_My_Operating_System_" \
--user-data true \
--username root \
--uuid "ami-_My_AMI_ID_"
----
