[[Changing_the_Default_Download_Policy]]
= Changing the Default Download Policy

You can set the default download policy that {Project} applies to repositories that you create in all organizations.

ifdef::satellite[]
Depending on whether it is a Red Hat or non-Red Hat {customrepo}, {Project} uses separate settings.
Changing the default value does not change existing settings.
endif::[]
ifndef::satellite[]
Depending on whether it is a Red Hat, SUSE, or {customrepo}, {Project} uses separate settings.
Changing the default value does not change existing settings.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Administer*{nbsp}>{nbsp}*Settings*.
. Click the *Content* tab.
. Change the default download policy depending on your requirements:
+
* To change the default download policy for a Red Hat repository, change the value of the *Default Red Hat Repository download policy* setting.
ifdef::satellite[]
* To change the default download policy for a {customrepo}, change the value of the *Default Custom Repository download policy* setting.
endif::[]
ifndef::satellite[]
* To change the default download policy for a non-Red Hat {customrepo}, change the value of the *Default Custom Repository download policy* setting.
endif::[]

.CLI procedure
* To change the default download policy for Red Hat repositories to one of `immediate` or `on_demand`, enter the following command:
+
[subs="+quotes"]
----
# hammer settings set \
--name default_redhat_download_policy \
--value _immediate_
----

ifndef::satellite[]
* To change the default download policy for a {customrepo} to one of `immediate` or `on_demand`, enter the following command:
endif::[]
ifdef::satellite[]
* To change the default download policy for a non-Red Hat {customrepo} to one of `immediate` or `on_demand`, enter the following command:
endif::[]
+
[subs="+quotes"]
----
# hammer settings set \
--name default_download_policy \
--value _immediate_
----
