[id="Applying_configurations_{context}"]
= Applying configurations

In following sections we suggest various tunables and how to apply them.
Please always test changing these in non production environment first, with valid backup and with proper outage window as in most of the cases {Project} restart is required.

It is also a good practice to setup a monitoring before applying any change as it will allow you to evaluate effect of the change.
Our testing environment might be too far from what you will see although we are trying hard to mimic real world environment.

._Changing systemd service files_
If you have changed some systemd service file, you need to notify systemd daemon to reload the configuration:

----
# systemctl daemon-reload
----

After this you still need to reload relevant service for the change to take effect. It is best to restart whole {Project}:

[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service restart
----

._Changing configuration files_
If you have changed some configuration file (e.g. `/etc/foreman-installer/custom-hiera.yaml`), you need to apply the changes:

[options="nowrap" subs="attributes"]
----
# {foreman-installer}
----

._Running installer with additional options_
If you need to rerun installer with some new options added:

[options="nowrap" subs="attributes,quotes"]
----
# {foreman-installer} _new options_
----

._Checking basic sanity of the setup_
Optional: After any change, run this quick {Project} health-check:

[options="nowrap" subs="attributes"]
----
# {foreman-maintain} health check
----
