:_mod-docs-content-type: PROCEDURE

[id="logging-in-to-the-{ProjectWebUI-context}_{context}"]
= Logging in to the {ProjectWebUI}

[role="_abstract"]
Use the web user interface to log in to {Project} for further configuration.

ifdef::katello,orcharhino,satellite[]
.Prerequisites
* Ensure that the Katello root CA certificate is installed in your browser.
For more information, see xref:common/modules/proc_importing-the-katello-root-ca-certificate-using-web-ui.adoc#importing-the-katello-root-ca-certificate-using-{project-context}-web-ui[].
endif::[]

.Procedure
. Access {ProjectServer} using a web browser pointed to the fully qualified domain name:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
https://_{foreman-example-com}_/
----
. Enter the user name and password created during the configuration process.
If a user was not created during the configuration process, the default user name is _admin_.

.Next steps
* If you have problems logging in, you can reset the password.
For more information, see xref:common/modules/proc_resetting-the-administrative-user-password.adoc#Resetting_the_Administrative_User_Password_{context}[].
