[id="Distribution_of_Archived_Content_View_Versions_{context}"]
= Distribution of Archived Content View Versions

If you have a Content View version that is not associated with any lifecycle environments, you can set the default view of that Content View version to be viewed.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. Click the *Content* tab.
. Set the *Distribute archived content view versions* parameter to *Yes*.
. Click *Submit*.
+
This enables the repositories of Content View versions without lifecycle environments to be distributed at `/pulp/content/<organization>/content_views/<content view>/X.Y/…`.
+
If you set the *Distribute archived content view versions* parameter to *No*, it does not delete the old repositories of Content View versions but does not create new repositories.
To see the published Content View version, do the following:
. Navigate to *Content Views* and select the Content View.
Click the *Versions* tab to view the versions of the Content View.
