:_mod-docs-content-type: PROCEDURE

[id="updating-{project-context}-server"]
= Updating {ProjectServer}

[role="_abstract"]
You can update your {ProjectServer} to the latest packages published by {Team}.

ifdef::orcharhino[]
If you want to upgrade {Project} to the next version, see xref:sources/installation_and_maintenance/upgrading_orcharhino_server.adoc[Upgrading {ProjectServer}] or xref:sources/installation_and_maintenance/upgrading_orcharhino_proxy_server.adoc[Upgrading {SmartProxyServer}].
endif::[]

.Prerequisites
* Back up your {ProjectServer}.
For more information, see {AdministeringDocURL}backing-up-{project-context}[Backing up {Project}] in _{AdministeringDocTitle}_.

.Procedure
ifdef::containerized[]
. Use the health check option to determine if the system is ready for update:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} health
----
+
Review the results and address any highlighted error conditions before performing the update.
. Update the {Project} repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf upgrade https://yum.theforeman.org/releases/{ProjectVersion}/el9/x86_64/foreman-release.rpm
----
. Upgrade the `foremanctl` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf upgrade foremanctl
----
. Re-deploy {ProjectServer} to perform the update:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} deploy
----
endif::[]
ifndef::containerized[]
. On your {ProjectServer}, start {Project} maintenance mode:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} maintenance-mode start
----
. Upgrade all packages:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {project-package-update}
----
. Reconfigure {ProjectServer}:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {foreman-installer}
----
. Stop {Project} maintenance mode:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} maintenance-mode stop
----
endif::[]

.Verification
* On your {ProjectServer}, verify that all {Project} services are running:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
ifdef::containerized[]
# systemctl status foreman.target
endif::[]
ifndef::containerized[]
# {foreman-maintain} service status -b
endif::[]
----

ifndef::containerized[]
.Next steps
* Update your {SmartProxyServers}.
For more information, see xref:updating-{smart-proxy-context}-server[]
endif::[]
