[id="Creating_a_Host_Group_{context}"]
= Creating a Host Group

A host group is a template for common host settings.
Adding host settings and attributes for every new host is time consuming.
If you use host groups, you can apply common attributes to hosts that you create.

.Host Group Settings and Nested Host Groups

A host group can define many settings for hosts, such as Lifecycle Environment, Content View, or Ansible roles that are available to the hosts.

NOTE: When you change the properties of a host group, the new settings do not propagate to the hosts assigned to the host group.
Only Puppet class settings get updated on hosts after you change them in the host group.

You can create a hierarchy of host groups.
Aim to have one base level host group that represents all hosts in your organization and provides general settings, and then nested groups that provide specific settings.

.Nested Host Group Hierarchy
====
You create a top-level host group named `Base` and two nested host groups named `Webserver` and `Storage`.
The nested host groups are associated with multiple hosts.
You also create host `custom.example.com` that is not associated with any host group.

[cols="1,1,1"]
|===
|Top-level host group |Nested host group |Host

.5+|*Base*

This host group applies the `{EL}{nbsp}8.8` operating system setting.

.2+|*Webserver*

This host group applies the `linux-system-roles.selinux` Ansible role.

|*webserver1.example.com*
|*webserver2.example.com*

.2+|*Storage*

This host group applies the `linux-system-roles.postfix` Ansible role.

|*storage1.example.com*
|*storage2.example.com*

|
|*custom.example.com*

|===

In this hierarchy:

* `Base` defines the settings common to all hosts. All hosts use {EL}{nbsp}8.8 as their operating system.
* `webserver1.example.com` and `webserver2.example.com` use the `linux-system-roles.selinux` Ansible role.
`storage1.example.com` and `storage2.example.com` use the `linux-system-roles.postfix` Puppet class.
* `custom.example.com` inherits none of the Puppet classes defined by the host groups.
====

{Project} applies host settings in the following order when nesting host groups:

* Host settings take priority over host group settings.
* Nested host group settings take priority over parent host group settings.

.Nested Host Group Settings
====
You define different values for the operating system and Ansible role settings on the top-level host group (*Base*) and nested host groups (*Webserver* and *Storage*).

[cols="1,1,1"]
|===
|Top-level host group |Nested host group |Host

.3+a|*Base*

This host group applies these settings:

* The `{EL}{nbsp}8.8` operating system
* The `linux-system-roles.selinux` Ansible role

a|*Webserver*

This host group applies these settings:

* The `{EL}{nbsp}8.9` operating system
* No Ansible role

a|*webserver1.example.com*

*webserver2.example.com*

a|*Storage*

This host group applies these settings:

* No operating system
* The `linux-system-roles.postfix` Ansible role

a|*storage1.example.com*

*storage2.example.com*

|
a|*custom.example.com*

|===

{Project} applies settings from nested groups in the following way:

* *webserver1.example.com* and *webserver2.example.com* inherit these settings:
** The `{EL}{nbsp}8.9` operating system from host group *Webservers*
** The `linux-system-roles.selinux` Ansible role from host group *Base*
* *storage1.example.com* and *storage2.example.com* inherit these settings:
** The `{EL}{nbsp}8.8` operating system from host group *Webservers*
** The `linux-system-roles.postfix` Ansible role from host group *Base*
* *custom.example.com* inherits this setting:
** The `{EL}{nbsp}8.8` operating system from host group *Base*

====

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-host-group_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups* and click *Create Host Group*.
. If you have an existing host group that you want to inherit attributes from, you can select a host group from the *Parent* list.
If you do not, leave this field blank.
. Enter a *Name* for the new host group.
. Enter any further information that you want future hosts to inherit.
. Click the *Ansible Roles* tab, and from the *Ansible Roles* list, select one or more roles that you want to add to the host.
Use the *arrow* icon to manage the roles that you add or remove.
. Click the additional tabs and add any details that you want to attribute to the host group.
+
[NOTE]
====
Puppet fails to retrieve the Puppet CA certificate while registering a host with a host group associated with a Puppet environment created inside a `Production` environment.

To create a suitable Puppet environment to be associated with a host group, manually create a directory:

[options="nowrap", subs="+quotes,attributes"]
----
# mkdir /etc/puppetlabs/code/environments/_example_environment_
----
====
. Click *Submit* to save the host group.

[id="cli-creating-a-host-group_{context}"]
.CLI procedure
* Create the host group with the `hammer hostgroup create` command.
For example:
+
----
# hammer hostgroup create --name "Base" \
--architecture "My_Architecture" \
--content-source-id _My_Content_Source_ID_ \
--content-view "_My_Content_View_" \
--domain "_My_Domain_" \
--lifecycle-environment "_My_Lifecycle_Environment_" \
--locations "_My_Location_" \
--medium-id _My_Installation_Medium_ID_ \
--operatingsystem "_My_Operating_System_" \
--organizations "_My_Organization_" \
--partition-table "_My_Partition_Table_" \
--puppet-ca-proxy-id _My_Puppet_CA_Proxy_ID_ \
--puppet-environment "_My_Puppet_Environment_" \
--puppet-proxy-id _My_Puppet_Proxy_ID_ \
--root-pass "My_Password" \
--subnet "_My_Subnet_"
----
