:_mod-docs-content-type: PROCEDURE

[id="Configuring_Server_for_Outgoing_Emails_{context}"]
= Configuring {ProjectServer} for outgoing emails

To send email messages from {ProjectServer}, you can use an SMTP server.

.Prerequisites
* Some SMTP servers with anti-spam protection or grey-listing features are known to cause problems.
To set up outgoing email with such a service, install and configure a vanilla SMTP service on {ProjectServer} for relay.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. Click the *Email* tab and set the configuration options to match your preferred delivery method.
The changes have an immediate effect.
+
.. The following example shows the configuration options for using an SMTP server:
+
.Using an SMTP server as a delivery method
[cols="1,1,2",options="header"]
|====
|Name| Example value| Additional information
|Delivery method       | SMTP |
|SMTP address          | _smtp.example.com_ |
|SMTP authentication   | login |
|SMTP HELO/EHLO domain | _example.com_ |
|SMTP password         | _password_ | Use the login credentials for the SMTP server.
|SMTP port             | 25 |
|SMTP username         | _user@example.com_ | Use the login credentials for the SMTP server.
|====
.. The following example uses *gmail.com* as an SMTP server:
+
.Using gmail.com as an SMTP server
[cols="1,1,2",options="header"]
|====
|Name| Example value| Additional information
|Delivery method           | SMTP |
|SMTP address              | smtp.gmail.com |
|SMTP authentication       | plain |
|SMTP HELO/EHLO domain     | smtp.gmail.com |
|SMTP enable StartTLS auto | Yes |
|SMTP password             | _app password_ | Use the Google app password.
For more information, see https://support.google.com/mail/answer/185833[Sign in with app passwords] in _Google Help Center_.
|SMTP port                 | 587 |
|SMTP username             | _user_@gmail.com | Use the Google account name.
|====
+

. To send email by using an SMTP server that uses TLS authentication, also perform one of the following steps:
+
* Mark the CA certificate of the SMTP server as trusted.
To do so, execute the following commands on {ProjectServer}:
+
[options="nowrap"]
----
# cp mailca.crt /etc/pki/ca-trust/source/anchors/
# update-ca-trust extract
----
+
Where `_mailca.crt_` is the CA certificate of the SMTP server.
+
* Alternatively, in the {ProjectWebUI}, set the `SMTP enable StartTLS auto` option to `No`.

. Click *Test email* to send a test message to the user's email address to confirm the configuration is working.
If a message fails to send, the {ProjectWebUI} displays an error.
See the log at `/var/log/foreman/production.log` for further details.

.Additional resources
* For information on configuring email notifications for individual users or user groups, see {AdministeringDocURL}Configuring_Email_Notification_Preferences_admin[Configuring Email Notification Preferences] in _{AdministeringDocTitle}_.
