:_mod-docs-content-type: PROCEDURE

[id="registering-a-host-to-{project-context}-by-using-web-ui"]
= Registering a host to {Project} by using {ProjectWebUI}

[role="_abstract"]
You can register a host to {Project} by using the {ProjectWebUI} with registration templates.
This also enables you to set up various integration features and host tools during the registration process.

.Prerequisites
include::snip_registering-a-host-prerequisites.adoc[]

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Register Host*.
. Enter the details for how you want the registered host to be configured.
* If you select a host group from the *Host Group* list, the following fields inherit their values from the host group:
+
** *Operating system*
ifdef::katello,satellite,orcharhino[]
** *Activation Keys*
endif::[]
** *Lifecycle environment*
ifdef::katello,satellite,orcharhino[]
* A {SmartProxy} behind a load balancer takes precedence over the {SmartProxy} selected in the {ProjectWebUI} as the content source of the host.
. On the *General* tab, in the *Activation Keys* field, enter one or more activation keys to assign to your host.
endif::[]
. Specify any other registration details that you require.
The available settings include the following:
+
* On the *General* tab, in the *{SmartProxy}* field, you can select the {SmartProxy} to register your host through.
A {SmartProxy} behind a load balancer takes precedence over a {SmartProxy} selected in the {ProjectWebUI} as the content source of the host.
* On the *General* tab, in the *Download utility* field, you can select `wget` if you want to register your host by using a `wget` command.
By default, {Project} generates a `curl` command.
* On the *General* tab, you can select the *Insecure* option to make the first call insecure.
During this first call, your host downloads the CA file from {Project}.
Your host will use this CA file to connect to {Project} with all future calls making them secure.
+
{Team} recommends that you avoid insecure calls.
+
If an attacker, located in the network between {Project} and your host, fetches the CA file from the first insecure call, the attacker will be able to access the content of the API calls to and from your host and the JSON Web Tokens (JWT).
Therefore, if you have chosen to deploy SSH keys during registration, the attacker will be able to access your host using the SSH key.
ifndef::orcharhino[]
* On the *Advanced* tab, in the *Repositories* field, you can list repositories to be added before the registration is performed.
You do not have to specify repositories if you provide them in an activation key.
endif::[]
* On the *Advanced* tab, you can configure
ifdef::katello,satellite,red_hat_enterprise_linux[remote execution, {Insights}, and packages to be installed.]
ifdef::almalinux,amazon_linux,centos,debian,oracle_linux,rocky_linux,suse_linux_enterprise_server,ubuntu[remote execution and packages to be installed.]
* On the *Advanced* tab, in the *Token lifetime (hours)* field, you can change the validity duration of the JSON Web Token (JWT) that {Project} uses for authentication.
The duration of this token defines how long the generated registration command works.
+
Note that {Project} applies the permissions of the user who generates the registration command to authorization of your host.
If the user loses or gains additional permissions, the permissions of the JWT change too.
Therefore, do not delete, block, or change permissions of the user during the token duration.
+
The scope of the JWTs is limited to the registration endpoints only and cannot be used anywhere else.
* On the *Advanced* tab, you can enable container and Flatpak registry access without a username or password by selecting the *Set up container registry certs* checkbox.
Using certificate-based authentication also enforces lifecycle management of container and Flatpak content for the host.
ifdef::orcharhino[]
. On the *Advanced* tab, in the *Repositories* field, enter the repositories for {client-os} {client-os-major} and {project-client-name} on {Project}.
ifdef::debian,ubuntu[]
* In the *Repository* field, enter the `{project-client-name} for {client-os} {client-os-major}` repository, for example, `deb \http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}_Client/{client-os-label}_Client_{client-os-major-label}/ stable main`.
* In the *Repository* field, enter the `{client-os} {client-os-major} main` repository, for example, `deb \http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}_{client-os-major-label}/{client-os-label}{client-os-major-label}_main/ {client-os-codename-lowercase} main`.
* In the *Repository* field, enter the `{client-os} {client-os-major} security` repository, for example, `deb \http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}/{client-os-label}_{client-os-major-label}_security/ {client-os-codename-lowercase}-security main`.
* In the *Repository* field, enter the `{client-os} {client-os-major} updates` repository, for example, `deb \http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}/{client-os-label}_{client-os-major-label}_updates/ {client-os-codename-lowercase}-updates main`.
* For all repositories, in the *Repository GPG key URL* field, enter the URL of the `pulp_deb_signing.key` file on your {SmartProxy} as GPG public key to verify synchronized {client-content-type} content, for example, `\https://{foreman-example-com}/pub/pulp_deb_signing.key`.
endif::[]
ifdef::almalinux,centos,oracle_linux,rocky_linux[]
* In the *Repository* field, enter the `{project-client-name} for {client-os} {client-os-major}` repository URL, for example, `\http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}_Client/{client-os-label}_Client_{client-os-major}/`.
* In the *Repository* field, enter the `{client-os} {client-os-major} BaseOS` repository URL, for example, `\http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}_{client-os-major}/BaseOS/`.
* In the *Repository* field, enter the `{client-os} {client-os-major} AppStream` repository URL, for example, `\http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}_{client-os-major}/AppStream/`.
* For all repositories, in the *Repository GPG key URL* field, enter the URL of the associated GPG public key of the repository to verify synchronized {client-content-type} content, for example, `\https://{foreman-example-com}/katello/api/v2/repositories/_My_Repository_ID_/gpg_key_content`.
endif::[]
ifdef::amazon_linux,red_hat_enterprise_linux,suse_linux_enterprise_server[]
* In the *Repository* field, enter the {project-client-name} repository URL, for example, `\http://{foreman-example-com}/pulp/content/_My_Organization_Label_/Library/custom/{client-os-label}_client/{client-os-label}_client/`.
* In the *Repository GPG key URL* field, enter the URL of the associated GPG public key of the repository to verify synchronized {client-content-type} content, for example, `\https://{foreman-example-com}/katello/api/v2/repositories/_My_Repository_ID_/gpg_key_content`.
endif::[]
ifdef::amazon_linux,suse_linux_enterprise_server[]
* Use the *Published At* URLs of {client-os} {client-os-major} repositories to provide the required repositories to your host.
endif::[]
ifdef::red_hat_enterprise_linux[]
* Use the *Published At* URLs of {client-os} {client-os-major} Kickstart repositories to provide the BaseOS and AppStream repositories to your host.
endif::[]
endif::[]
. Click *Generate* to create the registration command.
. Click on the _files_ icon to copy the command to your clipboard.
. Connect to your host using SSH and run the registration command.
. Run the registration command as `root` on the host that you want to register.
After registration completes, any Ansible roles assigned to a host group you specified when configuring the registration template will run on the host.

ifdef::katello,orcharhino,satellite[]
include::snip_verification-repositories-enabled.adoc[]
endif::[]

ifdef::katello,orcharhino,satellite[]
.Next steps
* To set up monitoring of outdated services and applications using Tracer, see {ManagingHostsDocURL}configuring-tracer-on-a-host_managing-hosts[Configuring Tracer on a host] in _{ManagingHostsDocTitle}_.
endif::[]
