[id="setting-the-provisioning-context_{context}"]
= Setting the Provisioning Context

When you set a provisioning context, you define which organization and location to use for provisioning hosts.

The organization and location menus are located in the menu bar, on the upper left of the {ProjectWebUI}.
If you have not selected an organization and location to use, the menu displays: *Any Organization* and *Any Location*.
ifdef::orcharhino[]
For more information, see xref:sources/management_ui/the_context_menu.adoc[context menu].
endif::[]

.Procedure

. Click *Any Organization* and select the organization.
. Click *Any Location* and select the location to use.

Each user can set their default provisioning context in their account settings.
Click the user name in the upper right of the {ProjectWebUI} and select *My account* to edit your user account settings.

.CLI procedure

* When using the CLI, include either `--organization` or `--organization-label` and `--location` or `--location-id` as an option.
For example:
+
[subs="+quotes"]
----
# hammer host list --organization "Default_Organization" --location "Default_Location"
----
+
This command outputs hosts allocated for the Default_Organization and Default_Location.
