:_mod-docs-content-type: PROCEDURE

[id="verifying-requirements-for-local-user-and-group-accounts"]
= Verifying requirements for local user and group accounts

[role="_abstract"]
When configuring Active Directory (AD) integration, you must ensure that all user and group accounts remain local on your {ProjectServer}.
Maintaining these local accounts prevents potential authentication conflicts between accounts defined in {ProjectServer} and accounts defined in the AD domain.

To ensure that authentication conflicts between {Project} and AD users and groups do not occur, verify whether the user and group accounts exist in both the `/etc/passwd` file for account definitions and the `/etc/group` file for group definitions on your {ProjectServer}.

.Procedure
. On your {ProjectServer}, verify whether entries for `puppet`, `{apache-user}`, `foreman` and `foreman-proxy` groups exist in both `/etc/passwd` and `/etc/group`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# grep 'puppet\|{apache-user}\|foreman\|foreman-proxy' /etc/passwd /etc/group
----
+
If the command returns entries for each account from both `/etc/password` and `/etc/group`, no conflicts occur.
. If the command does not return entires for each account, create the missing accounts.
