[id="Adding_VMware_Details_to_a_Compute_Profile_{context}"]
= Adding VMware Details to a Compute Profile

You can predefine certain hardware settings for virtual machines on VMware vSphere.
You achieve this through adding these hardware settings to a compute profile.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-Adding_VMware_Details_to_a_Compute_Profile_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*Compute Profiles*.
. Select a compute profile.
. Select a Vmware compute resource.
. In the *CPUs* field, enter the number of CPUs to allocate to the host.
. In the *Cores per socket* field, enter the number of cores to allocate to each CPU.
. In the *Memory* field, enter the amount of memory in MiB to allocate to the host.
. In the *Firmware* checkbox, select either _BIOS_ or _UEFI_ as firmware for the host.
By default, this is set to _automatic_.
. In the *Cluster* list, select the name of the target host cluster on the VMware environment.
. From the *Resource pool* list, select an available resource allocations for the host.
. In the *Folder* list, select the folder to organize the host.
. From the *Guest OS* list, select the operating system you want to use in VMware vSphere.
. From the *Virtual H/W version* list, select the underlying VMware hardware abstraction to use for virtual machines.
. If you want to add more memory while the virtual machine is powered on, select the *Memory hot add* checkbox.
. If you want to add more CPUs while the virtual machine is powered on, select the *CPU hot add* checkbox.
. If you want to add a CD-ROM drive, select the *CD-ROM drive* checkbox.
. From the *Boot order* list, define the order in which the virtual machines tried to boot.
. Optional: In the *Annotation Notes* field, enter an arbitrary description.
. If you use image-based provisioning, select the image from the *Image* list.
. From the *SCSI controller* list, select the disk access method for the host.
. If you want to use eager zero thick provisioning, select the *Eager zero* checkbox.
By default, the disk uses lazy zero thick provisioning.
. From the *Network Interfaces* list, select the network parameters for the host's network interface.
At least one interface must point to a {SmartProxy}-managed network.
. Optional: Click *Add Interface* to create another network interfaces.
. Click *Submit* to save the compute profile.

[id="cli-Adding_VMware_Details_to_a_Compute_Profile_{context}"]
.CLI procedure
. Create a compute profile:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile create --name "_My_Compute_Profile_"
----
. Set VMware details to a compute profile:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile values create \
--compute-attributes "cpus=1,corespersocket=2,memory_mb=1024,cluster=MyCluster,path=MyVMs,start=true" \
--compute-profile "_My_Compute_Profile_" \
--compute-resource "_My_VMware_" \
--interface "compute_type=VirtualE1000,compute_network=mynetwork \
--volume "size_gb=20G,datastore=Data,name=myharddisk,thin=true"
----
