[id="Configuring_Your_{project-context}_to_Run_Ansible_Roles_{context}"]
= Configuring Your {Project} to Run Ansible Roles

In {Project}, you can import Ansible roles to help with automation of routine tasks.
ifdef::satellite[]
Ansible is enabled by default on {ProjectServer}.
endif::[]
ifndef::satellite[]
To enable Ansible on {ProjectServer}, see xref:Enabling_Ansible_Integration_with_{project-context}_{context}[].
endif::[]

[id="Ansible-paths_{context}"]
.Ansible paths

{Project} imports Ansible roles and variables from paths based on configuration in `/etc/ansible/ansible.cfg`.
{Project} then runs imported roles from paths based on configuration in `/etc/foreman-proxy/ansible.cfg`.
In both cases, {Project} reads the paths from `roles_path` and `collections_paths` directives.
Keep these two cfg files in sync, otherwise you might import roles that cannot be run or you will not see roles you can run.

If none of the paths are specified in the configuration files, the following default paths are used:

* `/etc/ansible/roles`
* `/usr/share/ansible/roles`
* `/etc/ansible/collections`
* `/usr/share/ansible/collections`

.Procedure
. Configure your xref:Ansible-paths_{context}[] on the {ProjectServer} and all {SmartProxyServers} where you want to use the roles.
. Add the roles to a directory in an xref:Ansible-paths_{context}[Ansible path] on the {ProjectServer} and all {SmartProxyServers} from where you want to use the roles.
If you want to use custom or third party Ansible roles, ensure to configure an external version control system to synchronize roles between {ProjectServer} and {SmartProxyServers}.

. On all {SmartProxyServers} that you want to use to run Ansible roles on hosts, enable the Ansible plug-in:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {installer-scenario-smartproxy} \
--enable-foreman-proxy-plugin-ansible
----
. Distribute SSH keys to enable {SmartProxies} to connect to hosts using SSH.
For more information, see {ManagingHostsDocURL}ssh-keys-for-remote-execution-overview_managing-hosts[Distributing SSH Keys for Remote Execution] in _{ManagingHostsDocTitle}_.
{Project} runs Ansible roles the same way it runs remote execution jobs.
. Import the Ansible roles into {Project}.
. Proceed to xref:Using_Ansible_Roles_to_Automate_Repetitive_Tasks_on_Clients_{context}[].
