[id="configuring-project-settings-for-keycloak-authentication_{context}"]
= Configuring {Project} Settings for {Keycloak} Authentication

. In the {Project} web UI, navigate to *Administer* > *Settings*, and click the *Authentication* tab.
. Locate the *Authorize login delegation* row, and in the *Value* column, set the value to *Yes*.
. Locate the *Authorize login delegation auth source user autocreate* row, and in the *Value* column,
set the value to *External*.
. Locate the *Login delegation logout URL* row, and in the *Value* column, set the value to
*https://{foreman-example-com}/users/extlogout*.
. Locate the *OIDC Algorithm* row, and in the *Value* column, set the algorithm for encoding on {Keycloak} to *RS256*.
. Locate the *OIDC Audience* row, and in the *Value* column, set the value to the client ID for {Keycloak}.
. Locate the *OIDC Issuer* row, and in the *Value* column, set the value to _https://{Keycloak-short}.com:8443/auth/realms/{Project}_Realm_.
. Locate the *OIDC JWKs URL* row, and in the *Value* column, set the value to _https://{Keycloak-short}.com:8443auth/realms/{Project}_Realm/protocol/openid-connect/certs_.
. Navigate to *Administer* > *Authentication Sources* and click *External*.
. Click *Create LDAP Authentication Source* and select the {Keycloak} server.
. Click the *Locations* tab and add locations that can use the {Keycloak} authentication source.
. Click the *Organizations* tab and add organizations that can use the {Keycloak} authentication source.
. Click *Submit*.
