[id="configuring-project-with-keycloak-for-totp-authentication_{context}"]
= Configuring {Project} with {Keycloak} for TOTP Authentication

Use this procedure to configure {Project} to use {Keycloak} as an OpenID provider for external authentication with Time-based One-time Password (TOTP).

.Prerequisites

* {Project} configured with {Keycloak} external authentication.

.Procedure

. In the {Keycloak} web UI, navigate to the {Project} realm.
. Navigate to *Authentication*, and click the *OTP Policy* tab.
. Ensure that the *Supported Applications* field includes FreeOTP or Google Authenticator.
. Configure the OTP settings to suit your requirements.
. Optional: If you want to use TOTP authentication as a default authentication method for all users, click the *Flows* tab, and to the right of the *OTP Form* setting, select *REQUIRED*.
. Click the *Required Actions* tab.
. To the right of the *Configure OTP* row, select the *Default Action* check box
. To verify that OTP authentication works, log in to {Project}, {Project} redirects you to SSO login screen.
. Enter your username and password, and click *Log In*.
. Because this is the first attempt to log in, {Keycloak} requests you to configure your client by scanning the barcode and entering the pin displayed.
. After configuring your client and entering a valid PIN, you are redirected to {Project} and
logged in.
