[id="Configuring_the_Discovery_Service_{context}"]
= Configuring the Discovery service

ifndef::orcharhino[]
// Why and when is this a problem?
Network interface names are not expected to always be the same https://access.redhat.com/solutions/5984311[between major versions] of {RHEL},
ifdef::foreman-el,katello[]
or any other operating system being provisioned,
endif::[]
hosts or virtual machines can be created with incorrect network configurations.
You can disable the new naming scheme by a kernel command line argument:

* For Dell servers, use the `biosdevname=1` argument.
* For other hardware or virtual machines, use the `net.ifnames=1` argument.
endif::[]

[NOTE]
====
ifdef::satellite[]
The Foreman Discovery image provided with {Project} is based on {EL} 8.
endif::[]
ifdef::orcharhino[]
The Foreman Discovery image provided with {Project} is based on CentOS Stream 8.
endif::[]
ifndef::satellite,orcharhino[]
{Project} provides link:https://downloads.theforeman.org/discovery/releases/[multiple versions] of the Foreman Discovery image (FDI):

* FDI version 4.0 and newer are based on CentOS Stream 8
* FDI versions older than 4.0 are based on CentOS Stream 7
endif::[]
====
