:_mod-docs-content-type: PROCEDURE

[id="promoting-a-content-view-by-using-cli"]
= Promoting a content view by using Hammer CLI

[role="_abstract"]
Use this procedure to promote content views across different lifecycle environments by using Hammer CLI.

.Prerequisites
* Your {Project} account has a role that grants the `promote_or_remove_content_views` and `promote_or_remove_content_views_to_environment` permissions.

.Procedure
* Promote the content view to a lifecycle environment:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view version promote \
--content-view "_My_Content_View_Name_" \
--version 1 \
--to-lifecycle-environment "_My_Lifecycle_Environment_Name_" \
--organization "_My_Organization_"
----
+
Repeat the command for each lifecycle environment to promote the content view to.

.Verification
* Display information about your content view version to verify that it is promoted to the required lifecycle environment:
+
[options="nowrap" subs="verbatim,quotes"]
----
$ hammer content-view version info --id _My_Content_View_Version_ID_
----

.Next steps
* To register a host to your content view, see {ManagingHostsDocURL}Registering_Hosts_by_Using_Global_Registration_managing-hosts[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_.
