:_mod-docs-content-type: PROCEDURE

[id="configuring-{project-context}-server-to-consume-content-from-a-custom-cdn-by-using-web-ui"]
= Configuring {ProjectServer} to consume content from a custom CDN by using {ProjectWebUI}

[role="_abstract"]
Configure your {ProjectServer} to consume Red{nbsp}Hat repositories from a custom Content Delivery Network (CDN) server or web server instead of the Red{nbsp}Hat CDN.
{Project} automatically recognizes which repositories from your subscription manifest are available on your CDN server.

.Prerequisites
* You have a CDN server that provides Red{nbsp}Hat content and is accessible by {ProjectServer}.
* If your CDN server uses HTTPS, ensure you have uploaded the SSL certificate into {Project}.
For more information, see {ContentManagementDocURL}importing-custom-ssl-certificates-by-using-web-ui[Importing Custom SSL Certificates] in _{ContentManagementDocTitle}_.
* You have uploaded a manifest to your organization.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Subscriptions*.
. Click *Manage Manifest*.
. Select the *CDN Configuration* tab.
. Select the *Custom CDN* tab.
. In the *URL* field, enter the URL of your CDN server from which you want {ProjectServer} to consume Red{nbsp}Hat repositories.
. Optional: In the *SSL CA Content Credential*, select the SSL certificate of the CDN server.
. Click *Update*.
. Enable Red{nbsp}Hat repositories consumed from your internal CDN server.
