[id="configuring_a_bonded_interface"]
= Configuring a bonded interface

You can combine multiple physical interfaces together by configuring a bonded interface for the host.

[NOTE]
====
Bonded interfaces currently require a MAC address of a physical device.
Therefore, the configuration of these interfaces works only on bare-metal hosts.
====

.Procedure
. Navigate to the *Add Interface* form:
.. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
.. Click *Edit* next to the host you want to edit.
.. On the *Interfaces* tab, click *Add Interface*.

. Select *Bond* from the *Type* list.

. Specify the general interface settings:
.. In the *Device Identifier* field, specify the interface ID in the `bond0` format .
.. Specify a *MAC address*.
.. If you are configuring a secondary interface, select *Managed*.
Otherwise, {Project} does not apply the configuration.

. Add the configuration specific to bonded interfaces:
.. *Mode*: Select the bonding mode.
.. *Attached devices*: Specify a comma-separated list of identifiers of attached devices.
These can be physical interfaces or VLANs.
.. *Bond options*: Specify a space-separated list of configuration options, for example `miimon=100`.

. Click *OK* to save the interface configuration.
. Click *Submit* to apply the changes to the host.

[id="cli-configuring-a-bonded-interface"]
.CLI procedure

* To create a host with a bonded interface, enter the following command:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# hammer host create \
--ask-root-password yes \
--hostgroup _My_Host_Group_ \
--ip=_My_IP_Address_ \
--mac=_My_MAC_Address_ \
--managed true \
--interface="identifier=_My_NIC_1, mac=_My_MAC_Address_1_, managed=true, type=Nic::Managed, domain_id=_My_Domain_ID_, subnet_id=_My_Subnet_ID_" \
--interface="identifier=_My_NIC_2_, mac=_My_MAC_Address_2_, managed=true, type=Nic::Managed, domain_id=_My_Domain_ID_, subnet_id=_My_Subnet_ID_" \
--interface="identifier=_bondN_, ip=_My_IP_Address_2_, type=Nic::Bond, mode=active-backup, attached_devices=[_My_NIC_1_,_My_NIC_2_], managed=true, domain_id=_My_Domain_ID_, subnet_id=_My_Subnet_ID_" \
--location "_My_Location_" \
--name "_My_Host_Name_" \
--organization "_My_Organization_" \
--subnet-id=_My_Subnet_ID_
----
+
Replace `bondN` with `bond` and the ID of your device identifier, for example, `bond0`.
