[id="Adding_Custom_DEB_Repositories_{context}"]
= Adding {customdebtitle} Repositories

Use this procedure to add {customdeb} repositories in {Project}.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-custom-deb-repositories[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products* and select the product that you want to use, and then click *New Repository*.
. In the *Name* field, enter a name for the repository.
{Project} automatically completes the *Label* field based on what you have entered for *Name*.
. Optional: In the *Description* field, enter a description for the repository.
. From the *Type* list, select `deb` as type of repository.
. In the *Upstream URL* field, enter the URL of the external repository to use as a source.
You can find the upstream URLs on Debian-based systems in `/etc/apt/sources.list`.
. In the *Releases/Distributions* field, set one or multiple releases separated by whitespace.
The distributions specify the path from the repository root to the `Release` file.
Repositories that omit the `dists` directory are using the deprecated _flat repository structure_.
To synchronize a flat repository, you must specify exactly one distribution that ends with a `/`.
+
For official Debian repositories, set a _codename_ in the *Releases/Distributions* field, for example `buster` for Debian 10 or `bullseye` for Debian 11.
Avoid using `stable` or `testing` because the codename they reference changes over time.
This helps to avoid drastic changes once a new Debian version is released and the reference is changed.
To keep things easy to manage and to avoid potential performance and network issues during synchronization, create one repository per release in {Project}.
For official Ubuntu repositories, use the Ubuntu suite, for example `focal` or `focal-updates`.
. Optional: In the *Components* field, enter a component.
This indicates the licensing terms of the software packages.
+
In Debian, it is divided into `main`, `contrib`, and `non-free`.
For official Debian or Ubuntu repositories, {Team} recommends leaving this field empty to synchronize all available components.
Note that some third party Debian repositories use the components in ways that may require setting an explicit selection.
+
[CAUTION]
====
Ensure that you enter both *Releases* and *Components* exactly as they are in an `/etc/apt/sources.list` file.
====
. Optional: In the *Architectures* field, enter one or multiple architectures.
If you want to make the repository available to all hosts regardless of the architecture, ensure to select *No restriction*.
ifdef::orcharhino[]
. Optional: In the *Errata URL* field, enter the URL of an errata service.
endif::[]
. Select the *Verify SSL* check box if you want to verify that the upstream repository's SSL certificates are signed by a trusted CA.
. Optional: In the *Upstream Username* field, enter the user name for the upstream repository if required for authentication.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Password* field, enter the corresponding password for the upstream repository.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Authentication Token* field, provide the token of the upstream repository user for authentication.
Leave this field empty if the repository does not require authentication.
. From the *Download Policy* list, select the type of synchronization {ProjectServer} performs.
For more information, see xref:Download_Policies_Overview_{context}[].
. From the *Mirroring Policy* list, select the type of content synchronization {ProjectServer} performs.
For more information, see xref:Mirroring_Policies_Overview_{context}[].
. Optional: In the *HTTP Proxy Policy* field, select an HTTP proxy.
. Optional: If you want, you can clear the *Publish via HTTP* check box to disable this repository from publishing through HTTP.
. Optional: From the *GPG Key* list, select the GPG key if you want to verify the signatures of the `Release` files associated with the Debian repository.
. Optional: In the *SSL CA Cert* field, select the SSL CA Certificate for the repository.
. Optional: In the *SSL Client cert* field, select the SSL Client Certificate for the repository.
. Optional: In the *SSL Client Key* field, select the SSL Client Key for the repository.
. Click *Save* to create the repository.

[id="cli-adding-custom-deb-repositories"]
.CLI procedure
. Enter the following command to create the repository:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository create \
--content-type "deb" \
--deb-architectures "_My_DEB_Architectures" \
--deb-components "_My_DEB_Components_" \
--deb-releases "_My_DEB_Releases_" \
--gpg-key-id "_My_GPG_Key_ID" \
--name "_My_Repository_" \
--organization "_My_Organization_" \
--product "_My_Product_" \
--publish-via-http true \
--url _My_Upstream_URL_
----

Continue to xref:Synchronizing_Repositories_{context}[synchronize the repository].
