[id="Creating_an_Insights_Plan_for_Hosts_{context}"]
= Creating an Insights Plan for Hosts

With {Project}, you can create a Red{nbsp}Hat Insights remediation plan and run the plan on {Project} hosts.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* *>* *Insights*.
. On the Red{nbsp}Hat Insights page, select the number of recommendations that you want to include in an Insights plan.
+
You can only select the recommendations that have an associated playbook.
. Click *Remediate*.
. In the *Remediation Summary* window, you can select the *Resolutions* to apply.
Use the *Filter* field to search for specific keywords.
. Click *Remediate*.
. In the *Job Invocation* page, do not change the contents of precompleted fields.
. Optional. For more advanced configuration of the Remote Execution Job, click *Show Advanced Fields*.
. Select the *Type of query* you require.
. Select the *Schedule* you require.
. Click *Submit*.

Alternatively:

. In the {ProjectWebUI}, navigate to *Hosts* *>* *All Hosts*.
. Select a host.
. On the Host details page, click *Recommendations*.
. On the Red{nbsp}Hat Insights page, select the number of recommendations you want to include in an Insights plan and proceed as before.

In the Jobs window, you can view the progress of your plan.
