:_mod-docs-content-type: PROCEDURE

[id="troubleshooting-remote-jobs-timing-out-after-yggdrasil-update"]
= Troubleshooting: Remote jobs timing out after `yggdrasil` update

[role="_abstract"]
On hosts that have weak dependencies disabled and are configured to use the `yggdrasil` pull client, remote jobs can start failing due to timeouts after the `yggdrasil` package has been updated to version 0.4.z or later.
You can manually install the `foreman_ygg_migration` package to address the problem.

The pull-based transport configuration relies on the Yggdrasil service and differs based on the version of the `yggdrasil` package that is installed on the host.
For pull-based remote execution mode to work correctly after `yggdrasil` version 0.4.z is installed on the host, the Yggdrasil client configuration must be updated.
Installing the `foreman_ygg_migration` package on the host ensures that {Project} applies the required changes to Yggdrasil configuration.

On hosts with weak dependencies enabled, {Project} automatically installs the `foreman_ygg_migration` package.
No further steps are required.

On hosts with weak dependencies disabled, you must install the `foreman_ygg_migration` package manually.

.Procedure
. Determine which version of the `yggdrasil` package is installed on the host:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ rpm --query yggdrasil
----
. If your host has `yggdrasil` version 0.4.z or later installed, the `yggdrasil` and `com.redhat.Yggdrasil1.Worker1.foreman` services are expected to be running.
Check the status of these services:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl status yggdrasil com.redhat.Yggdrasil1.Worker1.foreman
----
+
If the above services are not running, it means that Yggdrasil might not be configured correctly.
. Install the `foreman_ygg_migration` package manually:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# dnf install foreman_ygg_migration
----
+
Installing `foreman_ygg_migration` ensures that {Project} applies the required Yggdrasil configuration changes and enables remote execution in pull mode to work as expected.

.Verification
. Check the status of the Yggdrasil services again:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl status yggdrasil com.redhat.Yggdrasil1.Worker1.foreman
----
+
These services should now be running.
