:_mod-docs-content-type: PROCEDURE

[id="deploying-insights-by-using-the-ansible-role"]
= Deploying {Insights} by using the Ansible role

[role="_abstract"]
The *RedHatInsights.insights-client* Ansible role is used to automate the installation and registration of hosts with {Insights}.

.Procedure
. Add the *RedHatInsights.insights-client* role to the hosts.
For more information, see {ManagingConfigurationsAnsibleDocURL}Using_Ansible_Roles_to_Automate_Repetitive_Tasks_on_Clients_ansible[Using Ansible roles to automate repetitive tasks on clients in _{ManagingConfigurationsAnsibleDocTitle}_].
. To run the *RedHatInsights.insights-client* role on your host, navigate to *Hosts* > *All Hosts* and click the name of the host that you want to use.
. On the host details page, expand the *Schedule a job* dropdown menu.
. Click *Run Ansible roles*.

.Additional resources
* {ManagingConfigurationsAnsibleDocURL}Getting_Started_with_Ansible_in_{project-context}_ansible[Getting started with Ansible in {Project} in _{ManagingConfigurationsAnsibleDocTitle}_]
