[id="disabling-dns-for-integration_{context}"]
= Disabling DNS for integration

// MARC: New module. Content is based on https://github.com/theforeman/foreman-documentation/blob/master/guides/common/modules/proc_disabling-dns-dhcp-tftp-for-unmanaged-networks.adoc, and adjusted for DNS.
// Needs to be checked if it is technically correct.

If you want to manually manage a DNS service, you must prevent {Project} from maintaining this service on the operating system and disable orchestration to avoid errors.

[NOTE]
====
Disabling DNS in {Project} does not remove the related backend service on the operating system.
====

.Procedure

. On {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-proxy-dns false
----

. In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets* and select a subnet.

. Click the *{SmartProxies}* tab and clear the *Reverse DNS {SmartProxy}* field.

. Navigate to *Infrastructure* > *Domains* and select a domain.

. Clear the *DNS {SmartProxy}* field.

[NOTE]
====
{Project} does not perform orchestration when a {SmartProxy} is not set for a given subnet and domain.
When enabling or disabling {SmartProxy} associations, orchestration commands for existing hosts can fail if the expected records and configuration files are not present.
When associating a {SmartProxy} to turn orchestration on, ensure the required DHCP, DNS records, and TFTP files are in place for the existing {Project} hosts in order to prevent host deletion failures in the future.
====

