:_mod-docs-content-type: PROCEDURE

[id="migrating-from-hosted-to-in-{project-context}-{insights-id}"]
= Migrating from hosted to in-{Project} {Insights}

[role="_abstract"]
Migrate from hosted {Insights} to {insights-iop} when you need local analysis on your {ProjectServer} without sending host data to the {RHCloud}.

.Procedure
. On {ProjectServer}, enable {insights-iop}:
ifdef::containerized[]
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foremanctl} deploy --add-feature iop
----
endif::[]
ifndef::containerized[]
** If {insights-iop} was previously enabled:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --iop-ensure present
----
** If {insights-iop} was not previously enabled:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --enable-iop
----
endif::[]
. On your hosts, re-register the Insights client:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# insights-client --register
----
+
You can use remote execution to run this command on your hosts.

.Verification
. Verify that the *{Insights}* submenu in the {ProjectWebUI} no longer shows the *Inventory Upload* menu item and shows the *Vulnerability* menu item.
. Verify that the same recommendations appear for your hosts as before.

.Additional resources
* {ManagingHostsDocURL}configuring-and-setting-up-remote-jobs[Configuring and setting up remote jobs in _{ManagingHostsDocTitle}_]
