[id="{context}_creating_an_application_instance"]
= Creating an Application Instance

You can create xref:{context}_application_instances[application instances] as a blueprint for users to provision and configure hosts.

.Procedure
. In the {ProjectWebUI}, navigate to *Application > App Instances* and click the *New Application Instance* button.
. In the *Name* field, enter the name of the new application instance.
. Optional: In the *Description* field, enter an arbitrary description.
. From the *Application Definition* menu, select an existing application definition.
. In the table, connect the hosts and necessary services.
You can either assign existing hosts to your application instance or deploy new hosts.
.. To assign an existing host to a service, click on the *Server* icon.
Select both a service and existing host, and click *Save*.
.. Optional: Click the *A* character to edit, add, lock, or delete Ansible group variables.
Note that you cannot change host parameters as existing hosts are not redeployed but only reconfigured using Ansible.
.. Alternatively, in the *Hostname* field, enter a unique name for the host.
You can enter lowercase characters, digits, and hyphens.
Hosts cannot start with a hyphen.
.. In the *Description* field, enter a description.
.. From the *Service* menu, choose a service from the selected application definition.
Refer to the list of services in the top right corner.
.. In the *Actions* column,
... click the *edit* icon to edit an entry;
... click the *settings* icon to add or edit existing {ProjectName} parameters.
Every hierarchy level of {ProjectName} parameters can be overwritten.
... Click the *A* character to edit, add, lock, or delete Ansible group variables.
+
You can refer to any {Project} parameter using `PARAM[_name_of_your_parameter_]`, for example, based on an operating system or a host group.
The {Project} parameter name cannot contain whitespace.
+
When the host is configured, ACD gets the value for the variable `_name_of_your_parameter_`.
When you deploy your application instance or reconfigure it afterwards, navigate to the *Preview templates* tab to check if the parameters are resolved correctly.
... Click the *delete* icon to delete an entry.
. Click the *A* character to view and edit the corresponding Ansible group variables.
You may edit unlocked values.
. Click *Submit* to save your application instance.
