[id="Enabling_the_Client_Repository_{context}"]
= Enabling the {project-client-name} Repository

ifdef::foreman-el,katello[]
You require the Katello plug-in to complete this procedure.
endif::[]

The {project-client-name} repository provides the `katello-agent`, `katello-host-tools`, and `puppet` packages for clients registered to {ProjectServer}.

To use the CLI instead of the {ProjectWebUI}, see the xref:CLI_Enabling_the_Client_Repository_{context}[].

ifeval::["{mode}" == "disconnected"]
.Prerequisites
* Ensure that you import all content ISO images that you require into {ProjectServer}.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Red Hat Repositories*.
. Use the Search field to enter the following repository name: *{project-client-name} (for RHEL 7 Server) (RPMs)*.
. In the Available Repositories pane, click on *{project-client-name} (for RHEL 7 Server) (RPMs)* to expand the repository set.
+
If the *{project-client-name}* items are not visible, it may be because they are not included in the Red{nbsp}Hat Subscription Manifest obtained from the Customer Portal.
To correct that, log in to the Customer Portal, add these repositories, download the Red{nbsp}Hat Subscription Manifest and import it into {Project}.
For more information, see {ContentManagementDocURL}Managing_Red_Hat_Subscriptions_content-management[Managing Red Hat Subscriptions] in _{ContentManagementDocTitle}_.

. For the `x86_64` entry, click the *Enable* icon to enable the repository.

Enable the {project-client-name} repository for every supported major version of {RHEL} running on your hosts.
After enabling a Red Hat repository, a Product for this repository is automatically created.

[id="CLI_Enabling_the_Client_Repository_{context}"]
.CLI procedure
* Enable the {project-client-name} repository using the `hammer repository-set enable` command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository-set enable \
--basearch='x86_64' \
--name 'Red Hat {project-client-name} (for RHEL 7 Server) (RPMs)' \
--organization _"My_Organization"_ \
--product 'Red Hat Enterprise Linux Server'
----
