:_mod-docs-content-type: PROCEDURE

[id="downloading-files-to-a-host-from-a-python-repository-by-using-cli"]
= Downloading files to a host from a Python repository by using Hammer CLI

[role="_abstract"]
You can download files to a host from a Python repository in {Project} over HTTP or HTTPS.
Use Hammer CLI to copy the *Published At* URL of the Python repository.

.Prerequisites
* You have a Python repository.
* You know the name of the Python package you want to download to clients from the Python repository.
* To download the Python packages over HTTPS to your hosts, you require:
** The `katello-server-ca.crt`.
For more information, see {ConfiguringUserAuthenticationDocURL}importing-the-katello-root-ca-certificate-by-using-command-line[Importing the Katello root CA certificate by using command line] in _{ConfiguringUserAuthenticationDocTitle}_.
** An Organization Debug Certificate.
For more information, see {ManagingOrganizationsLocationsDocURL}Creating_an_Organization_Debug_Certificate_managing-organizations-locations[Creating an Organization Debug Certificate] in _{ManagingOrganizationsLocationsDocTitle}_.

.Procedure
. List all Python repositories:
+
[options="nowrap" subs="+quotes"]
----
$ hammer repository list --content-type python
----
. View the repository information:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
$ hammer repository info \
--name "_My_Python_Repository_" \
--organization-id _My_Organization_ID_ \
--product "__My_{customproductFirstCap}__"
----
include::snip_step-downloading-file-from-server.adoc[]
