[id="Configuring_FreeIPA_Authentication_on_Server_{context}"]
= Configuring the {FreeIPA} authentication source on {ProjectServer}

Enable {FreeIPA} users access to {Project} by configuring {aIPA} authentication provider on your {ProjectServer}.

.Prerequisites

* The system on which {ProjectServer} is running must be enrolled in the {FreeIPA} domain.

.Procedure

. Set {IPA} as the authentication provider for {Project}.
Specify the {Project} resources you want {IPA} users to access.
For example:
** To enable access to the {ProjectWebUI} but not the {Project} API:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--foreman-ipa-authentication=true
----
** To enable access to the {ProjectWebUI} and the {Project} API:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--foreman-ipa-authentication-api=true \
--foreman-ipa-authentication=true
----
+
[WARNING]
====
Enabling access to both the {ProjectWebUI} and the {Project} API poses a security risk.
After {aIPA} user receives a Kerberos ticket-granting ticket (TGT) by entering `kinit _user_name_`, an attacker can obtain an API session.
The attack is possible even if the user did not previously enter the {Project} login credentials anywhere, for example in the browser.
====
. Restart {Project} services:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service restart
----

.Verification

* As {aIPA} user, log in to {Project}.
// This might be a good place to link to the IPA authentication procedures currently included in Admin Project.
