:_mod-docs-content-type: PROCEDURE

[id="customize-default-values-of-ansible-variables-by-using-web-ui"]
= Customize default values of Ansible variables by using {ProjectWebUI}

[role="_abstract"]
You can set custom default values of Ansible variables in {Project} by using {ProjectWebUI}.
Global custom values help you define a baseline for your environment.

.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_director_variable_overrides`, `destroy_ansible_director_variable_overrides`, `destroy_ansible_variables`, `edit_ansible_director_variable_overrides`, `edit_ansible_director_variables`, `view_ansible_content`, `view_ansible_director_variable_overrides`, `view_ansible_director_variables`, and `view_organizations` permissions.
* Your {Project} contains imported Ansible content.

.Procedure
. In the {ProjectWebUI}, navigate to *Ansible* > *Content*.
. From the list of Ansible content, select a version.
. Select an Ansible role.
. Click the *Edit* icon.
. If you want to change the type of the variable, in the *Data type* field, select a different type.
. If you want to change the value of the variable, on the *Visual mode* or *Raw YAML* tab, enter the new value.
+
For lists, you can use drag and drop to reorder items.
For more complex values, paste your value into the *Raw YAML* tab.
. Click *Confirm* to submit your change to {Project}.

.Verification
. In the {ProjectWebUI}, navigate to *Ansible* > *Content*.
. From the list of Ansible content, select a version.
. Select an Ansible role.
. Verify that {Project} contains your custom default type and value.

.Additional resources
* xref:types-of-overrides[]
* xref:ansible-variable-precedence[]
