:_mod-docs-content-type: PROCEDURE

[id="changing-the-default-mirroring-policy"]
= Changing the default mirroring policy

You can set the default mirroring policy that {Project} applies to repositories that you create in all organizations.

Depending on whether it is a Yum or non-Yum {customrepo}, {Project} uses separate settings.
Only Yum repositories support the `mirror_complete` mirroring policy.
Red Hat repositories use `mirror_complete` by default and are unaffected by these settings.
Changing the default value does not change existing settings.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. Click the *Content* tab.
. Change the default mirroring policy depending on your requirements:
+
* To change the default mirroring policy for a Yum {customrepo}, change the value of the *Default custom yum repository mirroring policy* setting.
* To change the default mirroring policy for a non-Yum {customrepo}, change the value of the *Default custom non-yum repository mirroring policy* setting.

.CLI procedure
* To change the default mirroring policy for a Yum {customrepo} to one of `additive`, `mirror_content_only`, or `mirror_complete`, enter the following command:
+
[subs="+quotes"]
----
$ hammer settings set \
--name default_yum_mirroring_policy \
--value _mirror_complete_
----

* To change the default mirroring policy for a non-Yum {customrepo} to one of `additive` or `mirror_content_only`, enter the following command:
+
[subs="+quotes"]
----
$ hammer settings set \
--name default_non_yum_mirroring_policy \
--value _mirror_content_only_
----
