[id="installing-flatpak-applications-on-{project-context}-hosts"]
= Installing Flatpak applications on {Project} hosts

Use the command line to install selected applications from the enabled Flatpak remotes.

.Prerequisites
* Install Flatpak.
ifdef::satellite[]
* Enable the {Team} Flatpak remote.
endif::[]

.Procedure
. On the managed host, add your {ProjectServer} as a Flatpak remote:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ flatpak remote-add --authenticator-name=org.flatpak.Authenticator.Oci katello oci+https://_{foreman-example-com}_/
----
. Log in using Podman:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ podman login
----
. Install your application.
For example, to install the Mozilla Firefox Flatpak:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ flatpak install firefox
----

.Additional resources
* For more information about launching Flatpak applications, see {RHELDocsBaseURL}9/html/administering_the_system_using_the_gnome_desktop_environment/assembly_installing-applications-using-flatpak_administering-the-system-using-the-gnome-desktop-environment#launching-flatpak-applications_assembly_installing-applications-using-flatpak[Launching Flatpak applications].
* For more information about updating Flatpak applications, see {RHELDocsBaseURL}9/html/administering_the_system_using_the_gnome_desktop_environment/assembly_installing-applications-using-flatpak_administering-the-system-using-the-gnome-desktop-environment#updating-flatpak-applications_assembly_installing-applications-using-flatpak[Updating Flatpak applications].
