:_mod-docs-content-type: PROCEDURE

[id="excluding-hosts-from-{insights-id}-analytics_{context}"]
= Excluding hosts from {Insights} analytics

[role="_abstract"]
You can exclude hosts from {Insights} analytics.

You can use the following
ifdef::insights-in-cloud[]
parameters:
endif::[]
ifndef::insights-in-cloud[]
parameter:
endif::[]

`host_registration_insights`::
Setting this parameter to `false` will prevent {ProjectServer} from forwarding requests from Insights client on hosts.
The Insights client will not be installed on newly registered hosts.

ifdef::insights-in-cloud[]
`host_registration_insights_inventory`::
Setting this parameter to `false` will exclude the host from the {Project} host inventory that is uploaded to the {RHCloud}.
+
If you exclude a host that is already reported on the https://console.redhat.com/[{RHCloud}], it will be still removed automatically from the inventory.
However, this process can take some time to complete.
endif::[]

You can set
ifdef::insights-in-cloud[]
these parameters
endif::[]
ifndef::insights-in-cloud[]
this parameter
endif::[]
at any level.
For more information, see xref:Host_Parameter_Hierarchy_managing-hosts[].

.Procedure
. In the {ProjectWebUI}, navigate to *Host* > *All Hosts*.
. Select the host you want to exclude from {Insights} analytics.
. On the *Parameters* tab, click the edit button next to `host_registration_insights`.
. Set the value to *False*.
. Click *Submit* to save the parameter.
ifdef::insights-in-cloud[]
. Click the edit button next to `host_registration_insights_inventory`.
. Set the value to *False*.
. Click *Submit* to save the parameter.
endif::[]
