:_mod-docs-content-type: PROCEDURE

[id="creating-a-virt-who-configuration-by-using-web-ui_{context}"]
= Creating a virt-who configuration by using the {ProjectWebUI}

[role="_abstract"]
You can create a virt-who configuration for {provider} by using the {ProjectWebUI}.

The virt-who configuration creates a `virt_who_reporter_1` user with the `Virt-who Reporter` role, which provides minimal permissions for virt-who reporting to {ProjectServer}.
This user cannot be manually configured or used to log in to {ProjectServer}.

Local configuration values are stored in the `/etc/virt-who.d/_conf_name_.conf` file.
These values apply only to the hypervisor.

Global configuration values are stored in the `/etc/sysconfig/virt-who` file
These values, which include `Interval`, `Enable debugging output`, `HTTP Proxy`, and `Ignore Proxy`, apply to all virt-who configurations on the same server.
Redeploying a virt-who configuration on the same server overwrites these values.

.Prerequisites
* You have imported a subscription manifest that includes a host-based subscription into {ProjectServer}.
For more information, see xref:checking-for-subscriptions-that-require-virt-who_virt-who-vm-subs[].

ifdef::vmware-virt-who[]
* You have created a virt-who user with read-only access to all objects in the vCenter Data Center and a non-expiring password on the vCenter Server.
endif::[]

ifdef::kvm-virt-who,hyperv-virt-who,openstack-virt-who[]
* You have created a virt-who user with read-only access and a non-expiring password on the hypervisor.
endif::[]

ifdef::kubevirt-virt-who[]
* You have created a `kubeconfig` file.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Virt-who Configurations*.
. Click *Create Config*.
. Complete the following fields:
* *Name*: Configuration name.
* *Hypervisor Type*: Select *{hypervisor-ui}*.
ifdef::vmware-virt-who,hyper-virt-who[]
* *Hypervisor Server*: FQDN or IP address.
* *Hypervisor Username*: virt-who user name.
* *Hypervisor Password*: virt-who user password.
The password is encrypted when you deploy the configuration.
endif::[]
* *Interval*: Virtual machine information reporting interval.
* *{ProjectServer} FQDN*.
* *Hypervisor ID*: Select *Hostname* or *UUID*.

. Optional: *Filtering*. Select one of the following options for querying hypervisors:
* *Unlimited* (default): All hypervisors are queried.
* *Whitelist*: Specific hypervisors are included.
* *Blacklist*: Specific hypervisors are excluded.
** *Filter hosts*: Comma-separated list of included hypervisors.
** *Exclude hosts*: Comma-separated list of excluded hypervisors.
+
--
Specify the host name or UUID according to the hypervisor ID you selected.

[NOTE]
====
Follow these guidelines for host names:

* You can use wildcards, regular expressions, and special characters in the host name.
* If you use regular expressions, you must escape the backslashes.
* If you use special characters, you must enclose the host name in quotation marks.
--
ifdef::vmware-virt-who[]
* *Filter host parents*: Comma-separated list of included cluster IDs.
* *Exclude host parents*: Comma-separated list of excluded cluster IDs.
ifdef::satellite[]
For more information, see link:https://access.redhat.com/solutions/5696481[Using the "Filter Host Parents" and "Exclude Host Parents" Attributes with VMware Clusters] in the _Red{nbsp}Hat Knowledgebase_.
====
endif::[]
endif::[]

. You can configure the following logging and proxy options:
* *Enable debugging output*: Enables debug logging for virt-who.
* *HTTP Proxy*.
Example: `http://_proxy.example.com_:3128`.
+
To use no proxy, leave this field blank; this has the same result as entering `{asterisk}` in the *Ignore Proxy* field.
* *Ignore Proxy*: Comma-separated list of host names, IP addresses, or domains to bypass existing proxy settings.
ifdef::kubevirt-virt-who[]
. Enter the `kubeconfig` file path.
endif::[]
ifdef::nutanix-virt-who[]
. Select *Prism Central* or *Prism Element* from the *Prism Flavor* list.
. Optional: *Enable AHV Debug*: Enables AHV internal debugging.
This option provides additional AHV information when you enable both debugging options.
endif::[]

. Click *Submit*.
