:_mod-docs-content-type: PROCEDURE

[id="adding-vmware-images-to-server-by-using-web-ui_{context}"]
= Adding VMware images to {ProjectServer} by using {ProjectWebUI}

[role="_abstract"]
VMware vSphere uses templates as images for creating new virtual machines.
If using image-based provisioning to create new hosts, you need to add VMware template details to your {ProjectServer}.
This includes access details and the template name.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources*.
. Select your VMware compute resource.
. Click *Create Image*.
. In the *Name* field, enter a name for the image.
. From the *Operating System* list, select the base operating system of the image.
. From the *Architecture* list, select the operating system architecture.
. In the *Username* field, enter the SSH user name for image access.
By default, this is set to `root`.
. If your image supports user data input such as `cloud-init` data, click the *User data* checkbox.
. Optional: In the *Password* field, enter the SSH password to access the image.
. From the *Image* list, select an image from VMware.
. Click *Submit* to save the image details.
