[id="Viewing_installable_errata_{context}"]
= Viewing Installable Errata

Use the following procedure to view a list of installable errata and select errata to install.
.Procedure

. In the {ProjectWebUI}, navigate to *Hosts > All Hosts* and select the host you require.
. If there are errata associated with the host they are displayed in an Installable Errata card on the new Host page.
. On the new Host page, select the *Content* tab.
. On the Content page select the *Errata* tab.
. The page displays installable errata for the chosen host.
. Click the checkbox for any errata you wish to install.
. Using the three dots icon of the errata you want to install, select *Apply via Katello agent* if UNKNOWN, *Apply via Remote Execution* if UNKNOWN, or *Apply via customized remote execution* if UNKNOWN.
. Click *Submit*.

Alternatively

. In the {ProjectWebUI}, navigate to *Hosts > All Hosts* and select the host you require.
. If there are errata associated with the host they are displayed in an *Installable Errata* card on the new Host page.
. Click on the number of Installable Errata.
. The *Content Hosts* page for the selected host displays errata associated with the host.
. Click the check box for any errata you want to install and choose *Apply Selected*.
. Select *Apply via Katello agent* if UNKNOWN, *Apply via Remote Execution* if UNKNOWN, or *Apply via customized remote execution* if UNKNOWN.
. Click *Submit*.
