:_mod-docs-content-type: PROCEDURE

[id="running-the-{project-context}-deployment-utility"]
= Running the {Project} deployment utility

[role="_abstract"]
Install the required packages and run the {Project} deployment utility.

.Procedure
ifndef::foremanctl[]
. Upgrade all packages:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-upgrade}
----
. Install {project-installer-package}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install} {project-installer-package}
----
. Run the {Project} installer:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {installer-scenario}
----
+
The {foreman-installer} installer is a collection of Puppet modules that installs {Project} based on native operating system packages.
+
The installation run is non-interactive by default.
The script displays its progress and writes logs to `{installer-log-file}`.
+
For a list of the available customization options, run `{foreman-installer} --help` or `{foreman-installer} --full-help`.
endif::[]
ifdef::foremanctl[]
. Upgrade all packages:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-upgrade}
----
. Install the `foremanctl` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf install foremanctl
----
. Deploy the configuration on your server:
+
[options="nowrap" subs="+quotes,attributes"]
----
# foremanctl deploy
----
+
You can find credentials to access your {ProjectServer} in the message shown in the `TASK [post_install : Admin credentials]` task results.
+
For a list of available options, run `foremanctl --help`.
endif::[]
