:_mod-docs-content-type: PROCEDURE

[id="viewing-service-logs"]
= Viewing service logs

[role="_abstract"]
You can view and filter logs for any {Project} service by using `journalctl` with the appropriate unit filter.
Use correlation IDs to trace a single request across multiple services such as Foreman and Pulp.

.Prerequisites
* {ProjectServer} is installed and running.
* You have root access to the {ProjectServer} host.

.Procedure
* To view logs for a specific service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl --unit _<service_name>_
----
* To follow log output in real time, add the `-f` flag:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl --follow --unit _<service_name>_
----
+
For example:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl --follow --unit foreman
Aug 10 07:19:29 {foreman-example-com} foreman[1632]: 2026-08-10T07:19:29 [I|app|eb515c9c] Started GET "/api/v2/ping" for 192.168.124.1
Aug 10 07:19:29 {foreman-example-com} foreman[1632]: 2026-08-10T07:19:29 [I|app|eb515c9c] Processing by Api::V2::PingController#ping as JSON
Aug 10 07:19:29 {foreman-example-com} foreman[1632]: 2026-08-10T07:19:29 [I|app|eb515c9c] Completed 200 OK in 186ms (Views: 12.8ms | ActiveRecord: 8.1ms | Allocations: 42460)
----
+
In this output, `eb515c9c` is the correlation ID.

* To trace a request across services, locate the correlation ID in the log output and filter by it:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl --grep _<correlation_ID>_
----
+
For example:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl --grep eb515c9c
Aug 10 07:19:29 {foreman-example-com} foreman[1632]: 2026-08-10T07:19:29 [I|app|eb515c9c] Started GET "/api/v2/ping" for 192.168.124.1
Aug 10 07:19:29 {foreman-example-com} foreman[1632]: 2026-08-10T07:19:29 [I|app|eb515c9c] Processing by Api::V2::PingController#ping as JSON
Aug 10 07:19:29 {foreman-example-com} pulp-api[1193]: pulp [eb515c9c-cb85-44fa-bd6e-c49eaab71bc5]: "GET /pulp/api/v3/status/ HTTP/1.1" 200 6250
Aug 10 07:19:29 {foreman-example-com} foreman[1632]: 2026-08-10T07:19:29 [I|app|eb515c9c] Completed 200 OK in 186ms (Views: 12.8ms | ActiveRecord: 8.1ms | Allocations: 42460)
----

.Verification
* Verify that the command returns log entries for the expected service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl --unit _<service_name>_ -n 5
----

.Additional resources
ifdef::satellite[]
* {RHELDocsBaseURL}9/html-single/configuring_basic_system_settings/index#viewing-logs-using-the-command-line_assembly_troubleshooting-problems-using-log-files[Viewing logs using the command line in _{RHEL}{nbsp}9 Configuring basic system settings_]
endif::[]
