[id="creating-hardware-models_{context}"]
= Creating Hardware Models

ifndef::orcharhino[]
Use this procedure to create a hardware model in {Project} so that you can specify which hardware model a host uses.
endif::[]
ifdef::orcharhino[]
Use this procedure to create a xref:sources/management_ui/the_hosts_menu/hardware_models.adoc[hardware model] in {Project} so that you can specify which hardware model a host uses.
endif::[]

.Procedure

. In the {ProjectWebUI}, navigate to *Hosts* > *Hardware Models* and click *Create Model*.
. In the *Name* field, enter a name for the hardware model.
. Optionally, in the *Hardware Model* and *Vendor Class* fields, you can enter corresponding information for your system.
. In the *Info* field, enter a description of the hardware model.
. Click *Submit* to save your hardware model.

.CLI procedure

* Create a hardware model using the `hammer model create` command.
The only required parameter is `--name`.
Optionally, enter the hardware model with the `--hardware-model` option, a vendor class with the `--vendor-class` option, and a description with the `--info` option:
+
[options="nowrap" subs="+quotes"]
----
# hammer model create --name "_model_name_" --info "_description_" \
--hardware-model "_hardware_model_" --vendor-class "_vendor_class_"
----
