:_mod-docs-content-type: PROCEDURE

[id="provisioning-from-a-builder-image-on-{smart-proxy-context}"]
= Provisioning from a {LoraxCompose} image on {SmartProxy}

You can upload a {LoraxCompose} image to {Project} and use this image to provision hosts by using network boot.

ifndef::satellite[]
[NOTE]
====
This feature is available for {EL} hosts only.
====
endif::[]

When you provision from a {LoraxCompose} image, Anaconda installer partitions disks, downloads and mounts the image, and copies files over to a host.

.Prerequisites
* An existing TAR image created by using {LoraxCompose} in {the-Cockpit}.
Ensure that your blueprint to build the image includes the xref:packages-required-in-a-builder-image[required packages].
* If you want to use {SmartProxyServer} URL, then the referenced lifecycle environment, such as Library, must be synchronized to that {SmartProxyServer}.
For more information, see {InstallingSmartProxyDocURL}Adding_Lifecycle_Environments_{smart-proxy-context}[Adding lifecycle environments to {SmartProxyServers}] in _{InstallingSmartProxyDocTitle}_.

.Procedure
. On {Project}, create a {customproduct}, add a {customfiletype} repository to this product, and upload the image to the repository.
For more information, see {ContentManagementDocURL}Importing_Individual_ISO_Images_and_Files_content-management[Importing individual ISO images and files] in _{ContentManagementDocTitle}_.
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*.
. Select the host group that you want to use.
. Click the *Parameters* tab, and then click *Add Parameter*.
. Create a parameter named `kickstart_liveimg` with type *string* and set the value to the full URL of the image location or the file name of the image inside a published content view, for example:
* Full URL: `https://_{smartproxy-example-com}_/pulp/content/_My_Organization_Label_/Library/custom/_My_Product_Label_/_My_Repository_Label_/_My_Image_Name_.tar`
* Image file name: `_My_Image_Name_.tar`
+
You can use the image file name only if the host is subscribed to a single content view and lifecycle environment, and the `kt_activation_keys` parameter is defined for the host.
The content view must be published.
+
If a content source is assigned to the host, {Project} will use the hostname of the content source {SmartProxy} of the host.
If a content source is not assigned, {Project} will use the hostname of {ProjectServer}.
. Click *Submit* to save your changes.

.Additional resources
* xref:using-network-boot-to-provision-hosts[]
