[id="Configuring_Project_to_Use_LDAP_{context}"]
= Configuring {Project} to use LDAP

Configure an LDAP authentication source for {Project}.

.Procedure
. Set the Network Information System (NIS) service boolean to true to prevent SELinux from stopping outgoing LDAP connections:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# setsebool -P nis_enabled on
----
// Where do I run this cmd? ProjectServer?
. In the {ProjectWebUI}, navigate to *Administer* > *Authentication Sources*.
. From the *LDAP* menu, select *Create*.
.. On the *LDAP server* tab, enter the details of your LDAP server.
+
For TLS encrypted connections, select *LDAPS* to enable encryption.
Selecting *LDAPS* changes the default port in {ProjectWebUI} to `636`, which is the default for LDAPS.
.. On the *Account* tab, enter the account information and domain name details.
.. On the *Attribute mappings* tab, map LDAP attributes to {Project} attributes.
.. On the *Locations* tab, select the locations you want {Project} to assign to users created from the LDAP authentication source.
These locations will be available to users after they first log in.
.. On the *Organizations* tab, select the organizations you want {Project} to assign to users created from the LDAP authentication source.
These locations will be available to users after they first log in.
. Click *Submit*.

.Next steps
* If you did not select *Automatically Create Accounts In {Project}* on the *Account* tab, create user accounts manually.
For more information, see {AdministeringDocURL}Creating_a_User_admin[Creating a User] in _{AdministeringDocTitle}_.
* If you selected *Automatically Create Accounts In {Project}*, LDAP users can now log in to {Project} using their LDAP accounts and passwords.
* After users log in for the first time, the {Project} administrator must assign roles to them manually.
For more information about assigning appropriate roles to user accounts, see {AdministeringDocURL}Assigning_Roles_to_a_User_admin[Assigning Roles to a User] in _{AdministeringDocTitle}_.
