:_mod-docs-content-type: PROCEDURE

[id="configuring-custom-alternate-contents-sources-by-using-cli"]
= Configuring custom alternate content sources by using Hammer CLI

[role="_abstract"]
You can configure custom alternate content sources (ACS) to define alternate paths to download content during synchronization.

.Prerequisites
* If the repository requires SSL authentication, import the SSL certificate and key into {Project}.
For more information, see {ContentManagementDocURL}importing-custom-ssl-certificates-by-using-web-ui[Importing custom SSL certificates by using {ProjectWebUI}] in _{ContentManagementDocTitle}_.
* Note that the alternate content source paths consist of a base URL appended with the subpaths that you provide.
For example, if your base URL is `\https://{server-example-com}` and your subpaths are `rhel7/` and `rhel8/`, then both `\https://{server-example-com}/rhel7/` and `\https://{server-example-com}/rhel8/` will be searched.

.Procedure
. Configure a custom alternate content source:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer alternate-content-source create \
--alternate-content-source-type custom \
--base-url "_https://local-repo.example.com:port_" \
--name "_My_ACS_Name_" \
--smart-proxy-ids __My_{smart-proxy-context-titlecase}_ID__
----
. Check if the newly created alternate content source is listed:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer alternate-content-source list
----
. Refresh the alternate content source:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer alternate-content-source refresh --id _My_Alternate_Content_Source_ID_
----
. Add the {SmartProxies} to which the alternate content source is to be synced:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer alternate-content-source update \
--id _My_Alternate_Content_Source_ID_ \
--smart-proxy-ids __My_{smart-proxy-context-titlecase}_ID__
----
. Refresh the alternate content sources:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer alternate-content-source refresh --id _My_Alternate_Content_Source_ID_
----
