:_mod-docs-content-type: PROCEDURE

[id="adding-a-default-http-proxy-by-using-cli"]
= Adding a default HTTP proxy by using Hammer CLI

[role="_abstract"]
If your network uses an HTTP Proxy, you can configure {ProjectServer} to use an HTTP proxy for requests to the Red{nbsp}Hat Content Delivery Network (CDN) or another content source.
Use the FQDN instead of the IP address where possible to avoid losing connectivity because of network changes.

The following procedure configures an HTTP proxy only for downloading content for {Project}.

.Procedure
. Verify that the `http_proxy`, `https_proxy`, and `no_proxy` variables are not set:
+
[options="nowrap"]
----
# unset http_proxy https_proxy no_proxy
----
ifdef::katello,orcharhino,satellite[]
. Add an HTTP proxy entry to {Project} and set the HTTP proxy as default for content synchronization:
+
[options="nowrap" subs="+quotes"]
----
$ hammer http-proxy create \
--name=_My_HTTP_Proxy_ \
--username=_My_HTTP_Proxy_User_Name_ \
--password=_My_HTTP_Proxy_Password_ \
--url http://_http-proxy.example.com_:8080 \
--content-default-http-proxy true
----
endif::[]
ifndef::katello,orcharhino,satellite[]
. Add an HTTP proxy entry to {Project}:
+
[options="nowrap" subs="+quotes"]
----
$ hammer http-proxy create \
--name=_My_HTTP_Proxy_ \
--username=_My_HTTP_Proxy_User_Name_ \
--password=_My_HTTP_Proxy_Password_ \
--url http://_http-proxy.example.com_:8080
----
endif::[]
