:_mod-docs-content-type: PROCEDURE

[id="create-an-ansible-lifecycle-environment-path-by-using-web-ui"]
= Create an Ansible lifecycle environment path by using {ProjectWebUI}

[role="_abstract"]
You can create an Ansible lifecycle environment path by using {ProjectWebUI}.
Similar to content management, Ansible lifecycle environment paths allow you to develop, test, and run the same Ansible content in production in different versions.

.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_lifecycle_environment_paths`, `edit_ansible_lifecycle_environment_paths`, `view_ansible_content`, `view_ansible_lifecycle_environment_paths`, `view_ansible_lifecycle_environments`, and `view_organizations` permissions.

.Procedure
. In the {ProjectWebUI}, navigate to *Ansible* > *Environments*.
. Click *Create lifecycle environment path*.
. In the *Unnamed LCE Path* field, click the *Edit* icon.
. Enter a name for your lifecycle environment path and click the *Save* icon.
. Click *Confirm* to rename your lifecycle environment path.

.Verification
. In the {ProjectWebUI}, navigate to *Ansible* > *Environments*.
. Verify that {Project} shows your newly created lifecycle environment path.
