[id="Creating_a_Content_Filter_for_APT_Content_{context}"]
= Creating a Content Filter for APT Content

You can filter Content Views containing deb content to include or exclude specific packages or package groups.
Filters are based on a combination of the _name_ and the _architecture_.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-content-filter-apt_{context}[].

For examples of how to build a filter, see xref:Content_Filter_Examples_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content*{nbsp}>{nbsp}*Content Views* and select a Content View.
. On the *Filters* tab, click *Create filter*.
. Enter a name.
. From the *Content type* list, select a content type.
. From the *Inclusion Type* list, select either *Include filter* or *Exclude filter*.
. Optional: In the *Description* field, enter a description for the filter.
. Click *Create filter* to create your content filter.
. Depending on what you enter for *Content Type*, add rules to create the filter that you want.
. Select if you want the filter to *Apply to subset of repositories* or *Apply to all repositories*.
. Click *Publish New Version* to publish the filtered repository.
. Optional: In the *Description* field, enter a description of the changes.
. Click *Save* to publish a new version of the Content View.
+
You can promote this Content View across all environments.

[id="cli-creating-a-content-filter-apt_{context}"]
.CLI procedure
. Add a filter to the Content View.
Use the `--inclusion false` option to set the filter to an Exclude filter:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view filter create \
--content-view "_Example_Content_View_" \
--description "_My_Content_View_Filter_Description_" \
--inclusion false \
--name "_Errata Filter_" \
--organization "_My_Organization_" \
--type erratum
----
. Add a rule to the filter:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view filter rule create \
--content-view "_My_Content_View_" \
--content-view-filter "_My_Errata_Filter_" \
--date-type updated \
--organization "_My_Organization_" \
--start-date "_YYYY-MM-DD_" \
--types enhancement,bugfix
----
. Publish the Content View:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view publish \
--description "Adding errata filter" \
--name "_My_Content_View_" \
--organization "_My_Organization_"
----
. Promote the view across all environments:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view version promote \
--content-view "_Example_Content_View_" \
--organization "_My_Organization_" \
--to-lifecycle-environment "Development" \
--version 1
# hammer content-view version promote \
--content-view "_Example_Content_View_" \
--organization "_My_Organization_" \
--to-lifecycle-environment "Testing" \
--version 1
# hammer content-view version promote \
--content-view "_Example_Content_View_" \
--organization "_My_Organization_" \
--to-lifecycle-environment "Production" \
--version 1
----
