:_mod-docs-content-type: PROCEDURE

[id="creating-a-content-view-by-using-web-ui"]
= Creating a content view by using {ProjectWebUI}

[role="_abstract"]
Use this procedure to create a content view by using the {ProjectWebUI}.

While you can stipulate whether you want to resolve any package dependencies on a content view by content view basis, you might want to change the default {Project} settings to enable or disable package resolution for all content views.
For more information, see xref:Resolving_Package_Dependencies_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Content Views*.
. Click *Create content view*.
. In the *Name* field, enter a name for the view.
{Project} automatically completes the *Label* field from the name you enter.
. In the *Description* field, enter a description of the view.
. In the *Type* field, select a *Content view* or a *Composite content view*.
. Optional: If you want to solve dependencies automatically every time you publish this content view, select the *Solve dependencies* checkbox.
Dependency solving slows the publishing time and might ignore any content view filters you use.
This can also cause errors when resolving dependencies for errata.
. Click *Create content view*.
. On the *Repositories* tab, select the repository from the *Type* list that you want to add to your content view, select the checkbox next to the available repositories you want to add, then click *Add repositories*.
. Click *Publish new version* and in the *Description* field, enter information about the version to log changes.
. Optional: Enable a promotion path by clicking *Promote* and select one or more lifecycle environments to promote the new version to.
. Click *Next*.
. On the *Review details* page, review the environments you are trying to publish.
. Click *Finish*.

.Next steps
* To register a host to your content view, see {ManagingHostsDocURL}Registering_Hosts_by_Using_Global_Registration_managing-hosts[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_.
