:_mod-docs-content-type: PROCEDURE

[id="configuring-openvox-agent-on-a-project-host-manually"]
= Configuring OpenVox agent on a {Project} host manually

[role="_abstract"]
On {Project} hosts that are already registered, you can install and configure the OpenVox agent manually.
A configured OpenVox agent is required on the host for Puppet integration with your {Project}.

.Prerequisites
ifndef::managing-configurations-puppet[]
* Puppet must be enabled in your {Project}.
For more information, see {ManagingConfigurationsPuppetDocURL}[_{ManagingConfigurationsPuppetDocTitle}_].
endif::[]
* The host must have a Puppet environment assigned to it.
ifdef::satellite[]
+
* {project-client-name} OpenVox repository is synchronized on {ProjectServer}, available in the content view and the lifecycle environment of the host, and enabled for the host.
+
include::snip_openvox-client-repos.adoc[]
endif::[]
ifndef::satellite[]
* Ensure a repository containing the OpenVox agent is enabled on the host.
endif::[]

.Procedure
. Log in to the host as the `root` user.
ifdef::orcharhino[]
. Install the Puppet agent package:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install} puppet-agent
----
endif::[]
ifndef::orcharhino[]
. Install the OpenVox agent package.
* On hosts running {EL} 8 and above:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-el8} puppet-agent
----
ifdef::satellite[]
* On hosts running {EL} 7 and below:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-el7} puppet-agent
----
+
[NOTE]
====
The `openvox-agent` package, included in the OpenVox repository, provides the `puppet-agent` command, which is used to install the OpenVox agent.
====
endif::[]
endif::[]
ifndef::satellite,orcharhino[]
* On hosts running Debian:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-deb} puppet-agent
----
* On hosts running {SLES}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {client-package-install-sles} puppet-agent
----
endif::[]
. Add the OpenVox agent to `PATH` in your current shell using the following script:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
. /etc/profile.d/puppet-agent.sh
----
. Configure the OpenVox agent.
Set the `environment` parameter to the name of the Puppet environment to which the host belongs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet config set server _{foreman-example-com}_ --section agent
# puppet config set environment _My_Puppet_Environment_ --section agent
----
. Start the OpenVox agent service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet resource service puppet ensure=running enable=true
----
. Create a certificate for the host:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet ssl bootstrap
----
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*.
. From the list in the *Actions* column for the required {SmartProxyServer}, select *Certificates*.
. Click *Sign* to the right of the required host to sign the SSL certificate for the OpenVox agent.
. On the host, run the OpenVox agent again:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppet ssl bootstrap
----
