[id="Generating_a_Report_for_Installable_Errata_on_Content_Hosts_{context}"]
= Generating a Report for Installable Errata on Content Hosts

Use this procedure to generate a report for content hosts showing installable errata in *Report Templates*.

.Procedure
. In the {ProjectwebUI}, navigate to *Monitor* > *Report Templates*.
. To the right of *Host* - *Applicable Errata*, click *Generate*.
. Optional: To schedule a report, click the icon to the right of the *Generate at* field, and select the specific date and time for generating the report.
. Optional: To send a report to an e-mail address, select the *Send report via e-mail* checkbox, and in the *Deliver to e-mail addresses* field, enter the required e-mail address.
. Select your output format.
. Optional: Apply search query filters.
To view all available results, do not populate the filter field with any values.
. To filter errata or not, select your preferred installability option from the dropdown menu.
If necessary, refer to the tooltips for additional information on each section.
