:_mod-docs-content-type: PROCEDURE

[id="creating-hosts-with-uefi-http-boot-provisioning-by-using-web-ui"]
= Creating hosts with UEFI HTTP boot provisioning by using {ProjectWebUI}

[role="_abstract"]
You can provision hosts from {Project} by using the UEFI HTTP Boot if the hosts have this capability.
In HTTP boot, configuration files are transferred over HTTP instead of TFTP as in PXE boot.
Using this method can help reduce the booting time during host provisioning.
HTTP is also more reliable for transfer of large files, such as Live images, than TFTP.

You enter the host details on {ProjectServer} and boot your host.
{ProjectServer} automatically manages the HTTP boot configuration, organizes networking services, and provides the operating system and configuration for the host.

Create a host entry to add the host details.
When you save the host entry, {Project} creates the relevant provisioning settings.
This also includes creating the necessary directories and files for PXE booting.
When you boot the host, the host requests a DHCP lease.
The DHCP service responds with a lease which includes the location of the installation content.
The host uses the installation content to install the operating system.

ifdef::katello,satellite,orcharhino[]
During the installation, the host registers to {ProjectServer} by using the activation key, installs the necessary host management tools from the {project-client-name} repository, and performs initial configuration.
endif::[]
ifndef::katello,satellite,orcharhino[]
During the installation, the host registers to {ProjectServer} and performs initial configuration.
endif::[]

.Prerequisites
* Your {SmartProxy} has been configured for UEFI HTTP booting.
For more information, see xref:configuring-{smart-proxy-context}-for-uefi-http-booting[].

.Procedure
include::snip_steps-create-a-host-tab-host.adoc[]
include::snip_steps-create-a-host-tab-interfaces.adoc[]
. Click the *Operating System* tab, and verify that all fields contain values.
Confirm each aspect of the operating system.
. From the *PXE Loader* list, select *Grub2 UEFI HTTP*.
. Optional: Click *Resolve* in *Provisioning template* to check the new host can identify the right provisioning templates to use.
+
For more information about provisioning templates, see xref:provisioning-templates[].
ifdef::katello,satellite,orcharhino[]
include::snip_step-parameter-ak.adoc[]
endif::[]
. Click *Submit* to save the host details.
