[id="Creating_Hosts_with_PXE_less_Provisioning_{context}"]
= Creating Hosts with PXE-less Provisioning

Some hardware does not provide a PXE boot interface.
In {Project}, you can provision a host without PXE boot.
This is also known as PXE-less provisioning and involves generating a boot ISO that hosts can use.
Using this ISO, the host can connect to {ProjectServer}, boot the installation media, and install the operating system.

{Project} also provides a PXE-less discovery service that operates without PXE-based services, such as DHCP and TFTP.
For more information, see xref:Implementing_PXE_less_Discovery_{context}[].

.Boot ISO Types

There are the following types of boot ISOs:

ifndef::satellite[]
Host image::
A boot ISO for the specific host.
This image contains only the boot files that are necessary to access the installation media on {ProjectServer}.
The user defines the subnet data in {Project} and the image is created with static networking.
The image is based on iPXE boot firmware, only a limited number of network cards is supported.
endif::[]

Full host image::
A boot ISO that contains the kernel and initial RAM disk image for the specific host.
This image is useful if the host fails to chainload correctly.
The provisioning template still downloads from {ProjectServer}.

ifndef::satellite[]
Generic image::
A boot ISO that is not associated with a specific host.
The ISO sends the host's MAC address to {ProjectServer}, which matches it against the host entry.
The image does not store IP address details and requires access to a DHCP server on the network to bootstrap.
This image is also available from the `/bootdisk/disks/generic` URL on your {ProjectServer}, for example, `\https://{foreman-example-com}/bootdisk/disks/generic`.
endif::[]

Subnet image::
A boot ISO that is not associated with a specific host.
The ISO sends the host's MAC address to {SmartProxyServer}, which matches it against the host entry.
The image does not store IP address details and requires access to a DHCP server on the network to bootstrap.
This image is generic to all hosts with a provisioning NIC on the same subnet.
The image is based on iPXE boot firmware, only a limited number of network cards is supported.

[NOTE]
====
The *Full host image* is based on SYSLINUX and Grub and works with most network cards.
ifdef::satellite[]
When using a *Subnet image*,
endif::[]
ifndef::satellite[]
When using a *Host image*, *Generic image*, or *Subnet image*,
endif::[]
see https://ipxe.org/appnote/hardware_drivers[supported hardware on ipxe.org] for a list of network card drivers expected to work with an iPXE-based boot disk.
====

ifdef::satellite[]
*Full host image* contains a provisioning token, therefore the generated image has limited lifespan.
endif::[]
ifndef::satellite[]
*Host image* and *Full host image* contain provisioning tokens, therefore the generated image has limited lifespan.
endif::[]
For more information about configuring security tokens, read xref:Configuring_the_Security_Token_Validity_Duration_{context}[].

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-hosts-with-pxe-less-provisioning_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Create Host*.
. In the *Name* field, enter a name that you want to become the provisioned system's host name.
. Click the *Organization* and *Location* tabs and change the context to match your requirements.
. From the *Host Group* list, select a host group that you want to use to populate the form.
. Click the *Interface* tab, and on the host's interface, click *Edit*.
. Verify that the fields are populated with values.
Note in particular:
+
* The *Name* from the *Host* tab becomes the *DNS name*.
* {ProjectServer} automatically assigns an IP address for the new host.
+
. In the *MAC address* field, enter a MAC address for the host.
. Ensure that {ProjectServer} automatically selects the *Managed*, *Primary*, and *Provision* options for the first interface on the host.
If not, select them.
. Click the *Operating System* tab, and verify that all fields contain values.
Confirm each aspect of the operating system.
. Click *Resolve* in *Provisioning Templates* to check the new host can identify the right provisioning templates to use.
+
For more information about associating provisioning templates, see xref:provisioning-templates_{context}[].
ifdef::katello,satellite,orcharhino[]
. Click the *Parameters* tab, and ensure that a parameter exists that provides an activation key.
If not, add an activation key.
endif::[]
. Click *Submit* to save the host details.
This creates a host entry and the host details page appears.
. Download the boot disk from {ProjectServer}.
+
ifndef::satellite[]
* For *Host image*, on the host details page, click the vertical elipsis and select *Host '_My_Host_Name_' image*.
endif::[]
* For *Full host image*, on the host details page, click the vertical elipsis and select *Full host '_My_Host_Name_' image*.
ifndef::satellite[]
* For *Generic image*, navigate to *Infrastructure* > *Subnets*, click *Boot disk* and select *Generic image*.
endif::[]
* For *Subnet image*, navigate to *Infrastructure* > *Subnets*, click the dropdown menu in the *Actions* column of the required subnet and select *Subnet generic image*.
. Write the ISO to a USB storage device using the `dd` utility or `livecd-tools` if required.
. When you start the host and boot from the ISO or the USB storage device, the host connects to {ProjectServer} and starts installing operating system from its kickstart tree.
ifdef::satellite,katello,orcharhino[]
+
When the installation completes, the host also registers to {ProjectServer} using the activation key and installs the necessary configuration and management tools from the *{project-client-name}* repository.
endif::[]



[id="cli-creating-hosts-with-pxe-less-provisioning_{context}"]
.CLI procedure
. Create the host using the `hammer host create` command.
+
[options="nowrap" subs="+quotes"]
----
# hammer host create --name "_My_Host_Name_" --organization "_My_Organization_" \
--location "_My_Location_" --hostgroup "_My_Host_Group_" --mac "_aa:aa:aa:aa:aa:aa_" \
--build true --enabled true --managed true
----
. Ensure that your network interface options are set using the `hammer host interface update` command.
+
[options="nowrap" subs="+quotes"]
----
# hammer host interface update --host "_My_Host_Name_" --managed true \
--primary true --provision true
----
. Download the boot disk from {ProjectServer} using the `hammer bootdisk` command:
+
ifndef::satellite[]
* For *Host image*:
+
[options="nowrap" subs="+quotes"]
----
# hammer bootdisk host --host _My_Host_Name.example.com_
----
endif::[]
* For *Full host image*:
+
[options="nowrap" subs="+quotes"]
----
# hammer bootdisk host --host _My_Host_Name.example.com_ --full true
----
ifndef::satellite[]
* For *Generic image*:
+
[options="nowrap" subs="+quotes"]
----
# hammer bootdisk generic
----
endif::[]
* For *Subnet image*:
+
[options="nowrap" subs="+quotes"]
----
# hammer bootdisk subnet --subnet _My_Subnet_Name_
----

+
This creates a boot ISO for your host to use.
. Write the ISO to a USB storage device using the `dd` utility or `livecd-tools` if required.
. When you start the physical host and boot from the ISO or the USB storage device, the host connects to {ProjectServer} and starts installing operating system from its kickstart tree.
ifdef::satellite,katello,orcharhino[]
+
When the installation completes, the host also registers to {ProjectServer} using the activation key and installs the necessary configuration and management tools from the *{project-client-name}* repository.
endif::[]
