:_mod-docs-content-type: PROCEDURE

[id="configuring-{smart-proxy-context}-server-with-a-default-ssl-certificate"]
= Configuring {SmartProxyServer} with a default SSL certificate

[role="_abstract"]
If your {ProjectServer} is configured with the default certificate, you must configure your {SmartProxyServer} with the SSL certificate that is signed by {ProjectServer} default Certificate Authority (CA).

.Prerequisites
ifndef::foreman-deb[]
* {SmartProxyServer} is registered to {ProjectServer}.
ifdef::satellite[]
For more information, see xref:registering-{smart-proxy-context}-server[].
endif::[]
endif::[]
* {SmartProxyServer} packages are installed.
ifndef::orcharhino[]
For more information, see xref:installing-{smart-proxy-context}-packages[].
endif::[]
* The required ports are open.
ifndef::orcharhino[]
For more information, see xref:opening-required-ports[].
endif::[]

.Procedure
ifdef::containerized[]
. On your {ProjectServer}, generate an authentication bundle for the {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} auth-bundle _{smartproxy-example-com}_
----
+
To regenerate the bundle for an existing {SmartProxyServer}, add the `--certificate-renew` option to the `{foremanctl} auth-bundle` command.
. On your {ProjectServer}, copy the authentication bundle to {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# scp /var/lib/foremanctl/certs/bundles/_{smartproxy-example-com}_.tar.gz \
root@_{smartproxy-example-com}_:/root/_{smartproxy-example-com}_.tar.gz
----
+
[IMPORTANT]
====
The authentication bundle contains TLS private keys and OAuth credentials.
Treat the bundle as highly sensitive and delete any copies after deployment.
====
. On the {SmartProxyServer}, deploy the configuration:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} deploy-proxy \
--flavor {foremanctl-proxy-scenario} \
--auth-bundle /root/_{smartproxy-example-com}_.tar.gz \
--foreman-fqdn _{foreman-example-com}_
----
endif::[]
ifndef::containerized[]
. On {ProjectServer}, to store all the source certificate files for your {SmartProxyServer}, create a directory that is accessible only to the `root` user, for example `/root/{smart-proxy-context}_cert`:
+
[options="nowrap", subs="+quotes,attributes"]
----
# mkdir /root/_{smart-proxy-context}_cert_
----
. On {ProjectServer}, generate the `/root/{smart-proxy-context}_cert/_{smartproxy-example-com}_-certs.tar` certificate archive for your {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {certs-generate} \
--foreman-proxy-fqdn _{smartproxy-example-com}_ \
--certs-tar /root/{smart-proxy-context}_cert/_{smartproxy-example-com}_-certs.tar
----
+
Retain a copy of the `{foreman-installer}` command that the `{certs-generate}` command returns for deploying the certificate to your {SmartProxyServer}.
+
.Example output of `{certs-generate}`
[options="nowrap", subs="+quotes,attributes""]
----
_output omitted_
{installer-scenario-smartproxy} \
--certs-tar-file "/root/{smart-proxy-context}_cert/_{smartproxy-example-com}_-certs.tar" \
--foreman-proxy-foreman-base-url "https://_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{smartproxy-example-com}_" \
--foreman-proxy-oauth-consumer-key "_s97QxvUAgFNAQZNGg4F9zLq2biDsxM7f_" \
--foreman-proxy-oauth-consumer-secret "_6bpzAdMpRAfYaVZtaepYetomgBVQ6ehY_"
----
. On {ProjectServer}, copy the certificate archive file to your {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# scp /root/{smart-proxy-context}_cert/_{smartproxy-example-com}_-certs.tar \
root@_{smartproxy-example-com}_:/root/_{smartproxy-example-com}_-certs.tar
----
. On {SmartProxyServer}, to deploy the certificate, enter the `{foreman-installer}` command that the `{certs-generate}` command returns.
endif::[]
+
[IMPORTANT]
====
Do not delete the certificate archive file after you deploy the certificate.
It is required, for example, when upgrading {SmartProxyServer}.
====
