[id="Managing_SSH_Keys_for_a_User_{context}"]
= Managing SSH Keys for a User

Use this procedure to add or remove SSH keys for a user.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-managing-ssh-keys-for-a-user_{context}[].

.Prerequisites
* Ensure that you are logged in to the {ProjectWebUI} as an Admin user of {ProjectName} or a user with the _create_ssh_key_ permission enabled for adding SSH key and _destroy_ssh_key_ permission for removing a key.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer*{nbsp}>{nbsp}*Users*.
. From the *Username* column, click on the username of the required user.
. Click on the *SSH Keys* tab.
+
* To Add SSH key
... Prepare the content of the public SSH key in a clipboard.
... Click *Add SSH Key*.
... In the *Key* field, paste the public SSH key content from the clipboard.
... In the *Name* field, enter a name for the SSH key.
... Click *Submit*.
+
* To Remove SSH key
... Click *Delete* on the row of the SSH key to be deleted.
... Click *OK* in the confirmation prompt.

[id="cli-managing-ssh-keys-for-a-user_{context}"]
.CLI procedure

To add an SSH key to a user, you must specify either the path to the public SSH key file, or the content of the public SSH key copied to the clipboard.

* If you have the public SSH key file, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer user ssh-keys add \
--user-id _user_id_ \
--name _key_name_ \
--key-file _~/.ssh/id_rsa.pub_
----

* If you have the content of the public SSH key, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer user ssh-keys add \
--user-id _user_id_ \
--name _key_name_ \
--key _ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNtYAAABBBHHS2KmNyIYa27Qaa7EHp+2l99ucGStx4P77e03ZvE3yVRJEFikpoP3MJtYYfIe8k 1/46MTIZo9CPTX4CYUHeN8= host@user_
----

To delete an SSH key from a user, enter the following command:

[options="nowrap", subs="+quotes,attributes"]
----
# hammer user ssh-keys delete --id _key_id_ --user-id _user_id_
----

To view an SSH key attached to a user, enter the following command:

[options="nowrap", subs="+quotes,attributes"]
----
# hammer user ssh-keys info --id _key_id_ --user-id _user_id_
----

To list SSH keys attached to a user, enter the following command:

[options="nowrap", subs="+quotes,attributes"]
----
# hammer user ssh-keys list --user-id _user_id_
----
