[id="downloading-the-binary-dvd-images_{context}"]
= Downloading the Binary DVD Images

Use this procedure to download the ISO images for {RHEL} and {ProjectName}.

.Procedure

. Go to https://access.redhat.com/[Red Hat Customer Portal] and log in.

. Click *DOWNLOADS*.

. Select *Red Hat Enterprise Linux - Versions 7 and below*.

. Ensure that you have the correct product and version for your environment.
+
* *Product Variant* is set to *Red Hat Enterprise Linux Server*.
* *Version*  is set to the latest minor version of the product you plan to use as the base operating system.
* *Architecture* is set to the 64 bit version.

. On the *Product Software* tab, download the Binary DVD image for the latest Red Hat Enterprise Linux Server version.

. Click *DOWNLOADS* and select *{ProjectName}*.

. Ensure that you have the correct product and version for your environment.
+
* *Product Variant* is set to *{ProjectName}*.
* *Version*  is set to the latest minor version of the product you plan to use as the base operating system.
* *Architecture* is set to the 64 bit version.

. On the *Product Software* tab, download the Binary DVD image for the latest {ProjectName} version.

. Copy the ISO files to `/var/tmp` on the {Project} base operating system or other accessible storage device.
+
[options="nowrap"]
----
# scp localfile username@hostname:remotefile
----
