[id="Synchronizing_the_Client_Repository_{context}"]
= Synchronizing the {project-client-name} Repository

ifdef::satellite[]
Use this section to synchronize the {project-client-name} repository from the Red Hat Content Delivery Network (CDN) to your {Project}.
This repository provides the `katello-agent`, `katello-host-tools`, and `puppet` packages for clients registered to {ProjectServer}.
endif::[]

ifndef::satellite[]
.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
+
A list of product repositories available for synchronization is displayed.
. Click the arrow next to the *{RHEL} Server* product to view available content.
. Select *{project-client-name} (for RHEL 8 or RHEL 7 Server) RPMs x86_64*.
. Click *Synchronize Now*.
endif::[]

ifdef::satellite[]
.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
+
A list of product repositories available for synchronization is displayed.
. Click the arrow next to the *{RHEL} Server* product to view available content.
. Select *{project-client-name} (for RHEL 8) RPMs x86_64*.
. Click *Synchronize Now*.
endif::[]

ifndef::satellite[]
.CLI procedure
* Synchronize your {project-client-name} repository using the `hammer repository synchronize` command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--async \
--name 'Red Hat {project-client-name} for RHEL 8 or RHEL 7 Server RPMs x86_64' \
--organization _"My_Organization"_ \
--product 'Red Hat Enterprise Linux Server'
----
endif::[]

ifdef::satellite[]
.CLI procedure
* Synchronize your {project-client-name} repository using the `hammer repository synchronize` command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--async \
--name 'Red Hat {project-client-name} for RHEL 8 RPMs x86_64' \
--organization _"My_Organization"_ \
--product 'Red Hat Enterprise Linux Server'
----
endif::[]