[id="Importing_a_Content_View_Version_from_a_Webserver{context}"]
= Importing a Content View Version from a Webserver

You can import an exported Content View version directly from a web server to create a version with the same content in an organization on another {ProjectServer}.
For more information about exporting a Content View version, see xref:Exporting_a_Content_View_Version_{context}[].

When you import a Content View version, it has the same major and minor version numbers and contains the same repositories with the same packages and errata.
Custom Repositories, Products and Content Views are automatically created if they do not exist in the importing organization.

.Prerequisites
* The exported files must be in a syncable format.
* The exported files must be accessible via http/https.
* If there are any Red Hat repositories in the exported content, the importing organization's manifest must contain subscriptions for the products contained within the export.
* The user importing the Content View version must have the _Content Importer_ Role.

.Procedure
. To import the Content View version to {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer content-import version \
--organization-id=_My_Organization_ID_ \
--path=http://<url>/pub/exports/2021-02-25T21-15-22-00-00/
----
+
. To verify that you imported the Content View version successfully, list Content View versions for your organization:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer content-view version list \
--organization-id=_My_Organization_ID_
----
