[id="synchronizing-templates-with-an-existing-repository_{context}"]
= Synchronizing Templates with an Existing Repository

You can use existing repositories to import and export templates from your {ProjectServer}.

.Procedure
. If you want to use HTTPS to connect to the repository and you use a self-signed certificate authentication on your Git server, validate the certificate:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# sudo -u foreman git config --global http.sslCAPath _Path_To_My_Certificate_
----
. If you want to use SSH to connect to the repository, perform the following steps:
.. Create an SSH key pair if you do not already have it.
Do not specify a passphrase.
+
----
# sudo -u foreman ssh-keygen
----
.. Configure your version control server with the public key from your {Project}, which resides in `/usr/share/foreman/.ssh/id_rsa.pub`.
.. Accept the Git SSH host key as the `foreman` user:
+
[subs="+quotes"]
----
# sudo -u foreman ssh _git.example.com_
----
. Configure the TemplateSync plug-in settings on a *TemplateSync* tab.
.. Change the *Branch* setting to match the target branch on a Git server.
.. Change the *Repo* setting to match the Git repository.
For example, for the repository located in `git@git.example.com/templates.git` set the setting into `git@git.example.com/templates.git`.
