:_mod-docs-content-type: PROCEDURE

[id="assigning-content-view-environments-to-hosts-in-bulk"]
= Assigning content view environments to hosts in bulk

[role="_abstract"]
You can assign content view environments to hosts in bulk by using {ProjectWebUI}.
A host must always have at least one content view environment assigned.

.Prerequisites
* If you want to assign multiple content view environments, the *Allow multiple content views* setting must be enabled.
For more information, see xref:content-view-environments-overview[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Select the hosts to which you want to assign content view environments.
. Click the hosts table menu icon and select *Manage content* > *Content view environments*.
. Edit the content view environments as needed.
* Click *Remove* to remove a content view environment.
* Click *Add content view environment* to assign an additional content view environment.
* Drag and drop the content view environments to change their order.
. Click *Save*.

.Additional resources
* xref:content-view-environment-ordering-and-priority[]
