[id="synchronizing_the_new_repositories_{context}"]
= Synchronizing the new repositories

You must enable and synchronize the new {ProjectVersion} repositories before you can upgrade {SmartProxyServers} and {Project} clients.

.Procedure

. In the {ProjectWebUI}, navigate to *Content* > *Red{nbsp}Hat Repositories*.
Enable the following repositories:
* Repositories required to upgrade {SmartProxyServers}:
** *{ProjectName} {SmartProxy} {ProjectVersion} (for RHEL 9 x86_64) (RPMs)*
** *{ProjectName} Maintenance {ProjectVersion} (for RHEL 9 x86_64) (RPMs)*
** *{EL} 9 (for x86_64 {endash} BaseOS) (RPMs)*
** *{EL} 9 (for x86_64 {endash} AppStream) (RPMs)*
* Repositories required to upgrade {Project} clients:
** *{project-client-name}* for each {RHEL} version your clients are using
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
Synchronize the following repositories:
** All repositories for version {ProjectVersion}
** *{project-client-name}* repositories for each {RHEL} version your clients are using

.Troubleshooting
* If you do not see the {ProjectVersion} repositories in the list of repositories or if an error occurs when synchronizing a repository, refresh the Red{nbsp}Hat Subscription Manifest.
In the {ProjectWebUI}, navigate to *Content* > *Subscriptions* > *Manage Manifest* > *Refresh*.
+
[WARNING]
====
Do not delete the manifest from the Customer Portal or in the {ProjectWebUI}.
Deleting your manifest removes all the entitlements of your hosts.
====

.Additional resources
* For more information on synchronizing repositories, see {ContentManagementDocURL}[_{ContentManagementDocTitle}_].
