:_mod-docs-content-type: PROCEDURE

[id="renewing-self-signed-ca-certificates"]
= Renewing self-signed CA certificates

[role="_abstract"]
The self-signed certiticate authority (CA) certificate on your {ProjectServer} is valid for 20 years by default.
If you need to renew it because the expiration date is close, follow the below procedure.

.Procedure
* Renew CA certificates:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foremanctl} deploy --certificate-ca-renew
----
+
To set a custom validity period, append `--certificate-ca-validity-days _My_Days_` with the validity period in days for the new certificate.

.Verification
* In your browser, go to your {ProjectServer} login page, for example, `\https://{foreman-example-com}`, and inspect the CA certificate in the browser.
This is typically displayed as a shield, padlock, or tune icon next to the address bar depending on your browser.
* On the command line, verify the new certificate validity period:
+
[options="nowrap", subs="+quotes,attributes"]
----
# echo | openssl s_client -connect 127.0.0.1:443 2>/dev/null
----
+
The output displays the whole SSL connection information.
Check the `NotBefore` and `NotAfter` dates of CA entry in the "Certificate chain" section, where `NotBefore` is the date when the certificate becomes valid and `NotAfter` is the date when it expires.

.Next steps
* Refresh the CA certificate on your {SmartProxyServers}.
For more information, see {InstallingSmartProxyDocURL}configuring-{smart-proxy-context}-server-with-ssl-certificates[Configuring {SmartProxyServer} with SSL certificates] in _{InstallingSmartProxyDocTitle}_.
* Refresh the CA certificate on your hosts.
For more information, see {ManagingHostsDocURL}refreshing-the-self-signed-ca-certificate-on-hosts[Refreshing the self-signed CA certificate on hosts] in _{ManagingHostsDocTitle}_.
