:_mod-docs-content-type: PROCEDURE

[id="unassign-ansible-roles-from-a-host-by-using-api"]
= Unassign Ansible roles from a host by using {Project} API

[role="_abstract"]
You can unassign Ansible roles from your host by using {Project} API.

.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_lifecycle_environment_paths`, `edit_ansible_lifecycle_environment_paths`, `view_ansible_content`, `view_ansible_lifecycle_environment_paths`, `view_ansible_lifecycle_environments`, and `view_organizations` permissions.

// TODO: Fix API endpoint
.Procedure
. Optional: Get a list of all assigned Ansible roles:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/execution_environments/ \
| jq ".results | .[]"
----
. Create a JSON file, for example, `data.json` to define your Ansible roles:
+
[source, json, options="nowrap", subs="verbatim,quotes,attributes"]
----
{
  "lifecycle_environment": {
    "description": "_My_Description_",
    "name": "_My_Ansible_Lifecycle_Environment_Name_",
    "execution_environment_id": "_My_Ansible_Execution_Environment_ID_"
  }
}
----
. Unassign Ansible roles from your host:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--data @data.json \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--request PUT \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/lifecycle_environments/_My_Ansible_Lifecycle_Environment_ID_/ \
| jq
----

// TODO: Fix API endpoint
.Verification
* Query the {Project} API to verify that {Project} unassigned the Ansible roles from your host successfully:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/lifecycle_environments/_My_Ansible_Lifecycle_Environment_ID_/ \
| jq
----
