[id="Configuring_the_Cleaning_Unused_Tasks_Feature_{context}"]
= Configuring the Cleaning Unused Tasks Feature

{Project} performs regular cleaning to reduce disc space in the database and limit the rate of disk growth.
As a result, {Project} backup completes faster and overall performance is higher.

By default, {Project} executes a cron job that cleans tasks every day at 19:45.
{Project} removes the following tasks during the cleaning:

* Tasks that have run successfully and are older than thirty days
* All tasks that are older than a year

.For {Project}s Upgraded from Previous Versions
ifndef::orcharhino[]
Until https://bugzilla.redhat.com/show_bug.cgi?id=1788615[BZ#1788615] is resolved, this functionality works only on fresh installations of {ProjectXY} and later.
endif::[]
If you upgrade {Project} from previous versions, this functionality is disabled by default.
To enable {Project} to perform regular cleaning, enter the following command:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-plugin-tasks-automatic-cleanup true
----

Optionally use this procedure to adjust the configuration to serve your needs.

.Procedure
. Optional: To configure the time at which {Project} runs the cron job, set the `--foreman-plugin-tasks-cron-line` parameter to the time you want in cron format.
For example, to schedule the cron job to run every day at 15:00, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-plugin-tasks-cron-line "00 15 * * *"
----
. Optional: To configure the period after which {Project} deletes the tasks, edit the `:rules:` section in the `/etc/foreman/plugins/foreman-tasks.yaml` file.
