[id="Configuring_a_Finish_Template_for_Amazon_EC2_{context}"]
= Configuring a Finish Template for an Amazon Web Service EC2 Environment

ifdef::satellite[]
You can use {ProjectName} finish templates during the provisioning of {RHEL} instances in an Amazon EC2 environment.
endif::[]

ifndef::satellite[]
You can use {ProjectName} finish templates during the provisioning of Linux instances in an Amazon EC2 environment.
endif::[]

If you want to use a Finish template with SSH, {Project} must reside within the EC2 environment and in the correct security group.
{Project} currently performs SSH finish provisioning directly, not using {SmartProxyServer}.
If {ProjectServer} does not reside within EC2, the EC2 virtual machine reports an internal IP rather than the necessary external IP with which it can be reached.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning Templates*.
. In the *Provisioning Templates* page, enter `Kickstart default finish` into the search field and click *Search*.
. On the *Kickstart default finish* template, select *Clone*.
. In the *Name* field, enter a unique name for the template.
ifdef::satellite[]
. In the template, prefix each command that requires root privileges with `sudo`, except for `subscription-manager register` and `yum` commands, or add the following line to run the entire template as the sudo user:
endif::[]
ifndef::satellite[]
. In the template, prefix each command that requires root privileges with `sudo`, except for `yum` or equivalent commands, or add the following line to run the entire template as the `sudo` user:
endif::[]
+
----
sudo -s << EOS
_Template_ _Body_
EOS
----
+
. Click the *Association* tab, and associate the template with a {RHEL} operating system that you want to use.
. Click the *Locations* tab, and add the the location where the host resides.
. Click the *Organizations* tab, and add the organization that the host belongs to.
. Make any additional customizations or changes that you require, then click *Submit* to save your template.
. In the {ProjectWebUI}, navigate to *Hosts* > *Operating systems* and select the operating system that you want for your host.
. Click the *Templates* tab, and from the *Finish Template* list, select your finish template.
. In the {ProjectWebUI}, navigate to *Hosts* > *Create Host* and enter the information about the host that you want to create.
. Click the *Parameters* tab and navigate to *Host parameters*.
ifdef::satellite,orcharhino[]
. In *Host parameters*, click the *Add Parameter* button three times to add three new parameter fields.
Add the following three parameters:
endif::[]
ifdef::foreman-el,foreman-deb,katello[]
. If you have the Remote Execution plugin installed, in *Host parameters*, click the *Add Parameter* button two times to add two new parameter fields.
If you use the Katello plugin, add a third parameter field.
Add the following parameters:
endif::[]
.. In the *Name* field, enter `remote_execution_ssh_keys`.
In the corresponding *Value* field, enter the output of `cat /usr/share/foreman-proxy/.ssh/id_rsa_foreman_proxy.pub`.
.. In the *Name* field, enter `remote_execution_ssh_user`.
In the corresponding *Value* field, enter `ec2-user`.
ifdef::satellite,orcharhino[]
.. In the *Name* field, enter `activation_keys`.
In the corresponding *Value* field, enter your activation key.
endif::[]
ifdef::foreman-el,katello[]
.. If you use the Katello plugin, in the *Name* field, enter `activation_keys`.
In the corresponding *Value* field, enter your activation key.
endif::[]
. Click *Submit* to save the changes.
