[id="Creating_a_User_{context}"]
= Creating a user

Use this procedure to create a user.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-user_{context}[].

.Procedure
// This is the core procedure -- for users who have trouble finding the right button.
// But I'm keeping it super short so that following it doesn't become a nuisance due to describing steps that users can just see in the web UI.
. In the {ProjectWebUI}, navigate to *Administer* > *Users*.
. Click *Create User*.
. Enter the account details for the new user.
. Click *Submit* to create the user.

// After the procedure, this is the place where users can find more details about the fields that are not that obvious from the web UI.
// Splitting this from the core procedure supports scannability -- because you can see where the clicking ends and where the explanation begins.
// Introducing this with "for example" supports maintainability -- because we don't commit ourselves to maintaining a complete list.
For example, you can specify the following account details:

* On the *User* tab, you must set a password for the user.
Select the source by which the user is authenticated from the *Authorized by* list:
** Select *INTERNAL* to manage the user inside {ProjectServer}.
** Select *EXTERNAL* to manage the user with external authentication as described in {InstallingServerDocURL}Configuring_External_Authentication_{project-context}[Configuring External Authentication] in _{InstallingServerDocTitle}_.
* On the *Organizations* tab, ensure an organization is selected for the user.
You can also use the *Default on login* drop-down list to select which organization is selected for the user after they log in.
+
[IMPORTANT]
====
Ensure every user is assigned to an organization.
If a user is not assigned to an organization, their access is limited.
====

[id="cli-creating-a-user_{context}"]
.CLI procedure
* To create a user, enter the `hammer user create` command.
For example:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer user create \
--auth-source-id _My_Authentication_Source_ \
--login _My_User_Name_ \
--mail _My_User_Mail_ \
--organization-ids _My_Organization_ID_1_,_My_Organization_ID_2_ \
--password _My_User_Password_
----
+
The `--auth-source-id 1` setting means that the user is authenticated internally, you can specify an external authentication source as an alternative.
Add the `--admin` option to grant administrator privileges to the user.
Specifying organization IDs is not required, you can modify the user details later using the `update` subcommand.

.Additional resources

* For more information about subcommands related to user accounts, enter `hammer user --help`.
