[id='enabling-insights-on-your-{project-context}-server']
= Enabling Insights on your {ProjectServer}

To maintain your {ProjectServer}, and improve your ability to monitor and diagnose problems you might have with {Project}, install Red{nbsp}Hat Insights on {ProjectServer} and register {ProjectServer} with Red{nbsp}Hat Insights.

.Procedure

. Install Red{nbsp}Hat Insights on {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {project-package-install} insights-client
----
+
. Register {ProjectServer} with Red{nbsp}Hat Insights:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --register-with-insights
----

.Next steps
* Optional: Change the default schedule for running `insights-client` by configuring `insights-client.timer` on {Project}.
For more information, see {RHDocsBaseURL}red_hat_insights/1-latest/html/client_configuration_guide_for_red_hat_insights/assembly-client-changing-schedule[Changing the insights-client schedule] in the _Client Configuration Guide for Red Hat Insights_.
