[id="creating-hosts-with-uefi-http-boot-provisioning"]
= Creating hosts with UEFI HTTP boot provisioning

You can provision hosts from {Project} using the UEFI HTTP Boot.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-hosts-with-uefi-http-boot-provisioning_{context}[].

.Prerequisites
* Ensure that you meet the requirements for HTTP booting.
ifndef::orcharhino[]
For more information, see {PlanningDocURL}http-booting-requirements[HTTP Booting Requirements] in _{PlanningDocTitle}_.
endif::[]

.Procedure
. Enable `foreman-proxy-http`, `foreman-proxy-httpboot`, and `foreman-proxy-tftp` features.
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--foreman-proxy-http true \
--foreman-proxy-httpboot true \
--foreman-proxy-tftp true
----
. Ensure that the {SmartProxy} has TFTP and HTTPBoot features recognized.
In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}* and click on {SmartProxy} to see the list of recognized features.
Click *Refresh Features* if any of the features are missing.
. Ensure that {SmartProxy} is associated with the provisioning subnet.
In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets* > *Edit Subnet* > *{SmartProxies}* and select the {SmartProxy} for both *TFTP* and *HTTPBoot* options.
. Click *OK* to save.
include::snip_steps-create-a-host-tab-host.adoc[]
include::snip_steps-create-a-host-tab-interfaces.adoc[]
. Click the *Operating System* tab, and verify that all fields contain values.
Confirm each aspect of the operating system.
. From the *PXE Loader* list, select *Grub2 UEFI HTTP*.
. Optional: Click *Resolve* in *Provisioning template* to check the new host can identify the right provisioning templates to use.
+
For more information about associating provisioning templates, see xref:creating-provisioning-templates[].
ifdef::katello,satellite,orcharhino[]
include::snip_step-parameter-ak.adoc[]
endif::[]
. Click *Submit* to save the host details.
+
For more information about network interfaces, see {ManagingHostsDocURL}configuring-network-interfaces[Configuring network interfaces] in _{ManagingHostsDocTitle}_.
. Set the host to boot in UEFI mode from network.
. Start the host.
. From the boot menu, select *Kickstart default PXEGrub2*.

This creates the host entry and the relevant provisioning settings.
This also includes creating the necessary directories and files for UEFI booting the bare-metal host.
When you start the physical host and set its boot mode to UEFI HTTP, the host detects the defined DHCP service, receives HTTP endpoint of {SmartProxy} with the Kickstart tree and installs the operating system.

ifdef::katello,satellite,orcharhino[]
When the installation completes, the host also registers to {ProjectServer} using the activation key and installs the necessary configuration and management tools from the {project-client-name} repository.
endif::[]

[id="cli-creating-hosts-with-uefi-http-boot-provisioning_{context}"]
.CLI procedure
. Enable `foreman-proxy-http`, `foreman-proxy-httpboot`, and `foreman-proxy-tftp true` features:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--foreman-proxy-http true \
--foreman-proxy-httpboot true \
--foreman-proxy-tftp true
----
. Create the host with the `hammer host create` command.
+
[options="nowrap" subs="+quotes"]
----
$ hammer host create \
--build true \
--enabled true \
--hostgroup "_My_Host_Group_" \
--location "_My_Location_" \
--mac "_My_MAC_Address_" \
--managed true \
--name "_My_Host_Name_" \
--organization "_My_Organization_" \
--pxe-loader "Grub2 UEFI HTTP"
----
. Ensure the network interface options are set using the `hammer host interface update` command:
+
[options="nowrap" subs="+quotes"]
----
$ hammer host interface update \
--host "_My_Host_Name_" \
--managed true \
--primary true \
--provision true
----
. Set the host to boot in UEFI mode from network.
. Start the host.
. From the boot menu, select *Kickstart default PXEGrub2*.

This creates the host entry and the relevant provisioning settings.
This also includes creating the necessary directories and files for UEFI booting the bare-metal host.
When you start the physical host and set its boot mode to UEFI HTTP, the host detects the defined DHCP service, receives HTTP endpoint of {SmartProxy} with the Kickstart tree and installs the operating system.

ifdef::katello,satellite,orcharhino[]
When the installation completes, the host also registers to {ProjectServer} using the activation key and installs the necessary configuration and management tools from the {project-client-name} repository.
endif::[]
