:_mod-docs-content-type: PROCEDURE

[id="create-a-predefined-configuration-for-hosts-on-{opentofu-target-id}-by-using-web-ui"]
= Create a predefined configuration for hosts on {opentofu-target} by using {ProjectWebUI}

[role="_abstract"]
You can add {opentofu-target} hardware settings to a compute profile.
When you create a host on {opentofu-target} using this compute profile, these settings are automatically populated.

.Prerequisites
* You created an image for {opentofu-target} on {Project}.
For more information, see xref:define-an-image-for-hosts-on-{opentofu-target-id}-by-using-web-ui[].

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Profiles*.
. Select your compute profile.
. Select your {opentofu-target} compute resource.
ifdef::hetzner-cloud[]
. From the *Server Type* list, select the server type to use for provisioning.
. From the *Location* list, select the geographical location of the {opentofu-target} datacenter.
+
The list of available locations is not dynamically reduced to the locations that allow the selected server type.
You must check manually if the selected server type is available within the location.
If you do not select a location, {Project} automatically selects a compatible location.
. Select *Backups* if you want to have backups of your hosts enabled on {opentofu-target}.
. Optional: From the *Storage* section, define additional Storage Volumes.
. From the *Image* list, select the image to use for provisioning.
. From the *Network* list, select the network to use for provisioning.
+
The first network-interface will receive a public IP address.
Selecting a managed subnet may therefore result in an error.
endif::[]
ifdef::stackit-cloud[]
. In the *Machine type* field, define the size of the cloud instance that is available in your project.
For example, enter `g2i.1`.
. In the *Region* field, enter the geographical location identifier.
For example, enter `eu01`.
. If you want to define a specific availability zone, in the *Availability zone* field, enter the identifier of the {opentofu-target} availability zone.
For example, enter `eu01-1`.
. In the *Boot volume size (GB)* field, enter the size of the disk of your host.
For example, enter `64` to provide a 64 GiB disk to your host.
. If you want to assign an IPv4 address to the host, check the *Assign public IPv4* checkbox.
. From the *Image* list, select the image to use for provisioning.
. If you want to add your host to a specific network, in the *Network ID* field, enter the identifier of the {opentofu-target} network.
. If you want to add your host to a security group, in the *Security group ID* field, enter the identifier of the {opentofu-target} security group.
If you leave it empty, {opentofu-target} will create a security group and assign it to your host.
. If you want to add another network interface, click *Add Interface* and enter the network ID and security group ID.
. If you want to add another disk, click *Add Volume* and enter a name for your disk, its size, and the availability zone.
Ensure that this matches with the availability zone that you have entered before.
endif::[]
. Click *Submit* to save the values to your compute profile.

.Next steps
* Create a host group or host based on your compute profile.
For more information, see xref:provision-a-host-on-{opentofu-target-id}-by-using-web-ui[].
