[id="setting-the-load-balancer-for-host-registration_{context}"]
= Setting the Load Balancer for Host Registration

You can configure {Project} to register clients through a load balancer when using the host registration feature.

You will be able to register hosts to the load balancer instead of {SmartProxy}.
The load balancer will decide through which {SmartProxy} to register the host at the time of request.
Upon registration, the subscription manager on the host will be configured to manage content through the load balancer.

.Prerequisites
* You configured SSL certificates on all {SmartProxyServer}s.
For more information, see xref:configuring-capsule-servers-for-load-balancing[].
* You enabled Registration and Templates plug-ins on all {SmartProxyServer}s:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {installer-scenario-smartproxy} \
--foreman-proxy-registration true \
--foreman-proxy-templates true
----

.Procedure
. On all {SmartProxyServer}s, set the registration and template URLs using `{foreman-installer}`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {installer-scenario-smartproxy} \
--foreman-proxy-registration-url "https://_loadbalancer.example.com_:{smartproxy_port}" \
--foreman-proxy-template-url "https://_loadbalancer.example.com_:8000"
----
. In the {ProjectWebUI}, navigate to *Infrastracture* > *{SmartProxies}*.
. For each {SmartProxy}, click the dropdown menu in the *Actions* column and select *Refresh*.
