[id="overriding-Ansible-variables_{context}"]

= Overriding Ansible Variables in {Project}

If you run Ansible roles in {Project}, you can use {Project} to override Ansible variables for those roles.

The following procedure refers to hosts and host groups.
For more information, see {ManagingHostsDocURL}[_{ManagingHostsDocTitle}_].

.Precedence in Overriding Variables

If you use an Ansible role to run a task as a user that is not the `Effective User`, there is a strict order of precedence for overriding Ansible variables.
To ensure that the variable that you override follows the correct order of precedence, see https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#ansible-variable-precedence[Variable precedence: Where should I put a variable?] in the _Ansible User Guide_.

.Prerequisite

* You must have Ansible variables in {Project}.
For more information, see xref:importing-Ansible-roles_{context}[]

.Procedure

. In the {ProjectWebUI}, navigate to *Configure* > *Variables*.
. Select the Ansible variable that you want to override and manage with {Project}.
. In the *Default Behavior* area, select the *Override* check box.
. In the *Parameter Type* field, select the value type for validation such as *string* or *boolean*.
The types *array* and *hash* have further options for handling upon a variable match.
For more information, see xref:prioritize-order[the _Prioritize Attribute Order_ area] below.
. In the *Default Value* field, enter the default value that you want to use if there is no match for the variable.
. Optional: If you do not want to display the value of the variable as plain text in the {ProjectWebUI}, select the *Hidden Value* check box to display the content of the variable as asterisks.
This is useful for sensitive values such as passwords or secret tokens.
. Optional: Expand the *Optional Input Validator* area and specify conditions that will be used to validate concrete values of the variable:
* Select *Required* if you want to enforce users to fill in this variable.
* In the *Validator Type* field, select how the value will be validated:
** `list` - The value will be validated against an enumeration of allowed values.
** `regex` - The value will be validated against a regular expression pattern.
. Optional: [#prioritize-order]#In the *Prioritize Attribute Order* area#, specify the order of priority to match an override with a host by host attributes.
Order at the top takes higher precedence.
The first match wins.
+
You can combine multiple attributes into a single matcher key using a comma as the AND operation.
For example, the matcher key of `hostgroup, environment` would expect matchers such as `hostgroup = "web servers"` AND `environment = production`.
+
If you use the parameter type *array* or *hash*, you can further set:

** *Merge Overrides* - Merges members of the arrays/hashes instead of replacing the whole array or hash.
If the hashes contain the same key, the value is overwritten by the value of the host.
** *Merge Default* - Adds the default value to the array or hash.
** *Avoid Duplicates* - Ensures that the values in the array or hash are unique.
. Optional: Expand the *Specify Matchers* area and specify criteria for selecting hosts on which the variable overrides.
. To save the override settings, click *Submit*.

To use the Ansible variable, add the variable as a parameter to your host or host group, or add the variable as a global parameter.

.Adding the Variable to a Host

. In the {ProjectWebUI}, navigate to *Hosts > All Hosts* and select the host that you want to use.
. Click the *Ansible* tab, and in the *Variables* area, click the pencil icon to edit the value of the variable.
. Click the tick icon to accept the value of the changed variable or the cross icon to cancel the change.

.Adding the Variable to a Host Group

. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*, and select the host group that you want to use.
. Click the *Parameters* tab, and in the *Host Group Parameters* area, click *Add Parameter*.
. In the *Name* field, add the Ansible variable name.
. From the *Type* list, select the type of the variable for validation.
. In the *Value* field, enter the value for the variable.

.Adding the Variable as a Global Parameter

. In the {ProjectWebUI}, navigate to *Configure* > *Global Parameters*, and click *Create Parameter*.
. In the *Name* field, add the Ansible variable name.
. From the *Type* list, select the type of the variable for validation.
. In the *Value* field, enter the value for the variable.
. Optional: If you do not want to display the Ansible variable in plain text, select the *Hidden Values* check box to display the content of the variable as asterisks in the {ProjectWebUI}.
