[id="Upgrading-Project-from-EL7-to-EL8{context}"]
= Upgrading {Project} from {RHEL} 7 to {RHEL} 8

Use this procedure to upgrade your {Project} installation from {RHEL} 7 to {RHEL} 8.
LEAPP is the supported tool for {RHEL} 7 to {RHEL} 8 upgrades.

.Prerequisites
* {Project} {ProjectVersionPrevious} running on CentOS Linux 7.
ifdef::katello,foreman-el[]
- {Project} installations running on {RHEL} 7 cannot upgrade to {RHEL} 8. You must have a {RHEL} compatible LEAPP build to upgrade.
endif::[]
* Access to available repositories or a local mirror of repositories.
* No outstanding updates.
* {Project} installations can be upgraded to CentOS Stream 8 and a {RHEL} rebuild.
ifdef::satellite[]
* {Project} installations upgrade from {RHEL} 7 to {RHEL} 8, not from CentOS Linux 7 and {RHEL} rebuilds.
endif::[]

.Procedure
ifdef::katello,foreman-el[]
. Configure the https://copr.fedorainfracloud.org/coprs/g/theforeman/leapp/[@theforeman/leapp COPR Repository], which contains newer LEAPP packages than those shipped by https://wiki.almalinux.org/elevate/[AlmaLinux/ELevate], and support {Project} upgrades:

+
----
# curl -o /etc/yum.repos.d/theforeman-leapp.repo https://copr.fedorainfracloud.org/coprs/g/theforeman/leapp/repo/epel-7/group_theforeman-leapp-epel-7.repo
----
. Install required packages:
+
----
# yum install leapp leapp-repository leapp-data-centos
----

. Add {Project} specific repositories to `/etc/leapp/files/leapp_upgrade_repositories.repo`:
+
----
# [leapp-foreman]
name=Foreman 3.2
baseurl=https://yum.theforeman.org/releases/3.2/el8/$basearch
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-foreman
module_hotfixes=1

[leapp-foreman-plugins]
name=Foreman plugins 3.2
baseurl=https://yum.theforeman.org/plugins/3.2/el8/$basearch
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-foreman
module_hotfixes=1

[leapp-foreman-client]
name=Foreman client 3.2
baseurl=https://yum.theforeman.org/client/3.2/el8/$basearch
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-foreman-client

[leapp-puppet7]
name=Puppet 7 Repository el 8 - $basearch
baseurl=http://yum.puppetlabs.com/puppet7/el/8/$basearch
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-puppet7-release
       file:///etc/pki/rpm-gpg/RPM-GPG-KEY-2025-04-06-puppet7-release
enabled=1
gpgcheck=1

[leapp-katello]
name=Katello 4.4
baseurl=https://yum.theforeman.org/katello/4.4/katello/el8/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-foreman
enabled=1
gpgcheck=1
module_hotfixes=1

[leapp-katello-candlepin]
name=Candlepin: an open source entitlement management system.
baseurl=https://yum.theforeman.org/katello/4.4/candlepin/el8/$basearch/
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-foreman
enabled=1
gpgcheck=1
module_hotfixes=1

[leapp-pulpcore]
name=pulpcore: Fetch, Upload, Organize, and Distribute Software Packages.
baseurl=https://yum.theforeman.org/pulpcore/3.16/el8/$basearch/
gpgkey=https://yum.theforeman.org/pulpcore/3.16/GPG-RPM-KEY-pulpcore
enabled=1
gpgcheck=1
module_hotfixes=1
----
endif::[]

* If you are not using {Project}, you can leave out `leapp-katello`, `leapp-katello-candlepin` and `leapp-pulpcore`.

* If you are using Puppet 6 instead of Puppet 7, replace the `7` with a `6` in the `leapp-puppet7` entry.

* You need a Puppet repository for the Puppet agent that the installer is using.

ifdef::katello,foreman-el[]
. We do not support {RHEL} 8 installations with EPEL 8 enabled, so remove `epel-release`:
+
----
# yum remove epel-release
----
endif::[]

. Remove `centos-release-scl` and `centos-release-scl-rh` repositories:
+
----
# yum remove centos-release-scl centos-release-scl-rh
----
. Let LEAPP analyze your system:
+
----
# leapp preupgrade
----

+

The first run is expected to fail but report issues.
Continue to the next step for remediation.

. Fix issues found by LEAPP (check `/var/log/leapp/leapp-report.txt` for details):
+
----
# rmmod pata_acpi
# echo PermitRootLogin yes | tee -a /etc/ssh/sshd_config
# leapp answer --section remove_pam_pkcs11_module_check.confirm=True
----
+

ifdef::katello,foreman-el[]
** If `preupgrade` aborts with a dependency resolution error such as:
+
----
# package rubygem-fx-0.5.0-2.el8.noarch requires rubygem(railties) >= 4.0.0,
----
but none of the providers can install or:
+
----
# package rubygem-railties-6.0.4.7-1.el8.noarch requires rubygem(thor) < 2.0
----
but none of the providers can install:
endif::[]

ifdef::katello,foreman-el[]
. Remove packages that are no longer available from any repository:
+
----
# dnf remove $(dnf repoquery --extras --exclude '*katello*' --exclude '*pulp*' --exclude '*localhost*' --exclude "*$HOSTNAME*" --exclude libmodulemd) –
----
endif::[]

+

. Check the output if it does not contain any local packages.

. Remove `rubygem-thor`:
+
----
# yum remove rubygem-thor
----

. Ensure `leapp preupgrade` has no issues.
. Run:
+
----
# leapp upgrade
----

+

. Reboot the system.
. After the system reboots, a live system conducts the upgrade, reboots to fix SELinux labels, then reboots into the final {RHEL} 8 system.
. After the system reboots, LEAPP finishes the upgrade, watch it with:
+
----
# journalctl -u leapp_resume -f
----

[NOTE]
====
If you install the system and need to use `--disable-system-checks`, the last step of the upgrade is going to fail, and you need to call `{foreman-installer} --disable-system-checks` manually once the system reboots.
====
