[id="renaming-{smart-proxy-context}_{context}"]
= Renaming {SmartProxyServer}

The host name of {SmartProxyServer} is referenced by {ProjectServer} components and all hosts registered to it.
This procedure ensures that in addition to renaming {SmartProxyServer}, you also update all references to the new host name.

[WARNING]
====
Renaming your {SmartProxyServer} host shuts down all {Project} services on that host.
The services restart after the renaming is complete.
====

.Prerequisites
* Back up your {SmartProxyServer} before renaming.
If you fail to successfully rename it, restore it from the backup.
For more information, see xref:backing-up-{project-context}-server-and-{smart-proxy-context}_{context}[].
* Run the `hostname` and `hostname -f` commands on {SmartProxyServer}.
If both commands do not return the FQDN of {SmartProxyServer}, the `{project-change-hostname}` script will fail to complete.
+
If the `hostname` command returns the shortname of {SmartProxyServer} instead of the FQDN, use `hostnamectl set-hostname _My_Old_FQDN_` to set the old FQDN correctly before attempting to use the `{project-change-hostname}` script.

.Procedure
. On your {ProjectServer}, generate a new certificates archive file for your {SmartProxyServer}.
+
* If you are using the default SSL certificate, regenerate the default SSL certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {certs-generate} \
--certs-tar /root/_new-{smartproxy-example-com}-certs.tar_ \
--foreman-proxy-fqdn _new-{smartproxy-example-com}_
----
+
Ensure that you enter the full path to the `.tar` file.
+
* If you are using a custom SSL certificate, create a new SSL certificate for your {SmartProxyServer}.
ifndef::orcharhino[]
For more information, see {InstallingSmartProxyDocURL}configuring-capsule-custom-server-certificate_{smart-proxy-context}[Configuring {SmartProxyServer} with a Custom SSL Certificate] in _{InstallingSmartProxyDocTitle}_.
endif::[]
. On your {ProjectServer}, copy the certificates archive file to your {SmartProxyServer}.
For example, to copy the archive file to the `root` user's home directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp /root/_new-{smartproxy-example-com}-certs.tar_ root@_{smartproxy-example-com}_:
----
. On your {SmartProxyServer}, run the `{project-change-hostname}` script and provide the host's new name, {Project} credentials, and certificates archive file name.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {project-change-hostname} _new-{smartproxy-example-com}_ \
--certs-tar /root/_new-{smartproxy-example-com}-certs.tar_ \
--password _My_Password_ \
--username _My_Username_
----
+
Ensure that you enter the full path to the `.tar` file.
. If you have created a custom certificate for your {SmartProxyServer}, deploy the certificate to your {SmartProxyServer} by entering the `{foreman-installer}` command that the `{certs-generate}` command returned in a previous step.
ifndef::orcharhino[]
For more information, see {InstallingSmartProxyDocURL}deploying-a-custom-ssl-certificate-to-{smart-proxy-context}-server_{smart-proxy-context}[Deploying a Custom SSL Certificate to {SmartProxyServer}] in _{InstallingSmartProxyDocTitle}_.
endif::[]
. Reregister all hosts that are registered to your {SmartProxyServer}.
For more information, see {ManagingHostsDocURL}registering_hosts_to_server_managing-hosts[Registering hosts and setting up host integration] in _{ManagingHostsDocTitle}_.
. Update the {SmartProxy} host name in the {ProjectWebUI}.
.. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*.
.. Locate {SmartProxyServer} in the list, and click *Edit*.
.. Edit the *Name* and *URL* fields to match {SmartProxyServer}'s new host name, then click *Submit*.
.. On your DNS server, add a record for the new hostname of your {SmartProxyServer}, and delete the record of the previous host name.
