[id="configuring-kerberos-authentication-for-remote-execution_{context}"]
= Configuring Kerberos Authentication for Remote Execution

You can use Kerberos authentication to establish an Script connection for remote execution on {Project} hosts.

.Prerequisites
* Enroll {ProjectServer} on the Kerberos server
* Enroll the {Project} target host on the Kerberos server
* Configure and initialize a Kerberos user account for remote execution
* Ensure that the foreman-proxy user on {Project} has a valid Kerberos ticket granting ticket

.Procedure
. To install and enable Kerberos authentication for remote execution, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {installer-scenario} \
 --foreman-proxy-plugin-remote-execution-script-script-kerberos-auth true
----
+
. To edit the default user for remote execution, in the {ProjectWebUI}, navigate to *Administer* > *Settings* and click the *RemoteExecution* tab.
In the *Script User* row, edit the second column and add the user name for the Kerberos account.
. Navigate to *remote_execution_effective_user* and edit the second column to add the user name for the Kerberos account.

To confirm that Kerberos authentication is ready to use, run a remote job on the host.
