:_mod-docs-content-type: PROCEDURE

[id="resetting-external-authentication-configuration-for-kerberos-sso"]
= Resetting external authentication configuration for Kerberos SSO

[role="_abstract"]
You can disable external authentication with {FreeIPA} or Active Directory (AD) by resetting the configuration for the `IPA` authentication type.
This prevents user accounts defined in the external authentication source from accessing {Project}.

[IMPORTANT]
====
Resetting external authentication prevents users from accessing {Project} as described in xref:configuring-kerberos-sso-with-{FreeIPA-context}-in-{project-context}[] and xref:configuring-kerberos-sso-for-active-directory-users-in-project_{context}[].
However, some configuration files, such as configuration files for the System Security Services Daemon (SSSD), will remain modified because {Project} does not have access to the previous state of these files.
====

.Procedure
ifdef::foremanctl[]
* Reset the external authentication configuration to the default state:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foremanctl deploy --reset-external-authentication
----
endif::[]
ifndef::foremanctl[]
* Reset the external authentication configuration to the default state:
** To disable access to {ProjectWebUI}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --reset-foreman-ipa-authentication
----
** To disable access to {ProjectWebUI}, {Project} API, and Hammer CLI:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --reset-foreman-ipa-authentication-api
----
endif::[]

.Verification
ifdef::foremanctl[]
#How can users verify this?#
endif::[]
ifndef::foremanctl[]
* Display the value for the `foreman-ipa-authentication` and `foreman-ipa-authentication-api` configuration options:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --help | grep foreman-ipa-authentication
----
+
The expected value for disabled external authentication is `false`.
endif::[]
