[id="Deploying_a_Policy_in_a_Host_Group_Using_Puppet_{context}"]
= Deploying a Policy in a Host Group Using Puppet

After you deploy a compliance policy in a host group using Puppet, the Puppet agent installs the SCAP client and configures OpenSCAP scans on the hosts on the next Puppet run according to the selected compliance policy.

The SCAP content in your compliance policy might require remote resources.
For more information, see xref:inclusion-of-remote-scap-resources_{context}[].

.Prerequisites
* You have enabled OpenSCAP on your {SmartProxy}.
ifdef::satellite[]
For more information, see {InstallingSmartProxyDocURL}Enabling_OpenSCAP_on_{smart-proxy-context}_Servers_{smart-proxy-context}[Enabling OpenSCAP on {SmartProxyServersTitle}] in _{InstallingSmartProxyDocTitle}_.
endif::[]
ifndef::satellite[]
For more information, see xref:Installing_the_OpenSCAP_Plugin_{context}[].
endif::[]
include::snip_prerequisite-rhel-repositories.adoc[]
* You have enabled and synced the {project-client-name} repository to {Project}, and enabled it on the hosts.
* You have xref:Creating_a_Compliance_Policy_{context}[created a compliance policy] with the Puppet deployment option and assigned the host group.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*.
. Click the host group that you want to configure for OpenSCAP reporting.
. In the *Environment* list, select the Puppet environment that contains the `foreman_scap_client*` Puppet classes.
. In the *OpenSCAP {SmartProxy}* list, select the {SmartProxy} with OpenSCAP enabled that you want to use.
. On the *Puppet ENC* tab, add the `foreman_scap_client` Puppet class.
. Optional: Configure any *Puppet Class Parameters*.
. Click *Submit* to save your changes.
