[id="enabling-dependency-solving_{context}"]
= Enabling Dependency Solving

You can enable dependency solving per Content View or by default for your whole {Project} environment.

.Prerequisites

* Dependency solving is useful only in limited contexts.
Before enabling it, ensure you read and understand xref:Resolving_Package_Dependencies_content-management[]

.Procedure

To enable dependency solving per Content View in the {ProjectWebUI}

. Select *Content > Content Views*.
. In the list of content views, select the required content view.
. Under *Details*, toggle *Solve dependencies*.

To enable dependency solving by default:

. Select *Administer > Settings*.
. Under *Content*, change the value for *content view Dependency Solving Default* to *yes*.
Write a short introductory paragraph that provides an overview of the module. The introduction should include what the module will help the user do and why it will be beneficial to the user. Include key words that relate to the module to maximize search engine optimization.