:_mod-docs-content-type: PROCEDURE

[id="Registering_Clients_Using_the_Bootstrap_Script_{context}"]
= **(Deprecated)** Registering clients using the bootstrap script

[role="_abstract"]
To register clients, enter the following command on the client.
You must complete the registration procedure for each client.

.Prerequisites
* Ensure that you install the bootstrap script on the client and change file permissions of the script to executable.
For more information, see {ManagingHostsDocURL}Registering_Hosts_by_Using_the_Bootstrap_Script_managing-hosts[Registering Hosts to {ProjectName} Using The Bootstrap Script] in _{ManagingHostsDocTitle}_.

.Procedure
* On {EL} 8, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--activationkey="_My_Activation_Key_" \
--enablerepos={project-client-RHEL8-url} \
--force \
--hostgroup="_My_Host_Group_" \
--location="_My_Location_" \
--login=_admin_ \
--organization="_My_Organization_" \
--puppet-ca-port 8141 \
--server _{loadbalancer-example-com}_
----
+
The options used in the command include the following:
+
`enablerepos`::
Replace `<arch>` with the client architecture, for example `x86`.
`--force`::
Include the `--force` option to register the client that has been previously registered to a standalone {SmartProxy}.
`--puppet-ca-port`::
Include the `--puppet-ca-port 8141` option if you use Puppet.

* On {EL} 7, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# python bootstrap.py --login=_admin_ \
--activationkey="_My_Activation_Key_" \
--enablerepos={project-client-RHEL7-url} \
--force \
--hostgroup="_My_Host_Group_" \
--location="_My_Location_" \
--organization="_My_Organization_" \
--puppet-ca-port 8141 \
--server _{loadbalancer-example-com}_
----
+
The options used in the command include the following:
+
`--force`::
Include the `--force` option to register the client that has been previously registered to a standalone {SmartProxy}.
`--puppet-ca-port`::
Include the `--puppet-ca-port 8141` option if you use Puppet.
+
The script prompts for the password corresponding to the {Project} user name you entered with the `--login` option.
