[id="Provisioning_Ubuntu_Autoinstall_Through_Smart_Proxies_{context}"]
= Provisioning Ubuntu Autoinstall Through {SmartProxies}

Perform these steps to provision hosts running Ubuntu 20.04.3+ or Ubuntu 22.04.

.Procedure
. On your {SmartProxyServer}, ensure _Smart Proxy HTTP forward_ is enabled:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# grep "^:enabled: true$" /etc/foreman-proxy/settings.d/templates.yml
----
+
Note that this is enabled by default.
. On your {SmartProxyServer}, open the corresponding port:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# firewall-cmd --permanent --zone=public --add-port=8000/tcp
# firewall-cmd --reload
----
. On your {ProjectServer}, add your {SmartProxyServer} to the list of trusted proxies:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--foreman-trusted-proxies "127.0.0.1" \
--foreman-trusted-proxies "::1" \
--foreman-trusted-proxies "_Your_IP_"
----
. Provide the extracted ISO and ISO image itself on each {SmartProxyServer}.
For more information, see xref:Creating_an_Installation_Medium_for_Ubuntu_22_04_{context}[].
. In the {ProjectWebUI}, navigate to *Hosts > Installation Media* and create an installation medium.
Set the *Path* to the extracted ISO image on your {SmartProxyServer}.
. In the {ProjectWebUI}, navigate to *Hosts > Operating Systems* and assign the installation medium to your operating system entry for Ubuntu 22.04.
. In the {ProjectWebUI}, navigate to *Configure > Host Groups*, select the host group that you use to deploy Ubuntu 22.04 through a {SmartProxyServer}, and set the installation medium entry accordingly.
