[id="uploading-content-to-{project-context}-server"]
= Uploading Content to {ProjectServer}

You can use the {Project} API to upload and import large files to your {ProjectServer}.
This process involves four steps:

. Create an upload request.
. Upload the content.
. Import the content.
. Delete the upload request.

The maximum file size that you can upload is 2{nbsp}MB.
For information about uploading larger content, see xref:api-uploading-content-larger-than-2-mb[].

.Procedure
. Assign the package name to the variable `name`:
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export name=jq-1.6-2.el7.x86_64.rpm
----
. Assign the checksum of the file to the variable `checksum`:
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export checksum=$(sha256sum $name|cut -c 1-65)
----
. Assign the file size to the variable `size`:
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export size=$(du -bs $name|cut -f 1)
----
. Create an upload request that returns the upload ID of the request by using `size` and `checksum`.
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header 'Content-Type: application/json' \
--request POST \
--user _My_User_Name_:__My_Password__ \
--data "{\"size\": \"$size\", \"checksum\":\"$checksum\"}" \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads
----
+
where 76, in this case, is an example Repository ID.
+
Example request:
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
{"upload_id":"37eb5900-597e-4ac3-9bc5-2250c302fdc4"}
----
. Assign the upload ID to the variable `upload_id`:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export upload_id=37eb5900-597e-4ac3-9bc5-2250c302fdc4
----
. Assign the path of the package you want to upload to the variable `path`:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ export path=/root/jq/jq-1.6-2.el7.x86_64.rpm
----
. Upload your content.
Ensure you use the correct MIME type when you upload data.
The API uses the `application/json` MIME type for the requests to {Project} unless stated otherwise.
Combine the upload ID, MIME type, and other parameters to upload content.
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--user _My_User_Name_:__My_Password__ \
--header Accept:application/json \
--header Content-Type:multipart/form-data \
--request PUT \
--data-urlencode size=$size \
--data-urlencode offset=0 \
--data-urlencode content@$\{path} \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id
----
. After you have uploaded the content to your {ProjectServer}, you need to import it into the appropriate repository.
Until you complete this step, {ProjectServer} does not detect the new content.
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header "Content-Type:application/json" \
--request PUT \
--user _My_User_Name_:__My_Password__ \
--data "{\"uploads\":[{\"id\": \"$upload_id\", \"name\": \"$name\", \"checksum\": \"$checksum\" }]}" \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/import_uploads
----
. After you have successfully uploaded and imported your content, you can delete the upload request.
This frees any temporary disk space that data is using during the upload.
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header 'Content-Type: application/json' \
--request DELETE \
--user _My_User_Name_:__My_Password__ \
--data "{}" \
https://_{foreman-example-com}_/katello/api/v2/repositories/76/content_uploads/$upload_id
----
