:_mod-docs-content-type: PROCEDURE

[id="installing-a-smart-proxy-server"]
= Installing {SmartProxyServer}

[role="_abstract"]
Install {SmartProxyServer} and configure it for host registration and provisioning.

.Prerequisites
* `{smartproxy-installer-package}` packages are installed.

.Procedure
. Upgrade all packages:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-upgrade}
----
ifdef::foreman-el,foreman-deb[]
. Install {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--enable-foreman-proxy \
--enable-puppet \
--foreman-proxy-foreman-base-url https://_{foreman-example-com}_ \
--foreman-proxy-oauth-consumer-key _My_oAuth_Consumer_Key_ \
--foreman-proxy-oauth-consumer-secret _My_oAuth_Consumer_Secret_ \
--foreman-proxy-puppetca false \
--foreman-proxy-tftp false \
--foreman-proxy-trusted-hosts _{foreman-example-com}_ \
--no-enable-foreman \
--no-enable-foreman-cli \
--puppet-server-ca false
----
. Enable the Registration and Templates features on your {SmartProxyServer} and set the template URL:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--foreman-proxy-registration true \
--foreman-proxy-templates true \
--foreman-proxy-template-url "http://_{smartproxy-example-com}_:8000"
----
. On your {SmartProxyServer}, open the corresponding ports:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# firewall-cmd --permanent --zone=public --add-port=8000/tcp
----
. On your {SmartProxyServer}, reload the firewall configuration:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# firewall-cmd --reload
----
. On {ProjectServer}, add the {SmartProxy} to the list of trusted proxies.
endif::[]
ifdef::katello[]
* To install {SmartProxyServer} with content, refer to xref:configuring-{smart-proxy-context}-server-with-ssl-certificates[].
Running `{certs-generate}` is a required prerequisite to installing {SmartProxyServer} with content.
* On {ProjectServer}, add the {SmartProxy} to the list of trusted proxies.
endif::[]
+
This is required for {Project} to recognize hosts' IP addresses forwarded over the `X-Forwarded-For` HTTP header set by {SmartProxy}.
For security reasons, {Project} recognizes this HTTP header only from localhost by default.
You can enter trusted proxies as valid IPv4 or IPv6 addresses of {SmartProxies}, or network ranges.
+
[WARNING]
====
Do not use a network range that is too broad because that might cause a security risk.
====
+
Enter the following command.
Note that the command overwrites the list that is currently stored in {Project}.
Therefore, if you have set any trusted proxies previously, you must include them in the command as well:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--foreman-trusted-proxies "127.0.0.1/8" \
--foreman-trusted-proxies "::1" \
--foreman-trusted-proxies "_My_IP_address_" \
--foreman-trusted-proxies "_My_IP_range_"
----
+
The localhost entries are required, do not omit them.

.Verification
. List the current trusted proxies using the full help of {Project} installer:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --full-help | grep -A 2 "trusted-proxies"
----
. The current listing contains all trusted proxies you require.
