[id="configuring-server-for-use-with-dhcpd"]
= Configuring {ProjectServer} for use with dhcpd

You can configure {ProductName} with a non-installer-managed DHCP server.

Perform the steps on the {ProjectServer} or {SmartProxyServer}.

.Prerequisites
* You configured the DHCP service and shared the configuration and lease files over the network. For more information, see xref:configuring-dhcpd-to-use-with-server[].

.Procedure
. Install the required package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {project-package-install} {nfs-client-package}
----
. Create the directories into which you later mount the NFS shares:
+
[options="nowrap"]
----
# mkdir -p /mnt/nfs/etc/dhcp /mnt/nfs/var/lib/dhcpd
----
. Set the owner of the `/mnt/nfs` and sub-directories to `foreman-proxy`:
+
[options="nowrap"]
----
# chown -R foreman-proxy /mnt/nfs
----
. Verify that the NFS server exports the required directories:
+
[options="nowrap" subs="+quotes"]
----
# showmount -e _DHCP_Server_FQDN_
----
. Edit the `/etc/fstab` file, and add entries for the NFS shares to mount them automatically when the system boots:
+
[options="nowrap" subs="+quotes"]
----
_<dhcp_server_fqdn>_:/exports/etc/dhcp       /mnt/nfs/etc/dhcp       nfs  ro,vers=3,auto,nosharecache,context="system_u:object_r:dhcp_etc_t:s0"     0 0

_<dhcp_server_fqdn>_:/exports/var/lib/dhcpd  /mnt/nfs/var/lib/dhcpd  nfs  ro,vers=3,auto,nosharecache,context="system_u:object_r:dhcpd_state_t:s0"  0 0
----
. Mount the NFS shares:
+
[options="nowrap"]
----
# mount /mnt/nfs/etc/dhcp/
# mount /mnt/nfs/var/lib/dhcpd/
----
. Optional: Verify that the `foreman-proxy` user can access the files on the NFS server:
.. Switch to the `foreman-proxy` user:
+
[options="nowrap"]
----
# su foreman-proxy -s /bin/bash
----
.. Display the `/mnt/nfs/etc/dhcp/dhcpd.conf` file:
+
[options="nowrap"]
----
$ cat /mnt/nfs/etc/dhcp/dhcpd.conf
----
.. Display the `/mnt/nfs/var/lib/dhcpd/dhcpd.leases` file:
+
[options="nowrap"]
----
$ cat /mnt/nfs/var/lib/dhcpd/dhcpd.leases
----
.. Log out the `foreman-proxy` user to switch back to the `root` user:
+
[options="nowrap"]
----
$ exit
----
. Configure {ProjectServer} or {SmartProxyServer} to use the DHCP server:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--foreman-proxy-dhcp true \
--foreman-proxy-dhcp-provider remote_isc \
--enable-foreman-proxy-plugin-dhcp-remote-isc \
--foreman-proxy-dhcp-server _<dhcp_server_fqdn>_ \
--foreman-proxy-plugin-dhcp-remote-isc-dhcp-config /mnt/nfs/etc/dhcp/dhcpd.conf \
--foreman-proxy-plugin-dhcp-remote-isc-dhcp-leases /mnt/nfs/var/lib/dhcpd/dhcpd.leases \
--foreman-proxy-plugin-dhcp-remote-isc-key-name omapi_key \
--foreman-proxy-plugin-dhcp-remote-isc-key-secret _<key_secret>_ \
--foreman-proxy-plugin-dhcp-remote-isc-omapi-port 7911
----
. For each affected {SmartProxy}, update the configuration of that {SmartProxy} in the {ProjectWebUI}.
See xref:associating-the-dhcp-service-with-a-subnet[].

