:_mod-docs-content-type: PROCEDURE

[id="configuring-{smart-proxy-context}-for-uefi-http-booting"]
= Configuring {SmartProxy} for UEFI HTTP booting

You can provision hosts from {Project} by using the UEFI HTTP Boot if the hosts have this capability.
Configure your {SmartProxy} for UEFI HTTP booting.

.Prerequisites
* Ensure that your environment meets the requirements for HTTP booting.
ifndef::orcharhino[]
For more information, see {PlanningDocURL}http-booting[HTTP booting] in _{PlanningDocTitle}_.
endif::[]

.Procedure
ifndef::satellite[]
. Enable `foreman-proxy-http`, `foreman-proxy-httpboot`, and `foreman-proxy-tftp` features.
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--foreman-proxy-http true \
--foreman-proxy-httpboot true \
--foreman-proxy-tftp true
----
. Ensure that the {SmartProxy} has TFTP and HTTPBoot features recognized.
In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}* and click on {SmartProxy} to see the list of recognized features.
Click *Refresh Features* if any of the features are missing.
endif::[]
. Ensure that {SmartProxy} is associated with the provisioning subnet.
In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets* > *Edit Subnet* > *{SmartProxies}* and select the {SmartProxy} for both *TFTP* and *HTTPBoot* options.
. Click *OK* to save.

[role="_additional-resources"]
.Next steps
* xref:creating-hosts-with-uefi-http-boot-provisioning[]
