:_mod-docs-content-type: PROCEDURE

[id="Adding_Packages_to_a_Host_Collection_{context}"]
= Adding packages to a host collection

[role="_abstract"]
The following procedure shows how to add packages to host collections.

.Prerequisites
* The content to be added should be available in one of the existing repositories or added prior to this procedure.
* Content should be promoted to the environment where the hosts are assigned.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Host Collections*.
. Select the host collection where the package should be added.
. On the *Collection Actions* tab, click *Package Installation, Removal, and Update*.
. To update all packages, click *Update All Packages* to use the default method.
Alternatively, select the drop-down icon to the right of the button to select a method to use.
Selecting the *via remote execution {endash} customize first* menu entry will take you to the *Job invocation* page where you can customize the action.
. Select the *Package* or *Package Group* radio button as required.
. In the field provided, specify the package or package group name.
Then click:
+
* *Install* {endash} to install a new package using the default method.
Alternatively, select the drop-down icon to the right of the button and select a method to use.
Selecting the *via remote execution {endash} customize first* menu entry will take you to the *Job invocation* page where you can customize the action.
* *Update* {endash} to update an existing package in the host collection using the default method.
Alternatively, select the drop-down icon to the right of the button and select a method to use.
Selecting the *via remote execution {endash} customize first* menu entry will take you to the *Job invocation* page where you can customize the action.
