:_mod-docs-content-type: PROCEDURE

[id="preparing-for-disaster-recovery-with-active-and-passive-project-server-with-external-storage"]
= Preparing for disaster recovery with active and passive {ProjectServer} with external storage

ifdef::satellite[]
Create your passive {ProjectServer} as a clone of your active {ProjectServer}.
endif::[]
ifndef::satellite[]
Create your passive {ProjectServer} as a backup of your active {ProjectServer}.
endif::[]
Ensure that the `/var/lib/pulp` and `{postgresql-lib-dir}` directories on your shared storage are available to both servers.

.Procedure
. Replicate the `/var/lib/pulp` and `{postgresql-lib-dir}` directories from the active {ProjectServer} to your shared storage.
ifdef::satellite[]
. Clone your active {ProjectServer}.
For more information, see xref:cloning-{project-context}-server[].
endif::[]
ifndef::satellite[]
. Back up your active {ProjectServer} and restore it on a system that will serve as your passive {ProjectServer}.
For more information, see xref:backing-up-{project-context}-server-and-{smart-proxy-context}_admin[] and xref:restoring-{project-context}-server-or-{smart-proxy-context}-from-a-backup_admin[].
endif::[]
. Keep the source server powered on.
Power off the new server.
+
The source server remains your active primary server, while the new server becomes the passive secondary server.
. Determine how you want to attach the database content on the shared storage to your passive server:
* If you mount the storage directly on both your active and passive server, the servers will always see the same, up-to-date content.
* If you mount the storage only on your active server, the passive server will access the data only if it takes over as the active server.

.Verification
Perform this test in an isolated staging environment:

. Mimic a full outage on the active server.
To make sure the active server is inaccessible, you can turn the machine off, halt the virtual machine (VM) if your server runs on a VM, or isolate the machine by using a firewall.
. Switch DNS records of the active server with the DNS records of the passive server.
. Verify that your passive server can access the data stored on your shared storage.
. Assess the functionality of the test {ProjectServer}.
For more information, see xref:retrieving-the-status-of-services-by-using-web-ui[].
. Perform these verification checks regularly.

ifdef::satellite[]
.Additional resources
* For more information on mounting directories, see link:{RHELDocsBaseURL}9/html-single/managing_file_systems/index#mounting-file-systems-on-demand_managing-file-systems[Mounting file systems on demand] in _{RHEL}{nbsp}9 Managing file systems_.
endif::[]
