:_mod-docs-content-type: PROCEDURE

[id="setting-up-flatpak-remote-for-{smart-proxy-context}"]
= Setting up Flatpak remote for {SmartProxy}

[role="_abstract"]
Configure {SmartProxyServers} to synchronize and distribute Flatpak repositories to managed hosts.

[NOTE]
====
{SmartProxies} synchronize Flatpaks and make them available to all hosts, but not organizations, content views, or lifecycle environments. 
Clients receive the latest Flatpaks synchronized on the {SmartProxy} globally.
====

.Prerequisites
* Synchronize Flatpak repositories to the {SmartProxy}.
For more information, see xref:repository-synchronization[].

.Procedure
. On the managed host, add the {SmartProxy} as a Flatpak remote:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ flatpak remote-add --authenticator-name=org.flatpak.Authenticator.Oci katello oci+https://{smartproxy-example-com}/
----
. Log in the host to the container registry using one of the following methods: 
* Certificate authentication
** When registering a host to {SmartProxy}, select the *Set up container registry certs* checkbox.
** If the host is already registered, run the *Flatpak - Login to registry via podman* job template on the host.
Set *Set up certificate authentication* to `true` and enter the URL of your {SmartProxy} as the registry URL.
* Using Podman
** Log in using Podman:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ podman login _{foreman-example-com}_
----
For more information about logging in using Podman, see xref:Configuring_podman_to_trust_the_CA_{context}[].
+
You might need to log in to the registry again if you have not saved your credentials.
. Optional: Save your credentials permanently using one of the following options:
* To save the credentials for the current user:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ cp $XDG_RUNTIME_DIR/containers/auth.json $HOME/.config/flatpak/oci-auth.json
----
* To save the credentials system-wide:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ cp $XDG_RUNTIME_DIR/containers/auth.json /etc/flatpak/oci-auth.json
----
. Install your application.
For example, to install the Mozilla Firefox Flatpak:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ flatpak install firefox
----
