[id="configuring-dns-dhcp-and-tftp_{context}"]

= Configuring DNS, DHCP, and TFTP on {ProductName}

To configure the DNS, DHCP, and TFTP services on {ProductName}, use the `satellite-installer` command with the options appropriate for your environment.

To view a complete list of configurable options, enter the `satellite-installer --scenario satellite --help` command.

Any changes to the settings require entering the `satellite-installer` command again. You can enter the command multiple times and each time it updates all configuration files with the changed values.

.Prerequisites

Before you can configure DNS, DHCP and TFTP services, ensure that the following conditions are met:

ifeval::["{context}" == "satellite"]
* Ensure that the following information is available to you:
** DHCP IP address ranges
** DHCP gateway IP address
** DHCP nameserver IP address
** DNS information
** TFTP server name

* Use the FQDN instead of the IP address where possible in case of network changes.
endif::[]

ifeval::["{context}" == "capsule"]
* You must have the correct network name (`dns-interface`) for the DNS server.
* You must have the correct interface name (`dhcp-interface`) for the DHCP server.
endif::[]

* Contact your network administrator to ensure that you have the correct settings.

.Procedure

* Enter the `satellite-installer` command with the options appropriate for your environment. The following example shows configuring full provisioning services:

ifeval::["{context}" == "satellite"]
+
[options="nowrap" subs="+quotes"]
----
# satellite-installer --scenario satellite \
--foreman-proxy-dns true \
--foreman-proxy-dns-managed true \
--foreman-proxy-dns-interface __eth0__ \
--foreman-proxy-dns-zone __example.com__ \
--foreman-proxy-dns-forwarders __172.17.13.1__ \
--foreman-proxy-dns-reverse __13.17.172.in-addr.arpa__ \
--foreman-proxy-dhcp true \
--foreman-proxy-dhcp-managed true \
--foreman-proxy-dhcp-interface __eth0__ \
--foreman-proxy-dhcp-range "__172.17.13.100__ __172.17.13.150__" \
--foreman-proxy-dhcp-gateway __172.17.13.1__ \
--foreman-proxy-dhcp-nameservers __172.17.13.2__ \
--foreman-proxy-tftp true \
--foreman-proxy-tftp-managed true \
--foreman-proxy-tftp-servername $(hostname)
----

You can monitor the progress of the `satellite-installer` command displayed in your prompt. You can view the logs in `/var/log/foreman-installer/satellite.log`. You can view the settings used, including the `admin_password` parameter, in the `/etc/foreman-installer/scenarios.d/satellite-answers.yaml` file.
endif::[]

ifeval::["{context}" == "capsule"]
+
[options="nowrap" subs="+quotes"]
----
# satellite-installer --scenario capsule \
--foreman-proxy-dns true \
--foreman-proxy-dns-managed true \
--foreman-proxy-dns-interface _eth0_ \
--foreman-proxy-dns-zone _example.com_ \
--foreman-proxy-dns-forwarders _172.17.13.1_ \
--foreman-proxy-dns-reverse _13.17.172.in-addr.arpa_ \
--foreman-proxy-dhcp true \
--foreman-proxy-dhcp-managed true \
--foreman-proxy-dhcp-interface _eth0_ \
--foreman-proxy-dhcp-range "_172.17.13.100_ _172.17.13.150_" \
--foreman-proxy-dhcp-gateway _172.17.13.1_ \
--foreman-proxy-dhcp-nameservers _172.17.13.2_ \
--foreman-proxy-tftp true \
--foreman-proxy-tftp-managed true \
--foreman-proxy-tftp-servername $(hostname)
----
endif::[]


For more information about configuring DHCP, DNS, and TFTP services, see the link:https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersion}/html/provisioning_guide/configuring_networking#Configuring_Networking-Configuring_Network_Services_for_PXE_Boot[Configuring Network Services] section in the _Provisioning Guide_.

ifeval::["{context}" == "satellite"]
For more information about disabling the DNS, DHCP, and TFTP services in Satellite and managing them manually, see xref:disabling_dns_dhcp_tftp_for_unmanaged_networks[Disabling DNS, DHCP, and TFTP for Unmanaged Networks].

For more information about configuring external services, see xref:configuring_external_services[Configuring External Services].
endif::[]
