:_mod-docs-content-type: PROCEDURE

[id="Deleting_a_Location_{context}"]
= Deleting a location

ifdef::foreman-deb,foreman-el[]
You can delete a location if the location is not associated with any host groups.
If there are any host groups associated with the location you are about to delete, remove them by navigating to *Administer* > *Locations* and clicking the relevant location.
endif::[]
ifdef::katello,orcharhino,satellite[]
You can delete a location if the location is not associated with any lifecycle environments or host groups.
If there are any lifecycle environments or host groups associated with the location you are about to delete, remove them by navigating to *Administer* > *Locations* and clicking the relevant location.
endif::[]
ifndef::orcharhino[]
Do not delete the default location created during installation because the default location is a placeholder for any unassociated hosts in the {Project} environment.
endif::[]
There must be at least one location in the environment at any given time.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Locations*.
. Select *Delete* from the list to the right of the name of the location you want to delete.
. Click *OK* to delete the location.

.CLI procedure
. View all locations:
+
[subs="+quotes"]
----
$ hammer location list
----
+
From the output, note the ID of the location that you want to delete.
. Delete a location:
+
[subs="+quotes"]
----
$ hammer location delete --id _My_Location_ID_
----
