:_mod-docs-content-type: PROCEDURE

[id="generating-a-full-host-boot-disk-by-using-web-ui"]
= Generating a full host boot disk by using {ProjectWebUI}

[role="_abstract"]
You can generate a full boot disk for a specific host.

.Prerequisites
ifdef::katello,satellite,orcharhino[]
include::snip_prerequisite-activation-key-available.adoc[]
+
include::snip_prerequisite-project-client-repository-ak.adoc[]
endif::[]
ifndef::satellite[]
* Ensure that the operating system has PXELinux and PXEGrub2 templates associated.
For more information, see xref:associating-templates-with-operating-systems-by-using-web-ui[].
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Create Host*.
+
include::snip_steps-create-a-host-tab-host.adoc[]
+
include::snip_steps-create-a-host-tab-interfaces.adoc[]
. Click the *Operating System* tab.
Verify that all fields contain correct values.
. Click *Resolve* in *Provisioning Templates* to check the new host can identify the right provisioning templates to use.
+
For more information about associating provisioning templates, see xref:associating-templates-with-operating-systems-by-using-web-ui[].
ifdef::katello,satellite,orcharhino[]
+
include::snip_step-parameter-ak.adoc[]
endif::[]
. Click *Submit* to save the host details.
This creates a host entry and the host details page appears.
. Download the boot disk from {ProjectServer}.
On the host details page, click the vertical ellipsis and select *Full host '_My_Host_Name_' image*.
