:_mod-docs-content-type: PROCEDURE

[id="enabling-connections-to-capsule_{context}"]
= Enabling connections from {ProjectServer} and clients to a {SmartProxyServer}

On the base operating system on which you want to install {SmartProxy}, you must enable incoming connections from {ProjectServer} and clients to {SmartProxyServer} and make these rules persistent across reboots.

include::snip_firewalld.adoc[]

.Procedure
ifdef::katello,satellite,orcharhino[]
. Open the ports for clients on {SmartProxyServer}:
+
[options="nowrap"]
----
# firewall-cmd \
--add-port="8000/tcp" \
--add-port="9090/tcp"
----
endif::[]
. Allow access to services on {SmartProxyServer}:
+
[options="nowrap"]
----
# firewall-cmd \
--add-service=dns \
--add-service=dhcp \
--add-service=tftp \
ifdef::katello,satellite,orcharhino[]
--add-service=http \
--add-service=https \
endif::[]
ifndef::katello,satellite,orcharhino[]
--add-service=foreman-proxy \
endif::[]
--add-service=puppetmaster
----
. Make the changes persistent:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# firewall-cmd --runtime-to-permanent
----

.Verification
* Enter the following command:
+
[options="nowrap"]
----
# firewall-cmd --list-all
----

ifndef::foreman-deb[]
For more information, see {RHELDocsBaseURL}9/html/configuring_firewalls_and_packet_filters/using-and-configuring-firewalld_firewall-packet-filters[Using and configuring firewalld] in _{RHEL}{nbsp}9 Configuring firewalls and packet filters_.
endif::[]