:_mod-docs-content-type: PROCEDURE

[id="importing-suse-products-by-using-web-ui"]
= Importing SUSE products by using {ProjectWebUI}

[role="_abstract"]
Use this procedure to import products from SUSE into {Project} from {ProjectWebUI}.

.Prerequisites
* You have added your SCC account to {Project}.
For more information, see xref:adding-an-scc-account-to-{project-context}-by-using-web-ui[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content > SUSE Subscriptions*.
. Click *Select products* on your previously synchronized SCC account.
. Use the *Select Product*, *Select Version*, and *Select Architecture* lists to filter all available SUSE products.
+
Note that each filter depends on the previous selection.
. Click *Search* to apply the filter.
. Select all SUSE products you want to synchronize to {Project}.
+
You can select individual repositories from the *Filter repositories* list.
By default, _debug_ and _source_ repositories are excluded.
. Click *Add product(s)* to create the selected SUSE products in {Project}.
+
Note that the SCC Manager plugin can only add, but not remove products from {Project}.
. Optional: Click on the task ID to follow the creation of the selected products in {Project}.
