[id="creating-linked-lifecycle-environments"]
= Creating linked lifecycle environments

Use this example to create a path of lifecycle environments.
This procedure uses the default Library environment with ID `1` as the starting point for creating lifecycle environments.

[id="api-creating-linked-lifecycle-environments"]
.API procedure
. Choose an existing lifecycle environment that you want to use as a starting point.
List the environment by using its ID.
In this case, the environment with ID `1`:
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--request GET \
--user _My_User_Name_:__My_Password__ \
https://_{foreman-example-com}_/katello/api/environments/1 \
| python3 -m json.tool
----
+
Example response:
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
  _output omitted_
   *"id": 1,*
   *"label": "Library",*
	_output omitted_
    *"prior": null,*
    *"successor": null,*
  _output truncated_
----
. Create a JSON file, for example, `life-cycle.json`, with the following content:
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
{"organization_id":1,"label":"api-dev","name":"API Development","prior":1}
----
. Create a lifecycle environment by using the `prior` option set to `1`.
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header "Accept:application/json" \
--header "Content-Type:application/json" \
--request POST \
--user _My_User_Name_:__My_Password__ \
--data @life-cycle.json \
https://_{foreman-example-com}_/katello/api/environments \
| python3 -m json.tool
----
+
Example response:
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
      _output omitted_
    "description": null,
    *"id": 2,*
    "label": "api-dev",
    "library": false,
    "name": "API Development",
    "organization": {
        "id": 1,
        "label": "Default_Organization",
        "name": "Default Organization"
    },
    "permissions": {
        "destroy_lifecycle_environments": true,
        "edit_lifecycle_environments": true,
        "promote_or_remove_content_views_to_environments": true,
        "view_lifecycle_environments": true
    },
   *"prior":* {
        *"id": 1,*
        "name": "Library"
    },
    _output truncated_
----
+
In the command output, you can see the ID for this lifecycle environment is `2`, and the lifecycle environment before this one is `1`.
Use the lifecycle environment with ID `2` to create a successor to this environment.
. Edit the previously created `life-cycle.json` file to update the `label`, `name`, and `prior` values.
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
{"organization_id":1,"label":"api-qa","name":"API QA","prior":2}
----
. Create a lifecycle environment using the `prior` option set to `2`.
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl \
--header "Accept:application/json" \
--header "Content-Type:application/json" \
--request POST \
--user _My_User_Name_:__My_Password__ \
--data @life-cycle.json \
https://_{foreman-example-com}_/katello/api/environments \
| python3 -m json.tool
----
+
Example response:
+
[source, none, options="nowrap", subs="+quotes,attributes"]
----
      _output omitted_
   "description": null,
   *"id": 3,*
    "label": "api-qa",
    "library": false,
    "name": "API QA",
    "organization": {
        "id": 1,
        "label": "Default_Organization",
        "name": "Default Organization"
    },
    "permissions": {
        "destroy_lifecycle_environments": true,
        "edit_lifecycle_environments": true,
        "promote_or_remove_content_views_to_environments": true,
        "view_lifecycle_environments": true
    },
   *"prior":* {
        *"id": 2,*
        "name": "API Development"
    },
    "successor": null,
    _output truncated_
----
+
In the command output, you can see the ID for this lifecycle environment is `3`, and the lifecycle environment before this one is `2`.
