[id="using-a-synced-kickstart-repository_{context}"]
= Using a Synced Kickstart Repository for a Host's Operating System

ifdef::foreman-el,katello[]
The following feature is provided by the Katello plug-in.
endif::[]

{Project} contains a set of synchronized kickstart repositories that you use to install the provisioned host's operating system.
For more information about adding repositories, see {ContentManagementDocURL}Synchronizing_Repositories_content-management[Syncing Repositories] in the _Content Management Guide_.

Use this procedure to set up a kickstart repository.

.Prerequisites
You must enable both *BaseOS* and *Appstream Kickstart* before provisioning.

.Procedure
. Add the synchronized kickstart repository that you want to use to the existing Content View, or create a new Content View and add the kickstart repository.
+
For {RHEL} 8, ensure that you add both *{RHEL} 8 for x86_64 - AppStream Kickstart x86_64 8* and *{RHEL} 8 for x86_64 - BaseOS Kickstart x86_64 8* repositories.
ifdef::satellite,orcharhino[]
+
If you use a disconnected environment, you must import the Kickstart repositories from a {RHEL} binary DVD.
For more information, see {ContentManagementDocURL}Importing_Kickstart_Repositories_content-management[Importing Kickstart Repositories] in the _Content Management Guide_.
endif::[]
+
. Publish a new version of the Content View where the kickstart repository is added and promote it to a required lifecycle environment.
For more information, see {ContentManagementDocURL}Managing_Content_Views_content-management[Managing Content Views] in the _Content Management Guide_.
. When you create a host, in the *Operating System* tab, for *Media Selection*, select the *Synced Content* checkbox.

To view the kickstart tree, enter the following command:

[subs="+quotes"]
----
# hammer medium list --organization "_My_Organization_"
----
