:_mod-docs-content-type: PROCEDURE

[id="creating-a-composite-content-view-by-using-cli"]
= Creating a composite content view by using Hammer CLI

[role="_abstract"]
Use this procedure to create a composite content view by using Hammer CLI.

.Procedure
. Before you create the composite content views, list the version IDs for your existing content views:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view version list \
--organization "_My_Organization_"
----
. Create a new composite content view.
When the `--auto-publish` option is set to `yes`, the composite content view is automatically republished when a content view it includes is republished:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view create \
--composite \
--auto-publish yes \
--name "_Example_Composite_Content_View_" \
--description "Example composite content view" \
--organization "_My_Organization_"
----
. Add a content view to the composite content view.
You can identify content view, content view version, and Organization in the commands by either their ID or their name.
To add multiple content views to the composite content view, repeat this step for every content view you want to include.
+
* If you have the *Always update to latest version* option enabled for the content view:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
$ hammer content-view component add \
--component-content-view-id _Content_View_ID_ \
--composite-content-view "_Example_Composite_Content_View_" \
--latest \
--organization "_My_Organization_"
----
* If you have the *Always update to latest version* option disabled for the content view:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
$ hammer content-view component add \
--component-content-view-id _Content_View_ID_ \
--composite-content-view "_Example_Composite_Content_View_" \
--component-content-view-version-id _Content_View_Version_ID_ \
--organization "_My_Organization_"
----
. Publish the composite content view:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view publish \
--name "_Example_Composite_Content_View_" \
--description "Initial version of composite content view" \
--organization "_My_Organization_"
----
. Promote the composite content view across all environments:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-view version promote \
--content-view "_Example_Composite_Content_View_" \
--version 1 \
--to-lifecycle-environment "Development" \
--organization "_My_Organization_"
$ hammer content-view version promote \
--content-view "_Example_Composite_Content_View_" \
--version 1 \
--to-lifecycle-environment "Testing" \
--organization "_My_Organization_"
$ hammer content-view version promote \
--content-view "_Example_Composite_Content_View_" \
--version 1 \
--to-lifecycle-environment "Production" \
--organization "_My_Organization_"
----
