:_mod-docs-content-type: PROCEDURE

[id="Registering_Proxy_to_Server_{context}"]
= Registering to {ProjectServer}

[role="_abstract"]
Register the base operating system on which you want to install {SmartProxyServer} to {ProjectServer}.
This enables you to download the installation packages from your synchronized repositories.

.Prerequisites
* Prerequisites for Red{nbsp}Hat subscription manifest:
** On {ProjectServer}, a manifest must be installed and it must contain the appropriate repositories for the organization you want {SmartProxy} to belong to.
** The manifest must contain repositories for the base operating system on which you want to install {SmartProxy}, as well as any clients that you want to connect to {SmartProxy}.
** The repositories must be synchronized.
+
For more information on manifests and repositories, see {ContentManagementDocURL}Managing_Red_Hat_Subscriptions_content-management[Managing Red Hat Subscriptions] in _{ContentManagementDocTitle}_.
* Prerequisites for HTTP proxy and network:
** The {ProjectServer} base operating system must be able to resolve the host name of the {SmartProxy} base operating system and vice versa.
** Ensure HTTPS connection using client certificate authentication is possible between {SmartProxyServer} and {ProjectServer}.
HTTP proxies between {SmartProxyServer} and {ProjectServer} are not supported.
** You must configure the host and network-based firewalls accordingly.
ifeval::["{context}" == "load-balancing"]
For more information, see {InstallingSmartProxyDocURL}opening-required-ports[Opening required ports in _{InstallingSmartProxyDocTitle}_].
endif::[]
ifeval::["{context}" == "installing-capsule-server"]
For more information, see xref:common/modules/proc_opening-required-ports.adoc#opening-required-ports[].
endif::[]

include::snip_host-registration-steps.adoc[]
