:_mod-docs-content-type: PROCEDURE

[id="viewing-logs-with-journalctl_{context}"]
= Viewing service logs with journalctl

[role="_abstract"]
You can view and filter logs for any containerized {Project} service by using `journalctl` with the appropriate unit or syslog identifier filter.
Monitoring service output helps you verify service health, troubleshoot issues, and follow log output in real time.

.Prerequisites
* Containerized {ProjectServer} is installed and running.
* You have root access to the {ProjectServer} host.

.Procedure
. View logs for a specific `systemd` unit by using the `-u` option.
+
Use this method for Podman container services such as `foreman`, `candlepin`, `foreman-proxy`, and `valkey`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -u _service_name_
----
+
For example, to view Foreman logs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -u foreman
----
. View logs for a specific syslog identifier tag by using the `-t` option.
+
Use this method for `httpd` virtual host logs that use `systemd-cat` for log routing:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -t _tag_name_
----
+
For example, to view HTTPS access logs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -t httpd-ssl-access
----
. To filter logs by time range, use the `--since` and `--until` options:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -u foreman --since "2025-01-15 08:00:00" --until "2025-01-15 09:00:00"
----
. To follow logs in real time, add the `-f` option:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -u foreman -f
----
. To combine multiple service filters in a single query, specify multiple `-u` or `-t` options:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -u foreman -u foreman-proxy -f
----
. To filter logs by priority level, use the `-p` option:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# journalctl -u foreman -p err
----
+
Valid priority values include `emerg`, `alert`, `crit`, `err`, `warning`, `notice`, `info`, and `debug`.

.Verification
* Confirm that log output appears for the targeted service.
If no output appears, verify that the service is running:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl status _service_name_
----

.Additional resources
* For the full list of service identifiers, see xref:service-journald-identifiers_{context}[].
* For a mapping of traditional log paths to journalctl commands, see xref:traditional-vs-containerized-logging_{context}[].
ifdef::satellite[]
* {RHELDocsBaseURL}9/html-single/configuring_basic_system_settings/index#viewing-logs-using-the-command-line_assembly_troubleshooting-problems-using-log-files[Viewing logs using the command line in _{RHEL}{nbsp}9 Configuring basic system settings_]
endif::[]
