[id="puppet_guide_overriding_puppet_parameters_location_based_{context}"]
= Overriding Puppet Parameters Location Based

You can use groups of hosts to override Puppet parameters for multiple hosts at once.
The following examples chooses the _location_ context to illustrate setting context based parameters.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure > Classes* and select the *Smart Class Parameter* tab.
. Choose a parameter.
. Use the *Order* list to define the hierarchy of the Puppet parameters.
The individual host (`fqdn`) marks the most and the location context (`location`) the least relevant.
. Check *Merge Overrides* if you want to add all further matched parameters after finding the first match.
. Check *Merge Default* if you want to also include the default value even if there are more specific values defined.
. Check *Avoid Duplicates* if you want to create a list of unique values for the selected parameter.
. The *matcher* field requires an _attribute type_ from the _order_ list.
For example, you can choose `Paris` as _location_ context and set the value to French ntp servers.
. Use the *Add Matcher* button to add more matchers.
. Click *Submit* to save the changes.
