:_mod-docs-content-type: PROCEDURE

[id="Performing_an_Incremental_Backup_{context}"]
= Performing an incremental backup

[role="_abstract"]
Use this procedure to perform an offline backup of any changes since a previous backup.

To perform incremental backups, you must perform a full backup as a reference to create the first incremental backup of a sequence.
Keep the most recent full backup and a complete sequence of incremental backups to restore from.

.Prerequisites
* Ensure that your backup location has sufficient available disk space to store the backup.
ifdef::katello,orcharhino,satellite[]
For more information, see xref:Estimating_the_Size_of_a_Backup_{context}[].
endif::[]

.Procedure
. Perform a full offline backup:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline _/var/backup_directory_
----
. Create a directory within your backup directory to store the first incremental backup:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline --incremental _/var/backup_directory/full_backup_ _/var/backup_directory_
----
. Create the second incremental backup by including the path to the first incremental backup to indicate the starting point for the next increment.
This creates a directory for the second incremental backup in your backup directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline --incremental _/var/backup_directory/first_incremental_backup_ _/var/backup_directory_
----
. Optional: If you want to point to a different version of the backup, and make a series of increments with that version of the backup as the starting point, you can do this at any time.
For example, if you want to make a new incremental backup from the full backup rather than the first or second incremental backup, point to the full backup directory:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline --incremental _/var/backup_directory/full_backup_ _/var/backup_directory_
----
