[id="Installing_the_Katello_Agent_{context}"]
= Installing the Katello Agent

You can install the Katello agent to remotely update {Project} clients.

[NOTE]
====
The Katello agent is deprecated and will be removed in a future {Project} version.
Migrate your processes to use the remote execution feature to update clients remotely.
For more information, see {ManagingHostsDocURL}Migrating_From_Katello_Agent_to_Remote_Execution_managing-hosts[Migrating from Katello Agent to Remote Execution] in _{ManagingHostsDocTitle}_.
====

The `katello-agent` package depends on the `gofer` package that provides the `goferd` service.

.Prerequisites
ifdef::satellite[]
* You have enabled the {project-client-name} repository on {ProjectServer}.
For more information, see {InstallingServerDocURL}Enabling_the_Client_Repository_{project-context}[Enabling the {project-client-name} Repository] in _{InstallingServerDocTitle}_.
* You have synchronized the {project-client-name} repository on {ProjectServer}.
For more information, see {InstallingServerDocURL}synchronizing-the-satellite-tools-repository_{project-context}[Synchronizing the {project-client-name} Repository] in _{InstallingServerDocTitle}_.
endif::[]
* You have enabled the {project-client-name} repository on the client.

.Procedure
. Install the `katello-agent` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {client-package-install} katello-agent
----
. Start the `goferd` service:
+
[options="nowrap" subs="+quotes,attributes"]
----
# systemctl start goferd
----
