:_mod-docs-content-type: PROCEDURE

[id="creating-a-user-by-using-web-ui"]
= Creating a user by using {ProjectWebUI}

[role="_abstract"]
Use this procedure to create a user from the {ProjectWebUI}.

Users are strictly confined to their assigned organizations and locations.
Users can only access and assign resources within the organizations and locations they belong to.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Users*.
. Click *Create User*.
. Enter the account details for the new user.
. Click *Submit* to create the user.
+
The user account details that you can specify include the following:
+
* On the *User* tab, select an authentication source from the *Authorized by* list:
** *INTERNAL*: to manage the user inside {ProjectServer}.
** *EXTERNAL*: to manage the user with external authentication.
For more information, see {ConfiguringUserAuthenticationDocURL}[_{ConfiguringUserAuthenticationDocTitle}_].
* On the *Organizations* tab, select organizations for the user.
Select the default organization from the *Default on login* list.
{Project} uses this organization for the user after login.
* On the *Locations* tab, select locations for the user.
Select the default location from the *Default on login* list.
{Project} uses this location for the user after login.
