:_mod-docs-content-type: PROCEDURE

[id="Changing_the_Lifecycle_Environment_or_Content_View_of_a_Host_Collection_{context}"]
= Changing the lifecycle environment or content view of a host collection

[role="_abstract"]
The following procedure shows how to change the assigned lifecycle environment or content view of host collections.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Host Collection*.
. Selection the host collection where the lifecycle environment or content view should be changed.
. On the *Collection Actions* tab, click *Change assigned Lifecycle Environment or Content View*.
. Select the lifecycle environment to be assigned to the host collection.
. Select the required content view from the list.
. Click *Assign*.
+
[NOTE]
====
The changes take effect in approximately 4 hours.
To make the changes take effect immediately, on the host, enter the following command:
----
# subscription-manager refresh
----
You can use remote execution to run this command on multiple hosts at the same time.
====
