[id="Creating_KernelCare_Repositories_for_{client-os-context}_{client-os-major}_{context}"]
= Creating KernelCare repositories for {client-os} {client-os-major}

You need to provide the KernelCare client on your hosts to live-patch their Linux kernel.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Click *Create Product* to create a product named `KernelCare {client-os}`.
For more information, see {ContentManagementDocURL}Creating_a_Custom_Product_content-management[Creating a product] in _{ContentManagementDocTitle}_.
. On the *Repositories* tab, click *New Repository* to create a repository of type `yum` as follows:
+
* *Name*: `KernelCare {client-os} {client-os-major}`
* *Upstream URL*: `https://repo.cloudlinux.com/kernelcare/{client-os-major}/x86_64/`
* Optional: Add the KernelCare GPG pub key as content credential: `https://repo.cloudlinux.com/kernelcare/RPM-GPG-KEY-KernelCare`.

+
For more information, see {ContentManagementDocURL}Adding_Custom_RPM_Repositories_content-management[Adding RPM Repositories] in _{ContentManagementDocTitle}_.
