[id="Synchronizing_the_Client_Repository_{context}"]
= Synchronizing the {project-client-name} Repository

Use this section to synchronize the {project-client-name} repository from the Red Hat Content Delivery Network (CDN) to your {Project}.
This repository provides the `katello-agent`, `katello-host-tools`, and `puppet` packages for clients registered to {ProjectServer}.
Select the applicable operating system and version to synchronize the client repository.

* xref:#synchronizing-repos-rhel-9[{RHEL} 9]
* xref:#synchronizing-repos-rhel-8[{RHEL} 8]
* xref:#synchronizing-repos-rhel-7[{RHEL} 7]

== [[synchronizing-repos-rhel-9]]{RHEL} 9

To use the CLI instead of the {ProjectWebUI}, see the xref:CLI_Synchronizing_the_Client_Repository_rhel_9{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
+
A list of product repositories available for synchronization is displayed.
. Click the arrow next to the *{RHEL} for x86_64* product to view available content.
. Select *{Team} {project-client-name} for RHEL 9 x86_64 RPMs*.
. Click *Synchronize Now*.

[id="CLI_Synchronizing_the_Client_Repository_rhel_9{context}"]
.CLI procedure
* Synchronize your {project-client-name} repository using the `hammer repository synchronize` command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--name '{Team} {project-client-name} for RHEL 9 x86_64 RPMs' \
--organization _"My_Organization"_ \
--product '{RHEL} for x86_64'
----

== [[synchronizing-repos-rhel-8]]{RHEL} 8

To use the CLI instead of the {ProjectWebUI}, see the xref:CLI_Synchronizing_the_Client_Repository_rhel_8{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
+
A list of product repositories available for synchronization is displayed.
. Click the arrow next to the *{RHEL} for x86_64* product to view available content.
. Select *{Team} {project-client-name} for RHEL 8 x86_64 RPMs*.
. Click *Synchronize Now*.

[id="CLI_Synchronizing_the_Client_Repository_rhel_8{context}"]
.CLI procedure
* Synchronize your {project-client-name} repository using the `hammer repository synchronize` command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--name '{Team} {project-client-name} for RHEL 8 x86_64 RPMs' \
--organization _"My_Organization"_ \
--product '{RHEL} for x86_64'
----

== [[synchronizing-repos-rhel-7]]{RHEL} 7

To use the CLI instead of the {ProjectWebUI}, see the xref:CLI_Synchronizing_the_Client_Repository_rhel_7{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
+
A list of product repositories available for synchronization is displayed.
. Click the arrow next to the *{RHEL} Server* product to view available content.
. Select *{project-client-name} (for RHEL 7 Server) RPMs x86_64*.
. Click *Synchronize Now*.

[id="CLI_Synchronizing_the_Client_Repository_rhel_7{context}"]
.CLI procedure
* Synchronize your {project-client-name} repository using the `hammer repository synchronize` command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--async \
--name 'Red Hat {project-client-name} for RHEL 7 Server RPMs x86_64' \
--organization _"My_Organization"_ \
--product 'Red Hat Enterprise Linux Server'
----
