[id="deploying-a-custom-ssl-certificate-to-satellite-server_{context}"]

= Deploying a Custom SSL Certificate to Satellite Server

Use this procedure to configure your Satellite{nbsp}Server to use a custom SSL certificate signed by a Certificate Authority. The `katello-certs-check` command validates the input certificate files and returns the commands necessary to deploy a custom SSL certificate to Satellite{nbsp}Server.

.Procedure

To deploy a custom certificate on your Satellite Server, complete the following steps:

. Validate the custom SSL certificate input files. Note that for the `katello-certs-check` command to work correctly, Common Name (CN) in the certificate must match the FQDN of Satellite Server.
+
[options="nowrap", subs="+quotes"]
----
# katello-certs-check \
-c __/root/satellite_cert/satellite_cert.pem__ \      <1>
-k __/root/satellite_cert/satellite_cert_key.pem__ \  <2>
-b __/root/satellite_cert/ca_cert_bundle.pem__        <3>
----
<1> Path to the Satellite Server certificate file that is signed by a Certificate Authority.
<2> Path to the private key that was used to sign the Capsule{nbsp}Server certificate.
<3> Path to the Certificate Authority bundle.
+
If the command is successful, it returns two `satellite-installer` commands, one of which you must use to deploy a certificate to Satellite Server.

. From the output of the `katello-certs-check` command, depending on your requirements, enter the `satellite-installer` command that deploys a certificate to a new Satellite or updates a certificate on a currently running Satellite.
+
IMPORTANT: Do not delete the certificate archive file after you deploy the certificate. It is required, for example, when upgrading Satellite Server.

. On a computer with network access to Satellite{nbsp}Server, navigate to the following URL: `https://_satellite.example.com_`.

. In your browser, view the certificate details to verify the deployed certificate.
