:_mod-docs-content-type: PROCEDURE

[id="installing-a-smart-proxy-server"]
= Installing {SmartProxyServer}

[role="_abstract"]
With {SmartProxy} packages installed, you can proceed to install the {SmartProxyServer}.

ifdef::containerized[]
.Prerequisites
* {SmartProxyServer} packages are installed.
For more information, see xref:installing-{smart-proxy-context}-packages[].
endif::[]

.Procedure
ifndef::containerized[]
ifdef::foreman-el,foreman-deb[]
* To install {SmartProxyServer}, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} \
--enable-foreman-proxy \
--enable-puppet \
--foreman-proxy-foreman-base-url https://_{foreman-example-com}_ \
--foreman-proxy-oauth-consumer-key _My_oAuth_Consumer_Key_ \
--foreman-proxy-oauth-consumer-secret _My_oAuth_Consumer_Secret_ \
--foreman-proxy-puppetca false \
--foreman-proxy-tftp false \
--foreman-proxy-trusted-hosts _{foreman-example-com}_ \
--no-enable-foreman \
--no-enable-foreman-cli \
--puppet-server-ca false
----
endif::[]
ifdef::katello[]
* To install {SmartProxyServer} with content, refer to xref:configuring-{smart-proxy-context}-server-with-ssl-certificates[].
Running `{certs-generate}` is a required prerequisite to installing {SmartProxyServer} with content.
endif::[]
endif::[]
ifdef::containerized[]
. On your {ProjectServer}, generate an authentication bundle for the {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} auth-bundle _{smartproxy-example-com}_
----
. On your {ProjectServer}, copy the authentication bundle to {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# scp /var/lib/foremanctl/certs/bundles/_{smartproxy-example-com}_.tar.gz \
root@_{smartproxy-example-com}_:/root/_{smartproxy-example-com}_.tar.gz
----
+
[IMPORTANT]
====
The authentication bundle contains TLS private keys and OAuth credentials.
Treat the bundle as highly sensitive and delete any copies after deployment.
====
. On the {SmartProxyServer}, deploy the configuration:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl} deploy-proxy \
--flavor {foremanctl-proxy-scenario} \
--auth-bundle /root/_{smartproxy-example-com}_.tar.gz \
--foreman-fqdn _{foreman-example-com}_
----
endif::[]
