[id="examining-hosts-per-rule-compliance-result_{context}"]
= Examining Hosts per Rule Compliance Result

Using this procedure, you can examine a simplified report and use policy rules to list hosts that have a certain compliance result, such as failing a particular rule.

.Prerequisite
* Your user account has a role assigned that has the `view_arf_reports` and `view_hosts` permissions.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Reports*.
. In the *Reported At* column, navigate to the report of the required host and compliance policy, and click the time link.
. {Project} displays a simplified list of policy rules with the results of the scan.
. Optional: Filter the rules by check result.
From the *Show log messages* dropdown list, select one of the following filters:
** *Failed and othered* {endash} to view rules that have failed or have not been checked during the scan,
** *Failed only* {endash} to view only rules that have failed.
. Optional: Examine the details of the rule.
In the *Message* column, click the icon next to the name of the rule.
. In the row of the required rule, navigate to the *Actions* column and click *Hosts failing this rule*.
