[id="Deleting_an_Organization_{context}"]
= Deleting an Organization

You can delete an organization if the organization is not associated with any life cycle environments or host groups.
If there are any life cycle environments or host groups associated with the organization you are about to delete, remove them by navigating to *Administer*{nbsp}>{nbsp}*Organizations* and clicking the relevant organization.
Do not delete the default organization created during installation because the default organization is a placeholder for any unassociated hosts in the {Project} environment.
There must be at least one organization in the environment at any given time.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer*{nbsp}>{nbsp}*Organizations*.
. From the list to the right of the name of the organization you want to delete, select *Delete*.
. Click *OK* to delete the organization.

.CLI procedure
. Enter the following command to retrieve the ID of the organization that you want to delete:
+
----
# hammer organization list
----
+
From the output, note the ID of the organization that you want to delete.
. Enter the following command to delete an organization:
+
[subs="+quotes"]
----
# hammer organization delete --id _Organization_ID_
----
