[id="Installing_the_DHCP_Infoblox_Module_{context}"]
= Installing the DHCP Infoblox module

Use this procedure to install the DHCP Infoblox module on {ProductName}.
Note that you cannot manage records in separate views.

You can also install DHCP and DNS Infoblox modules simultaneously by combining this procedure and xref:Installing_the_DNS_Infoblox_Module_{context}[].

.DHCP Infoblox record type considerations
If you want to use the DHCP and DNS Infoblox modules together, configure the DHCP Infoblox module with the `fixedaddress` record type only.
The `host` record type causes DNS conflicts and is not supported.

If you configure the DHCP Infoblox module with the `host` record type, you have to unset both DNS {SmartProxy} and Reverse DNS {SmartProxy} options on your Infoblox-managed subnets, because Infoblox does DNS management by itself.
Using the `host` record type leads to creating conflicts and being unable to rename hosts in {Project}.

.Procedure
. On {ProductName}, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-proxy-plugin-dhcp-infoblox \
--foreman-proxy-dhcp true \
--foreman-proxy-dhcp-provider infoblox \
--foreman-proxy-dhcp-server _infoblox.example.com_ \
--foreman-proxy-plugin-dhcp-infoblox-username _admin_ \
--foreman-proxy-plugin-dhcp-infoblox-password _infoblox_ \
--foreman-proxy-plugin-dhcp-infoblox-record-type fixedaddress \
--foreman-proxy-plugin-dhcp-infoblox-dns-view default \
--foreman-proxy-plugin-dhcp-infoblox-network-view default
----
. Optional: In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*, select the {SmartProxy} with the DHCP Infoblox module, and ensure that the *dhcp* feature is listed.
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets*.
. For all subnets managed through Infoblox, ensure that the IP address management (*IPAM*) method of the subnet is set to `DHCP`.
