:_mod-docs-content-type: PROCEDURE

[id="configuring-a-bonded-interface-by-using-web-ui"]
= Configuring a bonded interface by using {ProjectWebUI}

[role="_abstract"]
You can combine multiple physical interfaces by configuring a bonded interface for the host.
Network interface card (NIC) bonding binds multiple interfaces into one logical interface that appears as a single device with one MAC address.
Bonding increases bandwidth and provides redundancy by making two or more NICs act as one.

[NOTE]
====
Bonded interfaces currently require a MAC address of a physical device.
Therefore, the configuration of these interfaces works only on bare-metal hosts.
====

.Procedure
. Navigate to the *Add Interface* form:
.. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
.. Click *Edit* next to the host you want to edit.
.. On the *Interfaces* tab, click *Add Interface*.

. Select *Bond* from the *Type* list.

. Specify the general interface settings:
.. In the *Device Identifier* field, specify the interface ID in the `bond0` format .
.. Specify a *MAC address*.
.. If you are configuring a secondary interface, select *Managed*.
Otherwise, {Project} does not apply the configuration.

. Add the configuration specific to bonded interfaces:
.. *Mode*: Select the bonding mode.
.. *Attached devices*: Specify a comma-separated list of identifiers of attached devices.
These can be physical interfaces or VLANs.
.. *Bond options*: Specify a space-separated list of configuration options, for example `miimon=100`.

. Click *OK* to save the interface configuration.
. Click *Submit* to apply the changes to the host.
