[id="Creating_Hosts_from_Discovered_Hosts_{context}"]
= Creating hosts from discovered hosts

Provisioning discovered hosts follows a provisioning process that is similar to PXE provisioning.
The main difference is that instead of manually entering the host's MAC address, you can select the host to provision from the list of discovered hosts.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-hosts-from-discovered-hosts_{context}[].

.Prerequisites
include::snip_prerequisite-networking-for-provisioning.adoc[]
* You have one or more discovered hosts in your {Project} inventory.
include::snip_prerequisites-common-compute-resource.adoc[]
* You have associated a `Discovery kexec`-kind template and `provisioning`-kind template with the operating system.
For more information, see xref:Associating_Templates_with_Operating_Systems_{context}[].

For information about the security tokens, see xref:Configuring_the_Security_Token_Validity_Duration_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
. Select the host you want to provision and click *Provision* to the right of the list.
. Select one of the following options:
* To provision a host from a host group, select a host group, organization, and location, and then click *Create Host*.
* To provision a host with further customization, click *Customize Host* and enter the additional details you want to specify for the new host.
. Verify that the fields are populated with values.
Note in particular:
+
* The *Name* from the *Host* tab becomes the *DNS name*.
* {ProjectServer} automatically assigns an IP address for the new host.
* {ProjectServer} automatically populates the MAC address from the Discovery results.
+
. Ensure that {ProjectServer} automatically selects the *Managed*, *Primary*, and *Provision* options for the first interface on the host.
If not, select them.
. Click the *Operating System* tab, and verify that all fields contain values.
Confirm each aspect of the operating system.
. In *Provisioning templates*, click *Resolve* to check if the new host can identify the correct provisioning templates.
ifdef::satellite[]
The host must resolve to the following provisioning templates:
+
* *Discovery kexec*: `Discovery Red Hat kexec`
* *Provisioning template*: `Kickstart default`
endif::[]
. Click *Submit* to save the host details.

When the host provisioning is complete, the discovered host moves to *Hosts* > *All Hosts*.

[id="cli-creating-hosts-from-discovered-hosts_{context}"]
.CLI procedure
. Identify the discovered host to provision:
+
----
$ hammer discovery list
----
. Select the host and provision it by using a host group.
Set a new host name with the `--new-name` option:
+
[options="nowrap" subs="+quotes"]
----
$ hammer discovery provision \
--build true \
--enabled true \
--hostgroup "_My_Host_Group_" \
--location "_My_Location_" \
--managed true \
--name "_My_Host_Name_" \
--new-name "_My_New_Host_Name_" \
--organization "_My_Organization_"
----
+
This removes the host from the discovered host listing and creates a host entry with the provisioning settings.
The Discovery image automatically reboots the host to PXE or initiates kernel execution.
The host detects the DHCP service and starts installing the operating system.
The rest of the process is identical to the normal PXE workflow described in xref:Creating_Hosts_with_Unattended_Provisioning_{context}[].
