[id="Adding_Errata_To_An_Incremental_Content_View_{context}"]
= Adding Errata to an Incremental Content View

If errata are available but not installable, you can create an incremental Content View version to add the errata to your content hosts.
For example, if the Content View is version 1.0, it becomes Content View version 1.1, and when you publish, it becomes Content View version 2.0.

IMPORTANT: If your content view version is old, you might encounter incompatibilities when incrementally adding enhanacement errata. 
This is because enhancements are typically designed for the most current software in a repository.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-errata-to-an-incremental-content-view[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Errata*.
. From the *Errata* list, click the name of the errata that you want to apply.
. Select the content hosts that you want to apply the errata to, and click *Apply to Hosts*.
This creates the incremental update to the Content View.
. If you want to apply the errata to the content host, select the *Apply Errata to Content Hosts immediately after publishing* checkbox.
. Click *Confirm* to apply the errata.

[id="cli-adding-errata-to-an-incremental-content-view"]
.CLI procedure
. List the errata and its corresponding IDs:
+
[options="nowrap" subs="+quotes"]
----
# hammer erratum list
----
. List the different content-view versions and the corresponding IDs:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view version list
----
. Apply a single erratum to content-view version.
You can add more IDs in a comma-separated list.
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view version incremental-update \
--content-view-version-id 319 --errata-ids 34068b
----
