:_mod-docs-content-type: PROCEDURE

[id="connect-{project-context}-to-{compute-resource-target-id}-by-using-web-ui"]
= Connect {Project} to {compute-resource-target-name} by using {ProjectWebUI}

[role="_abstract"]
You can use {Project} with the {compute-resource-name} plugin to provision, manage, and decommission hosts on {compute-resource-target-name}.

ifdef::hetzner-cloud[]
.Prerequisites
* You have an API token for your {compute-resource-target-name} account.
You can create the token on the Hetzner Console web interface.
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources*.
. Click *Create Compute Resource*.
. In the *Name* field, enter a name for the compute resource, for example, `{compute-resource-target-name}`.
+
Append the name of your {compute-resource-target-name} account if you plan to use multiple accounts simultaneously.
. From the *Provider* list, select *{compute-resource-name}*.
. Optional: In the *Description* field, enter a description for your compute resource.
. From the *{compute-resource-name} Provider* menu, select `{compute-resource-target-name}`.
. From the *{compute-resource-name} Template* menu, select `{compute-resource-target-name} provision default`.
// TODO: Yes really
ifdef::hetzner-cloud[]
. In the *URL* and *Username* fields, enter any arbitrary characters.
+
{Project} ignores them.
. In the *Password* field, enter your {compute-resource-target-name} token.
endif::[]
// TODO: Add steps per target to setup compute resource in Foreman
. Check *Enable caching* to cache API calls to {compute-resource-target-name} about clusters, network, or storage lists on {Project} for 60 minutes.
+
{Team} recommends to enable caching to improve performance.
. Click *Submit*.

// TODO: Obsolete after restructuring? Too many?
.Next steps
* Create a compute profile to bundle hardware settings.
* Define an image from your compute resource provider in {Project} to perform image-based host provisioning.
* Create a host group to bundle all settings in a blue print in {Project} for reproducible host deployments.
