[id="Importing_the_Katello_Root_CA_Certificate_{context}"]
= Importing the Katello Root CA Certificate

The first time you log in to {Project}, you might see a warning informing you that you are using the default self-signed certificate and you might not be able to connect this browser to {Project} until the root CA certificate is imported in the browser.
Use the following procedure to locate the root CA certificate on {Project} and to import it into your browser.

To use the CLI instead of the {ProjectWebUI}, see xref:CLI_Importing_the_Katello_Root_CA_Certificate_{context}[CLI Procedure].

.Prerequisites
* Your {ProjectName} is installed and configured.

.Procedure
. Identify the fully qualified domain name of your {ProjectServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hostname -f
----
. Access the `pub` directory on your {ProjectServer} using a web browser pointed to the fully qualified domain name:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
https://_{foreman-example-com}_/pub
----
. When you access {Project} for the first time, an untrusted connection warning displays in your web browser.
Accept the self-signed certificate and add the {Project} URL as a security exception to override the settings.
This procedure might differ depending on the browser being used.
Ensure that the {Project} URL is valid before you accept the security exception.
. Select `katello-server-ca.crt`.
. Import the certificate into your browser as a certificate authority and trust it to identify websites.

[id="CLI_Importing_the_Katello_Root_CA_Certificate_{context}"]
.CLI Procedure
. From the {Project} CLI, copy the `katello-server-ca.crt` file to the machine you use to access the {ProjectWebUI}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# scp /var/www/html/pub/katello-server-ca.crt _username@hostname:remotefile_
----
. In the browser, import the `katello-server-ca.crt` certificate as a certificate authority and trust it to identify websites.
