[id="Creating_Hosts_on_Proxmox_{context}"]
= Creating Hosts on Proxmox

The Proxmox provisioning process provides the option to create hosts over a network connection or using an existing image.

For network-based provisioning, you must create a host to access either integrated {SmartProxy} or an external {SmartProxyServer} on a Proxmox virtual network, so that the host has access to PXE provisioning services.
The new host entry triggers the Proxmox server to create the virtual machine.
If the virtual machine detects the defined {SmartProxyServer} through the virtual network, the virtual machine boots to PXE and begins to install the chosen operating system.

.DHCP Conflicts
If you use a virtual network on the Proxmox server for provisioning, ensure that you select a virtual network that does not provide DHCP assignments.
This causes DHCP conflicts with {ProjectServer} when booting new hosts.

For image-based provisioning, use the pre-existing image as a basis for the new volume.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Create Host*.
. In the *Name* field, enter a host name.
. On the *Organization* and *Location* tabs, ensure that the provisioning context is automatically set to the current context.
. From the *Host Group* list, select the host group that you want to use to populate the form.
. From the *Deploy on* list, select your Proxmox compute resource.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine-based settings.
. Click the *Interface* tab and click *Edit* on the host's interface.
. Verify that the fields are automatically populated with values.
Note in particular:
+
* The *Name* from the *Host* tab becomes the *DNS name*.
* {ProjectServer} automatically assigns an IP address for the new host.
. Ensure that the *MAC address* field is blank.
The Proxmox server assigns one to the host.
. Verify that the *Managed*, *Primary*, and *Provision* options are automatically selected for the first interface on the host.
If not, select them.
. In the interface window, review the Proxmox-specific fields that are populated with settings from our compute profile.
Modify these settings to suit your needs.
. On the *Operating System* tab, confirm that all fields automatically contain values.
. Select the Provisioning Method that you want:
+
* For network-based provisioning, click *Network Based*.
* For image-based provisioning, click *Image Based*.
ifdef::satellite[]
* For boot-disk provisioning, click *Boot disk based*.
endif::[]
ifndef::satellite[]
* If the `foreman_bootdisk` plug-in is installed and you want to use boot-disk provisioning, click *Boot disk based*.
endif::[]
. Click *Resolve* in *Provisioning templates* to check the new host can identify the right provisioning templates to use.
. Click the *Virtual Machine* tab and confirm that these settings are populated with details from the host group and compute profile.
Modify these settings to suit your requirements.
ifdef::satellite,orcharhino,katello[]
. On the *Parameters* tab, ensure that a parameter exists that provides an activation key.
If not, add an activation key.
endif::[]
ifdef::foreman-el[]
. If you use the Katello plugin, click the *Parameters* tab and ensure that a parameter exists that provides an activation key.
If not, add an activation key.
endif::[]
. Click *Submit* to provision your host on Proxmox.
