[id="Connected_Server_as_a_Content_Store_{context}"]
= Connected {ProjectServer} as a Content Store

In this scenario, you have one connected {ProjectServer} that is receiving content from an external source like the CDN.
The rest of your infrastructure is completely isolated, including another disconnected {ProjectServer}.
The connected {ProjectServer} is mainly used as a content store for updates.
The disconnected {ProjectServer} serves as the main {ProjectServer} for managing content for all infrastructure behind the isolated network.

.On the connected {ProjectServer}
. Ensure that repositories are using the immediate download policy, either by:
.. For existing repos using *On Demand*, change their download policy on the repository details page to *Immediate*.
.. For new repositories, ensure that the *Default Red Hat Repository download policy* setting is set to *Immediate* before enabling Red Hat repositories, and that the *Default download policy* is set to *Immediate* for custom repositories
For more information, see xref:Download_Policies_Overview_{context}[].
. Enable the content that you want to use.
For more information, see xref:Enabling_Red_Hat_Repositories_{context}[].
. Synchronize the enabled content.
. For the first export, perform a `complete Library` export so that all the synchronized content are exported.
This generates content archives that you can later import into one or more disconnected {ProjectServer}s.
For more information on performing a complete Library export, see xref:Exporting_the_Library_Environment_{context}[].
. Export all future updates in the connected {ProjectServer}s incrementally.
This generates leaner content archives that contain changes only from the recent set of updates.
For example, if you enable and synchronize a new repository, the next exported content archive contains content only from the newly enabled repository.
For more information on performing an incremental Library export, see xref:Using_ISS-Exporting-Library-Incremental[].

.On the disconnected {ProjectServer}
. Copy the exported content archive that you want from the connected {ProjectServer}.
. Import content to an organization using the procedure outlined in xref:Importing_into_the_Library_Environment_{context}[].
You can then manage content using Content Views or Lifecycle Environments as you require on the disconnected {ProjectServer}.
