[id="Creating_a_Content_View_{context}"]
= Creating a content view

Use this procedure to create a simple content view.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-content-view_{context}[].

.Prerequisites

While you can stipulate whether you want to resolve any package dependencies on a content view by content view basis, you might want to change the default {Project} settings to enable or disable package resolution for all content views.
For more information, see xref:Resolving_Package_Dependencies_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Content Views*.
. Click *Create content view*.
. In the *Name* field, enter a name for the view.
{Project} automatically completes the *Label* field from the name you enter.
. In the *Description* field, enter a description of the view.
. In the *Type* field, select a *Content view* or a *Composite content view*.
. Optional: If you want to solve dependencies automatically every time you publish this content view, select the *Solve dependencies* checkbox.
Dependency solving slows the publishing time and might ignore any content view filters you use.
This can also cause errors when resolving dependencies for errata.
. Click *Create content view*.

.Content view steps
. Click *Create content view* to create the content view.
. In the *Repositories* tab, select the repository from the *Type* list that you want to add to your content view, select the checkbox next to the available repositories you want to add, then click *Add repositories*.
. Click *Publish new version* and in the *Description* field, enter information about the version to log changes.
. Optional: You can enable a promotion path by clicking *Promote* to *Select a lifecycle environment from the available promotion paths to promote new version*.
. Click *Next*.
. On the *Review* page, you can review the environments you are trying to publish.
. Click *Finish*.

You can view the content view on the *Content Views* page.
To view more information about the content view, click the content view name.
To register a host to your content view, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in _{ManagingHostsDocTitle}_.

[id="cli-creating-a-content-view_{context}"]
.CLI procedure
. Obtain a list of repository IDs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer repository list --organization "_My_Organization_"
----
. Create the content view and add repositories:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer content-view create \
--description "_My_Content_View_" \
--name "_My_Content_View_" \
--organization "_My_Organization_" \
--repository-ids 1,2
----
+
For the `--repository-ids` option, you can find the IDs in the output of the `hammer repository list` command.
. Publish the view:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer content-view publish \
--description "_My_Content_View_" \
--name "_My_Content_View_" \
--organization "_My_Organization_"
----
. Optional: To add a repository to an existing content view, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer content-view add-repository \
--name "_My_Content_View_" \
--organization "_My_Organization_" \
--repository-id _repository_ID_
----

{ProjectServer} creates the new version of the view and publishes it to the Library environment.
