[id="configuring-group-mapping-for-keycloak-authentication_{context}"]
= Optional: Configuring external group mapping for {keycloak} authentication

To implement the role-based access control (RBAC), create a group in {Project}, assign a role to this group, and then map an {keycloak} group to the {Project} group.
As a result, anyone in the given group in {keycloak} will log in under the corresponding {Project} group.

For example, you can configure users of the {Project}-admin user group defined in Active Directory to authenticate as users with administrator privileges on {Project}.

.Procedure

. In the {ProjectWebUI}, navigate to *Administer* > *User Groups*.
. Click *Create User Group*.
.. In the *Name* field, enter a name for the user group.
Enter a name that is different from the Active Directory user group name.
.. Do not add any users or user groups to the new group in {ProjectWebUI}.
. On the *Roles* tab, select *Administer*.
. On the *External Groups* tab, click *Add external user group*.
.. In the *Name* field, enter the name of the Active Directory group.
.. From the *Auth Source* drop-down menu, select *EXTERNAL*.
. Click *Submit*.
