[id="Live_Patching_Hosts_Using_KernelCare_Plug_In_{context}"]
= Live Patching Hosts Using KernelCare Plug-In

You can use `kcarectl` provided by TuxCare to live-patch the Linux kernel on managed hosts.
By default, `kcarectl` checks for updates every four hours.
If the automatic installation of patches is disabled or if you want to install patches manually at a certain time, you can start the process using a remote execution job.

.Prerequisites
* Ensure your hosts have the `kernelcare` package installed.
* Ensure your hosts run {EL} 7, {EL} 8, or {EL} 9.
* Ensure your hosts have access to the internet to connect to cloudlinux.com.
+
If your host is in a disconnected environment, you can use ePortal by Tuxcare to provide Linux kernel patches.
For more information, see https://docs.tuxcare.com/eportal/[docs.tuxcare.com/eportal].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts*{nbsp}>{nbsp}*All Hosts*.
. Select one or multiple hosts and under *Select Action*, click * Schedule Remote Job*.
. In the *Job category* field, select `Commands`.
. In the *Job template* field, select `Run Command - SSH Default`.
. In the *command* field, enter `/usr/bin/kcarectl --update`.
. Click *Submit* to update to the latest Linux kernel on your hosts.

.Additional Resources
* For more information on live-patching managed hosts, see https://docs.tuxcare.com/live-patching-services/[docs.tuxcare.com/live-patching-services].
