:_mod-docs-content-type: PROCEDURE

[id="creating-a-flatpak-remote"]
= Creating a Flatpak remote

You can create a Flatpak remote to access and manage Flatpak repositories in {Project}.

.Prerequisites
* Your {Project} account has the following permissions for Flatpak remotes: `create_flatpak_remotes`, `view_flatpak_remotes`, `edit_flatpak_remotes`, and `destroy_flatpak_remotes`.
* Set up Flatpak on the content host that consumes applications from {ProjectServer}.
For more information, see {RHELDocsBaseURL}9/html/administering_the_system_using_the_gnome_desktop_environment/assembly_installing-applications-using-flatpak_administering-the-system-using-the-gnome-desktop-environment#setting-up-flatpak_assembly_installing-applications-using-flatpak[Setting up Flatpak].
* Ensure that Flatpak runtime repositories are available to clients alongside application repositories because Flatpak applications such as `rhel9/firefox-flatpak` depend on them for installation.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Flatpak Remotes*.
. Click *Create new*.
. In the *Name* field, enter a name for the Flatpak remote.
. In the *URL* field, enter the URL of the Flatpak remote.
  For example, to use the Red{nbsp}Hat Flatpak index, enter: `https://flatpaks.redhat.io/rhel/`.
. If the Flatpak remote requires authentication, enter the required credentials.
For example, synchronizing Red{nbsp}Hat Flatpaks from `registry.redhat.io` requires authentication.
For more information, see https://access.redhat.com/articles/RegistryAuthentication#creating-registry-service-accounts-6[Creating Registry Service Accounts].
. Click *Create*.
