:_mod-docs-content-type: PROCEDURE

[id="import-ansible-content-from-ansible-galaxy-by-using-api"]
= Import Ansible content from Ansible Galaxy by using {Project} API

[role="_abstract"]
You can import Ansible content from Ansible Galaxy into {Project} by using {Project} API.
Select Ansible Galaxy as content source if you want to import Ansible content from the Ansible Galaxy, from a resource that implements the Ansible Galaxy API, from a Pulp instance, or from a content view.

.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_content`, `view_ansible_content`, and `view_organizations` permissions.

.Procedure
. Create a JSON file, for example, `data.json` to define your Ansible content:
+
[source, json, options="nowrap", subs="verbatim,quotes,attributes"]
----
{
  "organization_id": "_My_Organization_ID_",
  "units": [
    {
      "unit_name": "_My_Namespace_._My_Name_",
      "unit_type": "collection",
      "unit_source_type": "galaxy",
      "unit_source": "https://galaxy.ansible.com",
      "unit_versions": [
        "_My_First_Version_",
        "_My_Second_Version_"
      ]
    }
  ]
}
----
. Import Ansible content from Ansible Galaxy:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--data @data.json \
--header "Accept: application/json" \
--header "Content-Type: application/json" \
--request POST \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/api/v2/ansible_director/ansible_content/ \
| jq
----
+
{Project} starts the import task and returns output similar to:
+
[source, json, options="nowrap", subs="verbatim,quotes,attributes"]
----
{
  "id": "_My_Task_ID_",
  "label": "ForemanAnsibleDirector::Actions::AnsibleContentUnit::Bulk::Import",
  "started_at": "2026-03-11 09:59:31 UTC"
}
----

.Verification
* Query the {Project} API to verify that the task finished successfully:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ curl \
--header "Accept: application/json" \
--user "_My_User_Name_:__My_Password__" \
https://{foreman-example-com}/foreman_tasks/api/tasks/_My_Task_ID_/details/ \
| jq ".result"
----
