[id="Upgrading_the_External_Database_{context}"]
= Upgrading the external database

You can upgrade an external database from {EL} 7 to {EL} 8 while upgrading {Project} from {ProjectVersionPrevious} to {ProjectVersion}.
Ensure that the external database is upgraded from PostgreSQL 12 to PostgreSQL 13.

.Prerequisites
* Create a new {EL} 8 based host for PostgreSQL server that follows the external database on {EL} 8 documentation.
ifdef::katello,orcharhino,satellite[]
For more information, see {InstallingServerDocURL}using-external-databases_{project-context}[Using External Databases with {Project}].
endif::[]

.Procedure
. Create a backup.
. Restore the backup on the new server.
. If {Project} reaches the new database server via the old name, no further changes are required.
Otherwise reconfigure {Project} to use the new name:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--foreman-db-host _newpostgres.example.com_ \
--katello-candlepin-db-host _newpostgres.example.com_ \
--foreman-proxy-content-pulpcore-postgresql-host _newpostgres.example.com_
----
