:_mod-docs-content-type: PROCEDURE

[id="Viewing_Patched_Kernel_Version_{context}"]
= Viewing patched kernel version

[role="_abstract"]
You can use a job template to view the patched kernel version on hosts.

.Prerequisites
* Ensure the `kernelcare` package is installed on your hosts.
For more information, see xref:Installing_the_KernelCare_Package_on_Hosts_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Monitor* > *Jobs* and click *Run job*.
. Select *LivePatching {endash} Script Default* as *Job category* and *LivePatching {endash} Kernel version* as *Job template* and click *Next*.
. Select hosts on which you want to run the job.
If you do not select any hosts, the job will run on all hosts you can see in the current context.
. Click *Next*.
. Optional: To configure advanced settings for the job, fill in the *Advanced fields*.
To learn more about advanced settings, see xref:advanced-settings-in-the-job-wizard_{context}[].
. Click *Next*.
. Select *Immediate execution* to execute the job immediately and click *Next*.
. Review job details.
You have the option to return to any part of the job wizard and edit the information.
. Click *Run* to view the running Kernel version on your hosts.
