:_mod-docs-content-type: PROCEDURE

[id="configuring-the-{project-context}-mcp-server"]
= Configuring the {Project} MCP server

Deploy the {Project} MCP server as a container and make it accessible to your MCP client.

.Procedure
. Build the MCP server container image.
For example, to build the container from the current directory and assign the `foreman-mcp-server` tag to it:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ podman build --tag foreman-mcp-server .
----
. Run the container.
For example, to run the container interactively, assign a pseudo-TTY, and publish port 8080 from the container to port 8080 on the host:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ podman run --interactive --tty --publish 8080:8080 foreman-mcp-server \
  --foreman-url https://_{foreman-example-com}_ \
  --host localhost \
  --port 8080 \
  --transport streamable-http
----
+
The `--transport streamable-http` option ensures that the MCP server uses a streamable HTTP protocol for communication.
It enables MCP clients to query data from the server.
+
The `--host localhost` option ensures that the MCP server binds to the localhost network interface.
It makes the MCP server accessible only from the machine where the container is running.

.Verification
* <TBD> Anything we can share to verify that the MCP server was successfully deployed? A very simple test to make sure everything completed successfully? </TBD>

.Next steps
* Configure your MCP client and connect it to the MCP server.
<TBD> Is there anything we should tell users about this step? For example, anything on what information to provide to the MCP client to enable it to authenticate to Foreman? </TBD>
