[id="Adding_Custom_RPM_Repositories_for_{os_name_anchor}_{os_major}_{context}"]
= Adding {customrpmtitle} Repositories for {os_name} {os_major}

This example creates a product and repositories for {os_name} {os_major}.

.Prerequisite
* Download and import the {gpg_url}[GPG public key] for yum repositories for {os_name} {os_major} into {Project}.
For more information, see xref:Importing_a_Custom_GPG_Key_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content > Products*.
. Click *Create Product* to create a product named `{os_name} {os_major}`.
For more information, see xref:Creating_a_Custom_Product_{context}[].
. On the *Repositories* tab, click *New Repository* to create three repositories of type `yum` as follows:
+
* *{yum_repo_baseos_name}*
** *Upstream URL*: `{yum_repo_baseos_url}`
* *{yum_repo_appstream_name}*
** *Upstream URL*: `{yum_repo_appstream_url}`
* *{yum_repo_extras_name}*
** *Upstream URL*: `{yum_repo_extras_url}`

+
For more information, see xref:Adding_Custom_RPM_Repositories_{context}[].
. Click *Create Product* to create a product named `{os_name} {os_major} client`.
. On the *Repositories* tab, click *New Repository* to create a repository of type `yum` as follows:
+
ifndef::orcharhino[]
* **{Project} EL{os_major} Client**
** *Upstream URL*: `{project-client-name}el{os_major}/`
endif::[]
ifdef::orcharhino[]
* **{os_name} {os_major} client**
** *Upstream URL*: see https://atixservice.zendesk.com/hc/de/articles/360013840079[ATIX Service Portal]
endif::[]
