:_mod-docs-content-type: PROCEDURE

[id="installing-errata-on-hosts-by-using-cli"]
= Installing errata on hosts by using CLI

[role="_abstract"]
You can use Hammer CLI to review and install installable errata on hosts so that security and bugfix updates are installed on selected hosts.

.Prerequisites
* Requirements for errata installation on hosts are met.
For more information, see xref:prerequisites-for-installing-errata-on-hosts[].

.Procedure
. List all errata:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer erratum list --organization "_My_Organization_"
----
+
You can limit the output to applicable by adding `--errata-restrict-applicable` or to installable errata by adding `--errata-restrict-installable`.
. Optional: View information of an erratum:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer erratum info --id _My_Erratum_ID_
----
. Install errata on your hosts.
+
You can use `Remote Execution`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer job-invocation create \
--feature katello_errata_install \
--inputs errata=_My_Erratum_ID_1_,_My_Erratum_ID_2_ \
--search-query "name = host.example.com"
----
+
If you want to install errata on all hosts in a host collection, use `"host_collection = _My_Host_Collection_Name_"` as the search query.
If you want to install a specific erratum on all hosts, use `"applicable_errata = _My_Erratum_ID_"` as the search query.
+
You can use a Bash script that installs an erratum on each host for which this erratum is available:
+
[source, terminal, options="nowrap", subs="+quotes,verbatim,attributes"]
----
for HOST in `hammer --csv --csv-separator "|" host list --search "applicable_errata = _My_Erratum_ID_" --organization "_My_Organization_" | tail -n+2 | awk -F "|" '{ print $2 }'` ;
do
  echo "== Installing on $HOST ==" ; hammer job-invocation create --feature katello_errata_install --search-query "name = $HOST" --inputs errata=_My_Erratum_ID_1_,_My_Erratum_ID_2_ ;
done
----
+
This command identifies all hosts with _My_Erratum_ID_ as an applicable erratum and then installs the erratum on each host.

.Verification
. Locate the task ID of your errata installation in task listing:
+
[options="nowrap" subs="verbatim,quotes"]
----
$ hammer task list
----
. Inspect the state of the selected task:
+
[options="nowrap" subs="+quotes"]
----
$ hammer task progress --id _My_Task_ID_
----

.Additional resources
* {AdministeringDocURL}working-efficiently-with-web-ui[Working efficiently with {ProjectWebUI} in _{AdministeringDocTitle}_]
