:_mod-docs-content-type: PROCEDURE

[id="creating-an-operating-system-for-{client-os-context}-{client-os-major-context}"]
= Creating an operating system for {client-os} {client-os-major}

[role="_abstract"]
Create an operating system in {Project} to provision hosts running {client-os} {client-os-major}.
This example creates an operating system entry for {client-os} {client-os-major}.

ifdef::orcharhino[]
include::snip_creating-os-on-orcharhino.adoc[]
endif::[]

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning Setup* > *Operating Systems*.
. Click *Create Operating System* to create an operating system entry for {client-os}.
. Enter `{client-os} {client-os-major}` as *Name* for the operating system.
Choose a name as reported by Ansible, Puppet, or Salt as fact.
. Set the *Major Version* to `{client-os-major}`.
. Leave the *Minor Version* field empty.
. Set the *Release Name* to `{client-os-codename}` for {client-os} {client-os-major}.
. On the *Partition Table* tab, select the `{client-os-partition-table}` partition table.
+
For more information, see xref:creating-partition-tables-by-using-web-ui[].
. On the *Templates* tab, select the `{client-os-provisioning-template-finish}` template as *Finish template*, the `{client-os-provisioning-template}` template as *Provisioning Template*, and the `{client-os-provisioning-template-pxelinux}` template as *PXELinux template*.
ifdef::orcharhino[]
+
include::snip_host-parameters-for-orcharhino-clients.adoc[]
endif::[]
+
For more information, see xref:creating-provisioning-templates-by-using-web-ui[].
. Click *Submit* to save the operating system entry for {client-os}.
