:_mod-docs-content-type: PROCEDURE

[id="adding-an-http-proxy-by-using-cli"]
= Adding an HTTP proxy by using Hammer CLI

[role="_abstract"]
You can add HTTP proxies to {Project} by using Hammer CLI.
You can then specify which HTTP proxy to use for products, repositories, and supported compute resources.

.Prerequisites
* Your HTTP proxy must allow access to the following hosts:
+
include::snip_host-names-for-http-proxy.adoc[]
* If {ProjectServer} uses an HTTP proxy to communicate with `subscription.rhsm.redhat.com` and `cdn.redhat.com`, then your HTTP proxy must not perform SSL inspection on these communications.

.Procedure
* Add your HTTP proxy to {Project}:
+
[options="nowrap" subs="+quotes,verbatim"]
----
$ hammer http-proxy create \
--name _My_HTTP_Proxy_ \
--url _http-proxy.example.com:8080_
----
+
Optional: To set the HTTP proxy as default for content synchronization, add the `--content-default-http-proxy true` option.
+
If your HTTP proxy requires authentication, add the `--username _My_User_Name_` and `--password _My_Password_` options.

ifndef::orcharhino[]
.Additional resources
* https://access.redhat.com/solutions/65300[How to access Red Hat Subscription Manager (RHSM) through a firewall or proxy]
endif::[]
