[id="creating-image-only-hosts_{context}"]
= Creating Image-based Hosts on {CRname}

In {Project}, you can use {CRname} provisioning to create hosts from an existing image.
The new host entry triggers the {CRname} server to create the instance using the pre-existing image as a basis for the new volume.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-image-only-hosts_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts*{nbsp}>{nbsp}*Create Host*.
. In the *Name* field, enter a name for the host.
. Click the *Organization* and *Location* tabs to ensure that the provisioning context is automatically set to the current context.
. From the *Host Group* list, select the host group that you want to use to populate the form.
. From the *Deploy on* list, select the {CRname} connection.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine settings.
. From the *Lifecycle Environment* list, select the environment.
. Click the *Interfaces* tab and click *Edit* on the host's interface.
. Verify that the fields are automatically populated, particularly the following items:
* The *Name* from the *Host* tab becomes the *DNS name*.
* The *MAC address* field is blank.
{CRname} assigns a MAC address to the host during provisioning.
ifndef::azure-provisioning[* {ProjectServer} automatically assigns an IP address for the new host.]
ifdef::gce-provisioning[* The *Domain* field is populated with the required domain.]
ifdef::azure-provisioning[* The *Azure Subnet* field is populated with the required Azure subnet.]
* The *Managed*, *Primary*, and *Provision* options are automatically selected for the first interface on the host.
If not, select them.

ifdef::azure-provisioning[. Optional: If you want to use a static private IP address, from the *IPv4 Subnet* list select the {Project} subnet with the *Network Address* field matching the Azure subnet address. In the *IPv4 Address* field, enter an IPv4 address within the range of your Azure subnet.]
. Click the *Operating System* tab, and confirm that all fields automatically contain values.
ifdef::openstack-provisioning[. If you want to change the image that populates automatically from your compute profile, from the *Images* list, select a different image to base the new host's root volume on.]
ifdef::azure-provisioning[. For *Provisioning Method*, ensure *Image Based* is selected.]
ifdef::azure-provisioning[. From the *Image* list, select the Azure Resource Manager image that you want to use for provisioning.]
ifdef::azure-provisioning[. In the *Root Password* field, enter the root password to authenticate with.]
. Click *Resolve* in *Provisioning templates* to check the new host can identify the right provisioning templates to use.
. Click the *Virtual Machine* tab and confirm that these settings are populated with details from the host group and compute profile.
Modify these settings to suit your needs.
ifdef::foreman-el,katello[]
. If you use the Katello plugin, click the *Parameters* tab, and ensure that a parameter exists that provides an activation key.
If not, add an activation key.
endif::[]
ifdef::satellite,orcharhino[]
. Click the *Parameters* tab, and ensure that a parameter exists that provides an activation key.
If not, add an activation key.
endif::[]
. Click *Submit* to save the host entry.

[id="cli-creating-image-only-hosts_{context}"]
.CLI procedure
* Create the host with the `hammer host create` command and include `--provision-method image`.
Replace the values in the following example with the appropriate values for your environment.
ifeval::["{context}" == "openstack-provisioning"]
+
[options="nowrap" subs="+quotes"]
----
# hammer host create \
--compute-attributes="flavor_ref=m1.small,tenant_id=openstack,security_groups=default,network=mynetwork" \
--compute-resource "_My_OpenStack_Platform_" \
--enabled true \
--hostgroup "_Base_" \
--image "_OpenStack Image_" \
--interface "managed=true,primary=true,provision=true" \
--location "New York" \
--managed true \
--name "openstack-host1" \
--organization "_My_Organization_" \
--provision-method image
----
endif::[]
ifeval::["{context}" == "gce-provisioning"]
+
[options="nowrap" subs="+quotes"]
----
# hammer host create \
--architecture _x86_64_ \
--compute-profile "_gce_profile_name_" \
--compute-resource "_My_GCE_Compute_Resource_" \
--image "_My_GCE_Image_" \
--interface "type=interface,domain_id=1,managed=true,primary=true,provision=true" \
--location "_My_Location_" \
--name "_GCE_VM_" \
--operatingsystem "_My_Operating_System_" \
--organization "_My_Organization_" \
--provision-method 'image' \
--puppet-ca-proxy-id _1_ \
--puppet-environment-id _1_ \
--puppet-proxy-id _1_ \
--root-password "_My_Root_Password_"
----
endif::[]
ifeval::["{context}" == "azure-provisioning"]
+
[options="nowrap" subs="+quotes"]
----
# hammer host create \
--architecture _x86_64_ \
--compute-profile "_My_Compute_Profile_" \
--compute-resource "_My_Azure_Compute_Resource_" \
--domain "_My_Domain_" \
--image "_My_Azure_Image_" \
--location "_My_Location_" \
--name="_Azure_VM_" \
--operatingsystem "_My_Operating_System_" \
--organization "_My_Organization_" \
--provision-method "image"
----
endif::[]

For more information about additional host creation parameters for this compute resource, enter the `hammer host create --help` command.
