[id="Configuring_TLS_for_Secure_LDAP_{context}"]
= Configuring TLS for Secure LDAP

Use the {Project} CLI to configure TLS for secure LDAP (LDAPS).

.Procedure
. Obtain the Certificate from the LDAP Server.
.. If you use Active Directory Certificate Services, export the Enterprise PKI CA Certificate using the Base-64 encoded X.509 format.
ifndef::orcharhino[]
See https://access.redhat.com/solutions/1498773[How to configure Active Directory authentication with `TLS` on {Project}] for information on creating and exporting a CA certificate from an Active Directory server.
endif::[]
.. Download the LDAP server certificate to a temporary location onto {ProjectServer} and remove it when finished.
+
For example, `/tmp/example.crt`.
The filename extensions `.cer` and `.crt` are only conventions and can refer to DER binary or PEM ASCII format certificates.
. Trust the Certificate from the LDAP Server.
+
{ProjectServer} requires the CA certificates for LDAP authentication to be in the system trust store.

.. Importe the certificate:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cp /tmp/_example.crt_ /etc/pki/tls/source/anchors
----
.. Update the certificate authority trust store:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# update-ca-trust enable
# update-ca-trust
----
