[id="Enabling_Red_Hat_Repositories_{context}"]
= Enabling Red{nbsp}Hat Repositories

If outside network access requires usage of an HTTP Proxy, configure a default HTTP Proxy for your server.
See {InstallingProjectDocURL}adding-a-default-http-proxy_{build}[Adding a default HTTP Proxy]

To select the repositories to synchronize, you must first identify the product that contains the repository, and then enable that repository based on the relevant release version and base architecture.
For {RHEL} 8, you must enable both AppStream and BaseOS repositories.

ifdef::satellite[]
.Disconnected {Project}
If you use Disconnected {ProjectServer}, you must configure {Project} to synchronize content with a local CDN server before synchronizing content.
For more information, see xref:Configuring_Server_to_Synchronize_Content_with_a_Local_CDN_Server_{context}[].
endif::[]

.Repository Versioning
The difference between associating {RHEL} operating system with either 7 Server repositories or 7._X_ repositories is that 7 Server repositories contain all the latest updates while {RHEL} 7._X_ repositories stop getting updates after the next minor version release.
Note that Kickstart repositories only have minor versions.

.For {RHEL} 8 Clients

To provision {RHEL} 8 clients, you require the *{RHEL} 8 for x86_64 - AppStream (RPMS)* and *{RHEL} 8 for x86_64 - BaseOS (RPMs)* repositories.

.For {RHEL} 7 Clients

To provision {RHEL} 7 clients, you require the *{RHEL} 7 Server (RPMs)* repository.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Red{nbsp}Hat Repositories*.
. To find repositories, either enter the repository name, or toggle the *Recommended Repositories* button to the on position to view a list of repositories that you require.
. In the Available Repositories pane, click a repository to expand the repository set.
. Click the *Enable* icon next to the base architecture and release version that you want.

.CLI procedure
. To search for your product, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# hammer product list --organization "_My_Organization_"
----
. List the repository set for the product:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository-set list \
--product "Red Hat Enterprise Linux Server" \
--organization "_My_Organization_"
----
. Enable the repository using either the name or ID number.
Include the release version, for example,`7Server` and base architecture, for example, `x86_64`.
For example:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository-set enable \
--name "Red Hat Enterprise Linux 7 Server (RPMs)" \
--releasever "7Server" \
--basearch "x86_64" \
--product "Red Hat Enterprise Linux Server" \
--organization "_My_Organization_"
----
