:_mod-docs-content-type: PROCEDURE

[id="restoring-{smart-proxy-context}-server-by-using-a-virtual-machine-snapshot"]
= Restoring {SmartProxyServer} by using a virtual machine snapshot

[role="_abstract"]
You can use virtual machine snapshots to back up and restore your {SmartProxyServer} for quick recovery after server failure or configuration issues.
Configure or redeploy the host and complete installation.
ifdef::katello,orcharhino,satellite[]
Then synchronize content from {ProjectServer} to your {SmartProxyServer}.
endif::[]

ifdef::katello,orcharhino,satellite[]
.Prerequisites
* Ensure that you either select the relevant organization and location context of your {SmartProxyServer} or choose *Any Organization* and *Any Location*.
endif::[]

.Procedure
. If your {SmartProxyServer} is a virtual machine, include it in your backup strategy by using VM snapshots.
Creating weekly snapshots that you can restore from is recommended.
. After a failure, either restore your {SmartProxyServer} from a snapshot by using your hypervisor tools, or deploy a new {SmartProxyServer} and ensure that the host name is the same as before, and then install the {SmartProxy} certificates.
ifdef::katello,orcharhino,satellite[]
You may still have them on {ProjectServer}, the package name ends in -certs.tar, alternately create new ones.
endif::[]
ifndef::katello,orcharhino,satellite[]
You may still have them, alternately create new ones.
endif::[]
. Follow the procedures in {InstallingSmartProxyDocURL}[Installing {SmartProxyServer}] until you can confirm, in the {ProjectWebUI}, that {SmartProxyServer} is connected to {ProjectServer}.
ifdef::katello,orcharhino,satellite[]
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*.
. Select your {SmartProxyServer}.
. On the *Overview* tab, click *Synchronize*.
* Select *Optimized Sync* to synchronize content from your {ProjectServer} to your {SmartProxyServer} that bypasses unnecessary steps to speed up performance.
* Select *Complete Sync* to perform a complete sync from your {ProjectServer} to your {SmartProxyServer} that synchronizes content even if the metadata has not changed.
endif::[]
