[id="configuring-capsule-default-certificate_{context}"]
= Configuring {SmartProxyServer} with a Default SSL Certificate

Use this section to configure {SmartProxyServer} with an SSL certificate that is signed by the {ProjectServer} default Certificate Authority (CA).

.Prerequisites

Before configuring {SmartProxyServer} with a default server certificate, ensure that your {SmartProxyServer} meets the following conditions:

* {SmartProxyServer} is registered to {ProjectServer}.
For more information, see xref:registering-to-satellite-server_{smart-proxy-context}[].
* The {SmartProxyServer} packages are installed.
For more information, see xref:installing-capsule-server-packages_{smart-proxy-context}[].

.Procedure

To configure {SmartProxyServer} with a default server certificate, complete the following steps:

. On {ProjectServer}, to store all the source certificate files for your {SmartProxyServer}, create a directory that is accessible only to the `root` user, for example `/root/{smart-proxy-context}_cert`:
+
[options="nowrap", subs="+quotes,attributes"]
----
# mkdir /root/_{smart-proxy-context}_cert_
----

. On {ProjectServer}, generate the `_/root/{smart-proxy-context}_cert/{smart-proxy-context}_certs.tar_` certificate archive for your {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {certs-generate} \
--foreman-proxy-fqdn _{smartproxy-example-com}_ \
--certs-tar _/root/{smart-proxy-context}_cert/{smart-proxy-context}_certs.tar_
----
+
Retain a copy of the `{foreman-installer}` command that the `{certs-generate}` command returns for deploying the certificate to your {SmartProxyServer}.
+
ifeval::["{build}" == "satellite"]
.Example output of `{certs-generate}`
[options="nowrap", subs="+quotes,attributes"]
----
_output omitted_
satellite-installer \
--scenario capsule \
--certs-tar-file                              "_/root/capsule_certs.tar_"\
--foreman-proxy-content-parent-fqdn           "_satellite.example.com_"\
--foreman-proxy-register-in-foreman           "true"\
--foreman-proxy-foreman-base-url              "https://_satellite.example.com_"\
--foreman-proxy-trusted-hosts                 "_satellite.example.com_"\
--foreman-proxy-trusted-hosts                 "_capsule.example.com_"\
--foreman-proxy-oauth-consumer-key            "_s97QxvUAgFNAQZNGg4F9zLq2biDsxM7f_"\
--foreman-proxy-oauth-consumer-secret         "_6bpzAdMpRAfYaVZtaepYetomgBVQ6ehY_"\
--puppet-server-foreman-url                   "https://_satellite.example.com_"
----
endif::[]

ifeval::["{build}" != "satellite"]
.Example output of `{certs-generate}`
[options="nowrap", subs="+quotes,attributes""]
----
_output omitted_
foreman-installer \
--scenario foreman-proxy-content \
--certs-tar-file                              "_/root/{smart-proxy-context}_certs.tar_"\
--foreman-proxy-content-parent-fqdn           "_{foreman-example-com}_"\
--foreman-proxy-register-in-foreman           "true"\
--foreman-proxy-foreman-base-url              "https://_{foreman-example-com}_"\
--foreman-proxy-trusted-hosts                 "_{foreman-example-com}_"\
--foreman-proxy-trusted-hosts                 "_{smartproxy-example-com}_"\
--foreman-proxy-oauth-consumer-key            "_s97QxvUAgFNAQZNGg4F9zLq2biDsxM7f_"\
--foreman-proxy-oauth-consumer-secret         "_6bpzAdMpRAfYaVZtaepYetomgBVQ6ehY_"\
--puppet-server-foreman-url                   "https://_{foreman-example-com}_"
----
endif::[]

. On {ProjectServer}, copy the certificate archive file to your {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,attributes"]
----
# scp /root/{smart-proxy-context}_cert/_{smartproxy-example-com}_-certs.tar \
root@_{smartproxy-example-com}_:/root/_{smartproxy-example-com}_-certs.tar
----

. On {SmartProxyServer}, to deploy the certificate, enter the `{foreman-installer}` command that the `{certs-generate}` command returns.
+
When network connections or ports to {Project} are not yet open, you can set the `--foreman-proxy-register-in-foreman` option to `false` to prevent {SmartProxy} from attempting to connect to {Project} and reporting errors.
Run the installer again with this option set to `true` when the network and firewalls are correctly configured.
+
IMPORTANT: Do not delete the certificate archive file after you deploy the certificate.
It is required, for example, when upgrading {SmartProxyServer}.
