:_mod-docs-content-type: PROCEDURE

[id="registering-a-host-and-testing-package-delivery"]
= Registering a host and testing package delivery

[role="_abstract"]
Register a host to {Project} and verify that it receives packages from your content view.
Registration connects the host to {ProjectServer} and assigns the lifecycle environment and content view from the activation key.

.Prerequisites
* You have root access to the host.
* The host and your {ProjectServer} can communicate over the network.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Register Host*.
. From the *Activation Keys* list, select the required activation key.
ifdef::katello,satellite[]
. If you have not deployed a CA-signed certificate on {ProjectServer}, select the *Insecure* option for the purposes of this tutorial.
endif::[]
. Click *Generate* to generate the registration command.
. On your host, run the registration command as the root user.

.Verification
* The registration command succeeds.
* On the host, install a package that is provided through the content view:
+
[options="nowrap" subs="+quotes"]
----
# dnf install _My_Package_Name_
----
+
Verify that {ProjectServer} delivers the package instead of external mirrors.
+
Your content pipeline is now working end to end.
Hosts registered with your activation key will receive packages from the content view snapshot most recently promoted to the *Development* lifecycle environment.

.Additional resources
* {ManagingHostsDocURL}registering-hosts-by-using-global-registration[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_
