:_mod-docs-content-type: PROCEDURE

[id="configuring-server-to-synchronize-content-over-a-network-by-using-cli"]
= Configuring {ProjectServer} to synchronize content over a network by using Hammer CLI

[role="_abstract"]
Configure a downstream {ProjectServer} to synchronize repositories from a connected upstream {ProjectServer} over HTTPS by using Hammer CLI.

.Prerequisites
* A network connection exists between the upstream {ProjectServer} and the downstream {ProjectServer}.
* You imported the same subscription manifest on both the upstream and downstream {ProjectServer}.
For more information, see xref:Importing_a_Red_Hat_Subscription_Manifest_into_Server_{context}[].
* On the upstream {ProjectServer}, you enabled the required repositories for the organization.
For more information, see {ContentManagementDocURL}enabling-red-hat-repositories-by-using-web-ui[Enabling Red Hat Repositories] in _{ContentManagementDocTitle}_.
* The upstream user is an admin or has the following permissions:
** `view_organizations`
** `view_products`
** `export_content`
** `view_lifecycle_environments`
** `view_content_views`
* On the downstream {ProjectServer}, you have imported the SSL certificate of the upstream {ProjectServer} using the contents of `http://_upstream-{foreman-example-com}_/pub/katello-server-ca.crt`.
For more information, see {ContentManagementDocURL}importing-custom-ssl-certificates-by-using-web-ui[Importing SSL Certificates] in _{ContentManagementDocTitle}_.
* The downstream user is an admin or has the permissions to create product repositories and organizations.

.Procedure
. Connect to your downstream {ProjectServer} using SSH.
. View information about the upstream CA certificate:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-credential show \
--name="_My_Upstream_CA_Cert_" \
--organization="_My_Downstream_Organization_"
----
+
Note the ID of the CA certificate for the next step.
. Set CDN configuration to an upstream {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer organization configure-cdn \
--name="_My_Downstream_Organization_" \
--type=network_sync \
--url https://_upstream-{foreman-example-com}_ \
--username _upstream_username_ --password _upstream_password_ \
--ssl-ca-credential-id "_My_Upstream_CA_Cert_ID" \
--upstream-organization-label="_My_Upstream_Organization_" \
[--upstream-lifecycle-environment-label="_My_Lifecycle_Environment_"] \
[--upstream-content-view-label="_My_Content_View_"]
----
+
The default lifecycle environment label is `Library`.
The default content view label is `Default_Organization_View`.
