:_mod-docs-content-type: PROCEDURE

[id="enabling-openscap"]
= Enabling OpenSCAP

ifdef::satellite[]
The OpenSCAP plugin is enabled on your {ProjectServer} by default.
To use the OpenSCAP plugin and content on {SmartProxyServers}, you must enable OpenSCAP on each {SmartProxyServer}.
endif::[]
ifndef::satellite[]
If you want to use the OpenSCAP plugin and content on {SmartProxyServers}, you must enable OpenSCAP on each {SmartProxyServer}.
endif::[]

ifndef::satellite[]
.Prerequisites
* You have installed the OpenSCAP plugin on your {ProjectServer}.
For more information, see xref:installing-the-openscap-plugin[].
endif::[]

.Procedure
* Enable OpenSCAP on your {SmartProxyServer}:
+
[options="nowrap" subs="quotes,attributes"]
----
# {foreman-installer} \
--enable-foreman-proxy-plugin-openscap \
--foreman-proxy-plugin-openscap-ansible-module true \
--foreman-proxy-plugin-openscap-puppet-module true
----
ifdef::katello,orcharhino[]
+
If you want to use Ansible to deploy compliance policies, you must enable it first.
For more information, see {ManagingConfigurationsAnsibleDocURL}[_{ManagingConfigurationsAnsibleDocTitle}_].
endif::[]
ifdef::katello,orcharhino,satellite[]
+
If you want to use Puppet to deploy compliance policies, you must enable it first.
For more information, see {ManagingConfigurationsPuppetDocURL}[_{ManagingConfigurationsPuppetDocTitle}_].
endif::[]
