:_mod-docs-content-type: PROCEDURE

[id="creating-a-custom-file-type-repository-by-using-web-ui"]
= Creating a {customfiletype} repository by using {ProjectWebUI}

[role="_abstract"]
The procedure for creating a {customfiletype} repository is the same as the procedure for creating any {customcontent}, except that when you create the repository, you select the *file* type.
You must create a product and then add a {customrepo}.

.Procedure
. In the {ProjectWebUI}, navigate to *Content > Products*.
. Select a product that you want to create a repository for.
. On the *Repositories* tab, click *New Repository*.
. In the *Name* field, enter a name for the repository.
{Project} automatically completes the *Label* field based on the name.
. Optional: In the *Description* field, enter a description for the repository.
. From the *Type* list, select `file` as type of repository.
. Optional: In the *Upstream URL* field, enter the URL of the upstream repository to use as a source.
If you do not enter an upstream URL, you can manually upload packages.
For more information, see xref:uploading-files-to-a-custom-file-type-repository-by-using-web-ui[].
. Select *Verify SSL* to verify that the SSL certificates of the repository are signed by a trusted CA.
. Optional: In the *Upstream Username* field, enter the user name for the upstream repository if required for authentication.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Password* field, enter the corresponding password for the upstream repository.
Clear this field if the repository does not require authentication.
. Optional: In the *Upstream Authentication Token* field, provide the token of the upstream repository user for authentication.
Leave this field empty if the repository does not require authentication.
. From the *Download Policy* list, select the type of synchronization {ProjectServer} performs.
For more information, see xref:Download_Policies_Overview_{context}[].
. From the *Mirroring Policy* list, select the type of content synchronization {ProjectServer} performs.
For more information, see xref:Mirroring_Policies_Overview_{context}[].
. Optional: In the *HTTP Proxy Policy* field, select an HTTP proxy.
By default, it uses the `Global Default` HTTP proxy.
. Optional: You can clear the *Unprotected* checkbox to require a subscription entitlement certificate for accessing this repository.
By default, the repository is published through HTTP.
. Optional: In the *SSL CA Cert* field, select the SSL CA Certificate for the repository.
. Optional: In the *SSL Client Cert* field, select the SSL Client Certificate for the repository.
. Optional: In the *SSL Client Key* field, select the SSL Client Key for the repository.
. Click *Save* to create the repository.
