:_mod-docs-content-type: PROCEDURE

[id="mirroring-remote-flatpak-repositories-to-{project-context}-products-by-using-cli"]
= Mirroring remote Flatpak repositories to {Project} products by using Hammer CLI

You can mirror a Flatpak repository from a Flatpak remote into an existing product in {Project} to make it available for content management and distribution.

This action creates a new repository inside the product you selected.
You can now synchronize the repository to pull down its content.
Flatpak repositories are container repositories and you can add them to content views like other container repositories.

Flatpak applications require a corresponding runtime environment, which the Flatpak remote also provides.
To make the {EL} 10 Mozilla Firefox Flatpak available to a host, ensure that the host can access the matching `rhel10/flatpak-runtime` repository.

.Prerequisites
* Your {Project} account has a role that grants the `view_flatpak_remotes` and `edit_flatpak_remotes` permissions.
* Ensure that Flatpak runtime repositories are available to hosts alongside application repositories.
Flatpak applications, such as `rhel9/firefox-flatpak`, depend on the runtime for installation.
* You have created a {customproduct} on {Project}.

.Procedure
* Mirror a Flatpak repository into your product:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ hammer flatpak-remote remote-repository mirror \
--flatpak-remote-id _My_Flatpak_Remote_ID_ \
--id _My_Flatpak_Repository_ID_ \
--product-id _My_Product_ID_
----
