:_mod-docs-content-type: PROCEDURE

[id="creating-a-content-view-filter-by-using-web-ui"]
= Creating a content view filter by using {ProjectWebUI}

// TODO: Add Deb content without module streams.
You can filter content views containing Yum content to include or exclude specific packages, package groups, errata, or module streams.
Filters are based on a combination of the _name_, _version_, and _architecture_.
For examples of how to build a filter, see xref:common/modules/con_content-filter-examples.adoc#Content_Filter_Examples_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Content Views*.
. Select a content view.
. On the *Filters* tab, click *Create filter*.
. Enter a name.
. From the *Content type* list, select a content type.
. From the *Inclusion Type* list, select either *Include filter* or *Exclude filter*.
. Optional: In the *Description* field, enter a description for the filter.
. Click *Create filter* to create your content filter.
. Depending on what you enter for *Content Type*, add rules to create the filter that you want.
. Select if you want the filter to *Apply to subset of repositories* or *Apply to all repositories*.
. Click *Publish New Version* to publish the filtered repository.
. Optional: In the *Description* field, enter a description of the changes.
. Click *Create filter* to publish a new version of the content view.
+
You can promote this content view across all environments.
