:_mod-docs-content-type: PROCEDURE

[id="exporting-a-content-view-version-in-the-syncable-format"]
= Exporting a content view version in the syncable format

[role="_abstract"]
You can export a version of a content view to a syncable format that you can use to create your custom CDN.
After you have exported the content view, you can do either of the following:

* Synchronize the content from your custom CDN over HTTP/HTTPS.
* Import the content using `hammer content-import`.
Note that this requires both the Export and Import servers to run {Project} {ProjectVersion}.

include::snip_generating-content.adoc[]

include::snip_content-types-syncable-export.adoc[]

.Prerequisites
ifdef::containerized[]
include::snip_allowed-export-paths-prerequisite.adoc[]
endif::[]
* Download policy is set to *Immediate* for all repositories within the content view you export.
For more information, see xref:Download_Policies_Overview_{context}[].
* Products that you export are synchronized to the required date.
* The user exporting the content has the _Content Exporter_ role.

.Procedure
. List versions of the content view that are available for export:
+
[subs="+quotes"]
----
$ hammer content-view version list \
--content-view="_My_Content_View_Name_" \
--organization="_My_Organization_"
----
+
Note the version number that you want to export.
In the following example, the version number is `1.0`.
. Export the content view version in a syncable format:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-export complete version \
--content-view="_My_Content_View_Name_" \
--version=1.0 \
--organization="_My_Organization_" \
--format=syncable
----

.Verification
* Verify that the exported content is located in the export directory:
+
[options="nowrap" subs="+quotes"]
----
# ls -lh /var/lib/pulp/exports/_My_Organization_/_My_Content_View_Name_/1.0/2021-02-25T18-59-26-00-00/
----
