:_mod-docs-content-type: PROCEDURE

[id="exporting-the-library-environment-in-the-syncable-format"]
= Exporting the Library environment in the syncable format

[role="_abstract"]
You can export content in the Library environment of an organization to a syncable format that you can use to create your custom CDN and synchronize the content from the custom CDN over HTTP/HTTPS.

ifdef::satellite[]
You can then serve the generated content on a local web server and synchronize it on the importing {ProjectServer} or in another {ProjectServer} organization.
endif::[]

You can use the generated content to create the same repository in another {ProjectServer} or in another {ProjectServer} organization by using content import.
On import of the exported archive, a regular content view is created or updated on your importing {ProjectServer}.
For more information, see xref:Importing_a_Content_View_Version_{context}[].

include::snip_content-types-syncable-export.adoc[]

The export contains directories with the packages, *listing* files, and metadata of the repository in Yum format that can be used to synchronize in the importing {ProjectServer}.

.Prerequisites
* Download policy is set to *Immediate* for all repositories within the Library lifecycle environment you export.
For more information, see xref:Download_Policies_Overview_{context}[].
* Products that you export are synchronized to the required date.
* The user exporting the content has the _Content Exporter_ role.

.Procedure
. Use the organization name or ID to export:
+
[options="nowrap" subs="+quotes"]
----
$ hammer content-export complete library \
--organization="_My_Organization_" \
--format=syncable
----
. Optional: Verify that the exported content is located in the export directory:
+
[options="nowrap" subs="+quotes"]
----
# du -sh /var/lib/pulp/exports/_My_Organization_/Export-_My_Repository_/1.0/2021-03-02T03-35-24-00-00
----
