[id="Exporting_the_Library_Environment_{context}"]
= Exporting the Library Environment

You can export contents of all Yum repositories in the Library environment of an organization to an archive file from {ProjectServer} and use this archive file to create the same repositories in another {ProjectServer} or in another {ProjectServer} organization.
The exported archive file contains the following data:

* A JSON file containing Content View version metadata.
* An archive file containing all the repositories from the Library environment of the organization.

{ProjectServer} exports only RPM and kickstart files included in a Content View version.
{Project} does not export the following content:

* Docker content

.Prerequisites

To export the contents of the Library lifecycle environment of the organization, ensure that {ProjectServer} where you want to export meets the following conditions:

* Ensure that the export directory has free storage space to accommodate the export.
* Ensure that the `/var/lib/pulp/exports` directory has free storage space equivalent to the size of the repositories being exported for temporary files created during the export process.
* Ensure that you set download policy to *Immediate* for all repositories within the Library lifecycle environment you export.
For more information, see xref:Download_Policies_Overview_{context}[].
* Ensure that you synchronize Products that you export to the required date.

.Export the Library Content of an Organization
. Use the organization name or ID to export.
+
[options="nowrap" subs="+quotes"]
----
# hammer content-export complete library --organization="_My_Organization_"
----
. Verify that the archive containing the exported version of a Content View is located in the export directory:
+
[options="nowrap" subs="+quotes"]
----
# ls -lh /var/lib/pulp/exports/_My_Organization_/Export-Library/1.0/2021-03-02T03-35-24-00-00
total 68M
-rw-r--r--. 1 pulp pulp 68M Mar  2 03:35 export-1e25417c-6d09-49d4-b9a5-23df4db3d52a-20210302_0335.tar.gz
-rw-r--r--. 1 pulp pulp 333 Mar  2 03:35 export-1e25417c-6d09-49d4-b9a5-23df4db3d52a-20210302_0335-toc.json
-rw-r--r--. 1 pulp pulp 443 Mar  2 03:35 metadata.json
----
+
You need all three files, the `tar.gz`, the `toc.json`, and the `metadata.json` file to be able to import.
. A new Content View **Export-Library** is created in the organization.
This Content View contains all the repositories belonging to this organization.
A new version of this Content View is published and exported automatically.

.Export with chunking

In many cases the exported archive content may be several gigabytes in size.
If you want to split it into smaller sizes or chunks.
You can use the `--chunk-size-gb` flag directly in the export command to handle this.
In the following example, you can see how to specify `--chunk-size-gb=2` to split the archives in `2 GB` chunks.

[options="nowrap" subs="+quotes"]
----
# hammer content-export complete library \
--chunk-size-gb=2 \
--organization="_My_Organization_"

Generated /var/lib/pulp/exports/_My_Organization_/Export-Library/2.0/2021-03-02T04-01-25-00-00/metadata.json

# ls -lh /var/lib/pulp/exports/_My_Organization_/Export-Library/2.0/2021-03-02T04-01-25-00-00/
----
