:_mod-docs-content-type: PROCEDURE

[id="configuring-the-freeipa-authentication-source-on-projectserver_{context}"]
= Configuring the {FreeIPA} authentication source on {ProjectServer}

[role="_abstract"]
Connect your {ProjectServer} to your {FreeIPA} domain by configuring {FreeIPA} as an authentication provider on your {ProjectServer}.

include::snip_ext-auth-mutually-exclusive.adoc[]

.Prerequisites
* {ProjectServer} running on a system that is enrolled in the {FreeIPA} domain.

.Procedure
. Enable access for your preferred login method:
* To enable access to the {ProjectWebUI} only:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
ifdef::foremanctl[]
# foremanctl deploy --external-authentication ipa
endif::[]
ifndef::foremanctl[]
# {foreman-installer} \
--foreman-ipa-authentication true
endif::[]
----
* To enable access to the {ProjectWebUI} and the {Project} API, including Hammer CLI:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
ifdef::foremanctl[]
# foremanctl deploy --external-authentication ipa_with_api
endif::[]
ifndef::foremanctl[]
# {foreman-installer} \
--foreman-ipa-authentication-api true \
--foreman-ipa-authentication true
endif::[]
----
+
[WARNING]
====
Enabling access to both the {ProjectWebUI} and the {Project} API poses a security risk.
After the {FreeIPA} user enters `kinit` to receive a Kerberos ticket-granting ticket (TGT), an attacker might obtain an API session.
The attack is possible even if the user did not previously enter the {Project} login credentials anywhere, for example in the browser.
====
. If your {ProjectServer} runs in an IPv6-only network and also runs on {EL}{nbsp}9.6 and earlier or {EL}{nbsp}10.0, set the `lookup_family_order` option in the `[domain/_{freeipaserver-example-com}_]` section of the `/etc/sssd/sssd.conf` file:
+
[source, ini, options="nowrap", subs="+quotes,verbatim,attributes"]
----
[domain/_{freeipaserver-example-com}_]
lookup_family_order = ipv6_only
----
+
If the DNS name of the IdM server can be translated to both an IPv4 and IPv6 address but the IPv4 address is not accessible, SSSD requires `lookup_family_order` to translate the DNS name correctly.
Without the option, IdM users are unable to use `kinit` to authenticate to {Project}.
// Related SSSD issue: https://github.com/SSSD/sssd/issues/3057

.Verification
* Log in to {ProjectWebUI} by entering the credentials of a user defined in {FreeIPA}.

.Additional resources
* xref:resetting-external-authentication-configuration-for-kerberos-sso[]
