[id="Promoting_SCAP_Content_to_Clients_{context}"]
= Promoting SCAP Content to Clients

The following section describes how to promote Security Content Automation Protocol (SCAP) content to clients registered to {SmartProxyServers} that you configure for load balancing.

.Prerequisite
* Ensure that you configure the SCAP content.
For more information, see {AdministeringDocURL}Configuring_SCAP_Content_admin[Configuring SCAP Content] in _{AdministeringDocTitle}_.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Classes* and click `foreman_scap_client`.
. Click the *Smart Class Parameter* tab.
. In the pane to the left of the *Smart Class Parameter* window, click `port`.
. In the *Default Behavior* area, select the *Override* checkbox.
. From the *Key Type* list, select `integer`.
. In the *Default Value* field, enter `{smartproxy_port}`.
. In the pane to the left of the *Smart Class Parameter* window, click `server`.
. In the *Default Behavior* area, select the *Override* checkbox.
. From the *Key Type* list, select `string`.
. In the *Default Value* field, enter the FQDN of your load balancer.
For example, `_{loadbalancer-example-com}_`.
. In the lower left of the *Smart Class Parameter* window, click *Submit*.
. Add the puppet module that contains the `foreman_scap_client` puppet class to a Content View.
Publish and promote this Content View to your client's environment.
. If you want to verify the configuration, run the Puppet agent on the client to promote the changes.
Do not run the Puppet agent on every client manually because the Puppet agent runs on the clients every 30 minutes.
+
----
# puppet agent -t --noop
----
. On the client, verify that the `/etc/foreman_scap_client/config.yaml` file contains the following lines:
+
[options="nowrap", subs="+quotes,attributes"]
----
# Foreman proxy to which reports should be uploaded
:server: '_{loadbalancer-example-com}_'
:port: {smartproxy_port}
----

.Additional Resources
* For more information about adding Puppet modules to {ProjectServer}, see {ManagingConfigurationsPuppetDocURL}installing_a_puppet_module_managing-configurations-puppet[Installing a Puppet Module on {ProjectServer}] in _{ManagingConfigurationsPuppetDocTitle}_.
* For more information about Content Views, see {ContentManagementDocURL}Managing_Content_Views_content-management[Managing Content Views] in _{ContentManagementDocTitle}_.
