:_mod-docs-content-type: PROCEDURE

[id="configuring-the-global-{smart-proxy-context}-remote-execution-setting-by-using-web-ui"]
= Configuring the global {SmartProxy} remote execution setting by using {ProjectWebUI}

[role="_abstract"]
By default, {Project} searches for remote execution {SmartProxies} in hosts' organizations and locations regardless of whether {SmartProxies} are assigned to hosts' subnets or not.
You can disable the *Enable Global {SmartProxy}* setting if you want to limit the search to the {SmartProxies} that are assigned to hosts' subnets.

If the *Enable Global {SmartProxy}* setting is enabled, {Project} adds another set of {SmartProxies} to select the remote execution {SmartProxy} from.
{Project} also selects the most lightly loaded remote execution {SmartProxy} from the set of all {SmartProxies} in the host's organization and location to execute a remote job.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. Click *Remote Execution*.
. Configure the *Enable Global {SmartProxy}* setting.
