[id="Adding_VMware_Images_to_Server_{context}"]
= Adding VMware Images to {ProjectServer}

VMware vSphere uses templates as images for creating new virtual machines.
If using image-based provisioning to create new hosts, you need to add VMware template details to your {ProjectServer}.
This includes access details and the template name.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-vmware-vsphere-images-to-server_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Compute Resources* and in the Compute Resources window, click the VMware vSphere connection.
. In the *Name* field, enter a name for the image.
. From the *Operatingsystem* list, select the base operating system of the image.
. From the *Architecture* list, select the operating system architecture.
. In the *User* field, enter the SSH user name for image access.
This is normally the `root` user.
. In the *Password* field, enter the SSH password for image access.
. From the *User data* list, select whether you want the images to support user data input, such as `cloud-init` data.
. In the *Image* field, enter the relative path and name of the template on the vSphere environment.
Do not include the data center in the relative path.
. Click *Submit* to save the image details.

[id="cli-adding-vmware-vsphere-images-to-server_{context}"]
.CLI procedure
* Create the image with the `hammer compute-resource image create` command.
Use the `--uuid` field to store the relative template path on the vSphere environment:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-resource image create \
--architecture "_My_Architecture_" \
--compute-resource "_My_VMware_"
--name "_My_Image_" \
--operatingsystem "_My_Operating_System_" \
--username root \
--uuid "_My_UUID_"
----
