:_mod-docs-content-type: PROCEDURE

[id="retrieving-the-status-of-services-by-using-web-ui"]
= Retrieving the status of services by using {ProjectWebUI}

[role="_abstract"]
{Project} uses a set of back-end services.
When troubleshooting, you can check the status of {Project} services in {ProjectWebUI}.

.Procedure
* In the {ProjectWebUI}, navigate to *Administer* > *About*.
** On the *{SmartProxies}* tab, view the status of all {SmartProxies}.
** On the *Available Providers* tab, view the status of enabled compute resource providers.
** On the *Compute Resources* tab, view the status of attached compute resource providers.
** on the *Plugins* tab, view the list of installed plugins.

.CLI procedure
* Get information from the database and {Project} services:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer ping
----
* Check the status of the services running in systemd:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service status
----
+
Run `{foreman-maintain} service --help` for more information.
* Perform a health check:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ {foreman-maintain} health check
----
+
Run `{foreman-maintain} health --help` for more information.
