[id="upgrading_a_disconnected_{project-context}_server_{context}"]
= Upgrading a disconnected {ProjectServer}

Use this procedure if your {ProjectServer} is not connected to the Red{nbsp}Hat Content Delivery Network.

[WARNING]
====
// Keep this in sync with common/modules/snip_warning-maintain-config-noop.adoc
* If you customized configuration files, either manually or using a tool such as Hiera, these changes are overwritten when you enter the `{foreman-maintain}` command during upgrading or updating.
You can use the `--noop` option with the `{foreman-installer}` command to review the changes that are applied during upgrading or updating.
ifdef::satellite[]
For more information, see the Red Hat Knowledgebase solution https://access.redhat.com/solutions/3351311[How to use the noop option to check for changes in {Project} config files during an upgrade].
endif::[]
====

.Prerequisites

* These instructions are for upgrading a disconnected {ProjectServer} {ProjectVersionPrevious} running on RHEL 9 to {ProjectServer} {ProjectVersion}. If you are running {ProjectServer} {ProjectVersionPrevious} on RHEL 8, you need to first Leapp upgrade {ProjectServer} {ProjectVersionPrevious} to RHEL 9 and then follow the upgrade steps below to upgrade to {ProjectVersion}.
  
.Before you begin

* Review and update your firewall configuration before upgrading your {ProjectServer}.
For more information, see {InstallingServerDisconnectedDocURL}Port_and_firewall_requirements_satellite[Port and firewall requirements] in _{InstallingServerDisconnectedDocTitle}_.
* Ensure that you do not delete the manifest from the Customer Portal or in the {ProjectWebUI} because this removes all the entitlements of your content hosts.
ifdef::satellite[]
* All {ProjectServer}s must be on the same version.
endif::[]


.Upgrade disconnected {ProjectServer}

. Stop all {Project} services:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service stop
----
+
. Take a snapshot or create a backup:
* On a virtual machine, take a snapshot.
* On a physical machine, create a backup.
. Start all {Project} services:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service start
----

. Optional: If you made manual edits to DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, back up the configuration files because the installer only supports one domain or subnet, and therefore restoring changes from these backups might be required.

. Optional: If you made manual edits to DNS or DHCP configuration files and do not want to overwrite the changes, enter the following command:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} --foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false
----

. In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
If there are discovered hosts available, turn them off and then delete all entries under the `Discovered hosts` page.
Select all other organizations in turn using the organization setting menu and repeat this action as required.
Reboot these hosts after the upgrade has completed.

. Remove old repositories:
+
[options="nowrap" subs="attributes"]
----
# rm /etc/yum.repos.d/*
----

.On the connected {ProjectServer}
. Ensure that you have synchronized the following repositories in your connected {ProjectServer}:
+
* {RepoRHEL9BaseOS}
* {RepoRHEL9AppStream}
* {RepoRHEL9ServerSatelliteServerProjectVersion}
. Export these repositories via Syncable format. `hammer content-export complete repository --id=<repo_id> --format=syncable`
. Copy the exported directories over to your disconnected {ProjectServer}.

.On the disconnected {ProjectServer}
. Identify the location of the copied content.
. Create the repository data file and add the `baseurl` directive.
+
[options="nowrap" subs="+quotes"]
----
[RHEL 9 Base OS]
name=Red Hat Enterprise Linux 9 for x86_64 - BaseOS (RPMs)
metadata_expire=-1
gpgcheck=0
cost=500
baseurl=file:///<export baseos location>/content/dist/rhel9/9/x86_64/baseos/os

[RHEL 9 AppStream]
name=Red Hat Enterprise Linux 9 for x86_64 - AppStream (RPMs)
mediaid=None
metadata_expire=-1
gpgcheck=0
cost=500
baseurl=file:///<export appstream location>/content/dist/rhel9/9/x86_64/appstream/os

[Satellite]
name=Satellite
mediaid=None
metadata_expire=-1
gpgcheck=0
cost=500
baseurl=file:///<export location>/content/dist/layered/rhel8/x86_64/satellite/{ProjectVersion}/os/
----

. Optional: Because of the lengthy upgrade time, use a utility such as `tmux` to suspend and reattach a communication session.
You can then check the upgrade progress without staying connected to the command shell continuously.
+
If you lose connection to the command shell where the upgrade command is running, you can see the logs in `{installer-log-file}` to check if the process completed successfully.

. Upgrade {foreman-maintain} to its next version:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} self-upgrade --maintenance-repo-label=Satellite
----

. If you are using an external database, upgrade your database to PostgreSQL 13.
. Use the health check option to determine if the system is ready for upgrade.
When prompted, enter the hammer admin user credentials to configure `{foreman-maintain}` with hammer credentials.
These changes are applied to the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade check --whitelist="repositories-validate,repositories-setup"  --target-version={ProjectVersion}
----
+
Review the results and address any highlighted error conditions before performing the upgrade.
. Perform the upgrade:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade run --whitelist="repositories-validate,repositories-setup" --target-version={ProjectVersion}
----
+
If the script fails due to missing or outdated packages check your exported content.
For more information, see {InstallingServerDisconnectedDocURL}resolving-package-dependency-errors_satellite[Resolving Package Dependency Errors] in _{InstallingServerDisconnectedDocTitle}_.

include::snip_steps-needs-reboot.adoc[]

. Optional: If you made manual edits to DNS or DHCP configuration files, check and restore any changes required to the DNS and DHCP configuration files using the backups that you made.

. If you make changes in the previous step, restart {Project} services:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service restart
----

. If you have the OpenSCAP plugin installed, but do not have the default OpenSCAP content available, enter the following command.
+
[options="nowrap" subs="attributes"]
----
# foreman-rake foreman_openscap:bulk_upload:default
----

. In the {ProjectWebUI}, navigate to *Configure* > *Discovery Rules*.
 Associate selected organizations and locations with discovery rules.
