[id="using-novnc-to-access-virtual-machines_{context}"]
= Using noVNC to Access Virtual Machines

You can use your browser to access the VNC console of VMs created by {Project}.

{Project} supports using noVNC on the following virtualization platforms:

* VMware
* Libvirt
* {OVirt}

.Prerequisites

* You must have a virtual machine created by {Project}.
* For existing virtual machines, ensure that the *Display type* in the *Compute Resource* settings is *VNC*.
* You must import the Katello root CA certificate into your {ProjectServer}. Adding a security exception in the browser is not enough for using noVNC. For more information, see the link:{BaseURL}administering_red_hat_satellite/chap-red_hat_satellite-administering_red_hat_satellite-accessing_red_hat_satellite#sect-{Project_Link}-Administering_{Project_Link}-Installing_the_Katello_Root_CA_Certificate[Installing the Katello Root CA Certificate] section in the _Administering {ProjectName}_ guide.

.Procedure

. On the VM host system, configure the firewall to allow VNC service on ports 5900 to 5930:
+
ifeval::["{build}" == "satellite"]
* On Red Hat Enterprise Linux 6:
endif::[]
ifeval::["{build}" != "satellite"]
* On operating systems with the `iptables` command:
endif::[]
+

----
# iptables -A INPUT -p tcp --dport 5900:5930 -j ACCEPT
# service iptables save
----
+
ifeval::["{build}" == "satellite"]
* On Red Hat Enterprise Linux 7:
endif::[]
ifeval::["{build}" != "satellite"]
* On operating systems with the `firewalld` service:
endif::[]
+
----
# firewall-cmd --add-port=5900-5930/tcp
# firewall-cmd --add-port=5900-5930/tcp --permanent
----
ifeval::["{build}" != "satellite"]
+
include::snip_firewalld.adoc[]
+
endif::[]
. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources* and select the name of a compute resource.
. In the *Virtual Machines* tab, select the name of a VM host. Ensure the machine is powered on and then select *Console*.
