[id="Configuring_Server_for_Outgoing_Emails_{context}"]
= Configuring {ProjectServer} for Outgoing Emails

To send email messages from {ProjectServer}, you can use either an SMTP server, or the `sendmail` command.

.Prerequisite
* Some SMTP servers with anti-spam protection or grey-listing features are known to cause problems.
To setup outgoing email with such a service either install and configure a vanilla SMTP service on {ProjectServer} for relay or use the `sendmail` command instead.

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Settings*.
. Click the *Email* tab and set the configuration options to match your preferred delivery method.
The changes have an immediate effect.
+
.. The following example shows the configuration options for using an SMTP server:
+
.Using an SMTP server as a delivery method
[cols=",",options="header"]
|====
|Name| Example value
|Delivery method       | SMTP
|SMTP address          | _smtp.example.com_
|SMTP authentication   | login
|SMTP HELO/EHLO domain | _example.com_
|SMTP password         | _password_
|SMTP port             | 25
|SMTP username         | _user@example.com_
|====
+
The `SMTP username` and `SMTP password` specify the login credentials for the SMTP server.
+
.. The following example uses *gmail.com* as an SMTP server:
+
.Using gmail.com as an SMTP server
[cols=",",options="header"]
|====
|Name| Example value
|Delivery method           | SMTP
|SMTP address              | smtp.gmail.com
|SMTP authentication       | plain
|SMTP HELO/EHLO domain     | smtp.gmail.com
|SMTP enable StartTLS auto | Yes
|SMTP password             | _password_
|SMTP port                 | 587
|SMTP username             | _user_@gmail.com
|====
+
.. The following example uses the `sendmail` command as a delivery method:
+
.Using sendmail as a delivery method
[cols=",",options="header"]
|====
|Name| Example value
|Delivery method | Sendmail
|Sendmail location | /usr/sbin/sendmail
|Sendmail arguments | -i
|====
+
For security reasons, both Sendmail location and Sendmail argument settings are read-only and can be only set in `/etc/foreman/settings.yaml`.
Both settings currently cannot be set via `{foreman-installer}`.
ifdef::foreman,katello,orcharhino[]
This is being tracked in https://projects.theforeman.org/issues/33543[issue #33543].
endif::[]
For more information see the *sendmail 1* man page.

. If you decide to send email using an SMTP server which uses TLS authentication, also perform one of the following steps:
+
* Mark the CA certificate of the SMTP server as trusted.
To do so, execute the following commands on {ProjectServer}:
+
[options="nowrap"]
----
# cp mailca.crt /etc/pki/ca-trust/source/anchors/
# update-ca-trust enable
# update-ca-trust
----
+
Where `_mailca.crt_` is the CA certificate of the SMTP server.
+
* Alternatively, in the {ProjectWebUI}, set the `SMTP enable StartTLS auto` option to `No`.

. Click *Test email* to send a test message to the user's email address to confirm the configuration is working.
If a message fails to send, the {ProjectWebUI} displays an error.
See the log at `/var/log/foreman/production.log` for further details.

NOTE: For information on configuring email notifications for individual users or user groups, see {AdministeringDocURL}Configuring_Email_Notifications_admin[Configuring Email Notifications] in _{AdministeringDocTitle}_.
