[id="Viewing_Compliance_Policy_Statistics_{context}"]
= Viewing Compliance Policy Statistics

You can view a compliance policy dashboard to verify compliance reports of a particular policy.
The compliance policy dashboard provides a statistical summary of compliance of hosts and the ability to view report details for each host within the scope of that policy.

For all hosts which were evaluated as non-compliant, the `Failed` statistic provides a useful metric for prioritizing compliance effort.
{Team} recommends to make the hosts detected as `Never audited` also a priority, since their status is unknown.

The dashboard provides the following information:

* A ring chart illustrating a high-level view of compliance of hosts with the policy.
* A statistical breakdown of compliance of hosts with the policy, in a tabular format.
* Links to the latest policy report for each host.

.Prerequisite
* Your user account has the `view_policies` permission.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *Policies*.
. In the row of the required policy, navigate to the *Actions* column and click *Dashboard*.
