:_mod-docs-content-type: PROCEDURE

[id="adding-a-remote-console-connection-for-a-host-on-proxmox"]
= Adding a remote console connection for a host on Proxmox

[role="_abstract"]
Configure {Project} and Proxmox to access the VNC remote console through {ProjectWebUI}.

.Prerequisites
* Your host has the VGA output `Standard VGA`.
* Your host has the type `KVM/Qemu server`.

.Procedure
. On your Proxmox, open the required port for VNC:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# firewall-cmd --add-port=_My_Port_/tcp --permanent && firewall-cmd --reload
----
+
The port is the sum of `5900` and the VMID of your host.
You can find the ID of your host on Proxmox.
For example, if your host has the VMID 142, open port `6042`.
. On your Proxmox, enable VNC for your host in `/etc/pve/nodes/_My_Proxmox_Instance_/qemu-server/_My_VMID_.conf`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
args: -vnc 0.0.0.0:_My_VMID_
----
+
For more information, see https://pve.proxmox.com/wiki/VNC_Client_Access[VNC Client Access] in the Proxmox documentation.
. Restart your host on Proxmox.
. On your {ProjectServer}, open the required port for VNC:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# firewall-cmd --add-port=_My_Port_/tcp --permanent && firewall-cmd --reload
----
ifndef::foreman-deb[]
. On your {ProjectServer}, allow the `websockify` capability in SELinux:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# setsebool -P foreman_rails_can_connect_all on && setsebool -P websockify_can_connect_all on
----
endif::[]
ifdef::katello,satellite,orcharhino[]
. If you use a custom SSL certificate, import the SSL certificate from {ProjectServer} into your browser.
For more information, see {ConfiguringUserAuthenticationDocURL}importing-the-katello-root-ca-certificate-by-using-browser[Importing the Katello root CA certificate by using browser] in _{ConfiguringUserAuthenticationDocTitle}_.
+
The remote console connection to your host will fail if you choose to temporarily accept not checking the certificates in your browser.
endif::[]

.Next steps
* You can now view the VNC console of your host in {ProjectWebUI}.
