[id="Synchronizing_a_Custom_Repository_{context}"]
= Synchronizing a Custom Repository

Use this procedure to synchronize content from a custom repository on a connected {ProjectServer} to a disconnected {ProjectServer} through {ISS} (ISS) Network Sync.

[NOTE]
====
When using {ISS} Network Sync, Red Hat repositories are configured automatically, but custom repositories are not.
They require performing the manual procedures mentioned below.
====

Follow the procedure for the connected {ProjectServer} before completing the procedure for the disconnected {ProjectServer}.

.Connected {ProjectServer}
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Click on the custom product.
. Click on the custom repository.
. Copy the *Published At:* URL.
. Continue with the procedure on disconnected {ProjectServer}.

.Disconnected {ProjectServer}
. Download the file `http://{foreman-example-com}/pub/katello-server-ca.crt` from the connected {ProjectServer} using `curl` or `wget`.
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl https://{foreman-example-com}/pub/katello-server-ca.crt
----
. On the disconnected {ProjectServer}, create an SSL Content Credential with the contents of this file.
. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Create your custom product with the following:
* *Upstream URL*: Paste the link that you copied earlier.
* *SSL CA Cert*: Select the SSL certificate that was transferred from your connected {ProjectServer}.

For more information on creating an SSL Content Credential, see xref:Importing_Custom_SSL_Certificates_{context}[].
For more information on creating a custom product, see xref:Creating_a_Custom_Product_{context}[].

After completing these steps, the disconnected {ProjectServer} will synchronize the custom repository as normal.
