[id="creating-architectures_{context}"]
= Creating Architectures

An architecture in {Project} represents a logical grouping of hosts and operating systems.
Architectures are created by {Project} automatically when hosts check in with Puppet.
Basic i386 and x86_64 architectures are already preset in {Project}.

Use this procedure to create an architecture in {Project}.

ifdef::satellite[]
.Supported Architectures

Only Intel x86_64 architecture is supported for provisioning using PXE, Discovery, and boot disk.
For more information, see the Red Hat Knowledgebase solution https://access.redhat.com/solutions/2674001[Supported architectures and provisioning scenarios in Satellite 6].
endif::[]

.Procedure

. In the {ProjectWebUI}, navigate to *Hosts* > *Architectures* and click *Create Architecture*.
. In the *Name* field, enter a name for the architecture.
ifndef::orcharhino[]
. From the *Operating Systems* list, select an operating system.
endif::[]
ifdef::orcharhino[]
. From the *Operating Systems* list, select an xref:sources/management_ui/the_hosts_menu/operating_systems.adoc[operating system].
endif::[]
If none are available, you can create and assign them under *Hosts* > *Operating Systems*.
. Click *Submit*.

.CLI procedure

* Enter the `hammer architecture create` command to create an architecture.
ifndef::orcharhino[]
Specify its name and operating systems that include this architecture:
endif::[]
ifdef::orcharhino[]
Specify its name and operating systems that include this xref:sources/management_ui/the_hosts_menu/architectures.adoc[architecture]:
endif::[]
+
[options="nowrap" subs="+quotes"]
----
# hammer architecture create --name "_Architecture_Name_" \
--operatingsystems "_os_"
----
