[id="Adding_an_SCC_Account_to_Server_{context}"]
= Adding an SCC account to {Project}

Use the following procedure to add your SCC account to {Project}.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-Adding_an_SCC_Account_to_Server_{context}[].

.Prerequisites
* You have installed the SCC Manager plugin on your {Project}.
For more information, see xref:Installing_the_SCC_Manager_plugin_{context}[].

.Procedure
. Optional: In the {ProjectWebUI}, navigate to *Content* > *Content Credentials* and click *Create Content Credential*.
+
Add the GPG public key for SLES 15 SP3 from https://www.suse.com/support/security/keys/[suse.com].
. In the {ProjectWebUI}, navigate to *Content* > *SUSE Subscriptions*.
. Click *Add SCC Account*.
. In the *Name* field, enter a name for your SCC account in {Project}.
. In the *Login* and *Password* fields, enter your SUSE credentials.
. In the *Base URL* field, you can enter the base URL for the Suse Customer Center.
By default, it is set to `\https://scc.suse.com`.
. Optional: Set a *Sync interval* to periodically update the SCC authentication tokens.
Note that this does not refer to synchronizing content to {Project}.
. Optional: In the *Use GPG key for SUSE products* field, you can select the previously created content credential to automatically add a GPG public key to your SUSE products.
`zypper` automatically verifies the signatures of each software package to ensure their authenticity.
+
[NOTE]
====
You can also set the GPG public key for repositories from SUSE at a later stage.
However, changing it does not affect already synchronized products.
If you already have synchronized products in {Project}, navigate to *Content > Products* and replace the GPG key in each respective product.
====
. Optional: From the *Download Policy* list, select a download policy for your SUSE products.
For more information, see xref:Download_Policies_Overview_{context}[].
. Optional: From the *Mirroring Policy* list, select a mirroring policy for your SUSE products.
For more information, see xref:Mirroring_Policies_Overview_{context}[].
. Click *Test connection* to verify your account information.
Note that you have to re-enter your password if you have already saved your SCC account to {Project}.
. Click *Submit* to save your SCC account to {Project}.
. In the {ProjectWebUI}, navigate to *Content > SUSE Subscriptions*, select your SCC account, and click *Sync* to fetch a list of products associated to your SCC account.

[id="cli-Adding_an_SCC_Account_to_Server_{context}"]
.CLI procedure
. Optional: Import the public GPG key from SUSE into {Project}.
+
For more information, see {ContentManagementDocURL}cli-importing-a-gpg-key[Importing a GPG Key] in _{ContentManagementDocTitle}_.
. Add your SCC account to {Project}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer scc_manager scc_accounts create \
--base-url "https://scc.suse.com/" \
--interval _My_Interval_ \
--katello-gpg-key-id _My_GPG_Key_ID_ \
--location-id _My_Location_ID_ \
--login "_My_SCC_Account_Name_" \
--name "_My_Account_Name_" \
--organization-id _My_Organization_ID_ \
--password "_My_SCC_Account_Password" \
--sync-date _My_Sync_Date_
----
. Test your SCC account credentials:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer scc_manager scc_accounts test_connection \
--id _My_SCC_Account_ID_
----
+
Ensure the command returns `Testing connection for SCC account succeeded`.
. Synchronize the list of available SUSE products to {Project}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer scc_manager scc_accounts sync \
--id _My_SCC_Account_ID_
----
. Check the status of the task:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer task info \
--id _My_Task_ID_
----
+
The synchronization is complete once the command returns `State: stopped` and `Result: success`.
