:_mod-docs-content-type: PROCEDURE

[id="pushing-container-images-to-{project-context}"]
= Pushing container images to {Project}

[role="_abstract"]
Push container images to the {Project} container registry to distribute custom images to hosts and lifecycle environments through {Project} content management.

.Prerequisites
* You have reviewed xref:considerations-for-using-the-{project-context}-container-registry[].
* If {ProjectServer} uses a self-signed certificate, you have configured Podman or Docker to trust the {Project} certificate authority.
For more information, see xref:configuring-podman-to-trust-the-certificate-authority[] and xref:configuring-docker-to-trust-the-certificate-authority[].
* Your {Project} account has the `edit_products` permission.
* A product exists in your organization.
For more information, see xref:creating-a-custom-product-by-using-web-ui[].
* Your {Project} account has the `create_personal_access_tokens` permission.
{Project} automatically generates a token when you run `podman login`.

.Procedure
. Log in to the container registry:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ podman login _{foreman-example-com}_
----
. Push a container image to the {Project} container registry.
To indicate which organization, product, and repository the container image belongs to, include the organization and product in the container image path.
+
You can specify the container image destination by using one of the following schemas:
+
* Push the container image by using the label-based schema:
+
[options="nowrap", subs="+quotes,attributes,verbatim"]
----
$ podman push _My_Container_Image_ID_ _{foreman-example-com}_/_My_Organization_Label_/_My_Product_Label_/_My_Repository_Name_[:__My_Tag__]
----
* Push the container image by using the ID-based schema:
+
[options="nowrap", subs="+quotes,attributes,verbatim"]
----
$ podman push _My_Container_Image_ID_ _{foreman-example-com}_/id/_My_Organization_ID_/_My_Product_ID_/_My_Repository_Name_[:__My_Tag__]
----

+
The image tag is optional.
. After the content push has completed, {Project} creates the repository.
