[id="Configuring_Direct_AD_Integration_with_GSS_Proxy_{context}"]
= Configuring direct AD integration with GSS-proxy

In the {Project} CLI, configure the direct Active Directory integration with GSS-proxy.

.Prerequisites
* {Project} is enrolled with the Active Directory server.
For more information, see xref:Enrolling_Server_with_the_AD_Server_{context}[].

.Procedure
. Create the `/etc/ipa/` directory and the `default.conf` file:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir /etc/ipa
# touch /etc/ipa/default.conf
----
. To the `default.conf` file, add the following content:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
[global]
server = unused
realm = _EXAMPLE.ORG_
----
. Create the `/etc/net-keytab.conf` file with the following content:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
[global]
workgroup = EXAMPLE
realm = EXAMPLE.ORG
kerberos method = system keytab
security = ads
----
. Determine the effective user ID of the Apache user:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# id {apache-user}
----
+
Apache user must not have access to the keytab file.
. Create the `/etc/gssproxy/00-http.conf` file with the following content:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
[service/HTTP]
mechs = krb5
cred_store = keytab:/etc/gssproxy/http.keytab
cred_store = ccache:/var/lib/gssproxy/clients/krb5cc_%U
euid = __ID_of_Apache_User__
----
. Set the correct SELinux context for the future keytab entry:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# semanage fcontext -a -s system_u -t krb5_keytab_t '/etc/gssproxy/http\.keytab'
----
. Create a keytab entry:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# KRB5_KTNAME=FILE:/etc/gssproxy/http.keytab net ads keytab add HTTP -U administrator -d3 -s /etc/net-keytab.conf
# chown root.root /etc/gssproxy/http.keytab
# chmod 600 /etc/gssproxy/http.keytab
----
// TO BE CONFIRMED: This step should not be needed
. Add a *Service Principal Name (SPN)* for your AD server.
You can use a tool such as `adcli`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# adcli spn --add _My_Service_/{foreman-example-com} _My_Username_
----
. Configure SSSD to map Group Policy Objects (GPOs) from AD to the `foreman` PAM service by ensuring the following lines are included in the `/etc/sssd/sssd.conf` file:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
access_provider = ad
ad_gpo_access_control = enforcing
ad_gpo_map_service = +foreman
----
ifdef::satellite[]
+
For more information on GPOs, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/integrating_rhel_systems_directly_with_windows_active_directory/managing-direct-connections-to-ad_integrating-rhel-systems-directly-with-active-directory#applying-group-policy-object-access-control-in-rhel_managing-direct-connections-to-ad[How SSSD interprets GPO access control rules] in _Integrating RHEL systems directly with Windows Active Directory_.
endif::[]
. If you changed the `/etc/sssd/sssd.conf` configuration file, restart the `sssd` service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart sssd
----
. Enable IPA authentication in {Project}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --foreman-ipa-authentication=true
----
. Start and enable the `gssproxy` service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart gssproxy
# systemctl enable --now gssproxy
----
. To configure the Apache server to use the `gssproxy` service, create a `systemd` drop-in file and add the following content to it:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir -p /etc/systemd/system/httpd.service.d/
# vi /etc/systemd/system/httpd.service.d/gssproxy.conf
[Service]
Environment=GSS_USE_PROXY=1
----
. Apply changes to the service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl daemon-reload
----
. Start and enable the `httpd` service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart httpd
----

.Verification
Verify that SSO is working as expected.

With a running Apache server, users making HTTP requests against the server are authenticated if the client has a valid Kerberos ticket.

. Retrieve the Kerberos ticket of the LDAP user, using the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# kinit ldapuser
----
. View the Kerberos ticket, using the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# klist
----
. View output from successful SSO-based authentication, using the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# curl -k -u : --negotiate https://__{foreman-example-com}/__users/extlogin
----
+
This returns the following response:
+
[options="nowrap", subs="+quotes,attributes"]
----
<html><body>You are being <a href="https://__{foreman-example-com}/__users/4-ldapuserexample-com/edit">redirected</a>.</body></html>
----
