[id="Importing_into_the_Library_Environment_from_webserver_{context}"]
= Importing into the Library Environment from a Webserver

You can import exported Library content  directly from a web server into the Library lifecycle environment of an organization on another {ProjectServer}.
For more information about exporting contents from the Library environment, see xref:Exporting_the_Library_Environment_{context}[].

.Prerequisites
* The exported files must be in a syncable format.
* The exported files must be accessible via http/https.
* If there are any Red Hat repositories in the exported content, the importing organization's manifest must contain subscriptions for the products contained within the export.
* The user importing the Content View version must have the _Content Importer_ Role.
*
.Procedure
. Identify the Organization that you wish to import into.
. To import the Library content to {ProjectServer}, enter the following command:
+
[subs="+quotes"]
----
# hammer content-import library \
--organization="_My_Organization_" \
--path=http://<url>/pub/exports/2021-02-25T21-15-22-00-00/
----
+
A new Content View called `Import-Library` is created in the target organization.
This Content View is used to facilitate the Library content import.
+
By default, this Content View is not shown in the {ProjectWebUI}.
`Import-Library` is not meant to be assigned directly to hosts.
Instead, assign your hosts to `Default Organization View` or another Content View as you would normally.
