[id="Adding_{project-context}_Server_to_{awx-context}_as_a_Dynamic_Inventory_Item_{context}"]
= Adding {ProjectServer} to {awx} as a Dynamic Inventory Item

To add {ProjectServer} to {awx} as a dynamic inventory item, you must create a credential for a {ProjectServer} user on {awx}, add an {awx} user to the credential, and then configure an inventory source.

.Prerequisites
* If your {Project} deployment is large, for example, managing tens of thousands of hosts, using a non-admin user can negatively impact performance because of time penalties that accrue during authorization checks.
For large deployments, consider using an admin user.
* For non-admin users, you must assign the `{awx} Inventory Reader` role to your {ProjectServer} user.
For more information about managing users, roles, and permission filters, see {AdministeringDocURL}Creating_and_Managing_Roles_admin[Creating and Managing Roles] in _{AdministeringDocTitle}_.
* You must host your {ProjectServer} and {awx} on the same network or subnet.

.Procedure
. In the {awx} web UI, create a credential for your {Project}.
For more information about creating credentials, see http://docs.ansible.com/ansible-tower/latest/html/userguide/credentials.html#add-a-new-credential[Add a New Credential] and http://docs.ansible.com/ansible-tower/latest/html/userguide/credentials.html#red-hat-satellite-6[{ProjectName} Credentials] in the _{awx} User Guide_.
+
.{Project} Credentials
[cols="1a,2a"options="header"]
|====
|*Credential Type*: |*{ProjectNameX}*
|*{Project} URL*: |https://_{foreman-example-com}_
|*Username*: |The username of the {Project} user with the integration role.
|*Password*: |The password of the {Project} user.
|====
+
. Add an {awx} user to the new credential.
For more information about adding a user to a credential, see http://docs.ansible.com/ansible-tower/latest/html/userguide/credentials.html#getting-started-with-credentials[Getting Started with Credentials] in the _{awx} User Guide_.
. Add a new inventory.
For more information, see http://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#add-a-new-inventory[Add a new inventory] in the _{awx} User Guide_.
. In the new inventory, add {ProjectServer} as the inventory source, specifying the following inventory source options.
For more information, see https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#add-source[Add Source] in the _{awx} User Guide_.
+
.Inventory Source Options
[cols="1a,2a"options="header"]
|====
|*Source* |*{ProjectNameX}*
|*Credential* |The credential you create for {ProjectServer}.
|*Overwrite* |Select
|*Overwrite Variables* | Select
|*Update on Launch* |Select
|*Cache Timeout* |_90_
|====
+
. Ensure that you synchronize the source that you add.
