[id="configuring-repositories-proxy_{context}"]

= Configuring Repositories

Use this procedure to enable the repositories that are required to install {ProductName}.

. Disable all repositories:
+
[options="nowrap"]
----
# subscription-manager repos --disable "*"
----
+

. Enable the following repositories:
+
[options="nowrap" subs="+quotes,attributes"]
----
# subscription-manager repos --enable={RepoRHEL8BaseOS} \
--enable={RepoRHEL8AppStream} \
--enable={RepoRHEL8ServerSatelliteCapsuleProductVersion} \
--enable={RepoRHEL8ServerSatelliteMaintenanceProductVersion}
----

. Enable the module:
+
[options="nowrap"]
----
# dnf module enable satellite-capsule:el8
----
+
[NOTE]
====
Enablement of the module `satellite-capsule:el8` warns about a conflict with `postgresql:10` and `ruby:2.5` as these modules are set to the default module versions on {RHEL} 8.
The module `satellite-capsule:el8` has a dependency for the modules `postgresql:12` and `ruby:2.7` that will be enabled with the `satellite-capsule:el8` module.
These warnings do not cause installation process failure, hence can be ignored safely.
For more information about modules and lifecycle streams on {RHEL} 8, see https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle[{RHEL} Application Streams Life Cycle].
====
+

NOTE: If you are installing {ProductName} as a virtual machine hosted on {oVirt}, you must also enable the *Red{nbsp}Hat Common* repository, and install {oVirt} guest agents and drivers.
For more information, see https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.4/html/virtual_machine_management_guide/installing_guest_agents_and_drivers_linux_linux_vm#Installing_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux[Installing the Guest Agents and Drivers on {RHEL}] in the _Virtual Machine Management Guide_.
+
. Clear any metadata:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-clean} all
----
+
. Optional: Verify that the required repositories are enabled:
+
[options="nowrap"]
----
# {package-manager} repolist enabled
----
