[id="configuring-satellite-to-synchronize-content-with-a-local-cdn-server_{context}"]
= Configuring Satellite to Synchronize Content with a Local CDN Server

In a disconnected environment, you must ensure that Satellite Server contains the required content to provision systems with the latest security updates, errata, and packages. To do this, follow this procedure to download content ISO images from the Red{nbsp}Hat Customer Portal and import them into a local CDN server. You can host the local CDN server on the base operating system of Satellite Server or on a system that is accessible to Satellite over HTTP. Next, you must configure Satellite Server to synchronize content with the local CDN server.

.Procedure

. Log on to the Red{nbsp}Hat Customer Portal at https://access.redhat.com.

. In the upper left of the window, click *Downloads* and select *Red Hat Satellite*.

. Click the *Content ISOs* tab. This page lists all the products that are available in your subscription.

. Click the link for the product name, such as *Red Hat Enterprise Linux 7 Server (x86_64)* to download the ISO image.

. Copy all of Satellite Content ISO images to a system that you want to use as a local CDN server. For example, the `/root/isos` directory on Satellite Server.
+
Note that storing the content on the same system where Satellite is installed is not a requirement. The CDN can be hosted on a different system inside the same disconnected network as long as it is accessible to Satellite Server over HTTP.

. On the system that you want to use as your local CDN server, create a local directory that is accessible over httpd. For example, `/var/www/html/pub/sat-import/`:
+
----
# mkdir -p /var/www/html/pub/sat-import/
----

. Create a mount point and temporarily mount the ISO image at that location:
+
----
# mkdir /mnt/iso
# mount -o loop /root/isos/first_iso /mnt/iso
----

. Recursively copy content of the first ISO image to the local directory:
+
----
# cp -ruv /mnt/iso/* /var/www/html/pub/sat-import/
----

. If you do not plan to use the mounted binary DVD ISO image, unmount and remove the mount point:
+
----
# umount /mnt/iso
# rmdir /mnt/iso
----

. Repeat the above step for each ISO image until you have copied all the data from the Content ISO images into `/var/www/html/pub/sat-import/`.

. Ensure that the SELinux context for the directory is correct:
+
----
# restorecon -rv /var/www/html/pub/sat-import/
----

. In the Satellite web UI, navigate to *Content* > *Subscriptions*.

. Click *Manage Manifest*.

. Edit the *Red Hat CDN URL* field to point to the host name of the system that you use as a local CDN server with the newly created directory, for example:
+
`http://server.example.com/pub/sat-import/`

. Click *Update* and then upload your manifest into Satellite.
