[id="synchronizing-the-project-client-name-repository-rhel-7-and-rhel-6"]
= Synchronizing the {project-client-name} repository for {RHEL} 7 and {RHEL} 6

[NOTE]
====
You require *{RHEL} Extended Lifecycle Support (ELS) Add-on* subscription to synchronize the repositories of {RHEL} 6.
For more information, see https://www.redhat.com/en/resources/els-datasheet[{RHEL} Extended Lifecycle Support (ELS) Add-on] guide.
====

To use the CLI instead of the {ProjectWebUI}, see the procedure relevant for your {RHEL} version:

* xref:CLI_Synchronizing_the_Client_Repository_rhel_7_{context}[]
* xref:CLI_Synchronizing_the_Client_Repository_rhel_6_{context}[]

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Sync Status*.
. Click the arrow next to the *{RHEL} Server* or *{RHEL} Server - Extended Lifecycle Support*.
. Select *{project-client-name} (for RHEL 7 Server) RPMs x86_64* or *{project-client-name} for RHEL 6 Server - ELS RPMs x86_64* based on your operating system version.
. Click *Synchronize Now*.

[id="CLI_Synchronizing_the_Client_Repository_rhel_7_{context}"]
.CLI procedure for {RHEL} 7
* Synchronize your {project-client-name} repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--async \
--name "{project-client-name} for RHEL 7 Server RPMs x86_64" \
--organization "_My_Organization_" \
--product "{RHEL} Server"
----

[id="CLI_Synchronizing_the_Client_Repository_rhel_6_{context}"]
.CLI procedure for {RHEL} 6
* Synchronize your {project-client-name} repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize \
--async \
--name "{project-client-name} for RHEL 6 Server - ELS RPMs x86_64" \
--organization "_My_Organization_" \
--product "{RHEL} Server - Extended Lifecycle Support"
----

.Additional resources
* For details about the `hammer repository synchronize` command, enter `hammer repository synchronize --help`.
