[id="Synchronizing_SUSE_Content_{context}"]
= Synchronizing SUSE Content

Use this procedure to synchronize SUSE content to your {Project} to deploy, register, and serve content to managed hosts.

.Prerequisite
* You have imported SUSE products into {Project}.
For more information, see xref:Importing_SUSE_Products_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content > Products*.
. Select the `SUSE Linux Enterprise Server 15 SP3 x86_64` product and click *Sync Now* to synchronize the SUSE repositories for SLES 15 SP3 to {Project}.
. In the {ProjectWebUI}, navigate to *Content > Content Views*.
. Create a Content View called `SLES 15 SP3` comprising the SLES repositories created in the `SLES 15 SP3` product and a Content View called `SLES 15 SP3 {Project} client` comprising the {Project} client repository created in the `SLES 15 SP3 {Project} client` product.
+
For more information, see xref:Creating_a_Content_View_{context}[].
. Publish a new version of both Content Views.
+
For more information, see xref:Promoting_a_Content_View_{context}[].
. In the {ProjectWebUI}, navigate to *Content > Content Views*.
. Click *Create Content View* to create a Composite Content View called `Composite SLES 15 SP3` comprising the previously published `SLES 15 SP3` Content View, the `SLES 15 SP3 {Project} client` Content View, and optionally further Content Views of your choice, for example a Content View containing Puppet.
ifdef::orcharhino[]
For more information, see the https://atixservice.zendesk.com/hc/de/articles/360013840079[ATIX Service Portal] for the necessary upstream URL.
endif::[]
For more information, see xref:Creating_a_Composite_Content_View_{context}[].
. Publish a new version and promote this version to the Life Cycle Environment of your choice.
. In the {ProjectWebUI}, navigate to *Content > Activation Keys*.
. Click *Create Activation Key* to create an Activation Key called `sles-15-sp3`.
+
For more information, see xref:Creating_an_Activation_Key_{context}[].
. On the *Details* tab, select a Life Cycle Environment and Composite Content View.
. On the *Subscriptions* tab, select the necessary subscriptions, for example `SLES 15 SP3`, `SLES 15 SP3 {Project} client`, and `Puppet`.
