:_mod-docs-content-type: PROCEDURE

[id="creating-architectures-by-using-web-ui"]
= Creating architectures by using {ProjectWebUI}[[creating-architectures_provisioning]]

[role="_abstract"]
You can group hosts and operating systems in {Project} by creating custom architectures.
{Project} automatically creates architectures when hosts check in with Puppet, and x86_64 is already preset.

ifdef::satellite[]
[NOTE]
====
Only the Intel x86_64 architecture is supported for provisioning using PXE, Discovery, and boot disk.
For more information, see the Red Hat Knowledgebase solution https://access.redhat.com/solutions/2674001[Supported architectures and provisioning scenarios in Satellite 6].
====
endif::[]

.Procedure

. In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning Setup* > *Architectures*.
. Click *Create Architecture*.
. In the *Name* field, enter a name for the architecture.
. From the *Operating Systems* list, select an operating system.
If none are available, you can create and assign them under *Hosts* > *Provisioning Setup* > *Operating Systems*.
. Click *Submit*.
