:_mod-docs-content-type: PROCEDURE

[id="enabling-power-management-on-hosts_{context}"]
= Enabling power management on hosts

[role="_abstract"]
To perform power management tasks on hosts using the intelligent platform management interface (IPMI) or a similar protocol, you must enable the baseboard management controller (BMC) module on {ProductName}.

{ProjectName} supports the following BMC providers:

* `freeipmi`
* `ipmitool`
* `redfish`

.Prerequisites
* Your host has a network interface of the BMC type.
{ProductName} uses this NIC to pass credentials to the host.

.Procedure
. Enable the BMC module and select the default provider:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} \
--foreman-proxy-bmc "true" \
--foreman-proxy-bmc-default-provider "_freeipmi_"
----
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Subnets*.
. Select the subnet of your host.
ifdef::satellite[]
. On the *{SmartProxies}* tab, select your {ProductName} as *BMC {SmartProxy}*.
endif::[]
ifndef::satellite[]
. On the *Proxies* tab, select your {ProductName} as *BMC Proxy*.
endif::[]
. Click *Submit*.

.Next steps
* Configure a BMC interface on your host.
For more information, see {ManagingHostsDocURL}configuring-a-baseboard-management-controller-interface[Configuring a baseboard management controller (BMC) interface] in _{ManagingHostsDocTitle}_.
