[id="Importing_Custom_SSL_Certificates_{context}"]
= Importing {customssltitle} Certificates

Before you synchronize {customcontent} from an external source, you might need to import SSL certificates into your {customproduct}.
This might include client certs and keys or CA certificates for the upstream repositories you want to synchronize.

If you require SSL certificates and keys to download RPMs, you can add them to {Project}.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-importing-custom-ssl-certificates_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Content Credentials*.
In the Content Credentials window, click *Create Content Credential*.
. In the *Name* field, enter a name for your SSL certificate.
. From the *Type* list, select *SSL Certificate*.
. In the *Content Credentials Content* field, paste your SSL certificate, or click *Browse* to upload your SSL certificate.
. Click *Save*.

[id="cli-importing-custom-ssl-certificates_{context}"]
.CLI procedure
. Copy the SSL certificate to your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ scp _My_SSL_Certificate_ root@{foreman-example-com}:~/.
----
. Upload the SSL Certificate to {Project}:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-credentials create \
--content-type cert \
--name "_My_SSL_Certificate_" \
--organization "_My_Organization_" \
--path ~/_My_SSL_Certificate_
----
