:_mod-docs-content-type: PROCEDURE

[id="creating-an-activation-key-by-using-web-ui"]
= Creating an activation key by using {ProjectWebUI}

[role="_abstract"]
Create an activation key from the {ProjectWebUI} to assign various attributes to hosts during registration.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Activation Keys* and click *Create Activation Key*.
. In the *Name* field, enter the name of the activation key.
. If you want to set a limit, clear the *Unlimited hosts* checkbox, and in the *Limit* field, enter the maximum number of systems you can register with the activation key.
If you want unlimited hosts to register with the activation key, ensure the *Unlimited Hosts* checkbox is selected.
. Optional: In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the environment to use.
. From the *Content View* list, select a content view to use.
ifndef::orcharhino[]
. In the *Repository Sets* tab, override repositories to Enabled or Disabled as desired.
For more information, see xref:enabling-and-disabling-repositories-on-activation-key_{context}[].
endif::[]
. Click *Save*.
. Optional: In the *System Purpose* section, you can configure the activation key to set system purpose attributes on hosts during registration.
This helps determine which repositories are available on the host.
It also helps with reporting in the Subscriptions service of the Red Hat Hybrid Cloud Console.
