[id="installing-standalone-hammer"]
= Installing standalone Hammer

You can install Hammer on a host running {install-on-os} that has no {ProjectServer} installed, and use it to connect from the host to a remote {Project}.

.Prerequisites
ifndef::katello,orcharhino,satellite[]
* Ensure that the CA certificate of {ProjectServer} is deployed to the truststore on the host.
endif::[]
ifdef::katello[]
* Ensure that you register the host to {ProjectServer} or {SmartProxyServer}.
* If you are installing on {EL}{nbsp}9, ensure that the following repositories are enabled and synchronized on {ProjectServer}:
** {EL} 9 BaseOS
** {EL} 9 AppStream
** https://yum.theforeman.org/releases/{ProjectVersion}/el9/x86_64/foreman-release.rpm[{Project} release RPM]
* If you are installing on {EL}{nbsp}8, ensure that the following repositories are enabled and synchronized on {ProjectServer}:
** {EL} 8 BaseOS
** {EL} 8 AppStream
** https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm[{Project} release RPM]
endif::[]
ifdef::orcharhino[]
* Ensure that you register the host to {ProjectServer} or {SmartProxyServer}.
* If you are installing on {EL}{nbsp}8, ensure that the following repositories are enabled and synchronized on {ProjectServer}:
** {EL} 8 BaseOS
** {EL} 8 AppStream
** {SmartProxy} repository
endif::[]
ifdef::satellite[]
* Ensure that you register the host to {ProjectServer} or {SmartProxyServer}.
* If you are installing on {EL}{nbsp}9, ensure that the following repositories are enabled and synchronized on {ProjectServer}:
** {RepoRHEL9BaseOS}
** {RepoRHEL9AppStream}
** {RepoRHEL9ServerSatelliteUtils}
* If you are installing on {EL}{nbsp}8, ensure that the following repositories are enabled and synchronized on {ProjectServer}:
** {RepoRHEL8BaseOS}
** {RepoRHEL8AppStream}
** {RepoRHEL8ServerSatelliteUtils}
endif::[]

.Procedure
ifdef::foreman-deb[]
. Enable the required repositories on the host.
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# wget https://deb.theforeman.org/foreman.asc -O /etc/apt/trusted.gpg.d/foreman.asc
# echo "deb http://deb.theforeman.org/ _My_Distribution_Codename_ {ProjectVersion}" | sudo tee /etc/apt/sources.list.d/foreman.list
# echo "deb http://deb.theforeman.org/ plugins {ProjectVersion}" | sudo tee -a /etc/apt/sources.list.d/foreman.list
----
. Install Hammer CLI:
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# {client-package-install-deb} {project-context}-cli
----
. Set the `:host:` entry in the `/etc/hammer/cli.modules.d/foreman.yml` file to the {Project} URL:
+
[options="nowrap", subs="+quotes,attributes"]
----
:host: 'https://_{foreman-example-com}_'
----
endif::[]
ifdef::foreman-el[]
. Enable the required repositories on the host.
* If you are installing on {EL}{nbsp}9, enable the following repository:
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# {client-package-install-el9} https://yum.theforeman.org/releases/{ProjectVersion}/el9/x86_64/foreman-release.rpm
----
+
* If you are installing on {EL}{nbsp}8, enable the following repository:
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# {client-package-install-el8} https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm
----
. If you are installing on {EL}{nbsp}8, enable the following module:
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# dnf module enable {dnf-module-utils}
----
. Install Hammer CLI:
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# {client-package-install-el8} {project-context}-cli
----
. Set the `:host:` entry in the `/etc/hammer/cli.modules.d/foreman.yml` file to the {Project} URL:
+
[options="nowrap", subs="+quotes,attributes"]
----
:host: 'https://_{foreman-example-com}_'
----
endif::[]
ifdef::katello,orcharhino,satellite[]
. Enable the required repositories on the host.
. If you are installing on {EL}{nbsp}8, enable the following module:
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# dnf module enable {dnf-module-utils}
----
. Install Hammer CLI:
+
[options="nowrap" subs="verbatim,quotes,attributes"]
----
# {client-package-install-el8} {project-context}-cli
----
. Set the `:host:` entry in the `/etc/hammer/cli.modules.d/foreman.yml` file to the {Project} URL:
+
[options="nowrap", subs="+quotes,attributes"]
----
:host: 'https://_{foreman-example-com}_'
----
endif::[]

ifdef::katello,orcharhino,satellite[]
.Additional resources
* {ManagingHostsDocURL}Enabling_Custom_Repositories_on_Content_Hosts_managing-hosts[Enabling repositories on hosts] in _{ManagingHostsDocTitle}_
* {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in _{ManagingHostsDocTitle}_
* {ContentManagementDocURL}Synchronizing_Repositories_content-management[Synchronizing Repositories] in _{ContentManagementDocTitle}_
endif::[]
