[id="Assigning_a_Host_to_a_Specific_Organization_{context}"]
= Assigning a Host to a Specific Organization

Use this procedure to assign a host to a specific organization.
ifdef::satellite[]
For general information about organizations and how to configure them, see {AdministeringDocURL}Managing_Organizations_admin[Managing Organizations] in _{AdministeringDocTitle}_.
endif::[]
ifndef::satellite[]
For general information about organizations and how to configure them, see {ManagingOrganizationsLocationsDocURL}Managing_Organizations_managing-organizations-locations[Managing Organizations] in _{ManagingOrganizationsLocationsDocTitle}_.
endif::[]

[NOTE]
====
If your host is already registered with a different organization, you must first unregister the host before assigning it to a new organization.
To unregister the host, run `subscription-manager unregister` on the host.
After you assign the host to a new organization, you can re-register the host.
====

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All hosts*.
. Select the checkbox of the host you want to change.
. From the *Select Action* list, select *Assign Organization*.
A new option window opens.
. From the *Select Organization* list, select the organization that you want to assign your host to.
Select the checkbox *Fix Organization on Mismatch*.
+
[NOTE]
====
A mismatch happens if there is a resource associated with a host, such as a domain or subnet, and at the same time not associated with the organization you want to assign the host to.
The option *Fix Organization on Mismatch* will add such a resource to the organization, and is therefore the recommended choice.
The option *Fail on Mismatch* will always result in an error message.
For example, reassigning a host from one organization to another will fail, even if there is no actual mismatch in settings.
====
. Click *Submit*.
