:_mod-docs-content-type: PROCEDURE

[id="Recovering_Corrupted_Content_on_{smart-proxy-context}_{context}"]
= Recovering corrupted content on {SmartProxy}

If the client is unable to consume content from a published repository to which it has a subscription, the content has been corrupted and needs to be repaired.
In case of content corruption on a {SmartProxy}, you can recover it by using the `verify-checksum` command in Hammer CLI.
The `verify-checksum` command can repair content in a content view, lifecycle environment, repository, or all content on {SmartProxy}.
You can track the progress of a command by navigating to *Monitor* > *{Project} Tasks* > *Tasks* and searching for the action *Verify checksum for content on smart proxy*.

.CLI procedure
* To repair content in a content view, run Hammer on your {SmartProxy}:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ {hammer-smart-proxy} content verify-checksum \
--content-view-id _My_Content_View_ID_ \
--id __My_{smart-proxy-context-titlecase}_ID__ \
--organization-id _My_Organization_ID_
----
* To repair content in a lifecycle environment, run Hammer on your {SmartProxy}:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ {hammer-smart-proxy} content verify-checksum \
--id __My_{smart-proxy-context-titlecase}_ID__ \
--lifecycle-environment-id _My_Lifecycle_Environment_ID_ \
--organization-id _My_Organization_ID_
----
* To repair content in a repository, run Hammer on your {SmartProxy}:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ {hammer-smart-proxy} content verify-checksum \
--id __My_{smart-proxy-context-titlecase}_ID__ \
--organization-id _My_Organization_ID_ \
--repository-id _My_Repository_ID_
----
* To repair all content on {SmartProxy}, run the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ {hammer-smart-proxy} content verify-checksum \
--id __My_{smart-proxy-context-titlecase}_ID__
----
