[id="Creating_an_Activation_Key_{context}"]
= Creating an Activation Key

You can use activation keys to define a specific set of subscriptions to attach to hosts during registration.
The subscriptions that you add to an activation key must be available within the associated Content View.

ifndef::orcharhino[]
include::snip_do-not-attach-subscriptions-to-key.adoc[]
endif::[]

Subscription Manager attaches subscriptions differently depending on the following factors:

* Are there any subscriptions associated with the activation key?
* For {RHEL} 8 hosts: Is there system purpose set on the activation key?

Note that {Project} automatically attaches subscriptions only for the products installed on a host.
For subscriptions that do not list products installed on {RHEL} by default, such as the Extended Update Support (EUS) subscription, use an activation key specifying the required subscriptions.

Based on the previous factors, there is one possible scenario for subscribing with activation keys:

* Activation key that attaches subscriptions automatically.
+
With no subscriptions specified, hosts using the activation key search for the best fitting subscription from the ones provided by the Content View associated with the activation key.
For {RHEL} 8 hosts, you can configure the activation key to set system purpose on hosts during registration to enhance the automatic subscriptions attachment.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-an-activation-key_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Lifecycle* > *Activation Keys* and click *Create Activation Key*.
. In the *Name* field, enter the name of the activation key.
. If you want to set a limit, clear the *Unlimited hosts* checkbox, and in the *Limit* field, enter the maximum number of systems you can register with the activation key.
If you want unlimited hosts to register with the activation key, ensure the *Unlimited Hosts* checkbox is selected.
. Optional: In the *Description* field, enter a description for the activation key.
. From the *Environment* list, select the environment to use.
. From the *Content View* list, select a Content View to use.
ifndef::orcharhino[]
. In the *Repository Sets* tab, ensure only your named repository is enabled.
endif::[]
. Click *Save*.
. Optional: For {RHEL} 8 hosts, in the *System Purpose* section, you can configure the activation key with system purpose to set on hosts during registration to enhance subscriptions auto attachment.

[id="cli-creating-an-activation-key_{context}"]
.CLI procedure
. Create the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key create \
--name "_My_Activation_Key_" \
--unlimited-hosts \
--description "_Example Stack in the Development Environment_" \
--lifecycle-environment "_Development_" \
--content-view "_Stack_" \
--organization "_My_Organization_"
----
. Optional: For {RHEL} 8 hosts, enter the following command to configure the activation key with system purpose to set on hosts during registration to enhance subscriptions auto attachment.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key update \
--organization "_My_Organization_" \
--name "_My_Activation_Key_" \
--service-level "_Standard_" \
--purpose-usage "_Development/Test_" \
--purpose-role "_{RHELServer}_" \
--purpose-addons "_addons_"
----
. Obtain a list of your subscription IDs:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer subscription list --organization "_My_Organization_"
----
. Attach the {RHEL} subscription UUID to the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key add-subscription \
--name "_My_Activation_Key_" \
--subscription-id _My_Subscription_ID_ \
--organization "_My_Organization_"
----
. List the product content associated with the activation key:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key product-content \
--content-access-mode-all true \
--name "_My_Activation_Key_" \
--organization "_My_Organization_"
----
+
. Override the default auto-enable status for the {project-client-name} repository.
The default status is set to disabled.
To enable, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer activation-key content-override \
--name "_My_Activation_Key_" \
--content-label {project-client-RHEL7-url} \
--value 1 \
--organization "_My_Organization_"
----
