:_mod-docs-content-type: PROCEDURE

[id="unassign-ansible-roles-from-a-host-by-using-cli"]
= Unassign Ansible roles from a host by using Hammer CLI

[role="_abstract"]
You can unassign Ansible roles from your host by using Hammer CLI.

.Prerequisites
// TODO: Fix list of permissions
* Your {Project} account has a role that grants the `create_ansible_lifecycle_environment_paths`, `edit_ansible_lifecycle_environment_paths`, `view_ansible_content`, `view_ansible_lifecycle_environment_paths`, `view_ansible_lifecycle_environments`, and `view_organizations` permissions.
* You have installed the Hammer CLI plugin for Ansible Director.
For more information, see xref:install-the-hammer-cli-plugin-for-ansible-director[].

.Procedure
. Optional: List all Ansible roles assigned to your host:
+
----
$ hammer
----
. Unassign Ansible roles from your host:
+
----
$ hammer
----

.Verification
. List all Ansible roles assigned to your host:
+
----
$ hammer
----
+
Verify that {Project} unassigned the Ansible roles from your host successfully.
