:_mod-docs-content-type: PROCEDURE

[id="configuring-the-fallback-to-any-{smart-proxy-context}-remote-execution-setting-by-using-cli"]
= Configuring the fallback to any {SmartProxy} remote execution setting by using Hammer CLI

[role="_abstract"]
You can enable the *Fallback to Any {SmartProxy}* setting so that {Project} can use other {SmartProxies} assigned to hosts when no remote execution {SmartProxy} is found for the host subnets.
This is useful for hosts with no subnets or when their subnets use {SmartProxies} without remote execution enabled.

If the *Fallback to Any {SmartProxy}* setting is enabled, {Project} adds another set of {SmartProxies} to select the remote execution {SmartProxy} from.
{Project} also selects the most lightly loaded {SmartProxy} from the set of all {SmartProxies} assigned to the host, such as the following:

* DHCP, DNS and TFTP {SmartProxies} assigned to the host's subnets
* DNS {SmartProxy} assigned to the host's domain
* Realm {SmartProxy} assigned to the host's realm
* OpenVox server {SmartProxy}
* Puppet CA {SmartProxy}
* OpenSCAP {SmartProxy}

.Procedure
* Configure the *Fallback to Any {SmartProxy}* setting:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ hammer settings set \
--name remote_execution_fallback_proxy \
--value true
----
