:_mod-docs-content-type: PROCEDURE

[id="configuring-custom-alternate-contents-sources-by-using-web-ui"]
= Configuring custom alternate content sources by using {ProjectWebUI}

[role="_abstract"]
You can configure custom alternate content sources (ACS) to define alternate paths to download content during synchronization.

.Prerequisites
* If the repository requires SSL authentication, import the SSL certificate and key into {Project}.
For more information, see {ContentManagementDocURL}Importing_Custom_SSL_Certificates_content-management[Importing {customssl} certificates] in _{ContentManagementDocTitle}_.
* Note that the alternate content source paths consist of a base URL appended with the subpaths that you provide.
For example, if your base URL is `\https://{server-example-com}` and your subpaths are `rhel10/` and `rhel9/`, then both `\https://{server-example-com}/rhel10/` and `\https://{server-example-com}/rhel9/` will be searched.

.Procedure
. In the {ProjectWebUI}, navigate to *Content* > *Alternate Content Sources*.
. Click *Add source*.
. Set the *Source type* to *Custom*.
. Select the *Content type* from the drop-down list.
. In the *Name* field, enter a name for the alternate content source.
. Optional: In the the *Description* field, provide a description for the ACS.
. Select {SmartProxies} to which the alternate content source is to be synced.
. In the *Base URL* field, enter the URL of the alternate content source.
. In the *Subpaths* field, provide a comma-separated list of subpaths.
. If your alternate content source requires authentication, provide the *Manual Authentication* or *Content Authentication* credentials.
. If SSL verification is required, enable *Verify SSL* and select the SSL CA certificate.
. Click *Add*.
. Navigate to *Content* > *Alternate Content Sources*.
. Click the vertical ellipsis next to the newly created alternate content source and click *Refresh*.

.Verification
. In the {ProjectWebUI}, navigate to *Monitor* > *{Project} Tasks* > *Tasks*.
. Search for `Refresh Alternate Content Source`.
. Verify that the task finished succesfully.
