:_mod-docs-content-type: PROCEDURE

[id="creating-an-installation-medium-for-ubuntu"]
= Creating an installation medium for Ubuntu

[role="_abstract"]
To provision hosts running Ubuntu, you need to provide both the ISO image and the extracted ISO image on your {ProjectServer}.
This example uses {client-os-example}.

.Procedure
. On your {ProjectServer}, download the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ wget --directory-prefix /tmp/ {client-iso-image-url}
----
. Mount the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mount /tmp/{client-iso-image-file-name} /mnt
----
. Provide the ISO image and the extracted directory under _{foreman-example-com}/pub_:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mkdir --parents /var/www/html/pub/installation_media/ubuntu/{client-iso-image-directory}/
# cp /tmp/{client-iso-image-url} /var/www/html/pub/installation_media/ubuntu/{client-iso-image-name}
# cp --archive /mnt/* /var/www/html/pub/installation_media/ubuntu/{client-iso-image-directory}/
----
+
Ensure the path in `/pub/` matches the path in your _Preseed default PXELinux Autoinstall_ template.
. Unmount and delete the ISO image:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# umount /mnt/
# rm --force /tmp/{client-iso-image-url}
----
+
[TIP]
====
If you manage this with Puppet or a similar configuration management system, you can take an alternative approach.
Instead of copying the ISO image content, you can create a symbolic link at `/var/www/html/pub/installation_media/ubuntu/{client-iso-image-directory}/` that points to the mounted image.
Keep the ISO image mounted so that it is accessible to HTTP clients.

Do not mount the ISO image directly under `/var/lib/foreman/`.
On Ubuntu, mounting under this directory causes the package `postinst` script to fail during the `chmod -Rf /var/lib/foreman` command.
====

.Next steps
* Use `\http://{foreman-example-com}/pub/installation_media/ubuntu/{client-iso-image-directory}/` to set up your installation media entry in {Project}.
For more information, see xref:adding-installation-media-to-{project-context}-by-using-web-ui[].
