[id="configuring-repositories_{context}"]

= Configuring Repositories

Use this procedure to enable the repositories that are required to install {ProductName}. Choose from the available list which operating system and version you are installing on:

ifdef::foreman-el,katello[]
* xref:#repositories-centos-stream-8[CentOS Stream 8]
endif::[]
ifdef::foreman-el,katello,satellite[]
* xref:#repositories-rhel-8[{RHEL} 8]
endif::[]
ifdef::foreman-deb[]
* xref:#repositories-debian-11[Debian 11 (Bullseye)]
* xref:#repositories-ubuntu-2004[Ubuntu 20.04 (Focal)]
endif::[]

ifdef::foreman-el,katello[]
== [[repositories-centos-stream-8]]CentOS Stream 8

:distribution: el
:distribution-major-version: 8
:package-manager: dnf

include::proc_configuring-repositories-el.adoc[]

ifdef::katello[]
+
. Enable `powertools` repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-manager} config-manager --set-enabled powertools
----
endif::[]

+
. Enable the DNF modules:
+
[options="nowrap" subs="+quotes,attributes"]
----
# dnf module enable {dnf-modules}
----

If this fails to enable, see {InstallingServerDocURL}troubleshooting_dnf_modules[DNF module enablement troubleshooting].

endif::[]

ifdef::foreman-el,katello,satellite[]
== [[repositories-rhel-8]]{RHEL} 8

:distribution: rhel
:distribution-major-version: 8
:package-manager: dnf

. Disable all repositories:
+
[options="nowrap"]
----
# subscription-manager repos --disable "*"
----
+

. Enable the following repositories:
+
[options="nowrap" subs="+quotes,attributes"]
ifdef::foreman-el,katello[]
----
# subscription-manager repos --enable={RepoRHEL8BaseOS} \
--enable={RepoRHEL8AppStream}
----
endif::[]
ifdef::satellite[]
----
# subscription-manager repos --enable={RepoRHEL8BaseOS} \
--enable={RepoRHEL8AppStream} \
--enable={RepoRHEL8ServerSatelliteServerProductVersion} \
--enable={RepoRHEL8ServerSatelliteMaintenanceProductVersion}
----
endif::[]
+

ifdef::foreman-el,katello[]
include::proc_configuring-repositories-el.adoc[]
endif::[]

ifdef::foreman-el,katello,satellite[]
. Enable the DNF modules:
+
[options="nowrap" subs="+quotes,verbatim,attributes"]
----
# dnf module enable {dnf-modules}
----
+
[NOTE]
====
include::snip_dnf-module-enable-note.adoc[]
====
endif::[]

[NOTE]
====
If you are installing {ProductName} as a virtual machine hosted on {oVirt}, you must also enable the *Red{nbsp}Hat Common* repository, and install {oVirt} guest agents and drivers.
For more information, see https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.3/html/virtual_machine_management_guide/installing_guest_agents_and_drivers_linux#Installing_the_Guest_Agents_and_Drivers_on_Red_Hat_Enterprise_Linux[Installing the Guest Agents and Drivers on {RHEL}] in the _Virtual Machine Management Guide_.
====
endif::[]

ifdef::foreman-deb[]
== [[repositories-debian-11]]Debian 11 (Bullseye)

:distribution-codename: bullseye
include::proc_configuring-repositories-deb.adoc[]

== [[repositories-ubuntu-2004]]Ubuntu 20.04 (Focal)

:distribution-codename: focal
include::proc_configuring-repositories-deb.adoc[]

endif::[]
