[id="Creating_a_User_{context}"]
= Creating a User

Use this procedure to create a user.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-creating-a-user_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Users*.
. Click *Create User*.
. In the *Login* field, enter a username for the user.
. In the *Firstname* and *Lastname* fields, enter the real first name and last name of the user.
. In the *Mail* field, enter the user’s email address.
. In the *Description* field, add a description of the new user.
. Select a specific language for the user from the *Language* list.
. Select a timezone for the user from the *Timezone* list.
+
By default, {ProjectServer} uses the language and timezone settings of the user’s browser.
. Set a password for the user:
.. From the *Authorized by* list, select the source by which the user is authenticated.
** *INTERNAL*: to enable the user to be managed inside {ProjectServer}.
** *EXTERNAL*: to configure external authentication as described in {InstallingServerDocURL}Configuring_External_Authentication_{project-context}[Configuring external authentication] in _{InstallingServerDocTitle}_.
.. Enter an initial password for the user in the *Password* field and the *Verify* field.
. Click *Submit* to create the user.

[id="cli-creating-a-user_{context}"]
.CLI procedure
* To create a user, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer user create \
--auth-source-id _My_Authentication_Source_ \
--login _My_User_Name_ \
--mail _My_User_Mail_ \
--organization-ids _My_Organization_ID_1_,_My_Organization_ID_2_ \
--password _My_User_Password_
----
+
The `--auth-source-id 1` setting means that the user is authenticated internally, you can specify an external authentication source as an alternative.
Add the `--admin` option to grant administrator privileges to the user.
Specifying organization IDs is not required, you can modify the user details later using the `update` subcommand.

For more information about user related subcommands, enter `hammer user --help`.
