[id="Applying_Errata_to_a_Host_{context}"]
= Applying Errata to a Host

Use these procedures to review and apply errata to a host.

.Prerequisites
ifdef::satellite[]
* Synchronize {ProjectName} repositories with the latest errata available from Red{nbsp}Hat.
For more information, see xref:Synchronizing_Repositories_{context}[].
endif::[]
* Register the host to an environment and Content View on {ProjectServer}.
For more information, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in the _Managing Hosts_ guide.
* Configure the host for remote execution.
For more information about running remote execution jobs, see {ManagingHostsDocURL}Configuring_and_Setting_Up_Remote_Jobs_managing-hosts[Configuring and Setting Up Remote Jobs] in the _Managing Hosts_ guide.

[NOTE]
====
If the host is already configured to receive content updates with the deprecated Katello Agent, migrate to remote execution instead.
For more information, see {ManagingHostsDocURL}Migrating_From_Katello_Agent_to_Remote_Execution_managing-hosts[Migrating From Katello Agent to Remote Execution] in the _Managing Hosts_ guide.
====

The procedure to apply an erratum to a managed host depends on its operating system.
