:_mod-docs-content-type: PROCEDURE

[id="applying-a-predefined-tuning-profile"]
= Applying a predefined tuning profile

[role="_abstract"]
Run `{foreman-installer}` with the `--tuning` option to apply a profile.
Choosing the right tuning profile helps your {ProjectServer} use its CPU cores and memory better.

[NOTE]
====
You cannot use predefined tuning profiles on {SmartProxyServers}.
====

.Procedure
. If you use a `custom-hiera.yaml` file on your {ProjectServer}, perform the following steps:
.. Optional: Back up your `custom-hiera.yaml` file:
+
----
# cp /etc/foreman-installer/custom-hiera.yaml \
/etc/foreman-installer/custom-hiera.original.yaml
----
+
This ensures you can restore the `custom-hiera.yaml` file to its original state if it becomes corrupted.
.. Review the definitions of the base tuning profile in `/usr/share/foreman-installer/config/foreman.hiera/tuning/common.yaml` and the tuning profile that you want to apply in `/usr/share/foreman-installer/config/foreman.hiera/tuning/sizes/`.
.. Compare the configuration entries against the entries in your `/etc/foreman-installer/custom-hiera.yaml` file.
.. Remove any duplicated configuration settings that you find in `custom-hiera.yaml`.
This ensures the settings in `custom-hiera.yaml` do not override the settings in the base tuning profile and your chosen predefined tuning profile.
. Apply the tuning profile:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-installer} --tuning _medium_
----
