:_mod-docs-content-type: PROCEDURE

[id="configuring-{project-context}-with-an-alternate-cname_{context}"]
= Configuring {Project} with an alternate CNAME

[role="_abstract"]
You can configure an alternate CNAME for {Project} with the default {Project} certificate.
Note that the procedures for users of a default {Project} certificate and custom certificate differ.

.Procedure
ifdef::foremanctl[]
. Add an alternate CNAME to a new installation or an existing deployment of {Project} with a default {Project} certificate:
[options="nowrap" subs="+quotes,attributes"]
----
# {foremanctl-installer} --certificate-cname _My_alternate-{foreman-example-com}_
----
endif::[]
ifndef::foremanctl[]
. If you have installed {Project} with a default {Project} certificate and want to configure {Project} with an alternate CNAME, generate a new default {Project} SSL certificate with an additional CNAME on {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --certs-cname _My_alternate-{foreman-example-com}_ --certs-update-server
----
. If you have not installed {Project}, you can add the `--certs-cname _My_alternate-{foreman-example-com}_` option to the `{foreman-installer}` command to install {Project} with an alternate CNAME.
endif::[]
. If you use {Project} with a custom certificate, when creating a custom certificate, include the alternate CNAME records to the custom certificate.
For more information, see {InstallingServerDocURL}creating-a-custom-ssl-certificate_{project-context}[Creating a Custom SSL Certificate for {ProjectServer}].
ifdef::foremanctl[]
+
[NOTE]
====
You can remove all CNAMEs from an existing certificate by using the `{foremanctl-installer} --reset-certificate-cname` command.
====
endif::[]
