[id="editing-a-resource-quota"]
= Editing a resource quota

You can edit a resource quota to adjust available resources to {Project} users.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-editing-a-resource-quota[].

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Resource Quotas*.
. Select your resource quota.
. Adjust the *CPU cores*, *Memory*, or *Disk space* and click *Apply* to submit your changes to {Project}.
. Click *Create resource quota* to submit the resource quota to {Project}.

[id="cli-editing-a-resource-quota"]
.CLI procedure
. Optional: List all resource quotas:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ hammer resource-quota list --fields id,name
----
. Edit a resource quota:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
$ hammer resource-quota update \
--cpu-cores _My_CPU_Cores_ \
--description _My_Resource_Quota_Description_ \
--disk-space _My_Disk_Space_in_GiB_ \
--id _My_Resource_Quota_ID_ \
--memory _My_Memory_in_MiB_ \
--name "_My_Resource_Quota_Name_"
----
+
If you set the value to `0`, users cannot consume any resource at all.
To reset resource quotas, you can use `--remove-cpu-cores-limit`, `--remove-disk-space-limit`, and `--remove-memory-limit`.
+
For all options, see `hammer resource-quota update --help`.
