[id="Adding_a_Subnet_to_Server_{context}"]
= Adding a Subnet to {ProjectServer}

You must add information for each of your subnets to {ProjectServer} because {Project} configures interfaces for new hosts.
To configure interfaces, {ProjectServer} must have all the information about the network that connects these interfaces.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-a-subnet_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure*{nbsp}>{nbsp}*Subnets*, and in the Subnets window, click *Create Subnet*.
. In the *Name* field, enter a name for the subnet.
. In the *Description* field, enter a description for the subnet.
. In the *Network address* field, enter the network address for the subnet.
. In the *Network prefix* field, enter the network prefix for the subnet.
. In the *Network mask* field, enter the network mask for the subnet.
. In the *Gateway address* field, enter the external gateway for the subnet.
. In the *Primary DNS server* field, enter a primary DNS for the subnet.
. In the *Secondary DNS server*, enter a secondary DNS for the subnet.
. From the *IPAM* list, select the method that you want to use for IP address management (IPAM).
For more information about IPAM, see xref:Configuring_Networking_{context}[].
+
. Enter the information for the IPAM method that you select.
ifdef::satellite[]
Click the *Remote Execution* tab and select the {SmartProxy} that controls the remote execution.
endif::[]
ifndef::satellite[]
. If you use the remote execution plugin, click the *Remote Execution* tab and select the {SmartProxy} that controls the remote execution.
endif::[]
. Click the *Domains* tab and select the domains that apply to this subnet.
. Click the *{SmartProxies}* tab and select the {SmartProxy} that applies to each service in the subnet, including DHCP, TFTP, and reverse DNS services.
. Click the *Parameters* tab and configure any subnet level parameters to apply to hosts attached to this subnet.
For example, user defined Boolean or string parameters to use in templates.
. Click the *Locations* tab and select the locations that use this {SmartProxy}.
. Click the *Organizations* tab and select the organizations that use this {SmartProxy}.
. Click *Submit* to save the subnet information.

[id="cli-adding-a-subnet_{context}"]
.CLI procedure
* Create the subnet with the following command:
+
[options="nowrap" subs="+quotes"]
----
# hammer subnet create \
--boot-mode "DHCP" \
--description "_My_Description_" \
--dhcp-id _My_DHCP_ID_ \
--dns-id _My_DNS_ID_ \
--dns-primary "192.168.140.2" \
--dns-secondary "8.8.8.8" \
--domains "_my-domain.tld" \
--from "192.168.140.111" \
--gateway "192.168.140.1" \
--ipam "DHCP" \
--locations "_My_Location_" \
--mask "255.255.255.0" \
--name "_My_Network_" \
--network "192.168.140.0" \
--organizations "_My_Organization_"
--tftp-id _My_TFTP_ID_ \
--to "192.168.140.250" \
----

[NOTE]
====
In this example, the `--dhcp-id`, `--dns-id`, and `--tftp-id` options use 1, which is the ID of the integrated {SmartProxy} in {ProjectServer}.
====
