[id="Republishing_Repository_and_Content_View-Metadata_{context}"]
= Republishing Repository and Content View Metadata

Republishing repository metadata is used when a repository distribution does not have the content that should be distributed based on the contents of the repository.

Use this procedure with caution.
In most cases, {Team} recommends a complete repository sync or publishing a new Content View version.

.Procedure

. In the {ProjectWebUI}, navigate to *Content* > *Products*.
. Select the product that includes the repository for which you want to republish metadata.
. Navigate to the repository where you want to republish metadata.
. To republish metadata for the repository, select *Republish Repository Metadata* from the *Select Action* menu.
+
[NOTE]
====
This action is not available for repositories that implement the *Complete Mirroring* policy since the metadata is copied from the repository's upstream source instead of being generated locally.
====

To republish Content View metadata:

. In the {ProjectWebUI}, navigate to *Content View* > *Versions* tab >.
. Select the Content View version metadata you want to republish, click the vertical ellipsis icon, and click *Republish repository metadata*.

Republishing repository metadata will regenerate metadata for all repositories in the Content View version that do not adhere to the *Complete Mirroring* policy.
