[id="Using_an_NFS_Share_for_Content_Storage_{context}"]
= Using an NFS Share for Content Storage

Your environment requires adequate hard disk space to fulfill content storage.
In some situations, it is useful to use an NFS share to store this content.
This appendix shows how to mount the NFS share on your {ProjectServer}'s content management component.

[IMPORTANT]
Use high-bandwidth, low-latency storage for the `/var/lib/pulp` file system.
{ProjectName} has many I/O-intensive operations; therefore, high-latency, low-bandwidth storage might have issues with performance degradation.

.Procedure
. Create the NFS share.
This example uses a share at `nfs.example.com:/{Project}/pulp`.
Ensure this share provides the appropriate permissions to {ProjectServer} and its `apache` user.
. Stop {Project} services on your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service stop
----
. Ensure {ProjectServer} has the `nfs-utils` package installed:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} nfs-utils
----
. You need to copy the existing contents of `/var/lib/pulp` to the NFS share.
First, mount the NFS share to a temporary location:
+
----
# mkdir /mnt/temp
# mount -o rw nfs.example.com:/{Project}/pulp /mnt/temp
----
+
Copy the existing contents of `/var/lib/pulp` to the temporary location:
+
----
# cp -r /var/lib/pulp/* /mnt/temp/.
----
. Set the permissions for all files on the share to use the `pulp` user.
. Unmount the temporary storage location:
+
----
# umount /mnt/temp
----
. Remove the existing contents of `/var/lib/pulp`:
+
----
# rm -rf /var/lib/pulp/*
----
. Edit the `/etc/fstab` file and add the following line:
+
----
nfs.example.com:/{Project}/pulp    /var/lib/pulp   nfs    rw,hard,intr,context="system_u:object_r:pulpcore_var_lib_t:s0"
----
+
This makes the mount persistent across system reboots.
Ensure to include the SELinux context.
. Enable the mount:
+
----
# mount -a
----
. Confirm the NFS share mounts to `var/lib/pulp`:
+
----
# df
Filesystem                         1K-blocks     Used Available Use% Mounted on
...
nfs.example.com:/{Project}/pulp 309506048 58632800 235128224  20% /var/lib/pulp
...
----
+
Also confirm that the existing content exists at the mount on `var/lib/pulp`:
+
----
# ls /var/lib/pulp
----
. Start {Project} services on your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service start
----

{ProjectServer} now uses the NFS share to store content.
Run a content synchronization to ensure the NFS share works as expected.
For more information, see xref:Synchronizing_Repositories_{context}[].
