[id='configuring-hosts-to-use-an-alternate-cname-for-content-management_{context}']
= Configuring Hosts to Use an Alternate {Project} CNAME for Content Management

If {Project} is configured with an alternate CNAME, you can configure hosts to use the alternate {Project} CNAME for content management. To do this, you must point hosts to the alternate {Project} CNAME prior to registering the hosts to {Project}. You can do this using the bootstrap script or manually.

.Configuring Hosts with the bootstrap Script

On the host, run the bootstrap script with the `--server _alternate_fqdn.example.com_` option to register the host to the alternate {Project} CNAME:

[options="nowrap" subs="+quotes,attributes"]
----
# ./bootstrap.py --server _alternate_fqdn.example.com_
----

.Configuring Hosts Manually

On the host, edit the `/etc/rhsm/rhsm.conf` file to update `hostname` and `baseurl` settings to point to the alternate host name, for example:

[options="nowrap" subs="+quotes,attributes"]
----
[server]
# Server hostname:
hostname = _alternate_fqdn.example.com_

_content omitted_

[rhsm]
# Content base URL:
baseurl=https://_alternate_fqdn.example.com_/pulp/repos
----

Now you can register the host with the `subscription-manager`.
