[id="Exporting_the_Library_Environment_in_a_Syncable_Format_{context}"]
= Exporting the Library Environment in a Syncable Format

You can export contents of all yum repositories, Kickstart repositories and file repositories in the Library environment of an organization to a syncable format that you can use to create your custom CDN and synchronize the content from the custom CDN over HTTP/HTTPS.

ifdef::satellite[]
You can then serve the generated content on a local web server and synchronize it on the importing {ProjectServer} or in another {ProjectServer} organization.
endif::[]

You can use the generated content to create the same repository in another {ProjectServer} or in another {ProjectServer} organization by using content import.
On import of the exported archive, a regular content view is created or updated on your importing {ProjectServer}.
For more information, see xref:Importing_a_Content_View_Version_{context}[].

You can export the following content in the syncable format from {ProjectServer}:

* Yum repositories
* Kickstart repositories
* File repositories

You cannot export Ansible, Deb, or Docker content.

The export contains directories with the packages, *listing* files, and metadata of the repository in Yum format that can be used to synchronize in the importing {ProjectServer}.

.Prerequisites
* Ensure that you set the download policy to *Immediate* for all repositories within the Library lifecycle environment you export.
For more information, see xref:Download_Policies_Overview_{context}[].
* Ensure that you synchronize products you export to the required date.
* Ensure that the user exporting the content has the `Content Exporter` role.

.Procedure
. Use the organization name or ID to export:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-export complete library \
--organization="_My_Organization_" \
--format=syncable
----
. Optional: Verify that the exported content is located in the export directory:
+
[options="nowrap" subs="+quotes"]
----
# du -sh /var/lib/pulp/exports/_My_Organization_/Export-_My_Repository_/1.0/2021-03-02T03-35-24-00-00
----
