:_mod-docs-content-type: PROCEDURE

[id="connecting-the-mcp-client-to-the-mcp-server"]
= Connecting the MCP client to the MCP server

[role="_abstract"]
Connect your Model Context Protocol (MCP) client to the MCP server so that your AI application can obtain data about your {Project} inventory.

In this scenario, your MCP client runs on the same system where you deployed the MCP server.

.Prerequisites
* Your MCP client must support setting custom HTTP headers.

.Procedure
. Generate a personal access token (PAT) that the MCP client will use to connect to the MCP server:
.. In the {ProjectWebUI}, click the user menu in the top bar and select *My Account*.
.. Select the *Personal Access Tokens* tab.
.. Click *Add Personal Access Token*.
+
[IMPORTANT]
====
{Team} recommends to set an expiration date for a PAT used to configure the MCP client.
====
. Configure your client to pass credentials in an HTTP authorization request header.
The exact configuration steps depend on your MCP client.
+
For example, some clients require you to create a configuration file with the following contents:
+
[options="nowrap", subs="+quotes,attributes"]
----
"my-mcp-server": {
	"url": "http://localhost:8080/mcp/sse",
	"type": "http",
	"headers": {
		"FOREMAN_USERNAME": "_My_Username_",
		"FOREMAN_TOKEN": "_My_PAT_"
	}
}
----

.Additional resources
* {APIDocURL}creating-a-personal-access-token_rest-api[Creating a Personal Access Token in _{APIDocTitle}_]
