:_mod-docs-content-type: PROCEDURE

[id="creating-a-granular-permission-filter-by-using-web-ui"]
= Creating a granular permission filter by using {ProjectWebUI}

[role="_abstract"]
Use this procedure to create a granular permission filter from the {ProjectWebUI}.

{Project} does not apply search conditions to create actions.
For example, limiting the _create_locations_ action with _name = "Default Location"_ expression in the search field does not prevent the user from assigning a custom name to the newly created location.

.Procedure
. Specify a query in the *Search* field on the *Edit Filter* page.
Queries have the following form:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
_field_name_ _operator_ _value_
----

* _field_name_ marks the field to be queried.
The range of available field names depends on the resource type.
For example, the _Partition Table_ resource type offers _family_, _layout_, and _name_ as query parameters.

* _operator_ specifies the type of comparison between _field_name_ and _value_.
See xref:Supported_Operators_for_Granular_Search_{context}[] for an overview of applicable operators.

* _value_ is the value used for filtering.
This can be for example a name of an organization.
Two types of wildcard characters are supported: underscore (_) provides single character replacement, while percent sign (%) replaces zero or more characters.
+
[NOTE]
====
For most resource types, the *Search* field provides a drop-down list suggesting the available parameters.
This list appears after placing the cursor in the search field.
For many resource types, you can combine queries using logical operators such as _and_, _not_ and _has_ operators.
====
