:_mod-docs-content-type: PROCEDURE

[id="change-an-ansible-execution-environment-by-using-web-ui"]
= Change an Ansible Execution Environment by using {ProjectWebUI}

[role="_abstract"]
You can change an Ansible Execution Environment in {Project} by using {ProjectWebUI}.
You can change the name, base container image, or version of `ansible-core`.

.Prerequisites
* Your {Project} account has a role that grants the `create_ansible_execution_environments`, `edit_ansible_execution_environments`, `view_ansible_content`, `view_ansible_execution_environments`, and `view_organizations` permissions.

.Procedure
. In the {ProjectWebUI}, navigate to *Ansible* > *Execution Environments*.
. For your Ansible Execution Environment, click the *Edit* icon.
+
You can rename the Ansible Execution Environment, rebuild it based on another container image, or include a different version of Ansible.
. Click the *Save* icon to change your Ansible Execution Environment.

.Verification
. In the {ProjectWebUI}, navigate to *Ansible* > *Execution Environments*.
. For your Ansible Execution Environments, verify that the build status icon is green.

.Additional resources
* xref:build-an-ansible-execution-environment-by-using-web-ui[]
