[id="enabling-connections-from-capsule-to-satellite_{context}"]
= Enabling Connections from {SmartProxyServer} to {ProjectServer}

On {ProjectServer}, you must enable the incoming connection from {SmartProxyServer} to {ProjectServer} and make this rule persistent across reboots.

.Prerequisites

* Ensure that the firewall rules on {ProjectServer} are configured to enable connections for client to {Project} communication, because {SmartProxyServer} is a client of {ProjectServer}. For more information, see {InstallingProjectDocURL}preparing-environment-for-satellite-installation#enabling-client-connections-to-satellite_satellite[Enabling Connections from a Client to {ProjectServer}] in _{project-installation-guide-title}_.

.Procedure

include::snip_firewalld.adoc[]

. On {ProjectServer}, enter the following command to open the port for {SmartProxy} to {Project} communication:
+
[options="nowrap"]
----
# firewall-cmd --add-port="5646/tcp"
----

. Make the changes persistent:
+
----
# firewall-cmd --runtime-to-permanent
----
