[id="Using_{FreeIPA-context}_credentials_to_log_in_to_the_{ProjectWebUI-context}-with-Mozilla-Firefox_{context}"]
= Logging in to the {ProjectWebUI} with {FreeIPA} credentials in Mozilla Firefox

You can use Mozilla Firefox to log in to the {ProjectWebUI} with your {FreeIPA} credentials.

Use the latest stable Mozilla Firefox browser.

.Prerequisites
* You have {FreeIPA} authentication configured in your {Project} environment.
ifndef::orcharhino[]
For more information, see {InstallingServerDocURL}configuring-a-freeipa-server-as-an-external-identity-provider-for-project_{project-context}[{InstallingServerDocTitle}].
endif::[]
* Your Mozilla Firefox is configured for Single Sign-On (SSO).
ifdef::satellite[]
For more information, see {RHELDocsBaseURL}9/html/configuring_authentication_and_authorization_in_rhel/configuring_applications_for_sso#Configuring_Firefox_to_use_Kerberos_for_SSO[Configuring Firefox to use Kerberos for single sign-on] in _Configuring authentication and authorization in {RHEL}{nbsp}9_.
endif::[]

.Procedure
. Obtain the Kerberos ticket granting ticket (TGT):
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
$ kinit _user_
Password for user@EXAMPLE.COM:
----
. In Mozilla Firefox, go to the URL of your {ProjectServer}.
. You are logged in automatically.

Alternatively:

. In your browser address bar, enter the URL of your {ProjectServer}.
. Enter your login and password.
