:_mod-docs-content-type: PROCEDURE

[id="Deploying_a_Policy_in_a_Host_Group_Using_Ansible_{context}"]
= Deploying a policy in a host group using Ansible

[role="_abstract"]
After you deploy a compliance policy in a host group using Ansible, the Ansible role installs the SCAP client and configures OpenSCAP scans on the hosts according to the selected compliance policy.

The SCAP content in the compliance policy might require remote resources.
For more information, see xref:inclusion-of-remote-scap-resources_{context}[].

.Prerequisites
* You have enabled OpenSCAP on your {SmartProxy}.
For more information, see xref:enabling-openscap[].
ifdef::foreman-el,foreman-deb[]
* Ensure that a repository that provides the `openscap-scanner` package and its dependencies is enabled on the host.
endif::[]
ifndef::foreman-el,foreman-deb[]
* Repositories for the operating system version of the host are synchronized on {ProjectServer} and enabled on the host.
ifdef::client-content-dnf[]
ifndef::satellite[]
For example, for {EL} you might require:
endif::[]
** {EL} 10 BaseOS and AppStream RPMs repositories
** {EL} 9 BaseOS and AppStream RPMs repositories
** {EL} 8 BaseOS and AppStream RPMs repositories
** {EL} 7 Server and Extras RPMs repositories
endif::[]
endif::[]
ifndef::client-content-dnf[]
You might require:
** For Ubuntu 24.04 "Noble": Suite `noble` and components `main universe`
** For Debian 12 "Bookworm": Suite `bookworm` and component `main`
endif::[]
ifndef::satellite[]

+
You need repositories that provide the `openscap-scanner` package and its dependencies.
endif::[]
ifdef::foreman-el[]
* {project-client-name} repository is available on the host.
endif::[]
ifndef::foreman-el[]
* {project-client-name} repository for the operating system version of the host is synchronized on {ProjectServer}, available in the content view and the lifecycle environment of the host, and enabled for the host.
ifndef::orcharhino[]
For more information, see {ContentManagementDocURL}Changing_the_Repository_Sets_Status_for-a-Host-in_{project-context}_content-management[Changing the repository sets status for a host in {Project}] in _{ContentManagementDocTitle}_.
endif::[]
endif::[]
This repository is required for installing the SCAP client.
* You have xref:Creating_a_Compliance_Policy_{context}[created a compliance policy] with the Ansible deployment option and assigned the host group.

.Procedure
. In the {ProjectWebUI}, navigate to *Configure* > *Host Groups*.
. Click the host group that you want to configure for OpenSCAP reporting.
. From the *OpenSCAP {SmartProxy}* list, select the {SmartProxy} with OpenSCAP enabled that you want to use.
. On the *Ansible Roles* tab, assign the `theforeman.foreman_scap_client` Ansible role.
. Optional: On the *Parameters* tab, configure any Ansible variables of the role.
. Click *Submit* to save your changes.
. In the row of the required host group, navigate to the *Actions* column and select *Run all Ansible roles*.
