:_mod-docs-content-type: PROCEDURE

[id="using-an-upstream-{project-context}-server-as-a-content-store"]
= Using an upstream {ProjectServer} as a content store

[role="_abstract"]
Export Library content from an upstream {ProjectServer} that serves as a content store and import it on the downstream server that manages content for isolated infrastructure.

.Procedure
. On the upstream {ProjectServer}, perform the following steps:
.. Ensure that repositories are using the *Immediate* download policy in one of the following ways:
... For existing repositories using *On Demand*, change their download policy on the repository details page to *Immediate*.
ifdef::katello,satellite,red_hat_enterprise_linux[]
... For new repositories, ensure that the *Default Red Hat Repository download policy* setting is set to *Immediate* before enabling Red{nbsp}Hat repositories, and that the *Default download policy* is set to *Immediate* for custom repositories.
endif::[]
ifdef::almalinux,amazon_linux,centos,debian,oracle_linux,rocky_linux,suse_linux_enterprise_server,ubuntu[]
... Ensure that the *Default download policy* is set to *Immediate* for custom repositories.
endif::[]
.. Enable the content that you want to synchronize.
+
If you want to sync custom content, first create a {customproduct} and then synchronize repositories.
.. Synchronize the enabled content:
... On the first export, perform a `complete` Library export so that all the synchronized content is exported.
This generates content archives that you can later import into one or more downstream {ProjectServer}s.
... Export all future updates on the upstream {ProjectServer} incrementally.
This generates leaner content archives that contain only a recent set of updates.
For example, if you enable and synchronize a new repository, the next exported content archive contains content only from the newly enabled repository.
. On the downstream {ProjectServer}, perform the following steps:
.. Bring the content exported from the upstream {ProjectServer} over to the hard disk.
.. Place it inside a directory under `/var/lib/pulp/imports/`.
.. Import the content to an organization.
+
You can then manage content using content views or lifecycle environments as you require.

.Additional resources
ifdef::katello,satellite,red_hat_enterprise_linux[]
* xref:enabling-red-hat-repositories-by-using-web-ui[]
endif::[]
* xref:Download_Policies_Overview_{context}[]
* xref:creating-a-custom-product-by-using-web-ui[]
* xref:synchronizing-repositories-ad-hoc[]
* xref:Exporting_the_Library_Environment_{context}[]
* xref:exporting-the-library-environment-incrementally_{context}[]
* xref:Importing_into_the_Library_Environment_{context}[]
