:_mod-docs-content-type: PROCEDURE

[id="registering-a-host-to-{project-context}-by-using-cli_{context}"]
= Registering a host to {Project} by using Hammer CLI

[role="_abstract"]
You can register hosts with {Project} using the host registration feature in Hammer CLI.
For more information, see {ManagingHostsDocURL}registering-hosts-and-setting-up-host-integration_managing-hosts[Registering hosts and setting up host integration] in _{ManagingHostsDocTitle}_.

.Procedure
. Generate the host registration command:
+
ifndef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command \
--insecure true
----
endif::[]
ifdef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command \
--activation-keys "_My_Activation_Key_"
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer host-registration generate-command \
--activation-keys "_My_Activation_Key_" \
--insecure true
----
endif::[]
. Connect to your host using SSH and run the registration command.
ifdef::satellite[]
. Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifndef::satellite[]
. Ensure that the appropriate repositories have been enabled:
+
ifdef::client-content-dnf[]
* On {EL}: Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifdef::client-content-apt[]
* On Debian: Check the `/etc/apt/sources.list` file and ensure that the appropriate repositories have been enabled.
endif::[]
endif::[]
