[id="Benchmarking_Disk_Performance_{context}"]
= Benchmarking Disk Performance

We are working to update `{foreman-maintain}` to only warn the users when its internal quick storage benchmark results in numbers below our recommended throughput.

Also working on an updated benchmark script you can run (which will likely be integrated into `{foreman-maintain}` in the future) to get a more accurate real-world storage information.

[NOTE]
====
* One may have to temporarily reduce the RAM in order to run the I/O benchmark.
For example if the host has 256 GB RAM, test would require 512 GB of storage to run.
So as a workaround, you can add `mem=20G` kernel option in grub during system boot to temporary reduce size of system RAM.
The benchmark will create a very large file that is double (2x) the size of the RAM in specified directory and execute a series of storage I/O tests against it.
The size of the file ensures that the test is not just testing the filesystem caching.
* Please bear above in mind when performing benchmark of other filesystems.
For example if you plan to test on smaller volumes (typically PostgreSQL storage), you might need to reduce RAM size as described above.
* If you are using different storage solutions (SAN, iSCSI, and so on), they might be giving different performance.
* We recommend you to stop all services before executing this script and you will be prompoted to do so.
====

This test does not use direct I/O and will utilize file caching as normal operations would.

// Would it make sense to package this script for Foreman?
You can find our first version of the script https://github.com/RedHatSatellite/satellite-support/blob/master/storage-benchmark[storage-benchmark].
To execute it, just download the script to your {Project}, make it executable, and run:

[options="nowrap" subs="+quotes,attributes"]
----
# ./storage-benchmark /var/lib/pulp
----

As noted in the README block in the script, generally you wish to see on average 100MB/sec or higher in the tests below:

* Local SSD based storage should give values of 600MB/sec or higher.
* Spinning disks should give values in the range of 100-200MB/sec or higher.

If you see values below this, please open a support ticket for assistance.

ifdef::satellite[]
For more information, see https://access.redhat.com/solutions/3397771[Impact of Disk Speed on Satellite Operations].
endif::[]
