[id="Customizing_the_Discovery_PXE_Boot_{context}"]
= Customizing the Discovery PXE boot
[[Discovery_Templates_and_Snippets_Settings_{context}]]
[[Provisioning_Template_PXELinux_Discovery_Snippet_{context}]]

{Project} builds PXE boot menus from the global provisioning templates: `PXELinux global default` for BIOS provisioning, `PXEGrub global default`, and `PXEGrub2 global default` for UEFI provisioning.
The PXE boot menus are available on {ProjectServer} and all {SmartProxies} that have the TFTP feature enabled.

The Discovery menu item uses a Linux kernel for the operating system, which passes kernel parameters to configure the Discovery service.
You can customize the passed kernel parameters by changing the following snippets:

Snippet `pxelinux_discovery`:: This snippet is included in the `PXELinux global default` template.
+
The `KERNEL` and `APPEND` options boot the Discovery kernel and initial ramdisk.
The `APPEND` option contains a further kernel parameters.

Snippet `pxegrub_discovery`:: This snippet is included in the `PXEGrub global default` template.
However, Discovery is http://projects.theforeman.org/issues/15997[not supported with GRUB 1.x].

Snippet `pxegrub2_discovery`:: This snippet is included in the `PXEGrub2 global default` template.

To view provisioning templates and snippets, navigate to *Hosts* > *Templates* > *Provisioning Templates*.
Templates and snippets are locked to prevent changes.
If you want to edit a template or snippet, clone it, save it with a unique name, and then edit the clone.
For information about the kernel parameters, see xref:kernel-parameters-for-discovery-customization_{context}[].

.Discovering hosts from multiple {SmartProxies}
{Project} deploys the same template to all TFTP {SmartProxies} and there is no variable or macro available to render the {SmartProxy}'s host name.
The hard-coded `proxy.url` does not not work with two or more TFTP {SmartProxies}.
As a workaround, every time you click *Build PXE Defaults*, edit the configuration file in the TFTP directory using SSH, or use a common DNS alias for appropriate subnets.
To use {SmartProxy} to proxy the discovery steps, edit `/var/lib/tftpboot/pxelinux.cfg/default` or `/var/lib/tftpboot/grub2/grub.cfg` and change the URL to {SmartProxyServer} FQDN you want to use.

.Procedure
. Clone and edit snippet.
. Clone and edit template.
Include your snippet instead of the original one.
. Set your custom template in global settings.
In the {ProjectWebUI}, navigate to *Administer* > *Settings* and click the *Provisioning* tab and set the templates that you want to use.
. Build PXE default.
In the {ProjectWebUI}, navigate to *Hosts* > *Templates* > *Provisioning Templates* and click *Build PXE Default*.
This refreshes the default PXE boot menus on {ProjectServer} and any TFTP {SmartProxies}.
