[id="Inspecting_Available_Errata_{context}"]
= Inspecting Available Errata

The following procedure describes how to view and filter the available errata and how to display metadata of the selected advisory.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-inspecting-available-errata[].

.Procedure
. Navigate to *Content* > *Errata* to view the list of available errata.
. Use the filtering tools at the top of the page to limit the number of displayed errata:
+
* Select the repository to be inspected from the list.
*All Repositories* is selected by default.
* The *Applicable* check box is selected by default to view only errata applicable to the selected repository.
Select the *Installable* check box to view only errata marked as installable.
* To search the table of errata, type the query in the *Search* field in the form of:
+
[subs="+quotes"]
----
__parameter operator value__
----
+
See xref:tabl-Parameters_Available_for_Errata_Search[] for the list of parameters available for search.
Find the list of applicable operators in {AdministeringDocURL}supported-operators-for-granular-search_admin[Supported Operators for Granular Search] in _Administering {ProjectName}_.
Automatic suggestion works as you type.
You can also combine queries with the use of *and* and *or* operators.
For example, to display only security advisories related to the *kernel* package, type:
+
----
type = security and package_name = kernel
----
+
Press *Enter* to start the search.
. Click the *Errata ID* of the erratum you want to inspect:
+
* The *Details* tab contains the description of the updated package as well as documentation of important fixes and enhancements provided by the update.
* On the *Content Hosts* tab, you can apply the erratum to selected content hosts as described in xref:Applying_Errata_to_Multiple_Hosts[].
* The *Repositories* tab lists repositories that already contain the erratum.
You can filter repositories by the environment and Content View, and search for them by the repository name.

[id="cli-inspecting-available-errata"]
.CLI procedure
* To view errata that are available for all organizations, enter the following command:
+
[options="nowrap" subs="verbatim,quotes"]
----
# hammer erratum list
----
* To view details of a specific erratum, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
# hammer erratum info --id _erratum_ID_
----
* You can search errata by entering the query with the `--search` option.
For example, to view applicable errata for the selected product that contains the specified bugs ordered so that the security errata are displayed on top, enter the following command:
+
[options="nowrap" subs="verbatim,quotes"]
----
# hammer erratum list \
--product-id 7 \
--search "bug = 1213000 or bug = 1207972" \
--errata-restrict-applicable 1 \
--order "type desc"
----

[[tabl-Parameters_Available_for_Errata_Search]]
.Parameters Available for Errata Search
[options="header"]
|====
|Parameter|Description|Example
|bug|Search by the Bugzilla number.|_bug = 1172165_
|cve|Search by the CVE number.|_cve = CVE-2015-0235_
|id|Search by the errata ID.
The auto-suggest system displays a list of available IDs as you type.|_id = RHBA-2014:2004_
|issued|Search by the issue date.
You can specify the exact date, like "Feb16,2015", or use keywords, for example "Yesterday", or "1 hour ago".
The time range can be specified with the use of the "<" and ">" operators.|_issued < "Jan 12,2015"_
|package|Search by the full package build name.
The auto-suggest system displays a list of available packages as you type.|_package = glib2-2.22.5-6.el6.i686_
|package_name|Search by the package name.
The auto-suggest system displays a list of available packages as you type.|_package_name = glib2_
|severity|Search by the severity of the issue fixed by the security update.
Specify _Critical_, _Important_, or _Moderate_.|_severity = Critical_
|title|Search by the advisory title.|_title ~ openssl_
|type|Search by the advisory type.
Specify _security_, _bugfix_, or _enhancement_.|_type = bugfix_
|updated|Search by the date of the last update.
You can use the same formats as with the `issued` parameter.|_updated = "6 days ago"_
|====
