[id="Installing_the_OpenSCAP_Plugin_{context}"]
= Installing the OpenSCAP Plug-in

You can install and enable the OpenSCAP plug-in to generate OpenSCAP compliance reports.
The OpenSCAP plug-in consists of the main OpenSCAP plug-in itself, the OpenSCAP smart proxy plug-in, and the OpenSCAP Hammer CLI plug-in.

.Procedure
. Install the OpenSCAP plug-in on your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-plugin-openscap --enable-foreman-proxy-plugin-openscap
----
ifndef::satellite[]
. Optional: Install the OpenSCAP Hammer CLI plug-in on your {ProjectServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-cli-openscap
----
endif::[]

. Install the OpenSCAP plug-in on any {SmartProxies}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --enable-foreman-proxy-plugin-openscap
----
. Install the OpenSCAP plug-in Puppet module:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install} puppet-foreman_scap_client
----
. In the {ProjectWebUI}, navigate to *Configure > Puppet Classes*.
. Click *Import environments from {foreman-example-com}*.
+
You can use Puppet to install and configure the OpenSCAP plug-in on your {ProjectServer} and {SmartProxies}.
