[id="puppet_guide_prerequisites_{context}"]
= Prerequisites for Puppet

There are four requirements to run the Puppet agent on managed hosts:

. Sync the Puppet agent from https://puppet.com/docs/puppet/6.21/install_puppet.html#enable_the_puppet_platform_repository[puppet.com].
For example, https://yum.puppet.com/puppet6/el/7/x86_64/[Puppet 6 for CentOS 7 on x86_64] or https://apt.puppet.com/[Puppet 6 for Ubuntu 20.04] with release `focal`, component `puppet6`, and architecture `amd64`.
+
Manage these repositories by using products, sync plans, content views, composite content views, and lifecycle environments.
See {ContentManagementDocURL} for more information.
. Provide the Puppet agent to the managed host using their activation key.
. Adjust the provisioning templates to have the Puppet agent installed automatically when provisioning a host:
+
[source,ruby]
----
<%
  pm_set = @host.puppetmaster.empty? ? false : true
  puppet_enabled = pm_set || host_param_true?('force-puppet')
-%>

<% if puppet_enabled %>
<%= snippet 'puppet_setup' %>
<% end -%>
----
+
Setting a Puppet server automatically installs Puppet on the managed host using the `puppet_setup` snippet.
. Add either `enable-puppet5` or `enable-puppet6` as parameter to your host or host group.
Set the parameter type to `boolean` and its value to `true`.
. Set a Puppet environment, Puppet server, and Puppet CA when provisioning a host.
