:_mod-docs-content-type: PROCEDURE

[id="recovering-corrupted-content-on-a-{smart-proxy-context}-server-by-using-web-ui"]
= Recovering corrupted content on a {SmartProxyServer} by using {ProjectWebUI}

[role="_abstract"]
Verify checksums for a lifecycle environment or content view on a {SmartProxyServer} when hosts cannot consume content and you need to repair corrupted files on the {SmartProxyServer}.

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*.
. Select your {SmartProxyServer}.
. Recover corrupted content on your {SmartProxyServer}.
** To repair content in a lifecycle environment, select the ellipsis next to your lifecycle environment and click *Verify Content Checksum*.
** To repair content in a content view, select the ellipsis next to your content view and click *Verify Content Checksum*.

.Verification
. In the {ProjectWebUI}, navigate to *Monitor* > *{Project} Tasks* > *Tasks*.
. Search for `Verify checksum for content`.
. Verify that the task completed successfully.
