[id="assigning-a-puppet-class-to-an-individual-host_{context}"]
= Assigning a Puppet class to an individual host

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Locate the host you want to add the `ntp` Puppet class to and click *Edit*.
. Select the *Puppet ENC* tab and look for the ntp class.
. Click the *+* symbol next to `ntp` to add the _ntp submodule_ to the list of _included classes_.
. Click *Submit* to save your changes.
+
[TIP]
====
If the _Puppet classes_ tab of an individual host is empty, check if it is assigned to the proper Puppet environment.
====

. Verify the Puppet configuration.
.. Navigate to *Hosts* > *All Hosts* and select the host.
.. From the top overflow menu, select *Legacy UI*.
.. Under *Details*, click *Puppet YAML*.
This produces output similar as follows:
+
[source, yaml, options="nowrap", subs="verbatim,quotes,attributes"]
----
---
parameters:
  // shortened YAML output
classes:
  ntp:
    servers: '["0.de.pool.ntp.org","1.de.pool.ntp.org","2.de.pool.ntp.org","3.de.pool.ntp.org"]'
environment: production
...
----

. Verify the ntp configuration.
+
Connect to your host using SSH and check the content of `/etc/ntp.conf`.
+
This example assumes your host is running _CentOS 7_.
Other operating systems may store the ntp config file in a different path.
+
[TIP]
====
You may need to run the Puppet agent on your host by executing the following command:

[options="nowrap", subs="verbatim,quotes,attributes"]
----
# puppet agent -t
----
====

. Running the following command on the host checks which ntp servers are used for clock synchronization:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# cat /etc/ntp.conf
----
+
This returns output similar as follows:
+
[source, none, options="nowrap", subs="verbatim,quotes,attributes"]
----
# ntp.conf: Managed by puppet.
server 0.de.pool.ntp.org
server 1.de.pool.ntp.org
server 2.de.pool.ntp.org
server 3.de.pool.ntp.org
----

You now have a working ntp module which you can add to a host or group of hosts to roll out your ntp configuration automatically.
