[id="Configuring_{smart-proxy-context}_Server_with_Default_SSL_Certificates_to_Generate_and_Sign_Puppet_Certificates_{context}"]
= Configuring {SmartProxyServer} with default SSL certificates to generate and sign Puppet certificates

On the {SmartProxyServer} that will generate Puppet certificates for all other load-balancing {SmartProxyServers}, configure Puppet certificate generation and signing.

.Procedure
. On {ProjectServer}, generate Katello certificates for the system where you configure {SmartProxyServer} to generate and sign Puppet certificates:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {certs-generate} \
--certs-tar "/root/_{smart-proxy-context}-ca.example.com_-certs.tar" \
--foreman-proxy-cname _{loadbalancer-example-com}_ \
--foreman-proxy-fqdn _{smart-proxy-context}-ca.example.com_
----
+
Retain a copy of the example `{foreman-installer}` command that is output by the `{certs-generate}` command for installing {SmartProxyServer} certificate.
. Copy the certificate archive file from {ProjectServer} to {SmartProxyServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp /root/_{smart-proxy-context}-ca.example.com_-certs.tar root@_{smart-proxy-context}-ca.example.com_:__{smart-proxy-context}-ca.example.com__-certs.tar
----
. Append the following options to the `{foreman-installer}` command that you obtain from the output of the `{certs-generate}` command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
--certs-cname "_{loadbalancer-example-com}_" \
--enable-foreman-proxy-plugin-remote-execution-script \
--foreman-proxy-puppetca "true" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--puppet-dns-alt-names "_{loadbalancer-example-com}_" \
--puppet-server-ca "true"
----
. On {SmartProxyServer}, enter the `{foreman-installer}` command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {installer-scenario-smartproxy} \
--certs-cname "_{loadbalancer-example-com}_" \
--certs-tar-file "_{smart-proxy-context}-ca.example.com-certs.tar_" \
--enable-foreman-proxy-plugin-remote-execution-script \
--enable-puppet \
--foreman-proxy-foreman-base-url "_https://{foreman-example-com}_" \
--foreman-proxy-oauth-consumer-key "_oauth key_" \
--foreman-proxy-oauth-consumer-secret "_oauth secret_" \
--foreman-proxy-puppetca "true" \
--foreman-proxy-trusted-hosts "_{foreman-example-com}_" \
--foreman-proxy-trusted-hosts "_{smart-proxy-context}-ca.example.com_" \
--puppet-ca-server "_{smart-proxy-context}-ca.example.com_" \
--puppet-dns-alt-names "_{loadbalancer-example-com}_" \
--puppet-server true \
--puppet-server-ca "true"
----
. On {SmartProxyServer} that is the Puppetserver Certificate Authority, stop the Puppet server:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl stop puppetserver
----
. Generate Puppet certificates for all other {SmartProxyServers} that you configure for load balancing, except the system where you first configured Puppet certificate signing:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# puppetserver ca generate \
--ca-client \
--certname _{smartproxy-example-com}_ \
--subject-alt-names _{loadbalancer-example-com}_
----
+
This command creates the following files:
+
* `/etc/puppetlabs/puppet/ssl/certs/_{smartproxy-example-com}_.pem`
* `/etc/puppetlabs/puppet/ssl/private_keys/_{smartproxy-example-com}_.pem`
* `/etc/puppetlabs/puppet/ssl/public_keys/_{smartproxy-example-com}_.pem`
* `/etc/puppetlabs/puppetserver/ca/signed/_{smartproxy-example-com}_.pem`
. Start the Puppet server:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl start puppetserver
----
