:_mod-docs-content-type: PROCEDURE

[id="Adding_a_Domain_to_Server_{context}"]
= Adding a domain to {ProjectServer}

[role="_abstract"]
{ProjectServer} defines domain names for each host on the network.
{ProjectServer} must have information about the domain and {SmartProxyServer} responsible for domain name assignment.

.Prerequisites
* The selected domain name is available.
{ProjectServer} might already have the relevant domain created as part of {ProjectServer} installation.
Switch the context to `Any Organization` and `Any Location` then check the domain list to see if it exists.

To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-a-domain_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Infrastructure* > *Domains* and click *Create Domain*.
. In the *DNS Domain* field, enter the full DNS domain name.
. In the *Fullname* field, enter the plain text name of the domain.
. Click the *Parameters* tab and configure any domain level parameters to apply to hosts attached to this domain.
For example, user defined Boolean or string parameters to use in templates.
. Click *Add Parameter* and fill in the *Name* and *Value* fields.
. Click the *Locations* tab, and add the location where the domain resides.
. Click the *Organizations* tab, and add the organization that the domain belongs to.
. Click *Submit* to save the changes.

[id="cli-adding-a-domain_{context}"]
.CLI procedure
* Use the `hammer domain create` command to create a domain:
+
[options="nowrap" subs="+quotes,attributes"]
----
$ hammer domain create \
--description "_My_Domain_" \
--dns-id __My_DNS_{smart-proxy-context-titlecase}_ID__ \
--locations "_My_Location_" \
--name "_my-domain.tld_" \
--organizations "_My_Organization_"
----
