[id='tuning-with-predefined-profiles_{context}']

= Tuning {ProjectServer} with Predefined Profiles

If your {Project} deployment includes more than 5000 hosts, you can use predefined tuning profiles to improve performance of {Project}.

Note that you cannot use tuning profiles on {SmartProxies}.

You can choose one of the profiles depending on the number of hosts your {Project} manages and available hardware resources.

The tuning profiles are available in the `/usr/share/foreman-installer/config/foreman.hiera/tuning/sizes` directory.

When you run the `{foreman-installer}` command with the `--tuning` option, deployment configuration settings are applied to {Project} in the following order:

. The default tuning profile defined in the `/usr/share/foreman-installer/config/foreman.hiera/tuning/common.yaml` file

. The tuning profile that you want to apply to your deployment and is defined in the `/usr/share/foreman-installer/config/foreman.hiera/tuning/sizes/` directory

. Optional: If you have configured a `/etc/foreman-installer/custom-hiera.yaml` file, {Project} applies these configuration settings.

Note that the configuration settings that are defined in the `/etc/foreman-installer/custom-hiera.yaml` file override the configuration settings that are defined in the tuning profiles.

Therefore, before applying a tuning profile, you must compare the configuration settings that are defined in the default tuning profile in `/usr/share/foreman-installer/config/foreman.hiera/tuning/common.yaml`, the tuning profile that you want to apply and your `/etc/foreman-installer/custom-hiera.yaml` file, and remove any duplicated configuration from the `/etc/foreman-installer/custom-hiera.yaml` file.

default::
Number of managed hosts: 0{range}5000
+
RAM: 20G
+
Number of CPU cores: 4

medium::
Number of managed hosts: 5001{range}10000
+
RAM: 32G
+
Number of CPU cores: 8

large::
Number of managed hosts: 10001{range}20000
+
RAM: 64G
+
Number of CPU cores: 16

extra-large::
Number of managed hosts: 20001{range}60000
+
RAM: 128G
+
Number of CPU cores: 32

extra-extra-large::
Number of managed hosts: 60000+
+
RAM: 256G
+
Number of CPU cores: 48+

.Procedure

. Optional: If you have configured the `custom-hiera.yaml` file on {ProjectServer}, back up the `/etc/foreman-installer/custom-hiera.yaml` file to `custom-hiera.original`.
You can use the backup file to restore the `/etc/foreman-installer/custom-hiera.yaml` file to its original state if it becomes corrupted:
+
----
# cp /etc/foreman-installer/custom-hiera.yaml \
/etc/foreman-installer/custom-hiera.original
----

. Optional: If you have configured the `custom-hiera.yaml` file on {ProjectServer}, review the definitions of the default tuning profile in `/usr/share/foreman-installer/config/foreman.hiera/tuning/common.yaml` and the tuning profile that you want to apply in `/usr/share/foreman-installer/config/foreman.hiera/tuning/sizes/`.
Compare the configuration entries against the entries in your `/etc/foreman-installer/custom-hiera.yaml` file and remove any duplicated configuration settings in your `/etc/foreman-installer/custom-hiera.yaml` file.

. Enter the `{foreman-installer}` command with the `--tuning` option for the profile that you want to apply.
For example, to apply the medium tuning profile settings, enter the following command:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} --tuning medium
----
