[id="preparing-for-disaster-recovery-with-active-and-passive-project-server-with-external-storage"]
= Preparing for disaster recovery with active and passive {ProjectServer} with external storage

Create your passive {ProjectServer} as a clone of your active {ProjectServer}.
Ensure that the `/var/lib/pulp` and `{postgresql-lib-dir}` directories on your shared storage are available to both servers.

.Procedure
. Replicate the `/var/lib/pulp` and `{postgresql-lib-dir}` directories from the active {ProjectServer} to your shared storage.
. Clone your active {ProjectServer}.
For more information, see xref:cloning_satellite_server[].
. Keep the source server powered on.
Power off the new cloned server.
+
The source server remains your active primary server, while the clone server becomes the passive secondary server.
. Determine how you want to attach the database content on the shared storage to your passive server:
* If you mount the storage directly on both your active and passive server, the servers will always see the same, up-to-date content.
* If you mount the storage only on your active server, the passive server will access the data only if it takes over as the active server.
// This would be a good place to talk more about the pros and cons of these two alternatives, wouldn't it? What would be those pros and cons?

.Verification
Perform this test in an isolated staging environment:

. Mimic a full outage on the active server.
To make sure the active server is inaccessible, you can turn the machine off, halt the virtual machine (VM) if your server runs on a VM, or isolate the machine by using a firewall.
. Switch DNS records of the active server with the DNS records of the passive server.
. Verify that your passive server can access the data stored on your shared storage.
. Assess the functionality of the test {ProjectServer}.
For more information, see xref:Retrieving_the_Status_of_Services_{context}[].
. Perform these verification checks regularly.

ifdef::satellite[]
.Additional resources
* For more information on mounting directories, see link:{RHELDocsBaseURL}9/html-single/managing_file_systems/index#mounting-file-systems-on-demand_managing-file-systems[Mounting file systems on demand] in _{RHEL}{nbsp}9 Managing file systems_.
endif::[]
