
[id="adding-a-host-to-a-host-collection_{context}"]
= Adding a Host to a Host Collection

You can add a host to a host collection in the {ProjectWebUI}.

.Prerequisites
ifdef::satellite[]
A host must be registered to {ProjectName} to add it to a Host Collection.
For more information about registering hosts, see xref:Registering_Hosts_{context}[].
endif::[]

ifndef::satellite[]
A host must be registered to {ProjectName} to add it to a Host Collection.
endif::[]

Note that if you add a host to a host collection, the {Project} auditing system does not log the change.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Click the name of the host you want to modify.
. In the *Host collections* card, click the vertical ellipsis and select *Add host to collections*.
. Select the host collection.
. Click *Add*.

.CLI procedure
* To add a host to a host collection, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer host-collection add-host \
--host-ids _My_Host_ID_1_ \
--id _My_Host_Collection_ID_
----
+
You can add multiple hosts by entering multiple host IDs separated with a comma.
