:_mod-docs-content-type: PROCEDURE

[id="consuming-content-from-an-ansible-collection-repository"]
= Consuming content from an Ansible Collection repository

[role="_abstract"]
Your hosts can consume content from an Ansible Collection repository on {ProjectServer} or {SmartProxyServer}.
Configure

.Prerequisites
* You have synchronized an Ansible Collection to a {Project} repository.
* // TODO: Does the host have to be assigned to the appropriate content view environment?
* The `ansible-core` package is installed on the host.
ifdef::client-content-dnf[]
This package is available in AppStream repositories.
endif::[]

.Procedure
. On the host, configure the `ansible-galaxy` client to use {ProjectServer} or {SmartProxyServer} as the Galaxy server.
Add the required sections to an `ansible.cfg` file, for example:
+
[options="nowrap", subs="+quotes,attributes,verbatim"]
----
[galaxy]
server_list = _My_Library_Server_, _My_Promoted_CV_Server_

[galaxy_server._My_Library_Server_]
url = https://_{server-example-com}_/pulp_ansible/galaxy/_My_Organization_Label_/Library/custom/_My_Product_Label_/_My_Repository_Label_/api/

[galaxy_server._My_Promoted_CV_Server_]
url = https://_{server-example-com}_/pulp_ansible/galaxy/_My_Organization_Label_/_My_Lifecycle_Environment_Label_/_My_Content_View_Label_/custom/_My_Product_Label_/_My_Repository_Label_/api/
----
+
Replace `{server-example-com}` with the fully qualified domain name of your {ProjectServer} or {SmartProxyServer}.
+
[NOTE]
====
Use the `/pulp_ansible/galaxy/` URL path instead of the `/pulp/content/` URL path.
====
. Install an Ansible Collection from your Galaxy server.
For example:
+
[options="nowrap", subs="+quotes,attributes,verbatim"]
----
# ansible-galaxy collection install _My_Namespace.My_Collection_ \
--server _My_Library_Server_
----

.Additional resources
* https://docs.ansible.com/projects/ansible/latest/collections_guide/collections_installing.html#configuring-the-ansible-galaxy-client[Configuring the ansible-galaxy client in the _Ansible Collections Guide_]
* https://docs.ansible.com/projects/ansible/latest/reference_appendices/config.html#the-configuration-file[The configuration file in the _Ansible Reference Appendix_]
