[id="best-practices-for-content-views_{context}"]
= Best practices for content views

* Create content views that bundle content for {client-os} and additional software such as `Apache-2.4` or `PostgreSQL-16.2`.
Content views that are too small require more effort to maintain.
* If you require daily updated content, use the content view `Default Organization View`, which contains the latest synchronized content from all repositories and is available in the _Library_ lifecycle environment.
* Restrict composite content views to situations that require greater flexibility, for example, if you update one content view on a weekly basis and another content view on a monthly basis.
* If you use composite content views, first publish the content views and then publish the composite content views.
The more content views you bundle, the more effort is needed to change or update content.
* Setting a lifecycle environment for content views is unnecessary if they are solely bundled to a composite content view.
* Automate creating and publishing composite content views and lifecycle environments by using a Hammer script or an {ansible-docs-url}[Ansible playbook].
Use cron jobs, systemd timers, or recurring logics for more visibility.
* Add the changes and date to the description of each published content view or composite content view version.
The most recent activity, such as moving content to a new lifecycle environment, is displayed by date in the {ProjectWebUI}, regardless of the latest changes to the content itself.
* Publishing a new content view or composite content view creates a new major version.
Incremental errata updates increment the minor version.
Note that you cannot change or reset this counter.
