:_mod-docs-content-type: REFERENCE

[id="system-requirements_{context}"]
= System requirements

ifdef::satellite[]
{ProductName} is fully supported on both physical systems and virtual machines that run on hypervisors that are supported to run {RHEL}.
For more information about certified hypervisors, see https://access.redhat.com/articles/certified-hypervisors[Certified Guest Operating Systems in Red Hat OpenStack Platform, Red Hat Virtualization, Red Hat OpenShift Virtualization and Red Hat Enterprise Linux with KVM].

endif::[]
Follow these system requirements when installing {ProductName}:

* Install {ProductName} on a freshly provisioned system that serves no other function except to run {ProductName}.
Do not use an existing system because the {Project} installer will affect the configuration of several components.
* Ensure you have administrative user (root) access to the system.
* Ensure the system meets the following requirements:
** {project-minimum-cpus}

ifeval::["{context}" == "{project-context}"]
** {project-minimum-memory} RAM or higher
endif::[]
ifeval::["{context}" == "{smart-proxy-context}"]
** {smart-proxy-minimum-memory} or higher
endif::[]
ifdef::katello,satellite[]
** 4 GB RAM of swap space or higher
endif::[]

** A unique host name, which can contain lower-case letters, numbers, dots (.) and hyphens (-)

* If you use custom certificates, ensure that the Common Name (CN) of the custom certificate is a fully qualified domain name (FQDN).
{ProjectServer} and {SmartProxyServer} do not support shortnames in the hostnames.

ifdef::foreman-el,katello,satellite[]
* Ensure SELinux is enabled, either in enforcing or permissive mode.
Installation with disabled SELinux is not supported.
For more information, see {PlanningDocURL}security-considerations[Security considerations] in _{PlanningDocTitle}_.
endif::[]

* Ensure the system clock on the system is synchronized across the network.
If the system clock is not synchronized, SSL certificate verification might fail.
ifdef::satellite[]
For example, you can use the Chrony suite for timekeeping.
For more information, see {RHELDocsBaseURL}9/html/configuring_basic_system_settings/configuring-time-synchronization_configuring-basic-system-settings[Configuring time synchronization] in _{RHEL}{nbsp}9 Configuring basic system settings_
endif::[]

ifdef::satellite[]
ifeval::["{context}" == "{project-context}"]
* If you are installing in an environment with air-gapped {ProjectServer}s, ensure that all your {ProjectServer}s are on the same {Project} version for ISS Export Sync to work.
ISS Network Sync works across all {Project} versions that support it.
For more information, see {ContentManagementDocURL}Synchronizing_Content_Between_Servers_content-management[Synchronizing Content Between {Project} Servers] in _{ContentManagementDocTitle}_.
endif::[]
endif::[]

* Ensure the system uses the `UTF-8` encoding.
If your territory is USA and your language is English, set `en_US.utf-8` as the system-wide locale settings.
ifndef::foreman-deb[]
For more information about configuring system locale in {EL}, see {RHELDocsBaseURL}9/html/configuring_basic_system_settings/assembly_changing-basic-environment-settings_configuring-basic-system-settings#proc_configuring-the-system-locale_assembly_changing-basic-environment-settings[Configuring the system locale] in _{RHEL}{nbsp}9 Configuring basic system settings_.
endif::[]

ifndef::installer-foremanctl[]
* If you use an external identity provider in your deployment, ensure the provider did not create the following user accounts on the system.
These user accounts can cause conflicts with the local users that {ProductName} creates:
** `{apache-user}`
ifeval::["{context}" == "{project-context}"]
** `foreman`
endif::[]
** `foreman-proxy`
** `postgres`
ifdef::katello,satellite,orcharhino[]
** `pulp`
endif::[]
** `puppet`
** `redis`
ifdef::katello,satellite,orcharhino[]
ifeval::["{context}" == "{project-context}"]
** `tomcat`
endif::[]
endif::[]
endif::[]
ifdef::installer-foremanctl[]
* If you use an external identity provider in your deployment, ensure the provider did not create the `{apache-user}` user account on the system.
This user account can cause conflicts with the local users that {ProductName} creates.
endif::[]

ifeval::["{context}" == "{smart-proxy-context}"]
[WARNING]
====
The version of {SmartProxy} must match the version of {Project} installed.
For example, the {SmartProxy} version {ProjectVersion} cannot be registered with the {Project} version {ProjectVersionPrevious}.
====
endif::[]

ifdef::satellite[]
ifeval::["{context}" == "{smart-proxy-context}"]
For more information on scaling your {SmartProxyServers}, see {InstallingSmartProxyDocURL}{smart-proxy-context}-server-scalability-considerations_{smart-proxy-context}[{SmartProxyServer} scalability considerations].
endif::[]
endif::[]
