[id="DHCP_Options_For_Network_Configuration_{context}"]
= DHCP Options for Network Configuration

--foreman-proxy-dhcp::
  Enables the DHCP service.
You can set this option to `true` or `false`.

--foreman-proxy-dhcp-managed::
  Enables Foreman to manage the DHCP service.
You can set this option to `true` or `false`.

--foreman-proxy-dhcp-gateway::
  The DHCP pool gateway.
Set this to the address of the external gateway for hosts on your private network.

--foreman-proxy-dhcp-interface::
  Sets the interface for the DHCP service to listen for requests.
Set this to `eth1`.

--foreman-proxy-dhcp-nameservers::
  Sets the addresses of the nameservers provided to clients through DHCP.
Set this to the address for {ProjectServer} on `eth1`.

--foreman-proxy-dhcp-range::
  A space-separated DHCP pool range for Discovered and Unmanaged services.

--foreman-proxy-dhcp-server::
  Sets the address of the DHCP server to manage.

Run `{foreman-installer} --help` to view more options related to DHCP and other {SmartProxy} services.
