[id="storage-requirements_{context}"]
= Storage requirements

The following table details storage requirements for specific directories.
These values are based on expected use case scenarios and can vary according to individual environments.

ifdef::katello,satellite[]
The runtime size was measured with {RHEL} 7, 8, and 9 repositories synchronized.
endif::[]

.Storage requirements for a {ProjectServer} installation
[cols="1,1,1",options="header"]
|====
|Directory |Installation Size |Runtime Size

|/var/log |10 MB |10 GB

|{postgresql-lib-dir} |100 MB |20 GB

|/usr | 10 GB | Not Applicable

|/opt/puppetlabs | 500 MB | Not Applicable

ifdef::katello,satellite,orcharhino[]
|/var/lib/pulp |1 MB |300 GB

endif::[]
|====

ifdef::foreman-el,katello,satellite[]
For external database servers: `{postgresql-lib-dir}` with installation size of 100 MB and runtime size of 20 GB.

For detailed information on partitioning and size, see {RHELDocsBaseURL}9/html/managing_storage_devices/disk-partitions_managing-storage-devices[Disk partitions] in _{RHEL-abbr}{nbsp}9 Managing storage devices_.
endif::[]
