[id="performing-configuration-management_{context}"]
= Performing Configuration Management

After you deploy Puppet agent on a host, you can start performing configuration management with Puppet.
This involves the following high-level steps:

. Managing Puppet modules on the Puppet server, that is installing and updating them.
. Importing Puppet classes and environments from Puppet modules into {Project}.
. Optional: Creating config groups from Puppet classes.
. Configuring overrides of Smart Class parameters on various levels.
. Assigning Puppet classes or config groups to host groups or individual hosts.
. Configuring intervals for runs of the Puppet agent on hosts and for configuration enforcement runs of the Puppet server.
. Monitoring configuration management using reports in the {ProjectWebUI}.
For more information, see {AdministeringDocURL}Monitoring_Resources_admin[Monitoring Resources] in _Administering {ProjectName}_.
. Configuring email notifications.
For more information, see {AdministeringDocURL}Configuring_Email_Notifications_admin[Configuring Email Notifications] in _Administering {ProjectName}_.

After assigning Puppet classes or config groups, {Project} runs configuration management automatically in the configured intervals to enforce Puppet configuration on the managed hosts, or you can initiate it manually on demand with the *Run Puppet Once* feature.
For more information, see xref:running-puppet-once-using-ssh_{context}[].
