[id="permissions-required-to-provision-hosts_{context}"]
= Permissions Required to Provision Hosts

The following list provides an overview of the permissions a non-admin user requires to provision hosts.

Compute resource:: view_compute_resources, create_compute_resources, destroy_compute_resources, power_compute_resources
+
Required to provision bare metal hosts.

Compute resource:: view_compute_resources_vms, create_compute_resources_vms, destroy_compute_resources_vms, power_compute_resources_vms
+
Required to provision VM hosts.

Location:: view_locations

Subnet:: view_subnets

Hostgroup:: view_hostgroups, create_hostgroups, edit_hostgroups, play_roles_on_hostgroup

Organization:: view_organizations

Compute profile:: view_compute_profiles

Host:: view_hosts, create_hosts, edit_hosts, destroy_hosts, build_hosts, power_hosts, play_roles_on_host

Host:: view_discovered_hosts, submit_discovered_hosts, auto_provision_discovered_hosts, provision_discovered_hosts, edit_discovered_hosts, destroy_discovered_hosts
+
Required if the Discovery service is enabled.

Activation Keys:: view_activation_keys

Domain:: view_domains

Environment:: view_environments

Image:: view_images

Medium:: view_media

Operatingsystem:: view_operatingsystems

Ptable:: view_ptables

Provisioning template:: view_provisioning_templates

Architecture:: view_architectures

Parameter:: view_params, create_params, edit_params, destroy_params

// Only if Katello is used
Lifecycle Environment:: view_lifecycle_environments

// Only if Katello is used
Product and Repositories:: view_products

// Only if Katello is used
Content Views:: view_content_views

Ansible role:: view_ansible_roles
+
Required if Ansible is used.

{SmartProxy}:: view_smart_proxies, view_smart_proxies_puppetca

{SmartProxy}:: view_openscap_proxies
+
Required if the OpenSCAP plug-in is enabled.

[role="_additional-resources"]
.Additional resources
* {AdministeringDocURL}Creating_a_Role_admin[Creating a Role] in _{AdministeringDocTitle}_
* {AdministeringDocURL}Adding_Permissions_to_a_Role_admin[Adding Permissions to a Role] in _{AdministeringDocTitle}_
* {AdministeringDocURL}Assigning_Roles_to_a_User_admin[Assigning Roles to a User] in _{AdministeringDocTitle}_