:_mod-docs-content-type: REFERENCE

[id="registration-methods_{context}"]
= Registration methods

[role="_abstract"]
You can use the following
ifdef::orcharhino[]
method
endif::[]
ifndef::orcharhino[]
methods
endif::[]
to register hosts to {Project}:

Global registration::
You generate a registration command from {Project} and run this command on an unlimited number of hosts to register them by using provisioning templates over the {Project} API.
For more information, see xref:Registering_Hosts_by_Using_Global_Registration_{context}[].
+
By using this method, you can also deploy {Project} SSH keys to hosts during registration to {Project} to enable hosts for remote execution jobs.
For more information, see xref:Configuring_and_Setting_Up_Remote_Jobs_{context}[].
+
By using this method, you can also configure hosts with {Insights} during registration to {Project}.
For more information, see xref:monitoring-hosts-by-using-insights[].

ifndef::satellite,orcharhino[]
Katello RHSM Consumer script::
You download and install the consumer script from `_{foreman-example-com}_/pub/katello-rhsm-consumer` on the host and then run the script.
This method is suitable for hosts that run Debian/Ubuntu.
endif::[]

ifndef::orcharhino[]
*(Deprecated)* Katello CA Consumer::
You download and install the consumer RPM from `_{foreman-example-com}_/pub/katello-ca-consumer-latest.noarch.rpm` on the host and then run `subscription-manager`.

*(Deprecated)* Bootstrap script::
You download the bootstrap script from `_{foreman-example-com}_/pub/bootstrap.py` on the host and then run the script.
For more information, see xref:Registering_Hosts_by_Using_the_Bootstrap_Script_{context}[].
endif::[]
