[id="DNS_Options_For_Network_Configuration_{context}"]
= DNS Options for Network Configuration

--foreman-proxy-dns::
  Enables the DNS feature.
You can set this option to `true` or `false`.

--foreman-proxy-dns-provider::
  Selects the provider to be used.

--foreman-proxy-dns-managed::
  Let the installer manage ISC BIND.
This is only relevant when using the `nsupdate` and `nsupdate_gss` providers.
You can set this option to `true` or `false`.

--foreman-proxy-dns-forwarders::
  Sets the DNS forwarders.
Only used when ISC BIND is managed by the installer.
Set this to your DNS recursors.

--foreman-proxy-dns-interface::
  Sets the interface to listen for DNS requests.
Only used when ISC BIND is managed by the installer.
Set this to `eth1`.

--foreman-proxy-dns-reverse::
  The DNS reverse zone name.
Only used when ISC BIND is managed by the installer.

--foreman-proxy-dns-server::
  Sets the address of the DNS server.
Only used by the `nsupdate`, `nsupdate_gss`, and `infoblox` providers.

--foreman-proxy-dns-zone::
  Sets the DNS zone name.
Only used when ISC BIND is managed by the installer.

Run `{foreman-installer} --help` to view more options related to DNS and other {SmartProxy} services.
