[id="performing-configuration-management_{context}"]
= Performing Configuration Management

Once you deployed Puppet agent on a host, you can start performing configuration management with Puppet.
This involves the following high-level steps:

. Managing Puppet modules on the Puppet server, that is installing and updating them.
. Importing Puppet classes and environments from Puppet modules into {Project}.
. Optional: Creating config groups.
. Configuring overrides of Smart Class parameters on various levels.
. Assigning Puppet classes, modules, or config groups to host groups or individual hosts.
. Configuring intervals for runs of the Puppet agent on hosts and for configuration enforcement runs of the Puppet server.
. Monitoring configuration management using reports in the {ProjectWebUI}.
. Configuring email notifications.
See {AdministeringDocURL}Configuring_Email_Notifications_admin[Configuring Email Notifications] in _Administering {ProjectName}_.

After assigning Puppet modules and configuring the intervals, {Project} runs configuration management automatically in the configured intervals to enforce Puppet configuration on the managed hosts, or you can initiate it manually on demand with the xref:running-puppet-once-using-ssh_managing-configurations-puppet[*Run Puppet Once* feature].
