[id="system-requirements_{context}"]
= System requirements

The following requirements apply to the networked base operating system:

* x86_64 architecture
ifdef::satellite[]
* The latest version of {EL} 9 or {EL} 8
endif::[]
* 4-core 2.0 GHz CPU at a minimum

ifeval::["{context}" == "{project-context}"]
* A minimum of {project-minimum-memory} RAM is required for {ProjectServer} to function.
ifdef::katello,satellite[]
In addition, a minimum of 4 GB RAM of swap space is also recommended.
endif::[]
{Project} running with less RAM than the minimum value might not operate correctly.
endif::[]

ifeval::["{context}" == "{smart-proxy-context}"]
* A minimum of 12 GB RAM is required for {SmartProxyServer} to function.
In addition, a minimum of 4 GB RAM of swap space is also recommended.
{SmartProxy} running with less RAM than the minimum value might not operate correctly.
endif::[]

ifdef::katello,satellite[]
* A unique host name, which can contain lower-case letters, numbers, dots (.) and hyphens (-)
endif::[]

ifdef::satellite[]
* A current {ProjectName} subscription
endif::[]
* Administrative user (root) access
* Full forward and reverse DNS resolution using a fully-qualified domain name

{Project} only supports `UTF-8` encoding.
If your territory is USA and your language is English, set `en_US.utf-8` as the system-wide locale settings.
For more information about configuring system locale in {EL}, see {RHELDocsBaseURL}9/html/configuring_basic_system_settings/assembly_changing-basic-environment-settings_configuring-basic-system-settings#proc_configuring-the-system-locale_assembly_changing-basic-environment-settings[Configuring the system locale] in _{RHEL}{nbsp}9 Configuring basic system settings_.

ifdef::satellite[]
Your {Project} must have the {SatelliteSub} manifest in your Customer Portal.
{Project} must have {project-context}-{smart-proxy-context}-6.x repository enabled and synced.
To create, manage, and export a Red{nbsp}Hat Subscription Manifest in the Customer Portal, see {RHDocsBaseURL}subscription_central/1-latest/html/creating_and_managing_manifests_for_a_connected_satellite_server/index[Creating and managing manifests for a connected {ProjectServer}] in _Subscription Central_.
endif::[]

{ProjectServer} and {SmartProxyServer} do not support shortnames in the hostnames.
When using custom certificates, the Common Name (CN) of the custom certificate must be a fully qualified domain name (FQDN) instead of a shortname.
This does not apply to the clients of a {Project}.

Before you install {ProductName}, ensure that your environment meets the requirements for installation.
ifeval::["{context}" == "{smart-proxy-context}"]
[WARNING]
====
The version of {SmartProxy} must match with the version of {Project} installed.
It should not be different.
For example, the {SmartProxy} version {ProjectVersion} cannot be registered with the {Project} version {ProjectVersionPrevious}.
====
endif::[]

{ProductName} must be installed on a freshly provisioned system that serves no other function except to run {ProductName}.
The freshly provisioned system must not have the following users provided by external identity providers to avoid conflicts with the local users that {ProductName} creates:

* {apache-user}
ifeval::["{context}" == "{project-context}"]
* foreman
endif::[]
* foreman-proxy
* postgres
ifdef::katello,satellite,orcharhino[]
* pulp
endif::[]
* puppet
* redis
ifdef::katello,satellite,orcharhino[]
ifeval::["{context}" == "{project-context}"]
* tomcat
endif::[]
endif::[]

ifdef::satellite[]
ifeval::["{context}" == "{smart-proxy-context}"]
For more information on scaling your {SmartProxyServers}, see {InstallingSmartProxyDocURL}{smart-proxy-context}-server-scalability-considerations_{smart-proxy-context}[{SmartProxyServer} scalability considerations].
endif::[]
endif::[]

ifdef::satellite[]
.Certified hypervisors
{ProductName} is fully supported on both physical systems and virtual machines that run on hypervisors that are supported to run {RHEL}.
For more information about certified hypervisors, see https://access.redhat.com/articles/973163[Certified Guest Operating Systems in {OpenStack}, {oVirt}, Red Hat {KubeVirt} and {RHEL} with KVM].
endif::[]

ifdef::foreman-el,katello,satellite[]
.SELinux mode
SELinux must be enabled, either in enforcing or permissive mode.
Installation with disabled SELinux is not supported.
endif::[]

.Synchronized system clock
The system clock on the base operating system where you are installing your {ProductName} must be synchronized across the network.
If the system clock is not synchronized, SSL certificate verification might fail.
ifdef::satellite[]
For example, you can use the Chrony suite for timekeeping.
For more information, see the following documents:

* {RHELDocsBaseURL}9/html/configuring_basic_system_settings/configuring-time-synchronization_configuring-basic-system-settings[Configuring time synchronization] in _{RHEL}{nbsp}9 Configuring basic system settings_
* {RHELDocsBaseURL}8/html/configuring_basic_system_settings/configuring-time-synchronization_configuring-basic-system-settings[COnfiguring time synchronization] in _{RHEL}{nbsp}8 Configuring basic system settings_.
endif::[]

ifdef::foreman-el,katello,satellite[]
.FIPS mode
ifeval::["{context}" == "{project-context}"]
You can install {Project} on a {EL} system that is operating in FIPS mode.
You cannot enable FIPS mode after the installation of {Project}.
endif::[]
ifeval::["{context}" == "{smart-proxy-context}"]
You can install {SmartProxy} on a {EL} system that is operating in FIPS mode.
You cannot enable FIPS mode after the installation of {SmartProxy}.
endif::[]
ifndef::satellite[]
{RHEL} clones are not being actively tested in FIPS mode.
If you require FIPS, consider using {RHEL}.
endif::[]
For more information, see {RHELDocsBaseURL}9/html/security_hardening/switching-rhel-to-fips-mode_security-hardening[Switching RHEL to FIPS mode] in _{RHEL}{nbsp}9 Security hardening_ or {RHELDocsBaseURL}8/html/security_hardening/switching-rhel-to-fips-mode_security-hardening[Switching RHEL to FIPS mode] in _{RHEL}{nbsp}8 Security hardening_.

[NOTE]
====
{Project} supports DEFAULT and FIPS crypto-policies.
The FUTURE crypto-policy is not supported for {Project} and {SmartProxy} installations.
The FUTURE policy is a stricter forward-looking security level intended for testing a possible future policy.
For more information, see {RHELDocsBaseURL}9/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening[Using system-wide cryptographic policies] in _{RHEL}{nbsp}9 Security hardening_.
====
endif::[]

ifdef::satellite[]
ifeval::["{context}" == "{project-context}"]
.{ISS} (ISS)
In a scenario with air-gapped {ProjectServer}s, all your {ProjectServer}s must be on the same {Project} version for ISS Export Sync to work.
ISS Network Sync works across all {Project} versions that support it.
For more information, see {ContentManagementDocURL}Synchronizing_Content_Between_Servers_content-management[Synchronizing Content Between {Project} Servers] in _{ContentManagementDocTitle}_.
endif::[]
endif::[]
