[id="ports-and-firewalls-requirements_{context}"]
[id="satellite-ports-and-firewalls-requirements_{context}"]
= Ports and Firewalls Requirements

For the components of {Project} architecture to communicate, ensure that the required network ports are open and free on the base operating system.
You must also ensure that the required network ports are open on any network-based firewalls.

Use this information to configure any network-based firewalls.
Note that some cloud solutions must be specifically configured to allow communications between machines because they isolate machines similarly to network-based firewalls.
If you use an application-based firewall, ensure that the application-based firewall permits all applications that are listed in the tables and known to your firewall.
If possible, disable the application checking and allow open port communication based on the protocol.

.Integrated {SmartProxy}
{ProjectServer} has an integrated {SmartProxy} and any host that is directly connected to {ProjectServer} is a Client of {Project} in the context of this section.
This includes the base operating system on which {SmartProxyServer} is running.

.Clients of {SmartProxy}
Hosts which are clients of {SmartProxies}, other than {Project}'s integrated {SmartProxy}, do not need access to {ProjectServer}.
ifdef::satellite[]
For more information on {Project} Topology, see {PlanningDocURL}sect-Documentation-Architecture_Guide-Capsule_Networking[{SmartProxy} Networking] in _Planning for {ProjectNameX}_.
endif::[]

Required ports can change based on your configuration.

ifdef::satellite[]
A matrix table of ports is available in the Red{nbsp}Hat Knowledgebase solution https://access.redhat.com/solutions/5627751[Red Hat Satellite List of Network Ports].
endif::[]

The following tables indicate the destination port and the direction of network traffic:

ifdef::satellite[]
ifeval::["{mode}" == "connected"]
.Ports for {Project} to Red Hat CDN Communication
[cols="24%,20%,18%,38%",options="header"]
|====
| Port | Protocol | Service | Required For
| 443 | TCP | HTTPS | Subscription Management Services (access.redhat.com) and connecting to the Red{nbsp}Hat CDN (cdn.redhat.com).
|====
endif::[]
endif::[]

ifdef::satellite[]
ifeval::["{mode}" == "connected"]
{ProjectServer} needs access to the Red{nbsp}Hat CDN.
For a list of IP addresses used by the Red{nbsp}Hat CDN (cdn.redhat.com), see the Knowledgebase article https://access.redhat.com/articles/1525183[Public CIDR Lists for Red Hat] on the Red{nbsp}Hat Customer Portal.
endif::[]
endif::[]

ifdef::katello[]
ifeval::["{mode}" == "connected"]
If you plan to use Red{nbsp}Hat services, {ProjectServer} needs access to the Red{nbsp}Hat CDN.
For a list of IP addresses used by the Red{nbsp}Hat CDN (cdn.redhat.com), see the Knowledgebase article https://access.redhat.com/articles/1525183[Public CIDR Lists for Red Hat] on the Red{nbsp}Hat Customer Portal.
endif::[]
endif::[]

.Ports for Browser-based User Interface Access to {Project}
[cols="24%,20%,18%,38%",options="header"]
|====
| Port | Protocol | Service | Required For
| 443 | TCP | HTTPS | Browser-based UI access to {Project}
| 80 | TCP | HTTP | Redirection to HTTPS for web UI access to {Project} (Optional)
|====

.Ports for Client to {Project} Communication
[cols="24%,20%,18%,38%",options="header"]
|====
| Port | Protocol | Service | Required For
| 80 | TCP | HTTP | Anaconda, yum, for obtaining Katello certificates, templates, and for downloading iPXE firmware
| 443 | TCP | HTTPS | Subscription Management Services, yum, Telemetry Services and client connections
ifdef::katello,satellite[]
| 5646 | TCP | AMQP | The {SmartProxy} Qpid dispatch router to the Qpid dispatch router in {Project}
| 5647 | TCP | AMQP | Katello Agent to communicate with {Project}'s Qpid dispatch router
endif::[]
| 8000 | TCP | HTTP | Anaconda to download kickstart templates to hosts, and for downloading iPXE firmware
| 8140 | TCP | HTTPS | Puppet agent to Puppet master connections
| 9090 | TCP | HTTPS | Sending SCAP reports to the integrated {SmartProxy}, for the discovery image during provisioning, and for communicating with {ProjectServer} to copy the SSH keys for Remote Execution (Rex) configuration
ifeval::["{mode}" == "connected"]
| - | ICMP | ping | DHCP {SmartProxy} to Client network, to verify non-active IP address (Optional)
| 7 | TCP | echo | DHCP {SmartProxy} to Client network, to verify non-active IP address (Optional)
endif::[]
| 53 | TCP and UDP | DNS | Client DNS queries to a {Project}'s integrated {SmartProxy} DNS service (Optional)
| 67 | UDP | DHCP | Client to {Project}'s integrated {SmartProxy} broadcasts, DHCP broadcasts for Client provisioning from a {Project}'s integrated {SmartProxy} (Optional)
| 69 | UDP |TFTP | Clients downloading PXE boot image files from a {Project}s' integrated {SmartProxy} for provisioning (Optional)
|====

Any managed host that is directly connected to {ProjectServer} is a client in this context because it is a client of the integrated {SmartProxy}.
This includes the base operating system on which a {SmartProxyServer} is running.

A DHCP {SmartProxy} performs ICMP ping or TCP echo connection attempts to hosts in subnets with DHCP IPAM set to find out if an IP address considered for use is free.
This behavior can be turned off using `{foreman-installer} --foreman-proxy-dhcp-ping-free-ip=false`.

.Ports for {Project} to {SmartProxy} Communication
[cols="24%,20%,18%,38%",options="header"]
|====
| Port | Protocol | Service | Required for
| 443 |  TCP | HTTPS | Connections to the Pulp server in the {SmartProxy}
| 9090 | TCP | HTTPS | Connections to the proxy in the {SmartProxy}
| 80 | TCP | HTTP | Downloading a bootdisk (Optional)
|====


.Optional Network Ports
[cols="24%,20%,18%,38%a",options="header"]
|====
| Port | Protocol | Service | Required For
| 22 | TCP | SSH | {Project} and {SmartProxy} originated communications, for Remote Execution (Rex) and Ansible.
| 443 | TCP | HTTPS | {Project} originated communications, for vCenter compute resource.
| 5000 | TCP | HTTP | {Project} originated communications, for compute resources in OpenStack or for running containers.
| 22, 16514 | TCP | SSH, SSL/TLS | {Project} originated communications, for compute resources in libvirt.
| 389, 636 | TCP | LDAP, LDAPS | {Project} originated communications, for LDAP and secured LDAP authentication sources.
| 5900 to 5930 | TCP | SSL/TLS | {Project} originated communications, for NoVNC console in web UI to hypervisors.
|====
