[id="Automatic_Contexts_for_Discovered_Hosts_{context}"]
= Automatic Contexts for Discovered Hosts

{ProjectServer} assigns an organization and location to discovered hosts according to the following sequence of rules:

. If a discovered host uses a subnet defined in {Project}, the host uses the first organization and location associated with the subnet.
. If the `discovery_organization` or `discovery_location` fact values are set, the discovered host uses these fact values as an organization and location.
To set these fact values, navigate to *Administer*{nbsp}>{nbsp}*Settings* > *Discovered*, and add these facts to the *Default organization* and *Default location* fields.
Ensure that the discovered host's subnet also belongs to the organization and location set by the fact, otherwise {Project} refuses to set it for security reasons.
. If none of the previous conditions exists, {Project} assigns the first Organization and Location ordered by name.

You can change the organization or location using the bulk actions menu of the *Discovered hosts* page.
Select the discovered hosts to modify and select *Assign Organization* or *Assign Location* from the *Select Action* menu.

Note that the `foreman_organization` and `foreman_location` facts are no longer valid values for assigning context for discovered hosts.
You still can use these facts to configure the host for Puppet runs.
To do this, navigate to *Administer*{nbsp}>{nbsp}*Settings* > *Puppet* section and add the `foreman_organization` and `foreman_location` facts to the *Default organization* and *Default location* fields.
