[id="access_to_information_from_insights_in_{Project}_{context}"]
= Access to information from Lightspeed in {Project}

You can access the additional information available for hosts from Red{nbsp}Hat Lightspeed in the following places in the {ProjectWebUI}:

* Navigate to *Insights* > *Recommendations* where the vertical ellipsis next to the *Remediate* button provides a *View in Red{nbsp}Hat Insights* link to the general recommendations page.
On each recommendation line, the vertical ellipsis provides a *View in Red{nbsp}Hat Insights* link to the recommendation rule, and, if one is available for that recommendation, a *Knowledgebase article* link.

* For additional information, navigate to *Hosts* > *All Hosts*.
If the host has recommendations listed, click on the number of recommendations.
On the *Insights* tab, the vertical ellipsis next to the *Remediate* button provides a *Go To {Project} Insights page* link to information for the system, and a *View in Red{nbsp}Hat Insights* link to host details on the console.
