[id="virt-who-troubleshooting-methods_{context}"]
= Virt-who troubleshooting methods

.Verifying virt-who status

To verify the status of `virt-who` by using the {ProjectWebUI}, navigate to *Infrastructure* > *Virt-who configurations* and check the *Status* column for each virt-who instance.
A status of `OK` indicates that virt-who is successfully connecting to Satellite{nbsp}Server and reporting the virtual machines managed by each hypervisor.

To list the status of all virt-who instances by using the CLI, enter the following command on {ProjectServer}:

----
# hammer virt-who-config list
----

The command's output includes the date and time at which each virt-who instance reported to {ProjectServer}.

.Debug logging

Check the `/var/log/rhsm/rhsm.log` file, where virt-who logs all its activity by default.

To enable more detailed logging, modify the virt-who configuration:

* In the {ProjectWebUI}, select *Enable debugging output*.
* In the Hammer CLI, add the `--debug true` option.

Redeploy the configuration for the change to take effect.

When the underlying issue is resolved, modify the virt-who configuration to disable debugging, then redeploy the configuration again.

.Testing configuration options

Make a change and test the result, repeating as needed. Virt-who provides two options to help test the configuration files, credentials, and connectivity to the virtualization platform:

* The `virt-who --one-shot` command reads the configuration files, retrieves the list of virtual machines and sends it to {ProjectServer}, then exits immediately.
* The `virt-who --print` command reads the configuration files and prints the list of virtual machines, but does not send it to {ProjectServer}.

The expected output is a list of hypervisors and their virtual machines, in JSON format.
The following is an extract from a VMware vSphere instance. The output from all hypervisors follows the same structure.

[options="nowrap"]
----
{
    "guestId": "422f24ed-71f1-8ddf-de53-86da7900df12",
    "state": 5,
    "attributes": {
        "active": 0,
        "virtWhoType": "esx",
        "hypervisorType": "vmware"
    }
},
----

.Identifying issues when using multiple virt-who configuration files

If you have multiple virt-who configuration files on one server, move one file at a time to a different directory while testing after each file move.
If the issue no longer occurs, the cause is associated with the most recently moved file.
After you have resolved the issue, return the virt-who configuration files to their original location.

Alternatively, you can test an individual file after moving it by using the `--config` option to specify its location. For example:

[options="nowrap" subs="+quotes,verbatim"]
----
# virt-who --debug --one-shot --config /tmp/_conf_name_.conf
----

.Identifying duplicate hypervisors

Duplicate hypervisors can cause subscription and entitlement errors. Enter the following commands to check for duplicate hypervisors:

[options="nowrap" subs="+quotes,verbatim"]
----
# systemctl stop virt-who
# virt-who -op >/tmp/virt-who.json
# systemctl start virt-who
# cat /tmp/virt-who.json | json_reformat | grep name | sort | uniq -c | sort -nr | head -n10
  3    "name": "localhost"
  1    "name": "rhel1.example.com"
  1    "name": "rhel2.example.com"
  1    "name": "rhel3.example.com"
  1    "name": "rhel4.example.com"
  1    "name": "rhvh1.example.com"
  1    "name": "rhvh2.example.com"
  1    "name": "rhvh3.example.com"
  1    "name": "rhvh4.example.com"
  1    "name": "rhvh5.example.com"
----

In this example, three hypervisors have the same FQDN (`localhost`), and must be corrected to use unique FQDNs.

.Identifying duplicate virtual machines

Enter the following commands to check for duplicate virtual machines:

[options="nowrap" subs="+quotes,verbatim"]
----
# systemctl stop virt-who
# virt-who -op >/tmp/virt-who.json
# systemctl start virt-who
# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | sort -nr | head -n10
----

.Checking the number of hypervisors

Enter the following commands to check the number of hypervisors virt-who currently reports:

[options="nowrap" subs="+quotes,verbatim"]
----
# systemctl stop virt-who
# virt-who -op >/tmp/virt-who.json
# systemctl start virt-who
# cat /tmp/virt-who.json | json_reformat | grep name | sort | uniq -c | wc -l
----

.Checking the number of virtual machines

Enter the following commands to check the number of virtual machines that virt-who currently reports:

[options="nowrap" subs="+quotes,verbatim"]
----
# systemctl stop virt-who
# virt-who -op >/tmp/virt-who.json
# systemctl start virt-who
# cat /tmp/virt-who.json | json_reformat | grep "guestId" | sort | uniq -c | wc -l
----
