[id="supported-clients-in-registration_{context}"]
= Supported clients in registration

{Project} supports the following operating systems and architectures for registration.

ifndef::orcharhino,satellite[]
[NOTE]
====
The following combinations have been tested.
https://github.com/theforeman/foreman/blob/develop/app/views/unattended/provisioning_templates/registration/global_registration.erb[*Global registration*] is a provisioning template for a shell script, which can be extended for additional systems.

If you decide to extend the template, please submit your changes to https://github.com/theforeman/foreman/#how-to-contribute[our repository].
Thanks for your contribution!
====
endif::[]

Supported Host Operating Systems::
The hosts can use the following operating systems:

ifndef::orcharhino,satellite[]
* Amazon Linux
* Debian
endif::[]
ifndef::orcharhino[]
* {EL} 9, 8, 7
endif::[]
ifdef::satellite[]
* {EL} 6 with the https://www.redhat.com/en/resources/els-datasheet[ELS Add-On]
endif::[]
ifndef::orcharhino,satellite[]
* Fedora
* OpenSUSE
* {SLES}
* Ubuntu
endif::[]
ifdef::orcharhino[]
* AlmaLinux
* Amazon Linux
* CentOS
* Debian
* Oracle Linux
* Red Hat Enterprise Linux
* Rocky Linux
* SUSE Linux Enterprise Server
* Ubuntu
endif::[]

Supported Host Architectures::
The hosts can use the following architectures:

ifdef::satellite[]
* i386
* x86_64
* s390x
* ppc_64
endif::[]

ifdef::orcharhino[]
[cols="2,3"]
|===
|Operating System |Architectures
|Debian 10 |aarch64, ppc64le, amd64
|Debian 11 |aarch64, amd64
|Debian 12 |amd64
|{EL} |x86_64
|{SLES} 12 |amd64
|{SLES} 15 |aarch64, ppc64le, amd64
|Ubuntu 16.04 |amd64
|Ubuntu 18.04 |amd64
|Ubuntu 20.04 |aarch64, amd64
|Ubuntu 22.04 |aarch64, amd64
|===
endif::[]

ifndef::orcharhino,satellite[]
* x86_64/amd64
endif::[]
