[id="remote_execution_settings_{context}"]
= Remote Execution Settings

[cols="30%,30%,40%",options="header"]
|====
| Setting | Default Value | Description
ifdef::satellite[]
| *Fallback to Any Capsule* | No | Search the host for any proxy with Remote Execution.
This is useful when the host has no subnet or the subnet does not have an execution proxy.
| *Enable Global Capsule* | Yes | Search for Remote Execution proxy outside of the proxies assigned to the host.
The search is limited to the host's organization and location.
endif::[]
ifndef::satellite[]
| *Fallback to Any Proxy* | No | Search the host for any proxy with Remote Execution.
This is useful when the host has no subnet or the subnet does not have an execution proxy.
| *Enable Global Proxy* | Yes | Search for Remote Execution proxy outside of the proxies assigned to the host.
The search is limited to the host's organization and location.
endif::[]
| *SSH User* | root | Default user to use for SSH.
You can override per host by setting the `remote_execution_ssh_user` parameter.
| *Effective User* | root | Default user to use for executing the script.
If the user differs from the SSH user, su or sudo is used to switch the user.
| *Effective User Method* | sudo | The command used to switch to the effective user.
One of [`sudo`, `dzdo`, `su`]
| *Effective user password* | \\***** | Effective user password. See *Effective User*.
| *Sync Job Templates* | Yes | Whether to sync templates from disk when running `db:seed`.
| *SSH Port* | 22 | Port to use for SSH communication.
Default port 22.
You can override per host by setting the `remote_execution_ssh_port` parameter.
| *Connect by IP* | No | Whether the IP addresses on host interfaces are preferred over the FQDN.
It is useful when the DNS is not resolving the FQDNs properly.
You can override this per host by setting the `remote_execution_connect_by_ip` parameter.
For dual-stacked hosts, consider the `remote_execution_connect_by_ip_prefer_ipv6` setting.
| *Prefer IPv6 over IPv4* | No | When connecting using an IP address, are IPv6 addresses preferred?
If no IPv6 address is set, it falls back to IPv4 automatically.
You can override this per host by setting the `remote_execution_connect_by_ip_prefer_ipv6` parameter.
By default and for compatibility, IPv4 is preferred over IPv6.
| *Default SSH password* | \\***** | Default password to use for SSH.
You can override per host by setting the `remote_execution_ssh_password` parameter.
| *Default SSH key passphrase* | \\***** | Default key passphrase to use for SSH.
You can override per host by setting the `remote_execution_ssh_key_passphrase` parameter.
| *Workers pool size* | 5 | Number of workers in the pool to handle the execution of the remote execution jobs.
Restart of the `dynflowd/{project-context}-tasks` service is required.
| *Cleanup working directories* | Yes | Whether working directories are removed after task completion.
You can override this per host by setting the `remote_execution_cleanup_working_dirs` parameter.
| *Cockpit URL* | | Where to find the Cockpit instance for the Web Console button.
By default, no button is shown.
| *Form Job Template* | Run Command - SSH Default | Choose a job template that is pre-selected in job invocation form.
| *Job Invocation Report Template* | Jobs - Invocation report template | Select a report template used for generating a report for a particular remote execution job.
| *Time to pickup* | 86400 | Time in seconds within which the host has to pick up a job.
If the job is not picked up within this limit, the job will be cancelled.
Applies only to pull-mqtt based jobs.
Defaults to one day.
|====
