:_mod-docs-content-type: REFERENCE

[id="best-practices-for-patching-content-hosts_{context}"]
= Best practices for patching content hosts

[role="_abstract"]
* Registering hosts to {Project} requires {project-client-name}, which contains the `katello-host-tools` package and its dependencies.
For more information, see {ManagingHostsDocURL}Registering_Hosts_by_Using_Global_Registration_managing-hosts[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_.
* Use the {ProjectWebUI} to install, upgrade, and remove packages from hosts.
You can update content hosts with job templates using SSH and Ansible.
* Apply errata on content hosts using the {ProjectWebUI}.
When patching packages on hosts using the default package manager, {Project} receives a list of packages and repositories to recalculate applicable errata and available updates.
* Modify or replace job templates to add custom steps.
This allows you to run commands or execute scripts on hosts.
* When running bulk actions on hosts, bundle them by major operating system version, especially when upgrading packages.
* Select *via remote execution {endash} customize first* to define the time when patches are applied to hosts when performing bulk actions.
* You cannot apply errata to packages that are not part of the repositories on {Project} and the assigned content view environments.
* Modifications to installed packages using `rpm` or `dpkg` are sent to {Project} with the next run of `apt`, `yum`, or `zypper`.
