[id="capsule-storage-requirements_{context}"]
= Storage requirements

The following table details storage requirements for specific directories.
These values are based on expected use case scenarios and can vary according to individual environments.

ifdef::katello,satellite[]
The runtime size was measured with {RHEL} 7, 8, and 9 repositories synchronized.
endif::[]

.Storage requirements for {SmartProxyServer} installation
[cols="1,1,1",options="header"]
|====
|Directory |Installation Size |Runtime Size
ifdef::katello,satellite,orcharhino[]
|/var/lib/pulp |1 MB |300 GB
|{postgresql-lib-dir} |100 MB |20 GB
endif::[]
|/usr |3 GB |Not Applicable
|/opt/puppetlabs |500 MB |Not Applicable
|====

The size of the PostgreSQL database on your {SmartProxyServer} can grow significantly with an increasing number of lifecycle environments, content views, or repositories that are synchronized from your {ProjectServer}.
In the largest {Project} environments, the size of `{postgresql-lib-dir}` on {SmartProxyServer} can grow to double or triple the size of `{postgresql-lib-dir}` on your {ProjectServer}.
