:_mod-docs-content-type: REFERENCE

[id="technical-users-provided-and-required-by-{project-context}"]
= Technical users provided and required by {Project}

[role="_abstract"]
The {Project} installation process automatically creates system accounts.
They manage files and process ownership of the components integrated into {Project}.
The following table lists all the accounts created by {Project} during installation.

Some of these accounts have fixed UIDs and GIDs, while others take the next available UID and GID on the system instead.
To control the UIDs and GIDs assigned to accounts, you can define accounts before installing {Project}.
Because some of the accounts have hard-coded UIDs and GIDs, it is not possible to do this with all accounts created during {Project} installation.

You can predefine accounts that have *Yes* in the *Flexible UID and GID* column with custom UID and GID before installing {Project}.

Do not change the home and shell directories of system accounts because they are requirements for {Project}.

Because of potential conflicts with local users that {Project} creates, you cannot use external identity providers for the system users of the {Project} base operating system.

.Technical users provided and required by {Project}
[options="header"]
|====
|User name |UID |Group name |GID |Flexible UID and GID |Home |Shell
|foreman |N/A |foreman |N/A |yes |/usr/share/foreman |/sbin/nologin
|foreman-proxy |N/A |foreman-proxy |N/A |yes |/usr/share/foreman-proxy |/sbin/nologin
ifdef::foreman-deb[]
|{apache-user} |33 |{apache-user} |33 |no |/var/www |/usr/sbin/nologin
endif::[]
ifndef::foreman-deb[]
|{apache-user} |48 |{apache-user} |48 |no |/usr/share/httpd |/sbin/nologin
endif::[]
|postgres |26 |postgres |26 |no |{postgresql-lib-dir} |/bin/bash
ifdef::katello,orcharhino,satellite[]
|pulp |N/A |pulp |N/A |no |N/A |/sbin/nologin
endif::[]
|puppet |52 |puppet |52 |no |/opt/puppetlabs/server/data/puppetserver |/sbin/nologin
ifdef::katello,orcharhino,satellite[]
|saslauth |N/A |saslauth |76 |no |/run/saslauthd |/sbin/nologin
|tomcat |53 |tomcat |53 |no |/usr/share/tomcat |/bin/nologin
endif::[]
ifndef::foreman-deb[]
|unbound |N/A |unbound |N/A |yes |/etc/unbound |/sbin/nologin
endif::[]
|====
