[id="Overview_of_Individual_Loggers_{context}"]
= Overview of individual loggers

The following list provides an overview of selected loggers.
You can find the complete list of loggers with their default values in
ifdef::satellite,orcharhino[]
`/usr/share/foreman/config/application.rb` under `Foreman::Logging.add_loggers`.
endif::[]
ifndef::satellite,orcharhino[]
https://github.com/theforeman/foreman/blob/55b0a9f1b1b2871976c5ea7b7874f18afcf1a8ab/config/application.rb#L279-L294:[`/usr/share/foreman/config/application.rb` under `Foreman::Logging.add_loggers`].
endif::[]

`app`::
Logs web requests and all general application messages.
+
Default value: true.

`audit`::
Logs additional fact statistics, numbers of added, updated, and removed facts.
+
Default value: true.

`background`::
Logs information from the background processing component.

`blob`::
Logs contents of rendered templates for auditing purposes.
+
[IMPORTANT]
====
The `blob` logger might contain sensitive data.
====

`dynflow`::
Logs information from the Dynflow process.

`ldap`::
Logs high level LDAP queries and LDAP operations.
+
Default value: false.

`notifications`::
Logs information from the notifications component.

`permissions`::
Logs queries to user roles, filters, and permissions when loading pages.
+
Default value: false.

`sql`::
Logs SQL queries made through Rails ActiveRecord.
+
Default value: false.

`telemetry`::
Logs debugging information from telemetry.

`templates`::
Logs information from the template renderer component.
