:_mod-docs-content-type: REFERENCE

[id="useful-search-examples"]
= Useful search examples

[role="_abstract"]
The following examples demonstrate useful ways to filter and find resources in {ProjectWebUI}.
Use them as starting points to build your own searches that match your specific needs.

These search examples show how to filter hosts and are based on host attribute search parameters.
You can use them on {ProjectWebUI} pages that list hosts, such as *Hosts* > *All Hosts*.
You can apply the same syntax to filter other resources on other {ProjectWebUI} pages.

Find hosts by host global status and sub-status::
Hosts that have an *OK* global status:
+
[options="nowrap" subs="+quotes"]
----
global_status = ok
----
+
Hosts that have an *Error* or *Warning* global status:
+
[options="nowrap" subs="+quotes"]
----
global_status = error or global_status = warning
----
+
Hosts that have at least one pending resource:
+
[options="nowrap" subs="+quotes"]
----
status.pending > 0
----
+
Hosts that restarted some service during last run:
+
[options="nowrap" subs="+quotes"]
----
status.restarted > 0
----
+
Hosts that have an interesting last run that might indicate something has happened:
+
[options="nowrap" subs="+quotes"]
----
status.interesting = true
----

Find hosts that need attention::
Hosts with security updates available:
+
[options="nowrap", subs="+quotes,attributes"]
----
errata_status = security_needed
----
+
Hosts that have email notifications for configuration errors enabled and are in a failed state:
+
[options="nowrap", subs="+quotes,attributes"]
----
status.enabled = true AND status.failed = true
----
+
Hosts that have not generated a report recently:
+
[options="nowrap", subs="+quotes,attributes"]
----
last_report < "7 days ago"
----

Find hosts by configuration, environment, or registration date::
Hosts in production that belong to a host group whose name includes a variation of the word "webservers":
+
[options="nowrap", subs="+quotes,attributes"]
----
environment = production AND hostgroup ~ webservers
----
+
Hosts registered in the last month:
+
[options="nowrap", subs="+quotes,attributes"]
----
registered_at > "30 days ago"
----
+
Hosts registered between specific dates:
+
[options="nowrap", subs="+quotes,attributes"]
----
registered_at > 1-January-2026 AND registered_at < 31-January-2026
----

Exclude specific results::
+
All hosts except hosts in a host group named "exceptions":
+
[options="nowrap", subs="+quotes,attributes"]
----
NOT hostgroup = exceptions
----
+
Hosts that are not compliant with policies:
+
[options="nowrap", subs="+quotes,attributes"]
----
compliance_status != "compliant"
----

Use wildcards for flexible matching::
+
Hosts with names that include the strings "web" and "prod":
+
[options="nowrap", subs="+quotes,attributes"]
----
name ~ web*prod*
----
+
Host groups starting with a specific prefix:
+
[options="nowrap", subs="+quotes,attributes"]
----
hostgroup ~ rhel%
----
