:_mod-docs-content-type: REFERENCE

[id="configuring-logging-type-and-layout_{context}"]
= Configuring logging type and layout

[role="_abstract"]
By default, {Project} uses file-based logging.
You can use `{foreman-installer}` to change the logging type and logging layout.

Configuring logging with journal::
Enter the following `{foreman-installer}` command to configure logging to the `journald` service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--foreman-logging-type journald \
--foreman-proxy-log JOURNAL
----
To inspect the log messages, use the `journalctl` utility.
For example:
+
* `journalctl --unit foreman` and `journalctl --unit foreman-proxy` show messages for the `foreman` and `foreman-proxy` units
* `journalctl REQUEST=_request_ID_` shows messages for a specified request

Configuring file-based logging::
Enter the following `{foreman-installer}` command to configure file-based logging:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--reset-foreman-logging-type \
--reset-foreman-proxy-log
----
To inspect the log messages, view these files:
+
* `/var/log/foreman/production.log`
* `/var/log/foreman-proxy.log`

Procedure for configuring logging to JSON output::
On your {ProjectServer}, enable logging to JSON output for `{foreman-installer}`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} \
--foreman-logging-layout json \
--foreman-logging-type file
----
To inspect the log messages, use `jq`:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cat /var/log/foreman/production.log | jq
----
ifdef::satellite[]

.Additional resources
* {RHELDocsBaseURL}9/html-single/configuring_basic_system_settings/index#viewing-logs-using-the-command-line_assembly_troubleshooting-problems-using-log-files[Viewing logs using the command line in _{RHEL}{nbsp}9 Configuring basic system settings_]
endif::[]
