[id="capsule-ports-and-firewalls-requirements_{context}"]
= Ports and Firewalls Requirements

For the components of {Project} architecture to communicate, ensure that the required network ports are open and free on the base operating system.
You must also ensure that the required network ports are open on any network-based firewalls.

The installation of a {SmartProxyServer} fails if the ports between {ProjectServer} and {SmartProxyServer} are not open before installation starts.

Use this information to configure any network-based firewalls.
Note that some cloud solutions must be specifically configured to allow communications between machines because they isolate machines similarly to network-based firewalls.
If you use an application-based firewall, ensure that the application-based firewall permits all applications that are listed in the tables and known to your firewall.
If possible, disable the application checking and allow open port communication based on the protocol.

.Integrated {SmartProxy}
{ProjectServer} has an integrated {SmartProxy} and any host that is directly connected to {ProjectServer} is a Client of {Project} in the context of this section.
This includes the base operating system on which {SmartProxyServer} is running.

.Clients of {SmartProxy}
Hosts which are clients of {SmartProxies}, other than {Project}'s integrated {SmartProxy}, do not need access to {ProjectServer}.
For more information on {Project} Topology, see {PlanningDocURL}sect-Documentation-Architecture_Guide-Capsule_Networking[{SmartProxy} Networking] in _Planning for {ProjectNameX}_.

Required ports can change based on your configuration.

ifdef::katello,satellite,orcharhino[]
A matrix table of ports is available in the Red{nbsp}Hat Knowledgebase solution https://access.redhat.com/solutions/5627751[Red Hat Satellite List of Network Ports].
endif::[]

The following tables indicate the destination port and the direction of network traffic:

.{SmartProxy} incoming traffic
[cols="15%,15%,15%,15%,20%,20%",options="header"]
|====
| Destination Port | Protocol | Service |Source| Required For | Function
| 67 | UDP | DHCP | Client | PXE Boot | DHCP
| 69 | UDP | TFTP | Client | TFTP Server |
ifdef::katello,satellite,orcharhino[]
 .3+| 80 .3+| TCP .3+| HTTP .3+| Client | Content Host registration | {SmartProxy} CA RPM registration
                                        | PXEBoot | Installation
                                        | Package Installation | yum execution
endif::[]
 .3+| 443, 80 .3+| TCP .3+| HTTPS, HTTP .3+| Client | Content Host Registration | {SmartProxy} CA RPM installation
                                                    | PXE Boot | Installation
                                                    | Package installation | yum extension
 .6+| 443 .6+| TCP .6+| HTTPS .5+| {Smartproxy} | {SmartProxy} registration |  Installation/ removal/ update
                                                | Power management | iPXE chained template retrieval
                                                | Telemetry data upload | Send data to Red{nbsp}Hat portal
                                                | OpenSCAP | Configure Client
                                                | Remote Execution Upload |
                                                | {ProjectServer}|Content Mirroring | Initiation
//ifdef::katello,satellite,orcharhino[]
| 5647 (optional) | TCP | AMQP | Client | goferd message bus | Forward message to client

Katello agent to communicate with Qpid dispatcher
| 8000 | TCP | HTTPS | Client | Bootdisk | iPXE chained template retrieval
| 8140 | TCP | HTTPS | Client | Puppet |
| 8443 | TCP | HTTPS | Client | Content Host registration | Initiation

Uploading facts

Sending installed packages and traces
 .5+| 9090 .5+| TCP .5+| HTTPS | Discovered Node|Discovery |Host discovery and provisioning
 .4+| {ProjectServer} | Provisioning | {SmartProxy} API requirement to configure TFTP, DHCP and others
                      | Remote execution | Run job on VM
                      | {SmartProxy} feature retrieval |
                      | OpenSCAP | View SCAP report in HTML or XML format
endif::[]
|====

Any managed host that is directly connected to {ProjectServer} is a client in this context because it is a client of the integrated {SmartProxy}.
This includes the base operating system on which a {SmartProxyServer} is running.

A DHCP {SmartProxy} performs ICMP ping and TCP echo connection attempts to hosts in subnets with DHCP IPAM set to find out if an IP address considered for use is free.
This behavior can be turned off using `{foreman-installer} --foreman-proxy-dhcp-ping-free-ip=false`.

.{SmartProxy} outgoing traffic
[cols="15%,15%,15%,15%,20%,20%",options="header"]

|====
| Destination Port | Protocol | Service |Source| Required For | Function
| 7 | ICMP and UDP | ECHO | {ProjectServer} | DHCP | {SmartProxy} API requirement to configure TFTP, DHCP and others
| 22 | TCP | SSH | Target host | Remote execution |Run job on  VM proxied through {SmartProxy}
| 53 | TCP and UDP | DNS | DNS Server | {SmartProxy} registration | DNS records
 .8+| 443 .8+| TCP .8+| HTTPS .8+| {SmartProxy} | {SmartProxy} registration | (smart host, {SmartProxy})

                                                 Content Mirroring

                                                 Forward Request to {Project}

                                                 External Node Classification

                                                 Run Report

                                                 Template retrieval
                                                 | Power Management | iPXE chained template retrieval
                                                 | goferd message bus | Send report to {ProjectServer}

                                                Initiation
                                                 | Telemetry Data Upload | Send data to Red{nbsp}Hat Portal
                                                 | OpenSCAP | Send report from {SmartProxy} to {Project}
                                                 | Content promotion | Initiation
                                                 | Content Sync | Initiation

Red{nbsp}Hat CDN
                                                 | Remote Execution result upload |
| 623 |  |  | Client | Power management | BMC On/Off/Cycle/Status
ifdef::katello,satellite,orcharhino[]
| 5646 | TCP | AMQP | {ProjectServer} | Power management for Katello agent | Forward message to Qpid dispatch router on {SmartProxy}
endif::[]
| 7911 | TCP | DHCP, OMAPI | DHCP Server| DHCP | The DHCP target is configured using `--foreman-proxy-dhcp-server` and defaults to localhost

ISC and `remote_isc` use a configurable port that defaults to 7911 and uses OMAPI

Infoblox always uses port 443 and HTTPS
ifdef::katello,satellite,orcharhino[]
 .2+| 8443 .2+| TCP .2+| HTTPS | Discovered Node|Power management | {SmartProxy} sends reboot command to the discovered host
                               | cert-api.access.redhat.com |Telemetry data upload and report | Send and read data to and from the Red{nbsp}Hat portal
endif::[]
|====

NOTE: A DHCP {SmartProxy} sends an ICMP ECHO to confirm an IP address is free, *no response* of any kind is expected.
ICMP can be dropped by a networked-based firewall, but *any* response prevents the allocation of IP addresses.
