:_mod-docs-content-type: REFERENCE

[id="additional-deployment-tasks_{context}"]
= Additional deployment tasks

[role="_abstract"]
{Project} offers a range of additional capabilities that you can use to further enhance your {Project} deployment.

Remote execution commands on hosts::
With remote execution, you can perform various tasks on multiple hosts simultaneously.
{Project} supports the following modes of transport for remote execution: pull-based mode (over MQTT/HTTPS) and push-based mode (over SSH).
+
For more information, see {ManagingHostsDocURL}configuring-and-setting-up-remote-jobs[Configuring and setting up remote jobs] in _{ManagingHostsDocTitle}_.

Automating tasks with a configuration management tool::
By integrating {Project} with a configuration management tool, you can automate repetitive tasks and ensure consistent configuration of your hosts.
+
ifndef::satellite[]
You can use Ansible to configure hosts.
endif::[]
For more information on using Ansible with {Project}, see {ManagingConfigurationsAnsibleDocURL}[_{ManagingConfigurationsAnsibleDocTitle}_].
+
You can use Puppet to configure hosts.
For more information on using Puppet with {Project}, see {ManagingConfigurationsPuppetDocURL}[_{ManagingConfigurationsPuppetDocTitle}_].
+
ifndef::foreman-deb,satellite[]
You can use Salt to configure hosts.
For more information on using Salt with {Project}, see {ManagingConfigurationsSaltDocURL}[_{ManagingConfigurationsSaltDocTitle}_].
endif::[]

Security management with OpenSCAP::
ifndef::satellite[]
You can enable the OpenSCAP plugin on your {ProjectServer} and any {SmartProxyServers}.
endif::[]
With OpenSCAP, you can manage compliance policies and run security compliance scans on your hosts.
After the scan completes, a compliance report is uploaded to your {ProjectServer}.
+
For more information, see {ManagingSecurityDocURL}[_{ManagingSecurityDocTitle}_].

Load balancing::
With load balancing configured on your {SmartProxyServers}, you can improve performance on {SmartProxyServers} while also improving performance and stability for host connections to {Project}.
+
For more information, see {ConfiguringLoadBalancerDocURL}[_{ConfiguringLoadBalancerDocTitle}_].

ifdef::satellite,orcharhino[]
Incident management with {Insights}::
With {Insights} enabled on your {ProjectServer}, you can identify key risks to stability, security, and performance.
+
For more information, see {InstallingServerDocURL}performing-additional-configuration-on-server_{project-context}[Performing additional configuration on {ProjectServer}] in _{InstallingServerDocTitle}_.
endif::[]
