[id="example-playbooks-based-on-modules-from-{project-context}-ansible-collection"]
= Example playbooks based on modules from {Project} Ansible Collection

All playbooks based on modules from {Project} Ansible Collection must include parameters detailing how to connect to the {Project} API.
The following examples use Ansible vault and module defaults group to provide these parameters, and they authenticate using a username and password.
For more information, see xref:creating-a-playbook-with-modules-from-{project-context}-ansible-collection[].

.Example Ansible playbook: Enable repositories and create a content view
====
This example playbook uses the following modules:

* `{ansible-namespace}.repository_set`
* `{ansible-namespace}.content_view`

The playbook ensures repositories are enabled and a content view that contains these repositories exists.

[options="nowrap" subs="+quotes,attributes"]
----
- name: Ensure RHEL 10 repositories are enabled and a content view exists
  hosts: localhost
  vars_files:
    - _My_Vault.yml_
  module_defaults:
    group/{ansible-module-defaults-group}:
      username: "{{ _My_Username_ }}"
      password: "{{ _My_Password_ }}"
      server_url: "{{ _My_Server_URL_ }}"
  tasks:
    - name: Ensure RHEL 10 repositories are enabled
      {ansible-namespace}.repository_set:
        name: "Red Hat Enterprise Linux 10 for x86_64 - BaseOS (RPMs)"
        organization: "Default Organization"
        product: "Red Hat Enterprise Linux for x86_64"
        repositories:
        - releasever: "10"
          basearch: "x86_64"
        state: enabled
      {ansible-namespace}.repository_set:
        name: "Red Hat Enterprise Linux 10 for x86_64 - AppStream (RPMs)"
        organization: "Default Organization"
        product: "Red Hat Enterprise Linux for x86_64"
        repositories:
        - releasever: "10"
          basearch: "x86_64"
        state: enabled

    - name: Sync RHEL 10 repositories
      {ansible-namespace}.repository_sync:
        repository: "Red Hat Enterprise Linux 10 for x86_64 - BaseOS RPMs 10"
        product: "Red Hat Enterprise Linux for x86_64"
        organization: "Default Organization"
      {ansible-namespace}.repository_sync:
        repository: "Red Hat Enterprise Linux 10 for x86_64 - AppStream RPMs 10"
        product: "Red Hat Enterprise Linux for x86_64"
        organization: "Default Organization"

    - name: Ensure a content view for RHEL 10 repositories exists
      {ansible-namespace}.content_view:
        name: "RHEL 10 content view"
        organization: "Default Organization"
        repositories:
          - name: "Red Hat Enterprise Linux 10 for x86_64 - BaseOS RPMs 10"
            product: "Red Hat Enterprise Linux for x86_64"
          - name: "Red Hat Enterprise Linux 10 for x86_64 - AppStream RPMs 10"
            product: "Red Hat Enterprise Linux for x86_64"
----

For more information, see the Ansible module documentation with the following commands:

* `ansible-doc {ansible-namespace}.repository_set`
* `ansible-doc {ansible-namespace}.content_view`
====

.Example Ansible playbook: Synchronize repositories and publish a content view
====
This example playbook uses the following modules:

* `{ansible-namespace}.repository_sync`
* `{ansible-namespace}.content_view_version`

The playbook synchronizes repositories and publishes the content view that includes them.

[options="nowrap" subs="+quotes,attributes"]
----
- name: Ensure RHEL 10 repositories are synced and content view is published
  hosts: localhost
  vars_files:
    - _My_Vault.yml_
  module_defaults:
    group/{ansible-module-defaults-group}:
      username: "{{ _My_Username_ }}"
      password: "{{ _My_Password_ }}"
      server_url: "{{ _My_Server_URL_ }}"
  tasks:
    - name: Sync RHEL 10 repositories
      {ansible-namespace}.repository_sync:
        repository: "Red Hat Enterprise Linux 10 for x86_64 - BaseOS RPMs 10"
        product: "Red Hat Enterprise Linux for x86_64"
        organization: "Default Organization"
      {ansible-namespace}.repository_sync:
        repository: "Red Hat Enterprise Linux 10 for x86_64 - AppStream RPMs 10"
        product: "Red Hat Enterprise Linux for x86_64"
        organization: "Default Organization"

    - name: Publish RHEL 10 content view
      {ansible-namespace}.content_view_version:
        content_view: "RHEL 10 content view"
        organization: "Default Organization"
----

For more information, see the Ansible module documentation with the following commands:

* `ansible-doc {ansible-namespace}.repository_set`
* `ansible-doc {ansible-namespace}.repository_sync`
* `ansible-doc {ansible-namespace}.content_view_version`
====

//.Example Ansible playbook: <Add example name>
//====
//This example playbook uses the following modules:
//
//* `{ansible-namespace}.<module_name>`
//* `{ansible-namespace}.<module_name>`
//
// The playbook ensures that <describe the expected result of the playbook>.
//
//[options="nowrap" subs="+quotes,attributes"]
//----
//- name: <Playbook name>
//  hosts: localhost
//  vars_files:
//    - _My_Vault.yml_
//  module_defaults:
//    group/{ansible-module-defaults-group}:
//      username: "{{ _My_Username_ }}"
//      password: "{{ _My_Password_ }}"
//      server_url: "{{ _My_Server_URL_ }}"
//  tasks:
//    - name: Task name
//      {ansible-namespace}.<module_name>:
//----
//
//For more information, see the Ansible module documentation with the following commands:
//
//* `ansible-doc {ansible-namespace}.<module_name>`.
//* `ansible-doc {ansible-namespace}.<module_name>`.
//====
//
.Additional resources
* Use the `ansible-doc --list {ansible-namespace}` command to display the {Project} Ansible modules installed on your system.
ifndef::orcharhino[]
* See {ansible-galaxy}[{ansible-galaxy-name}] for a complete list of {Project} Ansible modules and other related information.
endif::[]
