[id="supported-operating-systems_{context}"]
= Supported Operating Systems

ifdef::satellite[]
You can install the operating system from a disc, local ISO image, kickstart, or any other method that Red{nbsp}Hat supports.
Red{nbsp}Hat {ProductName} is supported on the latest versions of {RHEL} 8, and {RHEL} 7 Server that are available at the time when {ProductName} is installed.
Previous versions of {RHEL} including EUS or z-stream are not supported.
endif::[]

ifdef::foreman-el,foreman-deb,katello[]
You can install the operating system from a disc, local ISO image, or kickstart.
endif::[]

The following operating systems are supported by the installer, have packages, and are tested for deploying {Project}:

.Operating Systems supported by {foreman-installer}
|====
| Operating System | Architecture | Notes
ifdef::foreman-el,katello,orcharhino[]
| {EL} 8 | x86_64 only | EPEL is not supported.
endif::[]
ifdef::satellite[]
| {RHEL} 8 | x86_64 only |
| {RHEL} 7 | x86_64 only |
endif::[]
ifdef::foreman-deb[]
| Debian 11 (Bullseye) | amd64 |
| Ubuntu 20.04 (Focal) | amd64 |
endif::[]
|====

Before you install {Project}, apply all operating system updates if possible.

ifdef::satellite[]
Red{nbsp}Hat {ProductName} requires a {RHEL} installation with the `@Base` package group with no other package-set modifications, and without third-party configurations or software not directly necessary for the direct operation of the server.
This restriction includes hardening and other non-Red{nbsp}Hat security software.
If you require such software in your infrastructure, install and verify a complete working {ProductName} first, then create a backup of the system before adding any non-Red{nbsp}Hat software.
endif::[]

Install {ProductName} on a freshly provisioned system.

ifdef::satellite[]

ifeval::["{context}" == "{smart-proxy-context}"]
Do not register {SmartProxyServer} to the Red{nbsp}Hat Content Delivery Network (CDN).
endif::[]

Red{nbsp}Hat does not support using the system for anything other than running {ProductName}.
endif::[]
