:_mod-docs-content-type: REFERENCE

[id="efficiency-tips-for-web-ui"]
= Efficiency tips for {ProjectWebUI}

[role="_abstract"]
Use these keyboard shortcuts and techniques to navigate and search more efficiently in the {ProjectWebUI}.

`Ctrl + Shift + F` focuses the vertical navigation search bar::
After pressing this shortcut, you can start typing in the vertical navigation search bar.

`/` focuses the page search bar::
After pressing this shortcut, you can start typing in the page search bar.

Saving searches as bookmarks::
You can save a search you frequently use as a bookmark.
After entering your search query in the search field, click the arrow next to the *Search* button to select *Bookmark this search*.
You can then give the bookmark a name and choose whether to make it public or private.
+
To manage all bookmarks, navigate to *Administer* > *Bookmarks*.

Compact table mode::
Navigate to the user menu in the top bar and select *My account*.
Under the *UI Preferences* tab, you can enable compact table mode.
With compact table mode enabled, {ProjectWebUI} displays table rows with less space between items.
