[id="customizing-ansible-configuration_{context}"]
= Customizing Ansible Configuration

{Project} manages essential Ansible configuration that is required for Ansible integration with {Project}.
However, you can customize other Ansible configuration options as usual.

{Project} stores the essential Ansible configuration as environment variables in `/etc/foreman-proxy/ansible.env`.
This file is managed by the {foreman-installer}.

Ansible reads configuration from `/etc/ansible/ansible.cfg` and the environment provided by {SmartProxy}.
If you need to customize Ansible configuration, you can do so in the `/etc/ansible/ansible.cfg` file.

Note that environment variables take precedence over values in `ansible.cfg`, which ensures that the essential configuration required by {Project} is retained.

The following table lists the essential Ansible configuration options managed by {Project}.

.Essential Ansible Configuration
[options="header",cols="1,1,2"]
|====
| Environment Variable | Config Key | Description
| ANSIBLE_CALLBACK_WHITELIST | callback_whitelist | Enables callback to {Project}; equivalent to `callbacks_enabled` for cross-version compatibility
| ANSIBLE_CALLBACKS_ENABLED | callbacks_enabled | Enables callback to {Project}; equivalent to `callback_whitelist` for cross-version compatibility
| ANSIBLE_COLLECTIONS_PATHS | collections_paths | List of paths to Ansible collections
| ANSIBLE_LOCAL_TEMP | local_tmp | Temporary directory on {SmartProxy}
| ANSIBLE_HOST_KEY_CHECKING | host_key_checking | Disables checking of host keys during SSH connection
| ANSIBLE_ROLES_PATH | roles_path | List of paths to Ansible roles
| ANSIBLE_SSH_ARGS | ssh_args | Arguments passed to SSH connection
|====

.Additional resources
* https://docs.ansible.com/ansible/latest/reference_appendices/config.html[Ansible Configuration Settings]
