:_mod-docs-content-type: REFERENCE

[id="retrieving-archived-metrics_{context}"]
= Retrieving archived metrics

[role="_abstract"]
Use these commands to analyze historical performance data from PCP archive files, including viewing specific metrics over time ranges, comparing time periods, and investigating past performance issues on your {Project}.

* List all metrics that were enabled when the archive file was created:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# pminfo --archive _archive_file_
----
* View the host and time period covered by an archive file:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# pmdumplog -l _archive_file_
----
* List disk writes for each partition, over the time period covered by the archive file:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# pmrep -a /var/log/pcp/pmlogger/_{foreman-example-com}_/_20230831.00.10_ \
  disk.partitions.write
----
* List disk write operations per partition, with a 2-second interval, over the time period between 14:00 and 14:15:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# pmrep -a /var/log/pcp/pmlogger/_{foreman-example-com}_/_20230831.00.10_ \
  -t 2sec \
  -S @14:00 -T @14:15 \
  disk.partitions.write
----
* List average values of all performance metrics, including the time and value of the minimum/maximum, over the time period between 14:00 and 14:30, and format the values as a table:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# pmlogsummary /var/log/pcp/pmlogger/_{foreman-example-com}_/_20230831.00.10_ \
  -HlfiImM \
  -S @14:00 \
  -T @14:30 \
  disk.partitions.write \
  mem.freemem
----
* Display system metrics stored in an archive, starting from 14:00, in an interactive manner similar to the `top` tool:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# pcp --archive /var/log/pcp/pmlogger/_{foreman-example-com}_/_20230831.00.10_ \
  -S @14:00 \
  atop
----
