:_mod-docs-content-type: REFERENCE

[id="subscriptions-tracking-configuration"]
= Subscriptions tracking configuration

[role="_abstract"]
For successful tracking of your subscriptions usage, you have to perform the following configuration tasks.

In both connected and disconnected scenarios, perform the following task:

* Set the system purpose for hosts in {Project}.

In the connected scenarios, also perform the following tasks:

* If you use a hypervisor with virtual machines, configure virt-who on {ProjectServer}.
* Configure inventory upload in {Project} and install the Insights client on hosts.
* Activate the Subscriptions service in the {RHCloud} if needed.

.Additional resources
ifdef::katello,satellite,red_hat_enterprise_linux[]
* {ManagingHostsDocURL}editing-the-system-purpose-of-a-host-by-using-web-ui[Editing the system purpose of a host by using {ProjectWebUI} in _{ManagingHostsDocTitle}_]
endif::[]
* {ManagingHostsDocURL}monitoring-hosts-by-using-{insights-id}-in-cloud[Monitoring hosts by using {Insights} in {RHCloud} in _{ManagingHostsDocTitle}_]
* {RHDocsBaseURL}subscription_central/1-latest/html/getting_started_with_the_subscriptions_service[Activating and opening the subscriptions service in _Getting Started with the Subscriptions Service_]
* xref:expense-management-for-red-hat-subscriptions[]
ifndef::orcharhino[]
* {ConfiguringVMSubscriptionsDocURL}[_{ConfiguringVMSubscriptionsDocTitle}_]
endif::[]
* {ManagingHostsDocURL}monitoring-hosts-by-using-red-hat-lightspeed-in-cloud[Monitoring hosts by using {Insights} in {RHCloud} in _{ManagingHostsDocTitle}_]
* {RHDocsBaseURL}subscription_central/1-latest/html/getting_started_with_the_subscriptions_service[Activating and opening the subscriptions service in _Getting Started with the Subscriptions Service_]
