:_mod-docs-content-type: REFERENCE

[id="ipv6-and-ipv4-requirements"]
= IPv6 and IPv4 requirements

You can install {Project} in an IPv4 network or in an IPv6 network.
ifdef::satellite[]
Dual-stack {Project} installations that use both IPv4 and IPv6 are not supported.
endif::[]

The following requirements apply to installations in an IPv4 network:

* Ensure an IPv6 loopback is configured on the base system.
The loopback is typically configured by default.
Do not disable it.
Using the `ipv6.disable=1` kernel parameter or the `net.ipv6.conf.lo.disable_ipv6 = 1` sysctl option will break the installation.

The following requirements apply to installations in an IPv6 network:

ifdef::satellite[]
* Deploy an external HTTP proxy server that supports both IPv4 and IPv6.
This is required because Red Hat Content Delivery Network distributes content only over IPv4 networks, therefore you must use this HTTP proxy to pull content into the {Project} on your IPv6 network.
You must configure {Project} to use this dual-stack (supporting both IPv4 and IPv6) HTTP proxy as the default HTTP proxy.
endif::[]
ifndef::foreman-deb,foreman-el,satellite[]
* If you rely on content from IPv4-only networks, use an external dual-stack HTTP proxy.
Configure {Project} to use this dual-stack (supporting both IPv4 and IPv6) HTTP proxy as the default HTTP proxy.
endif::[]
ifdef::katello,orcharhino,satellite[]
* {Project} does not support configuring an HTTP proxy using a direct IPv6 address.
Instead, configure the HTTP proxy with a FQDN that resolves to the IPv6 address.
endif::[]

If you intend to provision hosts in an IPv6 network, the following requirements also apply:

* Deploy an external DHCPv6 server and configure it manually to communicate with the network boot process and to manage IP address assignment because {Project} cannot integrate with a DHCPv6 server and manage its configuration.
For more information about DHCPv6 server configuration, see {ProvisioningDocURL}options-in-unmanaged-dhcpv6[Options in unmanaged DHCPv6] in _{ProvisioningDocTitle}_.
ifndef::installer-foremanctl[]
* Configure {Project} for UEFI HTTP boot provisioning.
Although {Project} provisioning templates include IPv6 support for PXE and HTTP (iPXE) provisioning, the UEFI HTTP Boot provisioning is the only tested and certified provisioning workflow.
For more information, see xref:configuring-for-uefi-http-boot-provisioning-in-an-ipv6-network_{context}[].
endif::[]

.Additional resources
ifdef::satellite[]
* link:https://access.redhat.com/solutions/5045841[_How do I disable the IPv6 protocol on Red Hat Satellite and/or Red Hat Capsule server?_ in Red Hat Knowledgebase]
endif::[]
ifndef::installer-foremanctl[]
* xref:adding-a-default-http-proxy_{context}[]
endif::[]
