[id="capsule-ports-and-firewalls-requirements_{context}"]
= Ports and Firewalls Requirements

For the components of {Project} architecture to communicate, ensure that the required network ports are open and free on the base operating system.
You must also ensure that the required network ports are open on any network-based firewalls.

The installation of a {SmartProxyServer} fails if the ports between {ProjectServer} and {SmartProxyServer} are not open before installation starts.

Use this information to configure any network-based firewalls.
Note that some cloud solutions must be specifically configured to allow communications between machines because they isolate machines similarly to network-based firewalls.
If you use an application-based firewall, ensure that the application-based firewall permits all applications that are listed in the tables and known to your firewall.
If possible, disable the application checking and allow open port communication based on the protocol.

.Integrated {SmartProxy}
{ProjectServer} has an integrated {SmartProxy} and any host that is directly connected to {ProjectServer} is a Client of {Project} in the context of this section.
This includes the base operating system on which {SmartProxyServer} is running.

.Clients of {SmartProxy}
Hosts which are clients of {SmartProxies}, other than {Project}'s integrated {SmartProxy}, do not need access to {ProjectServer}.
For more information on {Project} Topology, see {PlanningDocURL}sect-Documentation-Architecture_Guide-Capsule_Networking[{SmartProxy} Networking] in _Planning for {ProjectNameX}_.

Required ports can change based on your configuration.

ifdef::katello,satellite,orcharhino[]
A matrix table of ports is available in the Red{nbsp}Hat Knowledgebase solution https://access.redhat.com/solutions/5627751[Red Hat Satellite List of Network Ports].
endif::[]

The following tables indicate the destination port and the direction of network traffic:

.{SmartProxy} incoming traffic
[cols="15%,15%,15%,15%,20%,20%",options="header"]
|====
| Destination Port | Protocol | Service |Source| Required For | Function
| 53 | TCP and UDP | DNS | DNS Servers and clients | Name resolution | DNS (optional)
| 67 | UDP | DHCP | Client | Dynamic IP | DHCP (optional)
| 69 | UDP | TFTP | Client | TFTP Server (optional) |
ifdef::katello,satellite,orcharhino[]
| 80 | TCP | HTTP | Client | Content Retrieval | Content
| 443, 80 | TCP | HTTPS, HTTP | Client | Content Host Registration | {SmartProxy} CA RPM installation
| 443, 80 | TCP | HTTPS, HTTP | Client | Package installation | yum extension
endif::[]
| 443 | TCP | HTTPS | {ProjectServer} |Content Mirroring | Management
| 443 | TCP | HTTPS | {ProjectName} | {SmartProxy} API | Smart Proxy functionality
| 5647 | TCP | AMQP | Client | goferd message bus | Forward message to client (optional)

Katello agent to communicate with Qpid dispatcher
| 8000 | TCP | HTTPS | Client | Provisioning Templates | Template retrieval for client installers, iPXE or UEFI HTTP Boot
| 8000 | TCP | HTTPS | Client | PXE Boot | Installation
| 8140 | TCP | HTTPS | Client | Puppet |
| 8443 | TCP | HTTPS | Client | Content Host registration | Initiation

Uploading facts

Sending installed packages and traces
ifdef::katello,satellite,orcharhino[]
| 8443 | TCP | HTTPS | Client | OpenSCAP | Configure Client
endif::[]
| 9090 | TCP | HTTPS | Client | OpenSCAP | Configure Client
| 9090 | TCP | HTTPS | Discovered Node|Discovery |Host discovery and provisioning
| 9090 | TCP | HTTPS | {ProjectName} | {SmartProxy} API | {SmartProxy} functionality
|====

Any managed host that is directly connected to {ProjectServer} is a client in this context because it is a client of the integrated {SmartProxy}.
This includes the base operating system on which a {SmartProxyServer} is running.

A DHCP {SmartProxy} performs ICMP ping and TCP echo connection attempts to hosts in subnets with DHCP IPAM set to find out if an IP address considered for use is free.
This behavior can be turned off using `{foreman-installer} --foreman-proxy-dhcp-ping-free-ip=false`.

.{SmartProxy} outgoing traffic
[cols="15%,15%,15%,15%,20%,20%",options="header"]

|====
| Destination Port | Protocol | Service |Source| Required For | Function
| 7 | ICMP | ping  | {ProjectServer} | DHCP | Free IP checking
|- (optional) | TCP | echo | {ProjectServer} | DHCP | Free IP checking
| 22 | TCP | SSH | Target host | Remote execution | Run jobs
| 53 | TCP and UDP | DNS | DNS Server | {SmartProxy} registration | Validation of DNS conflicts
| 443 | TCP | HTTPS | {SmartProxy} | {SmartProxy} registration | (smart host, {SmartProxy})

Content Mirroring

Forward Request to {Project}

External Node Classification

Run Report

Template retrieval
| 443 | TCP | HTTPS | {Project} | Power Management | iPXE chained template retrieval
| 443 | TCP | HTTPS | {Project} | goferd message bus | Send report to {ProjectServer}

Initiation
| 443 | TCP | HTTPS | {Project} | Telemetry Data Upload | Send data to Red{nbsp}Hat Portal
| 443 | TCP | HTTPS | {Project} | OpenSCAP | Send report from {SmartProxy} to {Project}
| 443 | TCP | HTTPS | {Project} | Content promotion | Initiation
| 443 | TCP | HTTPS | {Project} | Content Sync | Initiation
| 443 | TCP | HTTPS | {Project} | Content Sync | Red{nbsp}Hat CDN
| 443 | TCP | HTTPS | {Project}te | Remote Execution result upload |
| 623 |  |  | Client | Power management | BMC On/Off/Cycle/Status
ifdef::katello,satellite,orcharhino[]
| 5646 | TCP | AMQP | {ProjectServer} | Power management for Katello agent | Forward message to Qpid dispatch router on {SmartProxy}
endif::[]
| 7911 | TCP | DHCP, OMAPI | DHCP Server| DHCP | The DHCP target is configured using `--foreman-proxy-dhcp-server` and defaults to localhost

ISC and `remote_isc` use a configurable port that defaults to 7911 and uses OMAPI

Infoblox always uses port 443 and HTTPS
ifdef::katello,satellite,orcharhino[]
| 8443 | TCP | HTTPS | Discovered Node|Power management | {SmartProxy} sends reboot command to the discovered host
| 8443 | TCP | HTTPS | cert-api.access.redhat.com |Telemetry data upload and report | Send and read data to and from the Red{nbsp}Hat portal
endif::[]
|====

NOTE: ICMP to Port 7 UDP and TCP must not be rejected, but can be dropped.
The DHCP {SmartProxy} sends an ECHO REQUEST to the Client network to verify that an IP address is free.
Any response will prevent IP addresses being allocated.
