[id="expiring_rhel_client_support_in_rhel_lifecycle_status_{context}"]
= Expiring {RHEL} Client Support in RHEL Lifecycle Status

{Project} provides multiple mechanisms to display information about upcoming End of Support (EOS) events for your {RHEL} clients.

When either the end of maintenance support or the end of extended lifecycle support approaches in a year, you will see a notification banner in the {ProjectWebUI} if you have hosts with that {EL} version.
The notification provides information about the {EL} version, the number of hosts running that version in your environment, the lifecycle support, and the expiration date.
Along with other information, the {EL} lifecycle column is visible in the report.
For any hosts that are not running {EL}, *Unknown* displays in the *RHEL Lifecycle status* and *Last report* columns.

. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts*.
. Click *Manage columns*.
. Select the  *Content* column to expand it.
. Select *RHEL Lifecycle status*.
. Click *Save* to generate a new column that displays the {EL} lifecycle status.

You can also use the *Search* field to search hosts by `rhel_lifecycle_status`.
It can have the following values:
* `full_support`
* `maintenance_support`
* `approaching_end_of_maintenance`
* `extended_support`
* `approaching_end_of_support`
* `support_ended`

You can also find the {EL} lifecycle status on the *Host status* card on the host details page.
You will see an alert on the host page for each host that runs {EL} with an upcoming End of Support (EOS) event in a year as well as when support has ended.
