:_mod-docs-content-type: REFERENCE

[id="storage-requirements_{context}"]
= Storage requirements

Follow these storage requirements when installing {ProjectServer}:

* Ensure that the directories used by {ProjectServer} have sufficient disk space available:
+
.Storage requirements for a {ProjectServer} installation
[cols="9,3,3",options="header"]
|====
|Directory |Installation Size |Runtime Size

|/var/log |10 MB |10 GB

|{postgresql-lib-dir} |1 GB |20 GB

|/usr | 10 GB | Not Applicable

|/opt/puppetlabs | 500 MB | Not Applicable

ifdef::katello,satellite,orcharhino[]
|/var/lib/pulp |1 MB |300 GB
endif::[]

ifdef::satellite[]
|/var/lib/containers if using {insights-iop} |20 GB |30 GB
endif::[]
|====
+
These values are based on expected use case scenarios and can vary according to individual environments.
ifdef::katello,satellite[]
The runtime size was measured with {EL} 7, 8, and 9 repositories synchronized.
endif::[]
ifdef::katello,orcharhino,satellite[]
* If you mount the `/tmp` directory as a separate file system, use the `exec` mount option in the `/etc/fstab` file.
+
If `/tmp` is already mounted with the `noexec` option, change the option to `exec` and remount the file system.
This is a requirement for the `puppetserver` service to work.
* If you mount the `/var/lib/pulp` directory as an NFS share, specify the SELinux context of the `/var/lib/pulp` directory in the file system table.
Add the following lines to `/etc/fstab`:
+
[source, none, options="nowrap", subs="+quotes,verbatim,attributes"]
----
nfs.example.com:/nfsshare  /var/lib/pulp  nfs  context="system_u:object_r:pulpcore_var_lib_t:s0"  1 2
----
+
If the NFS share is already mounted, remount it using the above configuration and restore the SELinux context:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# restorecon -R /var/lib/pulp
----
+
* Do not use symbolic links for `/var/lib/pulp/`.
endif::[]

ifdef::katello,orcharhino,satellite[]
.Additional resources
* {RHELDocsBaseURL}9/html/managing_storage_devices/disk-partitions_managing-storage-devices[Disk partitions in _{RHEL}{nbsp}9 Managing storage devices_]
endif::[]
