[id="Email_Notification_Types_{context}"]
= Email Notification Types

Events for which you can receive email notifications from {Project} include the following:

* *Audit summary*: A summary of all activity audited by {ProjectServer}.
* *Host built*: A notification sent when a host is built.
* *Host errata advisory*: A summary of applicable and installable errata for hosts managed by the user.
* *Compliance policy summary*: A summary of OpenSCAP policy reports and their results.
* *Promote errata*: A notification sent only after a Content View promotion.
It contains a summary of errata applicable and installable to hosts registered to the promoted Content View.
This allows a user to monitor what updates have been applied to which hosts.
* *Sync errata*: A notification sent only after synchronizing a repository.
It contains a summary of new errata introduced by the synchronization.

For a complete list of notification events, navigate to *Administer* > *Users* in the {ProjectWebUI}, click the *Username* of the required user, and select the *Email Preferences* tab.