[id="Utilities_for_Processing_Log_Information_{context}"]
= Utilities for processing log information

You can collect information from log files to troubleshoot {Project}.

sosreport::
The `sos report` command collects configuration and diagnostic information from a Linux system, such as the running kernel version, loaded modules, running services, and system and service configuration files.
Additionally, it collects information about {ProjectName}, such as its back-end services and tasks.
This output is stored in a tar file located at `/var/tmp/__sosreport-XXX-20171002230919.tar.xz__`.
+
For more information, run `sos report --help` or see
ifdef::satellite[]
https://access.redhat.com/solutions/3592[What is a sosreport and how can I create one?] in the _{Team} Knowledgebase_.
endif::[]
ifndef::satellite[]
https://github.com/sosreport/sos/wiki#for-users[_SOS user documentation_].
endif::[]
+
[IMPORTANT]
====
The `sos report` command removes security information such as passwords, tokens, and keys while collecting information.
However, the tar files can still contain sensitive information about the {ProjectServer}.
Send the tar files directly to the intended recipient and not to a public target.
====

foreman-tail::
The `foreman-tail` command displays {Project} logs in real time.
+
For more information, see the `foreman-tail(8)` man page.
