[id="examples-of-organization-management-in-project"]
= Examples of organization management in {Project}

Single Organization::
A small business with a simple system administration chain.
In this case, you can create a single organization for the business and assign content to it.

Multiple Organizations::
A large company that owns several smaller business units.
For example, a company with separate system administration and software development groups.
In this case, you can create organizations for the company and each of the business units it owns.
This keeps the system infrastructure for each separate.
You can then assign content to each organization based on its needs.

External Organizations::
A company that manages external systems for other organizations.
For example, a company offering cloud computing and web hosting resources to customers.
In this case, you can create an organization for the company's own system infrastructure and then an organization for each external business.
You can then assign content to each organization where necessary.
