:_mod-docs-content-type: REFERENCE

[id="configuring-the-cleaning-unused-tasks-feature"]
= Configuring the cleaning unused tasks feature

[role="_abstract"]
{Project} automatically cleans up old tasks. You can configure the automatic cleaning process according to your needs.

By default, {Project} executes a cron job that cleans tasks every day at 19:45.
{Project} removes the following tasks during the cleaning:

* Tasks that have run successfully and are older than thirty days
* All tasks that are older than a year

You can configure the cleaning unused tasks feature using these options:

* To configure the time at which {Project} runs the cron job, set the `--foreman-plugin-tasks-cron-line` parameter to the time you want in cron format.
For example, to schedule the cron job to run every day at 15:00, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-plugin-tasks-cron-line "00 15 * * *"
----
* To configure the period after which {Project} deletes the tasks, edit the `:rules:` section in the `/etc/foreman/plugins/foreman-tasks.yaml` file.
* To disable regular task cleanup on {Project}, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-plugin-tasks-automatic-cleanup false
----
* To reenable regular task cleanup on {Project}, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-plugin-tasks-automatic-cleanup true
----
