[id="Example_Settings_for_LDAP_Connections_{context}"]
= Example settings for LDAP connections

.Example settings for Active Directory LDAP connections
====
This example uses a dedicated service account called _redhat_ that has bind, read, and search permissions on the user and group entries.

* *Account Username*: DOMAIN\redhat
* *Account password*: P@ssword
* *Base DN*: DC=example,DC=COM
* *Login name attribute*: userPrincipalName
* *First name attribute*: givenName
* *Last name attribute*: sn
* *Email address attribute*: mail
* *Photo attribute*: thumbnailPhoto

The `userPrincipalName` attribute allows the use of whitespace in usernames. The `sAMAccountName` attribute, which provides backwards compatibility with legacy Microsoft systems, does not allow the use of whitespace in usernames.

ifndef::orcharhino[]
For an example configuration, see https://access.redhat.com/solutions/1498773[How to configure Active Directory authentication with TLS on {Project}].
endif::[]
====

.Example settings for {FreeIPA} LDAP connections
====
This example uses a dedicated service account called _redhat_ that has bind, read, and search permissions on the user and group entries.

* *Account Username*: uid=redhat,cn=users,cn=accounts,dc=example,dc=com
* *Base DN*: dc=example,dc=com
* *Groups Base DN*: cn=groups,cn=accounts,dc=example,dc=com
* *Login name attribute*: uid
* *First name attribute*: givenName
* *Last name attribute*: sn
* *Email address attribute*: mail
====

.Example settings for POSIX LDAP connections
====
This example uses a dedicated service account called _redhat_ that has bind, read, and search permissions on the user and group entries.

* *Account Username*: uid=redhat,ou=users,dc=example,dc=com
* *Base DN*: dc=example,dc=com
* *Groups Base DN*: cn=employee,ou=userclass,dc=example,dc=com
* *Login name attribute*: uid
* *First name attribute*: givenName
* *Last name attribute*: sn
* *Email address attribute*: mail
====
