[id="supported-operating-systems_{context}"]

= Supported Operating Systems

You can install the operating system from disc, local ISO image, kickstart, or any other method that Red{nbsp}Hat supports. Red{nbsp}Hat {ProductName} is supported only on the latest versions of Red{nbsp}Hat Enterprise Linux{nbsp}7 Server that is available at the time when {ProductName} {ProductVersion} is installed. Previous versions of Red{nbsp}Hat Enterprise Linux including EUS or z-stream are not supported.

Red{nbsp}Hat {ProductName} requires a Red{nbsp}Hat Enterprise Linux installation with the `@Base` package group with no other package-set modifications, and without third-party configurations or software not directly necessary for the direct operation of the server. This restriction includes hardening and other non-Red{nbsp}Hat security software. If you require such software in your infrastructure, install and verify a complete working {ProductName} first, then create a backup of the system before adding any non-Red{nbsp}Hat software.

Install {ProductName} on a freshly provisioned system.
ifeval::["{context}" == "capsule"]
Do not register {SmartProxyServer} to the Red{nbsp}Hat Content Delivery Network (CDN).
endif::[]
Red{nbsp}Hat does not support using the system for anything other than running {ProductName}.
