:_mod-docs-content-type: REFERENCE

[id="system-requirements"]
= System requirements

The following list shows the most critical requirements common for most scenarios.

ifndef::foremanctl[]
// The requirements in this section must match the full requirements in the installation guide.
ifdef::foreman-deb[]
* The following operating systems are supported for deploying {Project}:
endif::[]
ifndef::foreman-deb[]
* The following operating system is supported for deploying {Project}:
endif::[]
+
ifndef::foreman-deb[]
** {EL} 9 (x86_64)
endif::[]
ifdef::foreman-deb[]
** Debian 12 (Bookworm) (amd64)
** Ubuntu 22.04 (Jammy) (amd64)
endif::[]
ifdef::foreman-el,katello,orcharhino[]
* Installing {Project} on a system with Extra Packages for Enterprise Linux (EPEL) is not supported.
endif::[]
* Install {ProductName} on a freshly provisioned system that serves no other function except to run {ProductName}.
* Ensure the system has at least {project-minimum-cpus} and {project-minimum-memory} of memory.
endif::[]

ifdef::foremanctl[]
ifdef::foreman-deb[]
* The following operating systems are supported for deploying {Project}:
endif::[]
ifndef::foreman-deb[]
* The following operating system is supported for deploying {Project}:
endif::[]
+
ifndef::foreman-deb[]
** {EL} 9 (x86_64)
endif::[]
ifdef::foreman-deb[]
** Debian 12 (Bookworm) (amd64)
** Ubuntu 22.04 (Jammy) (amd64)
endif::[]
* Install {ProductName} on a freshly provisioned system that serves no other function except to run {ProductName}.
* Ensure the system has at least {project-minimum-cpus} and {project-minimum-memory} of memory.
endif::[]
