:_mod-docs-content-type: REFERENCE

[id="prerequisites-for-configuring-{project-context}-with-keycloak-authentication_{context}"]
= Prerequisites for configuring {Project} with {keycloak-wildfly} authentication

[role="_abstract"]
Your {ProjectServer} and {keycloak} server must meet the following requirements before you configure {keycloak-wildfly} authentication.

ifndef::satellite[]
[NOTE]
====
The default {keycloak} distribution is now based on Quarkus.

{keycloak-quarkus} replaces {keycloak-wildfly} in {Project} deployments.
For information about configuring {keycloak-quarkus} authentication, see xref:configuring-sso-and-2fa-with-keycloak-in-project_keycloak-quarkus[].

For information about migrating from {keycloak-wildfly} to {keycloak-quarkus}, see link:https://www.keycloak.org/migration/migrating-to-quarkus[Migrating to Quarkus distribution].
====
endif::[]
ifdef::satellite[]
[NOTE]
====
The {keycloak-wildfly}{nbsp}7 product family has reached End of Full Support.
Use {keycloak-quarkus} instead in your {Project} deployments.
For information about configuring {keycloak-quarkus} authentication, see xref:configuring-sso-and-2fa-with-keycloak-in-project_keycloak-quarkus[].

For information about migrating from {keycloak-wildfly} to {keycloak-quarkus}, see link:https://docs.redhat.com/en/documentation/red_hat_build_of_keycloak/26.0[documentation for {keycloak-quarkus}].
====
endif::[]

On your {ProjectServer}:

* Install the packages required for registering a {keycloak} client:
+
[options="nowrap", subs="verbatim,quotes,attributes"]
----
# {project-package-install} mod_auth_openidc keycloak-httpd-client-install python3-lxml
----
// python3-lxml is only needed on EL9 because of https://redhat.atlassian.net/browse/RHEL-31496

On the {keycloak} side, ensure you meet the following requirements:

* Your {keycloak} server uses HTTPS instead of HTTP.
* If the certificates or the CA are self-signed, they have been added to the end-user certificate truststore.
* Your {keycloak} account has administrative privileges.
* A realm is created on the {keycloak} server for {Project} user accounts, for example `_{Project}_Realm_`.
* User accounts have been imported or added to {keycloak}.
ifndef::orcharhino[]
For more information about importing or creating users, see the https://docs.redhat.com/en/documentation/red_hat_single_sign-on/7.6/html/server_administration_guide/assembly-managing-users_server_administration_guide#proc-creating-user_server_administration_guide[_{RHSSO} Server Administration Guide_].
endif::[]
