[id="Predefined_Roles_Available_in_{project-context}_{context}"]
= Predefined roles available in {Project}

The following table provides an overview of permissions that predefined roles in {Project} grant to a user.

For a complete set of predefined roles and the permissions they grant, log in to {ProjectWebUI} as the privileged user and navigate to *Administer* > *Roles*.
For more information, see xref:Viewing_Permissions_of_a_Role_{context}[].

[cols="3,5,5" options="header"]
|====
|Predefined role |Permissions the role provides |Additional information
|Auditor
|View the Audit log.
|

|Default role
|
ifndef::foreman-deb,foreman-el[]
View tasks and jobs invocations.
endif::[]
ifdef::foreman-deb,foreman-el[]
The permissions this role provides depend on whether the remote execution and tasks plugins are enabled.
endif::[]
|{Project} automatically assigns this role to every user in the system.

|Manager
|View and edit global settings.
|

|Organization admin
|All permissions except permissions for managing organizations.
|An administrator role defined per organization.
The role has no visibility into resources in other organizations.

By cloning this role and assigning an organization, you can delegate administration of that organization to a user.

|Site manager
|View permissions for various items.

Permissions to manage hosts in the infrastructure.
|A restrained version of the Manager role.

|System admin
|Edit global settings in *Administer* > *Settings*.

View, create, edit, and destroy users, user groups, and roles.

View, create, edit, destroy, and assign organizations and locations but not view resources within them.

|Users with this role can create users and assign all roles to them.
Give this role only to trusted users.

|Viewer
|View the configuration of every element of the {Project} structure, logs, reports, and statistics.
|
|====
