:_mod-docs-content-type: REFERENCE

[id="postgresql-as-an-external-database-considerations_{context}"]
= PostgreSQL as an external database considerations

[role="_abstract"]
ifdef::katello,orcharhino,satellite[]
Foreman, Katello, and Candlepin use PostgreSQL.
endif::[]
ifndef::katello,orcharhino,satellite[]
Foreman uses PostgreSQL.
endif::[]
Review the advantages and disadvantages of external PostgreSQL to decide if this option fits your {Project} configuration.

ifdef::foreman-deb[]
{Project} requires PostgreSQL version 13 or later.
{Team} recommends that you use the PostgreSQL version that is part of the default operating system repositories.
endif::[]
ifdef::containerized[]
{Project} supports PostgreSQL version 16, which is available in {EL} 10 repositories.
By default, internal PostgreSQL runs in a Podman container on {ProjectServer}.
An external database runs on a dedicated host that you provision and support separately.
endif::[]
ifndef::foreman-deb,containerized[]
{Project} supports PostgreSQL version 13.
endif::[]

Advantages of external PostgreSQL::
* Increase in free memory and free CPU on {Project}
* Flexibility to set `shared_buffers` on the PostgreSQL database to a high number without the risk of interfering with other services on {Project}
* Flexibility to tune the PostgreSQL server's system without adversely affecting {Project} operations

Disadvantages of external PostgreSQL::
* Increase in deployment complexity that can make troubleshooting more difficult
* The external PostgreSQL server is an additional system to patch and support
* If either {Project} or the PostgreSQL database server suffers a hardware or storage failure, {Project} is not operational
* If there is latency between the {Project} server and database server, performance can suffer

ifdef::satellite[]
If you suspect that the PostgreSQL database on your {Project} is causing performance problems, use the information in https://access.redhat.com/solutions/2780871[Satellite 6: How to enable postgres query logging to detect slow running queries] to determine if you have slow queries.

Queries that take longer than one second are typically caused by performance issues with large installations, and moving to an external database might not help.
If you have slow queries, contact Red Hat Support.
endif::[]
