:_mod-docs-content-type: REFERENCE

[id="prerequisites-for-applying-errata"]
= Prerequisites for applying errata

[role="_abstract"]
Before you apply errata to hosts, ensure the following prerequisites are met.

ifdef::satellite[]
* Synchronize {ProjectName} repositories with the latest errata available from Red{nbsp}Hat.
For more information, see {ContentManagementDocURL}synchronizing-repositories-ad-hoc[Synchronizing repositories ad hoc] in _{ContentManagementDocTitle}_.
endif::[]
* Add errata to the content view assigned to your hosts and publish the content view.
For more information, see {ContentManagementDocURL}making-errata-available-through-content-views[Making errata available through content views] in _{ContentManagementDocTitle}_.
* Ensure errata are *installable* before you apply them to hosts.
Applicable errata update packages on the host, but you can install only errata included in the host's content view version.
If errata are applicable but not installable, create an incremental content view update.
For more information, see {ContentManagementDocURL}adding-errata-to-an-incremental-content-view-by-using-web-ui_content-management[Adding errata to an incremental content view by using {ProjectWebUI}] in _{ContentManagementDocTitle}_.
To control which errata are available in a content view, see {ContentManagementDocURL}creating-a-content-view-filter-for-errata-by-using-web-ui_content-management[Creating a content view filter for errata by using {ProjectWebUI}] in _{ContentManagementDocTitle}_.
* Register the host to an environment and content view on {ProjectServer}.
For more information, see {ManagingHostsDocURL}registering-hosts-by-using-global-registration[Registering hosts by using global registration] in _{ManagingHostsDocTitle}_.
* Configure the host for remote execution.
For more information about running remote execution jobs, see {ManagingHostsDocURL}configuring-and-setting-up-remote-jobs[Configuring and setting up remote jobs] in _{ManagingHostsDocTitle}_.
