You can register hosts with {Project} using the host registration feature in the {ProjectWebUI}, Hammer CLI, or the {Project} API.
For more information, see {ManagingHostsDocURL}Registering_Hosts_managing-hosts[Registering Hosts] in _{ManagingHostsDocTitle}_.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts > Register Host*.
ifeval::["{context}" == "load-balancing"]
. From the *{SmartProxy}* dropdown list, select the load balancer.
. Select *Force* to register a host that has been previously registered to a {SmartProxyServer}.
endif::[]
. Click *Generate* to create the registration command.
. Click on the _files_ icon to copy the command to your clipboard.
. Connect to your host using SSH and run the registration command.
ifdef::satellite[]
. Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifndef::satellite[]
. Ensure that the appropriate repositories have been enabled:
+
ifdef::client-content-dnf[]
* On {EL}: Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifdef::client-content-apt[]
* On Debian: Check the `/etc/apt/sources.list` file and ensure that the appropriate repositories have been enabled.
endif::[]
endif::[]

.CLI procedure
. Generate the host registration command using the Hammer CLI:
+
ifndef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
# hammer host-registration generate-command
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer host-registration generate-command \
--insecure true
----
endif::[]
ifdef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
# hammer host-registration generate-command \
--activation-keys "_My_Activation_Key_"
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer host-registration generate-command \
--activation-keys "_My_Activation_Key_" \
--insecure true
----
endif::[]
ifeval::["{context}" == "load-balancing"]
+
Include the `--smart-proxy-id __{SmartProxy}_ID__` option.
You can use the ID of any {SmartProxyServer} that you configured for host registration load balancing.
{Project} will apply the load balancer to the registration command automatically.
+
Include the `--force` option to register a host that has been previously registered to a {SmartProxyServer}.
endif::[]
. Connect to your host using SSH and run the registration command.
ifdef::satellite[]
. Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifndef::satellite[]
. Ensure that the appropriate repositories have been enabled:
+
ifdef::client-content-dnf[]
* On {EL}: Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifdef::client-content-apt[]
* On Debian: Check the `/etc/apt/sources.list` file and ensure that the appropriate repositories have been enabled.
endif::[]
endif::[]

.API procedure
. Generate the host registration command using the {Project} API:
+
ifndef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
# curl -X POST https://{foreman-example-com}/api/registration_commands \
--user "_My_User_Name_" \
-H 'Content-Type: application/json'
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -X POST https://{foreman-example-com}/api/registration_commands \
--user "_My_User_Name_" \
-H 'Content-Type: application/json' \
-d '{ "registration_command": { "insecure": true }}'
----
endif::[]
ifdef::katello,satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
# curl -X POST https://{foreman-example-com}/api/registration_commands \
--user "_My_User_Name_" \
-H 'Content-Type: application/json' \
-d '{ "registration_command": { "activation_keys": ["_My_Activation_Key_1_, _My_Activation_Key_2_"] }}'
----
+
If your hosts do not trust the SSL certificate of {ProjectServer}, you can disable SSL validation by adding the `--insecure` flag to the registration command.
+
[options="nowrap" subs="+quotes,attributes"]
----
# curl -X POST https://{foreman-example-com}/api/registration_commands \
--user "_My_User_Name_" \
-H 'Content-Type: application/json' \
-d '{ "registration_command": { "activation_keys": ["_My_Activation_Key_1_, _My_Activation_Key_2_"], "insecure": true }}'
----
+
Use an activation key to simplify specifying the environments.
For more information, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in _{ContentManagementDocTitle}_.
endif::[]
ifeval::["{context}" == "load-balancing"]
+
Include `{ "smart_proxy_id": __{SmartProxy}_ID__ }`.
You can use the ID of any {SmartProxyServer} that you configured for host registration load balancing.
{Project} will apply the load balancer to the registration command automatically.
+
Include `{ "force": true }` to register a host that has been previously registered to a {SmartProxyServer}.
endif::[]
+
To enter a password as a command line argument, use `username:password` syntax.
Keep in mind this can save the password in the shell history.
Alternatively, you can use a temporary personal access token instead of a password.
To generate a token in the {ProjectWebUI}, navigate to *My Account* > *Personal Access Tokens*.
. Connect to your host using SSH and run the registration command.
ifdef::satellite[]
. Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifndef::satellite[]
. Ensure that the appropriate repositories have been enabled:
+
ifdef::client-content-dnf[]
* On {EL}: Check the `/etc/yum.repos.d/redhat.repo` file and ensure that the appropriate repositories have been enabled.
endif::[]
ifdef::client-content-apt[]
* On Debian: Check the `/etc/apt/sources.list` file and ensure that the appropriate repositories have been enabled.
endif::[]
endif::[]
