.Prerequisites
ifdef::satellite[]
* Ensure that all {ProjectServer}s are on the same version.
//Major? Minor?
endif::[]
* If you have edited any of the default templates, back up the files either by cloning or exporting them.
** To confirm if a template has been edited, view its *History* before you upgrade.
Alternatively, view the changes in the audit log after you upgrade.
In the {ProjectWebUI}, navigate to *Monitor* > *Audits* and search for the template to see a record of changes made.
** The recommended template backup method is cloning.
Cloning prevents templates from being overwritten in future updates or upgrades.
** If you use the export backup method, restore your changes by comparing the exported template and the default template, and then manually apply your changes.
ifdef::katello,orcharhino,satellite[]
* If you implemented custom certificates, you must retain the content of both the `/root/ssl-build` directory and the directory in which you created any source files associated with your custom
certificates.
+
[WARNING]
====
Failure to retain these files during an upgrade causes the upgrade to fail.
If these files have been deleted, they must be restored from a backup in order for the upgrade to proceed.
====
endif::[]
