. Perform the following post-upgrade tasks to ensure your environment is adjusted to any changes applied during the upgrade.
.. If any of the templates you are using were created by cloning the default {Project} templates, verify whether the default templates changed during the upgrade.
If the default templates have changed, consider updating your custom templates as well to reflect these changes.
+
[NOTE]
====
If the default provisioning templates changed during the upgrade and your custom code is executed before or after the provisioning process, you can use custom provisioning snippets to avoid recreating cloned templates.
For more information about configuring custom provisioning snippets, see {ProvisioningDocURL}running-custom-code-during-host-provisioning[Running custom code during host provisioning] in _{ProvisioningDocTitle}_.
====
.. If your {Project} shows any discovered hosts, reboot them:
... In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
... Select *Any Organization* to display all discovered hosts.
... Reboot all discovered hosts.
