[[synchronizing_satellite_tools_repository]]
= Synchronizing the Satellite Tools Repository

ifeval::["{build}" == "foreman"]
If you use the Katello plug-in, you can synchronize the Satellite Tools repository from the Red Hat Content Delivery Network (CDN) to your {Project}.
This repository provides the `katello-agent` and `puppet` packages for clients registered to {ProjectServer}.
endif::[]

ifeval::["{build}" == "satellite"]
Use this section to synchronize the Satellite Tools repository from the Red Hat Content Delivery Network (CDN) to your {Project}.
This repository provides the `katello-agent` and `puppet` packages for clients registered to {ProjectServer}.
endif::[]

.Procedure
To synchronize the Satellite Tools repository, complete the following steps:

. In the {Project} web UI, navigate to *Content* > *Sync Status*.
+
A list of product repositories available for synchronization is displayed.

. Click the arrow next to the *Red{nbsp}Hat Enterprise Linux Server* product to view available content.

. Select *{ProjectName} Tools {ProductVersionRepoTitle} (for RHEL 7 Server) RPMs x86_64*.

. Click *Synchronize Now*.

.For CLI Users

Synchronize your Satellite Tools repository using the `hammer repository synchronize` command:

[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository synchronize --organization _"initial_organization_name"_ \
--product 'Red Hat Enterprise Linux Server' \
--name 'Red Hat Satellite Tools {ProductVersionRepoTitle} for RHEL 7 Server RPMs x86_64' \
--async
----
