[id="foreman-release-notes"]
= Foreman {ProjectVersion} Release Notes

[id="foreman-headline-features"]
== Headline Features

=== DSL Autocompletion in templates

The template editor now has embedded DSL documentation
(\https://yourforeman.example.com/templates_doc) as an auto-completion feature that is similar to
modern text editors or IDEs. It allows users to list all available macros whilst
writing a new or changing an existing template. An item in the list shows the
signature of the macro, its description and examples of how to use it. Each item
can be selected to be filled automatically in the template's body by pressing
`Enter` key. The list can be shown by pressing `Ctrl + Space` keys. There is
also `Live Autocompletion` checkbox to examine the list whilst typing.

Autocompletion is disabled by default and can be enabled in the
editor by checking `Autocompletion` checkbox.

=== EL9 Client repository

This release ships with the `foreman-client` repository being available for EL9 (CentOS Stream 9, AlmaLinux 9, Rocky 9, etc).

[id="foreman-upgrade-warnings"]
== Upgrade Warnings

=== Disabling unattended mode dropped

Running Foreman with setting `unattended: false` is dropped.
Every Foreman instance is now effectively running with this setting on.
For more details and discussion read https://community.theforeman.org/t/rfc-remove-unattended-setting/10035[the RFC].

=== BMC credentials access turned off by default

BMC credentials access through ENC YAML output and templates is turned off by default for increased security. To turn it on, go to Administer - Settings and turn the "BMC credentials access" setting on.

=== Updated browser compatiblity

We've updated our browsers compatibility to support the following:

* Google Chrome - latest version
* Microsoft Edge - latest version
* Apple Safari - latest version
* Mozilla Firefox - latest version
* Mozilla Firefox Extended Support Release (ESR) - latest version

[id="foreman-deprecations"]
== Deprecations

=== Running Foreman on EL 7

EL7 support is deprecated and will be dropped with Foreman 3.4. Users are advised to upgrade to EL8.

Note that this support statement refers to running Foreman and Foreman Smart Proxy themselves on EL7. Managing EL7 hosts remains supported. See https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008[the RFC] for more information.

=== Running Foreman on Debian 10

Debian 10 support is deprecated and will be dropped with Foreman 3.4. Users are advised to upgrade to Debian 11.

Note that this support statement refers to running Foreman and Foreman Proxy themselves on Debian 10. Managing Debian 10 hosts remains supported. See https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008[the RFC] for more information.

=== Running Foreman on Ruby 2.5

With the deprecation of Debian 10 deployments in Foreman 3.2 (and the removal of support in 3.4), there will be no supported platform with Ruby 2.5 anymore.
Therefore running Foreman on Ruby 2.5 is deprecated and support will be dropped (together with Debian 10) in Foreman 3.4.
Please switch to Ruby 2.7.
