[id="foreman-release-notes"]
= Foreman {ProjectVersion} release notes

[id="foreman-headline-features"]
== Headline features

//[id="user-interface-and-experience"]
//=== User interface & experience

//If this section would be empty otherwise, comment out the section heading.

[id="infrastructure-and-platform-updates"]
=== Infrastructure & platform updates

GRUB1 template support removed::
Support for legacy GRUB (GRUB1) templates has been completely removed.
Most distributions switched to GRUB2 by 2014, and maintaining GRUB1 support was causing compatibility issues with newer systems.
Systems still using GRUB1 for provisioning must migrate to GRUB2 before upgrading.

[id="networking-and-connectivity"]
=== Networking & connectivity

SSH certificate support for remote execution::
Smart Proxies can now use SSH certificates signed by a trusted certificate authority (CA) during remote execution connections.
This feature avoids the default Trust on First Use (TOFU) model and provides centralized trust management and revocation capabilities.

//[id="clients"]
//=== Clients

//If this section would be empty otherwise, comment out the section heading.

//[id="documentation-and-tooling"]
//=== Documentation & tooling

//If this section would be empty otherwise, comment out the section heading.

[id="foreman-upgrade-warnings"]
== Upgrade warnings

//If there are upgrade warnings, comment out the following line:
//There are no upgrade warnings with Foreman {ProjectVersion}.

NodeJS 18 no longer supported::
NodeJS 18 support has been dropped.
Foreman now requires NodeJS 22 or later for development and building assets.

[id="foreman-deprecations"]
== Deprecations

//If there are deprecations, comment out the following line.
//There are no deprecations with Foreman {ProjectVersion}.

ForemanModal component deprecated::
The ForemanModal component in Foreman core is now deprecated.
Plugins should migrate to PatternFly 5 modal components.

PatternFly 3 select form field deprecated::
The PatternFly 3 select form field component is deprecated.
PatternFly 5 Select components are used instead.
