[id="foreman-release-notes"]
= Foreman {ProjectVersion} Release Notes

[id="foreman-headline-features"]
== Headline Features

There are no highlights with Foreman {ProjectVersion}.

[id="foreman-upgrade-warnings"]
== Upgrade Warnings

// If this section would be empty otherwise, uncomment the following line:
//There are no upgrade warnings with Foreman {ProjectVersion}.
ifndef::foreman-deb[]
=== EL 7 client repositories dropped

RHEL 7 is out of maintenance since June 2024 and at the same time CentOS Linux 7 went end of life.
With Foreman 3.14, the client repository is no longer built for EL 7.
This primarily affects Katello and OpenSCAP users.

For more details, see the https://community.theforeman.org/t/drop-el7-packages-from-foreman-client-with-foreman-3-14/40505[removal RFC].

endif::[]
ifdef::foreman-deb[]
=== Running Foreman on Debian 11 (Bullseye) is not supported anymore

Foreman supports running on Debian 12 (Bullseye) since 3.11.4.
Running Foreman on Debian 11 has been deprecated since 3.13.
Support for running Foreman on Debian 11 has been removed.

Note this is for running Foreman itself.
Clients will remain supported.

For more details, see the https://community.theforeman.org/t/drop-debian-11-ruby-2-7-and-nodejs-14-support-in-foreman-3-14/40503[removal RFC].
endif::[]

=== {awx} Parameter Change
The `ansible_tower_fqdn` parameter has been removed and replaced with `ansible_tower_api_url`. This new parameter includes both the previous `ansible_tower_fqdn` value and the required API path for {awx}.

By default, the API path is set to `/api/controller/v2`. If you are using an older version of {awx} that requires a different API path, you will need to update it manually to `/api/v2`.

[id="foreman-deprecations"]
== Deprecations

There are no deprecations with Foreman {ProjectVersion}.
