[id="foreman-release-notes"]
= Foreman {ProjectVersion} Release Notes

[id="foreman-headline-features"]
== Headline Features

=== Puppet ENC functionality extracted to foreman_puppet plugin

Foreman without the plugin no longer includes Puppet environments, config groups, Puppet classes and smart class parameters.
It is still possible to assign Puppet environment to a host using the `puppet_environment` parameter. This is also the case for setting Puppet server and Puppet CA server for provisioning, which can be defined using the `puppet_server` and `puppet_ca_server`. A rake task will be provided to allow automatically migrating these values to parameters for users who do not wish to continue using the plugin.
By default, this plugin is still installed in 3.0 both on fresh installs and upgrades, but will default to off in future releases.
More information can be found on our Discourse in thread https://community.theforeman.org/t/puppet-enc-plugin-development/20687[Puppet ENC plugin development] and https://community.theforeman.org/t/puppet-in-3-0-release/24429[Puppet in 3.0 release].

=== Kerberos authentication using mod_auth_gssapi

The installer will now deploy `mod_auth_gssapi` instead of `mod_auth_kerb` if called with `--foreman-ipa-authentication=true`.
Existing installations will be upgraded to use `mod_auth_gssapi` too.
This allows deploying Kerberos authentication on CentOS 8, which lacks `mod_auth_kerb`.
Debian and Ubuntu also provide `mod_auth_gssapi` and the installer can now deploy Kerberos authentication there too.

=== Fact parsers are included in core

Fact parsers for Ansible, Chef, Salt and Subscription Manager were moved to the Foreman core. This is the first step in refactoring fact handling in Foreman to be simpler, faster and easily extendable. Thanks to that it's now possible to upload facts from these tools even if the respective plugin is not installed.

[id="foreman-upgrade-warnings"]
== Upgrade Warnings

* The `view_bookmarks` permission has been removed. All users are able to see their own bookmarks and any public bookmark defined by others.
* The `enable-epel` parameter now defaults to `false`. If you still want to enable EPEL at provisioning time, you will need to explicitly set the parameter to `true`.
* The `host_param_true?` and `host_param_false?` macros changed the meaning of the `default_value` parameter. The value is now used for the comparison if the parameter is not set on the host, instead of returing the value directly. Please update your templates accordingly.
* The Debian packages are signed with a new key https://theforeman.org/static/keys/5B7C3E5A735BCB4D615829DC0BDDA991FD7AAC8A.pub[5B7C3E5A735BCB4D615829DC0BDDA991FD7AAC8A]. Please import it to verify the packages.
* Foreman 2.5 for Debian/Ubuntu had briefly wrong versioned Ansible and Remote Execution plugins published, please read our https://theforeman.org/2021/08/please-manually-upgrade-ansible-and-remote-execution-plugins-on-25.html[blog post how to properly upgrade these].

[id="foreman-deprecations"]
== Deprecations

=== Running Foreman on Ubuntu 18.04

Foreman 2.5 introduced support to run on Ubuntu 20.04. Foreman 3.0 deprecates support for running on Ubuntu 18.04 and Foreman 3.1 will drop it.
Users are encouraged to upgrade to Ubuntu 20.04 either on Foreman 2.5 or 3.0 but Ubuntu 18.04 will remain supported until Foreman 2.5 and 3.0 are end of life.

Note that this is only support to run Foreman and Foreman Proxy themselves on Ubuntu 18.04. Managing Ubuntu 18.04 systems remains supported. See https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008[the RFC] for more information.

=== Running Foreman on EL7

Foreman 2.1 introduced EL8 support and Katello 4.0 (on Foreman 2.4) followed.
While it's currently undecided when EL7 support will be dropped exactly, this is an early notice given the considerable number of EL7 deployments.
For fresh installations, EL8 should considered the preferred target.
Existing installations should start thinking about a migration plan.

Note that this is only support to run Foreman and Foreman Proxy themselves on EL7. Managing EL7 systems remains supported. See https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008[the RFC] for more information.
