[id="foreman-release-notes"]
= Foreman {ProjectVersion} Release Notes

[id="foreman-headline-features"]
== Headline Features

[id="foreman-upgrade-warnings"]
== Upgrade Warnings

=== Running Foreman on EL7

EL7 support is dropped with Foreman 3.4. Users are advised to upgrade to EL8.

Note that this support statement refers to running Foreman and Foreman Smart Proxy themselves on EL7. Managing EL7 hosts remains supported. See [the RFC](https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008) for more information.

=== Running Foreman on Debian 10

Debian 10 support is dropped with Foreman 3.4. Users are advised to upgrade to Debian 11.

Note that this support statement refers to running Foreman and Foreman Proxy themselves on Debian 10. Managing Debian 10 hosts remains supported. See [the RFC](https://community.theforeman.org/t/deprecation-plans-for-foreman-on-el7-debian-10-and-ubuntu-18-04/25008) for more information.

=== Running Foreman on Ruby 2.5

With dropping the support of Debian 10 deployments in Foreman 3.2 (and the removal of support in 3.4), there is no supported platform with Ruby 2.5 anymore.
Therefore running Foreman on Ruby 2.5 is dropped in Foreman 3.4. Please switch to Ruby 2.7.

[id="foreman-deprecations"]
== Deprecations
