[id="foreman-release-notes"]
= Foreman {ProjectVersion} release notes

[id="foreman-headline-features"]
== Headline features

[id="user-interface-and-experience"]
=== User interface & experience

PatternFly 5 UI updates::
Continued migration to PatternFly 5 brings modernized notifications (link:https://projects.theforeman.org/issues/38345[#38345]) and other UI components, improving the overall user experience with updated design patterns.

[id="infrastructure-and-platform-updates"]
=== Infrastructure & platform updates

Multi-architecture iPXE support::
iPXE chain UEFI now supports multiple architectures (link:https://projects.theforeman.org/issues/38300[#38300]), enabling proper provisioning of ARM64 and other non-x86_64 hosts by delivering the correct iPXE binary for each architecture.

Resource Quota plugin::
If you use the Resource Quota plugin on {Project} {ProjectVersionPrevious}, {Project} will automatically assign all existing hosts to the `Unassigned` resource quota during the upgrade to {Project} {ProjectVersion}.
For more information, see {AdministeringDocURL}limiting-host-resources[Limiting host resources] in _{AdministeringDocTitle}_.

[id="foreman-upgrade-warnings"]
== Upgrade warnings

Ruby 2.7 no longer supported::
Ruby 2.7 support has been dropped (link:https://projects.theforeman.org/issues/38115[#38115], link:https://projects.theforeman.org/issues/38883[#38883]).

Grub1 removed::
Support for legacy GRUB (Grub1) has been completely removed from both Foreman and Smart Proxy (link:https://projects.theforeman.org/issues/38768[#38768], link:https://projects.theforeman.org/issues/38772[#38772], link:https://projects.theforeman.org/issues/38787[#38787], link:https://projects.theforeman.org/issues/38791[#38791]).
Only GRUB2 is supported going forward.
If you are still using Grub1 for provisioning, migrate to GRUB2 before upgrading.

[id="foreman-deprecations"]
== Deprecations

There are no deprecations with Foreman {ProjectVersion}.
