[id="foreman-release-notes"]
= Foreman {ProjectVersion} Release Notes

[id="foreman-headline-features"]
== Headline Features

=== New All Hosts page features


This release introduces an experimental new page that will eventually replace the All Hosts page.
In its first iteration, it includes Host Create and Register buttons, bulk multi-page selection, host deletion, and faster links to each host.
You can try out the new page via 'Show new host overview page' in Settings.
After changing the setting, a full browser page reload is required.
In future releases, more features will be added to the new page, and the old page will eventually be retired.

=== Redis is the default cache type

Default installations will now use Redis configured as the default cache type. Using Redis as the cache has proven to be better performant and does not result in file locking or cache misses.


[id="foreman-upgrade-warnings"]
== Upgrade Warnings

// If this section would be empty otherwise, uncomment the following line:
// There are no upgrade warnings with Foreman {ProjectVersion}.

=== Fedora/Red Hat Atomic is no longer supported

Red Hat Atomic went end of life in 2021 and Fedora Atomic even earlier.
Starting with Foreman 3.9, these will be recognized as regular Fedora or Red Hat.
The installation medium is no longer created, and provisioning templates have dropped support.

=== Short names of hosts in API calls are no longer supported

With host names stored as FQDN (Fully Qualified Domain Names) in Foreman, you can no longer use short names to retrieve the host resource in the Foreman API, such as `\https://foreman/api/hosts/:hostname`.
Use FQDN to identify the hosts.

[id="foreman-deprecations"]
== Deprecations

There are no deprecations with Foreman {ProjectVersion}.
