[id="foreman-release-notes"]
= Foreman {ProjectVersion} Release Notes

[id="foreman-headline-features"]
== Headline Features

ifndef::foreman-deb[]
There are no highlights with Foreman {ProjectVersion}.
endif::[]
ifdef::foreman-deb[]
=== Running Foreman on Debian 12 (Bookworm)

Foreman now supports running on Debian 12 (Bookworm).
endif::[]

[id="foreman-upgrade-warnings"]
== Upgrade Warnings

// If this section would be empty otherwise, uncomment the following line:
ifndef::foreman-deb[]
There are no upgrade warnings with Foreman {ProjectVersion}.
endif::[]
ifdef::foreman-deb[]
=== Running Foreman on Ubuntu 20.04 (Focal) is not supported anymore

Foreman supports running on Ubuntu 22.04 LTS (Jammy Jellyfish) since 3.11.
Running Foreman on Ubuntu 20.04 LTS has been deprecated since 3.12.
Support for running Foreman on Ubuntu 20.04 LTS has been removed.

Note this is for running Foreman itself.
Clients will remain supported.
endif::[]

[id="foreman-deprecations"]
== Deprecations

ifndef::foreman-deb[]
There are no deprecations with Foreman {ProjectVersion}.
endif::[]
ifdef::foreman-deb[]
Now that Debian 12 is supported, Foreman 3.14 will drop support for Debian 11.
Note this is for running Foreman itself.
Clients will remain supported.
endif::[]
