[id="katello-release-notes"]
= Katello {KatelloVersion} Release Notes

[id="katello-headline-features"]
== Headline Features

=== Use HTTP/2 on content proxies to connect to Foreman

https://github.com/theforeman/puppet-foreman_proxy_content/pull/442#issuecomment-1776993907 has some graphs - the number of concurrent registrations via content proxies has a MUCH lower error rate than it used to.

=== New System Purpose card on Activation Key details page

On the new experimental Activation Key details page (available by turning on Show Experimental Labs in Settings) you can now view and edit system purpose attributes for an activation key.

=== New host status for RHEL lifecycle reminders

For Red Hat Enterprise Linux hosts, you’ll now see a new host status which indicates when a host’s RHEL version is approaching the end of a support lifecycle.
The host will show a “Warning” status when its RHEL version is within 1 year of the end of support, and an “Error” status when end of support is reached.

=== Change Content Source action on new host overview page

On Foreman’s new All Hosts overview page, (available via Show New Host Overview Page in Settings), you can now select multiple hosts to perform a Change Content Source action.

=== New Host - Installed Products report

A new report template that is very similar to the Subscription - Entitlement Report but works for organizations using simple content access.
Subscription consumption is no longer listed, but installed products and system purpose fields are present.

=== Restore smart proxy content counts

Before Katello 4.0, when Pulp 2 was in use, smart proxies had count information for how many content units were synced.
Now, that information is back and more helpful.
Katello now gets the smart proxy content counts directly from the Pulp API so that users can reliably check how much content is synced to their smart proxies

=== Pulpcore version upgraded to 3.39

Features performance improvements most notably around import/export for disconnected environments.

[id="katello-upgrade-warnings"]
== Upgrade Warnings

=== Pulpcore

The pulpcore module stream must be disabled before updating packages.  Pulpcore RPMs are no longer modular.

[id="katello-deprecations"]
== Deprecations

=== Simple Content Access (SCA)

Simple Content Access will be the only subscription management mode as of Katello 4.12.
