[id="katello-release-notes"]
= Katello {KatelloVersion} Release Notes

[id="katello-headline-features"]
== Headline Features

=== Verify Content Checksum on container repositories using Hammer
Option '--validate-contents' now supports all repository types,
using "hammer repository synchronize" command. 
Previously container repositories and some others were not supported.

=== Add ACS bulk refresh option
Added option '--all' to "hammer alternate-content-source refresh" command.

=== Experimental activation key details page
When the setting 'Show Experimental Labs' is enabled, the Activation Key 
details page will be replaced by the beginnings of a redesigned page.

=== Content Views and CVV enhancements to filters and refresh
Content View filter creation/edit UI: 'Edit Rule' button is now 'Save'.
If dependency solving is enabled or disabled for a content view, it will now be marked as needing a new publish.

=== Pulpcore and plugins updated from Pulpcore 3.22 to 3.28
Contains both fixes and features that Katello can use in the future to better manage content, such as:\
[More filter options on the packages API](https://github.com/pulp/pulp_rpm/issues/3135)\
[New setting for generated primary.xml timestamps to match upstream repository](https://github.com/pulp/pulp_rpm/issues/3009)\
[RPM replicator support](https://github.com/pulp/pulp_rpm/issues/2995)\
[New distribution hiding option](https://github.com/pulp/pulpcore/issues/3538)\
[OpenTelemetry support](https://github.com/pulp/pulpcore/issues/3835)\
[File size added to content application listing](https://github.com/pulp/pulpcore/issues/3656)

[id="katello-upgrade-warnings"]
== Upgrade Warnings

=== Katello-Agent removal
Katello-Agent has been removed from Katello and is no longer available via web UI, API, or CLI.
Katello-Agent will be removed by upgrading. 
For patching hosts going forward, use remote execution.
Remote execution will not be automatically enabled as part of the upgrade. 
To ensure uninterrupted host patching, migrate to remote execution before upgrading.
To migrate hosts, see {ManagingHostsDocURL}Migrating_Hosts_From_Katello_Agent_to_Remote_Execution_managing-hosts[Migrating from Katello Agent to Remote Execution] in _{ManagingHostsDocTitle}_.

=== Removed various settings
As part of the removal of Katello-Agent, the following related settings have been removed: 
'Use remote execution by default', 'Accept action timeout', and 'Finish action timeout'.