include::common/attributes.adoc[]
include::common/header.adoc[]
:quickstart-installation-guide:
:context: {project-context}
:mode: connected
:ProductName: {ProjectServer}

= {project-installation-guide-title}

The Foreman installer is a collection of Puppet modules that installs everything required for a full working Foreman setup. It uses native OS packaging (e.g. RPM and .deb packages) and adds necessary configuration for the complete installation.

Components include the Foreman web UI, Smart Proxy, a Puppet server, TFTP, DNS and DHCP servers. It is configurable and the Puppet modules can be read or run in “no-op” mode to see what changes it will make.

include::common/modules/ref_supported-operating-systems.adoc[]

The installation will require 4GB of memory.
For more information, see {InstallingProjectDocURL}system-requirements_{project-context}[System Requirements].

The Foreman installer uses Puppet (5 or later required) to install Foreman. This guide assumes that you have a newly installed operating system, on which the installer will setup Foreman, a Puppet server, and the Smart Proxy by default. It’s not advisable to follow the steps below on an existing system, since the installer will affect the configuration of several components.

include::common/modules/proc_configuring-repositories.adoc[leveloffset=+1]

include::common/modules/proc_installing-the-satellite-server-packages.adoc[leveloffset=+1]

== Running the Installer

The installation run is non-interactive, but the configuration can be customized by supplying any of the options listed in foreman-installer --help, or by running foreman-installer -i for interactive mode. More examples are given in the Installation Options section. Adding -v will disable the progress bar and display all changes.

To run the installer, execute:

ifdef::foreman-el,foreman-deb[]
[options="nowrap" subs="+quotes,attributes"]
----
# foreman-installer
----
endif::[]
ifdef::katello[]
[options="nowrap" subs="+quotes,attributes"]
----
# foreman-installer --scenario katello
----
endif::[]

When the installer has completed, details will be printed about where to find Foreman and the Smart Proxy.
