[[Prerequisites]]
= Prerequisites

Before you can install and register {ProjectName} and {SmartProxy}, you must set up accounts with Amazon Web Services (AWS) and create and start {RHEL} instances on AWS.

== Amazon Web Service Assumptions

To use this guide, you must have a working knowledge of the following aspects of Amazon Web Services:

* Creating and accessing {RHEL} images in AWS
* Editing network access in AWS Security
* Creating EC2 instances and how to create EBS volumes
* Launching instances
* Importing and exporting virtual machines in AWS
* Using AWS Direct Connect

To install {Project} in an AWS environment, you must ensure that your AWS set up meets the {InstallingProjectDocURL}system-requirements_{project-context}[System Requirements] in _{project-installation-guide-title}_.

To install {SmartProxy} in an AWS environment, you must ensure that your AWS set up meets the {InstallingSmartProxyDocURL}system-requirements_{smart-proxy-context}[System Requirements] in _{smart-proxy-installation-guide-title}_.

For more information about Amazon Web Services and terminology, see https://aws.amazon.com/documentation/ec2/[Amazon Elastic Compute Cloud Documentation].

For more information about Amazon Web Services Direct Connect, see https://docs.aws.amazon.com/directconnect/latest/UserGuide/Welcome.html[What is AWS Direct Connect?]

ifndef::foreman-deb[]
== Red Hat Cloud prerequisites

To use this guide, you must complete the following steps:

* Register with Red Hat Cloud Access.
* Migrate any Red Hat subscriptions that you want to use.
* Create an AWS instance and deploy a {RHEL} virtual machine to the instance.
* Ensure that your subscriptions are eligible for transfer to Red Hat Cloud.
For more information, see https://www.redhat.com/en/technologies/cloud-computing/cloud-access#program-details[Red Hat Cloud Access Program Details].

For more information about deploying {RHEL} in AWS, see https://access.redhat.com/articles/2962171[How to Locate Red Hat Cloud Access Gold Images on AWS EC2].
endif::[]

== {ProjectName}-specific prerequisites

* Ensure that the Amazon EC2 instance type meets or exceeds the {InstallingProjectDocURL}system-requirements_{project-context}[System Requirements] in _{project-installation-guide-title}_.
For the best performance, use an https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/storage-optimized-instances.html[AWS storage optimized instance].
ifndef::foreman-deb[]
* Use {InstallingProjectDocURL}satellite-storage-requirements_{project-context}[Storage Requirements] in _{project-installation-guide-title}_ to understand and assign the correct storage to your AWS EBS volumes.
* Store the synced content on an EBS volume that is separate to the boot volume.
* Mount the synced content EBS volume separately in the operating system.
* Optional: store other data on a separate EBS volume.
endif::[]
* If you want {ProjectServer} and {SmartProxyServer} to communicate using external DNS hostnames, open the required ports for communication in the AWS Security Group that is associated with the instance.

ifndef::foreman-deb[]
== Preparing for the {ProjectName} Installation

In your AWS environment, complete the following steps:

. Launch an EC2 instance of a {RHEL} AMI.
. Connect to the newly created instance.
. If you use a Red Hat Gold Image, remove the RHUI client and set the `enabled` parameter in the `product-id.conf` to `1`.
+
[options="nowrap" subs="+quotes,attributes"]
-----
# {package-remove} -y rh-amazon-rhui-client*
# {package-clean} all
# cat << EOF > /etc/yum/pluginconf.d/product-id.conf
> [main]
> enabled=1
> EOF
-----
endif::[]
