[[Use_Case_Considerations]]
= Use Case Considerations

Because Amazon Web Services is an image-only service, there are common {Project} use cases that do not work, or require extra configuration in an Amazon Web Service environment.
If you plan to use {Project} on AWS, ensure that the use case scenarios that you want to use are available in an AWS environment.

== Use Cases Known to Work

You can perform the following {ProjectName} use cases on AWS:

ifdef::katello,orcharhino,satellite[]
* {ContentManagementDocURL}Managing_Red_Hat_Subscriptions_content-management[Managing Red Hat Subscriptions]
* {ContentManagementDocURL}Importing_Content_content-management[Importing Content]
* {ContentManagementDocURL}Managing_Errata[Managing Errata]
* {ManagingHostsDocURL}Registering_a_Host_Manually_managing-hosts[Registering a Host Manually]
endif::[]
ifdef::satellite[]
* https://access.redhat.com/products/red-hat-insights/#satellite6[Red Hat Insights]
endif::[]
* {AdministeringDocURL}Using_FreeIPA_admin[Realm Integration via IdM]
ifndef::foreman-deb[]
* {AdministeringDocURL}Managing_Security_Compliance_admin[OpenSCAP]
endif::[]
* {ManagingHostsDocURL}Configuring_and_Setting_Up_Remote_Jobs_managing-hosts[Remote Execution]

ifndef::foreman-deb[]
.Subscriptions

Not all Red Hat subscriptions are eligible to run in public cloud environments.
For more information about subscription eligibility, see the https://www.redhat.com/en/technologies/cloud-computing/cloud-access#program-details[Red Hat Cloud Access Page].
You can create additional organizations and then import additional manifests to the organizations.
ifdef::satellite[]
For more information, see {ContentManagementDocURL}Managing_Organizations-Creating_an_Organization[Creating an Organization] in the _Content Management Guide_.
endif::[]
ifndef::satellite[]
For more information, see {ManagingOrganizationsLocationsDocURL}Managing_Organizations_managing-organizations-locations[Managing Organizations] in the _Managing Organizations and Locations in {Project} Guide_.
endif::[]
endif::[]

.Multi-homed {Project} and {SmartProxy}

ifdef::satellite[]
Multi-homed {Project} is not supported.

Multi-homed {SmartProxy} is supported, to implement this, you can configure {SmartProxies} with a load balancer.
For more information, see {ConfiguringLoadBalancerDocURL}[Configuring {SmartProxies} with a Load Balancer].
endif::[]

ifndef::satellite[]
One way to use multi-homed {SmartProxies} is by configuring {SmartProxies} with a load balancer.
For more information, see {ConfiguringLoadBalancerDocURL}[Configuring {SmartProxies} with a Load Balancer].
endif::[]

You must do this when {ProjectServer} or {SmartProxyServer} has different internal and external DNS host names and there is no site-to-site VPN connection between the locations where you deploy {ProjectServer} and {SmartProxyServer}.

ifdef::katello,orcharhino,satellite[]
.On demand content sources
You can use the *On demand* download policy to reduce the storage footprint of the server that runs {Project}.
When you set the download policy to *On Demand*, content syncs to {ProjectServer} or {SmartProxyServer} when a content host requests it.

For more information, see {ContentManagementDocURL}Importing_Content_content-management[Importing Content] in the _Content Management Guide_.
endif::[]

== Use Cases that Do Not Work

In AWS, you cannot manage the DHCP.
Because of this, most of {ProjectServer}’s kickstart and PXE provisioning models are unusable.
This includes:

* PXE Provisioning
* Discovery and Discovery Rules
* ISO Provisioning methods.
** PXE-Less Discovery (iPXE)
** Per-host ISO
** Generic ISO
** Full-host ISO
