include ../common/Makefile

# Preview build for JTBD navigation structure
# Uses master-preview.adoc instead of master.adoc

SOURCES_PREVIEW = master-preview.adoc $(shell find . -type f -name \*.adoc)
DEST_HTML_PREVIEW = $(DEST_DIR)/index-preview-$(BUILD).html

html-preview: prepare $(IMAGES_TS)
	bundle exec asciidoctor -b html5 \
		-a compat-mode \
		-a experimental \
		-a listing-caption! \
		-a source-highlighter=highlightjs \
		-a table-caption! \
		-a toc=left \
		-a build=$(BUILD) \
		$(BASEURL_ATTR) \
		-d book \
		-o $(DEST_HTML_PREVIEW) \
		master-preview.adoc
	@echo "================================================"
	@echo "JTBD Preview built: $(DEST_HTML_PREVIEW)"
	@echo "================================================"
	@echo "Compare with original: $(DEST_DIR)/index-$(BUILD).html"
	@echo ""

browser-preview: html-preview
	${BROWSER_OPEN} "file://$(realpath $(ROOTDIR)/$(DEST_HTML_PREVIEW))"

.PHONY: html-preview browser-preview
