[id="Administering_Hosts"]
= Administering Hosts

This chapter describes creating, registering, administering, and removing hosts.

//Creating a Host in {ProjectName}
include::proc_creating-a-host-in-satellite.adoc[leveloffset=+1]

ifeval::["{build}" == "satellite"]
== Editing the System Purpose of a Host

You can edit the system purpose attributes for a {RHEL} host. System purpose attributes define which subscriptions to attach automatically to this host. For more information about system purpose, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_installation/graphical-installation_graphical-installation#configuring-system-purpose-standard_configuring-system-settings[Configuring system purpose] in the _Performing a standard RHEL installation_ guide.

.Prerequisites

* The host that you want to edit must be registered with the subscription-manager.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *Content Hosts* and click the name of the Red{nbsp}Hat Enterprise Linux{nbsp}8 host that you want to edit.
. In the *System Purpose* area, click the *Edit* or *Remove* icon for the system purpose attributes that you want to edit, add, or remove.
. Click *Save*.
. Click the *Subscriptions* tab and select *Subscriptions*.
. Click *Run Auto-Attach* to attach subscriptions to your host automatically.
. Refresh the page to verify that the subscriptions list contains the correct subscriptions.

.For CLI Users

. Log in to the host and edit the required system purpose attributes.
For example, set the usage type to `Production`, the role to `Red Hat Enterprise Linux Server`, and add the `addon` add on.
For the list of values, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_installation/graphical-installation_graphical-installation#configuring-system-purpose-standard_configuring-system-settings[Configuring system purpose] in the _Performing a standard RHEL installation_ guide.
+
[subs="+quotes"]
----
# syspurpose set-usage `_Production_`
# syspurpose set-role `_Red Hat Enterprise Linux Server_`
# syspurpose add-addons '_your_addon_'
----

. Verify the system purpose attributes for this host:
+
[subs="+quotes"]
----
# syspurpose show
----

. Automatically attach subscriptions to this host:
+
[subs="+quotes"]
----
# subscription-manager attach --auto
----

. Verify the system purpose status for this host:
+
[subs="+quotes"]
----
# subscription-manager status
----

[id="editing-the-system-purpose-of-a-host"]
== Editing the System Purpose of Multiple Hosts

You can edit the system purpose attributes of {RHEL} hosts.
System purpose attributes define which subscriptions to attach automatically to hosts.
For more information about system purpose, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_a_standard_rhel_installation/graphical-installation_graphical-installation#configuring-system-purpose-standard_configuring-system-settings[Configuring system purpose] in the _Performing a standard RHEL installation_ guide.

.Prerequisites

* The hosts that you want to edit must be registered with the subscription-manager.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *Content Hosts* and select Red{nbsp}Hat Enterprise Linux{nbsp}8 hosts that you want to edit.
. Click the *Select Action* list and select *Manage System Purpose*.
. Select the system purpose attributes that you want to assign to the selected hosts.
You can select one of the following values:
+
* A specific attribute to set an all selected hosts.
* *No Change* to keep the attribute set on the selected hosts.
* *None (Clear)* to clear the attribute on the selected hosts.
. Click *Assign*.
. Navigate to *Hosts* > *Content Hosts* and select the same Red{nbsp}Hat Enterprise Linux{nbsp}8 hosts to automatically attach subscriptions based on the system purpose.
. Click the *Select Action* list and select *Manage Subscriptions*.
. Click *Auto-Attach* to attach subscriptions to all selected hosts automatically based on their system role.
endif::[]

[id="changing-a-module-stream-for-a-host"]
== Changing a Module Stream for a Host

ifeval::["{build}" == "satellite"]
If you have a Red{nbsp}Hat Enterprise Linux 8 host, you can modify the module stream for the repositories you install.
endif::[]
ifeval::["{build}" != "satellite"]
If you have a Red{nbsp}Hat Enterprise Linux 8 or clone operating system host, you can modify the module stream for the repositories you install.
endif::[]

After you create the host, you can enable, disable, install, update, and remove module streams from your host in the {Project} web UI.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *Content Hosts* and click the name of the host that contains the modules you want to change.
. Click the *Module Streams* tab.
. From the *Available Module Streams* list, locate the module that you want to change.
You can use the *Filter* field to refine the list entries.
You can also use the *Filter Status* list to search for modules with a specific status.
. From the *Actions* list, select the change that you want to make to the module.
. In the *Job Invocation* window, ensure that the job information is accurate.
Change any details that you require, and then click *Submit*.

//Creating a Host Group
include::proc_creating-a-host-group.adoc[leveloffset=+1]

// Creating a Host Group for Each LifeCycle Environment
include::proc_creating-a-host-group-for-each-lifecycle-environment.adoc[leveloffset=+1]

[id="changing-the-group-of-a-host"]
== Changing the Group of a Host

Use this procedure to change the group of a host.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *All hosts*.
. Select the check box of the host you want to change.
. From the *Select Action* list, select *Change Group*.
A new option window opens.
. From the *Host Group* list, select the group that you want for your host.
. Click *Submit*.


[id="changing-the-environment-of-a-host"]
== Changing the Environment of a Host

Use this procedure to change the environment of a host.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *All hosts*.
. Select the check box of the host you want to change.
. From the *Select Action* list, select *Change Environment*.
A new option window opens.
. From the *Environment* list, select the new environment for your host.
. Click *Submit*.

[id="changing-the-managed-status-of-a-host"]
== Changing the Managed Status of a Host

Hosts provisioned by {Project} are Managed by default.
When a host is set to Managed, you can configure additional host parameters from {ProjectServer}.
These additional parameters are listed on the *Operating System* tab.
If you change any settings on the *Operating System* tab, they will not take effect until you set the host to build and reboot it.

If you need to obtain reports about configuration management on systems using an operating system not supported by {Project}, set the host to Unmanaged.

Use this procedure to switch a host between Managed and Unmanaged status.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *All hosts*.
. Select the host.
. Click *Edit*.
. Click *Manage host* or *Unmanage host* to change the host's status.
. Click *Submit*.

[id="assinging-a-host-to-a-specific-organization"]
== Assigning a Host to a Specific Organization

Use this procedure to assign a host to a specific organization.
For general information about organizations and how to configure them, see {ContentManagementDocURL}Managing_Organizations[Managing Organizations] in the _Content Management Guide_.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *All hosts*.
. Select the check box of the host you want to change.
. From the *Select Action* list, select *Assign Organization*.
A new option window opens.
. From the *Select Organization* list, select the organization that you want to assign your host to.
Select the check box *Fix Organization on Mismatch*.
+
[NOTE]
====
A mismatch happens if there is a resource associated with a host, such as a domain or subnet, and at the same time not associated with the organization you want to assign the host to.
The option *Fix Organization on Mismatch* will add such a resource to the organization, and is therefore the recommended choice.
The option *Fail on Mismatch* will always result in an error message.
For example, reassigning a host from one organization to another will fail, even if there is no actual mismatch in settings.
====

. Click *Submit*.

[id="assigning-a-host-to-a-specific-location"]
== Assigning a Host to a Specific Location

Use this procedure to assign a host to a specific location.
For general information about locations and how to configure them, see {ContentManagementDocURL}Managing_Locations-Creating_a_Location[Creating a Location] in the _Content Management Guide_.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *All hosts*.
. Select the check box of the host you want to change.
. From the *Select Action* list, select *Assign Location*.
A new option window opens.
. Navigate to the *Select Location* list and choose the location that you want for your host.
Select the check box *Fix Location on Mismatch*.
+
[NOTE]
====
A mismatch happens if there is a resource associated with a host, such as a domain or subnet, and at the same time not associated with the location you want to assign the host to.
The option *Fix Location on Mismatch* will add such a resource to the location, and is therefore the recommended choice.
The option *Fail on Mismatch* will always result in an error message.
For example, reassigning a host from one location to another will fail, even if there is no actual mismatch in settings.
====

. Click *Submit*.

//Removing a Host from {ProjectName}
include::proc_removing-a-host-from-satellite.adoc[leveloffset=+1]
