[id="overview-of-hosts-in-satellite"]
= Overview of Hosts in Red{nbsp}Hat Satellite 6

A host is any Red{nbsp}Hat Enterprise{nbsp}Linux client that Red{nbsp}Hat Satellite manages. Hosts can be physical or virtual. Virtual hosts can be deployed on any platform supported by Red{nbsp}Hat Satellite, such as KVM, VMware vSphere, OpenStack, Amazon EC2, Rackspace Cloud Services or Google Compute Engine.

Red{nbsp}Hat Satellite enables host management at scale, including monitoring, provisioning, remote execution, configuration management, software management, and subscription management. You can manage your hosts from the Satellite web UI or from the command line.

In the Satellite web UI, you can browse all hosts recognized by Satellite Server, grouped by type:

* *All Hosts* - a list of all hosts recognized by Satellite Server.
* *Discovered Hosts* - a list of bare-metal hosts detected on the provisioning network by the Discovery plug-in.
* *Content Hosts* - a list of hosts that manage tasks related to content and subscriptions.
* *Host Collections* - a list of user-defined collections of hosts used for bulk actions such as errata installation.

To search for a host, type in the *Search* field, and use an asterisk ({asterisk}) to perform a partial string search. For example, if searching for a content host named `dev-node.example.com`, click the *Content Hosts* page and type `dev-node*` in the *Search* field. Alternatively, `{asterisk}node{asterisk}` will also find the content host `dev-node.example.com.`

WARNING: Satellite Server is listed as a host itself even if it is not self-registered. Do not delete Satellite Server from the list of hosts.
