[[chap-Red_Hat_Satellite-Managing_Hosts-Configuring_Host_Collections]]
= Configuring Host Collections

ifdef::foreman-deb,foreman-el,katello[]
This is for users of the Katello plug-in and hosts running RPM-based linux distributions.
Hosts collections work via the Pulp back end.
endif::[]

A host collection is a group of multiple content hosts.
This feature enables you to perform the same action on multiple hosts at once.
These actions can include the installation, removal, and update of packages and errata, change of assigned life cycle environment, and change of Content View.
You can create host collections to suit your requirements, and those of your company.
For example, group hosts in host collections by function, department, or business unit.

include::Creating_System_Groups.adoc[leveloffset=+1]

include::Cloning_a_System_Group.adoc[leveloffset=+1]

include::Removing_System_Groups.adoc[leveloffset=+1]

include::Adding_Systems_to_System_Groups.adoc[leveloffset=+1]

include::Removing_Systems_from_System_Groups.adoc[leveloffset=+1]

[[sect-Red_Hat_Satellite-Managing_Hosts-Configuring_Host_Collections-Adding_Content_to_a_Host_Collection]]
== Adding Content to a Host Collection

These steps show how to add content to host collections in {ProjectName}.

include::Adding_Packages_to_System_Groups.adoc[leveloffset=+2]

include::Adding_Errata_to_System_Groups.adoc[leveloffset=+2]

include::Removing_Content_from_System_Groups.adoc[leveloffset=+2]

include::Changing_the_Assigned_Lifecycle_Environment_or_Content_View_for_a_Host_Collection.adoc[leveloffset=+2]
