[[chap-Managing_Hosts-Generating_Host_Monitoring_Reports]]
= Generating Host Monitoring Reports

To view the report templates, in the Satellite web UI, navigate to *Monitor* > *Report Templates*.

To schedule reports, you can configure a cron job or use the Satellite web UI.

.Procedure

. In the Satellite web UI, navigate to *Monitor* > *Report Templates*.
. To the right of the report template that you want to use, click *Generate*.
. Optional: To schedule a report, to the right of the *Generate at* field, click the icon to select the date and time you want to generate the report at.
. Optional: To send a report to an e-mail address, select the *Send report via e-mail* check box, and in the *Deliver to e-mail addresses* field, enter the required e-mail address.
. Optional: Apply search query filters. To view all available results, do not populate the filter field with any values.
. Click *Submit*. A CSV file that contains the report is downloaded. If you have selected the *Send report via e-mail* check box, the host monitoring report is sent to your e-mail address.

.For CLI Users

To generate a report, complete the following steps:

. List all available report templates:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# hammer report-template list
----

. Generate a report:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# hammer report-template generate --id _template ID_
----
+
This command waits until the report fully generates before completing. If you want to generate the report as a background task, you can use the `hammer report-template schedule` command.
