[id="Registering_a_Host_Using_the_Bootstrap_Script_{context}"]
= Registering a Host to {ProjectName} Using The Bootstrap Script

**Deprecated** Use registration via Global registration feature.

Use the bootstrap script to automate content registration and Puppet configuration.
You can use the bootstrap script to register new hosts, or to migrate existing hosts to {ProjectNameX} from {Project} 5, RHN, SAM, or RHSM.

The `katello-client-bootstrap` package is installed by default on {ProjectServer}'s base operating system.
The `bootstrap.py` script is installed in the `/var/www/html/pub/` directory to make it available to hosts at `_{foreman-example-com}_/pub/bootstrap.py`.
The script includes documentation in the `/usr/share/doc/katello-client-bootstrap-_version_/README.md` file.

To use the bootstrap script, you must install it on the host.
As the script is only required once, and only for the `root` user, you can place it in `/root` or `/usr/local/sbin` and remove it after use.
This procedure uses `/root`.

.Prerequisites
* You have a {Project} user with the permissions required to run the bootstrap script.
The examples in this procedure specify the `admin` user.
If this is not acceptable to your security policy, create a new role with the minimum permissions required and add it to the user that will run the script.
For more information, see xref:Setting_Permissions_for_the_Bootstrap_Script_{context}[].
* You have an activation key for your hosts with the {project-client-name} repository enabled.
For information on configuring activation keys, see {ContentManagementDocURL}Managing_Activation_Keys_content-management[Managing Activation Keys] in the _Content Management Guide_.
* You have created a host group.
For more information about creating host groups, see xref:creating-a-host-group[].

.Puppet Considerations

If a host group is associated with a Puppet environment created inside a `Production` environment, Puppet fails to retrieve the Puppet CA certificate while registering a host from that host group.

To create a suitable Puppet environment to be associated with a host group, follow these steps:

. Manually create a directory and change the owner:
+
[options="nowrap", subs="+quotes,attributes"]
----
# mkdir /etc/puppetlabs/code/environments/_example_environment_
# chown apache /etc/puppetlabs/code/environments/_example_environment_
----
. Navigate to *Configure* > *Environments* and click *Import environment from*.
The button name includes the FQDN of the internal or external {SmartProxy}.
. Choose the created directory and click *Update*.

.Procedure
. Log in to the host as the `root` user.
. Download the script:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# curl -O http://_{foreman-example-com}_/pub/bootstrap.py
----
. Make the script executable:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# chmod +x bootstrap.py
----
. Confirm that the script is executable by viewing the help text:

* On {RHEL} 8:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py -h
----
* On other {RHEL} versions:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ./bootstrap.py -h
----

. Enter the bootstrap command with values suitable for your environment.
+
For the `--server` option, specify the FQDN of {ProjectServer} or a {SmartProxyServer}.
For the `--location`, `--organization`, and `--hostgroup` options, use quoted names, not labels, as arguments to the options.
See xref:advanced-bootstrap-script-configuration[] for advanced use cases.

* On {RHEL} 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_
----

* On {RHEL} 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ./bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_
----

. Enter the password of the {Project} user you specified with the `--login` option.
+
The script sends notices of progress to *stdout*.

. When prompted by the script, approve the host's Puppet certificate.
In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}* and find the {Project} or {SmartProxyServer} you specified with the `--server` option.
. From the list in the *Actions* column, select *Certificates*.
. In the *Actions* column, click *Sign* to approve the host's Puppet certificate.
. Return to the host to see the remainder of the bootstrap process completing.

. In the {ProjectWebUI}, navigate to *Hosts* > *All hosts* and ensure that the host is connected to the correct host group.

. Optional: After the host registration is complete, remove the script:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# rm bootstrap.py
----

[id="Setting_Permissions_for_the_Bootstrap_Script_{context}"]
== Setting Permissions for the Bootstrap Script

Use this procedure to configure a {Project} user with the permissions required to run the bootstrap script.
To use the CLI instead of the {ProjectWebUI}, see the xref:CLI_Setting_Permissions_for_the_Bootstrap_Script_{context}[].

.Procedure
. In the {ProjectWebUI}, navigate to *Administer* > *Users*.
. Select an existing user by clicking the required *Username*.
A new pane opens with tabs to modify information about the selected user.
Alternatively, create a new user specifically for the purpose of running this script.
. Click the *Roles* tab.
. Select *Edit hosts* and *Viewer* from the *Roles* list.
+
[IMPORTANT]
====
The *Edit hosts* role allows the user to edit and delete hosts as well as being able to add hosts.
If this is not acceptable to your security policy, create a new role with the following permissions and assign it to the user:

* `view_organizations`
* `view_locations`
* `view_domains`
* `view_hostgroups`
* `view_hosts`
* `view_architectures`
* `view_ptables`
* `view_operatingsystems`
* `create_hosts`
====

. Click *Submit*.

[id="CLI_Setting_Permissions_for_the_Bootstrap_Script_{context}"]
.CLI procedure
. Create a role with the minimum permissions required by the bootstrap script.
This example creates a role with the name _Bootstrap_:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ROLE='Bootstrap'
hammer role create --name "$ROLE"
hammer filter create --role "$ROLE" --permissions view_organizations
hammer filter create --role "$ROLE" --permissions view_locations
hammer filter create --role "$ROLE" --permissions view_domains
hammer filter create --role "$ROLE" --permissions view_hostgroups
hammer filter create --role "$ROLE" --permissions view_hosts
hammer filter create --role "$ROLE" --permissions view_architectures
hammer filter create --role "$ROLE" --permissions view_ptables
hammer filter create --role "$ROLE" --permissions view_operatingsystems
hammer filter create --role "$ROLE" --permissions create_hosts
----
. Assign the new role to an existing user:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer user add-role --id _user_id_ --role _Bootstrap_
----
+
Alternatively, you can create a new user and assign this new role to them.
For more information on creating users with Hammer, see {AdministeringDocURL}chap-Administering-Users_and_Roles[Managing Users and Roles] in the _Administering {ProjectName}_ guide.
