[id="removing-a-host-from-satellite"]
= Removing a Host from {ProjectName}

Use this procedure to remove a host from {ProjectName}.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *All hosts* or *Hosts* > *Content Hosts*.
Note that there is no difference from what page you remove a host, from *All hosts* or *Content Hosts*.
In both cases, {Project} removes a host completely.
. Select the hosts that you want to remove.
. From the *Select Action* list, select *Delete Hosts*.
. Click *Submit* to remove the host from {ProjectName} permanently.

[WARNING]
====
If a host record that is associated with a virtual machine is deleted, the virtual machine will be deleted as well.
To avoid deleting the virtual machine in this situation, disassociate the virtual machine from {Project} without removing it from the hypervisor.
====

[id="disassociating-a-virtual-machine"]
.Disassociating A Virtual Machine from {Project} without Removing it from a Hypervisor

. In the {Project} web UI, navigate to *Hosts* > *All Hosts* and select the check box to the left of the hosts to be disassociated.
. From the *Select Action* list, select the *Disassociate Hosts* button.
. Optionally, select the check box to keep the hosts for future action.
. Click *Submit*.
