[id="removing-a-host"]
[id="removing-a-host-from-satellite"]
= Removing a Host from {ProjectName}

Use this procedure to remove a host from {ProjectName}.

.Procedure
. In the {ProjectWebUI}, navigate to *Hosts* > *All hosts* or *Hosts* > *Content Hosts*.
Note that there is no difference from what page you remove a host, from *All hosts* or *Content Hosts*.
In both cases, {Project} removes a host completely.
. Select the hosts that you want to remove.
. From the *Select Action* list, select *Delete Hosts*.
. Click *Submit* to remove the host from {ProjectName} permanently.

[WARNING]
====
By default, the `Destroy associated VM on host delete` setting is set to `no`.
If a host record that is associated with a virtual machine is deleted, the virtual machine will remain on the compute resource.

To delete a virtual machine on the compute resource, navigate to *Administer > Settings* and select the *Provisioning* tab.
Setting `Destroy associated VM on host delete` to `yes` deletes the virtual machine if the host record that is associated with the virtual machine is deleted.
To avoid deleting the virtual machine in this situation, disassociate the virtual machine from {Project} without removing it from the compute resource or change the setting.
====

[id="disassociating-a-virtual-machine"]
== Disassociating A Virtual Machine from {Project} without Removing it from a Hypervisor

. In the {ProjectWebUI}, navigate to *Hosts* > *All Hosts* and select the check box to the left of the hosts to be disassociated.
. From the *Select Action* list, select the *Disassociate Hosts* button.
. Optionally, select the check box to keep the hosts for future action.
. Click *Submit*.
