[id="installing-tracer"]
= Installing Tracer

Use this procedure to install Tracer on Red{nbsp}Hat Satellite {ProductVersion}, and access Traces. Tracer displays a list of services and applications that are outdated and need to be restarted. Traces is the output generated by Tracer in the Satellite web UI.

IMPORTANT: The integration of Tracer with Satellite Server is a Technology Preview feature. Technology Preview features are not fully supported under Red Hat Subscription Service Level Agreements (SLAs), may not be functionally complete, and are not intended for production use. These features provide early access to upcoming product innovations, enabling customers to test functionality and provide feedback during the development process. For more information see link:https://access.redhat.com/support/offerings/techpreview/[Red Hat Technology Preview Features Support Scope].

.Prerequisites

* The host must be registered to Red{nbsp}Hat Satellite.
* The Red{nbsp}Hat {project-client-name} repository must be enabled and synchronized on Satellite Server, and enabled on the host.

.Procedure

. On the content host, install the `katello-host-tools-tracer` RPM package:
+
----
# yum install katello-host-tools-tracer
----

. Enter the following command:
+
----
# katello-tracer-upload
----

. In the Satellite web UI, navigate to *Hosts* > *All hosts*, then click the required host name.

. In the *Properties* tab, examine the *Properties* table and find the Traces item. If you cannot find a Traces item in the *Properties* table, then Tracer is not installed.

. Navigate to *Hosts* > *Content Hosts*, then click the required host name.

. Click the *Traces* tab to view Traces.
