[id="registering-a-host-to-project-using-the-global-registration-template_{context}"]
= Registering a Host to {ProjectName} Using the Global Registration Template

Use the following procedure to register a host to {ProjectNameX}.

With this registration method you can register hosts to {Project} by generating a `curl` command on {Project} and running this command on hosts.
This method uses the global registration template that gives you complete control over the process of the host registration.

ifeval::["{build}" != "satellite"]
Note that you can extend the parameters by plug-ins.
For more information, see https://github.com/theforeman/foreman/blob/develop/developer_docs/how_to_create_a_plugin.asciidoc.
endif::[]

.Prerequisites
* The {Project} user that generates the `curl` command must have the `create_hosts` permission.
* You must have root privileges on the host that you want to register.

.Procedure
. In the {Project} web UI, navigate to *Hosts* > *Provisioning Templates*, find the *Linux registration default* template and click it.

. Click the *Association* tab.

. Select the operating systems that you want to register.

. Click *Submit*.

. Navigate to *Hosts* > *Operating Systems* and click the operating system that you want to register.

. Click the *Templates* tab.

. From the *Registration template* list, select *Linux registration default*.

. Click *Submit*.

. Navigate to *Hosts* > *All Hosts* > *Register Host*.

. Optional: If you want to register hosts to {SmartProxy}, ensure that the *Registration* feature is enabled on this {SmartProxy}.
+
Navigate to *Infrastructure* > *{SmartProxies}*, click the {SmartProxy} that you want to use, and locate the *Registration* feature in the *Active features* list.
+
Optional: If the *Registration* feature is not enabled on your {SmartProxy}, enter the following command on the {SmartProxy} to enable it:
+
[options="nowrap", subs="+quotes,attributes"]
----
# foreman-installer --foreman-proxy-registration \
--foreman-proxy-templates \
--foreman-proxy-template-url 'http://{smartproxy-example-com}'
----

. Optional: From the *Host Group* list, select the host group to associate the hosts with.

. From the *Operating System* list, select the operating system of hosts that you want to register.

. Optional: If you want to register hosts to a {SmartProxy}, from the *{SmartProxy}* list, select the {SmartProxy} to register hosts to.

ifeval::["{build}" == "satellite"]
. From the *Insights* list, select whether you want to register the hosts to Insights or not.
endif::[]

. From the *Remote Execution* list, select whether you want to deploy {Project} SSH keys to hosts or not.

. Optional: {Project} uses the JSON Web Tokens (JWT) for authentication.
This duration of this token defines how long the generated `curl` command works.
If you want to change the duration of the token, enter the required duration to the *Token lifetime (hours)* field.
You can set the duration to any number of hours.
+
Note that {Project} uses the permissions of the user who generates the `curl` command for authorization of hosts.
If the user loses or gains additional permissions, the permissions of the JWT change too.
Therefore, do not delete, block, or change permissions of the user during the token duration.

. Optional: In the *Remote Execution Interface* field, enter a network interface that hosts must use for the SSH connection.

ifeval::["{build}" == "satellite"]
. In the *Activation Key(s)* field, enter one or more activation keys to assign to registered hosts.
endif::[]

ifeval::["{build}" != "satellite"]
. Optional: If you register RHEL or CentOS hosts, in the *Activation Key(s)* field, enter one or more activation keys to assign to registered hosts.
endif::[]

. Click *Generate command*.

. Copy the generated `curl` command to enter it on the hosts.

. Configure hosts with the CA certificate with one of the following methods:
+
* Add the `--insecure` option to the `curl` command.
This makes the first call insecure, however, during this first call, hosts download the CA file from {Project}.
Hosts will use this CA file to connect to {Project} with all future calls making them secure.
If an attacker fetches the CA file from the first insecure call, the attacker will be able to access the registered host, get the `curl` command with the JWT, and call the `/register` endpoint from {Project}.
The following is an example of the `curl` command with the `--insecure` option:
+
[options="nowrap", subs="+quotes,attributes"]
----
curl -X GET --insecure https://{foreman-example-com}/register...
----
+
* If you do not want to call the `curl` command with the `--insecure` option, you can manually copy and install the CA file on each host.
You can find where {Project} stores the CA file by navigating to *Administer* > *Settings* > *Authentication* and locating the value for the *SSL CA file* setting.

. On the hosts that you want to register, enter the `curl` command as `root`.

.Customizing the Templates

Note that all default templates in {Project} are locked.
If you want to customize the registration process, you need to clone the default Global registration template and change the *Default Global registration template* setting in *Administer* > *Settings* > *Provisioning*.

You can configure the following global parameters by navigating to *Configure* > *Global Parameters*:

* The `host_registration_remote_execution` parameter is used in the `remote_execution_ssh_keys` snippet, the default value is `true`.

ifeval::["{build}" != "satellite"]
* The `host_registration_insights` parameter is used in the `insights` snippet, the default value is `false`.
endif::[]

ifeval::["{build}" == "satellite"]
* The `host_registration_insights` parameter is used in the `insights` snippet, the default value is `true`.
endif::[]

.Templates & snippets
[cols=2*]
|===
|Global Registration Template
|Contains steps for registration of host to the {Project}. Rendered when accessing `/register` endpoint.

|Host Registration Template
|In {Project} named `Linux registration default`, contains commands for Host setup.

|`remote_execution_ssh_keys` snippet
| Used in Host registration template, deploy SSH keys to the host. Only when `host_registration_remote_execution` parameter is `true`. Part of Host registration template

|`insights` snippet
| Download & install insights client. Only for Red Hat OS & when global parameter `host_registration_insights` is set to true. Part of Host registration template
|===

.Global Registration templates variables
[cols=3*,options=header]
|===
|Variable
|Command argument
|Description

|`@user`
|none
|Current authenticated user object.

|`@organization`
|`organization_id`
|If `organization_id` is not set, then user's default organization is set, or the first organization from user's organizations list.

|`@location`
|`location_id`
|If `location_id` is not set, user  default location is set, or the first location from user's locations list.

|`@hostgroup`
|`hostgroup_id`
|Host group of the host.

|`@operatingsystem`
|`operatingsystem_id`
|Host OS.

|`@setup_insights`
|`setup_insights`
|Override the value of `` global parameter for the registered host & install insights client.

|`@setup_remote_execution`
|`setup_remote_execution`
| Override the value of `` global parameter for the registered host & deploy SSH keys for remote execution.

|`@remote_execution_interface`
|`remote_execution_interface`
|Set default interface of host for the remote execution.

|`@activation_key`
|`activation_key`
|Activation keys for subscription manager, available only with katello plugin.

|`@registration_url`
|none
|URl for `/register` endpoint.
|===
