[[managing_and_monitoring_hosts_using_red_hat_web_console]]
= Managing and Monitoring Hosts Using {Cockpit}

You can access the {Cockpit} web UI through the {Project} web UI and use the functionality to manage and monitor hosts in {Project}.

.Prerequisites

* {Cockpit} is enabled in {Project}.
* {Cockpit} is installed on the host that you want to view:

ifeval::["{build}" != "satellite"]
** For more information see https://cockpit-project.org/running.html[Running Cockpit].
endif::[]

ifeval::["{build}" == "satellite"]
** For Red{nbsp}Hat Enterprise Linux 8, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/getting-started-with-the-rhel-8-web-console_system-management-using-the-rhel-8-web-console#installing-the-web-console_getting-started-with-the-rhel-8-web-console[Installing the web console] in the _Managing systems using the RHEL 8 web console_ guide.
** For Red{nbsp}Hat Enterprise Linux 7, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/managing_systems_using_the_rhel_7_web_console/getting-started-with-the-rhel-web-console_system-management-using-the-rhel-7-web-console#installing-the-web-console_getting-started-with-the-web-console[Installing the web console] in the _Managing systems using the RHEL 7 web console_ guide.
endif::[]

* {Project} or {SmartProxy} can authenticate to the host with SSH keys. For more information, xref:sect-Managing_Hosts-Establishing_a_Secure_Connection_for_Remote_Commands[].

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *All Hosts* and select the host that you want to manage and monitor with {Cockpit}.
. In the upper right of the host window, click *Web Console*.

You can now access the full range of features available for host monitoring and management, for example, {LoraxCompose}, through the {Cockpit}.

ifeval::["{build}" == "satellite"]
For more information about getting started with Red Hat web console, see the https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/index[_Managing systems using the RHEL 8 web console_] guide or the https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/managing_systems_using_the_rhel_7_web_console/getting-started-with-the-rhel-web-console_system-management-using-the-rhel-7-web-console#installing-the-web-console_getting-started-with-the-web-console[_Managing systems using the RHEL 7 web console_] guide.

For more information about using {LoraxCompose} through {Cockpit}, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/composing_a_customized_rhel_system_image/creating-system-images-with-composer-web-console-interface_composing-a-customized-rhel-system-image#accessing-composer-gui-in-the-rhel-8-web-console_creating-system-images-with-composer-web-console-interface[Accessing Image Builder GUI in the RHEL 8 web console] or https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/image_builder_guide/chap-documentation-image_builder-test_chapter_4#sect-Documentation-Image_Builder-Chapter4[Accessing Image Builder GUI in the RHEL 7 web console].
endif::[]
