[[ref_important_macros_for_report_templates]]
= Report Templates Macros

If you want to write custom report templates, you can use some of the following macros to build report templates. For more information about the available macros for report templates, in the {Project} web UI, navigate to *Monitor* > *Report Templates*, and click *Create Template*. In the Create Template window, click the *Help* tab.

For more information about writing report templates, see xref:proc_creating_a_report_template[].

input::
Using the `input` macro, you can customize the input data that the template can work with. You can define the input name, type, and the options that are available for users. For report templates, you can only use user inputs.
+
[options="nowrap" subs="+quotes"]
----
<%= input('cpus') %>
----
+
This loads the value from user input `cpus`.

load_hosts::
Using the `load_hosts` macro, you can generate a complete list of hosts.
+
[options="nowrap" subs="+quotes"]
----
<%- load_hosts().each_record do |host| -%>
<%=     host.name %>
----
+
Use the `load_hosts` macro with the `each_record` macro to load records in batches of 1000 to reduce memory consumption.

report_row::
Using the `report_row` macro, you can create reports in `.csv` format for ease of analysis.
+
[options="nowrap" subs="+quotes"]
----
<%-   report_row(
        'Server FQDN': host.name
      ) -%>
----

report_render::
Using the `report_render` macro, you can define the output of the report. For example, if you want the output of the report in YAML format, you can specify the format.
+
[options="nowrap" subs="+quotes"]
----
<%= report_render format: :yaml -%>
----
