[id="advanced-bootstrap-script-configuration"]
= Advanced Bootstrap Script Configuration

This section has more examples for using the bootstrap script to register or migrate a host.

[WARNING]
====
These examples specify the `admin` {Project} user.
If this is not acceptable to your security policy, create a new role with the minimum permissions required by the bootstrap script.
For more information, see xref:setting-permissions-for-the-bootstrap-script[].
====

== Migrating a host from one {ProjectX} to another {ProjectX}

Use the script with `--force` to remove the `katello-ca-consumer-{asterisk}` packages from the old {Project} and install the `katello-ca-consumer-{asterisk}` packages on the new {Project}.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--force
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--force
----

== Migrating a host from Red Hat Network (RHN) or {Project} 5 to {ProjectX}

The bootstrap script detects the presence of `/etc/syconfig/rhn/systemid` and a valid connection to RHN as an indicator that the system is registered to a legacy platform.
The script then calls `rhn-classic-migrate-to-rhsm` to migrate the system from RHN.
By default, the script does not delete the system's legacy profile due to auditing reasons.
To remove the legacy profile, use `--legacy-purge`, and use `--legacy-login` to supply a user account that has appropriate permissions to remove a profile.
Enter the user account password when prompted.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--legacy-purge \
--legacy-login _rhn-user_
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--legacy-purge \
--legacy-login _rhn-user_
----

== Registering a host to {ProjectX}, omitting Puppet setup

By default, the bootstrap script configures the host for content management and configuration management.
If you have an existing configuration management system and do not want to install Puppet on the host, use `--skip-puppet`.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--skip-puppet
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--skip-puppet
----

== Registering a host to {ProjectX} for content management only

To register a system as a content host, and omit the provisioning and configuration management functions, use `--skip-foreman`.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--server _{foreman-example-com}_ \
--organization=_"Example Organization"_ \
--activationkey=_activation_key_ \
--skip-foreman
----
* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --server _{foreman-example-com}_ \
--organization=_"Example Organization"_ \
--activationkey=_activation_key_ \
--skip-foreman
----

== Changing the method the bootstrap script uses to download the consumer RPM

By default, the bootstrap script uses HTTP to download the consumer RPM (__server.example.com__/pub/katello-ca-consumer-latest.noarch.rpm).
In some environments, you might want to allow HTTPS only between the host and {Project}.
Use `--download-method` to change the download method from HTTP to HTTPS.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--download-method https
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--download-method https
----

== Providing the host's IP address to {Project}

On hosts with multiple interfaces or multiple IP addresses on one interface, you might need to override the auto-detection of the IP address and provide a specific IP address to {Project}.
Use `--ip`.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--ip _192.x.x.x_
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--ip _192.x.x.x_
----

== Enabling remote execution on the host

Use `--rex` and `--rex-user` to enable remote execution and add the required SSH keys for the specified user.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--rex \
--rex-user _root_
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--rex \
--rex-user _root_
----

== Creating a domain for a host during registration

To create a host record, the DNS domain of a host needs to exist in {Project} prior to running the script.
If the domain does not exist, add it using `--add-domain`.

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py \
--login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--add-domain
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--add-domain
----

== Providing an alternative FQDN for the host

If the host's host name is not an FQDN, or is not RFC-compliant (containing a character such as an underscore), the script will fail at the host name validation stage.
If you cannot update the host to use an FQDN that is accepted by {Project}, you can use the bootstrap script to specify an alternative FQDN.

. Set `create_new_host_when_facts_are_uploaded` and `create_new_host_when_report_is_uploaded` to false using Hammer:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# hammer settings set \
--name  create_new_host_when_facts_are_uploaded \
--value false
# hammer settings set \
--name  create_new_host_when_report_is_uploaded \
--value false
----

. Use `--fqdn` to specify the FQDN that will be reported to {Project}:

* On Red{nbsp}Hat Enterprise Linux 8, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# /usr/libexec/platform-python bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--fqdn _node100.example.com_
----

* On Red{nbsp}Hat Enterprise Linux 5, 6, or 7, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# bootstrap.py --login=_admin_ \
--server _{foreman-example-com}_ \
--location=_"Example Location"_ \
--organization=_"Example Organization"_ \
--hostgroup=_"Example Host Group"_ \
--activationkey=_activation_key_ \
--fqdn _node100.example.com_
----
