[id="using-insights-with-satellite-hosts"]
= Using Red{nbsp}Hat Insights with Hosts in {Project}

You can use Red{nbsp}Hat Insights to diagnose systems and downtime related to security exploits, performance degradation and stability failures. You can use the dashboard to quickly identify key risks to stability, security, and performance. You can sort by category, view details of the impact and resolution, and then determine what systems are affected.

To use Red{nbsp}Hat Insights to monitor hosts that you manage with {Project}, you must first install Red{nbsp}Hat Insights on your hosts and register your hosts with Red{nbsp}Hat Insights.

To install and register your host using Puppet, or manually, see https://access.redhat.com/products/red-hat-insights/#getstarted[Red{nbsp}Hat Insights Getting Started].

.Deploying Red{nbsp}Hat Insights using the Ansible Role

You can automate the installation and registration of hosts with Red{nbsp}Hat Insights using the *RedHatInsights.insights-client* Ansible role. For more information about adding this role to your {Project}, see {BaseURL}administering_red_hat_satellite/chap-{Project_Link}-Administering_{Project_Link}-Managing_Ansible_Roles[Managing Ansible Roles].

. Add the *RedHatInsights.insights-client* role to the hosts.
+
For new hosts, see xref:creating-a-host-in-satellite[].
+
For existing hosts, see xref:Using_Ansible_Roles[].
+
. To run the *RedHatInsights.insights-client* role on your host, navigate to *Hosts* > *All Hosts* and click the name of the host that you want to use.
. Click the *Run Ansible roles* button.

When the role completes, you can view and work with the host that you add on the *Insights* > *Overview* page of the {Project} web UI.

.Additional Information

* To apply any system updates to the Red{nbsp}Hat Insights plug-in, enter `httpd restart` after updating.
* To view the logs for Red{nbsp}Hat Insights and all plug-ins, go to `/var/log/foreman/production.log`.
* If you have problems connecting to Red{nbsp}Hat Insights, ensure that your certificates are up-to-date. Refresh your subscription manifest to update your certificates.
* You can change the default schedule for running `insights-client` by configuring `insights-client.timer` on a host. For more information, see https://access.redhat.com/documentation/en-us/red_hat_insights/2020-04/html/client_configuration_guide_for_red_hat_insights/changing-the-client-schedule[Changing the insights-client schedule] in the _Client Configuration Guide for Red Hat Insights_.
