[id="adding-permissions-to-a-role_{context}"]
= Adding Permissions to a Role

Use this procedure to add permissions to a role.
To use the CLI instead of the {ProjectWebUI}, see the xref:cli-adding-permissions-to-a-role_{context}[].

.Procedure
. Navigate to *Administer* > *Roles*.
. Select *Add Filter* from the drop-down list to the right of the required role.
. Select the *Resource type* from the drop-down list.
The _(Miscellaneous)_ group gathers permissions that are not associated with any resource group.
. Click the permissions you want to select from the *Permission* list.
. Depending on the *Resource type* selected, you can select or deselect the *Unlimited* and *Override* check box.
The *Unlimited* check box is selected by default, which means that the permission is applied on all resources of the selected type.
When you disable the *Unlimited* check box, the *Search* field activates.
In this field you can specify further filtering with use of the {ProjectNameX} search syntax.
See xref:sect-Administering-Users_and_Roles-Granular_Permission_Filtering[] for details.
When you enable the *Override* check box, you can add additional locations and organizations to allow the role to access the resource type in the additional locations and organizations; you can also remove an already associated location and organization from the resource type to restrict access.
. Click *Next*.
. Click *Submit* to save changes.

[id="cli-adding-permissions-to-a-role_{context}"]
.CLI procedure

. List all available permissions:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer filter available-permissions
----

. Add permissions to a role:
+
[options="nowrap", subs="+quotes,attributes"]
----
# hammer filter create \
--role _role_name_ \
--permission-ids _perm_ID1_,_perm_ID2_...
----

For more information about roles and permissions parameters, enter the `hammer role --help` and `hammer filter --help` commands.
