[id="backing-up-satellite-server-and-capsule-server"]

== Backing Up {ProjectServer} and {SmartProxyServer}

You can back up your {Project} deployment to ensure the continuity of your {ProjectName} deployment and associated data in the event of a disaster.
If your deployment uses custom configurations, you must consider how to handle these custom configurations when you plan your backup and disaster recovery policy.

To create a backup of your {ProjectServer} or {SmartProxyServer} and all associated data, use the `satellite-maintain backup` command. Backing up to a separate storage device on a separate system is highly recommended.

{Project} services are unavailable during the backup.
Therefore, you must ensure that no other tasks are scheduled by other administrators.
You can schedule a backup using `cron`. For more information, see the xref:example-of-a-weekly-full-backup-followed-by-daily-incremental-backups_{context}[].

During offline or snapshot backups, the services are inactive and {Project} is in a maintenance mode. All the traffic from outside on port 443 is rejected by a firewall to ensure there are no modifications triggered.

A backup contains sensitive information from the `/root/ssl-build` directory. For example, it can contain hostnames, ssh keys, request files and SSL certificates. You must encrypt or move the backup to a secure location to minimize the risk of damage or unauthorized access to the hosts.

.Conventional Backup Methods

You can also use conventional backup methods. For more information, see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/part-System_Backup_and_Recovery.html[System Backup and Recovery] in the _Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 System Administrator's Guide_.

NOTE: If you plan to use the `satellite-maintain backup` command to create a backup, do not stop the `satellite-maintain` services.

* When creating a snapshot or conventional backup, you must stop all services as follows:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# satellite-maintain service stop
----

* Start the services after creating a snapshot or conventional backup:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# satellite-maintain service start
----

//Estimating the Size of a Backup
include::proc_estimating-the-size-of-a-backup.adoc[leveloffset=+2]

//Performing a Full Backup of {ProjectServer} or {SmartProxyServer}
include::proc_performing-a-full-backup-of-satellite-or-capsule.adoc[leveloffset=+2]

//Performing a Backup without Pulp Content
include::proc_performing-a-backup-without-pulp-content.adoc[leveloffset=+2]

//Performing an Incremental Backup
include::proc_performing-an-incremental-backup.adoc[leveloffset=+2]

//Example of a Weekly Full Backup Followed by Daily Incremental Backups
include::ref_example-of-a-weekly-full-backup-followed-by-daily-incremental-backups.adoc[leveloffset=+2]

//Performing an Online Backup
include::proc_performing-an-online-backup.adoc[leveloffset=+2]

//Performing a Snapshot Backup
include::proc_performing-a-snapshot-backup.adoc[leveloffset=+2]

//White-listing and Skipping Steps When Performing Backups
include::ref_white-listing-and-skipping-steps-when-performing-backups.adoc[leveloffset=+2]
