[id='configuring-a-host-for-openscap_{context}']
= Configuring a host for OpenSCAP

Use this procedure to configure all the OpenSCAP requirements for a host.

.OpenSCAP Setup Overview

You must complete the following tasks on Satellite Server to assign the necessary components for a host:

* Enable OpenSCAP on Capsule. For more information, see https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersion}/html/installing_capsule_server/performing-additional-configuration-on-capsule-server#enabling-openscap_capsule[Enabling OpenSCAP on External Capsules] in the _Installing Capsule Server_ guide.
* Assign an OpenSCAP Capsule.
* Assign a Puppet environment that contains the Puppet classes to deploy the OpenSCAP policies.
* Assign the `foreman_scap_client` and `foreman_scap_client::params` Puppet classes.
* Assign any compliance policies that you want to add.

For information about creating and administering hosts, see the https://access.redhat.com/documentation/en-us/red_hat_satellite/6.5/html/managing_hosts/index[Managing Hosts] guide.

.Procedure

. In the Satellite web UI, navigate to *Hosts* > *All Hosts*, and select *Edit* on the host you want to configure for OpenSCAP reporting.
. From the *Puppet Environment* list, select the Puppet environment that contains the `foreman_scap_client` and `foreman_scap_client::params` Puppet classes.
. From the *OpenSCAP Capsule* list, select the Capsule with OpenSCAP enabled that you want to use.
. Click the *Puppet Classes* tab, and add the `foreman_scap_client` and `foreman_scap_client::params` Puppet classes.
. To add a compliance policy, navigate to one of the following locations:
. Navigate to *Hosts* > *All Hosts*,
. Select the host or hosts to which you want to add the policy.
. Click *Select Action*.
. Select *Assign Compliance Policy* from the list.
. In the Policy window, select the policy that you want from the list of available policies and click *Submit*.
