[[chap-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication]]
== Configuring External Authentication

By using external authentication you can derive user and user group permissions from user group membership in an external identity provider. When you use external authentication, you do not have to create these users and maintain their group membership manually on Satellite Server.

.Important User and Group Account Information
All user and group accounts must be local accounts. This is to ensure that there are no authentication conflicts between local accounts on your Satellite Server and accounts in your Active Directory domain.

Your system is not affected by this conflict if your user and group accounts exist in both `/etc/passwd` and `/etc/group` files. For example, to check if entries for `puppet`, `apache`, `foreman` and `foreman-proxy` groups exist in both `/etc/passwd` and `/etc/group` files, enter the following commands:

[options="nowrap" subs="+quotes,verbatim"]
----
# cat /etc/passwd | grep 'puppet\|apache\|foreman\|foreman-proxy'
# cat /etc/group | grep 'puppet\|apache\|foreman\|foreman-proxy'
----

.Scenarios for Configuring External Authentication

Red{nbsp}Hat Satellite supports the following general scenarios for configuring external authentication:

* Using _Lightweight Directory Access Protocol_ (LDAP) server as an external identity provider. LDAP is a set of open protocols used to access centrally stored information over a network. With Satellite, you can manage LDAP entirely through the Satellite web UI. For more information, see xref:sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Using_LDAP[]. Though you can use LDAP to connect to an IdM or AD server, the setup does not support server discovery, cross-forest trusts, or single sign-on with Kerberos in Satellite's web UI.

* Using _Red{nbsp}Hat Enterprise Linux Identity Management_ (IdM) server as an external identity provider. IdM deals with the management of individual identities, their credentials and privileges used in a networking environment. Configuration using IdM cannot be completed using only the Satellite web UI and requires some interaction with the CLI. For more information see xref:sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication-Using_Identity_Management[].

* Using _Active Directory_ (AD) integrated with IdM through cross-forest Kerberos trust as an external identity provider. For more information see xref:active-directory-with-cross-forest-trust_{context}[].

* Using Red Hat Single Sign-On as an OpenID provider for external authentication to Satellite with CAC cards. For more information, see xref:integrating-satellite-with-red-hat-single-sign-on-for-external-authentication[].

As well as providing access to Satellite Server, hosts provisioned with Satellite can also be integrated with IdM realms. Red{nbsp}Hat Satellite has a realm feature that automatically manages the life cycle of any system registered to a realm or domain provider. For more information, see xref:sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication-External_Authentication_for_Provisioned_Hosts[].

.Authentication Overview
|====
|Type |Authentication | User Groups

|IdM | Kerberos or LDAP | Yes
|Active Directory | Kerberos or LDAP | Yes
|POSIX | LDAP | Yes

|====

include::Configuring_LDAP_Authentication_for_Red_Hat_Satellite.adoc[]

include::Using_IdM.adoc[]

include::Using_Active_Directory.adoc[]

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Creating_User_Groups-Configuring_External_User_Groups]]
=== Configuring External User Groups

Satellite does not associate external users with their user group automatically. You must create a user group with the same name as in the external source on Satellite. Members of the external user group then automatically become members of the Satellite user group and receive the associated permissions.

The configuration of external user groups depends on the type of external authentication.

To assign additional permissions to an external user, add this user to an internal user group that has no external mapping specified. Then assign the required roles to this group.

[[br-external_user_groups_prerequisites]]
.Prerequisites

* If you use an LDAP server, configure Satellite to use LDAP authentication. For more
information see xref:sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Using_LDAP[].
+
When using external user groups from an LDAP source, you cannot use the `$login` variable as a substitute for the account user name. You must use either an anonymous or dedicated service user.

* If you use an IdM or AD server, configure Satellite to use IdM or AD authentication. For more information, see xref:chap-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication[].

* Ensure that at least one external user authenticates for the first time.

* Retain a copy of the external group names you want to use. To find the group membership of external users, enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# id _username_
----

[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_User_Groups-To_Configure_an_External_User_Group]]
.To Configure an External User Group:

. In the Satellite web UI, navigate to *Administer* > *User Groups*, and click *Create User Group*.

. Specify the name of the new user group. Do not select any users to avoid adding users automatically when you refresh the external user group.

. Click the *Roles* tab and select the roles you want to assign to the user group. Alternatively, select the *Administrator* check box to assign all available permissions.

. Click the *External groups* tab, then click *Add external user group*, and select an authentication source from the *Auth source* drop-down menu.
+
Specify the exact name of the external group in the *Name* field.

. Click *Submit*.

=== Refreshing External User Groups for LDAP

To set the LDAP source to synchronize user group membership automatically on user login, in the *Auth Source* page, select the *Usergroup Sync* option. If this option is not selected, LDAP user groups are refreshed automatically through a scheduled cron job synchronizing the LDAP Authentication source every 30 minutes by default.

If the user groups in the LDAP Authentication source change in the lapse of time between scheduled tasks, the user can be assigned to incorrect external user groups. This is corrected automatically when the scheduled task runs.

Use this procedure to refresh the LDAP source manually.

.Procedure

. Navigate to *Administer* > *Usergroups* and select a user group.
. Navigate to the *External Groups* tab and click *Refresh* to the right of the required user group.

.For CLI Users

Enter the following command:

----
# foreman-rake ldap:refresh_usergroups
----

=== Refreshing External User Groups for IdM or AD
External user groups based on IdM or AD are refreshed only when a group member logs in to Satellite. It is not possible to alter user membership of external user groups in the Satellite web UI, such changes are overwritten on the next group refresh.


[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication-External_Authentication_for_Provisioned_Hosts]]
=== External Authentication for Provisioned Hosts

Use this section to configure Satellite Server or Capsule Server for IdM realm support, then add hosts to the IdM realm group.

*Prerequisites*

You require the following setup to configure external authentication for provisioned hosts:

* Satellite Server that is registered to the Content Delivery Network or an external Capsule Server that is registered to Satellite Server.

* A deployed realm or domain provider such as Red{nbsp}Hat Identity Management.

[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_a_Red_Hat_Satellite_Server_or_Capsule_Server_for_IdM_Realm_Support-To_configure_the_Satellite_Server_or_Capsule_Server_for_IdM_Realm_Support]]
.To install and configure IdM packages on Red Hat Satellite Server or Red Hat Satellite Capsule Server:

To use IdM for provisioned hosts, complete the following steps to install and configure IdM packages on Red{nbsp}Hat Satellite Server or Red{nbsp}Hat Satellite Capsule Server:

. Install the `ipa-client` package on Satellite Server or Capsule Server:
+
* On Satellite Server, enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-maintain packages install ipa-client
----
+
* On Capsule Server, enter the following command:
+
----
# yum install ipa-client
----

. Configure the server as an IdM client:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ipa-client-install
----
. Create a realm proxy user, `realm-capsule`, and the relevant roles in Red Hat Identity Management:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# foreman-prepare-realm admin realm-capsule
----
+
Note the principal name that returns and your Identity Management server configuration details because you require them for the following procedure.

[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_IdM]]
.To configure Satellite Server or Capsule Server for IdM Realm Support:

Complete the following procedure on Satellite and every Capsule that you want to use:

. Copy the `/root/freeipa.keytab` file to any Capsule Server that you want to include in the same principal and realm:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# scp /root/freeipa.keytab root@_capsule.example.com_:/etc/foreman-proxy/freeipa.keytab
----
+
. Move the `/root/freeipa.keytab` file to the `/etc/foreman-proxy` directory and set the ownership settings to the `foreman-proxy` user:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# mv /root/freeipa.keytab /etc/foreman-proxy
# chown foreman-proxy:foreman-proxy /etc/foreman-proxy/freeipa.keytab
----
+
. Enter the following command on all Capsules that you want to include in the realm. If you use the integrated Capsule on Satellite, enter this command on Satellite Server:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-installer --foreman-proxy-realm true \
--foreman-proxy-realm-keytab /etc/foreman-proxy/freeipa.keytab \
--foreman-proxy-realm-principal _realm-capsule@EXAMPLE.COM_ \
--foreman-proxy-realm-provider freeipa
----
+
You can also use these options when you first configure the Red{nbsp}Hat Satellite Server.
+
. Ensure that the most updated versions of the ca-certificates package is installed and trust the IdM Certificate Authority:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# cp /etc/ipa/ca.crt /etc/pki/ca-trust/source/anchors/ipa.crt
# update-ca-trust enable
# update-ca-trust
----
+
. Optional: If you configure IdM on an existing Satellite Server or Capsule Server, complete the following steps to ensure that the configuration changes take effect:
.. Restart the *foreman-proxy* service:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# systemctl restart foreman-proxy
----
+
.. In the Satellite web UI, navigate to *Infrastructure* > *Capsules*.
.. Locate the Capsule you have configured for IdM and from the list in the *Actions* column, select *Refresh*.


[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Creating_a_Realm_for_the_IdM_enabled_Capsule]]
.To create a realm for the IdM-enabled Capsule

After you configure your integrated or external Capsule with IdM, you must create a realm and add the IdM-configured Capsule to the realm.

To create a realm, complete the following steps:

. In the Satellite web UI, navigate to *Infrastructure* > *Realms* and click *Create Realm*.
. In the *Name* field, enter a name for the realm.
. From the *Realm Type* list, select the type of realm.
. From the *Realm Capsule* list, select the Capsule Server where you have configured IdM.
. Click the *Locations* tab and from the *Locations* list, select the location where you want to add the new realm.
. Click the *Organizations* tab and from the *Organizations* list, select the organization where you want to add the new realm.
. Click *Submit*.

.Updating Host Groups with Realm Information
You must update any host groups that you want to use with the new realm information.

. Navigate to *Configure* > *Host Groups*, select the host group that you want to update, and click the *Network* tab.
. From the *Realm* list, select the realm you create as part of this procedure, and then click *Submit*.

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-External_Authentication_for_Provisioned_Hosts-Adding_Hosts_to_an_IdM_Host_Group]]
.Adding Hosts to an IdM Host Group

Red{nbsp}Hat Enterprise Linux Identity Management (IdM) supports the ability to set up automatic membership rules based on a system's attributes. Red{nbsp}Hat Satellite's realm feature provides administrators with the ability to map the Red{nbsp}Hat Satellite host groups to the IdM parameter `userclass` which allow administrators to configure automembership.

When nested host groups are used, they are sent to the IdM server as they are displayed in the Red{nbsp}Hat Satellite User Interface. For example, "Parent/Child/Child".

Satellite Server or Capsule Server sends updates to the IdM server, however automembership rules are only applied at initial registration.


[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Adding_Hosts_to_an_IdM_Host_Group-To_Add_Hosts_to_an_IdM_Host_Group]]
.To Add Hosts to an IdM Host Group:

. On the IdM server, create a host group:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ipa hostgroup-add _hostgroup_name_ --desc=_hostgroup_description_
----
+
. Create an `automembership` rule:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ipa automember-add --type=hostgroup _hostgroup_name_ _automember_rule_
----
+
Where you can use the following options:
+
* `automember-add` flags the group as an automember group.
* `--type=hostgroup` identifies that the target group is a host group, not a user group.
* `_automember_rule_` adds the name you want to identify the automember rule by.
+
. Define an automembership condition based on the `userclass` attribute:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# ipa automember-add-condition --key=userclass --type=hostgroup --inclusive-regex=_^webserver_ _hostgroup_name_
----------------------------------
Added condition(s) to "_hostgroup_name_"
----------------------------------
Automember Rule: _automember_rule_
Inclusive Regex: userclass=_^webserver_
----------------------------
Number of conditions added 1
----------------------------
----
+
Where you can use the following options:
+
* `automember-add-condition` adds regular expression conditions to identify group members.
* `--key=userclass` specifies the key attribute as `userclass`.
* `--type=hostgroup` identifies that the target group is a host group, not a user group.
* `--inclusive-regex=` _^webserver_ identifies matching values with a regular expression pattern.
* _hostgroup_name_ - identifies the target host group's name.

When a system is added to Satellite Server's _hostgroup_name_ host group, it is added automatically to the Identity Management server's "_hostgroup_name_" host group. IdM host groups allow for Host-Based Access Controls (HBAC), sudo policies and other IdM functions.

include::proc_integrating-satellite-with-red-hat-single-sign-on-for-external-authentication.adoc[leveloffset=+2]
