[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Using_LDAP]]
=== Using LDAP

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Using_Configuring_TLS_for_Secure-LDAP]]

If you require {ProjectName} to use `TLS` to establish a secure LDAP connection (LDAPS), first obtain certificates used by the LDAP server you are connecting to and mark them as trusted on the base operating system of your {ProjectServer} as described below. If your LDAP server uses a certificate chain with intermediate certificate authorities, all of the root and intermediate certificates in the chain must be trusted, so ensure all certificates are obtained. If you do not require secure LDAP at this time, proceed to xref:configuring-red-hat-satellite-to-use-ldap_{context}[].


.Using SSSD Configuration
Though direct LDAP integration is covered in this section, Red{nbsp}Hat recommends that you use SSSD and configure it against {FreeIPA}, AD, or an LDAP server. SSSD improves the consistency of the authentication process. For more information about the preferred configurations, see xref:sect-{Project_Link}-Administering_{Project_Link}-Configuring_External_Authentication-Using_Active_Directory[]. You can also cache the SSSD credentials and use them for LDAP authentication. For more information on SSSD, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system-level_authentication_guide/sssd[Configuring SSSD] in the _Red{nbsp}Hat{nbsp}Enterprise{nbsp}Linux 7 System-Level Authentication Guide_.


include::configuring-tls-for-secure-ldap.adoc[leveloffset=+3]

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Using_Configuring_Red_Hat_Satellite_to_Use_LDAP]]

include::configuring-red-hat-satellite-to-use-ldap.adoc[leveloffset=+3]

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-LDAP_Settings]]
include::description-of-ldap-settings.adoc[leveloffset=+3]
include::example-settings-for-ldap-connections.adoc[leveloffset=+3]
include::example-ldap-filters.adoc[leveloffset=+3]
