[id='configuring-logging-to-journal']
= Configuring Logging to Journal

You can configure {Project} to manage logging with Journal.
Journal then forwards log messages to `rsyslog` and `rsyslog` writes the log messages to `/var/log/messages`.
Note that after this change the log messages do not appear in `/var/log/foreman/production.log` or `/var/log/foreman-proxy.log` any more.

ifeval::["{build}" == "satellite"]
For more information about Journal, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-viewing_and_managing_log_files#s1-Using_the_Journal[Using the Journal] in the _Red{nbsp}Hat Enterprise{nbsp}Linux 7 System Administrator's guide_.
endif::[]
ifeval::["{build}" != "satellite"]
For more information about Journal, see https://github.com/lzap/foreman-elasticsearch[].
endif::[]

.Procedure

To configure {ProjectServer} logging with Journal, complete the following steps:

. Enter the following `{foreman-installer}` command to configure logging to `journald`:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-logging-level info \
--foreman-logging-type journald \
--foreman-logging-layout pattern --foreman-proxy-log JOURNAL
----

. Restart the Apache daemon:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service restart --only httpd
----
