[id="Configuring_External_Authentication_{context}"]
== Configuring External Authentication

By using external authentication you can derive user and user group permissions from user group membership in an external identity provider.
When you use external authentication, you do not have to create these users and maintain their group membership manually on {ProjectServer}.

.Important User and Group Account Information
All user and group accounts must be local accounts.
This is to ensure that there are no authentication conflicts between local accounts on your {ProjectServer} and accounts in your Active Directory domain.

Your system is not affected by this conflict if your user and group accounts exist in both `/etc/passwd` and `/etc/group` files.
For example, to check if entries for `puppet`, `apache`, `foreman` and `foreman-proxy` groups exist in both `/etc/passwd` and `/etc/group` files, enter the following commands:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cat /etc/passwd | grep 'puppet\|apache\|foreman\|foreman-proxy'
# cat /etc/group | grep 'puppet\|apache\|foreman\|foreman-proxy'
----

.Scenarios for Configuring External Authentication

{ProjectName} supports the following general scenarios for configuring external authentication:

* Using _Lightweight Directory Access Protocol_ (LDAP) server as an external identity provider.
LDAP is a set of open protocols used to access centrally stored information over a network.
With {Project}, you can manage LDAP entirely through the {ProjectWebUI}.
For more information, see xref:sect-Administering-Using_LDAP[].
Though you can use LDAP to connect to a {FreeIPA} or AD server, the setup does not support server discovery, cross-forest trusts, or single sign-on with Kerberos in {Project}'s web UI.

* Using a {FreeIPA} server as an external identity provider.
{FreeIPA} deals with the management of individual identities, their credentials and privileges used in a networking environment.
Configuration using {FreeIPA} cannot be completed using only the {ProjectWebUI} and requires some interaction with the CLI.
For more information see xref:sect-Administering-Configuring_External_Authentication-Using_Identity_Management[].

* Using _Active Directory_ (AD) integrated with {FreeIPA} through cross-forest Kerberos trust as an external identity provider.
For more information see xref:active-directory-with-cross-forest-trust_{context}[].

* Using {Keycloak} as an OpenID provider for external authentication to {Project}.
For more information, see xref:configuring-project-with-keycloak-authentication_admin[].

* Using {Keycloak} as an OpenID provider for external authentication to {Project} with TOTP.
For more information, see xref:configuring-keycloak-authentication-with-totp_admin[].

ifndef::satellite,orcharhino[]
* Using {Keycloak} as an OpenID provider for external authentication to {Project} with {PIV} cards.
For more information, see xref:configuring-keycloak-authentication-with-cac-cards_admin[].
endif::[]

As well as providing access to {ProjectServer}, hosts provisioned with {Project} can also be integrated with {FreeIPA} realms.
{ProjectName} has a realm feature that automatically manages the life cycle of any system registered to a realm or domain provider.
For more information, see xref:sect-Administering-Configuring_External_Authentication-External_Authentication_for_Provisioned_Hosts[].

.Authentication Overview
|====
|Type |Authentication | User Groups

|{FreeIPA} | Kerberos or LDAP | Yes
|Active Directory | Kerberos or LDAP | Yes
|POSIX | LDAP | Yes

|====

include::Configuring_LDAP_Authentication_for_Red_Hat_Satellite.adoc[]

include::Using_IdM.adoc[]

include::Using_Active_Directory.adoc[]

[[sect-Administering-Creating_User_Groups-Configuring_External_User_Groups]]
=== Configuring External User Groups

{Project} does not associate external users with their user group automatically.
You must create a user group with the same name as in the external source on {Project}.
Members of the external user group then automatically become members of the {Project} user group and receive the associated permissions.

The configuration of external user groups depends on the type of external authentication.

To assign additional permissions to an external user, add this user to an internal user group that has no external mapping specified.
Then assign the required roles to this group.

[[br-external_user_groups_prerequisites]]
.Prerequisites

* If you use an LDAP server, configure {Project} to use LDAP authentication.
For more information see xref:sect-Administering-Using_LDAP[].
+
When using external user groups from an LDAP source, you cannot use the `$login` variable as a substitute for the account user name.
You must use either an anonymous or dedicated service user.

* If you use a {FreeIPA} or AD server, configure {Project} to use {FreeIPA} or AD authentication.
For more information, see xref:Configuring_External_Authentication_{context}[].

* Ensure that at least one external user authenticates for the first time.

* Retain a copy of the external group names you want to use.
To find the group membership of external users, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# id _username_
----

[[proc-Administering-Configuring_External_User_Groups-To_Configure_an_External_User_Group]]
.To Configure an External User Group:

. In the {ProjectWebUI}, navigate to *Administer* > *User Groups*, and click *Create User Group*.

. Specify the name of the new user group.
Do not select any users to avoid adding users automatically when you refresh the external user group.

. Click the *Roles* tab and select the roles you want to assign to the user group.
Alternatively, select the *Administrator* check box to assign all available permissions.

. Click the *External groups* tab, then click *Add external user group*, and select an authentication source from the *Auth source* drop-down menu.
+
Specify the exact name of the external group in the *Name* field.

. Click *Submit*.

=== Refreshing External User Groups for LDAP

To set the LDAP source to synchronize user group membership automatically on user login, in the *Auth Source* page, select the *Usergroup Sync* option.
If this option is not selected, LDAP user groups are refreshed automatically through a scheduled cron job synchronizing the LDAP Authentication source every 30 minutes by default.

If the user groups in the LDAP Authentication source change in the lapse of time between scheduled tasks, the user can be assigned to incorrect external user groups.
This is corrected automatically when the scheduled task runs.

Use this procedure to refresh the LDAP source manually.

.Procedure

. Navigate to *Administer* > *Usergroups* and select a user group.
. Navigate to the *External Groups* tab and click *Refresh* to the right of the required user group.

.CLI procedure

* Enter the following command:
+
----
# foreman-rake ldap:refresh_usergroups
----

=== Refreshing External User Groups for {FreeIPA} or AD
External user groups based on {FreeIPA} or AD are refreshed only when a group member logs in to {Project}.
It is not possible to alter user membership of external user groups in the {ProjectWebUI}, such changes are overwritten on the next group refresh.


[[sect-Administering-Configuring_External_Authentication-External_Authentication_for_Provisioned_Hosts]]
=== External Authentication for Provisioned Hosts

Use this section to configure {ProjectServer} or {SmartProxyServer} for {FreeIPA} realm support, then add hosts to the {FreeIPA} realm group.

*Prerequisites*

You require the following setup to configure external authentication for provisioned hosts:

* {ProjectServer} that is registered to the Content Delivery Network or an external {SmartProxyServer} that is registered to {ProjectServer}.

* A deployed realm or domain provider such as {FreeIPA}.

[id="Configuring_IdM_Realm_Support_{context}"]
.To install and configure {FreeIPA} packages on {ProjectServer} or {SmartProxyServer}:

To use {FreeIPA} for provisioned hosts, complete the following steps to install and configure {FreeIPA} packages on {ProjectServer} or {SmartProxyServer}:

. Install the `ipa-client` package on {ProjectServer} or {SmartProxyServer}:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} ipa-client
----

. Configure the server as a {FreeIPA} client:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ipa-client-install
----
. Create a realm proxy user, `realm-{smart-proxy-context}`, and the relevant roles in {FreeIPA}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-prepare-realm admin realm-{smart-proxy-context}
----
+
Note the principal name that returns and your {FreeIPA} server configuration details because you require them for the following procedure.

[[proc-Administering-Configuring_IdM]]
.To configure {ProjectServer} or {SmartProxyServer} for {FreeIPA} Realm Support:

Complete the following procedure on {Project} and every {SmartProxy} that you want to use:

. Copy the `/root/freeipa.keytab` file to any {SmartProxyServer} that you want to include in the same principal and realm:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# scp /root/freeipa.keytab root@_{smartproxy-example-com}_:/etc/foreman-proxy/freeipa.keytab
----
+
. Move the `/root/freeipa.keytab` file to the `/etc/foreman-proxy` directory and set the ownership settings to the `foreman-proxy` user:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# mv /root/freeipa.keytab /etc/foreman-proxy
# chown foreman-proxy:foreman-proxy /etc/foreman-proxy/freeipa.keytab
----
+
. Enter the following command on all {SmartProxies} that you want to include in the realm.
If you use the integrated {SmartProxy} on {Project}, enter this command on {ProjectServer}:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-installer} --foreman-proxy-realm true \
--foreman-proxy-realm-keytab /etc/foreman-proxy/freeipa.keytab \
--foreman-proxy-realm-principal _realm-{smart-proxy-context}@EXAMPLE.COM_ \
--foreman-proxy-realm-provider freeipa
----
+
You can also use these options when you first configure the {ProjectServer}.
+
. Ensure that the most updated versions of the ca-certificates package is installed and trust the {FreeIPA} Certificate Authority:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# cp /etc/ipa/ca.crt /etc/pki/ca-trust/source/anchors/ipa.crt
# update-ca-trust enable
# update-ca-trust
----
+
. Optional: If you configure {FreeIPA} on an existing {ProjectServer} or {SmartProxyServer}, complete the following steps to ensure that the configuration changes take effect:
.. Restart the *foreman-proxy* service:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl restart foreman-proxy
----
+
.. In the {ProjectWebUI}, navigate to *Infrastructure* > *{SmartProxies}*.
.. Locate the {SmartProxy} you have configured for {FreeIPA} and from the list in the *Actions* column, select *Refresh*.


[[proc-Administering-Creating_a_Realm_for_the_IdM_enabled_Capsule]]
.To create a realm for the {FreeIPA}-enabled {SmartProxy}

After you configure your integrated or external {SmartProxy} with {FreeIPA}, you must create a realm and add the {FreeIPA}-configured {SmartProxy} to the realm.

To create a realm, complete the following steps:

. In the {ProjectWebUI}, navigate to *Infrastructure* > *Realms* and click *Create Realm*.
. In the *Name* field, enter a name for the realm.
. From the *Realm Type* list, select the type of realm.
. From the *Realm {SmartProxy}* list, select {SmartProxyServer} where you have configured {FreeIPA}.
. Click the *Locations* tab and from the *Locations* list, select the location where you want to add the new realm.
. Click the *Organizations* tab and from the *Organizations* list, select the organization where you want to add the new realm.
. Click *Submit*.

.Updating Host Groups with Realm Information
You must update any host groups that you want to use with the new realm information.

. Navigate to *Configure* > *Host Groups*, select the host group that you want to update, and click the *Network* tab.
. From the *Realm* list, select the realm you create as part of this procedure, and then click *Submit*.

[[sect-Administering-External_Authentication_for_Provisioned_Hosts-Adding_Hosts_to_an_IdM_Host_Group]]
.Adding Hosts to a {FreeIPA} Host Group

{FreeIPA} supports the ability to set up automatic membership rules based on a system's attributes.
{ProjectName}'s realm feature provides administrators with the ability to map the {ProjectName} host groups to the {FreeIPA} parameter `userclass` which allow administrators to configure automembership.

When nested host groups are used, they are sent to the {FreeIPA} server as they are displayed in the {ProjectName} User Interface.
For example, "Parent/Child/Child".

{ProjectServer} or {SmartProxyServer} sends updates to the {FreeIPA} server, however automembership rules are only applied at initial registration.


[[proc-Administering-Adding_Hosts_to_an_IdM_Host_Group-To_Add_Hosts_to_an_IdM_Host_Group]]
.To Add Hosts to a {FreeIPA} Host Group:

. On the {FreeIPA} server, create a host group:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ipa hostgroup-add _hostgroup_name_ --desc=_hostgroup_description_
----
+
. Create an `automembership` rule:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ipa automember-add --type=hostgroup _hostgroup_name_ _automember_rule_
----
+
Where you can use the following options:
+
* `automember-add` flags the group as an automember group.
* `--type=hostgroup` identifies that the target group is a host group, not a user group.
* `_automember_rule_` adds the name you want to identify the automember rule by.
+
. Define an automembership condition based on the `userclass` attribute:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# ipa automember-add-condition --key=userclass --type=hostgroup --inclusive-regex=_^webserver_ _hostgroup_name_
----------------------------------
Added condition(s) to "_hostgroup_name_"
----------------------------------
Automember Rule: _automember_rule_
Inclusive Regex: userclass=_^webserver_
----------------------------
Number of conditions added 1
----------------------------
----
+
Where you can use the following options:
+
* `automember-add-condition` adds regular expression conditions to identify group members.
* `--key=userclass` specifies the key attribute as `userclass`.
* `--type=hostgroup` identifies that the target group is a host group, not a user group.
* `--inclusive-regex=` _^webserver_ identifies matching values with a regular expression pattern.
* _hostgroup_name_ - identifies the target host group's name.

When a system is added to {ProjectServer}'s _hostgroup_name_ host group, it is added automatically to the {FreeIPA} server's "_hostgroup_name_" host group.
{FreeIPA} host groups allow for Host-Based Access Controls (HBAC), sudo policies and other {FreeIPA} functions.

include::../common/assembly_configuring-keycloak-external-authentication.adoc[leveloffset=+2]
include::../common/assembly_configuring-keycloak-external-authentication-with-totp.adoc[leveloffset=+2]
ifndef::satellite,orcharhino[]
include::../common/assembly_configuring-keycloak-external-authentication-with-cac-cards.adoc[leveloffset=+2]
endif::[]
include::../common/modules/proc_disabling-keycloak-authentication.adoc[leveloffset=+2]
