= Enabling Individual Loggers
You can enable individual loggers for selective logging. Satellite uses the following loggers:

`app`::
Logs web requests and all general application messages. Default value: true.
`audit`::
Logs additional fact statistics, numbers of added, updated, and removed facts. Default value: true.
`ldap`::
Logs high level LDAP queries and LDAP operations. Default value: false.
`permissions`::
Logs queries to user roles, filters, and permissions when loading pages. Default value: false.
`sql`::
Logs SQL queries made through Rails ActiveRecord. Default value: false.

.Procedure

To enable individual loggers, complete the following steps.

. Enable the individual loggers that you want. For example, to enable `sql` and `ldap` loggers, enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-installer --foreman-loggers sql:true --foreman-loggers ldap:true
----

. Optional: To reset loggers to their default values, enter the following command:
+
----
# satellite-installer --reset-foreman-loggers
----
