[id='kerberos-configuration-in-web-browsers_{context}']
= Kerberos Configuration in Web Browsers

For information on configuring the Firefox browser see https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System-Level_Authentication_Guide/Configuring_Applications_for_SSO.html#Configuring_Firefox_to_use_Kerberos_for_SSO[Configuring Firefox to Use Kerberos for Single Sign-On] in the _Red{nbsp}Hat Enterprise{nbsp}Linux System-Level Authentication_ guide. 

If you use the Internet Explorer browser, add {ProjectServer} to the list of Local Intranet or Trusted sites, and turn on the _Enable Integrated Windows Authentication_ setting. See the Internet Explorer documentation for details.

[NOTE]
====
With direct AD integration, HBAC through {FreeIPA} is not available. As an alternative, you can use Group Policy Objects (GPO) that enable administrators to centrally manage policies in AD environments. To ensure correct GPO to PAM service mapping, use the following sssd configuration:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
access_provider = ad
ad_gpo_access_control = enforcing
ad_gpo_map_service = +foreman
----

Here, _foreman_ is the PAM service name. For more information on GPOs, please refer to the https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Windows_Integration_Guide/sssd-gpo.html[Red{nbsp}Hat Enterprise Linux Windows Integration Guide].
====
