[[chap-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Maintaining_a_Red_Hat_Satellite_Server]]
== Maintaining {ProjectServer}

This chapter provides information on how to maintain a {ProjectName} Server, including information on how to work with audit records, how to clean unused tasks, how to recover Pulp from a full disc, and how to reclaim disc space from MongoDB.

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Deleting_Audit_Records]]
=== Deleting Audit Records

Audit records are created automatically in {Project}. You can use the `foreman-rake audits:expire` command to remove audits at any time. You can also use a cron job to schedule audit record deletions at the set interval that you want.

By default, using the `foreman-rake audits:expire` command removes audit records that are older than 90 days. You can specify the number of days to keep the audit records by adding the *days* option and add the number of days.

For example, if you want to delete audit records that are older than seven days, enter the following command:

----
# foreman-rake audits:expire days=7
----

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Anonymizing_Audit_Records]]
=== Anonymizing Audit Records

You can use the `foreman-rake audits:anonymize` command to remove any user account or IP information while maintaining the audit records in the database. You can also use a cron job to schedule anonymizing the audit records at the set interval that you want.

By default, using the `foreman-rake audits:anonymize` command anonymizes audit records that are older than 90 days. You can specify the number of days to keep the audit records by adding the *days* option and add the number of days.

For example, if you want to anonymize audit records that are older than seven days, enter the following command:

----
# foreman-rake audits:anonymize days=7
----

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_the_Cleaning_Unused_Tasks_Feature]]
=== Configuring the Cleaning Unused Tasks Feature

{Project} performs regular cleaning to reduce disc space in the database and limit the rate of disk growth. As a result, {Project} backup completes faster and overall performance is higher.

By default, {Project} executes a cron job that cleans tasks every day at 19:45. {Project} removes the following tasks during the cleaning:

*  Tasks that have run successfully and are older than thirty days
*  All tasks that are older than a year

.For {Project}s Upgraded from Previous Versions
Until https://bugzilla.redhat.com/show_bug.cgi?id=1788615[BZ#1788615] is resolved, this functionality works only on fresh installations of {ProjectXY} and later. If you upgrade {Project} from previous versions, this functionality is disabled by default. To enable {Project} to perform regular cleaning, enter the following command:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-plugin-tasks-automatic-cleanup true
----

Optionally use this procedure to adjust the configuration to serve your needs.

.Procedure
. Optional: To configure the time at which {Project} runs the cron job, set the `--foreman-plugin-tasks-cron-line` parameter to the time you want in cron format. For example, to schedule the cron job to run every day at 15:00, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-installer} --foreman-plugin-tasks-cron-line "00 15 * * *"
----

. Optional: To configure the period after which {Project} deletes the tasks, edit the `:rules:` section in the `/etc/foreman/plugins/foreman-tasks.yaml` file.

[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Recovering_from_a_Full_Disk]]
=== Recovering from a Full Disk

The following procedure describes how to resolve the situation when a logical volume (LV) with the Pulp database on it has no free space.

[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-to_Recover_from_a_Full_Disk]]
.To recover from a full disk

. Let running Pulp tasks finish but do not trigger any new ones as they can fail due to the full disk.
. Ensure that the LV with the `/var/lib/pulp` directory on it has sufficient free space. Here are some ways to achieve that:
.. Remove orphaned content:
+
[options="nowrap" subs="+quotes,attributes"]
----
# foreman-rake katello:delete_orphaned_content RAILS_ENV=production
----
+
This is run weekly so it will not free much space.
.. Change the download policy from *Immediate* to *On Demand* for as many repositories as possible and remove already downloaded packages. See the Red{nbsp}Hat Knowledgebase solution link:https://access.redhat.com/solutions/2785021[How to change syncing policy for Repositories on {ProjectXY} from "Immediate" to "On-Demand"] on the Red{nbsp}Hat Customer Portal for instructions.
.. Grow the file system on the LV with the `/var/lib/pulp` directory on it. For more information, see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/logical_volume_manager_administration/fsgrow_overview[Growing a File System on a Logical Volume] in the _Red{nbsp}Hat Enterprise Linux 7 Logical Volume Manager Administration Guide_.
+
[NOTE]
====
If you use an untypical file system (other than for example ext3, ext4, or xfs), you might need to unmount the file system so that it is not in use. In that case, complete the following steps:

. Stop the `{foreman-maintain}` services:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service stop
----
. Grow the file system on the LV.
. Start the `{foreman-maintain}` services:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service start
----
====
+
. If some Pulp tasks failed due to the full disk, run them again.

[id='installing-and-updating-packages-on-satellite-server']
=== Managing Packages on the Base Operating System of {ProjectServer}

To install and update packages on the {Project} base operating system, you must enter the `{foreman-maintain} packages` command.

{Project} prevents users from installing and updating packages with `yum` because `yum` might also update the packages related to {Project} and result in system inconsistency.

IMPORTANT: The `{foreman-maintain} packages` command restarts some services on {ProjectServer} because it runs the `{foreman-installer} --upgrade` command after installing packages.

.Procedure

* To install packages on {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-maintain} packages install _package_1_ _package_2_
----

* To update packages on {ProjectServer}, enter the following command:
+
[options="nowrap", subs="+quotes,attributes"]
----
# {foreman-maintain} packages update _package_1_ _package_2_
----

.Using yum to Check for Package Updates

If you want to check for updates using `yum`, enter the command to install and update packages manually and then you can use `yum` to check for updates:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} packages unlock
# yum check update
# {foreman-maintain} packages lock
----
Updating packages individually can lead to package inconsistencies in {Project}. For more information about updating packages in {Project}, see {BaseURL}upgrading_and_updating_red_hat_satellite/updating_satellite_server_capsule_server_and_content_hosts#updating_satellite_server_to_next_minor_version[Updating {ProjectServer}].

.Enabling yum for {Project} Package Management

If you want to install and update packages on your system using `yum` directly and control the stability of the system yourself, enter the following command:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} packages unlock
----

.Restoring Package Management to the Default Settings

If you want to restore the default settings and enable {Project} to prevent users from installing and updating packages with `yum` and ensure the stability of the system, enter the following command:

[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} packages lock
----
