[id='performing-a-full-backup-of-satellite-or-capsule_{context}']

= Performing a Full Backup of Satellite Server or Capsule Server

Red{nbsp}Hat Satellite{nbsp}{ProductVersion} uses the `satellite-maintain backup` command to make backups.

There are three main methods of backing up Satellite Server:

* Offline backup
* Online backup
* Snapshot backups
+
For more information about each of these methods, you can view the usage statements for each backup method.

For offline backups:

[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-maintain backup offline --help
----

For online backups:

[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-maintain backup online --help
----

For snapshots backups:

[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-maintain backup snapshot --help
----

.Directory creation

The `satellite-maintain backup` command creates a time-stamped subdirectory in the backup directory that you specify. The `satellite-maintain backup` command does not overwrite backups, therefore you must select the correct directory or subdirectory when restoring from a backup or an incremental backup.
The `satellite-maintain backup` command stops and restarts services as required.

When you run the `satellite-maintain backup offline` command, the following default backup directories are created:

* `satellite-backup` on Satellite
* `foreman-proxy-backup` on Capsule

If you want to set a custom directory name, add the  `--preserve-directory` option and add a directory name. The backup is then stored in the directory you provide in the command line.
If you use the `--preserve-directory` option, no data is removed if the backup fails.

Note that if you use a local PgSQL database, the `postgres` user requires write access to the backup directory .

.Remote databases

You can use the `satellite-maintain backup` command to back up remote databases.

You can use both online and offline methods to back up remote databases, but if you use offline methods, such as snapshot, the `satellite-maintain backup` command performs a database dump.

.Prerequisites

* Ensure that your backup location has sufficient available disk space to store the backup. For more information, see xref:estimating-the-size-of-a-backup_{context}[].

.Procedure
To perform a full offline backup of Satellite Server or Capsule Server, complete one of the following steps:

[WARNING]
====
Request other users of Satellite Server or Capsule Server to save any changes and warn them that Satellite services are unavailable for the duration of the backup. Ensure no other tasks are scheduled for the same time as the backup.
====

* On Satellite Server, enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-maintain backup offline _/var/satellite-backup_
----

* On Capsule Server, enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-maintain backup offline _/var/foreman-proxy-backup_
----
