[id='performing-a-backup-without-pulp-content_{context}']
= Performing a Backup without Pulp Content

You can perform an offline backup that excludes the contents of the Pulp directory.
The backup without Pulp content is useful for debugging purposes and is only intended to provide access to configuration files without backing up the Pulp database.
You cannot restore from a directory that does not contain Pulp content.

[WARNING]
====
Request other users of {ProjectServer} or {SmartProxyServer} to save any changes and warn them that {Project} services are unavailable for the duration of the backup.
Ensure no other tasks are scheduled for the same time as the backup.
====

.Prerequisites

* Ensure that your backup location has sufficient available disk space to store the backup.
For more information, see xref:estimating-the-size-of-a-backup_{context}[].

.Procedure

* To perform an offline backup without Pulp content, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} backup offline --skip-pulp-content _/var/backup_directory_
----
