[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Resetting_the_Administrative_User_Password]]
===  Resetting the Administrative User Password

Use the following procedures to reset the administrative password to randomly generated characters or to set a new administrative password.

[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Resetting_the_Administrative_User_Password-To_Reset_the_Administrative_User_Password]]
.To Reset the Administrative User Password:

To reset the password to randomly generated characters, complete the following procedure:

. Log on to the base operating system where {ProjectServer} is installed.
. Enter the following command to reset the password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake permissions:reset
Reset to user: admin, password: qwJxBptxb7Gfcjj5
----
. Use this password to reset the password in the {Project} web UI.
. Edit the `~/.hammer/cli.modules.d/foreman.yml` file on {ProjectServer} to add the new password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
#  vi ~/.hammer/cli.modules.d/foreman.yml
----

Unless you update the `~/.hammer/cli.modules.d/foreman.yml` file, you cannot use the new password with Hammer CLI.

[[proc-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Resetting_the_Administrative_User_Password-To_Set_a_New_Administrative_User_Password]]
.To Set a New Administrative User Password:

To change the administrative user password to a new password, complete the following steps:

. Log on to the base operating system where {ProjectServer} is installed.
. To set the password, enter the following command:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# foreman-rake permissions:reset password=_new_password_
----
+
. Edit the `~/.hammer/cli.modules.d/foreman.yml` file on {ProjectServer} to add the new password:
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
#  vi ~/.hammer/cli.modules.d/foreman.yml
----

Unless you update the `~/.hammer/cli.modules.d/foreman.yml` file, you cannot use the new password with Hammer CLI.
