[id='restoring-from-a-full-backup_{context}']
= Restoring from a Full Backup

Use this procedure to restore Red{nbsp}Hat Satellite or Capsule Server from a full backup. When the restore process completes, all processes are online, and all databases and system configuration revert to the state at the time of the backup.

.Prerequisites
* Ensure that you are restoring to the correct instance. The Red Hat Satellite instance must have the same host name, configuration, and be the same major version as the original system.
* Ensure that you have an existing target directory. The target directory is read from the configuration files contained within the archive.
* Ensure that you have enough space to store this data on the base system of Satellite Server or Capsule Server as well as enough space after the restoration to contain all the data in the `/etc/` and `/var/` directories contained within the backup.
+
To check the space used by a directory, enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# du -sh _/var/backup_directory_
----
+
To check for free space, enter the following command:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# df -h _/var/backup_directory_
----
+
Add the ``--total`` option to get a total of the results from more than one directory.

* Ensure that all SELinux contexts are correct. Enter the following command to restore the correct SELinux contexts:
+
[options="nowrap" subs="+quotes,verbatim"]
----
# restorecon -Rnv /
----

.Procedure
. Choose the appropriate method to install Satellite or Capsule:

** To install Satellite Server from a connected network, follow the procedures in link:https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersion}/html/installing_satellite_server_from_a_connected_network/[Installing Satellite Server from a Connected Network].

** To install Satellite Server from a disconnected network, follow the procedures in link:https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersion}/html/installing_satellite_server_from_a_disconnected_network/[Installing Satellite Server from a Disconnected Network].

** To install a Capsule Server, follow the procedures in the link:https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersion}/html/installing_capsule_server/[Installing Capsule Server].

. Copy the backup data to Satellite Server’s local file system. Use `/var/` or `/var/tmp/`.

. Run the restoration script.
+
[options="nowrap" subs="+quotes,verbatim"]
----
# satellite-maintain restore __/var/backup_directory__
----
+
Where _backup_directory_ is the time-stamped directory or subdirectory containing the backed-up data.
+
The restore process can take a long time to complete, because of the amount of data to copy. 

.Additional Resources
* For troubleshooting, you can check `/var/log/foreman/production.log` and `/var/log/messages`.