[[chap-Administering-Starting_and_Stopping_Red_Hat_Satellite]]
== Starting and Stopping {ProjectName}

{Project} provides the `{foreman-maintain} service` command to manage {Project} services from the command line.
This is useful when creating a backup of {Project}.
For more information on creating backups, see xref:backing-up-satellite-server-and-capsule-server[].

ifdef::foreman-el,katello[]
.Prerequisite
This section uses the `{foreman-maintain}` command.
To use the commands in this section, you must install `{foreman-maintain}`, for example:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# yum install `{foreman-maintain}`
----

Alternatively, you can also use `systemctl` to start and stop services:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl stop foreman.service foreman.socket
----

However, services like dynflow still continue to run if you use `systemctl`.
You must target directly, for example:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# systemctl stop dynflow-sidekiq@*
----

endif::[]


ifdef::satellite,orcharhino[]
After installing {Project} with the `{foreman-installer}` command, all {Project} services are started and enabled automatically.
endif::[]

View the list of these services by executing:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service list
----

To see the status of running services, execute:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service status
----

To stop the `{foreman-maintain}` services, execute:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service stop
----

To start the `{foreman-maintain}` services, execute:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service start
----

To restart the `{foreman-maintain}` services, execute:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {foreman-maintain} service restart
----
