[[chap-Administering-Users_and_Roles]]
== Managing Users and Roles

A User defines a set of details for individuals using the system.
Users can be associated with organizations and environments, so that when they create new entities, the default settings are automatically used.
Users can also have one or more _roles_ attached, which grants them rights to view and manage organizations and environments.
See xref:user-management_{context}[] for more information on working with users.

You can manage permissions of several users at once by organizing them into user groups.
User groups themselves can be further grouped to create a hierarchy of permissions.
See xref:sect-Administering-Users_and_Roles-Creating_and_Managing_User_Groups[] for more information on creating user groups.

Roles define a set of permissions and access levels.
Each role contains one on more _permission filters_ that specify the actions allowed for the role.
Actions are grouped according to the _Resource type_.
Once a role has been created, users and user groups can be associated with that role.
This way, you can assign the same set of permissions to large groups of users.
{ProjectName} provides a set of predefined roles and also enables creating custom roles and permission filters as described in xref:sect-Administering-Users_and_Roles-Creating_and_Managing_Roles[].

[[sect-Administering-Users_and_Roles-Creating_and_Managing_Users]]
include::user-management.adoc[leveloffset=+2]

[[sect-Administering-Creating_and_Managing_Users-Creating_a_User]]
include::creating-a-user.adoc[leveloffset=+3]

[[sect-Administering-Creating_and_Managing_Users-Assigning_Roles_to_a_User]]
include::assigning-roles-to-a-user.adoc[leveloffset=+3]

include::impersonating-a-different-user-account.adoc[leveloffset=+3]

[[sect-Administering-Managing_SSH_Keys]]


include::ssh-keys.adoc[leveloffset=+2]

include::managing-ssh-keys-for-a-user.adoc[leveloffset=+3]


[[sect-Administering-Users_and_Roles-Creating_and_Managing_User_Groups]]

=== Creating and Managing User Groups

include::user-groups.adoc[leveloffset=+3]


[[sect-Administering-Users_and_Roles-Creating_and_Managing_User_Groups-Creating_a_User_Group]]

include::creating-a-user-group.adoc[leveloffset=+3]

[[sect-Administering-Users_and_Roles-Creating_and_Managing_User_Groups-Removing_a_User_Group]]

include::removing-a-user-group.adoc[leveloffset=+3]

[[sect-Administering-Users_and_Roles-Creating_and_Managing_Roles]]
=== Creating and Managing Roles

{ProjectName} provides a set of predefined roles with permissions sufficient for standard tasks, as listed in xref:predefined-roles-available-in-satellite_{context}[].
It is also possible to configure custom roles, and assign one or more permission filters to them.
Permission filters define the actions allowed for a certain resource type.
Certain {Project} plug-ins create roles automatically.

[[sect-Administering-Creating_and_Managing_Roles-Creating_a_Role]]

include::creating-a-role.adoc[leveloffset=+3]


To serve its purpose, a role must contain permissions.
After creating a role, proceed to xref:adding-permissions-to-a-role_{context}[].

[[sect-Administering-Creating_and_Managing_Roles-Cloning_a_Role]]
include::cloning-a-role.adoc[leveloffset=+3]

[[sect-Administering-Creating_and_Managing_Roles-Adding_Permissions_to_a_Role]]
include::adding-permissions-to-a-role.adoc[leveloffset=+3]


[[sect-Administering-Creating_and_Managing_Roles-Viewing_Permissions_of_a_Role]]
include::viewing-permissions-of-role.adoc[leveloffset=+3]

[[proc-Administering-Viewing_Permissions_of_a_Role-To_Create_a_Complete_Permission_Table]]
include::creating-a-complete-permission-table.adoc[leveloffset=+3]


[[sect-Administering-Creating_and_Managing_Roles-Removing_a_Role]]
include::removing-a-role.adoc[leveloffset=+3]


include::predefined-roles-available-in-satellite.adoc[leveloffset=3]


[[sect-Administering-Users_and_Roles-Granular_Permission_Filtering]]
=== Granular Permission Filtering

include::granular-permission-filter.adoc[leveloffset=+3]

include::creating-a-granular-permission-filter.adoc[leveloffset=+3]

==== Examples of Using Granular Permission Filters

As an administrator, you can allow selected users to make changes in a certain part of the environment path.
The following filter allows you to work with content while it is in the development stage of the application life cycle, but the content becomes inaccessible once is pushed to production.

include::applying-permissions-for-the-host-resource-type.adoc[leveloffset=+4]

You can limit user permissions to a certain organization or location with the use of the granular permission filter in the *Search* field.
However, some resource types provide a GUI alternative, an *Override* check box that provides the *Locations* and *Organizations* tabs.
On these tabs, you can select from the list of available organizations and locations.
See xref:creating-an-organization-specific-manager-role_{context}[].

include::creating-an-organization-specific-manager-role.adoc[leveloffset=+4]

include::supported-operators-for-granular-search.adoc[leveloffset=+3]
