[[sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication-Using_Identity_Management]]
=== Using Identity Management

This section shows how to integrate Red{nbsp}Hat Satellite Server with an IdM server and how to enable host-based access control.

[NOTE]
You can attach Identity Management as an external authentication source with no single sign-on support. For more information, see xref:sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Using_LDAP[].

[[br-Using-IdM-for-Authentication-prereq]]
.Prerequisites

- The Satellite Server has to run on Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7.1 or Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}6.6 or later.

- The base operating system of the Satellite Server must be enrolled in the IdM domain by the IdM administrator of your organization.

The examples in this chapter assume separation between IdM and Satellite configuration. However, if you have administrator privileges for both servers, you can configure IdM as described in link:https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Linux_Domain_Identity_Authentication_and_Policy_Guide/index.html#ldi-install[Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Linux Domain Identity, Authentication, and Policy Guide]

include::configuring-idm-authentication-on-satellite-server.adoc[leveloffset=+3]

include::configuring-host-based-authentication-control.adoc[leveloffset=+3]
