[id="upgrading_a_connected_{project-context}_server_{context}"]
= Upgrading a Connected {ProjectServer}

Use this procedure for a {ProjectServer} with access to the public internet

include::../common/modules/snip_using_installer_noop.adoc[]

.Upgrade {ProjectServer}

. Create a backup.
+
* On a virtual machine, take a snapshot.
* On a physical machine, create a backup.
+
For more information about backups, see {AdministeringDocURL}backing-up-{project-context}-server-and-{smart-proxy-context}_admin[Backing Up {ProjectServer} and {SmartProxyServer}] in _{AdministeringDocTitle}_.

. Optional: If you made manual edits to DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, back up the configuration files because the installer only supports one domain or subnet, and therefore restoring changes from these backups might be required.

. Optional: If you made manual edits to DNS or DHCP configuration files and do not want to overwrite the changes, enter the following command:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} --foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false
----
ifdef::katello[]
. Optional: If you use PostgreSQL as an external database, install the `postgresql-evr` package on the PostgreSQL server:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install} postgresql-evr
----
endif::[]
. In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
On the Discovered Hosts page, power off and then delete the discovered hosts.
From the *Select an Organization* menu, select each organization in turn and repeat the process to power off and delete the discovered hosts.
Make a note to reboot these hosts when the upgrade is complete.
ifdef::satellite[]
. Ensure that the {Project} Maintenance repository is enabled:
+
[options="nowrap" subs="attributes"]
----
# subscription-manager repos --enable \
{RepoRHEL8ServerSatelliteMaintenanceProductVersion}
----
. Enable the maintenance module:
+
[options="nowrap" subs="attributes"]
----
# dnf module enable satellite-maintenance:el8
----

. Check the available versions to confirm the version you want is listed:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade list-versions
----

. Use the health check option to determine if the system is ready for upgrade.
When prompted, enter the hammer admin user credentials to configure `{foreman-maintain}` with hammer credentials.
These changes are applied to the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade check --target-version {ProductVersion}
----
+
Review the results and address any highlighted error conditions before performing the upgrade.

. Because of the lengthy upgrade time, use a utility such as `tmux` to suspend and reattach a communication session.
You can then check the upgrade progress without staying connected to the command shell continuously.
+
If you lose connection to the command shell where the upgrade command is running you can see the logged messages in the `{installer-log-file}` file to check if the process completed successfully.

. Perform the upgrade:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade run --target-version {ProductVersion}
----
endif::[]
ifdef::katello[]
. Check for running tasks
+
[options="nowrap" subs="attributes"]
----
# foreman-rake katello:upgrade_check
----
endif::[]
ifdef::foreman-el,katello[]
. Update operating system packages:
+
[options="nowrap" subs="attributes"]
----
# {package-update}
----
. Update repositories
+
[options="nowrap" subs="attributes"]
----
ifdef::katello[]
# {package-update} https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm \
https://yum.theforeman.org/katello/{KatelloVersion}/katello/el8/x86_64/katello-repos-latest.rpm
endif::[]
ifdef::foreman-el[]
# {package-update} https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm
endif::[]
----
. Ensure the module streams are enabled:
+
[options="nowrap" subs="attributes"]
----
# dnf module enable {dnf-modules}
----
. Stop all services:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service stop
----
. Update the required packages:
+
[options="nowrap" subs="attributes"]
----
# {package-update}
----
+
. Run the installer:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer}
----
endif::[]
include::snip_needs_reboot.adoc[]
