[id="upgrading_content_hosts_{context}"]
= Upgrading Content Hosts

The {project-client-name} repository provides `katello-agent` and `katello-host-tools`, which provide communication services for managing Errata.

NOTE: The Katello agent is deprecated and will be removed in a future {Project} version.
Migrate your workloads to use the remote execution feature to update clients remotely.
For more information, see {ManagingHostsDocURL}Migrating_From_Katello_Agent_to_Remote_Execution_managing-hosts[Migrating from Katello Agent to Remote Execution] in _{ManagingHostsDocTitle}_.
{Project} now supports a pull-based provider as a replacement for the Katello agent.

For deployments using `katello-agent` and *goferd*, update all clients to the new version of `katello-agent`.
For deployments not using `katello-agent` and *goferd*, update all clients to the new version of `katello-host-tools`.
Complete this action as soon as possible so that your clients are fully compatible with {ProjectServer}.

.Prerequisites
* You must have upgraded {ProjectServer}.
* You must have enabled the new {project-client-name} repositories on the {Project}.
* You must have synchronized the new repositories in the {Project}.
* If you have not previously installed `katello-agent` on your clients and you want to install it, use the manual method.
For more information, see xref:cli-upgrading_content_hosts[].

[WARNING]
====
If you implemented custom certificates, you must retain the content of both the `/root/ssl-build` directory and the directory in which you created any source files associated with your custom certificates.

Failure to retain these files during an upgrade causes the upgrade to fail.
If these files have been deleted, they must be restored from a backup in order for the upgrade to proceed.
====

[[cli-upgrading_content_hosts]]
.CLI Procedure
. Log into the client system.

ifdef::katello[]
. Enable the {project-client-name} repository for this version of {Project}.
+
[options="nowrap" subs="attributes"]
----
# yum install {project-client-RHEL7-url}
----
endif::[]
. Depending on your configuration, complete one of the following steps:
+
* If your deployment uses `katello-agent` and *goferd*, enter the following command to install or upgrade `katello-agent`:
+
----
# yum install katello-agent
----
+
* If your deployment does not use `katello-agent` and *goferd*, enter the following command to install or upgrade `katello-host-tools`:
+
----
# yum install katello-host-tools
----
