[[upgrading_a_connected_satellite_server]]
= Upgrading a Connected {ProjectServer}

Use this procedure for a {ProjectServer} connected to the Red{nbsp}Hat Content Delivery Network.

[WARNING]
If you customize configuration files, manually or using a tool such as Hiera, these changes are overwritten when the installation script runs during upgrading or updating. You can use the `--noop` option with the {foreman-installer} script to test for changes. For more information, see the Red Hat Knowledgebase solution https://access.redhat.com/solutions/3351311[How to use the noop option to check for changes in {Project} config files during an upgrade.]

.Upgrade {ProjectServer}

. Create a backup.
+
* On a virtual machine, take a snapshot.
* On a physical machine, create a backup.
ifndef::orcharhino[]
+
For more information about backups, see https://access.redhat.com/documentation/en-us/red_hat_satellite/{ProductVersionPrevious}/html/administering_red_hat_satellite/backing-up-satellite-server-and-capsule-server[Backing Up {ProjectServer} and {SmartProxyServer}] in the _Administering {ProjectName} {ProductVersionPrevious}_ guide.
endif::[]

. Optional: If you made manual edits to DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, back up the configuration files because the installer only supports one domain or subnet, and therefore restoring changes from these backups might be required.

. Optional: If you made manual edits to DNS or DHCP configuration files and do not want to overwrite the changes, enter the following command:
+
[options="nowrap"]
----
# {foreman-installer} --foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false
----

. Optional: If you use PostgreSQL as an external database, on the PostgreSQL server, install the `rh-postgresql12-postgresql-evr` package, which is available from the `{RepoRHEL7Server{Project}ServerProductVersion}` repository:
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum install rh-postgresql12-postgresql-evr
----

. In the {Project} web UI, navigate to *Hosts* > *Discovered hosts*. On the Discovered Hosts page, power off and then delete the discovered hosts. From the *Select an Organization* menu, select each organization in turn and repeat the process to power off and delete the discovered hosts. Make a note to reboot these hosts when the upgrade is complete.

. Ensure that the {Project} Maintenance repository is enabled:
+
[options="nowrap" subs="attributes"]
----
# subscription-manager repos --enable \
{RepoRHEL7Server{Project}MaintenanceProductVersion}
----

. Check the available versions to confirm the version you want is listed:
+
[options="nowrap"]
----
# {foreman-maintain} upgrade list-versions
----

. Use the health check option to determine if the system is ready for upgrade. When prompted, enter the hammer admin user credentials to configure `{foreman-maintain}` with hammer credentials. These changes are applied to the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade check --target-version {TargetVersionMaintainUpgrade}
----
+
Review the results and address any highlighted error conditions before performing the upgrade.

. Because of the lengthy upgrade time, use a utility such as `screen` to suspend and reattach a communication session. You can then check the upgrade progress without staying connected to the command shell continuously. For more information about using the screen command, see link:https://access.redhat.com/articles/5247[How do I use the screen command?] article in the _Red{nbsp}Hat Knowledge{nbsp}Base_.
+
If you lose connection to the command shell where the upgrade command is running you can see the logged messages in the `/var/log/foreman-installer/satellite.log` file to check if the process completed successfully.

. Perform the upgrade:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade run --target-version {TargetVersionMaintainUpgrade}
----

. Check when the kernel packages were last updated:
+
[options="nowrap"]
----
# rpm -qa --last | grep kernel
----

. Optional: If a kernel update occurred since the last reboot, stop the `{foreman-maintain}` services and reboot the system:
+
----
# {foreman-maintain} service stop
# reboot
----

. If using a BASH shell, after a successful or failed upgrade, enter:
+
[options="nowrap"]
----
# hash -d {foreman-maintain} service 2> /dev/null
----

. Optional: If you made manual edits to DNS or DHCP configuration files, check and restore any changes required to the DNS and DHCP configuration files using the backups that you make.

. If you make changes in the previous step, restart the `{foreman-maintain}` services.
+
[options="nowrap"]
----
# {foreman-maintain} service restart
----

. If you have the OpenSCAP plug-in installed, but do not have the default OpenSCAP content available, enter the following command:

+
[options="nowrap"]
----
# foreman-rake foreman_openscap:bulk_upload:default
----
