[[upgrading_discovery_satellite]]

= Upgrading Discovery on {ProjectServer}

. Update the Discovery template in the {ProjectWebUI}:.
.. In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning templates*.
.. On the `PXELinux global default` line, click *Clone*.
.. Enter a new name for the template in the *Name* field, for example `ACME PXE global default`.
.. In the template editor field, change the line `ONTIMEOUT local` to `ONTIMEOUT discovery` and click *Submit*.
.. In the {ProjectWebUI}, navigate to *Administer* > *Settings* > *Provisioning*.
.. Set `Default PXE global template entry` = (custom value for environment).
.. Locate `Global default PXELinux template` and click on its *Value*.
.. Select the name of the newly created template from the menu and click *Submit*.
.. In the {ProjectWebUI}, navigate to *Hosts* > *Provisioning templates*.
.. Click *Build PXE Default*, then click *OK*.

+
[NOTE]
====
If the template is modified, a {Project} upgrade overrides it to its default version.
Once the PXE Default configuration is built, the template configured in the *Settings* is deployed to the TFTP.
This can result in deploying the default template if the new template is correctly set in the *Settings*.
====
+
. In the {ProjectWebUI}, go to *Configure* > *Discovery Rules* and associate selected organizations and locations with discovery rules.
