[id="Upgrading_Server_{context}"]
= Upgrading {ProjectServer}

This section describes how to upgrade {ProjectServer} from {ProjectVersionPrevious} to {ProjectVersion}.
You can upgrade from any minor version of {ProjectName} Server {ProjectVersionPrevious}.
ifdef::satellite[]
However, to access the latest migration and tooling fixes, upgrade to the latest 6.9.z before starting migration to {ProjectVersion}.

Although the process of upgrading from {ProjectVersionPrevious} to {ProjectVersion} also migrates Pulp content, this can take some considerable time.
You can reduce this time by following the procedure in xref:preparing_to_migrate_pulp_content[]

If you have not pre-migrated content from Pulp 2 to Pulp 3, you must upgrade to the latest version of {ProjectServer} before starting to migrate Pulp content.
endif::[]

include::upgrading_satellite_server_prerequisites.adoc[leveloffset=+3]

ifdef::satellite[]
.Upgrade Scenarios
- To upgrade a {ProjectServer} connected to the Red{nbsp}Hat Content Delivery Network, proceed to xref:upgrading_a_connected_satellite_server[].
- To upgrade a {ProjectServer} not connected to the Red{nbsp}Hat Content Delivery Network, proceed to xref:upgrading_a_disconnected_satellite[].

You cannot upgrade a self-registered {Project}. You must migrate a self-registered {Project} to the Red Hat Content Delivery Network (CDN) and then perform the upgrade. To migrate a self-registered {Project} to the CDN, see {BaseURL}upgrading_and_updating_red_hat_satellite/upgrading_red_hat_satellite#migrating_a_self_registered_satellite[Migrating Self-Registered {Project}s] in the _{ProjectXY} Upgrading and Updating {ProjectName}_ guide.
endif::[]

.FIPS mode

You cannot upgrade {ProjectServer} from a RHEL base system that is not operating in FIPS mode to a RHEL base system that is operating in FIPS mode.

To run {ProjectServer} on a {RHEL} base system operating in FIPS mode, you must install {Project} on a freshly provisioned RHEL base system operating in FIPS mode.
For more information, see {InstallingProjectDocURL}preparing-environment-for-satellite-installation[Preparing your environment for installation] in _Installing {ProjectServer}_.
