[[upgrading_a_disconnected_satellite]]
= Upgrading a Disconnected {ProjectServer}

Use this procedure if your {ProjectServer} is not connected to the Red{nbsp}Hat Content Delivery Network.

[WARNING]
====
// Keep this in sync with common/modules/snip_using_installer_noop.adoc
* If you customized configuration files, either manually or using a tool such as Hiera, these changes are overwritten when you enter the `{foreman-maintain}` command during upgrading or updating.
You can use the `--noop` option with the `{foreman-installer}` command to review the changes that are applied during upgrading or updating.
For more information, see the Red Hat Knowledgebase solution https://access.redhat.com/solutions/3351311[How to use the noop option to check for changes in {Project} config files during an upgrade].
ifdef::katello,orcharhino,satellite[]
* The hammer import and export commands have been replaced with `hammer content-import` and `hammer content-export` tooling.
+
If you have scripts that are using `hammer content-view version export`, `hammer content-view version export-legacy`, `hammer repository export`, or their respective import commands, you have to adjust them to use the `hammer content-export` command instead, along with its respective import command.
* If you implemented custom certificates, you must retain the content of both the `/root/ssl-build` directory and the directory in which you created any source files associated with your custom certificates.
+
Failure to retain these files during an upgrade causes the upgrade to fail.
If these files have been deleted, they must be restored from a backup in order for the upgrade to proceed.
endif::[]
====

.Before You Begin

* Review and update your firewall configuration before upgrading your {ProjectServer}.
For more information, see {InstallingServerDisconnectedDocURL}Ports_and_Firewalls_Requirements_satellite[Ports and Firewalls Requirements] in _{InstallingServerDisconnectedDocTitle}_.
* Ensure that you do not delete the manifest from the Customer Portal or in the {ProjectWebUI} because this removes all the entitlements of your content hosts.
* Back up and remove all Foreman hooks before upgrading.
Reinstate hooks only after {Project} is known to be working after the upgrade is complete.
ifdef::satellite[]
* All {ProjectServer}s must be on the same version.
endif::[]


.Upgrade Disconnected {ProjectServer}

. Create a backup.
+
* On a virtual machine, take a snapshot.
* On a physical machine, create a backup.

. A pre-upgrade script is available to detect conflicts and list hosts which have duplicate entries in {ProjectServer} that can be unregistered and deleted after upgrade.
In addition, it will detect hosts which are not assigned to an organization.
If a host is listed under *Hosts* > *All hosts* without an organization association and if a content host with same name has an organization already associated with it then the content host will automatically be unregistered.
This can be avoided by associating such hosts to an organization before upgrading.
+
Run the pre-upgrade check script to get a list of hosts that can be deleted after upgrading.
If any unassociated hosts are found, associating them to an organization before upgrading is recommended.
+
[options="nowrap"]
----
# foreman-rake katello:upgrade_check
----

. Optional: If you made manual edits to DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, back up the configuration files because the installer only supports one domain or subnet, and therefore restoring changes from these backups might be required.

. Optional: If you made manual edits to DNS or DHCP configuration files and do not want to overwrite the changes, enter the following command:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} --foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false
----

. In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
If there are discovered hosts available, turn them off and then delete all entries under the `Discovered hosts` page.
Select all other organizations in turn using the organization setting menu and repeat this action as required.
Reboot these hosts after the upgrade has completed.

. Make sure all external {SmartProxyServer}s are assigned to an organization, otherwise they might get unregistered due to host-unification changes.

. Remove old repositories:
+
[options="nowrap" subs="attributes"]
----
# rm /etc/yum.repos.d/*
----

. Stop {Project} services:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service stop
----

. Obtain the latest ISO files by following the {InstallingServerDisconnectedDocURL}downloading-the-binary-dvd-images_satellite[Downloading the Binary DVD Images] procedure in _{InstallingServerDisconnectedDocTitle}_.

. Create directories to serve as a mount point, mount the ISO images, and configure the `rhel8` repository by following the {InstallingServerDisconnectedDocURL}configuring-the-base-operating-system-with-offline-repositories-in-rhel-8_satellite[Configuring the Base Operating System with Offline Repositories in RHEL 8] procedure in _{InstallingServerDisconnectedDocTitle}_.
+
Do not install or update any packages at this stage.

. Configure the {Project} {ProjectVersion} repository from the ISO file.

.. Copy the ISO file's repository data file for the {ProjectName} packages:
+
[options="nowrap"]
----
# cp /media/sat6/Satellite/media.repo /etc/yum.repos.d/satellite.repo
----

.. Edit the `/etc/yum.repos.d/satellite.repo` file:
+
----
# vi /etc/yum.repos.d/sat6.repo
----

... Change the default `InstallMedia` repository name to `{Project}-{ProjectVersion}`:
+
[options="nowrap" subs="+quotes,attributes"]
----
[{Project}-{ProjectVersion}]
----

... Add the `baseurl` directive:
+
[options="nowrap"]
----
baseurl=file:///media/sat6/Satellite
----

. Configure the {ProjectName} Maintenance repository from the ISO file.

.. Copy the ISO file's repository data file for {ProjectName} Maintenance packages:
+
[options="nowrap"]
----
# cp /media/sat6/Maintenance/media.repo /etc/yum.repos.d/satellite-maintenance.repo
----

.. Edit the `/etc/yum.repos.d/satellite-maintenance.repo` file:
+
[options="nowrap"]
----
# vi /etc/yum.repos.d/satellite-maintenance.repo
----

... Change the default `InstallMedia` repository name to `{Project}-Maintenance`:
+
[options="nowrap" subs="+quotes,attributes"]
----
[{Project}-Maintenance]
----

... Add the `baseurl` directive:
+
[options="nowrap"]
----
baseurl=file:///media/sat6/Maintenance/
----

. Configure the Ansible repository from the ISO file.

.. Copy the ISO file's repository data file for Ansible packages:
+
[options="nowrap"]
----
# cp /media/sat6/ansible/media.repo /etc/yum.repos.d/ansible.repo
----

.. Edit the `/etc/yum.repos.d/ansible.repo` file:
+
[options="nowrap"]
----
# vi /etc/yum.repos.d/ansible.repo
----

... Change the default `InstallMedia` repository name to `Ansible`:
+
[options="nowrap" subs="+quotes,attributes"]
----
[Ansible]
----

... Add the `baseurl` directive:
+
[options="nowrap"]
----
baseurl=file:///media/sat6/ansible/
----

. Configure the Red Hat Software Collections repository from the ISO file.

.. Copy the ISO file's repository data file for Red Hat Software Collections packages:
+
[options="nowrap"]
----
# cp /media/sat6/RHSCL/media.repo /etc/yum.repos.d/RHSCL.repo
----

.. Edit the `/etc/yum.repos.d/RHSCL.repo` file:
+
[options="nowrap"]
----
# vi /etc/yum.repos.d/RHSCL.repo
----

... Change the default `InstallMedia` repository name to `RHSCL`:
+
[options="nowrap" subs="+quotes,attributes"]
----
[RHSCL]
----

... Add the `baseurl` directive:
+
[options="nowrap"]
----
baseurl=file:///media/sat6/RHSCL/
----

. Because of the lengthy upgrade time, use a utility such as `tmux` to suspend and reattach a communication session.
You can then check the upgrade progress without staying connected to the command shell continuously.
+
If you lose connection to the command shell where the upgrade command is running you can see the logs in `{installer-log-file}` to check if the process completed successfully.

. Check the available versions to confirm the version you want is listed:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade list-versions
----

. Use the health check option to determine if the system is ready for upgrade.
When prompted, enter the hammer admin user credentials to configure `{foreman-maintain}` with hammer credentials.
These changes are applied to the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade check --target-version {TargetVersion} \
--whitelist="repositories-validate,repositories-setup"
----
+
Review the results and address any highlighted error conditions before performing the upgrade.
. Perform the upgrade:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade run --target-version {TargetVersion} \
--whitelist="repositories-validate,repositories-setup"
----
+
If the script fails due to missing or outdated packages, you must download and install these separately.
For more information, see {InstallingServerDisconnectedDocURL}resolving-package-dependency-errors_satellite[Resolving Package Dependency Errors] in _{InstallingServerDisconnectedDocTitle}_.

include::snip_needs_reboot.adoc[]

. Optional: If you made manual edits to DNS or DHCP configuration files, check and restore any changes required to the DNS and DHCP configuration files using the backups that you made.

. If you make changes in the previous step, restart {Project} services:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service restart
----

. If you have the OpenSCAP plug-in installed, but do not have the default OpenSCAP content available, enter the following command.
+
[options="nowrap" subs="attributes"]
----
# foreman-rake foreman_openscap:bulk_upload:default
----

. In the {ProjectWebUI}, go to *Configure* > *Discovery Rules* and associate selected organizations and locations with discovery rules.
