[[upgrading_discovery_capsule]]

= Upgrading Discovery on {SmartProxyServer}s

. Verify that the Foreman Discovery package is current on {ProjectServer}.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {package-install-project} tfm-rubygem-foreman_discovery
----

. If an update occurred in the previous step, restart the `{foreman-maintain}` services.
+
----
# {foreman-maintain} service restart
----

. Upgrade the Discovery image on the {Project} {SmartProxy} that is either connected to the provisioning network with discovered hosts or provides TFTP services for discovered hosts.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {package-install-project} foreman-discovery-image
----

. On the same instance, install the package which provides the Proxy service, and then restart `foreman-proxy` service.
+
[options="nowrap", subs="+quotes,verbatim,attributes"]
----
# {package-install-project} tfm-rubygem-smart_proxy_discovery
# service foreman-proxy restart
----

. In the {Project} web UI, go to *Infrastructure* > *{SmartProxies}* and verify that the relevant {SmartProxy} lists *Discovery* in the features column. Select *Refresh* from the *Actions* drop-down menu if necessary.

. Go to *Infrastructure* > *Subnets* and for each subnet on which you want to use discovery:
.. Click the subnet name.
.. On the *{SmartProxies}* tab, ensure the *Discovery {SmartProxy}* is set to a {SmartProxy} you configured above.
