[id="upgrading_capsules-separately-from-satellite_{context}"]
= Upgrading {SmartProxies} Separately from {Project}

You can upgrade {Project} to the version {ProductVersion} and keep {SmartProxies} at the version {ProductVersionPrevious} until you have bandwidth to upgrade them too.

All the functionality that worked previously works on {ProductVersionPrevious} {SmartProxies}. However, the functionality added in the {ProductVersion} release will not work until you upgrade {SmartProxies} to {ProductVersion}.

Upgrading {SmartProxies} after upgrading {Project} can be useful in the following example scenarios:

. If you want to have several smaller outage windows instead of one larger window.
. If {SmartProxies} in your organization are managed by several teams and are located in different locations.
. If you use a load-balanced configuration, you can upgrade one load-balanced {SmartProxy} and keep other load-balanced {SmartProxies} at 1 version lower. This allows you to upgrade all {SmartProxies} one after another without any outage.
