[[upgrading_a_connected_satellite_server]]
= Upgrading a Connected {ProjectServer}

Use this procedure for a {ProjectServer} with access to the public internet

[WARNING]
If you customize configuration files, manually or using a tool such as Hiera, these changes are overwritten when the installation script runs during upgrading or updating.
You can use the `--noop` option with the {foreman-installer} script to test for changes.
For more information, see the Red Hat Knowledgebase solution https://access.redhat.com/solutions/3351311[How to use the noop option to check for changes in {Project} config files during an upgrade.]

.Upgrade {ProjectServer}

. Create a backup.
+
* On a virtual machine, take a snapshot.
* On a physical machine, create a backup.
+
For more information about backups, see {AdministeringDocURL}Backing_Up_Server_and_Proxy_admin[Backing Up {ProjectServer} and {SmartProxyServer}] in _{AdministeringDocTitle}_.

. Optional: If you made manual edits to DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, back up the configuration files because the installer only supports one domain or subnet, and therefore restoring changes from these backups might be required.

. Optional: If you made manual edits to DNS or DHCP configuration files and do not want to overwrite the changes, enter the following command:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} --foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false
----
ifdef::katello[]
. Optional: If you use PostgreSQL as an external database, on the PostgreSQL server, install the `rh-postgresql12-postgresql-evr` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum install rh-postgresql12-postgresql-evr
----
endif::[]
. In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
On the Discovered Hosts page, power off and then delete the discovered hosts.
From the *Select an Organization* menu, select each organization in turn and repeat the process to power off and delete the discovered hosts.
Make a note to reboot these hosts when the upgrade is complete.
ifdef::satellite[]
. Ensure that the {Project} Maintenance repository is enabled:
+
[options="nowrap" subs="attributes"]
----
# subscription-manager repos --enable \
{RepoRHEL7ServerSatelliteMaintenanceProductVersion}
----

. Check the available versions to confirm the version you want is listed:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade list-versions
----

. Use the health check option to determine if the system is ready for upgrade.
When prompted, enter the hammer admin user credentials to configure `{foreman-maintain}` with hammer credentials.
These changes are applied to the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade check --target-version {TargetVersion}
----
+
Review the results and address any highlighted error conditions before performing the upgrade.

. Because of the lengthy upgrade time, use a utility such as `tmux` to suspend and reattach a communication session.
You can then check the upgrade progress without staying connected to the command shell continuously.
+
If you lose connection to the command shell where the upgrade command is running you can see the logged messages in the `{installer-log-file}` file to check if the process completed successfully.

. Perform the upgrade:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade run --target-version {TargetVersion}
----
endif::[]
ifdef::katello[]
. Check for running tasks
+
[options="nowrap" subs="attributes"]
----
# foreman-rake katello:upgrade_check
----
. Update operating system packages:
+
[options="nowrap" subs="attributes"]
----
# yum update -y
----
. Update repositories
+
.For {EL} 7 Users:
[options="nowrap" subs="attributes"]
----
# yum update -y https://yum.theforeman.org/releases/{ProjectVersion}/el7/x86_64/foreman-release.rpm \
                https://yum.theforeman.org/katello/{KatelloVersion}/katello/el7/x86_64/katello-repos-latest.rpm
# yum install -y centos-release-scl-rh
----
+
.For {EL} 8 Users:
[options="nowrap" subs="attributes"]
----
# dnf update -y https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm \
                https://yum.theforeman.org/katello/{KatelloVersion}/katello/el8/x86_64/katello-repos-latest.rpm
----
. Ensure the module streams are enabled for {EL} 8:
+
[options="nowrap" subs="attributes"]
----
# dnf module enable -y katello:el8 pulpcore:el8
----
. Clean the yum cache and update the required packages:
+
[options="nowrap" subs="attributes"]
----
# yum clean all
# yum -y update
----
. Stop all services:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service stop
----
+
. Run the installer:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer}
----
endif::[]
. Determine if the system needs a reboot:
.. Check the version of newest installed kernel:
+
[options="nowrap"]
----
# rpm --query --last kernel | head -n 1
----
.. Compare this to the version of currently running kernel:
+
[options="nowrap"]
----
# uname --kernel-release
----
. Optional: If the newest kernel differs from the currently running kernel, reboot the system:
+
----
# reboot
----
. If using a BASH shell, after a successful or failed upgrade, enter:
+
[options="nowrap" subs="attributes"]
----
# hash -d {foreman-maintain} service 2> /dev/null
----
