[[upgrading_a_connected_satellite_server]]
= Upgrading a Connected {ProjectServer}

Use this procedure for a {ProjectServer} with access to the public internet

include::../common/modules/snip_using_installer_noop.adoc[]

.Upgrade {ProjectServer}

. Create a backup.
+
* On a virtual machine, take a snapshot.
* On a physical machine, create a backup.
+
For more information about backups, see {AdministeringDocURL}backing-up-{project-context}-server-and-{smart-proxy-context}_admin[Backing Up {ProjectServer} and {SmartProxyServer}] in _{AdministeringDocTitle}_.

. Optional: If you made manual edits to DNS or DHCP configuration in the `/etc/zones.conf` or `/etc/dhcp/dhcpd.conf` files, back up the configuration files because the installer only supports one domain or subnet, and therefore restoring changes from these backups might be required.

. Optional: If you made manual edits to DNS or DHCP configuration files and do not want to overwrite the changes, enter the following command:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer} --foreman-proxy-dns-managed=false \
--foreman-proxy-dhcp-managed=false
----
ifdef::katello[]
. Optional: If you use PostgreSQL as an external database, on the PostgreSQL server, install the `rh-postgresql12-postgresql-evr` package:
+
[options="nowrap" subs="+quotes,attributes"]
----
# yum install rh-postgresql12-postgresql-evr
----
endif::[]
. In the {ProjectWebUI}, navigate to *Hosts* > *Discovered hosts*.
On the Discovered Hosts page, power off and then delete the discovered hosts.
From the *Select an Organization* menu, select each organization in turn and repeat the process to power off and delete the discovered hosts.
Make a note to reboot these hosts when the upgrade is complete.
ifdef::satellite[]
. In the current upgrade process, you must enable the {Project} {ProductVersion} (or {SmartProxy}) repository to restrict any updates outside the {Project} Maintenance repository.
Please read the {MultiBaseURL}release_notes/assembly_introducing-red-hat-satellite_sat6-release-notes#ref_known-issues_assembly_introducing-red-hat-satellite[Known Issues] in the Release Notes as a workaround before proceeding further.
+
Enable the {Project} Maintenance repository and the {Project} {ProjectVersion} repositories:
+
[options="nowrap" subs="attributes"]
----
# subscription-manager repos \
--enable {RepoRHEL8ServerSatelliteMaintenanceProductVersion} \
--enable {RepoRHEL8ServerSatelliteServerProductVersion}
----
If the {Project} {ProductVersionPrevious} system was upgraded from {RHEL} 7 to {RHEL} 8 using Leapp, manually enable the Satellite module:
+
[options="nowrap" subs="attributes"]
----
# dnf module enable satellite:el8
----
endif::[]

. Check the available versions to confirm the version you want is listed:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade list-versions
----

. Use the health check option to determine if the system is ready for upgrade.
When prompted, enter the hammer admin user credentials to configure `{foreman-maintain}` with hammer credentials.
These changes are applied to the `/etc/foreman-maintain/foreman-maintain-hammer.yml` file.
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade check --target-version {TargetVersion}
----
+
Review the results and address any highlighted error conditions before performing the upgrade.

. Because of the lengthy upgrade time, use a utility such as `tmux` to suspend and reattach a communication session.
You can then check the upgrade progress without staying connected to the command shell continuously.
+
If you lose connection to the command shell where the upgrade command is running you can see the logged messages in the `{installer-log-file}` file to check if the process completed successfully.

. Perform the upgrade:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} upgrade run --target-version {TargetVersion}
----
endif::[]
ifdef::katello[]
. Check for running tasks
+
[options="nowrap" subs="attributes"]
----
# foreman-rake katello:upgrade_check
----
. Update operating system packages:
+
[options="nowrap" subs="attributes"]
----
# yum update -y
----
. Update repositories
+
.For {EL} 7 Users:
[options="nowrap" subs="attributes"]
----
# yum update -y https://yum.theforeman.org/releases/{ProjectVersion}/el7/x86_64/foreman-release.rpm \
                https://yum.theforeman.org/katello/{KatelloVersion}/katello/el7/x86_64/katello-repos-latest.rpm
# yum install -y centos-release-scl-rh
----
+
.For {EL} 8 Users:
[options="nowrap" subs="attributes"]
----
# dnf update -y https://yum.theforeman.org/releases/{ProjectVersion}/el8/x86_64/foreman-release.rpm \
                https://yum.theforeman.org/katello/{KatelloVersion}/katello/el8/x86_64/katello-repos-latest.rpm
----
. Ensure the module streams are enabled for {EL} 8:
+
[options="nowrap" subs="attributes"]
----
# dnf module enable -y katello:el8 pulpcore:el8
----
. Clean the yum cache and update the required packages:
+
[options="nowrap" subs="attributes"]
----
# yum clean all
# yum -y update
----
. Stop all services:
+
[options="nowrap" subs="attributes"]
----
# {foreman-maintain} service stop
----
+
. Run the installer:
+
[options="nowrap" subs="attributes"]
----
# {foreman-installer}
----
endif::[]
. Determine if the system needs a reboot:
.. Check the version of newest installed kernel:
+
[options="nowrap"]
----
# rpm --query --last kernel | head -n 1
----
.. Compare this to the version of currently running kernel:
+
[options="nowrap"]
----
# uname --kernel-release
----
. Optional: If the newest kernel differs from the currently running kernel, reboot the system:
+
----
# reboot
----
. If using a BASH shell, after a successful or failed upgrade, enter:
+
[options="nowrap" subs="attributes"]
----
# hash -d {foreman-maintain} service 2> /dev/null
----
