[id="enabling-the-satellite-tools-repository_{context}"]
= Enabling the {project-client-name} Repository

ifeval::["{build}" == "foreman"]
You require the Katello plug-in to complete this procedure.
endif::[]

The {project-client-name} repository provides the `katello-agent`, `katello-host-tools`, and `puppet` packages for clients registered to {ProjectServer}.

ifeval::["{mode}" == "disconnected"]
.Prerequisites

* Ensure that you import all content ISO images that you require into {ProjectServer}.
endif::[]

.Procedure

. In the {Project} web UI, navigate to *Content* > *Red Hat Repositories*.

. Use the Search field to enter the following repository name: *{project-client-name} (for RHEL 7 Server) (RPMs)*.

. In the Available Repositories pane, click on *{project-client-name} (for RHEL 7 Server) (RPMs)* to expand the repository set.
+
If the *{project-client-name}* items are not visible, it may be because they are not included in the Subscription Manifest obtained from the Customer Portal.
To correct that, log in to the Customer Portal, add these repositories, download the Subscription Manifest and import it into {Project}.

. For the `x86_64` entry, click the *Enable* icon to enable the repository.

Enable the {project-client-name} repository for every supported major version of {RHEL} running on your hosts.
After enabling a Red Hat repository, a Product for this repository is automatically created.

.For CLI Users

* Enable the {project-client-name} repository using the `hammer repository-set enable` command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer repository-set enable --organization _"initial_organization_name"_ \
--product 'Red Hat Enterprise Linux Server' \
--basearch='x86_64' \
--name 'Red Hat {project-client-name} (for RHEL 7 Server) (RPMs)'
----
