== First local boot ==

Host -> DHCP : requests the reserved IP and PXE details
Host -> TFTP : bootloader is downloaded
Host -> TFTP : bootloader gets MAC-based config
Foreman -> Host : tells bootloader to boot from HDD
group Initial host configuration
    group #ffcc32 Ansible [when enabled and Ansible roles assigned?]
        Host -> Proxy : sends initial facts
        Proxy -> Foreman : forwards initial facts
        note over Host : performs initial configuration
        Host -> Proxy : sends initial report
        Proxy -> Foreman : forwards initial report
    end
    group #ffcc32 Puppet [when enabled]
        Host -> Puppet : sends initial facts
        Puppet -> Foreman : forwards initial facts
        note over Host : performs initial configuration
        Host -> Puppet : sends initial report
        Puppet -> Foreman : forwards initial report
    end
end
note over Host : in operation
