loop
   Host -> Foreman : requests OS content
   Foreman -> Proxy : requests OS content
   Proxy -> Pulp : requests OS content
   Pulp -> Proxy : provides OS content
   Proxy -> Foreman : provides OS content
   Foreman -> Host : provides OS content
end