@startuml

!include foreman.pstyle

title VMware template provisioning with user data

actor       User
participant Foreman
participant "Foreman\nProxy X" as Proxy
participant "Virtual\nmachine" as VM
participant "VMware\nvCenter" as vCenter

User -> Foreman : Provisions VM\nin network X
Foreman -> vCenter : Creates a VM from a template on port 443
vCenter -> VM : Clones VM from template
VM -> Proxy : Calls back\nto Foreman port 80\nvia Proxy X 8000
Proxy -> Foreman : Forwards Userdata on port 80
Foreman -> Foreman : Redirects Userdata to port 443
VM -> Proxy : Registers
Proxy -> Foreman : Forwards VM registration to Foreman

@enduml
