@startuml

!include foreman.pstyle

title VMware Template Provisioning

participant User
participant Satellite
participant vCenter
participant "Capsule X" as Capsule
participant VM

User --> Satellite : Provision VM in network X
Satellite --> vCenter : Create a VM from a template on port 443
vCenter --> VM : Clone VM from template
VM --> Capsule : Call Back to Sat port 80 via Capsule X 8000
Capsule --> Satellite : Forward Userdata on port 80
Satellite --> Satellite : Redirect Userdata to port 443
VM --> Capsule : Registers itself to Satellite
Capsule -->Satellite : Forward VM registration to Satellite

@enduml
