User -> Foreman : Create host
Foreman -> Proxy : Request a free IP address
Proxy -> DHCP : Search for a free IP address in DHCP
DHCP -> Proxy : Return the free IP address
Proxy -> Foreman : Pass the free IP address
group Templates [*PXE* installer boot]
    Foreman -> Proxy : Render boot-loader configuration files
end
Proxy -> Proxy : Deploy boot-loader configuration files\nto ""/var/lib/tftpboot""
Foreman -> Proxy : Command to download installer kernel\nand initial RAM disk
Proxy -> Proxy : Download kernel and initial RAM disk
Foreman -> Proxy : Request DHCP reservation
Proxy -> DHCP : Create DHCP reservation
Foreman -> Proxy : Create DNS records
Proxy -> DNS : Forward DNS records
Proxy -> Foreman : Report status of TFTP, DHCP & DNS
Foreman -> User : Host is created\n(build mode enabled)
