loop
   Host -> Foreman : requests installation media
   Foreman -> Proxy : requests installation media
   Proxy -> Foreman : provides installation media
   Foreman -> Host : provides installation media
end
