User -> Foreman : create host action
Foreman -> Proxy : request a free IP address
Proxy -> DHCP : search for a free IP in DHCP
DHCP -> Proxy : return the free IP
Proxy -> Foreman : pass the free IP
group Templates [*PXE* installer boot]
    Foreman -> Proxy : render boot-loader configuration files
end
Proxy -> TFTP : deploy boot-loader configuration files\nto ""/var/lib/tftpboot""
Foreman -> Proxy : command to download installer kernel\nand initial RAM disk
note over Proxy : download installer kernel\nand initial RAM disk
Foreman -> Proxy : request DHCP reservation
Proxy -> DHCP : create DHCP reservation
Foreman -> Proxy : create DNS records
Proxy -> DNS : forward DNS records
Proxy -> Foreman : report status of TFTP, DHCP & DNS
Foreman -> User : host is created\n(build mode enabled)
