@startuml

!include foreman.pstyle

title Image-based provisioning with cloud-init configuration

actor       User
participant "Provisioned\nInstance" as Host
participant "Foreman" as Foreman
participant "Foreman\nProxy" as Proxy
participant "Infrastructure\nCloud" as Cloud
participant DNS
!if ($puppet)
participant "Puppet\nserver" as Puppet
!endif

note over Foreman : has an image\nwith cloud-init flag

== Create host in Foreman ==

User -> Foreman : clicks **Create Host**
User -> Foreman : selects cloud resource,\nthe image and submits
group Template [cloud-init]
   Foreman -> Proxy : renders the cloud-init script
end
Foreman -> Cloud : creates new instance\nwith cloud-init info
Cloud -> Foreman : reports IP address
Foreman -> Proxy : creates DNS records
Proxy -> DNS : forwards DNS records
!if ($puppet)
Foreman -> Proxy : creates Puppet sign request (autosign enabled)
Proxy -> Puppet : forwards Puppet sign request
!endif
Foreman -> Cloud : starts the instance
note over Host : boots up

== Cloud-init script ==

!include prov-initial-configuration.iuml
Host -> Foreman : calls home\n(disables build mode)

!if ($puppet)
== First Puppet run ==

Host -> Puppet : sends initial facts
Puppet -> Foreman : forwards initial facts
Host -> Puppet : compiles catalog
note over Host : host is configured
Host -> Puppet : sends initial report
Puppet -> Foreman : forwards initial report
!endif

note over Host : in operation

@enduml
