User -> Foreman : clicks **Create Host**
Foreman -> Proxy : requests free IP address
Proxy -> DHCP : reads DHCP cofiguration
note over Foreman : pings IP address
User -> Foreman : submits the **Create host** form
group Templates [*PXE* installer boot]
    Foreman -> Proxy : renders bootloader configuration files
end
Proxy -> TFTP : deploys bootloader configuration files
Foreman -> Proxy : commands to download OS installer kernel\nand initial RAM disk
Proxy -> Pulp : downloads OS installer kernel\nand initial RAM disk
Foreman -> Proxy : creates DHCP reservation
Proxy -> DHCP : forwards DHCP reservation
Foreman -> Proxy : creates DNS records
Proxy -> DNS : forwards DNS records
note over Foreman : host is created\n(build mode enabled)
