loop
   Host -> Foreman : Request installation media
   Foreman -> Proxy : Request installation media
   Proxy -> Foreman : Provide installation media
   Foreman -> Host : Provide installation media
end
