!if ($puppet)
opt when Puppet enabled
    Host -> Puppet : signs Puppet client certificate (Puppet agent)
end
!else
note over Host : initial host configuration\n- remote execution,\n- signs Puppet client cert,\n- runs Ansible roles,\n- etc.
!endif
