Host -> DHCP : requests the reserved IP and DHCP options
Host -> TFTP : downloads boot loader
Host -> TFTP : gets MAC-based boot-loader config
Host -> Host : config tells boot loader to boot from HDD
Host -> Host : boots from HDD
