!if ($networkboot)
Host -> DHCP : requests the reserved IP
!endif
Host -> Host : boots from HDD
!if ($puppet)
opt #ffcc32 when Puppet is enabled
    Host -> Puppet : sends initial facts
    Puppet -> Foreman : forwards initial facts
    note over Host : performs initial configuration
    Host -> Puppet : sends initial report
    Puppet -> Foreman : forwards initial report
end
!endif
note over Host : in operation
