!if ($puppet)
opt when Puppet enabled
    Host -> Puppet : sends CSR
    Puppet -> Host : sends certificate (if allowed to)
end
!else
note over Host : initial host configuration\n- remote execution,\n- signs Puppet client cert,\n- runs Ansible roles,\n- etc.
!endif
