!if ($puppet)
opt when Puppet enabled
    Host -> Host : install Puppet agent
    Host -> Puppet : send CSR
    Puppet -> Host : send certificate (if allowed to)
end
!endif
Host -> Host : configure\n- Subscription Manager,\n- remote execution,\n- run Ansible roles,\n- etc.
