opt when Puppet enabled
   Host -> Puppet : Send facts
   Host -> Puppet : Request catalog
   Puppet -> Foreman : Forward facts
   Puppet -> Foreman : Request external node classification
   Puppet -> Host : Respond with requested catalog
   Host -> Host : Run catalog
   Host -> Puppet : Send report
   Puppet -> Foreman : Forward report
end
