Host -> Puppet : sends facts
Host -> Puppet : requests catalog
Puppet -> Foreman : forwards facts
Puppet -> Foreman : requests ENC
Puppet -> Host : responds with requested catalog
note over Host : runs catalog
Host -> Puppet : sends report
Puppet -> Foreman : forwards report
