Host -> Puppet : send facts
Host -> Puppet : request catalog
Puppet -> Foreman : forward facts
Puppet -> Foreman : request ENC
Puppet -> Host : respond with requested catalog
note over Host : run catalog
Host -> Puppet : send report
Puppet -> Foreman : forward report
