include::common/attributes.adoc[]

:imagesdir: images
:upgrade-guide:
ifdef::foreman-el,foreman-deb,katello[]
:toc:
:toc-placement: left
endif::[]

:numbered:
:context: user-interface-guide

// WARNING: Do not rename or delete anchors starting with "fmid" prefix since
// they are linked from the Foreman application.

= {ProjectServer} User Interface Quickstart

[[fmid-external-authentication]]
== External Authentication

For more information, see {AdministeringDocURL}chap-Administering-Configuring_External_Authentication[Configuring External Authentication] in _Administering {ProjectName}_.

[[fmid-searching-and-bookmarking]]
== Searching and Bookmarking

For more information, see {AdministeringDocURL}chap-Administering-Searching_and_Bookmarking[Searching and Bookmarking] in _Administering {ProjectName}_.

[[fmid-global-parameters]]
== Global Parameters

TODO: We need some introduction for this topic, found nothing.

For more information, see {ManagingHostsDocURL}customizing-the-registration-templates_managing-hosts[Customizing the Registration Templates] in _Managing Hosts_.

[[fmid-compute-resources]]
== Compute Resources

A Compute Resource represents a virtual or cloud operating system instance.
+
.Instructions
* {ProvisioningDocURL}Provisioning_Cloud_Instances_in_Amazon_EC2-Adding_a_Amazon_EC2_Connection_to_the_Satellite_Server[Amazon EC2]
* {ProvisioningDocURL}adding-gce-connection_gce-provisioning[Google Compute Engine]
* {ProvisioningDocURL}adding-kubevirt-connection_kubevirt-provisioning[KubeVirt]
* {ProvisioningDocURL}adding-kvm-connection_kvm-provisioning[KVM]
* {ProvisioningDocURL}adding-azure-connection_azure-provisioning[Microsoft Azure]
* {ProvisioningDocURL}adding-openstack-connection_openstack-provisioning[OpenStack]
* {ProvisioningDocURL}adding-rhv-connection_rhv-provisioning[oVirt]
* {ProvisioningDocURL}Provisioning_Virtual_Machines_in_VMware_vSphere-Adding_a_VMware_vSphere_Connection_to_the_Satellite_Server[VMWare]

[[fmid-compute-profiles]]
== Compute Profiles

A Compute Profile specifies default attributes for new virtual machines on a compute resource.
+
.Instructions
* {ProvisioningDocURL}Provisioning_Cloud_Instances_in_Amazon_EC2-Adding_Amazon_EC2_Details_to_a_Compute_Profile[Amazon EC2]
* {ProvisioningDocURL}adding-gce-details-to-a-compute-profile_gce-provisioning[Google Compute Engine]
* {ProvisioningDocURL}adding-kvm-details-to-a-compute-profile_kvm-provisioning[KVM]
* {ProvisioningDocURL}adding-azure-details-to-a-compute-profile_azure-provisioning[Microsoft Azure]
* {ProvisioningDocURL}adding-openstack-details-to-a-compute-profile_openstack-provisioning[OpenStack]
* {ProvisioningDocURL}adding-rhv-details-to-a-compute-profile_rhv-provisioning[oVirt]
* {ProvisioningDocURL}Provisioning_Virtual_Machines_in_VMware_vSphere-Adding_VMware_vSphere_Details_to_a_Compute_Profile[VMWare]

For more information, see {ProvisioningDocURL}creating-compute-profiles_provisioning[Creating Compute Profiles] in _{ProjectName} Provisioning Guide_.

[[fmid-puppet-config-groups]]
== Puppet Config Groups

// TODO: Modularize?
//include::modules/con_puppet-introduction.adoc[leveloffset=+1]

* {ManagingHostsDocURL}using-puppet-for-configuration-management_managing-hosts[Using Puppet for Configuration Management]
* {ManagingHostsDocURL}puppet_guide_using_puppet_classes_managing-hosts[Puppet Classes and Config Groups]

[[fmid-domains]]
== Domains

// TODO: Modularize this
{ProjectServer} defines domain names for each host on the network.
{ProjectServer} must have information about the domain and Smart Proxy server responsible for domain name assignment.

* {ProvisioningDocURL}Configuring_Networking-Adding_a_Domain_to_the_Satellite_Server[Adding a Domain]

[[fmid-partition-tables]]
== Partition Tables

// TODO: Modularize this
A partition table is a type of template that defines the way {ProjectServer} configures the disks available on a new host.

* {ProvisioningDocURL}creating-partition-tables_provisioning[Creating Partition Tables]

[[fmid-provisioning-templates]]
== Provisioning Templates

// TODO: Modularize this
A provisioning template defines the way {ProjectServer} installs an operating system on a host.

* {ProvisioningDocURL}provisioning-templates_provisioning[Provisioning Templates introduction]
* {ManagingHostsDocURL}appe-Red_Hat_Satellite-Managing_Hosts-Template_Writing_Reference[Template Writing Reference]
* {ManagingHostsDocURL}Synchronizing_Templates_Repositories[Synchronizing Template Repositories]

[[fmid-operating-systems]]
== Operating Systems

// TODO: Modularize this
An operating system is a collection of resources that define how {ProjectServer} installs a base operating system on a host.
Operating system entries combine previously defined resources, such as installation media, partition tables, provisioning templates, and others.

* {ProvisioningDocURL}creating-operating-systems_provisioning[Creating Operating Systems]

[[fmid-http-proxies]]
== HTTP Proxies

If your network uses an HTTP Proxy, you can configure {Project} server to use an HTTP proxy for requests to EC2 Compute Resource.
ifdef::katello,satellite[]
Red Hat Content Delivery Network (CDN) or another content sources also use HTTP Proxy definition.
endif::[]

* {ProvisioningDocURL}Provisioning_Cloud_Instances_in_Amazon_EC2-Using-an-HTTP-Smart-Proxy[Using HTTP Proxy with Amazon EC2]
* {InstallingProjectDocURL}configuring-satellite-with-an-http-proxy_foreman[Configuring an HTTP Proxy]

// This is completely undocumented, or I haven't found it:
To configure an HTTP(S) Proxy for other Compute Resources, go to *Administer > Settings* and select the *General* tab.
Set an *HTTP(S) proxy* for all outgoing HTTP connections from {Project}.

[[fmid-fact-values]]
== Fact Values

// TODO: This is missing from NG docs: https://theforeman.org/manuals/2.5/index.html#3.5.5FactsandtheENC

* https://theforeman.org/manuals/2.5/index.html#3.5.5FactsandtheENC[Facts and ENC]

[[fmid-hosts]]
== Hosts

A host is any Linux client that {Project} manages.
For further information, visit {ManagingHostsDocURL}overview-of-hosts-in-satellite[Hosts Overview].

* {ManagingHostsDocURL}Administering_Hosts[Administering Hosts]

[[fmid-puppet-parametrized-classes]]
== Parameterized Puppet Classes

// TODO: Missing in NG docs: https://theforeman.org/manuals/2.5/index.html#4.2ManagingPuppet

* {ManagingHostsDocURL}using-puppet-for-configuration-management_managing-hosts[Using Puppet for Configuration Management]
* https://theforeman.org/manuals/2.5/index.html#4.2ManagingPuppet[Managing Puppet]

[[fmid-realm]]
== External Authentication for Provisioned Hosts

It is possible to configure {Project} to enroll provisioned hosts to a FreeIPA realm group.

* {AdministeringDocURL}sect-Administering-Configuring_External_Authentication-External_Authentication_for_Provisioned_Hosts[External Authentication for Provisioned Hosts]

[[fmid-report-templates]]
== Report Templates

// TODO: Modularize
You can use report templates to query {Project} data to obtain information about, for example, host status, registered hosts, applicable errata, applied errata, subscription details, and user activity.
Use the the report templates that ship with {Project} or write your own custom report templates that suit your requirements.

* {ManagingHostsDocURL}using_report_templates[Using Report Templates to Monitor Hosts]
* {ManagingHostsDocURL}appe-Red_Hat_Satellite-Managing_Hosts-Template_Writing_Reference[Template Writing Reference]
* {ManagingHostsDocURL}Synchronizing_Templates_Repositories[Synchronizing Template Repositories]

[[fmid-smart-proxies]]
== {SmartProxies}

* {PlanningDocURL}chap-Red_Hat_Satellite-Architecture_Guide-Introduction_to_Red_Hat_Satellite[Introduction to {Project}]
* {InstallingSmartProxyDocURL}[Installation of {SmartProxy}]
* {PlanningDocURL}chap-Documentation-Architecture_Guide-Capsule_Server_Overview[{Smart Proxy} Overview]

[[fmid-subnets]]
== Subnets

* {ProvisioningDocURL}Configuring_Networking[Configuring Networking]
* {ProvisioningDocURL}Configuring_Networking-Adding_a_Subnet_to_the_Satellite_Server[Adding a Subnet to {Project}]
* {PlanningDocURL}sect-Red_Hat_Satellite-Architecture_Guide-Single[Single Location with Segregated Subnets]
