---
config:
    theme: default
---
architecture-beta
    service user(mdi:account)[User 1]

    group user-system(mdi:laptop)[User system 1]
        group mcp-host[AI application 1] in user-system
            service mcp-client(mdi:checkbox-intermediate)[MCP client 1] in mcp-host
        service mcp-server(mdi:checkbox-intermediate)[MCP server 1] in user-system

    user:R <--> L:mcp-client{group}
    mcp-client:R <--> L:mcp-server

    service foreman-server(mdi:server)[Foreman server]
    group foreman-deployment[Foreman deployment]
        service hosts(mdi:monitor-multiple)[Hosts] in foreman-deployment

    foreman-server:R <-- L:hosts{group}

    service user-2(mdi:account)[User 2]

    group user-system-2(mdi:laptop)[User system 2]
       group mcp-host-2[AI application 2] in user-system-2
           service mcp-client-2(mdi:checkbox-intermediate)[MCP client 2] in mcp-host-2
        service mcp-server-2(mdi:checkbox-intermediate)[MCP server 2] in user-system-2

    user-2:R <--> L:mcp-client-2{group}
    mcp-client-2:R <--> L:mcp-server-2

    junction junction-top
    junction junction-bottom

    mcp-server:R <-- L:junction-top
    mcp-server-2:R <-- L:junction-bottom
    junction-top:B --> T:foreman-server
    junction-bottom:T --> B:foreman-server
