---
config:
    theme: default
---
architecture-beta
    service user(mdi:account)[User]

    group user-system(mdi:laptop)[User system]
        group mcp-host[AI application] in user-system
            service mcp-client(mdi:checkbox-intermediate)[MCP client] in mcp-host
        service mcp-server(mdi:checkbox-intermediate)[MCP server] in user-system

    user:R <--> L:mcp-client{group}
    mcp-client:R <--> L:mcp-server

    service foreman-server(mdi:server)[Foreman server]
    group foreman-deployment[Foreman deployment]
        service hosts(mdi:monitor-multiple)[Hosts] in foreman-deployment

    mcp-server:R <--> L:foreman-server
    foreman-server:R <-- L:hosts{group}
