---
config:
    theme: default
---
architecture-beta
    service user(mdi:account)[User]
    group mcp-host[AI application]
       service mcp-client(mdi:checkbox-intermediate)[MCP client] in mcp-host
    user:R <--> L:mcp-client{group}
    service mcp-server(mdi:checkbox-intermediate)[MCP server]
    mcp-client:R <--> L:mcp-server

    service foreman-server(mdi:server)[Foreman server]
    mcp-server:R <--> L:foreman-server
    group foreman-deployment[Foreman deployment]
        service hosts(mdi:monitor-multiple)[Hosts] in foreman-deployment
    foreman-server:R <-- L:hosts{group}
