---
config:
    theme: default
---
architecture-beta
    group foreman-server[Foreman Server]
        service foreman(mdi:server)[Foreman] in foreman-server
        service foreman-server-services(mdi:database)[Foreman services] in foreman-server
        group internal-proxy[Internal Smart Proxy] in foreman-server
            service foreman-proxy(mdi:cog-box)[Foreman Proxy] in internal-proxy
            service foreman-proxy-services(mdi:database)[Foreman Proxy services] in internal-proxy
        foreman:R -- L:foreman-server-services
        foreman:L --> R:foreman-proxy
        foreman-proxy:L -- R:foreman-proxy-services
    group hosts[Hosts]
        service host-1(mdi:desktop-classic)[Host 1] in hosts
        service host-2(mdi:desktop-classic)[Host 2] in hosts
        service host-3(mdi:desktop-classic)[Host 3] in hosts
        service host-4(mdi:desktop-classic)[Host 4] in hosts
        service host-5(mdi:desktop-classic)[Host 5] in hosts
        service host-6(mdi:desktop-classic)[Host 6] in hosts
        host-1:R -- L:host-2
        host-2:R -- L:host-3
        host-3:R -- L:host-4
        host-4:R -- L:host-5
        host-5:R -- L:host-6
host-5{group}:T --> B:foreman-server-services
host-4{group}:T --> B:foreman
host-3{group}:T <--> B:foreman-proxy
host-2{group}:T <--> B:foreman-proxy-services
