[[Provisioning_Cloud_Instances_in_Amazon_EC2]]
== Provisioning Cloud Instances in Amazon EC2

Amazon Elastic Compute Cloud (Amazon EC2) is a web service that provides public cloud compute resources. Using {Project}, you can interact with Amazon EC2's public API to create cloud instances and control their power management states. Use the procedures in this chapter to add a connection to an Amazon EC2 account and provision a cloud instance.

[[Provisioning_Cloud_Instances_in_Amazon_EC2-Prerequisites_for_Amazon_EC2_Provisioning]]
=== Prerequisites for Amazon EC2 Provisioning

The requirements for Amazon EC2 provisioning include:

  * A {SmartProxyServer} managing a network in your EC2 environment. Use a Virtual Private Cloud (VPC) to ensure a secure network between the hosts and the {SmartProxyServer}.
  * An Amazon Machine Image (AMI) for image-based provisioning.
include::../common/modules/snip_common-compute-resource-prereqs.adoc[]


[[Provisioning_Cloud_Instances_in_Amazon_EC2-Adding_a_Amazon_EC2_Connection_to_the_Satellite_Server]]
=== Adding an Amazon EC2 Connection to the {ProjectServer}

Use this procedure to add the Amazon EC2 connection in the {ProjectServer}'s compute resources.

.Time Settings and Amazon Web Services
Amazon Web Services uses time settings as part of the authentication process. Ensure that {ProjectServer}'s time is correctly synchronized. Ensure that an NTP service, such as `ntpd` or `chronyd`, is running properly on the {ProjectServer}. Failure to provide the correct time to Amazon Web Services can lead to authentication failures.

For more information about synchronizing time in {Project}, see link:{BaseURL}installing_satellite_server_from_a_connected_network/installing-satellite-server-connected#synchronizing_time[Synchronizing Time] in _{project-installation-guide-title}_.


.Procedure

To add an Amazon EC2 connection, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources* and in the Compute Resources window, click *Create Compute Resource*.
. In the *Name* field, enter a name to identify the Amazon EC2 compute resource.
. From the *Provider* list, select *EC2*.
. In the *Description* field, enter information that helps distinguish the resource for future use.
. Optional: From the *HTTP proxy* list, select an HTTP proxy to connect to external API services. You must add HTTP proxies to {Project} before you can select a proxy from this list. For more information, see xref:Provisioning_Cloud_Instances_in_Amazon_EC2-Using-an-HTTP-Smart-Proxy[].
. In the *Access Key* and *Secret Key* fields, enter the access keys for your Amazon EC2 account. For more information, see http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html[Managing Access Keys for your AWS Account] on the Amazon documentation website.
. Optional: Click the *Load Regions* button to populate the *Regions* list.
. From the *Region* list, select the Amazon EC2 region or data center to use.
. Click the *Locations* tab and ensure that the location you want to use is selected, or add a different location.
. Click the *Organizations* tab and ensure that the organization you want to use is selected, or add a different organization.
. Click *Submit* to save the Amazon EC2 connection.
. Select the new compute resource and then click the *SSH keys* tab, and click *Download* to save a copy of the SSH keys to use for SSH authentication. Until https://bugzilla.redhat.com/show_bug.cgi?id=1793138[BZ1793138] is resolved, you can download a copy of the SSH keys only immediately after creating the Amazon EC2 compute resource. If you require SSH keys at a later stage, follow the procedure in xref:connecting_to_an_Amazon_EC2_instance_using_SSH[].

.For CLI Users

Create the connection with the `hammer compute-resource create` command. Use `--user` and `--password` options to add the access key and secret key respectively.

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create --name "_My_EC2_" --provider "EC2" \
--description "Amazon EC2 Public Cloud` --user "_user_name_" \
--password "_secret_key_" --region "us-east-1" --locations "New York" \
--organizations "_My_Organization_"
----

[[Provisioning_Cloud_Instances_in_Amazon_EC2-Using-an-HTTP-Smart-Proxy]]
=== Using an HTTP Proxy with Compute Resources

In some cases, the EC2 compute resource that you use might require a specific HTTP proxy to communicate with {Project}. In {Project}, you can create an HTTP proxy and then assign the HTTP proxy to your EC2 compute resource.

However, if you configure an HTTP proxy for {Project} in *Administer* > *Settings*, and then add another HTTP proxy for your compute resource, the HTTP proxy that you define in *Administer* > *Settings* takes precedence.

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *HTTP Proxies*, and select *New HTTP Proxy*.
. In the *Name* field, enter a name for the HTTP proxy.
. In the *URL* field, enter the URL for the HTTP proxy, including the port number.
. Optional: Enter a username and password to authenticate to the HTTP proxy, if your HTTP proxy requires authentication.
. Click *Test Connection* to ensure that you can connect to the HTTP proxy from {Project}.
. Click the *Locations* tab and add a location.
. Click the *Organization* tab and add an organization.
. Click *Submit*.

[[Provisioning_Cloud_Instances_in_Amazon_EC2-Adding_Amazon_EC2_Images_on_the_Satellite_Server]]
=== Adding Amazon EC2 Images to {ProjectServer}

Amazon EC2 uses image-based provisioning to create hosts. You must add image details to your {ProjectServer}. This includes access details and image location.

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources* and select an Amazon EC2 connection.
. Click the *Images* tab, and then click *New Image*.
. In the *Name* field, enter a name to identify the image for future use.
. From the *Operating System* list, select the operating system that corresponds with the image you want to add.
. From the *Architecture* list, select the operating system's architecture.
. In the *Username* field, enter the SSH user name for image access. This is normally the `root` user.
. In the *Password* field, enter the SSH password for image access.
. In the *Image ID* field, enter the Amazon Machine Image (AMI) ID for the image. This is usually in the following format: `ami-xxxxxxxx`.
. Optional: Select the *User Data* check box if the images support user data input, such as `cloud-init` data. If you enable user data, the Finish scripts are automatically disabled. This also applies in reverse: if you enable the Finish scripts, this disables user data.
. Optional: In the *IAM role* field, enter the Amazon security role used for creating the image.
. Click *Submit* to save the image details.

.For CLI Users

Create the image with the `hammer compute-resource image create` command. Use the `--uuid` field to store the full path of the image location on the Amazon EC2 server.

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource image create --name "Test Amazon EC2 Image" \
--operatingsystem "RedHat 7.2" --architecture "x86_64" --username root \
--user-data true --uuid "ami-_my_ami_id_" --compute-resource "_My_EC2_"
----

[[Provisioning_Cloud_Instances_in_Amazon_EC2-Adding_Amazon_EC2_Details_to_a_Compute_Profile]]
=== Adding Amazon EC2 Details to a Compute Profile

You can add hardware settings for instances on Amazon EC2 to a compute profile.

.Procedure

To add hardware settings, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Profiles* and click the name of your profile, then click an EC2 connection.
. From the *Flavor* list, select the hardware profile on EC2 to use for the host.
. From the *Image* list, select the image to use for image-based provisioning.
. From the *Availability zone* list, select the target cluster to use within the chosen EC2 region.
. From the *Subnet* list, add the subnet for the EC2 instance. If you have a VPC for provisioning new hosts, use its subnet.
. From the *Security Groups* list, select the cloud-based access rules for ports and IP addresses to apply to the host.
. From the *Managed IP* list, select either a `Public` IP or a `Private` IP.
. Click *Submit* to save the compute profile.

.For CLI Users

The compute profile CLI commands are not yet implemented in {ProjectName}. As an alternative, you can include the same settings directly during the host creation process.

[[Provisioning_Cloud_Instances_in_Amazon_EC2-Creating_Image_Based_Hosts_on_Amazon_EC2]]
=== Creating Image-Based Hosts on Amazon EC2

The Amazon EC2 provisioning process creates hosts from existing images on the Amazon EC2 server.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *Create Host*.
. In the *Name* field, enter a name for the host.
. From the *Host Group* list, you can select a host group to populate most of the new host's fields.
. From the *Deploy on* list, select the EC2 connection.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine-based settings.
. Click the *Interface* tab, and then click *Edit* on the host's interface, and verify that the fields are populated with values. Leave the *Mac Address* field blank. The {ProjectServer} automatically selects and IP address and the *Managed*, *Primary*, and *Provision* options for the first interface on the host.
. Click the *Operating System* tab and confirm that all fields are populated with values.
. Click the *Virtual Machine* tab and confirm that all fields are populated with values.
ifeval::["{build}" == "foreman"]
. If you use the Katello plugin, click the *Parameters* tab, and ensure that a parameter exists that provides an activation key. If not, add an activation key.
endif::[]
ifeval::["{build}" == "satellite"]
. Click the *Parameters* tab, and ensure that a parameter exists that provides an activation key. If not, add an activation key.
endif::[]
. Click *Submit* to save your changes.

This new host entry triggers the Amazon EC2 server to create the instance, using the pre-existing image as a basis for the new volume.


.For CLI Users

Create the host with the `hammer host create` command and include `--provision-method image` to use image-based provisioning.

[options="nowrap" subs="+quotes"]
----
# hammer host create --name "ec2-test1" --organization "_My_Organization_" \
--location "New York" --hostgroup "Base" \
--compute-resource "_My_EC2_" --provision-method image \
--image "Test Amazon EC2 Image" --enabled true --managed true \
--interface "managed=true,primary=true,provision=true,subnet_id=EC2" \
--compute-attributes="flavor_id=m1.small,image_id=TestImage,availability_zones=us-east-1a,security_group_ids=Default,managed_ip=Public"
----

For more information about additional host creation parameters for this compute resource, enter the `hammer host create --help` command.

[[connecting_to_an_Amazon_EC2_instance_using_SSH]]
=== Connecting to an Amazon EC2 instance using SSH

You can connect remotely to an Amazon EC2 instance from {ProjectServer} using SSH. However, to connect to any Amazon Web Services EC2 instance that you provision through {ProjectName}, you must first access the private key that is associated with the compute resource in the Foreman database, and use this key for authentication.

To locate the private key and connect to an Amazon EC2 server using SSH, complete the following steps:

. To locate the compute resource list, on your {ProjectServer} base system, enter the following command, and note the ID of the compute resource that you want to use:
+
----
# hammer compute-resource list
----
+
. Switch user to the `postgres` user:
+
[options="nowrap" subs="+quotes"]
----
# su - postgres
----
+
. Initiate the `postgres` shell:
+
[options="nowrap" subs="+quotes"]
----
$ psql
----
+
. Connect to the Foreman database as the user `postgres`:
+
[options="nowrap" subs="+quotes"]
----
# postgres=# \c foreman
----
+
. Select the secret from `key_pairs` where `compute_resource_id = 3`:
+
[options="nowrap" subs="+quotes"]
----
# select secret from key_pairs where compute_resource_id = 3; secret
----
+
. Copy the key from after `-----BEGIN RSA PRIVATE KEY-----` until `-----END RSA PRIVATE KEY-----`.
. Create a `.pem` file and paste your key into the file:
+
[options="nowrap" subs="+quotes"]
----
# vim _Keyname_.pem
----
+
. Ensure that you restrict access to the `.pem` file:
+
[options="nowrap" subs="+quotes"]
----
# chmod 600 _Keyname_.pem
----
+
. To connect to the Amazon EC2 instance, enter the following command:
+
[options="nowrap" subs="+quotes"]
----
ssh -i _Keyname_.pem   ec2-user@_example.aws.com_
----


=== Configuring a Finish Template for an Amazon Web Service EC2 Environment

ifeval::["{build}" == "satellite"]
You can use {ProjectName} finish templates during the provisioning of Red{nbsp}Hat Enterprise Linux instances in an Amazon EC2 environment.
endif::[]

ifeval::["{build}" != "satellite"]
You can use {ProjectName} finish templates during the provisioning of Linux instances in an Amazon EC2 environment.
endif::[]

To configure a finish template for Amazon EC2, complete the following steps:

. In the {ProjectName} web UI, navigate to *Hosts* > *Provisioning Templates*.
. In the *Provisioning Templates* page, enter `Kickstart default finish` into the search field and click *Search*.
. On the *Kickstart default finish* template, select *Clone*.
. In the *Name* field, enter a unique name for the template.
ifeval::["{build}" == "satellite"]
. In the template, prefix each command that requires root privileges with `sudo`, except for `subscription-manager register` and `yum` commands, or add the following line to run the entire template as the sudo user:
endif::[]
ifeval::["{build}" != "satellite"]
. In the template, prefix each command that requires root privileges with `sudo`, except for `yum` or equivalent commands, or add the following line to run the entire template as the `sudo` user:
endif::[]
+
----
sudo -s << EOS
_Template_ _Body_
EOS
----
+
. Click the *Association* tab, and associate the template with a Red{nbsp}Hat Enterprise Linux operating system that you want to use.
. Click the *Locations* tab, and add the the location where the host resides.
. Click the *Organizations* tab, and add the organization that the host belongs to.
. Make any additional customizations or changes that you require, then click *Submit* to save your template.
. Navigate to *Hosts* > *Operating systems* and select the operating system that you want for your host.
. Click the *Templates* tab, and from the *Finish Template* list, select your finish template.
. Navigate to *Hosts* > *Create Host* and enter the information about the host that you want to create.
. Click the *Parameters* tab and navigate to *Host parameters*.
ifeval::["{build}" == "satellite"]
. In *Host parameters*, click the *Add Parameter* button three times to add three new parameter fields. Add the following three parameters:
endif::[]
ifeval::["{build}" != "satellite"]
. If you have the Remote Execution plugin installed, in *Host parameters*, click the *Add Parameter* button two times to add two new parameter fields. If you use the Katello plugin, add a third parameter field. Add the following parameters:
endif::[]
.. In the *Name* field, enter `remote_execution_ssh_keys`. In the corresponding *Value* field, enter the output of `cat /usr/share/foreman-proxy/.ssh/id_rsa_foreman_proxy.pub`.
.. In the *Name* field, enter `remote_execution_ssh_user`. In the corresponding *Value* field, enter `ec2-user`.
ifeval::["{build}" == "satellite"]
.. In the *Name* field, enter `activation_keys`. In the corresponding *Value* field, enter your activation key.
endif::[]
ifeval::["{build}" == "foreman"]
.. If you use the Katello plugin, in the *Name* field, enter `activation_keys`. In the corresponding *Value* field, enter your activation key.
endif::[]
. Click *Submit* to save the changes.

=== More Information about Amazon Web Services and {Project}

For information about how to locate Red{nbsp}Hat Gold Images on Amazon Web Services EC2, see https://access.redhat.com/articles/2962171[How to Locate Red{nbsp}Hat Cloud Access Gold Images on AWS EC2].

For information about how to install and use the Amazon Web Service Client on Linux, see https://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html[Install the AWS Command Line Interface on Linux] in the Amazon Web Services documentation.

For information about importing and exporting virtual machines in Amazon Web Services, see https://aws.amazon.com/ec2/vm-import/[VM Import/Export] in the Amazon Web Services documentation.
