[[Provisioning_Virtual_Machines_in_Azure]]
== Provisioning Cloud Instances in Microsoft Azure Resource Manager
{ProjectName} can interact with Microsoft Azure Resource Manager, including creating new virtual machines and controlling their power management states. Only image-based provisioning is supported for creating Azure hosts.

[[Provisioning_Virtual_Machines_in_Azure-Prerequisites_for_Azure_Provisioning]]
=== Prerequisites for Azure Provisioning

Before you begin, ensure that the following conditions are met:

* Ensure that you have the correct permissions to create an Azure Active Directory application. Fore more information, see https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#required-permissions[Check Azure AD permissions] in the _Microsoft identity platform (Azure Active Directory for developers_ documentation.
* You must create and configure an Azure Active Directory application and service principle to obtain Application (client) ID, Directory (tenant) ID, and Client Secret. For more information, see https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal[Use the portal to create an Azure AD application and service principal that can access resources] in the _Microsoft identity platform (Azure Active Directory for developers_ documentation. 
* You must have your Subscription ID.
* Optional: If you want to use Puppet with Azure hosts, navigate to *Administer* > *Settings* > *Puppet* and enable the `Use UUID for certificates` setting to configure Puppet to use consistent Puppet certificate IDs.
* Based on your needs, associate a `finish` or `user_data` provisioning template with the operating system you want to use. For more information about provisioning templates, see xref:Configuring_Provisioning_Resources-Types_of_Provisioning_Templates[].
include::Common_Compute_Resource_Prereqs.adoc[]

ifeval::["{build}" == "foreman"]
=== Installing the Foreman AzureRm Plug-in

Use this section to install the AzureRm plug-in in Foreman. Note that this plugin is version 2.0.x and does not depend on the previous foreman_azure 1.x as they refer to different Azure APIs. This AzureRm plug-in is compatible with Foreman 1.17 and later.

.Installing with Bundle (Gem)

To install the AzureRm plug-in using Bundle (Gem), complete the following steps:

. Append the following line to the `Gemfile.local.rb` file in your Foreman installation directory `/usr/share/foreman/bundler.d/Gemfile.local.rb`:
+
----
$ gem 'foreman_azure_rm'
----

. Change to the `~/usr/share/foreman/bundler.d/` directory:
+
----
cd ~/usr/share/foreman/bundler.d/
----

. Run the `bundle install` command.

.Installing with yum

To install the AzureRm plug-in using yum, enter the following command:

----
# yum install tfm-rubygem-foreman_azure_rm
----

=== Enabling the Foreman AzureRm Plug-in

After you install the AzureRm plug-in, you must enable it in Foreman.

. Enable the `azure` plug-in:
+
----
# foreman-installer --enable-foreman-plugin-azure --enable-foreman-cli-azure
----

. Reload the Apipie cache:
+
----
# hammer -r
----

. Verify that the commands 

endif::[]

[[Provisioning_Virtual_Machines_in_Azure-Adding_an_Azure_Connection]]
=== Adding an Azure Connection to {ProjectServer}

Use this procedure to add a Microsoft Azure Resource Manager compute resource to {Project} to be able to add images and provision hosts. Note that you must add a separate compute resource for a separate Azure Resource Manager region.

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources* and click *Create Compute Resource*.
. In the *Name* field, enter a name for the resource.
. From the *Provider* list, select *Azure Resource Manager*.
. Optional: In the *Description* field, enter a description for the resource.
. In the *Client ID* field, enter the Application (client) ID.
. In the *Client Secret* field, enter the client secret.
. In the *Subscription ID* field, enter the subscription ID.
. In the *Tenant ID* field, enter the Directory (tenant) ID.
. From the *Azure Region* list, select the Azure region to use. 
. Click the *Test Connection* button to verify that Satellite can connect to Azure.
. Click *Submit*.

.For CLI Users

Use the `hammer compute-resource create` command to add Azure compute resource to Satellite.

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create --name _azure_cr_name_ / <1>
--provider azurerm /                                    <2>
--tenant _tenant-id_ /                                    <3>
--app-ident _client-id_ \                                 <4> 
--secret-key _client-secret_ \                            <5>
--sub-id _subscription-id_ \                              <6> 
--region _region_                                         <7>
----
<1> With the `--name` option, enter a name for the resource.
<2> With the `--provider` option, enter `azurerm`.
<3> With the `--tenant` option, enter enter the Directory (tenant) ID.
<4> With the `--app-ident` option, enter the Application (client) ID.
<5> With the `--secret-key` option, enter the client secret.
<6> With the `--sub-id` option, enter the subscription ID.
<7> With the `--region` option, enter the Azure region to use. Note that the value for the `--region` option must be in lowercase and must not contain special characters.

[[Provisioning_Virtual_Machines_in_Azure-Adding_Azure_Images]]
=== Adding Azure Images to {ProjectServer}

Azure Resource Manager uses image-based provisioning to create hosts. You must add image details to your {ProjectServer}.

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources* and click an Azure compute resource.
. Click the *Images* tab.
. Click *Create Image*.
. In the *Name* field, enter a name for the image.
. From the *Operating system* list, select the base operating system for the image.
. From the *Architecture* list, select the operating system architecture.
. In the *User* field, enter the SSH user name for image access.
. Optional: In the *Password* field, enter a password to authenticate with. 
. In the *Marketplace Image URN* field, enter a Marketplace URN. For example, *RedHat:RHEL:7-RAW:latest*. For more information, see https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage[Find Linux VM images in the Azure Marketplace with the Azure CLI].
. Optional: Select the *User data* check box to enable user data input.
. Click *Submit* to save the image details.

.For CLI Users

To add an image, enter the following command.

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource image create --name _Azure_image_name_ \ <1>
--compute-resource _azure_cr_name_ \                               <2>
--uuid '_RedHat:RHEL:7-RAW:latest_' \                              <3>
--username '_azure_username_' \                                    <4>
--user-data _no_                                                   <5>
----
<1> With the `--name` option, enter a name for the image.
<2> With the `--compute-resource` option, enter a name of the Azure Compute resource that you want to create an image for.
<3> With the `--uuid` option, enter a Marketplace URN. For example, *RedHat:RHEL:7-RAW:latest*. For more information, see https://docs.microsoft.com/en-us/azure/virtual-machines/linux/cli-ps-findimage[Find Linux VM images in the Azure Marketplace with the Azure CLI].
<4> With the `--username` option, enter the SSH user name for image access. Note that the username that you enter for the image must be the same that you use when creating a host. The `--password` option is optional when creating an image. You cannot use the `root` user.
<5> With the `--user-data` option, define whether or not the image supports user data.


[[Provisioning_Virtual_Machines_in_Azure-Adding_Azure_Details_to_a_Compute_Profile]]
=== Adding Azure Details to a Compute Profile

You can add Azure details to a compute profile to automatically populate virtual machine-based settings on host creation. For more information about Azure Resource Manager concepts, see https://docs.microsoft.com/en-us/azure/azure-resource-manager/[Azure Resource Manager documentation].

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Profiles* and click the name of a compute profile to use.
. Select an Azure compute resource.
. From the *Resource group* list, select the resource group to provision to.
. From the *VM Size* list, select a VM size setting.
. From the *Platform* list, select *Linux*. Satellite does not support provisioning Windows VMs.
. In the *Username* field, enter a user name to authenticate with. Note that the username that you enter for compute profile must be the same that you use when creating an image.
. To authenticate the user, use one of the following options:
+
* To authenticate using a password, enter a password in the *Password* field.
+
* To authenticate using an SSH key, enter an SSH key inn the *SSH Key* field.
. Optional: If you want the VM to use a premium SSD, select the *Premium OS Disk* check box.
. From the *OS Disk Caching* list, select the disc caching setting.
. Optional: In the *Custom Script Command* field, enter commands to perform on the VM when the VM is provisioned.
. Optional: If you want to run custom scripts when provisioning finishes, in the *Comma separated file URIs* field, enter comma-separated file URIs of scripts to use. The scripts must contain `sudo` at the beginning because {ProjectName} downloads files to the `/var/lib/waagent/custom-script/download/0/` directory on the host and therefore scripts require sudo privileges to be executed.
. Click *Add Interface*.
. From the *Azure Subnet* list, select the Azure subnet to provision to.
. From the *Public IP* list, select the public IP setting.
. Optional: If you want the VM to use a static private IP, select the *Static Private IP* check box.
. Click *Submit*.

.For CLI Users

. Create a compute profile to use with the Azure Resource Manager compute resource:
+
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile create --name _compute_profile_name_
----

. Add Azure details to the compute profile: 
[options="nowrap" subs="+quotes"]
----
# hammer compute-profile values create \
--compute-profile "_compute_profile_name_" \ <1>
--compute-resource _azure_cr_name_ \         <2>
--compute-attributes="resource_group=_resource_group_,vm_size=_Standard_B1s_,username=_azure_user_,password=_azure_password_,platform=Linux,script_command=touch /var/tmp/text.txt" \ <3>
--interface="compute_public_ip=Dynamic,compute_network=mysubnetID,compute_private_ip=false" <4>
----
<1> With the `--compute-profile` option, enter the name of a compute profile to configure.
<2> With the `--compute-resource` option, enter a name of the Azure Compute resource that you want to configure a compute profile for.
<3> With the `--compute-attributes` option, specify the following details:
* With the `resource_group` setting, enter the resource group to provision to.
* With the `vm_size` setting, enter the size of the VM to provision, for example `Standard_B1s`.
* With the `username` setting, enter the SSH user name for image access. Note that the username that you enter for compute profile must be the same that you use when creating an image.
* With the `password` setting, enter the password to authenticate with.
* With the `platform` setting, enter `Linux`.
* Optional: If you want to run scripts on the VM after provisioning, specify the following settings:
** To enter the script directly, with the `script_command` setting, enter a command to be executed on the provisioned VM.
** TO run a script from a URI, with the `script_uris` setting, enter comma-separated file URIs of scripts to use. The scripts must contain `sudo` at the beginning because {ProjectName} downloads files to the `/var/lib/waagent/custom-script/download/0/` directory on the host and therefore scripts require sudo privileges to be executed. 
* Optional: If you want to use an SSH key for authentication, with the `ssh_key_data` setting, specify the SSH key.
* Optional: With the `os_disk_caching` setting, specify the OS disk caching method: `None`, `ReadOnly`, or `ReadWrite`.
* Optional: If you want the VM to use a premium SSD, set the `premium_os_disk` setting to `1`.
<4> With the `--interface` option, specify the following details:
* With the `compute_public_ip` setting, enter the public IP address type. Must be either `None`, `Static`, or `Dynamic`.
* With the `compute_network` setting, enter the ID of an available Azure Subnet to use for provisioning.
* With the `compute_private_ip` setting, specify whether to use a private IP address. Must be `true` or `false`.

[[Provisioning_Virtual_Machines_in_Azure-Creating_Image_Based_Hosts_on_Azure]]
=== Creating Image-Based Hosts on Azure

The Azure provisioning process creates hosts from existing images on Azure. 

.Static Private IP Considerations
If you want the VM to use a static private IP, you must complete the following steps:

. Ensure that you select the *Static Private IP* check box in the compute profile.
. Create a subnet in Satellite with *Network Address* matching the Azure subnet.
. While creating a host, on the *Network Interfaces* tab, select the created subnet and enter the IPv4 address within the range of your subnet.

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *Create host*.
. In the *Name* field, enter a name for the host.
. Click the *Organization* and *Location* tabs to ensure that the provisioning context is automatically set to the current context.
. Optional: From the *Host Group* list, you can select a host group to populate most of the new host's fields.
. From the *Deploy on* list, select an Azure compute resource.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine-based settings.
. Click the *Virtual Machine* tab and verify that the fields are populated with the correct values from the selected compute profile. 
. Click the *Interface* tab and click *Edit* on the host's interface.
. Verify that the fields are populated with the correct values from the selected compute profile and host group.
. Click the *Operating System* tab, and select the operating system to install.
. In the *Root Password ** field, enter the root password to authenticate with.
. Click *Resolve* in *Provisioning templates* to verify that the new host can identify the correct provisioning templates to use.
ifeval::["{build}" == "satellite"]
. Click the *Parameters* tab and ensure that a parameter exists that provides an activation key. If not, add an activation key.
endif::[]
ifeval::["{build}" == "foreman"]
. If you use the Katello plugin, click the *Parameters* tab and ensure that a parameter exists that provides an activation key. If not, add an activation key.
endif::[]
. Click *Submit*.

.For CLI Users

To create a host, enter the following command:

[options="nowrap" subs="+quotes"]
----
# hammer host create --compute-resource _azure_cr_name_ \ <1>
--compute-profile "_compute_profile_name_" \              <2>
--name="_Azure_VM_" \                                     <3> 
--organization "_Your_Organization_" \                    <4>
--location "_Your_Location_" \                            <5>
--domain _domain_name_ \                                  <6>
--architecture _x86_64_ \                                 <7>
--operatingsystem "_operating_system_name_" \             <8>
--image _Azure_image_name_                                <9>
----
<1> With the `--compute-resource` option, enter a name of an Azure Compute resource to provision to.
<2> With the `--compute-profile` option, enter a name a compute profile to use for provisioning.
<3> With the `--name` option, enter a name for the host.
<4> With the `--organization` option, enter an organization to use.
<5> With the `--location` option, enter a location to use.
<6> With the `--domain` option, enter a name of a domain to use for provisioning.
<7> With the `--architecture` option, enter a name of an architecture to use for provisioning
<8> With the `--operatingsystem` option, enter a name of an operating system to use for provisioning
<9> With the `--image` option, enter a name of an Azure Image to use for provisioning.
