[[Introduction]]
== Introduction

Provisioning is a process that starts with a bare physical or virtual machine and ends with a fully configured, ready-to-use operating system. Using {ProjectName}, you can define and automate fine-grained provisioning for a large number of hosts.

There are many provisioning methods. For example, you can use {ProjectServer}'s integrated {SmartProxy} or an external {SmartProxyServer} to provision bare metal hosts using both PXE based and non-PXE based methods. You can also provision cloud instances from specific providers through their APIs. These provisioning methods are part of the {ProjectNameX} application life cycle to create, manage, and update hosts.

[[Introduction-Defining_Provisioning_Types]]
=== Provisioning Types Overview

{ProjectNameX} has different methods for provisioning hosts:

Bare Metal Provisioning::
  {Project} provisions bare metal hosts primarily through PXE boot and MAC address identification. You can create host entries and specify the MAC address of the physical host to provision. You can also boot blank hosts to use {Project}'s discovery service, which creates a pool of ready-to-provision hosts. You can also boot and provision hosts through PXE-less methods.

Cloud Providers::
  {Project} connects to private and public cloud providers to provision instances of hosts from images that are stored with the Cloud environment. This also includes selecting which hardware profile or flavor to use.

Virtualization Infrastructure::
  {Project} connects to virtualization infrastructure services such as {OVirt} and VMware to provision virtual machines from virtual image templates or using the same PXE-based boot methods as bare metal providers.

Linux Containers::
  {Project} can create and manage containers on Red Hat Enterprise Linux Atomic Server.


[[Introduction-Defining_the_Provisioning_Workflow]]
=== Provisioning Workflow Overview

The provisioning process follows a basic workflow:

. You create a host. {Project} requests an unused IP address from the DHCP {SmartProxyServer} that is associated with the subnet. {Project} loads this IP address into the *IP address* field in the Create Host window. When you complete all the options for the new host, submit the new host request.
. The DHCP {SmartProxyServer} that is associated with the subnet reserves an entry for the host.
. {Project} configures the DNS records:
* A forward DNS record is created on the {SmartProxyServer} that is associated with the domain.
* A reverse DNS record is created on the DNS {SmartProxyServer} that is associated with the subnet.
. A PXELinux menu is created for the host in the TFTP {SmartProxyServer} that is associated with the subnet.
. The new host requests a DHCP lease from the DHCP server.
. The DHCP server responds to the lease request and returns TFTP `next-server` and `filename` options.
. The host requests the bootloader and menu from the TFTP server.
. The PXELinux menu and OS installer for the host is returned over TFTP.
. The installer requests the provisioning template or script from {Project}.
. {Project} renders the template and returns the resulting kickstart file to the host.
. The host enters a build process that installs the operating system, registers the host to {Project}, and installs management tools such as `katello-agent` and `puppet`.
. The installer notifies {Project} of a successful build in the `postinstall` script.
. The PXELinux menu reverts to a local boot template.
. The host starts its operating system. If you configured the host to use any Puppet classes, the host configures itself using the modules stored on {Project}.

This workflow differs depending on custom options. For example:

*Discovery*

If you use the Discovery service, {Project} automatically detects the MAC address of the new host and restarts the host after you submit a request. Note that TCP port 8443 must be reachable by the {SmartProxy} to which the host is attached for {Project} to restart the host.

*PXE-less Provisioning*

After you submit a new host request, you must boot the specific host with a boot disk that you download from {Project}.

*Compute Resources*

The compute resource creates the virtual machine for the host and returns the MAC address to {Project}. If you use image-based provisioning, the host does not follow the standard PXE boot and operating system installation: the compute resource creates a copy of the image for the new host to use.

*Containers*

The container provisioning process does not follow the workflow process.
