[[installing-the-discovery-service]]
= Installing the Discovery Service

Complete the following procedure to enable the Discovery service on {SmartProxyServer}.

.Procedure

. Enter the following commands on {SmartProxyServer}:
+
----
# yum install foreman-discovery-image rubygem-smart_proxy_discovery
----
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service restart
----
. In the {Project} web UI, navigate to *Infrastructure* > *{SmartProxy}*.

. Click the {SmartProxyServer} and select *Refresh* from the *Actions* list. Locate *Discovery* in the list of features to confirm the Discovery service is now running.

.Subnets

All subnets with discoverable hosts require an appropriate {SmartProxyServer} selected to provide the Discovery service.

To check this, navigate to *Infrastructure* > *{SmartProxies}* and verify if the {SmartProxyServer} that you want to use lists the Discovery feature. If not, click *Refresh features*.

In the {Project} web UI, navigate to *Infrastructure* > *Subnets*, select a subnet, click the {SmartProxies} tab, and select the *Discovery Proxy* that you want to use. Perform this for each subnet that you want to use.
