[[installing-the-discovery-service]]
= Installing the Discovery Service

Complete the following procedure to enable the Discovery service on {SmartProxyServer}.

.Procedure

. Enter the following commands on {SmartProxyServer}:
+
ifdef::satellite,orcharhino[]
[options="nowrap" subs="+quotes,attributes"]
----
# {package-install-project} foreman-discovery-image tfm-rubygem-smart_proxy_discovery
----
endif::[]
ifdef::foreman-el,katello[]
[options="nowrap" subs="+quotes,attributes"]
----
# foreman-installer \
  --enable-foreman-proxy-plugin-discovery \
  --foreman-proxy-plugin-discovery-install-images=true \
  --foreman-proxy-plugin-discovery-source-url=http://downloads.theforeman.org/discovery/releases/3.5/
----
endif::[]
+
. Restart the {foreman-maintain} services:
+
[options="nowrap" subs="+quotes,attributes"]
----
# {foreman-maintain} service restart
----
+
ifdef::orcharhino[]
Refer to the xref:sources/usage_guides/host_discovery_guide.adoc#host_discovery_guide_installation[host discovery guide] on how to install the host discovery plugin.
endif::[]
. In the {Project} web UI, navigate to *Infrastructure* > *{SmartProxy}*.

. Click {SmartProxyServer} and select *Refresh* from the *Actions* list.
Locate *Discovery* in the list of features to confirm the Discovery service is now running.

.Subnets

All subnets with discoverable hosts require an appropriate {SmartProxyServer} selected to provide the Discovery service.

To check this, navigate to *Infrastructure* > *{SmartProxies}* and verify if {SmartProxyServer} that you want to use lists the Discovery feature.
If not, click *Refresh features*.

In the {Project} web UI, navigate to *Infrastructure* > *Subnets*, select a subnet, click the {SmartProxies} tab, and select the *Discovery Proxy* that you want to use.
Perform this for each subnet that you want to use.
