[[using-an-image-builder-image-for-provisioning]]
== Using a {LoraxCompose} Image for Provisioning

In {Project}, you can integrate with {Cockpit} to perform actions and monitor your hosts.
Using {Cockpit}, you can access {LoraxCompose} and build images that you can then upload to a HTTP server and use this image to provision hosts.
When you configure {Project} for image provisioning, Anaconda installer partitions disks, downloads and mounts the image and copies files over to a host.
The preferred image type is TAR.

ifdef::foreman-el,katello[]
For more information about integrating {Cockpit} with {Project}, see https://theforeman.org/plugins/foreman_remote_execution/1.7/index.html#3.6Cockpitintegration[Cockpit integration].
endif::[]

ifdef::satellite[]
For more information about integrating {Cockpit} with {Project}, see {ManagingHostsDocURL}host_management_and_monitoring_using_red_hat_web_console[Host Management and Monitoring Using Red{nbsp}Hat web console] in the _Managing Hosts_ guide.
endif::[]

ifdef::orcharhino[]
Refer to the xref:sources/usage_guides/web_console_guide.adoc[web console guide] for more information.
endif::[]

.Prerequisites

. An existing TAR image created via {LoraxCompose}.

.Procedure

To use the {LoraxCompose} image with Anaconda Kickstart in {Project}, complete the following steps:

ifdef::satellite[]
. On {Project}, create a custom product, add a custom file repository to this product, and upload the image to the repository.
For more information, see {ContentManagementDocURL}importing_individual_iso_images_and_files[Importing Individual ISO Images and Files] in the _Content Management Guide_.
endif::[]
ifdef::orcharhino[]
. On {Project}, create a custom product, add a custom file repository to this product, and upload the image to the repository.
endif::[]
ifdef::foreman-el,katello[]
. If you use the Katello plug-in, on {Project}, create a custom product, add a custom file repository to this product, and upload the image to the repository.
For more information, see {ContentManagementDocURL}importing_individual_iso_images_and_files[Importing Individual ISO Images and Files] in the _Content Management Guide_.
endif::[]
ifdef::foreman[]
. Copy the TAR image to an existing HTTP server which installed hosts can reach.
endif::[]

. In the {Project} web UI, navigate to *Configure* > *Host Groups*, and select the host group that you want to use.
. Click the *Parameters* tab, and then click *Add Parameter*.
. In the *Name* field, enter `kickstart_liveimg`.
. From the *Type* list, select *string*.
. In the *Value* field, enter the absolute path or a relative path in the following format `custom/_product_/_repository_/_image_name_` that points to the exact location where you store the image.
. Click *Submit* to save your changes.

You can use this image for bare metal provisioning and provisioning using a compute resource.
For more information about bare metal provisioning, see xref:Using_PXE_to_Provision_Hosts[].
For more information about provisioning with different compute resources, see the relevant chapter for the compute resource that you want to use.
