[[Provisioning_Virtual_Machines_in_KVM]]
== Provisioning Virtual Machines on a KVM Server (libvirt)

Kernel-based Virtual Machines (KVMs) use an open source virtualization daemon and API called `libvirt` running on Red Hat Enterprise Linux. {ProjectNameX} can connect to the `libvirt` API on a KVM server, provision hosts on the hypervisor, and control certain virtualization functions.

[[Provisioning_Virtual_Machines_in_KVM-Prerequisites_for_KVM_Provisioning]]
=== Prerequisites for KVM Provisioning

The requirements for KVM provisioning include:

  * Synchronized content repositories for the version of Red Hat Enterprise Linux that you want to use. For more information, see link:/html/content_management_guide/importing_red_hat_content#Importing_Red_Hat_Content-Synchronizing_Red_Hat_Repositories[Synchronizing Red Hat Repositories] in the _Content Management Guide_.
  * A {SmartProxyServer} managing a network on the KVM server. Ensure no other DHCP services run on this network to avoid conflicts with the {SmartProxyServer}. For more information about network service configuration for {SmartProxyServer}s, see xref:Configuring_Networking[].
  * An activation key for host registration. For more information, see link:/html/content_management_guide/managing_activation_keys#Managing_Activation_Keys-Creating_an_Activation_Key[Creating An Activation Key] in the _Content Management_ guide.
  * A Red Hat Enterprise Linux server running KVM virtualization tools. For more information, see the https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Virtualization_Getting_Started_Guide/index.html[Red Hat Enterprise Linux 7 Virtualization Getting Started Guide].
  * An existing virtual machine image if you want to use image-based provisioning. Ensure that this image exists in a storage pool on the KVM host. The `default` storage pool is usually located in `/var/lib/libvirt/images`.

.User Roles and Permissions to Provision Libvirt Compute Resources

To provision a Libvirt host in {Project}, you must have a user account with the following roles:

* `Edit hosts`
* `View hosts`

For more information, see link:/html/administering_red_hat_satellite/chap-red_hat_satellite-administering_red_hat_satellite-users_and_roles#sect-Red_Hat_{Project}-Administering_Red_Hat_{Project}-Creating_and_Managing_Users-Assigning_Roles_to_a_User[Assigning Roles to a User] in the _Administering {ProjectName}_ guide.

You must also create a custom role with the following permissions:

* `view_compute_resources`
* `destroy_compute_resources_vms`
* `power_compute_resources_vms`
* `create_compute_resources_vms`
* `view_compute_resources_vms`
* `view_locations`
* `view_subnets`

For more information about creating roles, see link:/html/administering_red_hat_satellite/chap-Red_Hat_{Project}-Administering_Red_Hat_{Project}-Users_and_Roles#sect-Red_Hat_{Project}-Administering_Red_Hat_{Project}-Creating_and_Managing_Roles-Creating_a_Role[Creating a Role]. For more information about adding permissions to a role, see link:/html/administering_red_hat_satellite/chap-Red_Hat_{Project}-Administering_Red_Hat_{Project}-Users_and_Roles#sect-Red_Hat_{Project}-Administering_Red_Hat_{Project}-Creating_and_Managing_Roles-Adding_Permissions_to_a_Role[Adding Permissions to a Role] in the _Administering {ProjectName}_ guide.


[[Povisioning_Virtual_Machines_in_KVM-Configuring_the_Satellite_Server_for_KVM_Connections]]
=== Configuring {ProjectServer} for KVM Connections

Before adding the KVM connection, {ProjectServer} requires some configuration to ensure a secure connection. This means creating an SSH key pair for the user that performs the connection, which is the `foreman` user.

.Non-root users

These examples use the root user for KVM. However, if you want to use a non-root user on the KVM server, add the user to the `libvirt` group:
[options="nowrap" subs="+quotes"]
----
useradd -a -G libvirt _non_root_user_
----

.Procedure

To configure {ProjectServer} for KVM connections, complete the following steps:

. On {ProjectServer}, switch to the `foreman` user:
+
----
# su foreman -s /bin/bash
----

. Generate the key pair:
+
----
$ ssh-keygen
----

. Copy the public key to the KVM server:
+
[options="nowrap" subs="+quotes"]
----
$ ssh-copy-id _root@kvm.example.com_
----

. Exit the bash shell for the `foreman` user:
+
----
$ exit
----

. Install the `libvirt-client` package:
+
----
# yum install libvirt-client
----
+
. Use the following command to test the connection to the KVM server:
+
[options="nowrap"]
----
# su foreman -s /bin/bash -c 'virsh -c qemu+ssh://root@kvm.example.com/system list'
----
+
When you add the KVM connection in {ProjectServer}, use the `qemu+ssh` protocol and the address to the server. For example:
+
[options="nowrap" subs="+quotes"]
----
qemu+ssh://root@_kvm.example.com_/system
----

[[Provisioning_Virtual_Machines_in_KVM-Adding_a_KVM_Connection_to_the_Satellite_Server]]
=== Adding a KVM Connection to {ProjectServer}

Use this procedure to add a KVM connection to {ProjectServer}'s compute resources.

.Procedure

To add a KVM connection to {Project}, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*, and in the Compute Resources window, click *Create Compute Resource*.
. In the *Name* field, enter a name for the new compute resource.
. From the *Provider* list, select *Libvirt*
. In the *Description* field, enter a description for the compute resource.
. In the *URL* field, enter the connection URL to the KVM server. For example:
+
[options="nowrap" subs="+quotes"]
----
 qemu+ssh://_root@kvm.example.com_/system
----
. From the *Display type* list, select either *VNC* or *Spice*.
. Optional: To secure console access for new hosts with a randomly generated password, select the *Set a randomly generated password on the display connection* check box. You can retrieve the password for the VNC console to access guest virtual machine console from the `libvirtd` host from the output of the following command:
+
[options="nowrap" subs="+quotes"]
----
# virsh edit _your_VM_name_
<graphics type='vnc' port='-1' autoport='yes' listen='0.0.0.0' passwd='_your_randomly_generated_password_'>
----
+
The password is randomly generated every time the console for the virtual machine is opened, for example, with virt-manager.
+
. Click *Test Connection* to ensure that {ProjectServer} connects to the KVM server without fault.
. Verify that the *Locations* and *Organizations* tabs are automatically set to your current context. If you want, add additional contexts to these tabs.
. Click *Submit* to save the KVM connection.

.For CLI Users

Create the connection with the `hammer compute-resource create` command:

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create --name "_My_KVM_Server_" \
--provider "Libvirt" --description "KVM server at _kvm.example.com_" \
--url "qemu+ssh://root@_kvm.example.com/system_" --locations "New York" \
--organizations "_My_Organization_"
----


[[Provisioning_Virtual_Machines_in_KVM-Adding_KVM_Images_to_Satellite_Server]]
=== Adding KVM Images to {ProjectServer}

If you want to use image-based provisioning to create hosts, you must add information about the image to your {ProjectServer}. This includes access details and the image location.

.Procedure

To add KVM images on {ProjectServer}, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*, and in the Compute Resources window, click the name of your KVM connection.
. Click the *Image* tab, and then click *Create Image*.
. In the *Name* field, enter a name for the image.
. From the *Operatingsystem* list, select the image's base operating system.
. From the *Architecture* list, select the operating system architecture.
. In the *Username* field, enter the SSH user name for image access. This is normally the `root` user.
. In the *Password* field, enter the SSH password for image access.
. From the *User data* list, select if you want images to support user data input, such as `cloud-init` data.
. In the *Image path* field, enter the full path that points to the image on the KVM server. For example:
+
[options="nowrap" subs="+quotes"]
----
 /var/lib/KVM/images/TestImage.qcow2
----
+
. Click *Submit* to save the image details.

.For CLI Users

Create the image with the `hammer compute-resource image create` command. Use the `--uuid` field to store the full path of the image location on the KVM server.

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource image create --name "Test KVM Image" \
--operatingsystem "RedHat _version_" --architecture "x86_64" --username root \
--user-data false --uuid "/var/lib/libvirt/images/TestImage.qcow2" \
--compute-resource "_My_KVM_Server_"
----

[[Provisioning_Virtual_Machines_in_KVM-Adding_KVM_Details_to_a_Compute_Profile]]
=== Adding KVM Details to a Compute Profile

We can predefine certain hardware settings for KVM-based virtual machines by adding these hardware settings to a compute profile.

.Procedure

To add Red Hat Virtualization details to a compute profile, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Profiles*.
. In the Compute Profiles window, click the name of an existing compute resource or click *Create Compute Profile* and select a compute resource to use to create a compute profile.
. In the *CPUs* field, enter the number of CPUs to allocate to the new host.
. In the *Memory* field, enter the amount of memory to allocate to the new host.
. From the *Image* list, select the image to use if performing image-based provisioning.
. From the *Network Interfaces* list, select the network parameters for the host's network interface. You can create multiple network interfaces. However, at least one interface must point to a {SmartProxy}-managed network.
. In the *Storage* area, enter the storage parameters for the host. You can create multiple volumes for the host.
. Click *Submit* to save the settings to the compute profile.

.For CLI Users

The compute profile CLI commands are not yet implemented in {ProjectName} {ProductVersion}. As an alternative, you can include the same settings directly during the host creation process.

[[Provisioning_Virtual_Machines_in_KVM-Creating_Hosts_on_a_KVM_Server]]
=== Creating Hosts on a KVM Server

In {Project}, you can use KVM provisioning to create hosts over a network connection and from an existing image.

If you create a host with an existing image, the new host entry triggers the KVM server to create the virtual machine, using the pre-existing image as a basis for the new volume.

If you want to create a host over a network connection, the new host must have access either to {ProjectServer}'s integrated {SmartProxy} or an external {SmartProxyServer} on a KVM virtual network, so that the host has access to PXE provisioning services. This new host entry triggers the KVM server to create and start a virtual machine. If the virtual machine detects the defined {SmartProxyServer} through the virtual network, the virtual machine boots to PXE and begins to install the chosen operating system.

.DHCP Conflicts
For network-based provisioning, if you use a virtual network on the KVM server for provisioning, select a network that does not provide DHCP assignments. This causes DHCP conflicts with {ProjectServer} when booting new hosts.

.Procedure

To create a KVM host, complete the following steps:

. In the {Project} web UI, navigate to *Hosts* > *Create Host*.
. In the *Name* field, enter the name that you want to become the provisioned system's host name.
. Click the *Organization* and *Location* tabs to ensure that the provisioning context is automatically set to the current context.
. From the *Host Group* list, select the host group that you want to use to populate the form.
. From the *Deploy on* list, select the KVM connection.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine-based settings.
. Click the *Interface* tab and click *Edit* on the host's interface.
. Verify that the fields are automatically populated with values. Note in particular:
+
  * The *Name* from the *Host* tab becomes the *DNS name*.
  * {ProjectServer} automatically assigns an IP address for the new host.
+
. Ensure that the *MAC address* field is blank. The KVM server assigns one to the host.
. Verify that the *Managed*, *Primary*, and *Provision* options are automatically selected for the first interface on the host. If not, select them.
. In the interface window, review the KVM-specific fields that are populated with settings from your compute profile. Modify these settings to suit your needs.
. Click the *Operating System* tab, and confirm that all fields automatically contain values.
. For network-based provisioning, ensure that the *Provisioning Method* is set to `Network Based`. For image-based provisioning, ensure that the *Provisioning Method* is set to `Image Based`
. Click *Resolve* in *Provisioning templates* to check the new host can identify the right provisioning templates to use.
. Click the *Virtual Machine* tab and confirm that these settings are populated with details from the host group and compute profile. Modify these settings to suit your needs.
. Click the *Parameters* tab and ensure that a parameter exists that provides an activation key. If not, add an activation key.
. Click *Submit* to save the host entry.

.For CLI Users

Create the host with the `hammer host create` command and include `--provision-method build` to use network-based provisioning.

[options="nowrap" subs="+quotes"]
----
# hammer host create --name "kvm-test1" --organization "_My_Organization_" \
--location "New York" --hostgroup "Base" \
--compute-resource "_My_KVM_Server_" --provision-method build \
--build true --enabled true --managed true \
--interface "managed=true,primary=true,provision=true,compute_type=network,compute_network=_examplenetwork_" \
--compute-attributes="cpus=1,memory=1073741824" \
--volume="pool_name=default,capacity=20G,format_type=qcow2" \
--root-password "_password_"
----

Create the host with the `hammer host create` command and include `--provision-method image` to use image-based provisioning.

[options="nowrap" subs="+quotes"]
----
# hammer host create --name "kvm-test2" --organization "_My_Organization_" \
--location "New York" --hostgroup "Base" \
--compute-resource "_My_KVM_Server_" --provision-method image \
--image "Test KVM Image" --enabled true --managed true \
--interface "managed=true,primary=true,provision=true,compute_type=network,compute_network=examplenetwork" \
--compute-attributes="cpus=1,memory=1073741824" \
--volume="pool_name=default,capacity=20G,format_type=qcow2"
----



For more information about additional host creation parameters for this compute resource, see xref:CLI_Params[].
