[[Provisioning_Virtual_Machines_in_Red_Hat_Virtualization]]
== Provisioning Virtual Machines in {OVirt}

ifeval::["{build}" == "satellite"]
Red Hat Virtualization (version 4.0 and later) or Red Hat Enterprise Virtualization (version 3.6 and earlier) is an enterprise-grade server and desktop virtualization platform built on Red Hat Enterprise Linux.
endif::[]
ifeval::["{build}" == "foreman"]
{OVirt} is an enterprise-grade server and desktop virtualization platform built on Red Hat compatible system.
endif::[]

With {ProjectNameX}, you can manage virtualization functions through {OVirt}'s REST API version 3. REST API version 4 is not yet supported by {ProjectX}. This includes creating virtual machines and controlling their power states.

Use the following procedures to add a connection to a {OVirt} environment and provision a virtual machine.

[[Provisioning_Virtual_Machines_in_Red_Hat_Enterprise_Virtualization-Prerequisites_for_Red_Hat_Virtualization_Provisioning]]
=== Prerequisites for {OVirt} Provisioning

The requirements for {OVirt} provisioning include:

  * A {SmartProxyServer} managing a logical network on the {OVirt} environment. Ensure no other DHCP services run on this network to avoid conflicts with the {SmartProxyServer}. For more information, see xref:Configuring_Networking[].
  * An existing template, other than the `blank` template, if you want to use image-based provisioning. For more information about creating templates for virtual machines, see https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.0/html/virtual_machine_management_guide/chap-templates[Templates] in the _Virtual Machine Management Guide_.
include::Common_Compute_Resource_Prereqs.adoc[]


[[Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Creating_a_Red_Hat_Virtualization_User]]
=== Creating a {OVirt} User

The {OVirt} server requires an administration-like user for {ProjectServer} communication. For security reasons, {Team} advises against using the `admin@internal` user for such communication. Instead, create a new {OVirt} user with the following permissions:

  - System
    * Configure System
      ** Login Permissions
  - Network
    * Configure vNIC Profile
      ** Create
      ** Edit Properties
      ** Delete
      ** Assign vNIC Profile to VM
      ** Assign vNIC Profile to Template
  - Template
    * Provisioning Operations
      ** Import/Export
  - VM
    * Provisioning Operations
      ** Create
      ** Delete
      ** Import/Export
      ** Edit Storage
  - Disk
    * Provisioning Operations
      ** Create
    * Disk Profile
      ** Attach Disk Profile

ifeval::["{build}" == "satellite"]
For more information about how to create a user and add permissions in {OVirt}, see https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.1/html/administration_guide/sect-red_hat_enterprise_virtualization_manager_user_tasks[Administering User Tasks From the Administration Portal] in the _Red Hat Virtualization Administration Guide_.
endif::[]
ifeval::["{build}" != "satellite"]
For more information about how to create a user and add permissions in {OVirt}, see https://www.ovirt.org/documentation/admin-guide/chap-Users_and_Roles.html[Users and Roles] in the {OVirt} documentation.
endif::[]

[[Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Adding_a_Red_Hat_Virtualization_Connection_to_the_Satellite_Server]]
=== Adding a {OVirt} Connection to {ProjectServer}

Use this procedure to add a {OVirt} connection to {ProjectServer}'s compute resources.

.Procedure

To add a {OVirt} connection to {Project}, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*, and in the Compute Resources window, click *Create Compute Resource*.
. In the *Name* field, enter a name for the new compute resource.
. From the *Provider* list, select *{OVirtShort}*.
. In the *Description* field, enter a description for the compute resource.
. In the *URL* field, enter the connection URL for the {OVirt} Manager's API.
+
For example, in {OVirtLegacyShort} 3.6 and earlier, the URL is
of the following form: `https://{ovirt-example-com}/ovirt-engine/api`. In {OVirtShort} 4.0 and
later, the URL is of the following form: `https://{ovirt-example-com}/ovirt-engine/api/v3`.
+
. Optionally, select the *Use APIv4 (experimental)* check box to evaluate the new engine API.
+
ifeval::["{build}" == "satellite"]
[WARNING]
The items listed in this step are provided as Technology Previews. For further information about the scope of Technology Preview status, and associated support implications, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
endif::[]
+
. In the *User* field, enter the name of a user with permissions to access {OVirt} Manager's resources.
. In the *Password* field, enter the password of the user.
. Click *Load Datacenters* to populate the *Datacenter* list with data centers from your {OVirt} environment.
. From the *Datacenter* list, select a data center.
. From the *Quota ID* list, select a quota to limit resources available to {Project}.
. In the *X509 Certification Authorities* field, enter the certificate authority for SSL/TLS access. Alternatively, if you leave the field blank, a self-signed certificate is generated on the first API request by the server.
. Click the *Locations* tab and select the location you want to use.
. Click the *Organizations* tab and select the organization you want to use.
. Click *Submit* to save the compute resource.

.For CLI Users

To create a {OVirt} connection, enter the `hammer compute-resource create` command with `Ovirt` for `--provider` and the name of the data center you want to use for `--datacenter`.

[options="nowrap" subs="+quotes,attributes"]
----
# hammer compute-resource create \
--name "__My_{OVirtShort}__" --provider "Ovirt" \
--description "{OVirtShort} server at _{ovirt-example-com}_" \
--url "_https://{ovirt-example-com}/ovirt-engine/api_" \
--use-v4 "false" --user "_Satellite_User_" \
--password "_My_Password_" \
--locations "New York" --organizations "_My_Organization_" \
--datacenter "_My_Datacenter_"
----

Optionally, to evaluate the new engine API, change `false` to `true` for the `--use-v4` option.

ifeval::["{build}" == "satellite"]
[WARNING]
====
The items listed in this step are provided as Technology Previews. For further information about the scope of Technology Preview status, and associated support implications, see https://access.redhat.com/support/offerings/techpreview/[Technology Preview Features Support Scope].
====
endif::[]

[[Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Adding_Red_Hat_Virtualization_Images_on_the_Satellite_Server]]
=== Adding {OVirt} Images to {ProjectServer}

{OVirt} uses templates as images for creating virtual machines. If you use image-based provisioning to create hosts, you must add {OVirt} template details to your {ProjectServer}. This includes access details and the template name.

.Procedure

To add {OVirt} images on {ProjectServer}, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*, and in the Compute Resources window, click the name of your {OVirt} connection.
. Click the *Image* tab, and then click *New Image*.
. In the *Name* field, enter a name for the image.
. From the *Operatingsystem* list, select the image's base operating system.
. From the *Architecture* list, select the operating system architecture.
. In the *Username* field, enter the SSH user name for image access. This is normally the `root` user.
. In the *Password* field, enter the SSH password for image access.
. From the *Image* list, select the name of the image on {OVirt}.
. Click *Submit* to save the image details.

.For CLI Users

Create the image with the `hammer compute-resource image create` command. Use the `--uuid` option to store the template UUID on the {OVirt} server.

[options="nowrap" subs="+quotes,attributes"]
----
# hammer compute-resource image create --name "__Test_{OVirtShort}_Image__" \
--operatingsystem "RedHat 7.2" --architecture "x86_64" --username root \
--uuid "9788910c-4030-4ae0-bad7-603375dd72b1" \
--compute-resource "__My_{OVirtShort}__"
----

[[Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Adding_Red_Hat_Virtualization_Details_to_a_Compute_Profile]]
=== Adding {OVirt} Details to a Compute Profile

You can predefine certain hardware settings for virtual machines on {OVirt}. You achieve this through adding these hardware settings to a compute profile.

.Procedure

To add {OVirt} details to a compute profile, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Profiles* and in the Compute Profiles window, click the name of the {OVirt} connection.
. From the *Cluster* list, select the target host cluster in the {OVirt} environment.
. From the *Template* list, select the {OVirtShort} template to use for the *Cores* and *Memory* settings.
. In the *Cores* field, enter the number of CPU cores to allocate to the new host.
. In the *Memory* field, enter the amount of memory to allocate to the new host.
. From the *Image* list, select image to use for image-based provisioning.
. In the *Network Interfaces* area, enter the network parameters for the host's network interface. You can create multiple network interfaces. However, at least one interface must point to a {SmartProxy}-managed network. For each network interface, enter the following details:
.. In the *Name* field, enter the name of the network interface.
.. From the *Network* list, select The logical network that you want to use.
. In the *Storage* area, enter the storage parameters for the host. You can create multiple volumes for the host. For each volume, enter the following details:
.. In the *Size (GB)* enter the size, in GB, for the new volume.
.. From the *Storage domain* list, select the storage domain for the volume.
.. From the *Preallocate disk*, select either thin provisioning or preallocation of the full disk.
.. From the *Bootable* list, select whether you want a bootable or non bootable volume.
. Click *Submit* to save the compute profile.

.For CLI Users

. To create a compute profile, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer compute-profile create --name "{OVirt} CP"
----
+
. To set the values for the compute profile, enter the following command:
+
[options="nowrap" subs="+quotes,attributes"]
----
# hammer compute-profile values create --compute-profile "{OVirt} CP" \
--compute-resource "__My_{OVirtShort}__" \
--interface "compute_interface=_Interface_Type_,compute_name=eth0,compute_network=satnetwork" \
--volume "size_gb=20G,storage_domain=Data,bootable=true" \
--compute-attributes "cluster=Default,cores=1,memory=1073741824,start=true""
----

[[Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Provisioning-Using-the-Cloud-init-Template]]
=== Provisioning Using the Cloud-init Template

With the {oVirt} compute resource, you can use `cloud-init` to configure the virtual machines that you provision. Using `cloud-init` avoids any special configuration on the network, such as a managed DHCP and TFTP, to finish the installation of the virtual machine. This method does not require {Project} to connect to the provisioned virtual machine using SSH to run the finish script.

.Prerequisites

You must prepare an image with `cloud-init` installed in {oVirt}, and then import the image to {Project} to use for provisioning.

. In {oVirt}, create a virtual machine to use for image-based provisioning in {Project}.
. On the virtual machine, install `cloud-init`:
+
[options="nowrap" subs="+quotes,attributes"]
----
{package-install} cloud-init
----
+
. To the `/etc/cloud/cloud.cfg` file, add the following information:
+
----
datasource_list: ["NoCloud", "ConfigDrive"]
----
+
. In {oVirt}, create an image from this virtual machine.
. Use the following procedure to add the image in {Project}: xref:Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Adding_Red_Hat_Virtualization_Images_on_the_Satellite_Server[]. Ensure that you select the *User Data* check box.
ifeval::["{build}" == "foreman"]
+
. You must enable the remote execution plug-in to use the 'cloud-init' template.
endif::[]

.Procedure

. In the {Project} web UI, navigate to *Hosts* > *Provisioning Templates*, and click *Create Template*.
. In the *Name* field, enter a name for the template.
. In the *Editor* field, enter the following template details:
+
----
<%#
kind: user_data
name: My {Project} {oVirt} Cloud-init
-%>
#cloud-config
hostname: <%= @host.shortname %>

<%# Allow user to specify additional SSH key as host paramter -%>
<% if @host.params['sshkey'].present? || @host.params['remote_execution_ssh_keys'].present? -%>
ssh_authorized_keys:
<% if @host.params['sshkey'].present? -%>
  - <%= @host.params['sshkey'] %>
<% end -%>
<% if @host.params['remote_execution_ssh_keys'].present? -%>
<% @host.params['remote_execution_ssh_keys'].each do |key| -%>
  - <%= key %>
<% end -%>
<% end -%>
<% end -%>
runcmd:
  - |
    #!/bin/bash
<%= indent 4 do
    snippet 'subscription_manager_registration'
end %>
<% if @host.info['parameters']['realm'] && @host.realm && @host.realm.realm_type == 'Red Hat Identity Management' -%>
  <%= indent 4 do
    snippet 'idm_register'
  end %>
<% end -%>
<% unless @host.operatingsystem.atomic? -%>
    # update all the base packages from the updates repository
    yum -t -y -e 0 update
<% end -%>
<%
    # safemode renderer does not support unary negation
    non_atomic = @host.operatingsystem.atomic? ? false : true
    pm_set = @host.puppetmaster.empty? ? false : true
    puppet_enabled = non_atomic && (pm_set || @host.params['force-puppet'])
%>
<% if puppet_enabled %>
    yum install -y puppet
    cat > /etc/puppet/puppet.conf << EOF
  <%= indent 4 do
    snippet 'puppet.conf'
  end %>
    EOF
    # Setup puppet to run on system reboot
    /sbin/chkconfig --level 345 puppet on

    /usr/bin/puppet agent --config /etc/puppet/puppet.conf --onetime --tags no_such_tag <%= @host.puppetmaster.blank? ? '' : "--server #{@host.puppetmaster}" %> --no-daemonize
    /sbin/service puppet start
<% end -%>
phone_home:
 url: <%= foreman_url('built') %>
 post: []
 tries: 10pp
----
+
. Click the *Type* tab and from the *Type* list, select *User data template*.
. Click the *Association* tab, and from the *Applicable Operating Systems* list, select the operating system that you want associate with the template.
. Click the *Locations* tab, and from the *Locations* list, select the location that you want to associate with the template.
. Click the *Organizations* tab, and from the *Organization* list, select the organization that you want to associate with the template.
. Click *Submit*.
. Navigate to *Hosts* > *Operating Systems*, and select the operating system you want to associate with the template.
. Click the *Templates* tab, and from the *User data template* list, select the name of the new template.
. Click *Submit*.

You can use the xref:Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Creating_Hosts_on_a_Red_Hat_Virtualization_Server[] procedure to provision hosts using the 'cloud-init` image and template.

[[Provisioning_Virtual_Machines_in_Red_Hat_Virtualization-Creating_Hosts_on_a_Red_Hat_Virtualization_Server]]
=== Creating Hosts on a {OVirt} Server

In {Project}, you can create {OVirt} hosts over a network connection or from an existing image.

To create a host over a network, the new host must have access to either {ProjectServer}'s integrated {SmartProxy} or an external {SmartProxyServer} on a {OVirt} virtual network, so that the host has access to PXE provisioning services. The new host entry triggers the {OVirt} server to create the virtual machine. If the virtual machine detects the defined {SmartProxyServer} through the virtual network, the virtual machine boots to PXE and begins to install the chosen operating system.

.DHCP conflicts
If you use a virtual network on the {OVirt} server for provisioning, ensure to select one that does not provide DHCP assignments. This causes DHCP conflicts with {ProjectServer} when booting new hosts.

When you create a host with an existing image, the new host entry triggers the {OVirt} server to create the virtual machine, using the pre-existing image as a basis for the new volume.

.Procedure

To create a host for {OVirt} Server, complete the following steps:

. In the {Project} web UI, navigate to *Hosts* > *New Host*.
. In the *Name* field, enter the name that you want to become the provisioned system's host name.
. Click the *Organization* and *Location* tabs to ensure that the provisioning context is automatically set to the current context.
. From the *Host Group* list, select the host group that you want to use to populate the form.
. From the *Deploy on* list, select the {OVirt} connection.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine-based settings.
. Click the *Interface* tab and click *Edit* on the host's interface.
. Verify that the fields are automatically populated with values. Note in particular:
+
  * The *Name* from the *Host* tab becomes the *DNS name*.
  * {ProjectServer} automatically assigns an IP address for the new host.
+
. Ensure that the *MAC address* field is blank. The {OVirt} server assigns one to the host.
. Verify that the *Managed*, *Primary*, and *Provision* options are automatically selected for the first interface on the host. If not, select them.
. In the interface window, ensure that the {OVirt}-specific fields are populated with settings from the compute profile. Modify these settings to suit your needs.
. Click the *Operating System* tab, and confirm that all fields automatically contain values.
. For network-based provisioning, ensure that the *Provisioning Method* is set to `Network Based`. For image-based provisioning, ensure that the *Provisioning Method* is set to `Image Based`.
. Click *Resolve* in *Provisioning templates* to check the new host can identify the right provisioning templates to use.
. Click the *Virtual Machine* tab and confirm that these settings are populated with details from the host group and compute profile. Modify these settings to suit your needs.
ifeval::["{build}" == "foreman"]
. If you use the Katello plugin, click the *Parameters* tab, and ensure that a parameter exists that provides an activation key. If not, add an activation key.
endif::[]
ifeval::["{build}" == "satellite"]
. Click the *Parameters* tab, and ensure that a parameter exists that provides an activation key. If not, add an activation key.
endif::[]
. Click *Submit* to save the host entry.

.For CLI Users

To create a host with network-based provisioning, use the `hammer host create` command and include `--provision-method build`.

[options="nowrap" subs="+quotes,attributes"]
----
# hammer host create --name "{OVirtShort}-test1" --organization "_My_Organization_" \
--location "New York" --hostgroup "Base" \
--compute-resource "__My_{OVirtShort}__" --provision-method build \
--build true --enabled true --managed true \
--interface "managed=true,primary=true,provision=true,compute_name=eth0,compute_network=satnetwork" \
--compute-attributes="cluster=Default,cores=1,memory=1073741824,start=true" \
--volume="size_gb=20G,storage_domain=Data,bootable=true"
----

To create a host with image-based provisioning, use the `hammer host create` command and include `--provision-method image`.

[options="nowrap" subs="+quotes,attributes"]
----
# hammer host create --name "{OVirtShort}-test2" --organization "_My_Organization_" \
--location "New York" --hostgroup "Base" \
--compute-resource "__My_{OVirtShort}__" --provision-method image \
--image "_Test_RHV_Image_" --enabled true --managed true \
--interface "managed=true,primary=true,provision=true,compute_name=eth0,compute_network=satnetwork" \
--compute-attributes="cluster=Default,cores=1,memory=1073741824,start=true" \
--volume="size_gb=20G,storage_domain=Data,bootable=true"
----

For more information about additional host creation parameters for this compute resource, see xref:CLI_Params[].




