[[Provisioning_Virtual_Machines_in_VMware_vSphere]]
== Provisioning Virtual Machines in VMware vSphere

VMware vSphere is an enterprise-level virtualization platform from VMware. {ProjectNameX} can interact with the vSphere platform, including creating new virtual machines and controlling their power management states.

[[Provisioning_Virtual_Machines_in_VMware_vSphere-Prerequisites_for_VMware_vSphere_Provisioning]]
=== Prerequisites for VMware vSphere Provisioning

The requirements for VMware vSphere provisioning include:

* Synchronized content repositories for the version of Red Hat Enterprise Linux that you want to use. For more information, see link:/html/content_management_guide/importing_red_hat_content#Importing_Red_Hat_Content-Synchronizing_Red_Hat_Repositories[Synchronizing Red Hat Repositories] in the _Content Management Guide_.
* A {SmartProxyServer} managing a network on the vSphere environment. Ensure no other DHCP services run on this network to avoid conflicts with the {SmartProxyServer}. For more information, see xref:Configuring_Networking[].
* An existing VMware template if you aim to use image-based provisioning.
* An activation key for host registration. For more information, see link:/html/content_management_guide/managing_activation_keys#Managing_Activation_Keys-Creating_an_Activation_Key[Creating An Activation Key] in the _Content Management_ guide.

[[Provisioning_Virtual_Machines_in_VMware_vSphere-Creating_a_VMware_vSphere_User]]
=== Creating a VMware vSphere User

The VMware vSphere server requires an administration-like user for {ProjectServer} communication. For security reasons, do not use the `administrator` user for such communication. Instead, create a user with the following permissions:

For VMware vCenter Server version 6.7, set the following permissions:

    - All Privileges -> Datastore -> Allocate Space, Browse datastore, Update Virtual Machine files, Low level file operations
    - All Privileges -> Network -> Assign Network
    - All Privileges -> Resource -> Assign virtual machine to resource pool
    - All Privileges -> Virtual Machine -> Change Config (All)
    - All Privileges -> Virtual Machine -> Interaction (All)
    - All Privileges -> Virtual Machine -> Edit Inventory (All)
    - All Privileges -> Virtual Machine -> Provisioning (All)

For VMware vCenter Server version 6.5, set the following permissions:

    - All Privileges -> Datastore -> Allocate Space, Browse datastore, Update Virtual Machine files, Low level file operations
    - All Privileges -> Network -> Assign Network
    - All Privileges -> Resource -> Assign virtual machine to resource pool
    - All Privileges -> Virtual Machine -> Configuration (All)
    - All Privileges -> Virtual Machine -> Interaction (All)
    - All Privileges -> Virtual Machine -> Inventory (All)
    - All Privileges -> Virtual Machine -> Provisioning (All)

[[Provisioning_Virtual_Machines_in_VMware_vSphere-Adding_a_VMware_vSphere_Connection_to_the_Satellite_Server]]
=== Adding a VMware vSphere Connection to {ProjectServer}

Use this procedure to add a VMware vSphere connection in {ProjectServer}'s compute resources.

Ensure that the host and network-based firewalls are configured to allow {Project} to vCenter communication on TCP port 443. Verify that {Project} is able to resolve the host name of vCenter and vCenter is able to resolve {ProjectServer}'s host name.

.Procedure

To add a connection, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*, and in the Compute Resources window, click *Create Compute Resource*.
. In the *Name* field, enter a name for the resource.
. From the *Provider* list, select *VMware*.
. In the *Description* field, enter a description for the resource.
. In the *VCenter/Server* field, enter the IP address or host name of the vCenter server.
. In the *User* field, enter the user name with permission to access the vCenter's resources.
. In the *Password* field, enter the password for the user.
. Click *Load Datacenters* to populate the list of data centers from your VMware vSphere environment.
. From the *Datacenter* list, select a specific data center to manage from this list.
. In the *Fingerprint* field, ensure that this field is populated with the fingerprint from the data center.
. From the *Display Type* list, select a console type, for example, *VNC* or *VMRC*. Note that VNC consoles are unsupported on VMware ESXi 6.5 and later.
. Optional: In the *VNC Console Passwords* field, select the *Set a randomly generated password on the display connection* check box to secure console access for new hosts with a randomly generated password. You can retrieve the password for the VNC console to access guest virtual machine console from the `libvirtd` host from the output of the following command:
+
[options="nowrap" subs="+quotes"]
----
# virsh edit _your_VM_name_
<graphics type='vnc' port='-1' autoport='yes' listen='0.0.0.0' passwd='_your_randomly_generated_password_'>
----
+
The password randomly generates every time the console for the virtual machine opens, for example, with virt-manager.
. From the *Enable Caching* list, you can select whether to enable caching of compute resources. For more information, see xref:Provisioning_Virtual_Machines_in_VMware_vSphere-Caching_of_Compute_resources[].
. Click the *Locations* and *Organizations* tabs and verify that the values are automatically set to your current context. You can also add additional contexts.
. Click *Submit* to save the connection.

.For CLI Users

Create the connection with the `hammer compute-resource create` command. Select `Vmware` as the `--provider` and set the instance UUID of the data center as the `--uuid`:

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource create --name "_My_vSphere_" \
--provider "Vmware" \
--description "vSphere server at _vsphere.example.com_" \
--server "_vsphere.example.com_" --user "_SatelliteUser_" \
--password "p@55w0rd!" --locations "New York" --organizations "_My_Organization_" \
--uuid 72cb9454-81cd-4231-a863-d9baf0f399f8
----

[[Provisioning_Virtual_Machines_in_VMware_vSphere-Adding_VMware_vSphere_Images_on_the_Satellite_Server]]
=== Adding VMware vSphere Images to {ProjectServer}

VMware vSphere uses templates as images for creating new virtual machines. If using image-based provisioning to create new hosts, you need to add VMware template details to your {ProjectServer}. This includes access details and the template name.

.Procedure

To add an image, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources* and in the Compute Resources window, click the VMware vSphere connection.
. In the *Name* field, enter a name for the image.
. From the *Operatingsystem* list, select the image's base operating system.
. From the *Architecture* list, select the operating system architecture.
. In the *User* field, enter the SSH user name for image access. This is normally the `root` user.
. In the *Password* field, enter the SSH password for image access.
. From the *User data* list, select whether you want the images to support user data input, such as `cloud-init` data.
. In the *Image* field, enter the relative path and name of the template on the vSphere environment. Do not include the data center in the relative path.
. Click *Submit* to save the image details.

.For CLI Users

Create the image with the `hammer compute-resource image create` command. Use the `--uuid` field to store the relative template path on the vSphere environment.

[options="nowrap" subs="+quotes"]
----
# hammer compute-resource image create --name "_Test_vSphere_Image_" \
--operatingsystem "RedHat 7.2" --architecture "x86_64" \
--username root --uuid "Templates/RHEL72" \
--compute-resource "_My_vSphere_"
----

[[Provisioning_Virtual_Machines_in_VMware_vSphere-Adding_VMware_vSphere_Details_to_a_Compute_Profile]]
=== Adding VMware vSphere Details to a Compute Profile

You can predefine certain hardware settings for virtual machines on VMware vSphere. You achieve this through adding these hardware settings to a compute profile.

.Procedure

To add VMware vSphere details to a compute profile, complete the following steps:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Profiles* and, in the Compute Profiles window, click the name of the compute profile, and then click the vSphere connection.
. In the *CPUs* field, enter the number of CPUs to allocate to the new host.
. In the *Cores per socket* field, enter the number of cores to allocate to each CPU.
. In the *Memory* field, enter the amount of memory to allocate to the new host.
. In the *Cluster* field, enter the name of the target host cluster on the VMware environment.
. From the *Resource pool* list, select an available resource allocations for the host.
. In the *Folder* field, enter the folder to organize the host.
. From the *Guest OS* list, select the operating system you want to use in VMware vSphere.
. From the *SCSI controller* list, select the disk access method for the host.
. From the *Virtual H/W version* list, select the underlying VMware hardware abstraction to use for virtual machines.
. You can select the *Memory hot add* or *CPU hot add* check boxes if you want to add more resources while the virtual machine is powered.
. From the *Image* list, select the image to use if performing image-based provisioning.
. From the *Network Interfaces* list, select the network parameters for the host's network interface. You can create multiple network interfaces. However, at least one interface must point to a {SmartProxy}-managed network.
. Select the *Eager zero* check box if you want to use eager zero thick provisioning. If unchecked, the disk uses lazy zero thick provisioning.
. Click *Submit* to save the compute profile.

.For CLI Users

The compute profile CLI commands are not yet implemented in {ProjectName} {ProductVersion}. As an alternative, you can include the same settings directly during the host creation process.

[[Provisioning_Virtual_Machines_in_VMware_vSphere-Creating_Hosts_on_a_VMware_vSphere_Server]]
=== Creating Hosts on a VMware vSphere Server

The VMware vSphere provisioning process provides the option to create hosts over a network connection or using an existing image.

For network-based provisioning, you must create a host to access either {ProjectServer}'s integrated {SmartProxy} or an external {SmartProxyServer} on a VMware vSphere virtual network, so that the host has access to PXE provisioning services. The new host entry triggers the VMware vSphere server to create the virtual machine. If the virtual machine detects the defined {SmartProxyServer} through the virtual network, the virtual machine boots to PXE and begins to install the chosen operating system.

.DHCP Conflicts
If you use a virtual network on the VMware vSphere server for provisioning, ensure that you select a virtual network that does not provide DHCP assignments. This causes DHCP conflicts with {ProjectServer} when booting new hosts.

For image-based provisioning, use the pre-existing image as a basis for the new volume.

.Procedure

To create a host for a VMware vSphere server, complete the following steps:

. In the {Project} web UI, navigate to *Hosts* > *New host*.
. In the *Name* field, enter the name that you want to become the provisioned system's host name.
. Click the *Organization* and *Location* tabs to ensure that the provisioning context is automatically set to the current context.
. From the *Host Group* list, select the host group that you want to use to populate the form.
. From the *Deploy on* list, select the VMware vSphere connection.
. From the *Compute Profile* list, select a profile to use to automatically populate virtual machine-based settings.
. Click the *Interface* tab and click *Edit* on the host's interface.
. Verify that the fields are automatically populated with values. Note in particular:
+
  * The *Name* from the *Host* tab becomes the *DNS name*.
  * The {ProjectServer} automatically assigns an IP address for the new host.
+
. Ensure that the *MAC address* field is blank. The VMware vSphere server assigns one to the host.
. Verify that the *Managed*, *Primary*, and *Provision* options are automatically selected for the first interface on the host. If not, select them.
. In the interface window, review the VMware vSphere-specific fields that are populated with settings from our compute profile. Modify these settings to suit your needs.
. Click the *Operating System* tab, and confirm that all fields automatically contain values.
. For network-based provisioning, ensure that the *Provisioning Method* is set to `Network Based`. For image-based provisioning, ensure that the *Provisioning Method* is set to `Image Based`
. Click *Resolve* in *Provisioning templates* to check the new host can identify the right provisioning templates to use.
. Click the *Virtual Machine* tab and confirm that these settings are populated with details from the host group and compute profile. Modify these settings to suit your needs.
. Click the *Parameters* tab and ensure that a parameter exists that provides an activation key. If not, add an activation key.
. Click *Submit* to save the host entry.

.For CLI Users

Create the host from a network with the `hammer host create` command and include `--provision-method build` to use network-based provisioning.

----
# hammer host create --name "vmware-test1" --organization "_My_Organization_" \
--location "New York" --hostgroup "Base" \
--compute-resource "_My_vSphere_" --provision-method build \
--build true --enabled true --managed true \
--interface "managed=true,primary=true,provision=true,compute_type=VirtualE1000,compute_network=mynetwork" \
--compute-attributes="cpus=1,corespersocket=2,memory_mb=1024,cluster=MyCluster,path=MyVMs,start=true" \
--volume="size_gb=20G,datastore=Data,name=myharddisk,thin=true"
----

[NOTE]
See xref:CLI_Params[] for more information on additional host creation parameters for this compute resource.

.For CLI Users

Create the host from an image with the `hammer host create` command and include `--provision-method image` to use image-based provisioning.

[options="nowrap" subs="+quotes"]
----
# hammer host create --name "vmware-test2" --organization "_My_Organization_" \
--location "New York" --hostgroup "Base" \
--compute-resource "_My_RHEV_" --provision-method image \
--image "Test RHEV Image" --enabled true --managed true \
--interface "managed=true,primary=true,provision=true,compute_type=VirtualE1000,compute_network=mynetwork" \
--compute-attributes="cpus=1,corespersocket=2,memory_mb=1024,cluster=MyCluster,path=MyVMs,start=true" \
--volume="size_gb=20G,datastore=Data,name=myharddisk,thin=true"
----

For more information about additional host creation parameters for this compute resource, see xref:CLI_Params[].


[[Provisioning_Virtual_Machines_in_VMware_vSphere-Caching_of_Compute_resources]]
=== Caching of Compute Resources

Caching of compute resources speeds up rendering of VMware information.

==== Enabling Caching of Compute Resources

To enable or disable caching of compute resources:

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*.
. Click the *Edit* button to the right of the VMware server you want to update.
. Select the *Enable caching* check box.

==== Refreshing the Compute Resources Cache

To refresh the cache of compute resources to update compute resources information:

.Procedure

. In the {Project} web UI, navigate to *Infrastructure* > *Compute Resources*.
. Select a VMware server you want to refresh the compute resources cache for and click the *Refresh Cache* button.

.For CLI Users

Use this API call to refresh the compute resources cache:

[options="nowrap" subs="+quotes"]
----
# curl -H "Accept:application/json,version=2" \
-H "Content-Type:application/json" -X PUT \
-u _username_:__password__ -k \
https://_{foreman.example.com}_/api/compute_resources/_compute_resource_id_/refresh_cache
----

Use the `hammer compute-resource list` command to determine the ID of the VMware server you want to refresh the compute resources cache for.
