<<<
=== Naming Conventions Overview
This solution guide uses a *naming convention for nearly all our Satellite entities*. These naming conventions make possible a lot of the automation explained in various chapters of this solution guide. We can use pattern matching and regular expressions to filter and divide Satellite entities automatically into different execution branches, based on conditions. Each time we use an item that follows our naming convention, we reference the naming convention summary chapter in Appendix XYZ at the end of this document.

The following rules apply for all naming conventions, with only a very few exceptions:

* All entities based on our naming convention are written in *lowercase letters*. The exception might be products and their repositories, if we want to use established and unchangeable vendor name notations.
* We use a *dash* between the different segments of each name pattern.
* To separate two items within a segment, we use *underscores*.
* Most of the pattern-matching starts from the left, so we can have *optional* segments at the *end* or right side of each pattern. These segments are used for optional version or release tags in some examples.

Our naming conventions are most critical for:

* content views
* host groups
* Activation Keys
The huge, and usually increasing, number of these entities makes standard naming conventions especially important.
