<<<
== Appendix II: Scripts


=== Foreman Hook 1: 05_containerhost.sh


In order for the script 05_contrainerhost.sh to work the foreman user needs a user to to execute hammer without password.
|===
|/usr/share/foreman/.hammer/cli_config.yml

|===

additionally the user foreman wants to write temporary information into a .cache folder in his home directory. Sadly foreman cannot create the directory because he is not the owner of his own home directory. Thus we have to create the .cache directory and give foreman the ownership in order for the hook script to be executed.

|===
|mkdir /usr/share/foreman/.cache

|===


* Add the script under _/usr/share/foreman/config/hooks/host/managed/before_provision/_
* chown to foreman
* chmod u+x
* restorecon -RvF /usr/share/foreman/config/hooks

|===
|containerhost=$2

|===


=== Foreman Hook 2: 10_logger.sh


* Add the script under _/usr/share/foreman/config/hooks/host/managed/before_provision/_
* chown to foreman
* chmod u+x
* restorecon -RvF /usr/share/foreman/config/hooks
* Add sudo rule

|===
|logger $1 $2

|===

For the logger script to work, it is mandatory to add the following sudoers rule in order for foreman to use the logger command:

|===
|foreman ALL=(ALL)       NOPASSWD:/usr/bin/logger

|===


=== Foreman Hook 3: 01_zabbix_host_create.sh



* Add the script under _/usr/share/foreman/config/hooks/host/managed/before_provision/_
* chown to foreman
* chmod u+x
* restorecon -RvF /usr/share/foreman/config/hooks


|===
|ZABBIX_SERVER=""

|===
