#!/bin/bash
#
# Use this helper to find anchors. Example:
#
#
# $ ./find-href activation
# build/doc-Content_Management_Guide/index-foreman.html#Managing_Activation_Keys
# build/doc-Content_Management_Guide/index-foreman.html#Managing_Activation_Keys-Creating_an_Activation_Key
# build/doc-Content_Management_Guide/index-foreman.html#Managing_Activation_Keys-Updating_Subscriptions_Associated_with_an_Activation_Key
# build/doc-Content_Management_Guide/index-foreman.html#Managing_Activation_Keys-Using_Activation_Keys
# build/doc-Content_Management_Guide/index-foreman.html#Managing_Activation_Keys-Enabling_Auto_Attach
# build/doc-Content_Management_Guide/index-foreman.html#Managing_Activation_Keys-Setting_the_Service_Level
#

grep -Ro "href=\"#[^\"]*" build/ | grep -i "$1" | sed s/:href=\"//g
