ifdef::context[:parent-context: {context}]
[id="using-foreman-webhooks_{context}"]
= Using Webhooks

A webhook is a way for a web page or web application to provide other applications with information in real time.
Webhooks are only triggered after an event occurs.
The request usually contains details of the event.
An event triggers callbacks, such as sending an e-mail confirming a host has been provisioned.
Webhooks enable you to define a call to an external API based on {Project} internal event using a fire-and-forget message exchange pattern.
The application sending the request does not wait for the response, or ignores it.

Payload of a webhook is created from webhook templates.
Webhook templates use the same ERB syntax as Provisioning templates.
Available variables:

* `@event_name`: Name of an event.
* `@webhook_id`: Unique event ID.
* `@payload`: Payload data, different for each event type. To access individual fields, use `@payload[:key_name]` Ruby hash syntax.
* `@payload[:object]`: Database object for events triggered by database actions (create, update, delete). Not available for custom events.
* `@payload[:context]`: Additional information as hash like request and session UUID, remote IP address, user, organization and location.

Because webhooks use HTTP, no new infrastructure needs be added to existing web services.

The typical use case for webhooks in {Project} is making a call to a monitoring system when a host is created or deleted.

Webhooks are useful where the action you want to perform in the external system can be achieved through its API.
Where it is necessary to run additional commands or edit files, the shellhooks plugin for {SmartProxies} is available.
The shellhooks plugin enables you to define a shell script on the {SmartProxy} that can be executed through the API.

You can use webhooks successfully without installing the shellhooks plugin.

For a list of available events, see xref:webhooks-available-events_{context}[Available webhook events].

include::modules/con_migrating-to-foreman-webhooks.adoc[leveloffset=+1]

include::modules/proc_installing-webhooks-plugin.adoc[leveloffset=+1]

include::modules/proc_creating-a-webhook-template.adoc[leveloffset=+1]

include::modules/proc_creating-a-webhook.adoc[leveloffset=+1]

include::modules/ref_webhooks-available-events.adoc[leveloffset=+1]

include::modules/con_shellhooks-plugin.adoc[leveloffset=+1]

include::modules/proc_installing-shellhooks-plugin.adoc[leveloffset=+1]

include::modules/proc_using-shellhook-arguments.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
