ifdef::context[:parent-context: {context}]

[id="using-foreman-webhooks_{context}"]
= Using Foreman Webhooks

A webhook is a way for a web page or web application to provide other applications with information.
The information is provided immediately. Specific events trigger customized callbacks, such as sending an email when a user registers with a website, or acknowledging online purchases.
Because webhooks use HTTP, no new infrastructure need be added to existing web services.

When the `foreman_webhooks` plugin is installed, {ProjectServer} can be configured to send webhook requests.
Webhooks are only triggered after an event occurs and are only fire-and-forget as responses are ignored.
The typical use case for webhooks in Foreman is making a call to a monitoring system when a host is created or deleted.
{ProjectServer} and various plugins broadcast internal events which, if they are of interest, can be subscribed to.
Webhook objects can be created where the target URL that expressed interest and other details of the event are specified.
The body of a webhook request, also known as payload, can be customized through an associated Webhook template and can be any HTTP content type.
HTTP authentication, content type, and headers can also be configured. {ProjectServer} does not support receiving webhooks.

include::modules/proc_installing-webhooks-shellhooks-plugin.adoc[leveloffset=+1]

include::modules/proc_creating-a-webhook-template.adoc[leveloffset=+1]

include::modules/proc_creating-a-webhook.adoc[leveloffset=+1]

include::modules/ref_webhooks-available-events.adoc[leveloffset=+1]

include::modules/ref_webhooks-templates.adoc[leveloffset=+1]

include::modules/ref_shellhooks.adoc[leveloffset=+1]

include::modules/ref_migrating-from-foreman_webhooks.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
