ifdef::context[:parent-context: {context}]

[id="Installing_Server_Disconnected_{context}"]
= Installing {ProjectServer}

When the intended host for {ProjectServer} is in a disconnected environment, you can install {ProjectServer} by using an external computer to download an ISO image of the packages, and copying the packages to the system you want to install {ProjectServer} on.
This method is not recommended for any other situation as ISO images might not contain the latest updates, bug fixes, and functionality.

Use the following procedures to install {ProjectServer}, perform the initial configuration, and import subscription manifests.

ifndef::foreman-deb[]
Before you continue, consider which manifests are relevant for your environment.
For more information on manifests, see {ContentManagementDocURL}Managing_Red_Hat_Subscriptions_content-management[Managing Red Hat Subscriptions] in the _Content Management Guide_.
endif::[]

NOTE: You cannot register {ProjectServer} to itself.

include::modules/proc_downloading-the-binary-dvd-images.adoc[leveloffset=+1]

include::modules/proc_configuring-the-base-operating-system-with-offline-repositories-in-rhel-7.adoc[leveloffset=+1]

include::modules/proc_configuring-the-base-operating-system-with-offline-repositories-in-rhel-8.adoc[leveloffset=+1]

include::modules/proc_installing-from-the-offline-repositories.adoc[leveloffset=+1]

include::modules/proc_resolving-package-dependancy-errors.adoc[leveloffset=+1]

include::modules/proc_synchronizing-the-system-clock-with-chronyd.adoc[leveloffset=+1]

include::modules/proc_installing-the-sos-package.adoc[leveloffset=+1]

[id="configuring-server_{context}"]
== Configuring {ProjectServer}

Install {ProjectServer} using the `{foreman-installer}` installation script.
Choose from one of the following methods:

* xref:Configuring_Installation_{context}[].
This method is performed by running the installation script with one or more command options.
The command options override the corresponding default initial configuration options and are recorded in the {Project} answer file.
You can run the script as often as needed to configure any necessary options.

NOTE: Depending on the options that you use when running the {Project} installer, the configuration can take several minutes to complete.
An administrator can view the answer file to see previously used options for both methods.

include::modules/proc_configuring-installation.adoc[leveloffset=+2]

include::modules/proc_disabling-subscription-connection.adoc[leveloffset=+1]

include::modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
