[id="Managing_Errata_{context}"]
= Managing Errata

ifdef::satellite[]
As a part of Red Hat's quality control and release process, we provide customers with updates for each release of official Red Hat RPMs.
Red Hat compiles groups of related package into an *erratum* along with an advisory that provides a description of the update.
endif::[]
ifndef::satellite[]
{RHEL} users receive errata for each release of official Red Hat RPMs.
SUSE Linux Enterprise Server users receive errata for each release of official SUSE RPMs.
endif::[]
ifdef::orcharhino[]
Additionally, ATIX provides Debian and Ubuntu users with errata.
endif::[]
There are three types of advisories (in order of importance):

Security Advisory::
Describes fixed security issues found in the package.
The security impact of the issue can be Low, Moderate, Important, or Critical.

Bug Fix Advisory::
Describes bug fixes for the package.

Product Enhancement Advisory::
Describes enhancements and new features added to the package.

{ProjectName} imports this errata information when synchronizing repositories with Red Hat's Content Delivery Network (CDN).
{ProjectName} also provides tools to inspect and filter errata, allowing for precise update management.
This way, you can select relevant updates and propagate them through Content Views to selected content hosts.

Errata are labeled according to the most important advisory type they contain.
Therefore, errata labeled as *Product Enhancement Advisory* can contain only enhancement updates, while *Bug Fix Advisory* errata can contain both bug fixes and enhancements, and *Security Advisory* can contain all three types.

In {ProjectName}, there are two keywords that describe an erratum's relationship to the available content hosts:

Applicable::
An erratum that applies to one or more content hosts, which means it updates packages present on the content host.
Although these errata apply to content hosts, until their state changes to *Installable*, the errata are not ready to be installed.
Installable errata are automatically applicable.

Installable::
An erratum that applies to one or more content hosts and is available to install on the content host.
Installable errata are available to a content host from life cycle environment and the associated Content View, but are not yet installed.

This chapter shows how to manage errata and apply them to either a single host or multiple hosts.

include::modules/proc_inspecting-available-errata.adoc[leveloffset=+1]

include::modules/con_subscribing-to-errata-notifications.adoc[leveloffset=+1]

include::modules/con_limitations-to-repository-dependency-resolution.adoc[leveloffset=+1]

include::modules/proc_creating-a-content-view-filter-for-errata.adoc[leveloffset=+1]

include::modules/proc_adding-errata-to-an-incremental-content-view.adoc[leveloffset=+1]

include::modules/proc_applying-errata-to-a-host.adoc[leveloffset=+1]

include::modules/proc_applying-errata-to-multiple-hosts.adoc[leveloffset=+1]

include::modules/proc_applying-errata-to-a-host-collection.adoc[leveloffset=+1]
