[id="installing-server"]
= Installing server

// User stories are based on the following template:
// As a <user>, I want to leverage <feature X> to reach <state Y> so that I solve <problem Z>.
// Persona of Foreman administrator are based on the "admin" persona as specified in https://github.com/theforeman/foreman-documentation/pull/4319/files 

As an administrator, I want to leverage tuning profiles to ensure my deployment is tailored to the number of hosts I'll deploy so that I prevent performance issues.

As an administrator, I want to leverage installation logs so that I can review the installation process or troubleshoot failures.

As an administrator, I want to install a {ProjectServer} with the default local (internal) database so that I can keep the installation process simple; I don't need the option to fine-tune the database.

As an administrator, I want to install a {ProjectServer} with an external PostgreSQL database (with or without encrypted connections) to help with the server load and gain more flexibility in tuning the database.
