[id="Supported-Usage_and_Versions-of-Project-Components_{context}"]
= Supported Usage and Versions of {Project} Components

[role="_abstract"]

ifdef::satellite[]
== Supported Usage of {Project} Components

Usage of all {ProjectName} components is supported within the context of {ProjectName} only as described below.
Third-party usage of any components is not supported.

{RHELServer}:: Each {ProjectName} subscription includes one supported instance of {RHELServer}.
Reserve this instance solely for the purpose of running  {ProjectName}.
Using the operating system included with {Project} to run other daemons, applications, or services within your environment is not supported.

SELinux:: Ensure SELinux is in enforcing or permissive mode.
Installation with disabled SELinux is not supported.

Foreman:: You can extend Foreman using plug-ins, but only plug-ins packaged with {ProjectName} are supported.
Red{nbsp}Hat does not support plug-ins in the {ProjectName} Optional repository.
See https://access.redhat.com/articles/1343683[Satellite 6 Component Versions] in Red{nbsp}Hat Knowledgebase for information about supported Foreman plug-ins.
+
{ProjectName} also includes components, configuration and functionality to provision and configure operating systems other than {RHEL}.
While these features are included and can be employed, Red{nbsp}Hat supports their usage for {RHEL}.

Pulp:: Pulp usage is only supported through the {ProjectWebUI}, CLI, and API.
+
Direct modification or interaction with Pulp's local API or database can causes irreparable damage to the {ProjectName} databases and is not supported.

Candlepin:: Candlepin usage is only supported through the {ProjectWebUI}, CLI, and API.
+
Direct interaction with Candlepin, its local API, or database can cause irreparable damage to the {ProjectName} databases and is not supported.

Embedded Tomcat Application Server:: The embedded Tomcat application server is only supported through the {ProjectWebUI}, API, and database.
+
Direct interaction with the embedded Tomcat application server local API or database is not supported.

Puppet:: The {Project} installation program enables users to install and configure Puppet servers as a part of {SmartProxyServers}.
A Puppet module, running on a Puppet server on the {ProjectServer} or {Project} {SmartProxyServer}, is also supported by Red{nbsp}Hat.

.Additional resources
* Red{nbsp}Hat supports many different scripting and other frameworks.
See https://access.redhat.com/articles/369183[How does Red{nbsp}Hat support scripting frameworks] in Red{nbsp}Hat Knowledgebase.
endif::[]

ifdef::satellite[]
== Supported Client Architectures: Content Management
Supported combinations of major versions of {RHEL} and hardware architectures for registering and managing hosts with {Project}.
This includes the {project-client-name} repositories.

.Content Management Support
[options="header"]
|====
|Platform |Architectures
|{RHEL} 9 |x86_64, ppc64le, s390x, aarch64
|{RHEL} 8 |x86_64, ppc64le, s390x
|{RHEL} 7 |x86_64, ppc64 (BE), ppc64le, aarch64, s390x
|{RHEL} 6 |x86_64, i386, s390x, ppc64 (BE)
|====
endif::[]

ifdef::satellite[]
== Supported Client Architectures: Host Provisioning
Supported combinations of major versions of {RHEL} and hardware architectures for host provisioning with {Project}.

.Host Provisioning Support
[options="header"]
|====
|Platform |Architectures
|{RHEL} 9 |x86_64
|{RHEL} 8 |x86_64
|{RHEL} 7 |x86_64
|{RHEL} 6 |x86_64, i386
|====
endif::[]

ifdef::satellite[]
== Supported Client Architectures: Configuration Management
Supported combinations of major versions of {RHEL} and hardware architectures for configuration management with {Project}.

.Puppet Agent Support
[options="header",cols="2,1"]
|====
|Platform |Architectures
|{RHEL} 9 |x86_64
|{RHEL} 8 |x86_64, aarch64
|{RHEL} 7 |x86_64
|{RHEL} 6 |x86_64, i386
|====
endif::[]

ifndef::satellite[]
== {ProjectServer} Operating System

{Project} has packages for {EL} 8, Debian 11 and Ubuntu 20.04.
Katello plug-in packages, which provide content management capabilities, are only available for {EL}.

The only architecture {Project} has packages for is x86_64.
endif::[]

ifndef::satellite[]
== Client Operating Systems

{Project} can help to manage any kind of operating systems that have clients {Project} can integrate with.
For example:

* Operating system installers that can perform unattended installations (such as Anaconda in Fedora and CentOS, or Debian-installer in Debian and Ubuntu)
* Puppet
* Ansible
* OpenSCAP
* OpenSSH
* Other clients where integration is provided by external plug-ins

{Project} is actively tested with the following client operating systems:

* CentOS 7 and 8
* Debian stable
* Ubuntu LTS

The Katello plug-in provides functionality for content and subscription management.
The following utilities are provided for selected CentOS and SLES operating systems:

* Katello agent
* Subscription manager
* Katello host tools
* Tracer utility

For Red Hat family operating systems, SELinux must not be set to disabled mode.
endif::[]

ifdef::satellite[]
[roles="_additional-resources"]
== Additional Resources

* See https://access.redhat.com/support/policy/updates/satellite[Red{nbsp}Hat Satellite Product Life Cycle] for information about support periods for {ProjectName} releases.
endif::[]