ifdef::context[:parent-context: {context}]

[id="using-foreman-webhooks_{context}"]
= Using Foreman Webhooks

A webhook is a way for a web page or web application to provide other applications with information in real time.
Webhooks are only triggered after an event occurs.
For example, when a user places an online order, a webhook makes an HTTP request to a pre-configured URL.
The request usually contains details of the event.
An event triggers callbacks, such as sending an -mail confirming an online purchase.

Webhooks use a fire-and-forget message exchange pattern. The application sending the request does not wait for the response, or ignores it.

After installing the `foreman_webhooks` plugin, you can configure {ProjectServer} to send webhook requests.
You can customize events, payloads, HTTP authemntication, content type and headers through {ProjectWebUI}.

Because webhooks use HTTP, no new infrastructure need be added to existing web services.

The typical use case for webhooks in {Project} is making a call to a monitoring system when a host is created or deleted.

{ProjectServer} does not support receiving webhooks.

.Additional resources

* xref:webhooks-available-events_{context}[Available webhook events]


include::modules/proc_installing-webhooks-shellhooks-plugin.adoc[leveloffset=+1]

include::modules/proc_creating-a-webhook-template.adoc[leveloffset=+1]

include::modules/proc_creating-a-webhook.adoc[leveloffset=+1]

include::modules/ref_webhooks-available-events.adoc[leveloffset=+1]

include::modules/ref_webhooks-templates.adoc[leveloffset=+1]

include::modules/ref_shellhooks.adoc[leveloffset=+1]

include::modules/ref_migrating-from-foreman_webhooks.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
