[id="installing-server-disconnected"]
[id="installing-satellite-server-disconnected"]
= Installing {ProjectServer}

When the intended host for {ProjectServer} is in a disconnected environment, you can install {ProjectServer} by using an external computer to download an ISO image of the packages, and copying the packages to the system you want to install {ProjectServer} on.
This method is not recommended for any other situation as ISO images might not contain the latest updates, bug fixes, and functionality.

Use the following procedures to install {ProjectServer}, perform the initial configuration, and import subscription manifests.

ifndef::foreman-deb[]
Before you continue, consider which manifests are relevant for your environment.
For more information on manifests, see {ContentManagementDocURL}Managing_Subscriptions[Managing Subscriptions] in the _Content Management Guide_.
endif::[]

NOTE: You cannot register {ProjectServer} to itself.

include::modules/proc_downloading-the-binary-dvd-images.adoc[leveloffset=+1]

include::modules/proc_configuring-the-base-operating-system-with-offline-repositories.adoc[leveloffset=+1]

include::modules/proc_installing-from-the-offline-repositories.adoc[leveloffset=+1]

include::modules/proc_resolving-package-dependancy-errors.adoc[leveloffset=+1]

include::modules/proc_synchronizing-the-system-clock-with-chronyd.adoc[leveloffset=+1]

include::modules/proc_installing-the-sos-package.adoc[leveloffset=+1]

[id="configuring-server_{context}"]
== Configuring {ProjectServer}

Install {ProjectServer} using the `{foreman-installer}` installation script.
Choose from one of the following methods:

* xref:configuring-satellite-manually_{context}[].
This method is performed by running the installation script with one or more command options.
The command options override the corresponding default initial configuration options and are recorded in the {Project} answer file.
You can run the script as often as needed to configure any necessary options.

* xref:configuring-satellite-automatically-using-an-answer-file_{context}[].
This method is performed by using an answer file to automate the configuration process when running the installation script.
The default {Project} answer file is `/etc/foreman-installer/scenarios.d/{project-context}-answers.yaml`.
The answer file in use is set by the `answer_file` directive in the `/etc/foreman-installer/scenarios.d/{project-context}.yaml` configuration file.

NOTE: Depending on the options that you use when running the {Project} installer, the configuration can take several minutes to complete.
An administrator can view the answer file to see previously used options for both methods.

include::modules/proc_configuring-installation.adoc[leveloffset=+2]

include::modules/proc_enabling-the-disconnected-mode.adoc[leveloffset=+1]

include::modules/proc_importing-a-subscription-manifest-into-satellite-server.adoc[leveloffset=+1]
