[[Managing_Subscriptions]]
= Managing Subscriptions

{ProjectNameX} can import content from the Red Hat Content Delivery Network (CDN).
{ProjectX} requires a Subscription Manifest to find, access, and download content from the corresponding repositories.
You must have a Subscription Manifest containing a subscription allocation for each organization on {ProjectServer}.
All subscription information is available in your Red Hat Customer Portal account.

Before you can complete the tasks in this chapter, you must create a Subscription Manifest in the Customer Portal.

To create, manage, and export a Subscription Manifest in the Customer Portal, see https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html/using_red_hat_subscription_management/using_manifests_con[Using Manifests] in the _Using Red Hat Subscription Management_ guide.

Use this chapter to import a Subscription Manifest and manage the manifest within the {ProjectWebUI}.

.Subscription Allocations and Organizations

You can manage more than one organization if you have more than one subscription allocation.
{ProjectX} requires a single allocation for each organization configured in {ProjectServer}.
The advantage of this is that each organization maintains separate subscriptions so that you can support multiple organizations, each with their own Red Hat accounts.

.Future-Dated subscriptions

You can use future-dated subscriptions in a subscription allocation.
When you add future-dated subscriptions to content hosts before the expiry date of the existing subscriptions, you can have uninterrupted access to repositories.

Manually attach the future-dated subscriptions to your content hosts before the current subscriptions expire.
Do not rely on the auto-attach method because this method is designed for a different purpose and might not work.
For more information, see xref:Attaching_Subscriptions_to_Content_Hosts[].

include::modules/proc_importing-a-subscription-manifest-into-foreman-server.adoc[leveloffset=+1]

include::modules/proc_locating-a-subscription.adoc[leveloffset=+1]

include::modules/proc_adding-subscriptions-to-subscription-allocations.adoc[leveloffset=+1]

include::modules/proc_removing-subscriptions-and-subscription-allocations.adoc[leveloffset=+1]

include::modules/proc_updating-and-refreshing-subscription-manifests.adoc[leveloffset=+1]

include::modules/proc_attaching-subscriptions-to-content-hosts.adoc[leveloffset=+1]

include::modules/proc_Bulk-Updating-Content-Hosts-Subscriptions.adoc[leveloffset=+1]
