ifdef::context[:parent-context: {context}]

[id="Configuring_Server_with_a_Custom_SSL_Certificate_{context}"]
= Configuring {ProjectServer} with a Custom SSL Certificate

By default, {ProjectName} uses a self-signed SSL certificate to enable encrypted communications between {ProjectServer}, external {SmartProxyServer}s, and all hosts.
If you cannot use a {Project} self-signed certificate, you can configure {ProjectServer} to use an SSL certificate signed by an external Certificate Authority.

To configure your {ProjectServer} with a custom certificate, complete the following procedures:

. xref:creating-a-custom-certificate_{project-context}[]
. xref:Deploying_a_Custom_SSL_Certificate_to_Server_{project-context}[]
. xref:deploying-a-custom-ssl-certificate-to-hosts_{project-context}[]
. If you have external {SmartProxyServer}s registered to {ProjectServer}, you must configure them with custom SSL certificates.
The same Certificate Authority must sign certificates for {ProjectServer} and {SmartProxyServer}.
For more information, see {InstallingSmartProxyDocURL}configuring-capsule-custom-server-certificate_{smart-proxy-context}[Configuring {SmartProxyServer} with a Custom SSL Certificate] in _{InstallingSmartProxyDocTitle}_.

//Creating a Custom SSL Certificate for {ProjectServer}
include::modules/proc_creating-a-custom-certificate.adoc[leveloffset=+1]

//Deploying a Custom SSL Certificate to {ProjectServer}
include::modules/proc_deploying-a-custom-ssl-certificate-to-satellite-server.adoc[leveloffset=+1]

//Deploying a Custom SSL Certificate to Hosts
include::modules/proc_deploying-a-custom-ssl-certificate-to-hosts.adoc[leveloffset=+1]

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
