ifdef::context[:parent-context: {context}]

[id="provisioning-cloud-instances-gce_{context}"]
= Provisioning Cloud Instances on Google Compute Engine

:context: gce-provisioning
:gce-provisioning:
:CRname: Google Compute Engine

{ProjectName} can interact with Google Compute Engine (GCE), including creating new virtual machines and controlling their power management states.
ifdef::satellite[]
You can only use golden images supported by {Team} with {Project} for creating GCE hosts.
endif::[]

ifdef::orcharhino[]
Refer to the xref:sources/compute_resources/gce.adoc[Google GCE] guide for more information.
endif::[]

.Prerequisites

include::modules/snip_common-compute-resource-prereqs.adoc[]
* In your GCE project, configure a service account with the necessary IAM Compute role.
For more information, see https://cloud.google.com/compute/docs/access/iam[Compute Engine IAM roles] in the GCE documentation.
* In your GCE project-wise metadata, set the `enable-oslogin` to `FALSE`.
For more information, see https://cloud.google.com/compute/docs/instances/managing-instance-access#enable_oslogin[Enabling or disabling OS Login] in the GCE documentation.
* Optional: If you want to use Puppet with GCE hosts, navigate to *Administer* > *Settings* > *Puppet* and enable the `Use UUID for certificates` setting to configure Puppet to use consistent Puppet certificate IDs.
* Based on your needs, associate a `finish` or `user_data` provisioning template with the operating system you want to use. For more information about provisioning templates, see {ProvisioningDocURL}provisioning-templates_provisioning[Provisioning Templates].

.Procedure Overview

. xref:adding-gce-connection_gce-provisioning[].
. xref:adding-images-to-server_gce-provisioning[].
. xref:adding-gce-details-to-a-compute-profile_gce-provisioning[].
. xref:creating-image-only-hosts_gce-provisioning[].

include::modules/proc_adding-gce-connection.adoc[leveloffset=+1]

include::modules/proc_adding-images-to-server.adoc[leveloffset=+1]

include::modules/proc_adding-gce-details-to-a-compute-profile.adoc[leveloffset=+1]

include::modules/proc_creating-image-only-hosts.adoc[leveloffset=+1]

:!gce-provisioning:
:!CRname:

ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
