[[Use_Case_Considerations]]
= Use Case Considerations

Because Amazon Web Services is an image-only service, there are common {Project} use cases that do not work, or require extra configuration in an Amazon Web Service environment.
If you plan to use {Project} on AWS, ensure that the use case scenarios that you want to use are available in an AWS environment.

== Use Cases Known to Work

You can perform the following {ProjectName} use cases on AWS:

ifeval::["{build}" != "foreman-deb"]
* {ContentManagementDocURL}Managing_Subscriptions[Subscription Management]
* {ContentManagementDocURL}Importing_Red_Hat_Content[Content Management]
* {ContentManagementDocURL}Managing_Errata[Errata Management]
* {ManagingHostsDocURL}registering-a-host-to-satellite[Configuring Hosts]
endif::[]
ifeval::["{build}" == "satellite"]
* https://access.redhat.com/products/red-hat-insights/#satellite6[Red Hat Insights]
endif::[]
* {AdministeringDocURL}sect-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Configuring_External_Authentication-Using_Identity_Management[Realm Integration via IdM]
* {AdministeringDocURL}chap-Red_Hat_Satellite-Administering_Red_Hat_Satellite-Security_Compliance_Management[OpenSCAP]
* {ManagingHostsDocURL}configuring-and-setting-up-remote-jobs_managing-hosts[Remote Execution]

ifeval::["{build}" != "foreman-deb"]
.Subscriptions

Not all Red Hat subscriptions are eligible to run in public cloud environments.
For more information about subscription eligibility, see the https://www.redhat.com/en/technologies/cloud-computing/cloud-access#program-details[Red Hat Cloud Access Page].
You can create additional organizations and then import additional manifests to the organizations.
For more information, see {ContentManagementDocURL}Managing_Organizations-Creating_an_Organization[Creating an Organization] in the _Content Management Guide_.
endif::[]

.Multi-homed {Project} and {SmartProxy}

ifeval::["{build}" == "satellite"]
Multi-homed {Project} is not supported.

Multi-homed {SmartProxy} is supported, to implement this, you can configure {SmartProxies} with a load balancer.
For more information, see {BaseURL}configuring_capsules_with_a_load_balancer/index[Configuring {SmartProxies} with a Load Balancer].
endif::[]

ifeval::["{build}" != "satellite"]
One way to use multi-homed {SmartProxies} is by configuring {SmartProxies} with a load balancer.
For more information, see {BaseURL}configuring_capsules_with_a_load_balancer/index[Configuring {SmartProxies} with a Load Balancer].
endif::[]

You must do this when {ProjectServer} or {SmartProxyServer} has different internal and external DNS host names and there is no site-to-site VPN connection between the locations where you deploy {ProjectServer} and {SmartProxyServer}.

ifeval::["{build}" != "foreman-deb"]
.On demand content sources
You can use the *On demand* download policy to reduce the storage footprint of the Red Hat Enterprise Linux server that runs {Project}.
When you set the download policy to *On Demand*, content syncs to the {ProjectServer} or {SmartProxyServer} when a content host requests it.

For more information, see {ContentManagementDocURL}Importing_Red_Hat_Content[Importing Red Hat Content] in the _Content Management Guide_.

endif::[]

== Use Cases that Do Not Work

In AWS, you cannot manage the DHCP.
Because of this, most of {ProjectServer}’s kickstart and PXE provisioning models are unusable.
This includes:

* PXE Provisioning
* Discovery and Discovery Rules
* ISO Provisioning methods.
** PXE-Less Discovery (iPXE)
** Per-host ISO
** Generic ISO
** Full-host ISO
