[[chap-Red_Hat_Satellite-API_Guide-Common_REST_API_Functions]]
== Common REST API functions

=== Using GET to query resources

This section describes how to use `GET` requests to query the {ProjectServer} for various types of information. `GET` requests do not make any changes to {Project} resources, they only return information about resources.

=== Listing all resources

Obtain a list of resources with a `GET` request on the collection URI obtained from the entry point.

Include an Accept HTTP header to define the MIME type for the response format.

[options="nowrap", subs="+quotes,attributes"]
----
GET /api/_collection_ HTTP/1.1
Accept: _MIME type_
----

=== Determining the state of a resource

Determine the state of a resource with a `GET` request on a URI obtained from a collection listing.

Include an Accept HTTP header to define the MIME type for the response format.

[options="nowrap", subs="+quotes,attributes"]
----
GET /api/_collection_/_resource_id_ HTTP/1.1
Accept: _MIME type_
----

=== Using POST to create resources

This section describes how to use `POST` requests to create {Project} resources. Special permissions might be required for some `POST` requests; see xref:apiPermsMatrix[] for information about API permissions.

[[sect-Red_Hat_Satellite-API_Guide-Common_REST_API_Functions-Creating_a_Resource_in_a_Collection]]
=== Creating a resource

Create a new resource with a `POST` request to the collection URI containing a representation of the new resource.

A `POST` request requires a Content-Type header. This informs the API of the representation MIME type in the body content as part of the request.

Include an Accept HTTP header to define the MIME type for the response format.

Each resource type has its own specific required properties. The client supplies these properties when creating a new resource. Refer to the individual resource type documentation for more details.

If a required property is absent, the creation fails with a representation indicating the missing elements.

[options="nowrap", subs="+quotes,attributes"]
----
POST /api/_collection_ HTTP/1.1
Accept: _MIME type_
Content-Type: _MIME type_

_body_
----
=== Using PUT to modify resources

This section describes how to use `PUT` requests to modify {Project} resources. Special permissions might be required for some `PUT` requests; see xref:apiPermsMatrix[] for information about API permissions.

[[sect-Red_Hat_Satellite-API_Guide-Common_REST_API_Functions-Updating_a_Resource]]
=== Updating a resource

Modify resource properties with a PUT request containing an updated description from a previous `GET` request for the resource URI. Details on modifiable properties are found in the individual resource type documentation.

A `PUT` request requires a Content-Type header. This informs the API of the representation MIME type in the body content as part of the request.

Include an Accept HTTP header to define the MIME type for the response format.

[options="nowrap", subs="+quotes,attributes"]
----
PUT /api/_collection_/_resource_id_ HTTP/1.1
Accept: _MIME type_
Content-Type: _MIME type_

_body_
----

This does not include immutable resource properties that an API user has attempted to modify. If you attempt to modify a strictly immutable resource property, the API reports a conflict with an error message representation in the response body.

Properties omitted from the representation are ignored and not changed.

=== Using DELETE to delete resources

This section describes how to use `DELETE` requests to delete {Project} resources. Special permissions might be required for some `DELETE` requests; see xref:apiPermsMatrix[] for information about API permissions.

[[sect-Red_Hat_Satellite-API_Guide-Common_REST_API_Functions-Deleting_a_Resource]]
=== Deleting a resource

Delete a resource with a `DELETE` request sent to its URI.

Include an Accept HTTP header to define the MIME type for the response format.

[options="nowrap", subs="+quotes,attributes"]
----
DELETE /api/_collection_/_resource_id_ HTTP/1.1
Accept: _MIME type_
----

Some cases require optional body content in the `DELETE` request to specify additional properties. A `DELETE` request with optional body content requires a Content-Type header to inform the API of the representation MIME type in the body content. If a `DELETE` request contains no body content, omit the Content-Type header.
