[id="api-cheat-sheet"]
= API cheat sheet

You can review the following examples of how to use the {ProjectName} API to perform various tasks.
You can use the API on {ProjectServer} via HTTPS on port 443 or on {SmartProxyServer} via HTTPS on port 8443.

You can address these different port requirements within the script itself.
For example, in Ruby, you can specify the {Project} and {SmartProxy} URLs as follows:

[options="nowrap", subs="+quotes,verbatim,attributes"]
----
url = 'https://_{foreman-example-com}_/api/v2/'
{smart-proxy-context}_url = 'https://_{smartproxy-example-com}_:8443/api/v2/'
katello_url = 'https://_{foreman-example-com}_/katello/api/v2/'
----

For the host that is subscribed to {ProjectServer} or {SmartProxyServer}, you can determine the correct port required to access the API from the */etc/rhsm/rhsm.conf* file, in the port entry of the `[server]` section.
You can use these values to fully automate your scripts, removing any need to verify which ports to use.

The following examples use `curl` for sending API requests.
For more information, see xref:calling-the-api-in-curl[].

Examples in this chapter use the Python `json.tool` module to format the output.
