[id="calling-the-api-in-curl"]
= Calling the API in curl

You can use `curl` with the {Project} API to perform various tasks.

{ProjectName} requires the use of HTTPS, and by default a certificate for host identification.
If you have not added the {ProjectServer} certificate as described in xref:ssl-authentication-overview[], then you can use the `--insecure` option to bypass certificate checks.

For user authentication, you can use the `--user` option to provide {Project} user credentials in the form `--user _username:password_` or, if you do not include the password, the command prompts you to enter it.
To reduce security risks, do not include the password as part of the command, because it then becomes part of your shell history.
Examples in this section include the password only for the sake of simplicity.

Be aware that if you use the `--silent` option, `curl` does not display a progress meter or any error messages.

Examples in this chapter use the Python `json.tool` module to format the output.

include::snip_note-python3-vs-python.adoc[]

[id="sect-API_Guide-Passing_JSON_Data_with_the_API_Request"]
== Passing JSON data to the API request

You can pass data to {ProjectServer} with the API request.
The data must be in JSON format.
When specifying JSON data with the `--data` option, you must set the following HTTP headers with the `--header` option:

----
--header "Accept:application/json" \
--header "Content-Type:application/json"
----

Use one of the following options to include data with the `--data` option:

.  The quoted JSON formatted data enclosed in curly braces `{}`.
  When passing a value for a JSON type parameter, you must escape quotation marks `"` with backslashes `\`.
  For example, within curly braces, you must format `"Example JSON Variable"` as `\"Example JSON Variable\"`:
+
----
--data {"id":44, "smart_class_parameter":{"override":"true", "parameter_type":"json", "default_value":"{\"GRUB_CMDLINE_LINUX\": {\"audit\":\"1\",\"crashkernel\":\"true\"}}"}}
----
.  The unquoted JSON formatted data enclosed in a file and specified by the `@` sign and the filename.
For example:
+
[options="nowrap", subs="+quotes,attributes"]

----
--data @_file_.json
----
+
Using external files for JSON formatted data has the following advantages:
+
* You can use your favorite text editor.
* You can use syntax checker to find and avoid mistakes.
* You can use tools to check the validity of JSON data or to reformat it.

.Validating a JSON file
Use the `json_verify` tool to check the validity of a JSON file:

[options="nowrap", subs="+quotes,attributes"]
----
$ json_verify < _test_file_.json
----

[id="sect-API_Guide-Performing_Simple_Queries"]
== Retrieving a list of resources

This section outlines how to use `curl` with the {ProjectX} API to request information from {Project}.
These examples include both requests and responses.
Expect different results for each deployment.

.Listing users

This example is a basic request that returns a list of {Project} resources, {Project} users in this case.
Such requests return a list of data wrapped in metadata, while other request types only return the actual object.

Example request:
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --request GET --user _My_User_Name_:__My_Password__ \
https://_{foreman-example-com}_/api/users | python3 -m json.tool
----

Example response:
[options="nowrap", subs="+quotes,attributes"]
----
{
    "page": 1,
    "per_page": 20,
    "results": [
        {
            "admin": false,
            "auth_source_id": 1,
            "auth_source_name": "Internal",
            "created_at": "2018-09-21 08:59:22 UTC",
            "default_location": null,
            "default_organization": null,
            "description": "",
            "effective_admin": false,
            "firstname": "",
            "id": 5,
            "last_login_on": "2018-09-21 09:03:25 UTC",
            "lastname": "",
            "locale": null,
            "locations": [],
            "login": "test",
            "mail": "example@domain.com",
            "organizations": [
                {
                    "id": 1,
                    "name": "Default Organization"
                }
            ],
            "ssh_keys": [],
            "timezone": null,
            "updated_at": "2018-09-21 09:04:45 UTC"
        },
        {
            "admin": true,
            "auth_source_id": 1,
            "auth_source_name": "Internal",
            "created_at": "2018-09-20 07:09:41 UTC",
            "default_location": null,
            "default_organization": {
                "description": null,
                "id": 1,
                "name": "Default Organization",
                "title": "Default Organization"
            },
            "description": "",
            "effective_admin": true,
            "firstname": "Admin",
            "id": 4,
            "last_login_on": "2018-12-07 07:31:09 UTC",
            "lastname": "User",
            "locale": null,
            "locations": [
                {
                    "id": 2,
                    "name": "Default Location"
                }
            ],
            "login": "admin",
            "mail": "root@example.com",
            "organizations": [
                {
                    "id": 1,
                    "name": "Default Organization"
                }
            ],
            "ssh_keys": [],
            "timezone": null,
            "updated_at": "2018-11-14 08:19:46 UTC"
        }
    ],
    "search": null,
    "sort": {
        "by": null,
        "order": null
    },
    "subtotal": 2,
    "total": 2
}
----

[id="sect-API_Guide-Creating_and_Modifying_Resources"]
== Creating and modifying resources

This section outlines how to use `curl` with the {ProjectX} API to manipulate resources on the {ProjectServer}.
These API calls require that you pass data in `json` format with the API call.
For more information, see xref:sect-API_Guide-Passing_JSON_Data_with_the_API_Request[].

[id="ex-API_Guide-Creating_a_New_User"]
.Creating a user

This example creates a user by providing required information in the `--data` option.

Example request:
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --header "Accept:application/json" \
--header "Content-Type:application/json" --request POST \
--user _My_User_Name_:__My_Password__ \
--data "{\"firstname\":\"_Test Name_\",\"mail\":\"_test@example.com_\",\"login\":\"_test_user_\",\"password\":\"_password123_\",\"auth_source_id\":__1__}" \
https://_{foreman-example-com}_/api/users | python3 -m json.tool
----

.Modifying a user

This example modifies first name and login of the `test_user` that was created in xref:ex-API_Guide-Creating_a_New_User[].

Example request:
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --header "Accept:application/json" \
--header "Content-Type:application/json" --request PUT \
--user _My_User_Name_:__My_Password__ \
--data "{\"firstname\":\"_New Test Name_\",\"mail\":\"_test@example.com_\",\"login\":\"_new_test_user_\",\"password\":\"_password123_\",\"auth_source_id\":__1__}" \
https://_{foreman-example-com}_/api/users/_8_ | python3 -m json.tool
----
