[[sect-API_Guide-Understanding_the_API_Syntax]]
=== API request composition

include::snip_note-python3-vs-python.adoc[]

The built-in API reference shows the API route, or path, preceded by an HTTP verb:

----
HTTP_VERB API_ROUTE
----

To work with the API, construct a command using the `curl` command syntax and the API route from the reference document:
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --request _HTTP_VERB_ \                   <1>
--insecure \                                   <2>
--user _sat_username:sat_password_ \             <3>
--data @_file_.json \                            <4>
--header "Accept:application/json" \ <5>
--header "Content-Type:application/json" \      <5>
--output _file_                                  <6>
_API_ROUTE_ \                                    <7>
| python3 -m json.tool                          <8>
----

<1> To use `curl` for the API call, specify an HTTP verb with the `--request` option. For example, `--request POST`.
<2> Add the `--insecure` option to skip SSL peer certificate verification check.
<3> Provide user credentials with the `--user` option.
<4> For `POST` and `PUT` requests, use the `--data` option to pass JSON formatted data. For more information, see xref:sect-API_Guide-Passing_JSON_Data_with_the_API_Request[].
<5> When passing the JSON data with the `--data` option, you must specify the following headers with the `--header` option. For more information, see xref:sect-API_Guide-Passing_JSON_Data_with_the_API_Request[].
<6> When downloading content from {ProjectServer}, specify the output file with the `--output` option.
<7> Use the API route in the following format: `https://_{foreman-example-com}_/katello/api/activation_keys`. In {ProjectX}, version 2 of the API is the default. Therefore it is not necessary to use `v2` in the URL for API calls.
<8> Redirect the output to the Python `json.tool` module to make the output easier to read.

=== Using the GET HTTP verb

Use the GET HTTP verb to get data from the API about an existing entry or resource.

.Example

This example requests the amount of {Project} hosts:

Example request:
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --request GET --insecure --user _sat_username:sat_password_ \
https://_{foreman-example-com}_/api/hosts | python3 -m json.tool
----

Example response:
[options="nowrap", subs="+quotes,attributes"]
----
{
  "total": 2,
  "subtotal": 2,
  "page": 1,
  "per_page": 20,
  "search": null,
  "sort": {
    "by": null,
    "order": null
  },
  "results":
_output truncated_
----
The response from the API indicates that there are two results in total, this is the first page of the results, and the maximum results per page is set to 20. For more information, see xref:sect-API_Guide-Understanding_the_JSON_Response_Format[].

=== Using the POST HTTP verb

Use the POST HTTP verb to submit data to the API to create an entry or resource. You must submit the data in JSON format. For more information, see xref:sect-API_Guide-Passing_JSON_Data_with_the_API_Request[].

.Example

This example creates an activation key.

. Create a test file, for example, `activation-key.json`, with the following content:
+
[options="nowrap", subs="+quotes,attributes"]
----
{"organization_id":1, "name":"TestKey", "description":"Just for testing"}
----

. Create an activation key by applying the data in the `activation-key.json` file:
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --header "Accept:application/json" \
--header "Content-Type:application/json" --request POST \
--user _sat_username:sat_password_ --insecure \
--data @activation-key.json \
https://_{foreman-example-com}_/katello/api/activation_keys \
| python3 -m json.tool
----
+
Example response:
+
[options="nowrap", subs="+quotes,attributes"]
----
{
    "id": 2,
    "name": "TestKey",
    "description": "Just for testing",
    "unlimited_hosts": true,
    "auto_attach": true,
    "content_view_id": null,
    "environment_id": null,
    "usage_count": 0,
    "user_id": 3,
    "max_hosts": null,
    "release_version": null,
    "service_level": null,
    "content_overrides": [

    ],
    "organization": {
        "name": "Default Organization",
        "label": "Default_Organization",
        "id": 1
    },
    "created_at": "2017-02-16 12:37:47 UTC",
    "updated_at": "2017-02-16 12:37:48 UTC",
    "content_view": null,
    "environment": null,
    "products": null,
    "host_collections": [

    ],
    "permissions": {
        "view_activation_keys": true,
        "edit_activation_keys": true,
        "destroy_activation_keys": true
    }
}
----

. Verify that the new activation key is present. In the {ProjectWebUI}, navigate to *Content* > *Activation keys* to view your activation keys.

=== Using the PUT HTTP verb

Use the PUT HTTP verb to change an existing value or append to an existing resource. You must submit the data in JSON format. For more information, see xref:sect-API_Guide-Passing_JSON_Data_with_the_API_Request[].

.Example

This example updates the `TestKey` activation key created in the previous example.

. Edit the `activation-key.json` file created previously as follows:
+
[options="nowrap", subs="+quotes,attributes"]
----
{"organization_id":1, "name":"TestKey", "description":"Just for testing","max_hosts":"10" }
----

. Apply the changes in the JSON file:
+
Example request:
+
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --header "Accept:application/json" \
--header "Content-Type:application/json" --request PUT \
--user _sat_username:sat_password_ --insecure \
--data @activation-key.json \
https://_{foreman-example-com}_/katello/api/activation_keys/2 \
| python3 -m json.tool
----
+
Example response:
+
[options="nowrap", subs="+quotes,attributes"]
----
{
    "id": 2,
    "name": "TestKey",
    "description": "Just for testing",
    "unlimited_hosts": false,
    "auto_attach": true,
    "content_view_id": null,
    "environment_id": null,
    "usage_count": 0,
    "user_id": 3,
    "max_hosts": 10,
    "release_version": null,
    "service_level": null,
    "content_overrides": [

    ],
    "organization": {
        "name": "Default Organization",
        "label": "Default_Organization",
        "id": 1
    },
    "created_at": "2017-02-16 12:37:47 UTC",
    "updated_at": "2017-02-16 12:46:17 UTC",
    "content_view": null,
    "environment": null,
    "products": null,
    "host_collections": [

    ],
    "permissions": {
        "view_activation_keys": true,
        "edit_activation_keys": true,
        "destroy_activation_keys": true
    }
}
----

. In the {ProjectWebUI}, verify the changes by navigating to *Content* > *Activation keys*.

=== Using the DELETE HTTP verb

To delete a resource, use the DELETE verb with an API route that includes the ID of the resource you want to delete.

.Example
This example deletes the `TestKey` activation key which ID is 2:

Example request:
[options="nowrap", subs="+quotes,attributes"]
----
$ curl --header "Accept:application/json" \
--header "Content-Type:application/json" --request DELETE \
--user _sat_username:sat_password_ --insecure \
https://_{foreman-example-com}_/katello/api/activation_keys/2 \
| python3 -m json.tool
----
Example response:
[options="nowrap", subs="+quotes,attributes"]
----
_output omitted_
    "started_at": "2017-02-16 12:58:17 UTC",
    "ended_at": "2017-02-16 12:58:18 UTC",
    "state": "stopped",
    "result": "success",
    "progress": 1.0,
    "input": {
        "activation_key": {
            "id": 2,
            "name": "TestKey"
_output truncated_
----

=== Relating API error messages to the API reference

The API uses a RAILs format to indicate an error:

[options="nowrap", subs="+quotes,attributes"]
----
_Nested_Resource_._Attribute_Name_
----

This translates to the following format used in the API reference:

[options="nowrap", subs="+quotes,attributes"]
----
_Resource_[_Nested_Resource_attributes_][_Attribute_Name_id_]
----
