[[chap-Red_Hat_Satellite-API_Guide-Using_the_Red_Hat_Satellite_API]]
== Using the Red{nbsp}Hat Satellite API

This chapter provides a range of examples of how to use the Red{nbsp}Hat Satellite API to perform different tasks. You can use the API on Satellite Server via HTTPS on port 443, or on Capsule Server via HTTPS on port 8443.

You can address these different port requirements within the script itself. For example, in Ruby, you can specify the Satellite and Capsule URLs as follows:

[options="nowrap" subs="+quotes,verbatim"]
----
url = 'https://_satellite.example.com_/api/v2/'
capsule_url = 'https://_capsule.example.com_:8443/api/v2/'
katello_url = 'https://_satellite.example.com_/katello/api/v2/'
----
For the host that is subscribed to Satellite{nbsp}Server or Capsule{nbsp}Server, you can determine the correct port required to access the API from the */etc/rhsm/rhsm.conf* file, in the port entry of the `[server]` section. You can use these values to fully automate your scripts, removing any need to verify which ports to use.

This chapter uses `curl` for sending API requests. For more information, see xref:sect-API_Guide-API_Requests_with_curl[].

Examples in this chapter use the Python `json.tool` module to format the output.

include::Working_with_Hosts.adoc[]

include::Working_with_Life_Cycle_Environments.adoc[]

include::Uploading_Content_to_Satellite_Server.adoc[]

include::Applying_Errata_to_a_Host_or_Host_Collection.adoc[]

include::Using_Extended_Searches.adoc[]

include::Using_Searches_with_Pagination_Control.adoc[]

include::Overriding_Smart_Class_Parameters.adoc[]

include::Modifying_a_Smart_Class_Parameter_Using_an_External_File.adoc[]

include::Deleting-OpenSCAP-Reports.adoc[]

include::Working_with_Pulp.adoc[]
