#!/usr/bin/env ruby

# frozen_string_literal: true

require 'asciidoctor'

BUILDS = %w[
  foreman-el
  foreman-deb
  containerized-katello
  containerized-orcharhino
  katello
  satellite
  orcharhino
].freeze

BASE_DIR = File.dirname(__dir__)

included = Set.new

Dir.glob(File.join(BASE_DIR, '*', 'master.adoc')).each do |path|
  BUILDS.each do |build|
    doc = Asciidoctor.load_file(
      path,
      doctype: :book,
      safe: :safe,
      base_dir: File.dirname(path),
      attributes: { 'build' => build }
    )

    included += doc.catalog[:includes].keys
  end
end

modules = Dir.glob(File.join(BASE_DIR, 'common', 'modules', '**', '*.adoc'))
assemblies = Dir.glob(File.join(BASE_DIR, 'common', 'assembly_*.adoc'))
absolute_included = included.map { |path| File.join(BASE_DIR, "#{path}.adoc") }

doc_root = Pathname.new(File.dirname(BASE_DIR))

unused = ((modules + assemblies) - absolute_included).map do |path|
  Pathname.new(path).relative_path_from(doc_root).to_s
end

# Content excluded from all current builds during the Satellite containerization transition
# https://github.com/theforeman/foreman-documentation/issues/4964
non_containerized_satellite_content = [
  'guides/common/assembly_building-cloud-images-for-project.adoc',
  'guides/common/assembly_cloning-project-server.adoc',
  'guides/common/assembly_updating-disconnected-satellite.adoc',
  'guides/common/assembly_upgrading-project-disconnected.adoc',
  'guides/common/assembly_usage-metrics-collection-in-project.adoc',
  'guides/common/modules/con_building-cloud-images-for-project.adoc',
  'guides/common/modules/con_cloning-process-overview.adoc',
  'guides/common/modules/con_cloning-project-server.adoc',
  'guides/common/modules/con_overview-of-usage-metrics-collection-in-project.adoc',
  'guides/common/modules/con_prerequisites-for-cloning.adoc',
  'guides/common/modules/con_updating-disconnected-server.adoc',
  'guides/common/modules/con_usage-metrics-collection-in-project.adoc',
  'guides/common/modules/proc_cloning-to-the-target-server.adoc',
  'guides/common/modules/proc_completing-the-rhel-7-image.adoc',
  'guides/common/modules/proc_disabling-the-collection-of-usage-metrics.adoc',
  'guides/common/modules/proc_exporting-repositories-from-the-connected-project-server.adoc',
  'guides/common/modules/proc_increasing-the-logging-level-for-insights-iop.adoc',
  'guides/common/modules/proc_installing-insights-iop-by-using-export-and-import.adoc',
  'guides/common/modules/proc_installing-insights-iop-with-the-project-context-iso-image.adoc',
  'guides/common/modules/proc_performing-post-cloning-tasks.adoc',
  'guides/common/modules/proc_performing-the-update-of-the-disconnected-project-server.adoc',
  'guides/common/modules/proc_preparing-repositories-on-the-disconnected-project-server.adoc',
  'guides/common/modules/proc_preparing-the-source-server-for-cloning.adoc',
  'guides/common/modules/proc_refreshing-clients-of-insights-iop.adoc',
  'guides/common/modules/proc_reviewing-usage-metrics-collected-from-your-project.adoc',
  'guides/common/modules/proc_synchronizing-the-new-repositories.adoc',
  'guides/common/modules/proc_updating-smart-proxy.adoc',
  'guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc',
  'guides/common/modules/proc_upgrading-container-images-of-insights-iop.adoc',
  'guides/common/modules/proc_upgrading-puppet-agent-7-to-openvox-agent-8.adoc',
  'guides/common/modules/ref_host-requirements-for-custom-rhel-images.adoc',
  'guides/common/modules/ref_preconfigured-rhel-kvm-guest-images.adoc',
  'guides/common/modules/ref_usage-metrics-collected-by-project.adoc',
  'guides/common/modules/snip_openvox-client-repos.adoc',
]

obsolete_exceptions = non_containerized_satellite_content - unused
unused -= non_containerized_satellite_content

if obsolete_exceptions.any?
  puts 'Obsolete unused-module exceptions:'
  puts obsolete_exceptions
  if ENV.key?('GITHUB_ACTIONS')
    message = 'File is included in a configured build and must be removed from the unused-module exceptions'
    obsolete_exceptions.each do |file|
      puts "::error file=#{file}::#{message}"
    end
  end
  exit(1)
end

if unused.any?
  puts unused
  if ENV.key?('GITHUB_ACTIONS')
    unused.each do |file|
      puts "::error file=#{file}::File is unused"
    end
  end
  exit(1)
end
