#!/usr/bin/env ruby

# frozen_string_literal: true

require 'asciidoctor'

BUILDS = %w[
  foreman-el
  foreman-deb
  containerized-katello
  containerized-orcharhino
  katello
  satellite
  orcharhino
].freeze

BASE_DIR = File.dirname(__dir__)

included = Set.new

Dir.glob(File.join(BASE_DIR, '*', 'master.adoc')).each do |path|
  BUILDS.each do |build|
    doc = Asciidoctor.load_file(
      path,
      doctype: :book,
      safe: :safe,
      base_dir: File.dirname(path),
      attributes: { 'build' => build }
    )

    included += doc.catalog[:includes].keys
  end
end

modules = Dir.glob(File.join(BASE_DIR, 'common', 'modules', '**', '*.adoc'))
assemblies = Dir.glob(File.join(BASE_DIR, 'common', 'assembly_*.adoc'))
absolute_included = included.map { |path| File.join(BASE_DIR, "#{path}.adoc") }

doc_root = Pathname.new(File.dirname(BASE_DIR))

unused = ((modules + assemblies) - absolute_included).map do |path|
  Pathname.new(path).relative_path_from(doc_root).to_s
end

# containerized content build isn't published
# https://github.com/theforeman/foreman-documentation/issues/4964
unused.delete('guides/common/modules/snip_allowed-export-paths-prerequisite.adoc')

# Non-containerized Satellite content excluded since satellite build is now containerized-only
# These modules/assemblies are only included for non-containerized satellite builds
non_containerized_satellite_content = [
  'guides/common/modules/con_building-cloud-images-for-project.adoc',
  'guides/common/modules/con_cloning-process-overview.adoc',
  'guides/common/modules/con_cloning-project-server.adoc',
  'guides/common/modules/con_configuring-inter-server-synchronization.adoc',
  'guides/common/modules/con_katello-ca-consumer-rpm-and-rhsm-consumer-script.adoc',
  'guides/common/modules/con_monitoring-hosts-by-using-insights-in-project.adoc',
  'guides/common/modules/con_overview-of-usage-metrics-collection-in-project.adoc',
  'guides/common/modules/con_prerequisites-for-cloning.adoc',
  'guides/common/modules/con_prerequisites-for-using-insights-iop.adoc',
  'guides/common/modules/con_red-hat-offline-knowledge-portal.adoc',
  'guides/common/modules/con_registering-hosts-by-using-the-bootstrap-script.adoc',
  'guides/common/modules/con_supported-client-architectures-for-configuration-management.adoc',
  'guides/common/modules/con_supported-client-architectures-for-content-management.adoc',
  'guides/common/modules/con_supported-client-architectures-for-host-provisioning.adoc',
  'guides/common/modules/con_updating-disconnected-server.adoc',
  'guides/common/modules/con_updating-project-to-next-patch-version.adoc',
  'guides/common/modules/con_usage-metrics-collection-in-project.adoc',
  'guides/common/modules/proc_changing-the-method-the-bootstrap-script-uses-to-download-the-consumer-rpm.adoc',
  'guides/common/modules/proc_cloning-to-the-target-server.adoc',
  'guides/common/modules/proc_completing-the-rhel7-image.adoc',
  'guides/common/modules/proc_configuring-repositories-proxy.adoc',
  'guides/common/modules/proc_configuring-the-base-operating-system-with-offline-repositories.adoc',
  'guides/common/modules/proc_creating-a-domain-for-a-host-during-registration.adoc',
  'guides/common/modules/proc_creating-a-puppet-environment-for-bootstrap-registration.adoc',
  'guides/common/modules/proc_disabling-recommendations-in-project.adoc',
  'guides/common/modules/proc_disabling-subscription-connection-by-using-cli.adoc',
  'guides/common/modules/proc_disabling-subscription-connection-by-using-web-ui.adoc',
  'guides/common/modules/proc_disabling-the-collection-of-usage-metrics.adoc',
  'guides/common/modules/proc_disabling-vulnerability-analysis-on-hosts.adoc',
  'guides/common/modules/proc_downloading-the-binary-dvd-images.adoc',
  'guides/common/modules/proc_enabling-recommendations-in-project.adoc',
  'guides/common/modules/proc_enabling-remote-execution-on-the-host.adoc',
  'guides/common/modules/proc_enabling-vulnerability-analysis-on-hosts.adoc',
  'guides/common/modules/proc_examining-vulnerability-of-hosts.adoc',
  'guides/common/modules/proc_exporting-repositories-from-the-connected-project-server.adoc',
  'guides/common/modules/proc_increasing-the-logging-level-for-insights-iop.adoc',
  'guides/common/modules/proc_installing-from-the-offline-repositories.adoc',
  'guides/common/modules/proc_installing-insights-iop-by-using-export-and-import.adoc',
  'guides/common/modules/proc_installing-insights-iop-with-the-project-context-iso-image.adoc',
  'guides/common/modules/proc_migrating-a-host-from-one-server-to-another-server.adoc',
  'guides/common/modules/proc_migrating-a-host-from-red-hat-network.adoc',
  'guides/common/modules/proc_migrating-from-hosted-to-in-project-insights.adoc',
  'guides/common/modules/proc_migrating-from-in-project-to-hosted-insights.adoc',
  'guides/common/modules/proc_performing-the-update-of-the-disconnected-project-server.adoc',
  'guides/common/modules/proc_post-cloning-tasks.adoc',
  'guides/common/modules/proc_preparing-repositories-on-the-disconnected-project-server.adoc',
  'guides/common/modules/proc_preparing-the-source-server-for-cloning.adoc',
  'guides/common/modules/proc_providing-an-alternative-fqdn-for-the-host.adoc',
  'guides/common/modules/proc_providing-the-hosts-ip-address.adoc',
  'guides/common/modules/proc_refreshing-clients-of-insights-iop.adoc',
  'guides/common/modules/proc_registering-a-host-for-content-management-only.adoc',
  'guides/common/modules/proc_registering-a-host-without-puppet.adoc',
  'guides/common/modules/proc_registering-clients-using-the-bootstrap-script.adoc',
  'guides/common/modules/proc_registering-hosts-by-using-the-bootstrap-script.adoc',
  'guides/common/modules/proc_resolving-package-dependency-errors.adoc',
  'guides/common/modules/proc_reverting-server-to-download-content-from-red-hat-cdn-by-using-cli.adoc',
  'guides/common/modules/proc_reverting-server-to-download-content-from-red-hat-cdn-by-using-web-ui.adoc',
  'guides/common/modules/proc_reviewing-usage-metrics-collected-from-your-project.adoc',
  'guides/common/modules/proc_setting-permissions-for-the-bootstrap-script-by-using-cli.adoc',
  'guides/common/modules/proc_setting-permissions-for-the-bootstrap-script-by-using-web-ui.adoc',
  'guides/common/modules/proc_synchronizing-the-new-repositories.adoc',
  'guides/common/modules/proc_updating-server.adoc',
  'guides/common/modules/proc_updating-smart-proxy.adoc',
  'guides/common/modules/proc_upgrading-a-disconnected-project-server.adoc',
  'guides/common/modules/proc_upgrading-container-images-of-insights-iop.adoc',
  'guides/common/modules/proc_upgrading-puppet-agent-7-to-openvox-agent-8.adoc',
  'guides/common/modules/ref_advanced-bootstrap-script-configuration.adoc',
  'guides/common/modules/ref_host-requirements-for-custom-images.adoc',
  'guides/common/modules/ref_managing-packages-on-the-base-operating-system.adoc',
  'guides/common/modules/ref_preconfigured-rhel-kvm-guest-images.adoc',
  'guides/common/modules/ref_supported-usage-of-project-components.adoc',
  'guides/common/modules/ref_troubleshooting-insights-iop.adoc',
  'guides/common/modules/ref_usage-metrics-collected-by-project.adoc',
  'guides/common/modules/snip_openvox-client-repos.adoc',
  'guides/common/assembly_building-cloud-images-for-project.adoc',
  'guides/common/assembly_cloning-project-server.adoc',
  'guides/common/assembly_configuring-inter-server-synchronization.adoc',
  'guides/common/assembly_installing-satellite-server-disconnected.adoc',
  'guides/common/assembly_monitoring-hosts-by-using-insights-in-project.adoc',
  'guides/common/assembly_updating-satellite.adoc',
  'guides/common/assembly_upgrading-project-disconnected.adoc',
  'guides/common/assembly_usage-metrics-collection-in-project.adoc'
]

non_containerized_satellite_content.each { |file| unused.delete(file) }

if unused.any?
  puts unused
  if ENV.key?('GITHUB_ACTIONS')
    unused.each do |file|
      puts "::error file=#{file}::File is unused"
    end
  end
  exit(1)
end
