:_mod-docs-content-type: REFERENCE

[id="hammer-user-access-token-list"]
= user access-token list

[role="_abstract"]
List all Personal Access Tokens for a user

*Usage*

----
# hammer user access-token <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `--user VALUE` {endash} User`s login to search by
* `--user-id VALUE` {endash} ID of the user
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS     | ALL | DEFAULT | THIN

| Id         | x   | x       | x
| Name       | x   | x       | x
| Active     | x   | x       |
| Expires at | x   | x       |
|===

*Search and order fields*

* `id` {endash} integer
* `name` {endash} string
* `user_id` {endash} integer

:_mod-docs-content-type: REFERENCE

[id="hammer-user-access-token-list"]
= user access-token list

[role="_abstract"]
List all Personal Access Tokens for a user

*Usage*

----
# hammer user access-token <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `--user VALUE` {endash} User`s login to search by
* `--user-id VALUE` {endash} ID of the user
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS     | ALL | DEFAULT | THIN

| Id         | x   | x       | x
| Name       | x   | x       | x
| Active     | x   | x       |
| Expires at | x   | x       |
|===

*Search and order fields*

* `id` {endash} integer
* `name` {endash} string
* `user_id` {endash} integer

