:_mod-docs-content-type: REFERENCE

[id="hammer-capsule-update"]
= capsule update

[role="_abstract"]
Update a Capsule

*Usage*

----
# hammer capsule update [OPTIONS]
----

*Options*

* `--download-policy VALUE` {endash} Download Policy of the capsule, must be one of on_demand, immediate, inherit,
streamed
* `--http-proxy VALUE` {endash} Name to search by
* `--http-proxy-id NUMBER` {endash} Id of the HTTP proxy to use with alternate content sources
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--name VALUE`
* `--new-name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--url VALUE`
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-capsule-update"]
= capsule update

[role="_abstract"]
Update a Capsule

*Usage*

----
# hammer capsule update [OPTIONS]
----

*Options*

* `--download-policy VALUE` {endash} Download Policy of the capsule, must be one of on_demand, immediate, inherit,
streamed
* `--http-proxy VALUE` {endash} Name to search by
* `--http-proxy-id NUMBER` {endash} Id of the HTTP proxy to use with alternate content sources
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--name VALUE`
* `--new-name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--url VALUE`
* `-h`, `--help` {endash} Print help


