:_mod-docs-content-type: REFERENCE

[id="hammer-model-create"]
= model create

[role="_abstract"]
Create a hardware model

*Usage*

----
# hammer model create [OPTIONS]
----

*Options*

* `--hardware-model VALUE`
* `--info VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--vendor-class VALUE`
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-model-create"]
= model create

[role="_abstract"]
Create a hardware model

*Usage*

----
# hammer model create [OPTIONS]
----

*Options*

* `--hardware-model VALUE`
* `--info VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--vendor-class VALUE`
* `-h`, `--help` {endash} Print help


