:_mod-docs-content-type: REFERENCE

[id="hammer-discovery-rule-update"]
= discovery-rule update

[role="_abstract"]
Update a rule

*Usage*

----
# hammer discovery-rule update [OPTIONS]
----

*Options*

* `--enabled BOOLEAN` {endash} Flag is used for temporary shutdown of rules
* `--hostgroup VALUE` {endash} Hostgroup name
* `--hostgroup-id NUMBER` {endash} The hostgroup that is used to auto provision a host
* `--hostgroup-title VALUE` {endash} Hostgroup title
* `--hostname VALUE` {endash} Defines a pattern to assign human-readable hostnames to the matching hosts
* `--hosts-limit VALUE` {endash} Enables to limit maximum amount of provisioned hosts per rule
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} Location ID for provisioned hosts
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--name VALUE` {endash} Represents rule name shown to the users
* `--new-name VALUE` {endash} Represents rule name shown to the users
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} Organization ID for provisioned hosts
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--priority NUMBER` {endash} Puts the rules in order, low numbers go first. Must be greater then zero
* `--search VALUE` {endash} Query to match discovered hosts for the particular rule
* `-h`, `--help` {endash} Print help


