:_mod-docs-content-type: REFERENCE

[id="hammer-template-build-pxe-default"]
= template build-pxe-default

[role="_abstract"]
Update the default PXE menu on all configured TFTP servers

*Usage*

----
# hammer template build-pxe-default [OPTIONS]
----

*Options*

* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-template-build-pxe-default"]
= template build-pxe-default

[role="_abstract"]
Update the default PXE menu on all configured TFTP servers

*Usage*

----
# hammer template build-pxe-default [OPTIONS]
----

*Options*

* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


