:_mod-docs-content-type: REFERENCE

[id="hammer-compute-resource-image-delete"]
= compute-resource image delete

[role="_abstract"]
Delete an image

*Usage*

----
# hammer compute-resource image <delete|destroy> [OPTIONS]
----

*Options*

* `--compute-resource VALUE` {endash} Compute resource name
* `--compute-resource-id VALUE`
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-compute-resource-image-delete"]
= compute-resource image delete

[role="_abstract"]
Delete an image

*Usage*

----
# hammer compute-resource image <delete|destroy> [OPTIONS]
----

*Options*

* `--compute-resource VALUE` {endash} Compute resource name
* `--compute-resource-id VALUE`
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


