:_mod-docs-content-type: REFERENCE

[id="hammer-foreign-input-set-update"]
= foreign-input-set update

[role="_abstract"]
Update a foreign input set

*Usage*

----
# hammer foreign-input-set update [OPTIONS]
----

*Options*

* `--description VALUE` {endash} Input set description
* `--exclude VALUE` {endash} A comma separated list of input names to be included from the foreign template.
* `--id VALUE`
* `--include VALUE` {endash} A comma separated list of input names to be included from the foreign template.
* `--include-all BOOLEAN` {endash} Include all inputs from the foreign template
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--new-name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--target-template-id VALUE` {endash} Target template ID
* `--template-id VALUE`
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-foreign-input-set-update"]
= foreign-input-set update

[role="_abstract"]
Update a foreign input set

*Usage*

----
# hammer foreign-input-set update [OPTIONS]
----

*Options*

* `--description VALUE` {endash} Input set description
* `--exclude VALUE` {endash} A comma separated list of input names to be included from the foreign template.
* `--id VALUE`
* `--include VALUE` {endash} A comma separated list of input names to be included from the foreign template.
* `--include-all BOOLEAN` {endash} Include all inputs from the foreign template
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--new-name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--target-template-id VALUE` {endash} Target template ID
* `--template-id VALUE`
* `-h`, `--help` {endash} Print help


