:_mod-docs-content-type: REFERENCE

[id="hammer-ansible-roles-import"]
= ansible roles import

[role="_abstract"]
DEPRECATED: Import Ansible roles

*Usage*

----
# hammer ansible roles import [OPTIONS]
----

*Options*

* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--proxy-id VALUE` {endash} Capsule to import from
* `--role-names LIST` {endash} Ansible role names to be imported
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-ansible-roles-import"]
= ansible roles import

[role="_abstract"]
DEPRECATED: Import Ansible roles

*Usage*

----
# hammer ansible roles import [OPTIONS]
----

*Options*

* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--proxy-id VALUE` {endash} Capsule to import from
* `--role-names LIST` {endash} Ansible role names to be imported
* `-h`, `--help` {endash} Print help


