:_mod-docs-content-type: REFERENCE

[id="hammer-hostgroup-ansible-roles-assign"]
= hostgroup ansible-roles assign

[role="_abstract"]
Assigns Ansible roles to a hostgroup

*Usage*

----
# hammer hostgroup ansible-roles assign [OPTIONS]
----

*Options*

* `--ansible-role-ids LIST` {endash} Ansible roles to assign to a hostgroup
* `--ansible-roles LIST`
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Hostgroup name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--title VALUE` {endash} Hostgroup title
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-hostgroup-ansible-roles-assign"]
= hostgroup ansible-roles assign

[role="_abstract"]
Assigns Ansible roles to a hostgroup

*Usage*

----
# hammer hostgroup ansible-roles assign [OPTIONS]
----

*Options*

* `--ansible-role-ids LIST` {endash} Ansible roles to assign to a hostgroup
* `--ansible-roles LIST`
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Hostgroup name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--title VALUE` {endash} Hostgroup title
* `-h`, `--help` {endash} Print help


