:_mod-docs-content-type: REFERENCE

[id="hammer-realm-update"]
= realm update

[role="_abstract"]
Update a realm

*Usage*

----
# hammer realm update [OPTIONS]
----

*Options*

* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--name VALUE` {endash} The realm name, e.g. EXAMPLE.COM
* `--new-name VALUE` {endash} The realm name, e.g. EXAMPLE.COM
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--realm-proxy-id NUMBER` {endash} Capsule ID to use within this realm
* `--realm-type VALUE` {endash} Realm type, e.g. Red Hat Identity Management or Active Directory
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-realm-update"]
= realm update

[role="_abstract"]
Update a realm

*Usage*

----
# hammer realm update [OPTIONS]
----

*Options*

* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--name VALUE` {endash} The realm name, e.g. EXAMPLE.COM
* `--new-name VALUE` {endash} The realm name, e.g. EXAMPLE.COM
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--realm-proxy-id NUMBER` {endash} Capsule ID to use within this realm
* `--realm-type VALUE` {endash} Realm type, e.g. Red Hat Identity Management or Active Directory
* `-h`, `--help` {endash} Print help


