:_mod-docs-content-type: REFERENCE

[id="hammer-user-mail-notification-update"]
= user mail-notification update

[role="_abstract"]
Update an email notification for a user

*Usage*

----
# hammer user mail-notification update [OPTIONS]
----

*Options*

* `--interval VALUE` {endash} Mail notification interval option, e.g. Daily, Weekly or Monthly. Required for
summary notification
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--mail-notification VALUE` {endash} Name to search by
* `--mail-notification-id NUMBER`
* `--mail-query VALUE` {endash} Relevant only for audit summary notification
* `--new-name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--subscription VALUE` {endash} Mail notification subscription option, e.g. Subscribe, Subscribe to my hosts or
Subscribe to all hosts. Required for host built and config error state
* `--user VALUE` {endash} User`s login to search by
* `--user-id VALUE`
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-user-mail-notification-update"]
= user mail-notification update

[role="_abstract"]
Update an email notification for a user

*Usage*

----
# hammer user mail-notification update [OPTIONS]
----

*Options*

* `--interval VALUE` {endash} Mail notification interval option, e.g. Daily, Weekly or Monthly. Required for
summary notification
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--mail-notification VALUE` {endash} Name to search by
* `--mail-notification-id NUMBER`
* `--mail-query VALUE` {endash} Relevant only for audit summary notification
* `--new-name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--subscription VALUE` {endash} Mail notification subscription option, e.g. Subscribe, Subscribe to my hosts or
Subscribe to all hosts. Required for host built and config error state
* `--user VALUE` {endash} User`s login to search by
* `--user-id VALUE`
* `-h`, `--help` {endash} Print help


