:_mod-docs-content-type: REFERENCE

[id="hammer-report-template-update"]
= report-template update

[role="_abstract"]
Update a report template

*Usage*

----
# hammer report-template update [OPTIONS]
----

*Options*

* `--audit-comment VALUE`
* `--default BOOLEAN` {endash} Whether or not the template is added automatically to new organizations and
locations
* `--description VALUE`
* `--file FILE` {endash} Path to a file that contains the report template content
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--locked BOOLEAN` {endash} Whether or not the template is locked for editing
* `--name VALUE`
* `--new-name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--snippet BOOLEAN`
* `-h`, `--help` {endash} Print help
* `-i`, `--interactive` {endash} Dump existing template and open it in an $EDITOR. Update with the result


