:_mod-docs-content-type: REFERENCE

[id="hammer-bootdisk-host"]
= bootdisk host

[role="_abstract"]
Download host image

*Usage*

----
# hammer bootdisk host [OPTIONS]
----

*Options*

* `--file VALUE` {endash} File or device to write image to
* `--force` {endash} Force writing to existing destination (device etc.)
* `--full BOOLEAN` {endash} True for full, false for basic reusable image
* `--host VALUE` {endash} Host name
* `--host-id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--sudo` {endash} Use sudo to write to device
* `-h`, `--help` {endash} Print help


