:_mod-docs-content-type: REFERENCE

[id="hammer-host-collection-package-group-remove"]
= host-collection package-group remove

[role="_abstract"]
Not supported. Use the remote execution equivalent `hammer job-invocation create --feature katello_group_remove`. Specify the host collection with the --search-query parameter, e.g. `--search-query "host_collection = MyCollection"` or `--search-query "host_collection_id=6"`

*Usage*

----
# hammer host-collection package-group remove [OPTIONS]
----

*Options*

* `-h`, `--help` {endash} Unsupported Operation - Use the remote execution equivalent `hammer
job-invocation create `--feature` katello_group_remove`. Specify the host
collection with the `--search-query` parameter, e.g. `--search-query
"host_collection = MyCollection"` or `--search-query "host_collection_id=6"`



Unfortunately the server does not support such operation.

:_mod-docs-content-type: REFERENCE

[id="hammer-host-collection-package-group-remove"]
= host-collection package-group remove

[role="_abstract"]
Not supported. Use the remote execution equivalent `hammer job-invocation create --feature katello_group_remove`. Specify the host collection with the --search-query parameter, e.g. `--search-query "host_collection = MyCollection"` or `--search-query "host_collection_id=6"`

*Usage*

----
# hammer host-collection package-group remove [OPTIONS]
----

*Options*

* `-h`, `--help` {endash} Unsupported Operation - Use the remote execution equivalent `hammer
job-invocation create `--feature` katello_group_remove`. Specify the host
collection with the `--search-query` parameter, e.g. `--search-query
"host_collection = MyCollection"` or `--search-query "host_collection_id=6"`



Unfortunately the server does not support such operation.

