:_mod-docs-content-type: REFERENCE

[id="hammer-organization-delete-parameter"]
= organization delete-parameter

[role="_abstract"]
Delete parameter for an organization

*Usage*

----
# hammer organization delete-parameter [OPTIONS]
----

*Options*

* `--name VALUE` {endash} Parameter name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Organization ID
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-organization-delete-parameter"]
= organization delete-parameter

[role="_abstract"]
Delete parameter for an organization

*Usage*

----
# hammer organization delete-parameter [OPTIONS]
----

*Options*

* `--name VALUE` {endash} Parameter name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Organization ID
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


