:_mod-docs-content-type: REFERENCE

[id="hammer-http-proxy-create"]
= http-proxy create

[role="_abstract"]
Create an HTTP proxy

*Usage*

----
# hammer http-proxy create [OPTIONS]
----

*Options*

* `--content-default-http-proxy BOOLEAN` Set this HTTP proxy as the default content HTTP proxy
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--name VALUE` {endash} The HTTP proxy name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--password VALUE` {endash} Password used to authenticate with the HTTP proxy
* `--url VALUE` {endash} URL of the HTTP proxy
* `--username VALUE` {endash} Username used to authenticate with the HTTP proxy
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-http-proxy-create"]
= http-proxy create

[role="_abstract"]
Create an HTTP proxy

*Usage*

----
# hammer http-proxy create [OPTIONS]
----

*Options*

* `--content-default-http-proxy BOOLEAN` Set this HTTP proxy as the default content HTTP proxy
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--name VALUE` {endash} The HTTP proxy name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--password VALUE` {endash} Password used to authenticate with the HTTP proxy
* `--url VALUE` {endash} URL of the HTTP proxy
* `--username VALUE` {endash} Username used to authenticate with the HTTP proxy
* `-h`, `--help` {endash} Print help


