:_mod-docs-content-type: REFERENCE

[id="hammer-template-update"]
= template update

[role="_abstract"]
Update a provisioning template

*Usage*

----
# hammer template update [OPTIONS]
----

*Options*

* `--audit-comment VALUE`
* `--description VALUE`
* `--file FILE` {endash} Path to a file that contains the template
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--locked BOOLEAN` {endash} Whether or not the template is locked for editing
* `--name VALUE` {endash} Template name
* `--new-name VALUE` {endash} Template name
* `--operatingsystem-ids LIST` {endash} Array of operating system IDs to associate with the template
* `--operatingsystems LIST`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--type VALUE` {endash} Template type. Eg. snippet, script, provision
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-template-update"]
= template update

[role="_abstract"]
Update a provisioning template

*Usage*

----
# hammer template update [OPTIONS]
----

*Options*

* `--audit-comment VALUE`
* `--description VALUE`
* `--file FILE` {endash} Path to a file that contains the template
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--locked BOOLEAN` {endash} Whether or not the template is locked for editing
* `--name VALUE` {endash} Template name
* `--new-name VALUE` {endash} Template name
* `--operatingsystem-ids LIST` {endash} Array of operating system IDs to associate with the template
* `--operatingsystems LIST`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--type VALUE` {endash} Template type. Eg. snippet, script, provision
* `-h`, `--help` {endash} Print help


