:_mod-docs-content-type: REFERENCE

[id="hammer-compute-resource-storage-domains"]
= compute-resource storage-domains

[role="_abstract"]
List storage domains for a compute resource

*Usage*

----
# hammer compute-resource storage-domains [OPTIONS]
----

*Options*

* `--cluster-id VALUE` {endash} Cluster ID (Deprecated: Use `--cluster-name` instead)
* `--cluster-name VALUE` {endash} Cluster name or path to search by
* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Compute resource name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--storage-domain VALUE`
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Id     | x   | x       | x
| Name   | x   | x       | x
|===


:_mod-docs-content-type: REFERENCE

[id="hammer-compute-resource-storage-domains"]
= compute-resource storage-domains

[role="_abstract"]
List storage domains for a compute resource

*Usage*

----
# hammer compute-resource storage-domains [OPTIONS]
----

*Options*

* `--cluster-id VALUE` {endash} Cluster ID (Deprecated: Use `--cluster-name` instead)
* `--cluster-name VALUE` {endash} Cluster name or path to search by
* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Compute resource name
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--storage-domain VALUE`
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Id     | x   | x       | x
| Name   | x   | x       | x
|===


