:_mod-docs-content-type: REFERENCE

[id="hammer-virt-who-config-update"]
= virt-who-config update

[role="_abstract"]
Update a virt-who configuration

*Usage*

----
# hammer virt-who-config update [OPTIONS]
----

*Options*

* `--ahv-internal-debug BOOLEAN`  Option Enable debugging output is required to enable AHV internal debug. It
provides extra AHV debug information when both options are enabled
* `--blacklist VALUE` {endash} Hypervisor blacklist, applicable only when filtering mode is set to 2. Wildcards
and regular expressions are supported, multiple records must be separated by
comma.
* `--debug BOOLEAN` {endash} Enable debugging output
* `--exclude-host-parents VALUE`  Applicable only for esx provider type. Hosts which parent (usually
ComputeResource) name is specified in comma-separated list in this option will
NOT be reported. Wildcards and regular expressions are supported, multiple
records must be separated by comma. Put the value into the double-quotes if it
contains special characters like comma. All new line characters will be removed
in resulting configuration file, white spaces are removed from beginning and
end.
* `--filter-host-parents VALUE` {endash} Applicable only for esx provider type. Only hosts which parent (usually
ComputeResource) name is specified in comma-separated list in this option will
be reported. Wildcards and regular expressions are supported, multiple records
must be separated by comma. Put the value into the double-quotes if it contains
special characters like comma. All new line characters will be removed in
resulting configuration file, white spaces are removed from beginning and end.
* `--filtering-mode ENUM` {endash} Hypervisor filtering mode
Possible value(s): `none`, `whitelist`, `blacklist`
* `--http-proxy VALUE` {endash} Name to search by
* `--http-proxy-id NUMBER` {endash} HTTP proxy that should be used for communication between the server on which
virt-who is running and the hypervisors and virtualization managers.
* `--hypervisor-id ENUM` {endash} Specifies how the hypervisor will be identified.
Possible value(s): `hostname`, `uuid`, `hwuuid`
* `--hypervisor-password VALUE` {endash} Hypervisor password, required for all hypervisor types except for
libvirt/kubevirt.
* `--hypervisor-server VALUE` {endash} Fully qualified host name or IP address of the hypervisor
* `--hypervisor-type ENUM` {endash} Hypervisor type
Possible value(s): `esx`, `hyperv`, `libvirt`, `kubevirt`, `ahv`
* `--hypervisor-username VALUE` {endash} Account name by which virt-who is to connect to the hypervisor.
* `--id NUMBER` {endash} Configuration numeric identifier
* `--interval ENUM` {endash} Configuration interval in minutes
Possible value(s): `60`, `120`, `240`, `480`, `720`, `1440`, `2880`, `4320`
* `--kubeconfig-path VALUE` {endash} Configuration file containing details about how to connect to the cluster and
authentication details.
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Configuration name
* `--new-name VALUE` {endash} Configuration name
* `--no-proxy VALUE` {endash} Ignore Proxy. A comma-separated list of hostnames or domains or ip addresses to
ignore Capsule settings for. Optionally this may be set to * to bypass proxy
settings for all hostnames domains or ip addresses.
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--prism-flavor ENUM` {endash} Select the Prism flavor you are connecting to
Possible value(s): `central`, `element`
* `--satellite-url VALUE` {endash} Satellite server FQDN
* `--whitelist VALUE` {endash} Hypervisor whitelist, applicable only when filtering mode is set to 1. Wildcards
and regular expressions are supported, multiple records must be separated by
comma.
* `-h`, `--help` {endash} Print help


