:_mod-docs-content-type: REFERENCE

[id="hammer-host-interface-delete"]
= host interface delete

[role="_abstract"]
Delete a host's interface

*Usage*

----
# hammer host interface <delete|destroy> [OPTIONS]
----

*Options*

* `--host VALUE` {endash} Host name
* `--host-id VALUE` {endash} ID or name of host
* `--id VALUE` {endash} ID of interface
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-host-interface-delete"]
= host interface delete

[role="_abstract"]
Delete a host's interface

*Usage*

----
# hammer host interface <delete|destroy> [OPTIONS]
----

*Options*

* `--host VALUE` {endash} Host name
* `--host-id VALUE` {endash} ID or name of host
* `--id VALUE` {endash} ID of interface
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


