:_mod-docs-content-type: REFERENCE

[id="hammer-import-templates"]
= import-templates

[role="_abstract"]
Import templates from a git repo or a directory on the server

*Usage*

----
# hammer import-templates [OPTIONS]
----

*Options*

* `--associate ENUM` {endash} Associate to OS`s, Locations & Organizations. Options are: always, new or never.
Possible value(s): `always`, `new`, `never`
* `--branch VALUE` {endash} Branch in Git repo.
* `--dirname VALUE` {endash} Directory within Git repo containing the templates.
* `--filter VALUE` {endash} Export templates with names matching this regex (case-insensitive; snippets are
not filtered).
* `--force BOOLEAN` {endash} Update templates that are locked
* `--http-proxy VALUE` {endash} Name to search by
* `--http-proxy-id NUMBER` {endash} ID of an HTTP proxy to use for template sync. Use this parameter together with
``http_proxy_policy`:`selected``
* `--http-proxy-policy ENUM` {endash} HTTP proxy policy for template sync. Use only when synchronizing templates
through the HTTP or the HTTPS protocol. If you choose `selected`, provide the
`http_proxy_id` parameter.
Possible value(s): `global`, `none`, `selected`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-ids LIST` {endash} REPLACE locations with given ids
* `--location-title VALUE` {endash} Set the current location context for the request
* `--location-titles LIST`
* `--locations LIST`
* `--lock ENUM` {endash} Lock imported templates
Possible value(s): `lock`, `keep_lock_new`, `keep`, `unlock`, `true`, `false`,
`0`, `1`
* `--negate BOOLEAN` {endash} Negate the prefix (for purging).
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-ids LIST` {endash} REPLACE organizations with given ids.
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--organization-titles LIST`
* `--organizations LIST`
* `--prefix VALUE` {endash} The string all imported templates should begin with.
* `--repo VALUE` {endash} Override the default repo from settings.
* `--verbose BOOLEAN` {endash} Show template diff in response
* `-h`, `--help` {endash} Print help


