:_mod-docs-content-type: REFERENCE

[id="hammer-scap-content-list"]
= scap-content list

[role="_abstract"]
List SCAP contents

*Usage*

----
# hammer scap-content <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Id     | x   | x       | x
| Title  | x   | x       | x
| Digest | x   | x       |
|===

*Search and order fields*

* `created_at` {endash} datetime
* `filename` {endash} string
* `location` {endash} string
* `location_id` {endash} integer
* `organization` {endash} string
* `organization_id` {endash} integer
* `title` {endash} string

