:_mod-docs-content-type: REFERENCE

[id="hammer-capsule-content-synchronize"]
= capsule content synchronize

[role="_abstract"]
Synchronize the content to the Capsule

*Usage*

----
# hammer capsule content synchronize [OPTIONS]
----

*Options*

* `--async` {endash} Do not wait for the task
* `--content-view VALUE` {endash} Content view name to search by
* `--content-view-id NUMBER` {endash} Id of the content view to limit the synchronization on
* `--environment VALUE` {endash} Lifecycle environment name to search by (--environment is deprecated: Use
* `--lifecycle-environment` instead)
* `--environment-id NUMBER` {endash} (--environment-id is deprecated: Use `--lifecycle-environment-id` instead)
* `--id NUMBER` {endash} Id of the Capsule
* `--lifecycle-environment VALUE` {endash} Lifecycle environment name to search by
* `--lifecycle-environment-id NUMBER` Id of the environment to limit the synchronization on
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Organization name
* `--organization-id VALUE` {endash} Organization ID
* `--repository VALUE` {endash} Repository name to search by
* `--repository-id NUMBER` {endash} Id of the repository to limit the synchronization on
* `--skip-metadata-check BOOLEAN` {endash} Skip metadata check on each repository on the Capsule
* `-h`, `--help` {endash} Print help


