:_mod-docs-content-type: REFERENCE

[id="hammer-report-template-export"]
= report-template export

[role="_abstract"]
Export a report template to ERB

*Usage*

----
# hammer report-template export [OPTIONS]
----

*Options*

* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--path VALUE` {endash} Path to directory where downloaded content will be saved
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-report-template-export"]
= report-template export

[role="_abstract"]
Export a report template to ERB

*Usage*

----
# hammer report-template export [OPTIONS]
----

*Options*

* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--path VALUE` {endash} Path to directory where downloaded content will be saved
* `-h`, `--help` {endash} Print help


