:_mod-docs-content-type: REFERENCE

[id="hammer-user-registration-tokens-invalidate"]
= user registration-tokens invalidate

[role="_abstract"]
Invalidate all registration tokens for a specific user

*Usage*

----
# hammer user registration-tokens invalidate [OPTIONS]
----

*Options*

* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--user VALUE` {endash} User`s login to search by
* `--user-id VALUE` {endash} ID of the user
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-user-registration-tokens-invalidate"]
= user registration-tokens invalidate

[role="_abstract"]
Invalidate all registration tokens for a specific user

*Usage*

----
# hammer user registration-tokens invalidate [OPTIONS]
----

*Options*

* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--user VALUE` {endash} User`s login to search by
* `--user-id VALUE` {endash} ID of the user
* `-h`, `--help` {endash} Print help


