:_mod-docs-content-type: REFERENCE

[id="hammer-capsule-list"]
= capsule list

[role="_abstract"]
List all Capsules

*Usage*

----
# hammer capsule <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--include-status BOOLEAN` {endash} Flag to indicate whether to include status or not
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Scope by locations
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Scope by organizations
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS   | ALL | DEFAULT | THIN

| Id       | x   | x       | x
| Name     | x   | x       | x
| Status   | x   | x       |
| Url      | x   | x       |
| Features | x   | x       |
|===

*Search and order fields*

* `feature` {endash} string
* `id` {endash} integer
* `location` {endash} string
* `location_id` {endash} integer
* `name` {endash} string
* `organization` {endash} string
* `organization_id` {endash} integer
* `url` {endash} string

