:_mod-docs-content-type: REFERENCE

[id="hammer-content-view-component-update"]
= content-view component update

[role="_abstract"]
Update a component associated with the content view

*Usage*

----
# hammer content-view component update [OPTIONS]
----

*Options*

* `--component-content-view VALUE` {endash} Content View name of the component who`s latest version is desired
* `--component-content-view-id VALUE` {endash} Content View identifier of the component who`s latest version is desired
* `--component-content-view-version VALUE` {endash} Content View Version number of the component. Either use this or
* `--component-content-view-version-id` option
* `--component-content-view-version-id VALUE` Content View Version identifier of the component
* `--composite-content-view VALUE` {endash} Name of the composite content view
* `--composite-content-view-id NUMBER` {endash} Composite content view identifier
* `--id NUMBER` {endash} Content view component ID. Identifier of the component association
* `--latest` {endash} Select the latest version of the components content view is desired
* `--organization VALUE` {endash} Organization name to search by
* `--organization-id VALUE` {endash} Organization ID to search by
* `--organization-label VALUE` {endash} Organization label to search by
* `--organization-title VALUE` {endash} Organization title to search by
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-content-view-component-update"]
= content-view component update

[role="_abstract"]
Update a component associated with the content view

*Usage*

----
# hammer content-view component update [OPTIONS]
----

*Options*

* `--component-content-view VALUE` {endash} Content View name of the component who`s latest version is desired
* `--component-content-view-id VALUE` {endash} Content View identifier of the component who`s latest version is desired
* `--component-content-view-version VALUE` {endash} Content View Version number of the component. Either use this or
* `--component-content-view-version-id` option
* `--component-content-view-version-id VALUE` Content View Version identifier of the component
* `--composite-content-view VALUE` {endash} Name of the composite content view
* `--composite-content-view-id NUMBER` {endash} Composite content view identifier
* `--id NUMBER` {endash} Content view component ID. Identifier of the component association
* `--latest` {endash} Select the latest version of the components content view is desired
* `--organization VALUE` {endash} Organization name to search by
* `--organization-id VALUE` {endash} Organization ID to search by
* `--organization-label VALUE` {endash} Organization label to search by
* `--organization-title VALUE` {endash} Organization title to search by
* `-h`, `--help` {endash} Print help


