:_mod-docs-content-type: REFERENCE

[id="hammer-compute-resource-image-available"]
= compute-resource image available

[role="_abstract"]
Show images available for addition

*Usage*

----
# hammer compute-resource image available [OPTIONS]
----

*Options*

* `--compute-resource VALUE` {endash} Compute resource name
* `--compute-resource-id VALUE`
* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Name   | x   | x       | x
| Uuid   | x   | x       |
|===


