:_mod-docs-content-type: REFERENCE

[id="hammer-ansible-roles-play-hosts"]
= ansible roles play-hosts

[role="_abstract"]
Runs all Ansible roles on hosts

*Usage*

----
# hammer ansible roles play-hosts [OPTIONS]
----

*Options*

* `--host-ids LIST` {endash} IDs of hosts to play roles on
* `--hosts LIST`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-ansible-roles-play-hosts"]
= ansible roles play-hosts

[role="_abstract"]
Runs all Ansible roles on hosts

*Usage*

----
# hammer ansible roles play-hosts [OPTIONS]
----

*Options*

* `--host-ids LIST` {endash} IDs of hosts to play roles on
* `--hosts LIST`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help


