:_mod-docs-content-type: REFERENCE

[id="hammer-user-table-preference-update"]
= user table-preference update

[role="_abstract"]
Updates a table preference for a given table

*Usage*

----
# hammer user table-preference update [OPTIONS]
----

*Options*

* `--columns LIST` {endash} List of user selected columns
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name of the table
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--user VALUE` {endash} User`s login to search by
* `--user-id VALUE` {endash} ID of the user
* `-h`, `--help` {endash} Print help


