:_mod-docs-content-type: REFERENCE

[id="hammer-webhook-template-list"]
= webhook-template list

[role="_abstract"]
List webhook templates

*Usage*

----
# hammer webhook-template <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Id     | x   | x       | x
| Name   | x   | x       | x
|===

*Search and order fields*

* `default` {endash} Values: true, false
* `location` {endash} string
* `location_id` {endash} integer
* `locked` {endash} Values: true, false
* `name` {endash} string
* `organization` {endash} string
* `organization_id` {endash} integer
* `snippet` {endash} Values: true, false
* `template` {endash} text

:_mod-docs-content-type: REFERENCE

[id="hammer-webhook-template-list"]
= webhook-template list

[role="_abstract"]
List webhook templates

*Usage*

----
# hammer webhook-template <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Id     | x   | x       | x
| Name   | x   | x       | x
|===

*Search and order fields*

* `default` {endash} Values: true, false
* `location` {endash} string
* `location_id` {endash} integer
* `locked` {endash} Values: true, false
* `name` {endash} string
* `organization` {endash} string
* `organization_id` {endash} integer
* `snippet` {endash} Values: true, false
* `template` {endash} text

