:_mod-docs-content-type: REFERENCE

[id="hammer-filter-info"]
= filter info

[role="_abstract"]
Show a filter

*Usage*

----
# hammer filter <info|show> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS         | ALL | DEFAULT | THIN

| Id             | x   | x       | x
| Resource type  | x   | x       |
| Search         | x   | x       |
| Unlimited?     | x   | x       |
| Override?      | x   | x       |
| Role           | x   | x       |
| Permissions    | x   | x       |
| Locations/     | x   | x       |
| Organizations/ | x   | x       |
| Created at     | x   | x       |
| Updated at     | x   | x       |
|===


