:_mod-docs-content-type: REFERENCE

[id="hammer-capsule-content-verify-checksum"]
= capsule content verify-checksum

[role="_abstract"]
Check for missing or corrupted artifacts, and attempt to redownload them.

*Usage*

----
# hammer capsule content verify-checksum [OPTIONS]
----

*Options*

* `--async` {endash} Do not wait for the task
* `--content-view VALUE` {endash} Content view name to search by
* `--content-view-id NUMBER` {endash} Id of the content view to limit verifying checksum on
* `--environment VALUE` {endash} Lifecycle environment name to search by (--environment is deprecated: Use
* `--lifecycle-environment` instead)
* `--environment-id NUMBER` {endash} (--environment-id is deprecated: Use `--lifecycle-environment-id` instead)
* `--id NUMBER` {endash} Id of the Capsule
* `--lifecycle-environment VALUE` {endash} Lifecycle environment name to search by
* `--lifecycle-environment-id NUMBER` Id of the environment to limit verifying checksum on
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Organization name
* `--organization-id VALUE` {endash} Organization ID
* `--repository VALUE` {endash} Repository name to search by
* `--repository-id NUMBER` {endash} Id of the repository to limit verifying checksum on
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-capsule-content-verify-checksum"]
= capsule content verify-checksum

[role="_abstract"]
Check for missing or corrupted artifacts, and attempt to redownload them.

*Usage*

----
# hammer capsule content verify-checksum [OPTIONS]
----

*Options*

* `--async` {endash} Do not wait for the task
* `--content-view VALUE` {endash} Content view name to search by
* `--content-view-id NUMBER` {endash} Id of the content view to limit verifying checksum on
* `--environment VALUE` {endash} Lifecycle environment name to search by (--environment is deprecated: Use
* `--lifecycle-environment` instead)
* `--environment-id NUMBER` {endash} (--environment-id is deprecated: Use `--lifecycle-environment-id` instead)
* `--id NUMBER` {endash} Id of the Capsule
* `--lifecycle-environment VALUE` {endash} Lifecycle environment name to search by
* `--lifecycle-environment-id NUMBER` Id of the environment to limit verifying checksum on
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Organization name
* `--organization-id VALUE` {endash} Organization ID
* `--repository VALUE` {endash} Repository name to search by
* `--repository-id NUMBER` {endash} Id of the repository to limit verifying checksum on
* `-h`, `--help` {endash} Print help


