:_mod-docs-content-type: REFERENCE

[id="hammer-role-filters"]
= role filters

[role="_abstract"]
List all filters

*Usage*

----
# hammer role filters [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE` {endash} User role id
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} User role name
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS        | ALL | DEFAULT | THIN

| Id            | x   | x       | x
| Resource type | x   | x       |
| Search        | x   | x       |
| Unlimited?    | x   | x       |
| Override?     | x   | x       |
| Role          | x   | x       |
| Permissions   | x   | x       |
|===


