:_mod-docs-content-type: REFERENCE

[id="hammer-config-group-list"]
= config-group list

[role="_abstract"]
List of config groups

*Usage*

----
# hammer config-group <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Id     | x   | x       | x
| Name   | x   | x       | x
|===

*Search and order fields*

* `name` {endash} string
* `puppetclass` {endash} string

:_mod-docs-content-type: REFERENCE

[id="hammer-config-group-list"]
= config-group list

[role="_abstract"]
List of config groups

*Usage*

----
# hammer config-group <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS | ALL | DEFAULT | THIN

| Id     | x   | x       | x
| Name   | x   | x       | x
|===

*Search and order fields*

* `name` {endash} string
* `puppetclass` {endash} string

