:_mod-docs-content-type: REFERENCE

[id="hammer-job-template-dump"]
= job-template dump

[role="_abstract"]
View job template content

*Usage*

----
# hammer job-template dump [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS
|===


:_mod-docs-content-type: REFERENCE

[id="hammer-job-template-dump"]
= job-template dump

[role="_abstract"]
View job template content

*Usage*

----
# hammer job-template dump [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS
|===


