:_mod-docs-content-type: REFERENCE

[id="hammer-content-export-generate-listing"]
= content-export generate-listing

[role="_abstract"]
Generates listing file on each directory of a syncable export. This command only needs to be used if the export was performed asynchronously or if the listing files were lost. Assumes the syncable export directory is accessible on disk

*Usage*

----
# hammer content-export generate-listing [OPTIONS]
----

*Options*

* `--id VALUE` {endash} Generate listing files based on specified export history
* `--task-id VALUE` {endash} Generate listing files for a syncable export task
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-content-export-generate-listing"]
= content-export generate-listing

[role="_abstract"]
Generates listing file on each directory of a syncable export. This command only needs to be used if the export was performed asynchronously or if the listing files were lost. Assumes the syncable export directory is accessible on disk

*Usage*

----
# hammer content-export generate-listing [OPTIONS]
----

*Options*

* `--id VALUE` {endash} Generate listing files based on specified export history
* `--task-id VALUE` {endash} Generate listing files for a syncable export task
* `-h`, `--help` {endash} Print help


