:_mod-docs-content-type: REFERENCE

[id="hammer-content-view-version-incremental-update"]
= content-view version incremental-update

[role="_abstract"]
Perform an Incremental Update on one or more Content View Versions

*Usage*

----
# hammer content-view version incremental-update [OPTIONS]
----

*Options*

* `--async` {endash} Do not wait for the task
* `--content-view-version VALUE` {endash} Content view version number
* `--content-view-version-id NUMBER` {endash} Content View Version Ids to perform an incremental update on.  May contain
composites as well as one or more components to update.
* `--deb-ids LIST` {endash} Deb Package ids to copy into the new versions
* `--debs LIST`
* `--description VALUE` {endash} The description for the new generated Content View Versions
* `--errata-ids LIST` {endash} Errata ids to copy into the new versions
* `--host-ids LIST` {endash} IDs of hosts to update
* `--lifecycle-environment-ids LIST` {endash} List of lifecycle environment IDs to update the content view version in
* `--lifecycle-environments LIST` {endash} List of lifecycle environment names to update the content view version in
* `--organization VALUE` {endash} Organization name for resolving lifecycle environment names
* `--organization-id VALUE` {endash} Organization id for resolving lifecycle environment names
* `--package-ids LIST` {endash} Package ids to copy into the new versions
* `--packages LIST`
* `--propagate-all-composites BOOLEAN` If true, will publish a new composite version using any specified
content_view_version_id that has been promoted to a lifecycle environment
* `--resolve-dependencies BOOLEAN` {endash} If true, when adding the specified errata or packages, any needed dependencies
will be copied as well. Defaults to true
* `--update-all-hosts BOOLEAN` {endash} Update all editable and applicable hosts within the specified Content View and                                                    Lifecycle Environments
* `-h`, `--help` {endash} Print help


:_mod-docs-content-type: REFERENCE

[id="hammer-content-view-version-incremental-update"]
= content-view version incremental-update

[role="_abstract"]
Perform an Incremental Update on one or more Content View Versions

*Usage*

----
# hammer content-view version incremental-update [OPTIONS]
----

*Options*

* `--async` {endash} Do not wait for the task
* `--content-view-version VALUE` {endash} Content view version number
* `--content-view-version-id NUMBER` {endash} Content View Version Ids to perform an incremental update on.  May contain
composites as well as one or more components to update.
* `--deb-ids LIST` {endash} Deb Package ids to copy into the new versions
* `--debs LIST`
* `--description VALUE` {endash} The description for the new generated Content View Versions
* `--errata-ids LIST` {endash} Errata ids to copy into the new versions
* `--host-ids LIST` {endash} IDs of hosts to update
* `--lifecycle-environment-ids LIST` {endash} List of lifecycle environment IDs to update the content view version in
* `--lifecycle-environments LIST` {endash} List of lifecycle environment names to update the content view version in
* `--organization VALUE` {endash} Organization name for resolving lifecycle environment names
* `--organization-id VALUE` {endash} Organization id for resolving lifecycle environment names
* `--package-ids LIST` {endash} Package ids to copy into the new versions
* `--packages LIST`
* `--propagate-all-composites BOOLEAN` If true, will publish a new composite version using any specified
content_view_version_id that has been promoted to a lifecycle environment
* `--resolve-dependencies BOOLEAN` {endash} If true, when adding the specified errata or packages, any needed dependencies
will be copied as well. Defaults to true
* `--update-all-hosts BOOLEAN` {endash} Update all editable and applicable hosts within the specified Content View and                                                    Lifecycle Environments
* `-h`, `--help` {endash} Print help


