:_mod-docs-content-type: REFERENCE

[id="hammer-content-export-incremental-library"]
= content-export incremental library

[role="_abstract"]
Performs an incremental export of the organization's library environment

*Usage*

----
# hammer content-export incremental library [OPTIONS]
----

*Options*

* `--async` {endash} Do not wait for the task
* `--chunk-size-gb NUMBER` {endash} Split the exported content into archives no greater than the specified size in
gigabytes.
* `--destination-server VALUE` {endash} Destination Server name
* `--fail-on-missing-content` {endash} Fails if any of the repositories belonging to this organization are
unexportable.
* `--format ENUM` {endash} Export formats.Choose syncable if the exported content needs to be in a yum
format. This option is only available for yum, file repositories. Choose
importable if the importing server uses the same version  and exported content
needs to be one of yum, file, ansible_collection, docker, deb repositories.
Possible value(s): `syncable`, `importable`
* `--from-history-id NUMBER` {endash} Export history identifier used for incremental export. If not provided the most
recent export history will be used.
* `--organization VALUE` {endash} Organization name to search by
* `--organization-id NUMBER` {endash} Organization identifier
* `--organization-label VALUE` {endash} Organization label to search by
* `--organization-title VALUE` {endash} Organization title
* `-h`, `--help` {endash} Print help


