:_mod-docs-content-type: REFERENCE

[id="hammer-job-template-list"]
= job-template list

[role="_abstract"]
List job templates

*Usage*

----
# hammer job-template <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Scope by locations
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Scope by organizations
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS       | ALL | DEFAULT | THIN

| Id           | x   | x       | x
| Name         | x   | x       | x
| Job category | x   | x       |
| Provider     | x   | x       |
| Type         | x   | x       |
|===


:_mod-docs-content-type: REFERENCE

[id="hammer-job-template-list"]
= job-template list

[role="_abstract"]
List job templates

*Usage*

----
# hammer job-template <list|index> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Scope by locations
* `--location-title VALUE` {endash} Set the current location context for the request
* `--order VALUE` {endash} Sort and order by a searchable field, e.g. `<field> DESC`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Scope by organizations
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--search VALUE` {endash} Filter results
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS       | ALL | DEFAULT | THIN

| Id           | x   | x       | x
| Name         | x   | x       | x
| Job category | x   | x       |
| Provider     | x   | x       |
| Type         | x   | x       |
|===


