:_mod-docs-content-type: REFERENCE

[id="hammer-mail-notification-info"]
= mail-notification info

[role="_abstract"]
Show an email notification

*Usage*

----
# hammer mail-notification <info|show> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE` {endash} Numerical ID or email notification name
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS            | ALL | DEFAULT | THIN

| Id                | x   | x       | x
| Name              | x   | x       | x
| Description       | x   | x       |
| Subscription type | x   | x       |
|===


:_mod-docs-content-type: REFERENCE

[id="hammer-mail-notification-info"]
= mail-notification info

[role="_abstract"]
Show an email notification

*Usage*

----
# hammer mail-notification <info|show> [OPTIONS]
----

*Options*

* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--id VALUE` {endash} Numerical ID or email notification name
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--name VALUE` {endash} Name to search by
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS            | ALL | DEFAULT | THIN

| Id                | x   | x       | x
| Name              | x   | x       | x
| Description       | x   | x       |
| Subscription type | x   | x       |
|===


