:_mod-docs-content-type: REFERENCE

[id="hammer-host-interface-list"]
= host interface list

[role="_abstract"]
List all interfaces for host

*Usage*

----
# hammer host interface <list|index> [OPTIONS]
----

*Options*

* `--domain VALUE` {endash} Domain name
* `--domain-id VALUE` {endash} ID or name of domain
* `--fields LIST` {endash} Show specified fields or predefined field sets only. (See below)
* `--host VALUE` {endash} Host name
* `--host-id VALUE` {endash} ID or name of host
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--page NUMBER` {endash} Page number, starting at 1
* `--per-page VALUE` {endash} Number of results per page to return, `all` to return all results
* `--subnet VALUE` {endash} Subnet name
* `--subnet-id VALUE` {endash} ID or name of subnet
* `-h`, `--help` {endash} Print help

*Predefined field sets*

|===
| FIELDS      | ALL | DEFAULT | THIN

| Id          | x   | x       | x
| Identifier  | x   | x       |
| Type        | x   | x       |
| Mac address | x   | x       |
| Ip address  | x   | x       |
| Dns name    | x   | x       |
|===


