:_mod-docs-content-type: REFERENCE

[id="hammer-os-create"]
= os create

[role="_abstract"]
Create an operating system

*Usage*

----
# hammer os create [OPTIONS]
----

*Options*

* `--architecture-ids LIST` {endash} IDs of associated architectures
* `--architectures LIST`
* `--description VALUE`
* `--family VALUE`
* `--location VALUE` {endash} Set the current location context for the request
* `--location-id NUMBER` {endash} Set the current location context for the request
* `--location-title VALUE` {endash} Set the current location context for the request
* `--major VALUE`
* `--media LIST`
* `--medium-ids LIST` {endash} IDs of associated media
* `--minor VALUE`
* `--name VALUE`
* `--organization VALUE` {endash} Set the current organization context for the request
* `--organization-id NUMBER` {endash} Set the current organization context for the request
* `--organization-title VALUE` {endash} Set the current organization context for the request
* `--os-parameters-attributes SCHEMA` Array of parameters
* `--partition-table-ids LIST` {endash} IDs of associated partition tables
* `--partition-tables LIST`
* `--password-hash ENUM` {endash} Root password hash function to use
Possible value(s): `SHA512`, `SHA256`, `Base64`, `Base64-Windows`, `MD5`
* `--provisioning-template-ids LIST`  IDs of associated provisioning templates
* `--provisioning-templates LIST`
* `--release-name VALUE`
* `-h`, `--help` {endash} Print help

Following parameters accept format defined by its schema (bold are required; <> contains acceptable type; [] contains acceptable value):

* `--os-parameters-attributes`  "*name*=<string>,*value*=<string>, ... "

