---
name: linkchecker

on:
  pull_request:
    branches:
      - master
      - "[0-9]+.[0-9]+"
env:
  RUBY_VERSION: 3.1
  BUNDLE_WITHOUT: "nanoc"
  MAKE_J: 3

jobs:
  check-html:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: guides
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install linkchecker
        run: |
          sudo apt-get update
          sudo apt-get install linkchecker -y

      - name: Clean the environment
        run: make clean

      - name: Build HTML with local links
        run: |
          make -j ${{ env.MAKE_J }} html BUILD=foreman-el LINKS=LOCAL
          make -j ${{ env.MAKE_J }} html BUILD=foreman-deb LINKS=LOCAL
          make -j ${{ env.MAKE_J }} html BUILD=katello LINKS=LOCAL
          make -j ${{ env.MAKE_J }} html BUILD=satellite LINKS=LOCAL
          make -j ${{ env.MAKE_J }} html BUILD=orcharhino LINKS=LOCAL

      - name: Check HTML links of all builds
        run: |
          make linkchecker-tryer

  theme-link-check:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
        working-directory: guides
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Build satellite docs
        run: |
          bundle exec make -j ${{ env.MAKE_J }} html BUILD=satellite LINKS=local

      - name: Extract TOC
        run: |
          mkdir -p build/ci-toc
          bundle exec ruby scripts/extract_links_toc \
              --f2l upstream_filename_to_satellite_link.json \
              --output-toc-file build/ci-toc/toc.json \
              --output-aliases-file build/ci-toc/aliases.json \
              build/**/index-satellite.html

      - name: Stage documentation TOC for CI artifact
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/toc-artifact"
          cp build/ci-toc/toc.json build/ci-toc/aliases.json "${GITHUB_WORKSPACE}/toc-artifact/"

      - name: Upload documentation TOC
        uses: actions/upload-artifact@v7
        with:
          name: documentation-toc
          path: toc-artifact
          if-no-files-found: error

  foreman-theme-satellite-plugin:
    needs: theme-link-check
    # TODO
    # uses: theforeman/foreman_theme_satellite/.github/workflows/toc-check.yml@develop
    uses: adamruzicka/foreman_theme_satellite/.github/workflows/toc-check.yml@ci
    secrets: inherit
    with:
      documentation_toc_artifact: documentation-toc
