[[Managing_Container_Images_with_Content_Views]]
=== Managing Container Images in Satellite

To manage container images with Content Views, complete the following steps:

. In the Satellite web UI, navigate to *Content* > *Content Views* and click *Create New View*.
. In the *Name* field, enter `Containers`. This automatically populates the *Label* field.
. In the *Description* field, enter a description. For example, `Container image for Red Hat Enterprise Linux 7`.
. If you want to use a Composite Content View to hold other Content Views, select the *Composite View* check box.
. Optional: If you select *Composite Content View*, you can select whether you want to Auto publish a composite view when a new version of a component Content View is created.
. Click *Save* to create the Content View.
. Navigate to the *Docker Content* subtab, then click *Add*.
. Select the container repository for a Red Hat Enterprise Linux 7 Server image.
. Click *Add Repository*.
. Navigate to *Versions* and click *Publish New Version*.

You can enter a *Description* for the version; meaningful descriptions can help in logging new content versions.

Satellite Server creates the new version of the view and publishes it to the Library environment.

You can also click *Promote* to promote this Content View across environments in the application life cycle.

.For CLI Users

. To obtain a list of repository IDs:
+
[options="nowrap" subs="+quotes"]
----
# hammer repository list --organization "_My_Organization_"
----
+
. Create the Content View and add the repository:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view create \
--name "Containers" \
--description "Container image for Red Hat Enterprise Linux 7" \
--repository-ids 8 \
--organization "_My_Organization_"
----
+
. Publish the view:
+
[options="nowrap" subs="+quotes"]
----
# hammer content-view publish \
--name "Containers" \
--description "Initial Content View for our container image" \
--organization "_My_Organization_"
----
