#!/usr/bin/env python3

import json
from pathlib import Path

versions = Path(__file__).parent / 'content' / 'js' / 'versions.js'
data = json.loads(versions.read_text().removeprefix('const navVersions = '))

for version in data:
    for build in version['builds']:
        for guide in build['guides']:
            print('/'.join([version['path'], guide['path'], build['filename']]))
