[id='pcp-metrics_{context}']
= PCP Metrics

Metrics are stored in a tree-like structure. For example, all network metrics are stored in a node named `network`. Each metric may be a single value, or a list of values, known as instances. For example, kernel load has three instances, a 1-minute, 5-minute, and 15-minute average.

For every metric entry, PCP stores both its data and metadata. This includes the metrics description, data type, units, and dimensions. For example, the metadata enables PCP to output multiple metrics with different dimensions.

The value of a counter metric only increases. For example, a count of disk write operations on a specific device only increases. When you query the value of a counter metric, PCP converts this into a rate value by default.

In addition to system metrics such as CPU, memory, kernel, XFS, disk, and network, the following metrics are configured:

[%header,cols=2*]
|===
|Metric
|Description

|hotproc.*
|Basic metrics of key Satellite processes

|apache.*
|Apache HTTP Server metrics

|postgresql.*
|Basic PostgreSQL statistics

|statsd.fm_rails_*
|Satellite metrics
|===
