[id='configuring-grafana-dashboard_{context}']
= Configuring Grafana dashboard

This procedure describes how to setup initial dashboard and add new metrics from {Project} Server.

.Procedure

Grafana comes with few dashboards available which gives a good starting point for building more complex dashboards.

. Click on Dashboards - Manage in the left menu.
. Find the _PCP Redist Host Overview_ item in the General listing of dashboards.
. Select desired host on the top query from the drop down: _{foreman.example.com}_.
+
Note that the last minute in all graphs is catching up slower if the dashboard is set to refresh more quickly than in one minute intervals. This is expected, by default the pmlogger is set to sample data at minute intervals and pmproxy takes few moments to process the data. When more recent data than one minute must be monitored, change the resolution interval to 30, 10 or even 1 second. To compensate missing information, set _Now delay now_ to "1m" in dashboard settings.
+

To add PostgreSQL metrics into the dashboard:
. Click on Add panel icon in the top menu.
. Click on Add query button.
. Type _postgresql.stat.database.tup_fetched_ into the query field.
. Choose General from the left picker.
. Insert Title for the graph.
. To return back to the dashboard, click on the top-left back button.

The following PostgreSQL metrics are available by default:

* postgresql.stat.database.tup_deleted
* postgresql.stat.database.tup_updated
* postgresql.stat.database.tup_inserted
* postgresql.stat.database.tup_fetched
* postgresql.stat.database.tup_returned

Individual databases (foreman, candlepin) are stored as instances, to display only one instance on the graph use syntax _postgresql.stat.database.tup_returned{instance.name=="foreman"}_. For more information about query syntax for PCP Redis data source, read pmseries manual page.